### ISSUE TITLE
Update Archiving SOP to include Exporting steps

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#100]
The current SOP for archiving doesn't include the exporter -https://docs.google.com/document/d/1S4fyCSqB3nLrCUssNMwSp6ff8tmeipMi_slnXW2Lrq4/edit?ts=5ef49b5f#heading=h.n3qy5yl0auvs

Could we please update this to reflect both how not to accidentally export to GCP at the moment, but also how we would do in the future as part of the overall process once the DCP is up and running.

Could we also have a "data export for MVP section" I imagine this would look like all datasets have been submitted to archives and accessioned but not yet exported and all curated datasets in draft (I think, as won't have been archived) and then what do we do and how do we know when they get to GCP.

**Comment by lauraclarke** [comment]
@clairerye this might be a good part of the dry run on the development side and then it can be iterated on during following operational steps
