### ISSUE TITLE
Transcriptomic diversity of cell types across the adult human brain

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1002]
### Associated files

* Google Drive:

### Published study links

* Paper: https://doi.org/10.1101/2022.10.12.511898

* Accessioned data:

* Ingest Link: https://contribute.data.humancellatlas.org/projects/detail?uuid=f8888f5a-4a19-41d0-ad96-4fafce8a8e79

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
this is the same paper as ticket #1013 - I think we can close this one and I'll keep working on the original ticket
