### ISSUE TITLE
E-MTAB-9841 - Transcriptional changes in the mammary gland during lactation revealed by single cell sequencing of cells from human milk

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1004]
### Associated files

* Google Drive:

### Published study links

* Paper: https://www.nature.com/articles/s41467-021-27895-0#Abs1

* Accessioned data:

Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=e956e66a-ac8e-483a-963a-0f92c7e5abfb&tab=project

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Started new ticket for this project #1023 for compliance with the onboarding tasks #1014 .
