### ISSUE TITLE
Yoshiaki Sunami - pancreatic cancer and pancreatitis 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1005]
### Associated files:

* Google Drive:
Ingest link: https://contribute.data.humancellatlas.org/projects/detail?uuid=c0ae1320-ef09-450a-af61-d8c02227ede8&tab=experiment-info

### Key Events

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [ ] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by Wkt8** [comment]
No information available yet. Sent the questionnaire and T&Cs form. Asked if they needed archiving or if they had any specific deadlines.

**Comment by Wkt8** [comment]
They have completed the questionnaire and terms and conditions form. No response to archiving or time-urgency.

**Comment by Wkt8** [comment]
No analysis files available. Sequence files are managed access under EGAS00001005889 but no access (maybe not public yet?) 

Have emailed Dr. Yoshiaki Sunami for analysis files.

**Comment by ESapenaVentura** [comment]
@Wkt8 to email again when capacity allows

**Comment by ofanobilbao** [comment]
@Wkt8 to email once again and if no response, close the ticket and mark it as stalled in Ingest

**Comment by Wkt8** [comment]
Emailed again.
