### ISSUE TITLE
Fill out your HCA meetings and training attendance June 2021 to November 2022

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1009]
As part of the reporting for the funder on the old DCP award, we will need to report on people's attendance to meetings or training. For all those who joined before June 2021 this should not come as big news, as we have done this every year.

There is a spreadsheet tab that was created with the purpose of not having to do this retroactively but as they took place. But I don't know how accurate or complete that is.

Now there is a **Deadline** for this: **21st January**

Make sure that you have filled out everything you attended (including link to any posters or presentations) on the [Spreadsheet](https://docs.google.com/spreadsheets/d/1-y7QNoIdwYdFHVxJUc5XWcQuuv6VYhvPLpt9Ls2PK7M/edit#gid=38920295) on the tabs for meetings and "Training & Others".

Once you're happy with the information you have provided on that spreadsheet, please, tick your name on this ticket

- [x] Gabs

- [x] Amnon

- [x] Enrique

- [x] Wei

- [x] Ida

- [x] Alexie

Please, feel free to add anyone else I might have forgotten. I will deal with both myself and Tony separately as we will be working on the reporting together

**Comment by MightyAx** [comment]
Done (No Training for me)

**Comment by ESapenaVentura** [comment]
I have added my attendance to the meetings -

Also, since this should be everything from Jun 1st 2021, I have added all the events I could find in my calendar from that point in time. 

Let me know if anything else is needed

**Comment by gabsie** [comment]
OK - done, @ofanobilbao
