### ISSUE TITLE
Contributor - FetalEmbryonicBrain

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1012]
### Project short name:
FetalEmbryonicBrain

### Primary Wrangler:
Ida

### Secondary Wrangler:
TBD

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1XYHQRZNTrAAfpHUb_ubWHXC2nomEa8gu)

### Published study links

* Paper: https://www.biorxiv.org/content/10.1101/2022.10.24.513487v1

* Accessioned data: 
EGAS00001004107
 cell count data available --> https://github.com/linnarsson-lab/developing-human-brain/

* Ingest project: https://contribute.data.humancellatlas.org/projects/detail?uuid=cbd2911f-252b-4428-abde-69e270aefdfc

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
We were contacted by thee contributor, however we can only wrangle what is in the public domain for this dataset

**Comment by idazucchi** [comment]
The organ part are very specific neuroantomic/developmental terms, I'm sending a copy of the ontology annotation to confirm with the authors if I selected the best term. [(thread)](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/UjaU2KrxU6M/m/QVOwdvFaBwAJ)

**Comment by idazucchi** [comment]
Graph valid - ready for secondary review!

**Comment by Wkt8** [comment]
Looks great! Nice job on creating individual specimens for each of the regions of sampling. 

Two things: 
Cell_Suspension
Could add "retrieved cell number" to the estimated cell count of cell suspensions? 

Analysis_File
Cell count in the total processed matrix file is: 1665937

**Comment by idazucchi** [comment]
Applied the comments, graph-valid and exported!

- [ ] import form

**Comment by idazucchi** [comment]
should we get in touch to say it's live even if they got in touch to get their publication into the DCP?
