### ISSUE TITLE
EGAS00001002171 - Single-cell transcriptomes from human kidneys reveal the cellular identity of renal tumors

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1032]
EGAS00001002171 - Single-cell transcriptomes from human kidneys reveal the cellular identity of renal tumors

### Project short name:
Haniffa-Human-10x3pv2

### Primary Wrangler:
Wei
### Secondary Wrangler:
Ida

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=d8ae869c-39c2-4cdd-b3fc-2d0d8f60e7b8&tab=project

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1m8h7hljfAweMHiEJan4zExn26pcXktn2

### Published study links

* Paper: https://doi.org/10.1126/science.aat1699

* Accessioned data: EGAS00001002171

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Wrangled and in graph-validating. Will need a secondary review!

**Comment by Wkt8** [comment]
Already in cellxgene: see https://cellxgene.cziscience.com/collections/125eef58-0f61-4963-9b08-53e851ab65fb

**Comment by Wkt8** [comment]
Completed changes, resubmitted, graphvalidated, now in exporting. 

Still needs to complete the product import form after export is confirmed.

**Comment by Wkt8** [comment]
Exported! Product import form completed.

**Comment by ofanobilbao** [comment]
@Wkt8 could you, please, review in the browser so that R26 can go Live? Thanks

**Comment by Wkt8** [comment]
Verified! Note to myself to update this (very low priority) to change corresponding contributor emails.

**Comment by Wkt8** [comment]
- [ ] Change corresponding contributors
- [ ] Re-export
- [ ] Submit Import Form

**Comment by Wkt8** [comment]
Completed.
