### ISSUE TITLE
SurveyHumanGlomerulonephritis

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1033]
### Project short name:
SurveyHumanGlomerulonephritis

### Primary Wrangler:
Ida

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=0057c36c-06ce-4cdf-bff4-533ad13f090c&tab=project

### Associated files

* Google Drive:

### Published study links

* Paper: [A single-cell survey of the human glomerulonephritis](https://doi.org/10.1111/jcmm.16407)

* Accessioned data: On demand from authors

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Data is available on demand form the authors --> I sent an email to ask for anonymised cell count matrices [(thread)](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/1de-wbWvqdg)
If they don't reply to our request we should get in touch with Peng and discuss this

**Comment by idazucchi** [comment]
I've emailed the authors about available data, I'm closing the ticket now. This can be re-opened if the authors reply

**Comment by idazucchi** [comment]
I've emailed the authors about available data, I'm closing the ticket now. This can be re-opened if the authors reply
