### ISSUE TITLE
Pathogen-induced tissue-resident memory TH17 (TRM17) cells amplify autoimmune kidney disease

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1034]
### Project short name:
PathogenInducedResidentMemory

### Primary Wrangler:
Ida
### Secondary Wrangler:
Enrique

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=dc0b65b0-7713-46f0-a339-0b03ea786046&tab=project

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1m_nVVXqa0nixcc6ZtidOuB88moUfU-9a)

### Published study links

* Paper: **Core data**  [Pathogen-induced tissue-resident memory TH17 (TRM17) cells amplify autoimmune kidney disease](https://doi.org/10.1126/sciimmunol.aba4163)

* Accessioned data: 
   - raw available upon request from authors
   - cell count in [figshare](https://figshare.com/s/7912de1afc7fd5bbefd4)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Donor info
>Because biopsies from individuals without kidney diseases were not available, we used tissue from the healthy parts of kidneys after tumor nephrectomy (table S1). We identified 5905 cells and 16,148 genes from three renal samples

Renal biopsies from patients with active ANCA-GN were further studied by scRNA-seq and CITE-seq. To this end, 6829 cells and 15,360 genes from six samples could be analyzed (table S2)
need the adjacent_disease field

**Comment by idazucchi** [comment]
I've sent an email to ask for more information on the specimens and how to match specimens and analysis files

**Comment by idazucchi** [comment]
I wrangled the human samples, but I need linking information to match the donors and their samples from the count matrices.
There are 3 count matrices which might be mouse but it's unclear what samples they belong to

To do:
- [ ] wrangle mouse?
- [ ] ontology script
- [ ] hca-util area
- [ ] validate
- [ ] IGV

**Comment by ESapenaVentura** [comment]
The dataset looks good, just a couple super super minor comments:

### Project
- Where did you get the cell count from? The sum of the cell counts from the matrix and from the project seems different
- Contributors - from the project role field, the ontology and ontology_label are missing

### Collection Protocol
- Name of the protocol (Nephrectomy) is misspelled
