### ISSUE TITLE
GSE159115 - RenalTumorMicroenvironment

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1036]
### Project short name:
RenalTumorMicroenvironment

### Primary Wrangler:
Ida

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=7c599029-7a3c-4b5c-8e79-e72c9a9a65fe&tab=project

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1cHVkvGQhCYwnV33WYcgRKjdAfkSwWV5Z?usp=share_link)

### Published study links

* Paper: **Core data** [Single-cell analyses of renal cell cancers reveal insights into tumor microenvironment, cell of origin, and therapy response](https://doi.org/10.1073/pnas.2103240118)

* Accessioned data: [GSE159115](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE159115)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Samples
>we performed comprehensive genomic profiling of dissociated tissues by scRNA-seq on a cohort of RCCs and benign adjacent kidney tissues (14 samples from nine patients)

issues
- [ ] check S1_21561 --> how is it spelled in the metadata files?
- [ ] wrong order in GEO, metadata looks swapped, check count files + metadata --> email?
GSM4819728 	SI_19704
GSM4819729 	SI_19703

**Comment by idazucchi** [comment]
I've sent an email to confirm the details above ([thread](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/dp-W6StxPbg))
the submission was stuck on `graph validation requested` so I asked Wei to validate it locally

```
(ingest-graph-validator) wteh@C02DM256ML85 renaltumor % ingest-graph-validator hydrate xls RenalTumorMicroenvironment_ontologies.xlsx
23-03-22 12:16:03 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
23-03-22 12:16:03 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
23-03-22 12:16:07 [ingest_graph_validator.hydrators.hydrator] - INFO: started xls hydrator for file [RenalTumorMicroenvironment_ontologies.xlsx]
23-03-22 12:16:50 [ingest_graph_validator.utils] - INFO: [import_spreadsheet] took [42825] ms
[]
<class 'ingest.importer.submission.EntityMap'>
23-03-22 12:16:50 [ingest_graph_validator.hydrators.hydrator] - INFO: imported 106 nodes
23-03-22 12:16:50 [ingest_graph_validator.hydrators.hydrator] - INFO: imported 482 edges
23-03-22 12:16:54 [ingest_graph_validator.hydrators.hydrator] - INFO: hydration finished
(ingest-graph-validator) wteh@C02DM256ML85 renaltumor % ingest-graph-validator action test /Users/wteh/PycharmProjects/ingest-graph-validator/graph_test_set
23-03-22 12:17:21 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
23-03-22 12:17:21 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
23-03-22 12:17:21 [ingest_graph_validator.actions.test_action] - INFO: loading tests
23-03-22 12:17:21 [ingest_graph_validator.actions.test_action] - INFO: loaded [15] test queries
23-03-22 12:17:21 [ingest_graph_validator.actions.test_action] - INFO: running tests
23-03-22 12:17:23 [ingest_graph_validator.actions.test_action] - INFO: all tests finished 
```

It's ready for secondary review!

**Comment by arschat** [comment]
Secondary review

Looks very good to me.
Well done!

**Comment by idazucchi** [comment]
the export is done (see [here](https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/641ae093eb5f263368b4d51e/exportJobs)) but the submission status didn't update correctly because the state tracker was being redeployed

I'm filling out the import form

**Comment by idazucchi** [comment]
**Update needed**
The authors confirmed :
- [ ] donor SS_2014 has ccRCC and only donated healthy tissues
- [ ] SI_19704 (Normal)
- [ ] SI_19703 (Tumor)

They are sending data for cellxgene

**Comment by idazucchi** [comment]
this dataset was left out of R26 - need to fill out the import form as a new dataset rather than an update

**Comment by idazucchi** [comment]
**Cellxgene**
Files for cellxgene are in the drive folder.
The metadata is scattered across different files:
- `.rds` : raw/processed counts, tsne, sample id, cell type as a code
- `.csv` : annotation files with the full name for the cell types, the normal one should have all cell types
- `.h5` : has gene ENSEMBL IDs

**Comment by idazucchi** [comment]
I've done the update and filled out the import form for R27

**Comment by arschat** [comment]
published in CxG
[https://cellxgene.cziscience.com/collections/1df8c90d-d299-4b2e-a54d-a5a80f36e780](https://cellxgene.cziscience.com/collections/1df8c90d-d299-4b2e-a54d-a5a80f36e780)
