### ISSUE TITLE
phs001457.v1.p1 - TubularCellLupusNephritis

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1037]
### Project short name:
TubularCellLupusNephritis

### Primary Wrangler:
Ida
### Secondary Wrangler:
@Wkt8 

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=97fca723-d9e9-4263-9f67-335416086f47&tab=project

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1Kk7T_6OYpiXso0tvRXPle-kkF3M-Y_1g)

### Published study links

* Paper: [Tubular cell and keratinocyte single-cell transcriptomics applied to lupus nephritis reveal type I IFN and fibrosis relevant pathways](https://doi.org/10.1038/s41590-019-0386-1)
* Accessioned data: phs001457.v1.p1
* Analysis files [Immport](https://www.immport.org/browser/?path=SDY997%2FResultFiles%2FRNA_sequencing_result)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
The paper and the metadata table mentions 8 blood samples, but there are no cell counts available for them so I've excluded them from the dataset

**Comment by idazucchi** [comment]
this is a large dataset and the graph validation is failing --> [ops ticket](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/gh/ebi-ait/hca-ebi-wrangler-central/1061)

**Comment by idazucchi** [comment]
passed graph validation locally, still need to update the status in ingest but it's ready for secondary review!

**Comment by Wkt8** [comment]
Secondary Review:
Donor_Organism: Donors with Ethnicity.Text = Black have Ontology ID and Ontology Label empty. We should add Ethnicity Ontology ID and Ethnicity Ontology Label Ontology ID for African-American from HANCESTRO

Good job!

**Comment by idazucchi** [comment]
I've edited the spreadsheet but the dataset is stuck in graph validating and I can't update the project
I ned dev help to:
1. put the project back to metadata valid
2. put the projet to graph valid once I've done the update - the project gets stuck due to its size but passed graph validation locally

**Comment by idazucchi** [comment]
I've added the missing ontology terms
This needs to be moved to graph valid by a dev since the graph validation gets stuck in ingest

Something weird with the biomaterials:
submission: 19293 
spreadsheet: 19293
api: 19293
project, metadata tab: 19317

I'd like to make sure there are no extra biomaterials in the submission before we export

**Comment by idazucchi** [comment]
I've followed Amnon's suggestion: I deleted the submission and re-uploaded the spreadsheet

**Comment by idazucchi** [comment]
Project is graph valid - currently waiting for ebi-ait/dcp-ingest-central#926 to be in production before trying to export
This project has ~19.000 biomaterials and ~19.000 links so it will likely fail spreadsheet generation due to the large `linkingMap`

**Comment by idazucchi** [comment]
Exporting for R27

**Comment by arschat** [comment]
Check if exported @Wkt8

**Comment by Wkt8** [comment]
Did not export - needs re-exporting

**Comment by ofanobilbao** [comment]
Amnon still has not found the cause. He will detach investigation from the release and this dataset. Export seems fine in his local computer. @amnonkhen to export it and let @idazucchi know when it's ready to submit import form

**Comment by idazucchi** [comment]
this is not on Dave's tracker - we can check more recent kidney lists but if not on any list can we close the ticket?

**Comment by arschat** [comment]
In [Lucia's kidney tracking](https://docs.google.com/spreadsheets/d/16nOKb9lnPXqbmpS6M-s1dU9wJrQ6rYzupw0Z_R2mbLI/edit?gid=0#gid=0) list, `Der et al.` is marked as 
**HCA dataset:** `N`
**Status:** `restricted access`

I think its safe to close this ticket.

**Comment by arschat** [comment]
Moving submission to graph valid state and close ticket.
