### ISSUE TITLE
GSE160048 - Single-cell RNA sequencing reveals the mesangial identity and species diversity of glomerular cell transcriptomes

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1038]
### Project short name:
Patrakka-Human-Smartseq2

### Primary Wrangler:
Wei

### Secondary Wrangler:
Ida

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=662157e4-ba53-4766-975a-ac11920f153e&tab=project

### Associated files

* Google Drive:

### Published study links

* Paper: **Included data** [Single-cell RNA sequencing reveals the mesangial identity and species diversity of glomerular cell transcriptomes](https://doi.org/10.1038/s41467-021-22331-9)

* Accessioned data: [GSE160048](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE160048)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Note to Wei: check project tabs! add yourself as curator!

**Comment by Wkt8** [comment]
Emailed Dr Patrakka to ask about linking between the GEO samples and the analysis files - maybe an open question here about the efficacy of modelling Smart-Seq 2 in so many cells?

**Comment by ofanobilbao** [comment]
@Wkt8 to chase once more, and if no response close the ticket and mark it as stalled in ingest

**Comment by Wkt8** [comment]
Emailed again.

**Comment by arschat** [comment]
Not in tracker, not in bionetwork tracking sheet, closing ticket.
