### ISSUE TITLE
Feedback to team on Festival of Genomics

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1039]
Enrique and Wei went to the Festival of Genomics and Biodata on 25th - 26th January, 2023. It would be valuable to feedback their insights and interactions with the community. 

**Acceptance criteria for the task:**
- [ ] Create a powerpoint presentation or slide deck to present at an AIT team meeting or smaller HCA meeting 
- [ ] Present findings to the team

**Comment by ESapenaVentura** [comment]
Moved back to (?) - People who attended still need to come up with slides/key takeaways

**Comment by Wkt8** [comment]
See initial slides here: https://docs.google.com/presentation/d/1jlWV1dhO1Fr3v6N6y_h0JMBnMpXHlbgkUoQWry_tipg/edit#slide=id.g1dce940c273_0_0

**Comment by gabsie** [comment]
D Yuan included people to discuss the presentation. 10 mins each maybe.
