### ISSUE TITLE
Fix R24 Import errors

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1041]
(started on [slack #dcp-ops](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1675332168656049))
>Below are the staging areas that we are seeing fail validation, and the errors we are receiving: 
crc32c Assertion Errors -- We ran into this issue with `e0c74c7a-20a4-4505-9cf1-38dcdd23011b` last release with file `prod/e0c74c7a-20a4-4505-9cf1-38dcdd23011b/data/GSE117211_KidneyMicroOrganoids_metadata_02-09-2022.xlsx` and you all were able to work your magic. 

This release, we're seeing this same issue with the following:

## crc32c assertion errors

- `e88714c2-2e78-49da-8146-5a60b50628b4` - [staging](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/e88714c2-2e78-49da-8146-5a60b50628b4/data?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22Name%2520contains_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22xlsx_5C_22_22_2C_22i_22_3A_22displayName_22%257D%255D%22))&authuser=3&prefix=&forceOnObjectsSortingFiltering=true)
  - `data/atlasOfTestisAging_metadata_05-12-2022.xlsx`
  - `data/atlasOfTestisAging_metadata_06-12-2022.xlsx`
  - Delete Old versions:
      - [x] links
      - [x] metadata
      - [x] descriptor
      - [x] data file
- `cd9d6360-ce38-4321-97df-f13c79e3cb84` - [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=cd9d6360-ce38-4321-97df-f13c79e3cb84) [staging](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/cd9d6360-ce38-4321-97df-f13c79e3cb84/data?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=3&prefix=&forceOnObjectsSortingFiltering=false)
  - data/SchulteSchrepping2020_metadata_26-01-2023.xlsx
  - Delete Old versions:
      - [x] links
      - [x] metadata
      - [x] descriptor
      - [x] data file
- `2d4d89f2-ebeb-467c-ae60-a3efc5e8d4ba` -
  - data/COVID19autoimmunityPBMCs_metadata_30-01-2023.xlsx
  - Delete Old versions:
      - [x] links
      - [x] metadata
      - [x] descriptor
      - [x] data file
- `6e60a555-fd95-4aa2-8e29-3ec2ef01a580` - [staging](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/6e60a555-fd95-4aa2-8e29-3ec2ef01a580?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=3&prefix=&forceOnObjectsSortingFiltering=false)
  - `data/atlasOfHumanEndometrialStromalCells_metadata_10-01-2023.xlsx`
  - Delete Old versions:
      - [x] links
      - [x] metadata
      - [x] descriptor
      - [x] data file

## JSON Schema Validation Errors 

- `cc95ff89-2e68-4a08-a234-480eca21ce79` - We ran into this issue last release with  where schema validation was failing due to finding "schema_major_version" and "schema_minor_version" in the provenance property object, which doesn't align with `https://schema.humancellatlas.org/system/1.0.3/provenance` schema.
- `2043c65a-1cf8-4828-a656-9e247d4e64f1` - This is seen in a number of files, with one example being `metadata/process/ffef693e-2202-41de-860f-14b5531d421a_2022-11-08T11:50:00.209000Z.json`

**Comment by ESapenaVentura** [comment]
https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/gh/ebi-ait/hca-ebi-wrangler-central/988

**Comment by arschat** [comment]
@MightyAx @amnonkhen look into the spreadsheet errors. Maybe remove these datasets since @ESapenaVentura is off?

**Comment by arschat** [comment]
@MightyAx @amnonkhen look into the spreadsheet errors. Maybe remove these datasets since @ESapenaVentura is off?

**Comment by amnonkhen** [comment]
*Regarding the crc errors:*
All files mentioned are old versions of the metadata spreadsheet and should therefor not be imported. I believed they are not linked to anything. If the importer cannot ignore them, they should simple be deleted.

**Comment by amnonkhen** [comment]
I went over the xlsx files mentioned in the ticket with regards to the crc error and deleted them.

**Comment by MightyAx** [comment]
A question for Nate:
When importing files on the staging environment that occur multiple times with various DCP versions.
Is each version processed, or only the latest version?

We are assuming that versions where a later version exists are not processed, but it would seem in this case that they can throw errors.

**Comment by MightyAx** [comment]
> I went over the xlsx files mentioned in the ticket with regards to the crc error and deleted them.

I don't understand, did you delete:

1. The excel files?
2. the file descriptors?
3. The metadata files?
4. The link files?

I don't think deleting the excel files will help, I think you need to delete the old versions of the descriptor, metadata and link files.
Or you have to delete everything!

**Comment by MightyAx** [comment]
Nates Response:

> To Alexie’s question, for the purposes of validation, I believe the importer will look at everything in the staging area. When we go to run the actual import, the existence of multiple versions of a file will be reconciled

> I don’t think the validator has any concept of “old versions” when it is run. The logic to sort that out comes in subsequent pipelines we run

**Comment by amnonkhen** [comment]
**crc errors** were fixed by deleting the older files and metadata from the stagig areas.

**regarding 2 datasets with “schema version errors”,** it seems like those are real problems:
cc95ff89-2e68-4a08-a234-480eca21ce79 - was in the import form even though export did not finish
2043c65a-1cf8-4828-a656-9e247d4e64f1 - maybe went through some manual tinkering that cause incorrect schema links to appear.
I recommend to exclude those two from R24 scope.

**Comment by idazucchi** [comment]
are the crc projects imported? is the issue resolved?

@ESapenaVentura to check with Nate which projects were imported and which excluded

**Comment by idazucchi** [comment]
check with Nate if there is a timeline for the changes in the importer validation - will this happen before release 25?
- [ ] investigate project `cc95ff89-2e68-4a08-a234-480eca21ce79` was it really exported?

**Comment by amnonkhen** [comment]
Follow a conversation with Nate, we decided that he will send EBI the list of import errors so that we understand what they are and investigate what is causing them.
If they are related to old versions of files in the staging area, the simplest course of action would be to cleanly re-export those projects:
1. rename the staging area to `_uuid_-ignore`
2. trigger a re-export (set status to graphValidating and export)
3. notify Nate after the successful re-export
4. after a successful import, delete the backup directories from step 1

**Comment by ESapenaVentura** [comment]
Steps

Go into wrangling status board
Immune cell atlas status
Old submission is graph validating
New submission is “submitted”
Submission we want to re-export: https://contribute.data.humancellatlas.org/submissions/detail?uuid=28ff3c1c-08e9-4e27-833f-04a521e24487&project=cc95ff89-2e68-4a08-a234-480eca21ce79
All files are in bucket: aws s3 ls s3://org-hca-data-archive-upload-prod/28ff3c1c-08e9-4e27-833f-04a521e24487/ | wc -l
125 days
Only 1 submission
Submission we want to re-export: https://contribute.data.humancellatlas.org/submissions/detail?uuid=0948a727-228f-4cfc-857e-6243c6aed08d&project=2043c65a-1cf8-4828-a656-9e247d4e64f1
DCP1 dataset; we don’t have the files. We need to re-export this with “METADATA ONLY” flag, then delete metadata/sequence_files, links/, descriptors/

**Comment by ESapenaVentura** [comment]
So, currently, the solutions look like this:

### Move current staging areas new location
```
gsutil -m mv gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/* gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1-ignore/
gsutil -m mv gs://broad-dsp-monster-hca-prod-ebi-storage/prod/cc95ff89-2e68-4a08-a234-480eca21ce79/* gs://broad-dsp-monster-hca-prod-ebi-storage/prod/cc95ff89-2e68-4a08-a234-480eca21ce79-ignore/
``` 

### Set up submission
**Immune cell atlas**
- Set old submission to exported (Not graph valid)
- Set new submission to graph valid (or metadata valid, then graph validate - Has been validated in the past, so there shouldn't be issues)
- Export new submission with data

**125 days**
- Set submission back to graph valid
- Export with metadata only flag
- Delete All file-related metadata
```
gsutil -m rm -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/data/
gsutil -m rm -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/links/
gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/descriptors/
gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/metadata/sequence_file
gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/metadata/supplementary_file/
```

There may be issues with the spreadsheets generated. Definitively not for n2; special attention to that one. If we want the spreadsheet to be pushed we need to run a more careful version of `gsutil rm`

**Comment by amnonkhen** [comment]
Please [see my comment regarding the "125 days" datsaet](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/992#issuecomment-1437053408). There is no need for the "surgical" deletions. We can simply delete the staging area and reexport the dataset. The data files have already been imported to the data browser.

**Comment by amnonkhen** [comment]
Project [c95ff89-2e68-4a08-a234-480eca21ce79](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc95ff89-2e68-4a08-a234-480eca21ce79) has 2 submissions, so creating a spreadsheet for it is not currently supported.

**Comment by ESapenaVentura** [comment]
125 days has been resolved

**Comment by amnonkhen** [comment]
waiting for R25 import

**Comment by amnonkhen** [comment]
waiting for R25 import
