### ISSUE TITLE
Wrangle project for MorPhiC

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1044]
**Description of the task**
With the goal in mind to set up metadata standards for MorPhiC projects, I have wrangled a dataset (Subset of data) and came out with a metadata repository.

Dataset and slides: https://drive.google.com/drive/folders/1XEB3BWk-cWgSOpN4e88hODCENrbE9Crw
Metadata repository: https://github.com/morphic-bio/metadata-schema

Old actions:
- [x] Decide dataset to wrangle
- [x] Update ticket accordingly

AI:
- [x] Dataset has been wrangled
- [x] Presented in MorPhiC DWG (Data Working Group)
- [x] Set up meetings with DPCs to further discuss (Present with spreadheet)

**Comment by arschat** [comment]
@gabsie help select dataset.

**Comment by ESapenaVentura** [comment]
@ESapenaVentura selected a dataset - To update ticket

**Comment by gabsie** [comment]
Presentation on HCA metadata schema with relation to Morphic done for the meeting today
