### ISSUE TITLE
Index of SOPs for wrangler use

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1045]
**Description of the task:**

As a data wrangler, I would like to have access to an SOP index so that I can easily check the documentation or note down if we are missing information

Potential categories:

- Wrangler procedures (Triage to wrangling)
- Metadata schema
- Tools to assist wrangling
   - hca-util
   - wrangler scripts
   - dev scripts

**Acceptance criteria for the task:**

**Comment by ESapenaVentura** [comment]
@arschat to comment here with list of potential categories

**Comment by arschat** [comment]
SOPs from the [wrangler central docs](https://ebi-ait.github.io/hca-ebi-wrangler-central/) and some other resources (with link if not in in wrangler central docs)

# SOPs
## Introductory
ebi-wrangler-onboarding.md
dataset_wrangling_SOP.md
[HCA metadata structure](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md)
secondary_review_SOP.md
## Triage
GDPR_Guidelines.md
dataset_acknowledgement_SOP.md
dataset_suitability_SOP.md
dataset_triage_SOP.md
## Metadata SpreadSheet
HCA_Metadata_Spreadsheet_Guide_Wranglers.md
wrangling_best_practices.md
[Contributor spreadsheet quick guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html)
[Spreadsheets examples](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-templates.html)
geo_to_hca_SOP.md
## Access data files
Globus_data_how_to.md
NCBI_SRA_cold_storage_how_to.md
Node_data_how_to.md
## Contact contributors
contributor_communication_SOP.md
contributor_matrix_addition_SOP.md
## After export
archiving_SOP.md
data_retraction_SOP.md
update_a_project_SOP.md
update_ena_runs_SOP.md
hca_to_scea_tools_SOP.md
## Update schema/ ontology
request_ontology_terms.md
schema_update_prioritisation_SOP.md
updating_zooma.md
## Advanced / Other
cloud_cost_SOP.md
[Programmatic submission](https://ebi-ait.github.io/ingest-programmatic-submissions/)
# Tools
-- handy_snippets.md
## Download 
Downloading 10x files from archives -- rename to `Download bam files and convert to fastq` ?
Downloading and converting SRA objects from SRA
Uploading files to an s3 bucket from the archives
hca cli commands
[hca-util admin](https://github.com/ebi-ait/hca-documentation/wiki/How-to-administrate-upload-areas-and-transfer-data-using-hca-util)
[hca-util contributor](https://ebi-ait.github.io/hca-metadata-community/contributing/uploading-data.html)
## Usefull commands / utilities
Use terminal sessions in EC2: tmux, screen
Transfer files between local machine and EC2: scp, rsync
Transfer files between local and EC2: Cyberduck
git commands
Converting markdown to pdf: grip
Converting yaml to csv: generic_yaml2csv.py
setup_public_folder_own_cloud.md
Validating files on the ec2: fastq_info
[ingest API token \w bookmarklet](https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/api_token.html)
## To be decided 
Generating submission summary report: generate_summary.py
Extract all text to ontology mappings from one or more submissions in ingest
Converting JSON schema properties to csv: json_fields_to_csv.py
cypher query snippets to help inspect metadata visually -- needs gcp credentials, no access (yet?)

**Comment by idazucchi** [comment]
the index looks great like this! I have just two comments
1. contributor_matrix_addition_SOP looks outdated, maybe we need to discuss removing it
2. the items in the tbd section are part of the snippets, although there is no unifying theme it's good to have a place to collect them and keep them on hand - could the snippet page stay the way it is now? maybe changing the order of the snippets within the page to group them a bit more?

**Comment by arschat** [comment]
Added SOP for accessing terra, split Tools into 4 groups, include links to relevant SOPs & tools .

# SOPs
## Introduction
ebi-wrangler-onboarding.md
dataset_wrangling_SOP.md
[HCA metadata structure](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md)
secondary_review_SOP.md
[Accessing terra](https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html)
## Triage
GDPR_Guidelines.md
dataset_acknowledgement_SOP.md
dataset_suitability_SOP.md
dataset_triage_SOP.md
## Metadata SpreadSheet
HCA_Metadata_Spreadsheet_Guide_Wranglers.md
wrangling_best_practices.md
[Contributor spreadsheet quick guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html)
[Spreadsheets examples](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-templates.html)
geo_to_hca_SOP.md
## Access data files
(link to Tools - Downloading from archive)
Globus_data_how_to.md
NCBI_SRA_cold_storage_how_to.md
Node_data_how_to.md
## Contact contributors
contributor_communication_SOP.md
~~contributor_matrix_addition_SOP.md~~ **-- outdated, maybe removing?**
## After export
archiving_SOP.md
data_retraction_SOP.md
update_a_project_SOP.md
update_ena_runs_SOP.md
hca_to_scea_tools_SOP.md
## Update schema/ ontology
request_ontology_terms.md
schema_update_prioritisation_SOP.md
updating_zooma.md
## Advanced / Other
cloud_cost_SOP.md
[Programmatic submission](https://ebi-ait.github.io/ingest-programmatic-submissions/)
# Tools
## Download from archives
Downloading 10x files from archives **-- rename to _Download bam files and convert to fastq_ ?**
Downloading and converting SRA objects from SRA
Uploading files to an s3 bucket from the archives
## Accessing upload-area & ingest production s3 bucket
hca cli commands
[hca-util admin](https://github.com/ebi-ait/hca-documentation/wiki/How-to-administrate-upload-areas-and-transfer-data-using-hca-util)
[hca-util contributor](https://ebi-ait.github.io/hca-metadata-community/contributing/uploading-data.html)
## Useful commands
Use terminal sessions in EC2: tmux, screen
Transfer files between local machine and EC2: scp, rsync
Transfer files between local and EC2: Cyberduck
git commands
Converting markdown to pdf: grip
## Useful script
Converting yaml to csv: generic_yaml2csv.py
setup_public_folder_own_cloud.md
Validating files on the ec2: fastq_info **mention [check_fastq.py script](https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/src/check_fastq.py)**
[ingest API token \w bookmarklet](https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/api_token.html)
Generating submission summary report: generate_summary.py
Extract all text to ontology mappings from one or more submissions in ingest
Converting JSON schema properties to csv: json_fields_to_csv.py
cypher query snippets to help inspect metadata visually **-- needs gcp credentials, no access (yet?)**

**Comment by gabsie** [comment]
@arschat will update today

**Comment by Wkt8** [comment]
Wranglers to review the PR above

**Comment by ESapenaVentura** [comment]
Re-reviewed
