### ISSUE TITLE
Auto-import curation

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1046]
**Description of the task:**
Curate the following projects in ingest

- [x] [R-SPONDIN2 mesenchymal cells form the bud tip progenitor niche during human lung development](https://contribute.data.humancellatlas.org/projects/detail?uuid=de90dae4-0f0f-4918-98a1-b1477ed5efdd)
- [x] [The pulmonary vasculature in lethal COVID-19 and idiopathic pulmonary fibrosis at single-cell resolution](https://contribute.data.humancellatlas.org/projects/detail?uuid=5a97202c-fa5a-4786-9217-80d357374e16)
- [x] [Single cell atlas identifies lipid-processing and immunomodulatory endothelial cells in healthy and malignant breast](https://contribute.data.humancellatlas.org/projects/detail?uuid=25e08db1-0a3b-4176-b791-509f6a749266)
- [x] [Quantification of extracellular proteins, protein complexes and mRNAs in single cells by proximity sequencing](https://contribute.data.humancellatlas.org/projects/detail?uuid=3bbc329d-f3a6-451b-b6cc-57a2d1bb7b30)
- [x] [Single-cell profiling of healthy human kidney reveals features of sex-based transcriptional programs and tissue-specific immunity](https://contribute.data.humancellatlas.org/projects/detail?uuid=77c13c40-a598-4036-807f-be09209ec2dd)
- [x] [Cerebrospinal fluid immune dysregulation during healthy brain aging and cognitive impairment](https://contribute.data.humancellatlas.org/projects/detail?uuid=4c3504a5-b63e-4d13-9652-b245576416ca)
- [x] [A cell atlas of human adrenal cortex development and disease](https://contribute.data.humancellatlas.org/projects/detail?uuid=5f28138b-db43-4469-a2d4-fd02f118611b)
- [x] [Microglia ferroptosis is regulated by SEC24B and contributes to neurodegeneration](https://contribute.data.humancellatlas.org/projects/detail?uuid=40acc944-fabf-4ba9-b930-e114a178eb91)
- [x] [Single-cell RNA sequencing analyses of primary cutaneous B-cell disorders reveal distinct molecular patterns consistent with clinical behavior](https://contribute.data.humancellatlas.org/projects/detail?uuid=733601b6-07e7-421c-aa2f-1a94c0759229)
- [x] [Single nucleus and spatial transcriptomic profiling of human healthy hamstring tendon](https://contribute.data.humancellatlas.org/projects/detail?uuid=c9c454a0-4371-417c-9acf-c23d9510007a)
- [x] [A single-cell comparison of adult and fetal human epicardium defines the age-associated changes in epicardial activity](https://contribute.data.humancellatlas.org/projects/detail?uuid=2962c6ca-e915-44db-b607-da51bb83749e)
- [x] [A comprehensive single-cell map of T cell exhaustion-associated immune environments in human breast cancer](https://contribute.data.humancellatlas.org/projects/detail?uuid=33f72b58-7e2b-4fa2-8865-85962c1748b6)

**Comment by idazucchi** [comment]
I sent an email to EuropePMC to see if they can add the missing publication 

I checked again and only _A single-cell comparison of adult and fetal human epicardium defines the age-associated changes in epicardial activity_ is missing

**Comment by idazucchi** [comment]
publications have to be submitted by their PI or one of the grant holders so we can't add the missing publication to EuropePMC

I will add the paper manually to ingest

**Comment by gabsie** [comment]
When adding a GEO accession to ingest, a project wasn't created, just a spreadsheet. To be tested again and see whether we need a bug ticket for this as well. @idazucchi
