### ISSUE TITLE
Review technologies cheatsheet

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1047]
**Description of the task:**
Review the technologies cheatsheet before it is shared with the blood bionetwork

Deadline: Friday 17th of February?
[cheatsheet](https://docs.google.com/spreadsheets/d/1H9i1BK-VOXtMgGVv8LJZZZ9rbTG4XCQTBRxErdqMvWk/edit#gid=0)

**Acceptance criteria for the task:**
- [ ] check existing technologies
   - [x] CITE-seq
   - [x] DroNc-seq
   - [ ] MARS-seq
   - [ ] inDrop
   - [ ] Drop-seq
   - [ ] Fluidigm C1
   - [ ] sci-CAR
   - [ ] GexScope
- [x] add smart-seq3

**Comment by ESapenaVentura** [comment]
Wranglers to check technologies if capacity allows - Please **check the boxes after checking**

**Comment by Wkt8** [comment]
This is not important to do right now! Closing.
