### ISSUE TITLE
Improve internal processes related to longevity of existing wrangling tickets

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1048]
Context: Some contributors reach out to us to push their data to DCP but then go "radiosilent". We need a plan on how to best tackle that situation.

Proposal:
- Set up expectation upfront with the contributors that we are expecting to be able to push their data to DCP as soon as possible and make it public there within the next 6 months - 1 year at the latest (we might have this already covered in our current wrangling documentation. But I thought it was worth writing it down here).
- If contributors go silent for 6 months, and we've already attempted communication as per wrangling SOP (whatever amount of chasing we agreed on etc), we:
1. Update Ingest Admin tab, to comment that is stalled due to contributor communication being halted, and link the zen hub ticket or any spreadsheet location etc for future reference in case in the future we get communication again from contributor or we don't want to re-start the wrangling from scratch
2. Close the ticket in ZenHub

This proposal would probably require to make this ticket an epic and create related Documentation tickets to amend or add to our Wrangling SOPs I guess.

**Actions**
- [ ] documentation PR
- [ ] review tickets in stalled
- [ ] review tickets in icebox

**Comment by ofanobilbao** [comment]
@gabsie check if I have captured all we discussed

**Comment by gabsie** [comment]
All sounds good, @ofanobilbao  - to be addressed in Doc hour.

**Comment by idazucchi** [comment]
### Changes needed:
all in the  contributor comunication SOP?

- Change contributor comms --> include timeline expectations, how long we can hold the data for next 6 months - 1 year
- How much do we chase them?
  1. wait a week
  2. wait two weeks   
  3. wait a month 
  4. no reply --> dead comunication
- admin tab - no comunication for X amount of time, github ticket here

**Comment by ofanobilbao** [comment]
Moving to the To Do queue. If no-one wants to pick it up or deems is needed then I'll close the ticket. It was meant to be a quick, let's improve how we deal with old tickets, which has sort of happened when every now and then we've done a review of old stuff
