### ISSUE TITLE
GSE130977, GSE130646, GSE138707 - Skeletal Muscle 

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#105]
**Primary Wrangler:**
Marion Shadbolt

**Secondary Wrangler:**
Ray

**Associated files:**

Google Drive:
https://drive.google.com/open?id=1x0wh-JqX2AOI9Iq6bpIFwMmsbgPtYhmp

**Published study links**

Paper: [Single-cell transcriptional profiles in human skeletal muscle](https://doi.org/10.1038/s41598-019-57110-6)

Accessioned data:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130977
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130646
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138707

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] obtain contributor matrices and cell type annotations
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Transfer files to ingest to validate data files
- [x] Submit dataset to Production 
- [x] transfer matrices/cell type annotations to gs bucket and fill in spreadsheet
- [ ] convert to scea format

**Comment by mshadbolt** [comment]
I converted and combined the three GEO series into one spreadsheet. There are 4 10x human cell suspensions derived from one donor, 2 mouse cell suspensions and 18 SMARTer cell suspensions. I am not sure if these are analysable the same way as SS2.

There is very little information recorded in the metadata about the donors so I have tried approaching the authors.

**Comment by mshadbolt** [comment]
emailed the authors to see if they can provide any further metadata (Stuart Sealfon and Gregory Smith)

**Comment by mshadbolt** [comment]
I requested more info from the authors again, I will move to stalled and if no response by the end of the sprint I don't think this dataset is worth pursuing further.

**Comment by mshadbolt** [comment]
received donor metadata so i will work on incorporating into the spreadsheet then will be ready to secondary review

**Comment by mshadbolt** [comment]
I have run the graph validator once but after I believe I fixed some issues I could not run it again as the python install on the ec2 seems broken, I will need to check again once it is back up and running again

**Comment by rays22** [comment]
### Secondary review:

I have reviewed the metadata. I have found only one minor issue:
- I it would look nicer to start sentence with a capital letter for one of the enrichment protocols:

> enrichment_protocol.protocol_core.protocol_description : "cells from the five mouse diaphragms" 


### ingest graph validation

I have run the ingest graph validator tests on my laptop. I used the latest spreadsheet: `GSE130646-GSE130977-GSE138707_combined_ontologies_sra_files.xlsx`. I have upload the [test results to the gdrive.](https://drive.google.com/file/d/1KrkGjXKXtSYQBkfM2ovrMiO56FD9CNnF/view?usp=sharing)

I am listing the failed tests, however, **all the failed test appear to be false errors.**


- [10x_has_more_than_2_files.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/10x_has_more_than_2_files.adoc)
    - This is a known false error: see <https://github.com/ebi-ait/ingest-graph-validator/issues/13>
- [file_donthave_outward_links.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/file_donthave_outward_links.adoc)
    - This is also a false error. See <https://github.com/ebi-ait/ingest-graph-validator/issues/27>
- [contains_cell_barcode_info.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/contains_cell_barcode_info.adoc)
    - I think this is also a false error. I am looking at the cypher code and the test does not seem know about `SMARTer` library contruction.
- [contains_umi_barcode_info.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/contains_umi_barcode_info.adoc)
    - I think this is also a false error. I am looking at the cypher code and the test does not seem know about `SMARTer` library contruction.
- [paired_end_2_files.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/paired_end_2_files.adoc)
    - It looks like another false error to me.

### Summary
I have not found any major issues.

**Comment by mshadbolt** [comment]
asked the contributor for cell type annotations/cluster information for matrices

**Comment by mshadbolt** [comment]
uploaded matrix files to google bucket and filled in sheet

**Comment by mshadbolt** [comment]
I have asked SCEA folks about whether they would like this project in SCEA/GXA

**Comment by mshadbolt** [comment]
SCEA said they were interested in the single cell stuff (GSE138707 & GSE130646). This consists of two cell suspensions from mouse and 4 biopsies taken from a single human donor.

My attempt at trying to convert this part of the experiment is here for IDs E-HCAD-33 and E-HCAD-34: https://drive.google.com/open?id=1u0084DN_u0ApwyF6CLpz_Ld8HOHz8OGq&authuser=mshadbolt%40ebi.ac.uk&usp=drive_fs

I have done the initial conversion but I wasn't sure about what information to put for the sra/fastq files. The factor-value stuff kinda confused me too. So there is some manual curation required in order to progress these to submission to SCEA.

**Comment by ami-day** [comment]
Taking this on

**Comment by ofanobilbao** [comment]
@ami-day I have moved this to Finished in the Wrangling board as I believe that's the case on the DCP journey. And that the only thing remaining is conversion to SCEA, which will be tracked on the SCEA board. Please, feel free to correct if I did not get that right. Thanks!
