### ISSUE TITLE
stuck in export R25

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1051]
**Context**

Four projects aimed for release 25 are stuck in exporting, all in a similar situation: the files are exported correctly, some projects have the spreadsheet with its descriptor but nothing else is exported.

----
- [x] ChimerismKidneyTransplantReject
uuid: `4ef86852-aca0-4a91-8522-9968e0e54dbe`
[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=4ef86852-aca0-4a91-8522-9968e0e54dbe&tab=project)
ticket ebi-ait/hca-ebi-wrangler-central#997
primary wrangler: Ida
  - [x] re-exported
  - [x] validated

----

- [x] MammaryLactactingCells
uuid: `e956e66a-ac8e-483a-963a-0f92c7e5abfb`
[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=e956e66a-ac8e-483a-963a-0f92c7e5abfb)
ticket ebi-ait/hca-ebi-wrangler-central#1023
primary wrangler: Arsenios
  - [x] re-exported
  - [x] validated

----

- [x] 125 days differentiation of embryonic stem cells - Update
uuid: `2043c65a-1cf8-4828-a656-9e247d4e64f1`
[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=2043c65a-1cf8-4828-a656-9e247d4e64f1)
ticket ebi-ait/hca-ebi-wrangler-central#992
primary wrangler: Enrique

  - [x] re-exported
  - [x] validated

---- 

- [ ] HumanMelanocyteDevelopment - large dataset!
uuid: `a4f154f8-5cc9-40b5-b8d7-af90afce8a8f`
[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=a4f154f8-5cc9-40b5-b8d7-af90afce8a8f)
ticket ebi-ait/hca-ebi-wrangler-central#853
primary wrangler: Ida
 
  - [x] re-exported
  - [ ] export completed
  - [ ] validated

*Excluded from DCP 25*
----

**Acceptance criteria**
- [x] investigate cause
- [ ] move to exported

**Comment by amnonkhen** [comment]
Regarding `4ef86852-aca0-4a91-8522-9968e0e54dbez`
I restarted the exporter and re-exported. Exporter finished.
@idazucchi please verify.

**Comment by ESapenaVentura** [comment]
@amnonkhen `2043c65a-1cf8-4828-a656-9e247d4e64f1` (125 days) still only has the spreadsheet in the area

```
gsutil ls -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/
gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/data/:
gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/data/Single cell RNAseq characterization of cell types produced over time in an in vitro model of human inhibitory interneuron differentiation._metadata_26-01-2023.xlsx

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/descriptors/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/descriptors/supplementary_file/:
gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/descriptors/supplementary_file/4d4a1860-5117-5e98-999a-5ebf2f5217b4_2023-01-26T22:03:01.310000Z.json

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/links/:
gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/links/4d4a1860-5117-5e98-999a-5ebf2f5217b4_2023-01-26T22:03:01.310000Z_2043c65a-1cf8-4828-a656-9e247d4e64f1.json

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/metadata/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/metadata/supplementary_file/:
gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/metadata/supplementary_file/4d4a1860-5117-5e98-999a-5ebf2f5217b4_2023-01-26T22:03:01.310000Z.json
```

**Comment by Wkt8** [comment]
For MammaryLactatingCells we had to remove outdated metadata descriptor files from terra staging area see #1023 

Action list to check whether there are outdated metadata descriptor files for the rest of the projects: 
- [ ] HumanMelanocyteDevelopment - large dataset!
- [ ] 125 days differentiation of embryonic stem cells - Update
- [ ] ChimerismKidneyTransplantReject

file descriptor and supplementary files.json (potentially links.json)

**Comment by ESapenaVentura** [comment]
for `2043c65a-1cf8-4828-a656-9e247d4e64f1` I have deleted the staging area and forced a re-export.

Currently checking on the ingest-exporter and looks like it's exporting fine

After export:
- [ ] Delete metadata related to sequence files

**Comment by ESapenaVentura** [comment]
`2043c65a-1cf8-4828-a656-9e247d4e64f1` **Done and validated**

**Comment by amnonkhen** [comment]
*Excluded from DCP 25*
Needs a bug ticket

**Comment by amnonkhen** [comment]
waiting for import
