### ISSUE TITLE
review import: covid19PBMCsTCRandCITEseq

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1052]
*Project Info*
uuid: `ae62bb31-55ca-4127-b0fb-b1771a604645`
project short name: covid19PBMCsTCRandCITEseq
primary wrangler: Rachel Schwartz
[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=ae62bb31-55ca-4127-b0fb-b1771a604645&tab=upload)
[staging area](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/ae62bb31-55ca-4127-b0fb-b1771a604645;tab=objects?prefix=&forceOnObjectsSortingFiltering=false&authuser=1)

Note:
assign to the current dev on operations.

**Comment by amnonkhen** [comment]
@rachadele I don't see this project uuid in ingest ["all projects" page](https://contribute.data.humancellatlas.org/projects/all) 
Have you deleted it? 
Is this still relevant?

**Comment by gabsie** [comment]
@amnonkhen - seems this is the project UUID:
ae62bb31-55ca-4127-b0fb-b1771a604645

**Comment by rachadele** [comment]
I think that may be an ingest error; I've been seeing weird behavior all day.

**Comment by amnonkhen** [comment]
This is the contents of the staging area:
 ```
gsutil ls -r "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/${uuid}/metadata/" | cut -d/ -f7 | sed -r '/^\s*$/d' | uniq -c | sort -k2,2 
    8 analysis_file
      5 analysis_protocol
    169 cell_suspension
      2 collection_protocol
     47 donor_organism
      4 enrichment_protocol
      4 library_preparation_protocol
   2356 process
      2 project
   3951 sequence_file
      2 sequencing_protocol
     70 specimen_from_organism
      3 supplementary_file
```

These are the entity counts from ingest:
```

     2023-02-24T13:19:48+00:00       INFO    entity type counts from ingest
    2023-02-24T13:19:49+00:00       INFO    biomaterials, 283
    2023-02-24T13:20:01+00:00       INFO    protocols, 12
    2023-02-24T13:20:02+00:00       INFO    files, 3957
2023-02-24T13:20:04+00:00       INFO    processes, 2219
```

I need to figure out the discrepancies.

**Comment by Mil-m** [comment]
@ESapenaVentura attempt of re-exporting

**Comment by ESapenaVentura** [comment]
Stuck again!

**Comment by ESapenaVentura** [comment]
In the staging area count from above there is an extra element in each of the folder counts because `gsutil ls -r` shows the name of the folder as the first entry

**Comment by ESapenaVentura** [comment]
## Counts
Biomaterials:  46 donors - 69 specimens - 168 cell suspensions : **Expected**
Protocols: 4 analysis + 1 collection + 3 enrichment + 3 library prep + 1 sequencing protocol = 12 protocols: **EXPECTED**
Files: 7 analysis files + 3950 sequence files + 2 supplementary files = 3957 files: **EXPECTED** (2 extra spreadsheets)
Processes: 2355: ** 136 EXTRA PROCESSES**  We need to check that there are actually 136 extra processes: `gsutil ls "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/${uuid}-backup/${uuid}/metadata/process" | grep -Eo "process/[A-Za-z0-9]*-[A-Za-z0-9]*-[A-Za-z0-9]*-[A-Za-z0-9]*-[A-Za-z0-9]*" | sort | uniq -cd | wc -l`

**Comment by ESapenaVentura** [comment]
Missing links is not something that is approachable in an operational way. This should be moved to R26

**Comment by ESapenaVentura** [comment]
Solved - Ready to go

**Comment by amnonkhen** [comment]
Waiting for import. Hoping there will not be errors.

**Comment by gabsie** [comment]
This made it to R25. Once in the browser, Rachel will have to check whether the update needed, actually made it through.

**Comment by gabsie** [comment]
to be checked whether it was returned with errors from the import team and see what has happened
