### ISSUE TITLE
updating published dataset - atlasOfTheHumanCiliaryBody 

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1053]
**Dataset/group this task is for:**
atlasOfTheHumanCiliaryBody 

- project uuid - 07518430-7031-4bdf-a3ce-1bf0917a1923
- [link to browseHCA data portal](https://data.humancellatlas.org/explore/projects/07518430-7031-4bdf-a3ce-1bf0917a1923)
- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=c07518430-7031-4bdf-a3ce-1bf0917a1923)

**Relevant People**
- Wrangler: Rachel Schwartz

**Description of the problem with the dataset**

Will need dataset reverted to Exported status so we can update an incorrect library preparation protocol ontology from microwell-seq -> BD Rhapsody Targeted mRNA

**Comment by ESapenaVentura** [comment]
I have reverted it to valid :)

Please let us know in the ticket when you hit export, we need to monitor it

**Comment by ESapenaVentura** [comment]
Has not been exported

**Comment by ESapenaVentura** [comment]
still not exported

**Comment by rachadele** [comment]
I thin kwe are still waiting for this ontology to be moved in the HCAO release: https://github.com/HumanCellAtlas/ontology/issues/127

**Comment by ESapenaVentura** [comment]
Oh ok, then we wait until next release :)

**Comment by ESapenaVentura** [comment]
@rachadele @willrockout it should be ready to go!

**Comment by anu-shiva** [comment]
Ontology term unblocked.  @rachadele @willrockout to look into this.

**Comment by gabsie** [comment]
@ESapenaVentura  - please remind on slack :)

**Comment by willrockout** [comment]
@ESapenaVentura @anu-shiva This is ready to go not sure if you want to kick of export so you can track it

**Comment by willrockout** [comment]
Just submitted project for export

**Comment by ESapenaVentura** [comment]
Exported!
