### ISSUE TITLE
Schema update priority ticket - 2023-02-24

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1054]
**What are the next schema updates?**
1. Disease adjacent specimen HumanCellAtlas/metadata-schema#1512
1. Add timecourse to biomaterials HumanCellAtlas/metadata-schema#1511

**What schemas will they affect?**

These changes will affect the following schemas:
- type/biomaterial/specimen_from_organism.json
- type/biomaterial/specimen_from_organism.json
- type/biomaterial/imaged_specimen.json
- type/biomaterial/organoid.json

**Why are these changes needed?**
1.`Disease adjacent` is useful to determine the difference between 'normal' healthy tissue and 'disease-adjacent' tissue which often is affected by its proximity to the pathology area. - requested by Skin bionetwork
1. Timecourse metadata may be relevant at different stages of the experiment

**Type of change and time frame**
Update number 1 constitutes a minor change.
Update number 2 constitues a minor change.

We are expecting to push both updates before 10-03-2024

**Comment by idazucchi** [comment]
Disease adjacent [PR](https://github.com/HumanCellAtlas/metadata-schema/pull/1514)

**Comment by gabsie** [comment]
@ESapenaVentura to approve on our side
