### ISSUE TITLE
HRA000342 - IgANephropathySTRT

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1056]
### Project short name: 
IgANephropathySTRT

### Primary Wrangler: 
Arsenios Chatzigeorgiou @arschat 

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1fIuGFkuiFhzz7JTvCYqvU_kcF17XEBg9?usp=share_link)

### Published study links

* Paper: **Included data** [Single-Cell Transcriptomics Reveal Immune Mechanisms of the Onset and Progression of IgA Nephropathy](https://doi.org/10.1016/j.celrep.2020.108525)

* Accessioned data: managed access data [HRA000342](https://ngdc.cncb.ac.cn/gsa-human/browse/HRA000342)
  - analysis files available from [drive](https://drive.google.com/drive/folders/1nGa31zbiLoXWpzbOJ-2_UPxWWyAELZUd?usp=sharing)

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=2caedc30-c816-4b99-a237-b9f3b458c8e5)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch witht the authors to request it

**Comment by arschat** [comment]
PBMC cells are not included in the given analysis files.

**Comment by arschat** [comment]
Submission with error in analysis files, and project tab cannot be deleted.

**Comment by arschat** [comment]
Contacted authors for more info in the enrichment protocol results (enrichment per cell suspension).
Replied with a metadata that contained "Position" of each cell suspension, replied for clarifications and a possible match between enrichment and "Position".
### Enrichment protocols
- glomerulus
- CD14+ macrophages
- EPCAM+ epithelium
- negative selected cells
### Position
- Glomerulus
- Interstitial
- Non-glomerulus
- Non-glomerulus-Non-macrophage
- Non-macrophage
- Renal

**Comment by arschat** [comment]
Authors verified the following matching:

**Comment by arschat** [comment]
Added changes and submitted spreadsheet. Waiting for graph validation

Since there is no CL ontology for glomerulus or negative selection I omitted the Selected cell types field and added a mention in the CS description about the type of enrichment.

**Comment by ESapenaVentura** [comment]
Seems ingest crashed down - Does not seem related to this dataset, though, but it has affected graph validation for this dataset

**Comment by ofanobilbao** [comment]
Submission needs to be put back to Metadata valid and then graph validation re-triggered. @ESapenaVentura to help on this

**Comment by amnonkhen** [comment]
@amnonkhen to retrigger GV.

**Comment by idazucchi** [comment]
Project
- update cell count to 3620

Donor
- there is no MONDO term for Nephroptosis, but there is an [HP](https://ontology.archive.data.humancellatlas.org/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0011126) one —> I would use that one instead

Collection 
- if you split the protocols split the description too to make it clearer 

Specimen
- fill out the nephrectomy samples as normal disease - they have no disease to filter on like this
- this is a bit tricky to represent but the specimens are split in two - glomerulus + rest of the kidney. I would suggest to represent it as:
    - kidney
    - kidney organ part glomerulus 
This allows the users to filter for glomerulus, but makes it clear that it's not the only tissue analysed.
you can also add a sentence to the collection protocol like "Glomeruli were isolated from the tissue, and the rest of the kidney and the glomeruli were processed separately"

Dissociation
- I would split the enzymatic dissociation used to isolate the glomerulus and the one used to dissociate the rest of the kidney to make the experimental design clearer

Cell suspension
- you can use CL:0002518  `kidney epithelial cell` for the epithelial cells

Enrichment
- use ; not / for marker separator
- I suggest `mouth pipetting` for `glomerulus_enrichment` rather than cell picking since the glomerulus is not a single cell and you can make it one protocol with `glomerulus_cell_size_enrichment`

Sequencing
- not pair ended

Analysis protocol
- `normalized_matrix_generation` is this needed? the file contains raw cell counts 

Analysis file
- no need to fill in the cell count for files that are not matrices

**Comment by arschat** [comment]
applied sec review comments, added submission but got the following error in metadata validation
`* Could not retrieve IRI for data:0006 at .file_core.content_description[0].ontology`

**Comment by arschat** [comment]
metadata valid, pushed graph validation on 12:14

**Comment by amnonkhen** [comment]
I triggered graph validation.
It finished successfully.

**Comment by arschat** [comment]
It is now exported and import form has been sent.
