### ISSUE TITLE
Add a template in the SOPs for contact after an HCA publication email

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1059]
In the wrangler's SOPs about [contributor communication](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/contributor_communication_SOP.html), there is not a template for contact after an HCA publication email.
Based on previous emails, the template should be the following:

> Dear [name/s of contributor/s],
> 
> Congratulations on your HCA manuscript!
> We have added the information about your publication to our project catalogue (https://www.ebi.ac.uk/humancellatlas/project-catalogue/) as a HCA publication.
> Due to internal processes it will take a day to display the publication information, in the meantime any feedback about the HCA project catalogue is greatly appreciated!
> 
> Do you have any time-sensitive requirements on archiving, or have you already archived your data in a specific database?
> 
> 
> Warm regards,
> [wrangler name]
> 
> On Behalf of the HCA DCP Ingestion Service 
> 

We should add an special case in the [First contact communication SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/contributor_communication_SOP.html#first-contact) named `Contact after an HCA publication announcement email`

- [x] Wranglers agree on the template
- [x] @arschat do the PR
- [x] review
- [x] merge

**Comment by amnonkhen** [comment]
@arschat to create a PR and have the template reviewed and approved.

**Comment by arschat** [comment]
Submitted the [PR](https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/1060)

**Comment by gabsie** [comment]
needs a small review @idazucchi

**Comment by arschat** [comment]
ida & wei reviewed and is now merged.
