### ISSUE TITLE
Protect contributor upload areas from disappearing

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#106]
**Description of the task:**

I created two upload areas (using <https://github.com/ebi-ait/hca-util>) for contributors on 2020-07-16. After creating them, I ran hca-util list -b to make sure the upload areas existed:
```
...
190028f6-532b-4132-ba8a-8f0a6c0b64bd/ ux  HCL-liver-issue89 
1f0aa586-2a17-489d-bd06-e16a812d02a9/ ux  StimulatedPBMCs-issue83 
```

On the same day, I sent one of the area UUIDs to a contributor.

Today (2020-07-31) I ran  `hca-util list -b` again, because I wanted to check if files have been uploaded there, but the above two upload areas appear to have been deleted.

It is very problematic when an active upload area gets deleted. I imagine it can lead to a lot of frustration and disappointment on their part when the contributors try to upload their data to a deleted area. 
I have created new upload areas to replace the ones that have been deleted and sent the new UUID with my apologies to one of the contributors, but I would like to avoid similar situations in the future.

I would like to make sure that empty (or non-empty) upload areas are stable, because there is usually a lag between the time they are set up and communicated to the contributor and the time when the contributors actually upload their data.

**Acceptance criteria for the task:**

- [ ] There is a process in place to check which s3 areas can be safely deleted.
- [ ] Upload areas of active projects are excluded from deletion.

**Comment by rdgoite** [comment]
This sounds more like a bug/enhancement, and needs some development work. Do we still need the `operations` label for this?
