### ISSUE TITLE
stuck in graph validating - TubularCellLupusNephritis

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1061]
**Dataset/group this task is for:**

- project uuid - `97fca723-d9e9-4263-9f67-335416086f47`
- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=97fca723-d9e9-4263-9f67-335416086f47)

**Relevant People**
- Wrangler Ida
- dev

**Description of the problem with the dataset**
This seems to be a size issue when running the graph validation - similar to #1050
The project has 38582 entities (mostly cell supensions) and 173443 links

I've tried to do graph validation locally but the project on't hydrate from the xls
```
ingest-graph-validator hydrate xls /Users/idazucchi/Documents/Wrangling/TubularCellLupusNephritis/TubularCellLupusNephritis_ontologies.xlsx 
23-03-03 11:53:04 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
23-03-03 11:53:05 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
23-03-03 11:53:05 [ingest_graph_validator.ingest_graph_validator] - INFO: Connecting to neo4j...
23-03-03 11:53:05 [ingest_graph_validator.hydrators.hydrator] - INFO: started xls hydrator for file [/Users/idazucchi/Documents/Wrangling/TubularCellLupusNephritis/TubularCellLupusNephritis_ontologies.xlsx]
23-03-03 11:53:55 [ingest_graph_validator.utils] - INFO: [import_spreadsheet] took [50343] ms
23-03-03 11:53:57 [ingest_graph_validator.hydrators.hydrator] - INFO: imported 38582 nodes
23-03-03 11:54:07 [ingest_graph_validator.hydrators.hydrator] - INFO: imported 231257 edges
```
it has been hanging there for 3h+

Wei solved the same issue with HumanMelanocyteDevelopment by running an older version of the ingest graph validation tool but this time it failed to hydrate
```
(ingest-graph-validator) wteh@C02DM256ML85 Ingest-graph-validator % ingest-graph-validator hydrate xls TubularCellLupusNephritis_ontologies.xlsx
23-03-03 10:27:43 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
23-03-03 10:27:43 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
23-03-03 10:27:47 [ingest_graph_validator.hydrators.hydrator] - INFO: started xls hydrator for file [TubularCellLupusNephritis_ontologies.xlsx]
23-03-03 10:28:37 [ingest_graph_validator.utils] - INFO: [import_spreadsheet] took [49893] ms
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ingest-graph-validator/bin/ingest-graph-validator", line 8, in <module>
    sys.exit(entry_point())
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/ingest_graph_validator/hydrators/hydrator_definitions.py", line 25, in xls
    XlsHydrator(ctx.obj.graph, xls_filename).hydrate()
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/ingest_graph_validator/hydrators/xls_hydrator.py", line 31, in __init__
    self._nodes = self.get_nodes()
  File "/opt/anaconda3/envs/ingest-graph-validator/lib/python3.8/site-packages/ingest_graph_validator/hydrators/xls_hydrator.py", line 49, in get_nodes
    for node_type in self._entity_map.entities_dict_by_type.keys():
AttributeError: 'NoneType' object has no attribute 'entities_dict_by_type'
```

**Acceptance criteria for the task:**
- [ ] TubularCellLupusNephritis graph valid in ingest

**Comment by Wkt8** [comment]
Found and fixed the issue and adding graph_test_set tests here

`(ingest-graph-validator) wteh@C02DM256ML85 ingest-graph-validator % ingest-graph-validator action test graph_test_set
23-03-06 12:50:30 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
23-03-06 12:50:30 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
23-03-06 12:50:30 [ingest_graph_validator.actions.test_action] - INFO: loading tests
23-03-06 12:50:30 [ingest_graph_validator.actions.test_action] - INFO: loaded [19] test queries
23-03-06 12:50:30 [ingest_graph_validator.actions.test_action] - INFO: running tests
23-03-06 12:50:32 [ingest_graph_validator.actions.test_action] - ERROR: test [contains_cell_barcode_info.adoc] failed: non-empty result.
23-03-06 12:50:32 [ingest_graph_validator.actions.test_action] - ERROR: result: [{'p': (_19380:library_preparation_protocol:protocol {`cdna_library_amplification_method.ontology`: 'OBI:0000415', `cdna_library_amplification_method.ontology_label`: 'polymerase chain reaction', `cdna_library_amplification_method.text`: 'PCR', describedBy: 'https://schema.humancellatlas.org/type/protocol/sequencing/6.3.1/library_preparation_protocol', end_bias: 'full length', id: 'library_Fluidigm', `input_nucleic_acid_molecule.ontology`: 'OBI:0000869', `input_nucleic_acid_molecule.ontology_label`: 'polyA RNA', `input_nucleic_acid_molecule.text`: 'polyA RNA', `library_construction_method.ontology`: 'EFO:0010058', `library_construction_method.ontology_label`: 'Fluidigm C1-based library preparation', `library_construction_method.text`: 'Fluidigm C1-based library preparation', nucleic_acid_source: 'single cell', primer: 'poly-dT', `protocol_core.protocol_description`: 'Single-cell suspensions at a concentration of 200,000\u2009cells\u2009ml\u20131 and no less than 2,000 cells were loaded into a medium (10\u201317\u2009\u00b5m) diameter, C1 HT, 800-well, integrated microfluidic chip (IFC) (Fluidigm) and processed according to the Fluidigm C1 HT protocol revision A, using the recommended standard mRNA-seq reagents and program. The IFC is divided into two 400-well sections, allowing for loading of skin and kidney samples matched by individual on the same chip. Following the manufacturer\u2019s recommendation, 7\u2009\u00b5l of 10% phosphate-buffered saline Tween was added to the valve fluid to reduce surface tension. The occupation of single-cell capture sites was verified by using a Zeiss Axiovert 200 inverted microscope averaging 500 single-cell captures per 800-well chip, and wells containing either debris or multiple captures were excluded from downstream analysis. The captured cells were lysed, poly(A) mRNA was reverse transcribed and complementary DNA pre-amplified using the SMARTer Ultra Low RNA kit (Clontech) in the Fluidigm C1 Single-Cell Auto Prep system. To monitor cDNA library conversion, a cocktail of synthetic RNA spikes, nos. 1, 4 and 7 of the Ambion ArrayControl RNA Spikes (ThermoFisher), was prepared as described in the Fluidigm C1 protocol and added to the lysis reaction (Mix A) for each experiment. After the initial rounds of PCR on the IFC, products were harvested, exonuclease treated and further amplified according to the Fluidigm protocol.\n\nPreamplified cDNA libraries were tagmented and barcoded using the Nextera XT Library Preparation Kit (Illumina) with indexing according to the Fluidigm C1 HT protocol revision A. An enrichment primer to select for the 3\u2032-ends was added during this step. PCR products originating from up to 800 cells per chip were pooled together using the 20 barcodes recommended by Fluidigm.', `protocol_core.protocol_id`: 'library_Fluidigm', `protocol_core.protocol_name`: 'Library preparation Fluidigm C1 HT', schema_type: 'protocol', `spike_in_kit.manufacturer`: 'ThermoFisher', `spike_in_kit.retail_name`: 'Ambion ArrayControl RNA Spike nos. 1, 4 and 7', strand: 'unstranded'}), '"Missing information for cell barcode"': 'Missing information for cell barcode', 'labels(p)': ['protocol', 'library_preparation_protocol']}]
23-03-06 12:50:35 [ingest_graph_validator.actions.test_action] - ERROR: test [contains_umi_barcode_info.adoc] failed: non-empty result.
23-03-06 12:50:35 [ingest_graph_validator.actions.test_action] - ERROR: result: [{'p': (_19380:library_preparation_protocol:protocol {`cdna_library_amplification_method.ontology`: 'OBI:0000415', `cdna_library_amplification_method.ontology_label`: 'polymerase chain reaction', `cdna_library_amplification_method.text`: 'PCR', describedBy: 'https://schema.humancellatlas.org/type/protocol/sequencing/6.3.1/library_preparation_protocol', end_bias: 'full length', id: 'library_Fluidigm', `input_nucleic_acid_molecule.ontology`: 'OBI:0000869', `input_nucleic_acid_molecule.ontology_label`: 'polyA RNA', `input_nucleic_acid_molecule.text`: 'polyA RNA', `library_construction_method.ontology`: 'EFO:0010058', `library_construction_method.ontology_label`: 'Fluidigm C1-based library preparation', `library_construction_method.text`: 'Fluidigm C1-based library preparation', nucleic_acid_source: 'single cell', primer: 'poly-dT', `protocol_core.protocol_description`: 'Single-cell suspensions at a concentration of 200,000\u2009cells\u2009ml\u20131 and no less than 2,000 cells were loaded into a medium (10\u201317\u2009\u00b5m) diameter, C1 HT, 800-well, integrated microfluidic chip (IFC) (Fluidigm) and processed according to the Fluidigm C1 HT protocol revision A, using the recommended standard mRNA-seq reagents and program. The IFC is divided into two 400-well sections, allowing for loading of skin and kidney samples matched by individual on the same chip. Following the manufacturer\u2019s recommendation, 7\u2009\u00b5l of 10% phosphate-buffered saline Tween was added to the valve fluid to reduce surface tension. The occupation of single-cell capture sites was verified by using a Zeiss Axiovert 200 inverted microscope averaging 500 single-cell captures per 800-well chip, and wells containing either debris or multiple captures were excluded from downstream analysis. The captured cells were lysed, poly(A) mRNA was reverse transcribed and complementary DNA pre-amplified using the SMARTer Ultra Low RNA kit (Clontech) in the Fluidigm C1 Single-Cell Auto Prep system. To monitor cDNA library conversion, a cocktail of synthetic RNA spikes, nos. 1, 4 and 7 of the Ambion ArrayControl RNA Spikes (ThermoFisher), was prepared as described in the Fluidigm C1 protocol and added to the lysis reaction (Mix A) for each experiment. After the initial rounds of PCR on the IFC, products were harvested, exonuclease treated and further amplified according to the Fluidigm protocol.\n\nPreamplified cDNA libraries were tagmented and barcoded using the Nextera XT Library Preparation Kit (Illumina) with indexing according to the Fluidigm C1 HT protocol revision A. An enrichment primer to select for the 3\u2032-ends was added during this step. PCR products originating from up to 800 cells per chip were pooled together using the 20 barcodes recommended by Fluidigm.', `protocol_core.protocol_id`: 'library_Fluidigm', `protocol_core.protocol_name`: 'Library preparation Fluidigm C1 HT', schema_type: 'protocol', `spike_in_kit.manufacturer`: 'ThermoFisher', `spike_in_kit.retail_name`: 'Ambion ArrayControl RNA Spike nos. 1, 4 and 7', strand: 'unstranded'}), '"Missing information for UMI barcode"': 'Missing information for UMI barcode', 'labels(p)': ['protocol', 'library_preparation_protocol']}]
23-03-06 12:50:35 [ingest_graph_validator.actions.test_action] - INFO: all tests finished `

**Comment by Wkt8** [comment]
Passed graph validation! 
```
(ingest-graph-validator) wteh@C02DM256ML85 ingest-graph-validator % ingest-graph-validator action test graph_test_set    
23-03-06 12:54:42 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
23-03-06 12:54:42 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
23-03-06 12:54:42 [ingest_graph_validator.actions.test_action] - INFO: loading tests
23-03-06 12:54:42 [ingest_graph_validator.actions.test_action] - INFO: loaded [15] test queries
23-03-06 12:54:42 [ingest_graph_validator.actions.test_action] - INFO: running tests
23-03-06 12:54:44 [ingest_graph_validator.actions.test_action] - INFO: all tests finished 
(ingest-graph-validator) wteh@C02DM256ML85 ingest-graph-validator % 
```

**Comment by Wkt8** [comment]
Made a PR which fixes the previous error in ingest-graph-validator - see [here](https://github.com/ebi-ait/ingest-graph-validator/pull/76)
