### ISSUE TITLE
Prepare talk for LatinCells Initiative

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1064]
**Description of the issue**
@ESapenaVentura needs to prepare a talk for the LatinCell initiative, happening from March 13th to 23rd. The talk:
- Will be 1h30 long, including questions from students (1:15 talk - 15 min questions)
- Will be at 9AM GMT-3 on March 14th (12 UK time)
- The topic of the session is: `Public Databases Related to Single-Cell Genomics`
- The topic of the talk will be: `Current landscape on single cell data", and will be focused around the current databases and data portals, both as a consumer and a contributor perspective. Special mention on the Human Cell Atlas and the resources it provides.

**Checklist and deadlines**
- [x] Define body of the talk in a document and link it here - **8th March**
   - [Backbone](https://docs.google.com/document/d/1To8BE9S3fGQZvSnJk4DKADAza5xsrfaoL4raAmHyq34/edit#)
- [ ] Create slides and post them for review  - **Friday 10th March**

**Comment by Wkt8** [comment]
Might find this useful! 
https://docs.google.com/presentation/d/1gNOeJnEkpyHgIjwnXH535AxumJ4DUgOKi3ROXUE7ugo/edit?usp=sharing

**Comment by ESapenaVentura** [comment]
https://docs.google.com/document/d/1To8BE9S3fGQZvSnJk4DKADAza5xsrfaoL4raAmHyq34/edit# Backbone

**Comment by Wkt8** [comment]
@ESapenaVentura to link the slides
