### ISSUE TITLE
Improve IGV test - smartseq2_has_2-3_files

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1069]
**Context**
I've recently wrangled a dataset (BenchmarkingSingleCellProtocols) that has smartSeq2 for library preparation and has R1, R1, I1 and I2 so it failed graph validation

we have agreed to improve the test to accomodate this case

**Acceptance criteria**
- [ ] edit test
- [ ] BenchmarkingSingleCellProtocols graph valid

**Comment by idazucchi** [comment]
I've opended a PR to start the discussion - here[https://github.com/ebi-ait/ingest-graph-validator/pull/77](url)

**Comment by arschat** [comment]
@idazucchi 
create a positive and a negative test
pass the test and upload spreadsheets to repo
investigate a longer solution (open another ticket)

**Comment by idazucchi** [comment]
I've added a spreadsheet with negative and positive examples. Wei approved the PR and I merged it.

Graph validation is still failing for BenchmarkingSingleCellProtocols because ingest is still running the old test - what do we have to do to pick up the new tests?

**Comment by gabsie** [comment]
Ida will try again and decide if to raise with @amnonkhen

**Comment by Wkt8** [comment]
Graph validation test stuck in 'graph validation requested' in staging: https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=77e2b993-74d7-4af7-b12d-05650788066c&project=48a3b782-a679-47eb-8e43-3c21e22e715d 

@amnonkhen

**Comment by ESapenaVentura** [comment]
@idazucchi and @ESapenaVentura to try re-request graph validation and see if it triggers

**Comment by ESapenaVentura** [comment]
requested graph validation again!

**Comment by idazucchi** [comment]
the test is in master and was deployed - closing this
