### ISSUE TITLE
need humanBloodCiteSeq2 reverted from complete -> exported

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1071]
*Project Info*
uuid: `3ce9ae94-c469-419a-9637-5d138a4e642f`
project short name: humanBloodCiteSeq2
primary wrangler: Rachel Schwartz

published project is missing contact info form contributor, we would like to update it this release.

Note:
assign to the current dev on operations.

**Comment by amnonkhen** [comment]
Why are you asking to change it to Exported? You need to be able to export it again, so it needs to be changed to GraphValid.
