### ISSUE TITLE
Auto-import curation

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1074]
Discovery script run on 15/3/2023

curate projects:
- [x] [Single-Cell RNA Sequencing Reveals the Effects of Chemotherapy on Human Pancreatic Adenocarcinoma and its Tumor Microenvironment](https://contribute.data.humancellatlas.org/projects/detail?uuid=72f85f9a-19d6-43f2-94ad-d7c6d86d6875)
- [x] [Lineage tracing reveals fate bias and transcriptional memory in human B cells](https://contribute.data.humancellatlas.org/projects/detail?uuid=8938d858-d828-492f-898f-c51810b1bccc)

Discovery script run on 19/4/2023
- [x] [Single-cell sequencing of human white adipose tissue identifies new cell states in health and obesity](https://contribute.data.humancellatlas.org/projects/detail?uuid=e8934407-7782-46dc-a82d-c02e90d5269c)
- [x] [Mapping hormone-regulated cell-cell interaction networks in the human breast at single-cell resolution](https://contribute.data.humancellatlas.org/projects/detail?uuid=7fc0a756-9b06-4e63-a780-6c9fc3f9d76d)
- [x] [Single-cell Transcriptomic Analysis of Systemic Autoinflammatory Diseases with Anti-TNFα Therapy](https://contribute.data.humancellatlas.org/projects/detail?uuid=c9933b64-3644-48d8-b7a9-207af32e9d5d)
- [x] [Integration of single-cell multiomic measurements across disease states with genetics identifies mechanisms of beta cell dysfunction in type 2 diabetes](https://contribute.data.humancellatlas.org/projects/detail?uuid=3e15e697-0f4e-4227-a4dd-9188c717737e)
- [x] [Astrocytic cell adhesion genes linked to schizophrenia correlate with synaptic programs in neurons](https://contribute.data.humancellatlas.org/projects/detail?uuid=42591e64-b99a-48e4-a1f2-602978982605)
- [x] [<i>Ex vivo</i>tissue perturbations coupled to single cell RNA-seq reveal multi-lineage cell circuit dynamics in human lung fibrogenesis](https://contribute.data.humancellatlas.org/projects/detail?uuid=dd051005-26f1-4b90-86a4-f9692de9d1ad)
- [x] [Adenomyosis: single-cell transcriptomic analysis reveals a paracrine mesenchymal–epithelial interaction involving the WNT/SFRP pathway](https://contribute.data.humancellatlas.org/projects/detail?uuid=e098a328-ba87-474b-a286-abd6b5f3744b)
- [x] [An integrated single cell and spatial transcriptomic map of human white adipose tissue](https://contribute.data.humancellatlas.org/projects/detail?uuid=57916660-af5a-44d5-a7a9-2e84b65f8a68)

**Comment by ofanobilbao** [comment]
Completed this. Made notes for any in doubt areas
