### ISSUE TITLE
Schema update priority ticket Tissue Atlas Grouping - 2023-03-17

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1076]
**What are the next schema updates?**
Issue: https://github.com/HumanCellAtlas/metadata-schema/issues/1517
PR: https://github.com/HumanCellAtlas/metadata-schema/pull/1520

**What schemas will they affect?**
These changes will affect the following schemas:
- module/project/publication.json

**Why are these changes needed?**
Biological Network Data Contributors need to be able to denote if
a) Their project is part of the HCA Tissue Atlas
b) Which HCA Tissue Atlas projects integrates data from all the others
c) What version of the HCA Tissue Atlas is represented

**Type of change and time frame**
There is only 1 update due to time constraints and another update being in progress. This new update constitutes a minor change. 

We are expecting to push both updates before (2 weeks from ticket 
creation date)
-->

**Comment by Wkt8** [comment]
Added fourth field - HCA project uuid, please review!

**Comment by idazucchi** [comment]
from Dave:
>As far as requirements, I can briefly summarize them as I currently understand them.
>1. Networks may produce multiple versioned atlases.
>2. Atlases may vary by a focus on tissue (possibly multiple) and disease (possibly multiple).
>3. A project may belong to zero or more atlases. 
>4. I am unsure if an atlas can belong to multiple networks, but we should possibly allow it in the schema.
>5. Users can filter projects by network and atlas version.
>6. The project list indicates if a project is included in a network or atlas.
>7. Users can filter samples and files by network and atlas version. Because atlas QC/processing may remove samples or cells from a project, we do not know if a sample or file is included, partially or entirely, in an atlas. We will not tag files or samples with atlases or networks in the browser. We also need a banner indicating that not all listed files and samples may be included in the atlas.
>8. We will have network and atlas version detail pages like we have a project detail page.

>Regarding the metadata schema, it seems that, at the very minimum, we need to tag projects with an array of atlases. This might be implemented with an atlas module under project, and an array of atlases on the project. I can add detail to this suggestion on the atlas PR. 

>There is much more information about the atlases displayed in the mocks. One idea about implementing this is to treat the atlas and network information as portal content and manage it like we manage the other portal content.


We need to discuss more point 7 and what additional information will be displayed for atlas projects. It might be enough to add an inclusion criteria field to the new module

**Comment by arschat** [comment]
Comment on the PR @gabsie

**Comment by gabsie** [comment]
Will update with the requested changes and nudge Dave/Hannes on slack.
