### ISSUE TITLE
Investigate submissions in intermediate statuses

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1078]
**Description of the issue**

As a wrangler, I would like to understand how many submissions are in an intermediate state and need to be researched. 

An intermediate state is defined as a state which should not be maintained over time, such as `archiving`, `submitted`, `Exporting`, etc

For this task, we will focus in submissions with exporting-related issues.

**Exporting-related status**
Statuses = Archiving, Exporting, Submitted

**R26**
- [Tang-Human-IgAN-GEXSCOPE](https://contribute.data.humancellatlas.org/submissions/detail?uuid=cb989b6e-bab9-432c-895d-ea8d2aa1ebab)
- [CovidImmuneAtlas](https://contribute.data.humancellatlas.org/submissions/detail?uuid=639d3383-47a6-4436-985e-4eedd8ee46bb)
- [HematopoieticImmuneCellAtlas](https://contribute.data.humancellatlas.org/submissions/detail?uuid=28ff3c1c-08e9-4e27-833f-04a521e24487)
- [humanBloodCiteSeq2](https://contribute.data.humancellatlas.org/submissions/detail?uuid=5f7fa8b1-f35b-4a2d-b385-c2a686acbc9c)
- [covid19PBMCsTCRandCITEseq](https://contribute.data.humancellatlas.org/submissions/detail?uuid=5fd102f6-8368-40c3-92f6-f0fc3a557aac)
- [normMyometriumAtlasAndLeiomyoma](https://contribute.data.humancellatlas.org/submissions/detail?uuid=4310b292-921c-4e87-a74b-5b8e3ce48c3d)

**Not R26**
- [HumanMelanocyteDevelopment](https://contribute.data.humancellatlas.org/submissions/detail?uuid=251bf9c5-a5e5-4da6-b2ad-93bac7d47eb4)
- [Singlecellsequencingoflungcarcinoma](https://contribute.data.humancellatlas.org/submissions/detail?uuid=6209e5d6-a2de-4bda-bde4-f68be3388046)
- [EmbryonicHindlimb](https://contribute.data.humancellatlas.org/submissions/detail?uuid=ee32b5da-696f-4f65-bf0e-83be66e88122)
- [THP1StimulationCells](https://contribute.data.humancellatlas.org/submissions/detail?uuid=4f40bcbf-6c56-422c-ac8a-3f162f818595)
- [SingleCelleQTLCoexpressionAnalysis](https://contribute.data.humancellatlas.org/submissions/detail?uuid=378455be-3938-4713-abfa-7584e1f63942)
- [BenchmarkingSingleCellProtocols](https://contribute.data.humancellatlas.org/projects/detail?uuid=6e177195-0ac0-468b-99a2-87de96dc9db4)

**Actions**
- [x] Define the list of datasets stuck in an exporting-related status
- [x] Investigate datasets
- [x] Derive actions from investigation

**Comment by ESapenaVentura** [comment]
Done, I have divided them in R26 and non-release 26 to help us prioritise

**Comment by rachadele** [comment]
R26:

- [normMyometriumAtlasAndLeiomyoma](https://contribute.data.humancellatlas.org/submissions/detail?uuid=4310b292-921c-4e87-a74b-5b8e3ce48c3d&project=aa55000c-0168-48d8-9026-2d3a76ec8af3https://contribute.data.humancellatlas.org/submissions/detail?uuid=4310b292-921c-4e87-a74b-5b8e3ce48c3d&project=aa55000c-0168-48d8-9026-2d3a76ec8af3)

**Comment by Wkt8** [comment]
@ESapenaVentura to create a ticket for re-exporting datasets and (if successful) sending the import forms for the datasets.

**Comment by ESapenaVentura** [comment]
All these datasets have been taken into account for re-export in this ticket: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/1082

There are 2 exceptions:
- [Tang-Human-IgAN-GEXSCOPE](https://contribute.data.humancellatlas.org/submissions/detail?uuid=cb989b6e-bab9-432c-895d-ea8d2aa1ebab): Already exported, its status just needs to be fixed.
- [EmbryonicHindlimb](https://contribute.data.humancellatlas.org/submissions/detail?uuid=ee32b5da-696f-4f65-bf0e-83be66e88122): Archiving status, this is a totally different story

We can move this ticket to done (When the ZenHub gods bless us with a board)
