### ISSUE TITLE
Assemble list contributor matrices and cell type annotation for MVP DCP2 release

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#108]
We need to provide a list of contributor matrices and cell-type annotation for the MVP DCP2 release so they can be part of the first snapshot.

We need to create a spreadsheet/tsv file which has the following four columns.
Here is a link to the spreadsheet: https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit#gid=0

1. project UUID
2. filename
3. file type (gene expression matrices, cell type annotation file, other)
4. file source (GEO, ArrayExpress, Contributor)

The files themselves should be uploaded to a GCP bucket, but we don't know where yet.

This task must be completed in this sprint, but no heroic measures should be taken to acquire this data.
There is no expectation of file format standardization or metadata harmonization within the files.

The expected source of files

1. Cell type annotation files produced for the March 2020 release 
2. Expression files from GEO/ArrayExpress
3. Responses to emails sent to contributors to ask for cell-type annotation/matrix files in loom/h5ad format (single emails to be sent with a clear deadline, no expectation of chasing)

Existing documents associated with this task
The plan overview https://docs.google.com/document/d/184dWgyqPUW2Kirt5C1VF9EXVRR58wTgFXtxHFPHel_0/edit#
The list of possible datasets (needs to be crosschecked with what will be uploaded) https://docs.google.com/document/d/1af-E-sGAvrTNyYdp_nsRDFka_q4BSG4djV4CQ2AfTjs/edit

**Checklist:**
- [x] Cross check what new DCP2 datasets will be uploaded
- [x] What is the location of the GCP bucket the files need to be uploaded to
  - gs://hca-prod-ebi-matrices
  - https://console.cloud.google.com/storage/browser/hca-prod-ebi-matrices
- [ ] Where are all the expression and cell-type annotation files
- [x] Emailing all contributors if needed for loom/h5ad files and/or cell type annotation

**Acceptance criteria for the task:**

- [x] Files uploaded to specified dropbox
- [x] Spreadsheet produced listing four columns specified above
- [ ] A list of projects which should not have contributor matrices/cell type annotation associated with them

**Comment by lauraclarke** [comment]
Bucket setup is being established here https://github.com/DataBiosphere/azul/issues/2136

I have asked for access for @rolando-ebi and @rdgoite as the dev people on operations this sprint  and next, more people can always be requested

**Comment by mshadbolt** [comment]
I created a sheet as specified here in the brokering folder: https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit#gid=0

The housing folder for files and the sheet is here: https://drive.google.com/open?id=1FMjJwYamMyuCtNJoTiA30kM3vsL6Q8LD

@lauraclarke I have added the tissue sensitivity study as a pilot, do you think the files and the way the spreadsheet is filled looks suitable?

**Comment by lauraclarke** [comment]
That spreadsheet looks good

Isn't c4077b3c-5c98-4d26-a614-246d12c2e5d7.TissueSensitivity-Lung-10x_cell_type_2020-03-12.csv cell type annotation though rather than other?

If those files could be uploaded to the GCP bucket and we can give UCSC both this file and tell them the actual files are in the bucket that would be great, then they could give us feedback

**Comment by mshadbolt** [comment]
yes that makes more sense. do we think it is a good idea to prefix with the project uuid? I don't like having such long names but at least it makes the files unambiguous. 

I had thought of also having subdirectories per project, but not sure if that is needed/wanted but will ask ucsc

**Comment by lauraclarke** [comment]
I think the UUID is a good way to ensure filename uniqueness without having do a massive amount of checking, I guess the project short name might also work if you would rather have something human-readable but that might create as many challenges as it resolved.

For sub-directories I don't know which is easier from a downstream perspective, all the files or subdirectories so checking sounds like a good plan

I will try and remember to figure out who other than Hannes is on point for this, it might be Daniel Sothos but I will confirm at the leadership MVP catch up today at 4 pm.

**Comment by mshadbolt** [comment]
ok thanks for confirming

 I just tried uploading some test files to the bucket and it doesn't seem to work, I will post on the ticket referred to above

**Comment by lauraclarke** [comment]
I think Hannes already closed that ticket so it might be better to create a new one or also ping Daniel and Hannes on slack

**Comment by mshadbolt** [comment]
I am now trying with the `gsutil` command line tool instead and it might be working, it is fairly slow and the h5ad files are quite large so won't know for a while.

**Comment by lauraclarke** [comment]
Trevor confirms Daniel Sothos is the right contact for their needs on this. I guess pointing him to this ticket is probably a good idea

**Comment by mshadbolt** [comment]
yep he has already fixed for me

**Comment by lauraclarke** [comment]
From trevor on how to indicate files which fall into more than one category
"We suggest 3 columns (1 for each file type), and check all that are applicable to that file (i.e. that row)."

**Comment by mshadbolt** [comment]
@danielsotirhos just letting you know I have started uploading files to gs area, so you could use for **testing** for what needs to be done in terms of building sub-graphs for these files. Let me know if there is anything unexpected with the folder structure or naming. 

Also don't consider these the 'final' files as yet, we want to get confirmation from contributors.

Also wanted to point out some files are from new projects that weren't a part of DCP1 so won't be in the system as yet.

**Comment by mshadbolt** [comment]
UCSC team said they want all files in the staging bucket by 2 weeks before the release deadline, the deadline is 18th of September so our deadline for this task is now end of business, Friday 4th September

**Comment by mshadbolt** [comment]
@lauraclarke just to confirm, if for a project I have found a gene expression matrix and cell type annotations I still need to email the contributor to check if that's what they want released? 

Or do I only need to email people if I can't find appropriate files?

**Comment by ami-day** [comment]
I have emailed authors of the projects I worked on to ask for cell type annotations and expression matrices. They were not available through the publication supplements. The raw expression matrix if consistently available in GEO.

**Comment by mshadbolt** [comment]
All files we have received have been uploaded to the provided google storage area and the UCSC team have been informed about them on HCA slack dcp2 channel

I consider this one done, I am confused by a couple of the acceptance criteria above but if someone disagrees feel free to reopen

**Comment by lauraclarke** [comment]
@mshadbolt The last one was so we knew the numbers and when UCSC post their summary table for the release we could confirm that nothing had been misattributed

**Comment by danielsotirhos** [comment]
@mshadbolt @lauraclarke According to the spreadsheet the following files should exist but were not found:
```
gs://hca-prod-ebi-matrices/abe1a013-af7a-45ed-8c26-f3793c24a1f4-KidneySingleCellAtlas/abe1a013-af7a-45ed-8c26-f3793c24a1f4.Fetal_full.h5ad
gs://hca-prod-ebi-matrices/abe1a013-af7a-45ed-8c26-f3793c24a1f4-KidneySingleCellAtlas/abe1a013-af7a-45ed-8c26-f3793c24a1f4.Mature_Full_v2.1.h5ad
gs://hca-prod-ebi-matrices/f83165c5-e2ea-4d15-a5cf-33f3550bffde-FetalMaternalInterface/f83165c5-e2ea-4d15-a5cf-33f3550bffde.FetalMaternal-Decidua-10x_cell_type_2020-03-12.csv
gs://hca-prod-ebi-matrices/f2fe82f0-4454-4d84-b416-a885f3121e59-FetalLiverHaematopoiesis/f2fe82f0-4454-4d84-b416-a885f3121e59.supp_table_s6.csv
gs://hca-prod-ebi-matrices/42d4f8d4-5422-4b78-adae-e7c3c2ef511c-HumanAdiposeTissue/42d4f8d4-5422-4b78-adae-e7c3c2ef511c.GSE128890_RAW.tar
gs://hca-prod-ebi-matrices/7027adc6-c9c9-46f3-84ee-9badc3a4f53b-Pitx2DevelopingHeart/7027adc6-c9c9-46f3-84ee-9badc3a4f53b.GSE131181_e10.5.meta.data.csv.gz
gs://hca-prod-ebi-matrices/7027adc6-c9c9-46f3-84ee-9badc3a4f53b-Pitx2DevelopingHeart/7027adc6-c9c9-46f3-84ee-9badc3a4f53b.GSE131181_e10.5.raw.data.csv.gz
gs://hca-prod-ebi-matrices/7027adc6-c9c9-46f3-84ee-9badc3a4f53b-Pitx2DevelopingHeart/7027adc6-c9c9-46f3-84ee-9badc3a4f53b.GSE131181_e10.5.scale.data.csv.gz
gs://hca-prod-ebi-matrices/7027adc6-c9c9-46f3-84ee-9badc3a4f53b-Pitx2DevelopingHeart/7027adc6-c9c9-46f3-84ee-9badc3a4f53b.GSE131181_e13.5.meta.data.csv.gz
gs://hca-prod-ebi-matrices/7027adc6-c9c9-46f3-84ee-9badc3a4f53b-Pitx2DevelopingHeart/7027adc6-c9c9-46f3-84ee-9badc3a4f53b.GSE131181_e13.5.raw.data.csv.gz
gs://hca-prod-ebi-matrices/7027adc6-c9c9-46f3-84ee-9badc3a4f53b-Pitx2DevelopingHeart/7027adc6-c9c9-46f3-84ee-9badc3a4f53b.GSE131181_e13.5.scale.data.csv.gz
gs://hca-prod-ebi-matrices/b4a7d12f-6c2f-40a3-9e35-9756997857e3-Lung_Fibroblasts/b4a7d12f-6c2f-40a3-9e35-9756997857e3.GSE129605_RAW.tar
gs://hca-prod-ebi-matrices/2086eb05-10b9-432b-b7f0-169ccc49d270-DevelopingCardiacSystem/2086eb05-10b9-432b-b7f0-169ccc49d270.GSE132658_RAW.tar
gs://hca-prod-ebi-matrices/2ef3655a-973d-4d69-9b41-21fa4041eed7-HumanAdultKidneyLiaoMiao/2ef3655a-973d-4d69-9b41-21fa4041eed7.GSE131685_RAW.tar
```

**Comment by mshadbolt** [comment]
@danielsotirhos apologies for missing those, currently uploading, will let you know when complete

**Comment by mshadbolt** [comment]
For the FetalLiverHaematopoieis there was a typo in the file name, it is an upper case S i.e.
`https://console.cloud.google.com/storage/browser/_details/hca-prod-ebi-matrices/f2fe82f0-4454-4d84-b416-a885f3121e59-FetalLiverHaematopoiesis/f2fe82f0-4454-4d84-b416-a885f3121e59.supp_table_S6.csv` 

some have inconsistencies in the folder naming which I will harmonise

**Comment by mshadbolt** [comment]
@danielsotirhos can you have another check and see that you can find all the files ok?

**Comment by mshadbolt** [comment]
just clarifying, 3 files were outright missing, the others had different naming which I largely matched above, though I didn't fix the upper case S in the fetal liver file in the cloud storage, I just updated the name in the google sheet

**Comment by danielsotirhos** [comment]
@mshadbolt Thank you, using the latest [spreadsheet](https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit#gid=0) (minus rows missing a file name) I found just one missing file.
```
gs://hca-prod-ebi-matrices/42d4f8d4-5422-4b78-adae-e7c3c2ef511c-HumanAdiposeTissue/42d4f8d4-5422-4b78-adae-e7c3c2ef511c.GSE128890_RAW.tar
```

Looks like it was placed in an extra subdir?
```
42d4f8d4-5422-4b78-adae-e7c3c2ef511c-HumanAdiposeTissue/42d4f8d4-5422-4b78-adae-e7c3c2ef511c_GSE128890_HumanAdiposeTissue/42d4f8d4-5422-4b78-adae-e7c3c2ef511c.GSE128890_RAW.tar
```

**Comment by mshadbolt** [comment]
d'oh I thought I fixed those, fixing...

**Comment by mshadbolt** [comment]
I think I fixed it @danielsotirhos

**Comment by danielsotirhos** [comment]
Perfect, all files on the spreadsheet found in the bucket. Thank you @mshadbolt

**Comment by mshadbolt** [comment]
Thanks for confirming  @danielsotirhos !
