### ISSUE TITLE
Investigate exports for R26 from import form

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1080]
**Description of the issue**
From all of the datasets with import forms filled out for R26, investigate how many of them have not got to a finished status (Exported, submitted)

**List of R26 datasets according to import form**
- https://contribute.data.humancellatlas.org/projects/detail?uuid=f3825dfe-990a-431f-b971-9c26d39840db
- https://contribute.data.humancellatlas.org/projects/detail?uuid=c5b475f2-76b3-4a8e-8465-f3b69828fec3
- https://contribute.data.humancellatlas.org/projects/detail?uuid=2d4d89f2-ebeb-467c-ae60-a3efc5e8d4ba
- https://contribute.data.humancellatlas.org/projects/detail?uuid=3ce9ae94-c469-419a-9637-5d138a4e642f
- https://contribute.data.humancellatlas.org/projects/detail?uuid=cd9d6360-ce38-4321-97df-f13c79e3cb84
- https://contribute.data.humancellatlas.org/projects/detail?uuid=7c599029-7a3c-4b5c-8e79-e72c9a9a65fe
- https://contribute.data.humancellatlas.org/projects/detail?uuid=c281ab63-7b7d-4bdf-b761-9b1baaa18f82

**Acceptance criteria**
- [x] All projects have been assessed and the assessment properly indicated in the ticket
- [x] The import team has been informed about these issues

**Comment by ESapenaVentura** [comment]
**Complete/Exported**
- https://contribute.data.humancellatlas.org/projects/detail?uuid=f3825dfe-990a-431f-b971-9c26d39840db
- https://contribute.data.humancellatlas.org/projects/detail?uuid=2d4d89f2-ebeb-467c-ae60-a3efc5e8d4ba&tab=upload
- https://contribute.data.humancellatlas.org/projects/detail?uuid=cd9d6360-ce38-4321-97df-f13c79e3cb84&tab=upload
- https://contribute.data.humancellatlas.org/projects/detail?uuid=c281ab63-7b7d-4bdf-b761-9b1baaa18f82&tab=upload
**Exporting**
- https://contribute.data.humancellatlas.org/projects/detail?uuid=c5b475f2-76b3-4a8e-8465-f3b69828fec3
- https://contribute.data.humancellatlas.org/projects/detail?uuid=3ce9ae94-c469-419a-9637-5d138a4e642f&tab=upload
- https://contribute.data.humancellatlas.org/projects/detail?uuid=7c599029-7a3c-4b5c-8e79-e72c9a9a65fe&tab=upload (Put to graph valid by accident when trying to move another dataset, but was stuck in exporting)

**Comment by ESapenaVentura** [comment]
Actions:
@ESapenaVentura to contact nathan to inform about those 3 datasets, for them to not be imported
@ESapenaVentura to contact the main wranglers for those 3 datasets, so that they can send another import form for the next release

**Comment by Wkt8** [comment]
Main wranglers to export these 3 datasets and fill in import forms for the release - this will work as a test for the ingest system.
