### ISSUE TITLE
GSE202109 - KidneySexBasedTranscriptome

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1081]
### Project short name:
KidneySexBasedTranscriptome
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1sQ1C-V8xD9V87WF_YVSvPJrz4BlaiyH3)

### Published study links

* Paper: [Single-cell profiling of healthy human kidney reveals features of sex-based transcriptional programs and tissue-specific immunity](https://doi.org/10.1038/s41467-022-35297-z)

* Accessioned data: [GSE202109](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE202109)

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=77c13c40-a598-4036-807f-be09209ec2dd&tab=project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
**Donors**
I'm going to send an email to confirm that the donor metadata is correct, there is a mismatch between GEO, UCSC cell browser and the supplementary material


Otherwise ready for secondary review, it's graph valid!

**Comment by Wkt8** [comment]
Apart from the above issue with the mismatch between donor metadata, looks good! Just a couple minor comments - 

Dissociation Protocol:

Change description of mechanical_dissociation
All living donor samples used for sequencing were processed within one hour of organ retrieval. Briefly, biopsies were collected in RPMI 1640 on ice, and mechanically dissociated with a blade **before enzymatic dissociation.** 


Change description of enzymatic_dissociation 
**After mechanical dissociation, specimens were enzymatically digested** at 37 °C with 0.1 mg/ml DNase I, 3300 CDA units/ml Collagenase MA  and 1430 NP units/ml BP neutral protease for 20 minutes at 37 °C with intermittent agitation in a dissociation protocol optimized to maximize viability and to preserve representation of rare and fragile cell populations

**Comment by idazucchi** [comment]
thanks for reviewing! I've applied your suggestions 
I'm pinging the authors again to confirm the donor metadata before submitting

**Comment by idazucchi** [comment]
I got the correct donor metadata from the authors, updated the submission and exported the dataset

**Comment by ESapenaVentura** [comment]
Done

**Comment by idazucchi** [comment]
To update:
- missing cell barcode ontology terms
