### ISSUE TITLE
GSE154027 - RegulatoryMapPostnatalLung

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1083]
### Project short name: 
RegulatoryMapPostnatalLung

_Part of Lung v2.0 atlas_

### Primary Wrangler:
Ida

### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1UEafiqsSLiJeyE01ClX08l8jlIBv6x-9)

### Published study links

* Paper: [A single-cell regulatory map of postnatal lung alveologenesis in humans and mice](https://www.sciencedirect.com/science/article/pii/S2666979X22000283)

* Accessioned data: [GSE154027](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE154027)

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=92afaa56-d501-481e-a027-dddd72212ba8)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
All data and metadata needed for wrangling are available. Experimental design is described thoroughly in paper's methods.

# Proccessed data available on GEO:
- accessible peaks bed file for human and mouse
- binary count matrices for human and mouse

# Metadata
- donors metadata available on Table S1
- plate and sample name available on cell_name

No action in advance needed.

**Comment by idazucchi** [comment]
would this be eligible for cellxgene? I'm not sure

mouse strain --> based on [this resources](https://www.jax.org/news-and-insights/jax-blog/2016/june/there-is-no-such-thing-as-a-b6-mouse) from JAX I think the mouse strain ontology can't be filled out 
Is it worth sending an email about it?

**Comment by arschat** [comment]
## Secondary review

Very nice submission! I have only few comments.

### Library preparation
- Nucleic acid source should be `single nucleus` instead of `single cell`
### Sequencing protocol
- Fastq creation method & version can be added: `bcl2fastq` and `v2.17.1.14`
### Analysis protocol
- `bcl2fastq` maybe should be mentioned in the seq protocol and not here
- There is a typo after bcl2fastq `:` instead of `;`
### Analysis file
- Genome version for mouse should be `GRCm38` instead of `GRCh38`

**Comment by idazucchi** [comment]
I applied the corrections and I'm exporting

**Comment by idazucchi** [comment]
I've updated the descriptions in ingest and tried to export but I suspect it got stuck

**Comment by idazucchi** [comment]
the submission was exported and I filled out the import form

**Comment by idazucchi** [comment]
verified in the Data Browser
