### ISSUE TITLE
Generate a spreadsheet template for RNA-Seq experiments

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1085]
**Description of the issue**
Based on the data and metadata provided by JAX, generate a spreadsheet that would collect the necessary metadata and present it to the DWG meeting.

**Comment by anu-shiva** [comment]
Presented the spreadsheet to DRACC. @ESapenaVentura to contact Bill?

**Comment by gabsie** [comment]
@gabsie to review the draft doc for the spreadsheet, to try send email today.
