### ISSUE TITLE
stuck in export: Landscape-ileum-colon

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1087]
*Project Info*
uuid: `cae461de-ecbd-482f-a5d4-11d607fc12ba`
project short name: Landscape-ileum-colon
primary wrangler: Rachel Schwartz

*background*
* slack link: 
* email: 

Note:
assign to the current dev on operations.

**Comment by rachadele** [comment]
@willrockout is re-triggering file validation

**Comment by gabsie** [comment]
@ESapenaVentura to take a look. If there are errors in ingest, we can check first with Rachel if she attended to them.

**Comment by gabsie** [comment]
to try reexport @ESapenaVentura

**Comment by idazucchi** [comment]
still stuck in exporting - 1k enetities, might have crushed ingest

**Comment by idazucchi** [comment]
@ESapenaVentura to add this to #1082
