### ISSUE TITLE
GSE157997_The ZIP8/SIRT1 axis regulates alveolar progenitor cell renewal in aging and idiopathic pulmonary fibrosis

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1088]
### Associated files

* [Google Drive](https://drive.google.com/drive/folders/10fYwxP5ls45BecvFvpUCCGTOF8SONG8n)

### Published study links

* Paper: [Jiang_X](https://www.jci.org/articles/view/157338)

* Accessioned data: [GSE157997](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE157997)
 
[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=e456c042-f6b6-4cec-a338-1a8ef80bd779)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Anu is waiting to export this as a demo with Alex and Dipayan next week
