### ISSUE TITLE
re-wrangle Single cell sequencing of lung carcinoma

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1090]
### Project short name:
SingleCellSequencingOfLungCarcinoma
### Primary Wrangler:
Ida

### Secondary Wrangler:
Anu

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1sKrpgMqZYRUMAIHelSoXOrsSlpUsrSt7)

### Published study links

* Paper: Phenotype molding of stromal cells in the lung tumor microenvironment. Lambrechts D, Wauters E, Boeckx B, Aibar S, Nittner D, Burton O, Bassez A, Decaluwé H, Pircher A, Van den Eynde K, Weynand B, Verbeken E, De Leyn P, Liston A, Vansteenkiste J, Carmeliet P, Aerts S, Thienpont B. Nature Medicine (2018), PMID:29988129
[10.1038/s41591-018-0096-5](https://doi.org/10.1038/s41591-018-0096-5)

* Accessioned data: 
    * [E-MTAB-6149](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-6149)
    * [E-MTAB-6653](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-6653)

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=453d7ee2-319f-496c-9862-99d397870b63)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by gabsie** [comment]
@gabsie to check whether this is still in the list.

**Comment by idazucchi** [comment]
E-MTAB-6149
wrangled fastqs + analysis files

E-MTAB-6653
Only bam files are available but `bamtofastq` doesn't work

```
bamtofastq_linux Sample_2c.bam.1 fastqs
bamtofastq v1.4.1
WARNING: no @RG (read group) headers found in BAM file. Splitting data by the GEM well marked in the corrected barcode tag.
Reads without a corrected barcode will not appear in output FASTQs
Unrecognized 10x BAM file. For BAM files produced by older pipelines, use one of the following flags:
--gemcode   BAM files created with GemCode data using Longranger 1.0 - 1.3
--lr20      BAM files created with Longranger 2.0 using Chromium Genome data
--cr11      BAM files created with Cell Ranger 1.0-1.1 using Single Cell 3' v1 data
```
It's possibly a [known issue](https://support.10xgenomics.com/docs/bamtofastq#issues), I'm checking with the ENA helpdesk if they are able to generate fastqs ([thread](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/MNHXvYpt-_Y))

To do:
- [ ] project
- [ ] hca-util area
- [ ] ontologies
- [ ] bam or fastq for E-MTAB-6653

**Comment by idazucchi** [comment]
ENA is not equipped to convert 10x bam files!
I can suggest the 10x_bam_to_fastq to the team, but it won't solve the issue for this dataset - should I get in touch with the authors?

**Comment by idazucchi** [comment]
I found the original fastqs through ArrayExpress - this is next on my todo list

**Comment by idazucchi** [comment]
- [ ] fix the read type for 6149

**Comment by idazucchi** [comment]
Ready for secondary review!

**Comment by anu-shiva** [comment]
The spreadsheet looks great, very minor comments-

- In Supplementary table 2 (page 22), it seems to be that the cell count is provided for the individual cell suspensions. This could possibly go in the **cell suspension** tab.
- In the **analysis protocol** tab and files-  II see the cell filtering etc in the derivation process. I was wondering if this still counts as a part of raw matrix generation? and in the **analysis files**  allsamples.rds.gz is not be a processed matrix? 
Could this be split as raw and processed?

**Comment by idazucchi** [comment]
- the cell count in table 2 looks more like the number of cells that passed QC rather than an estimated cell count for the cell suspension
- I'm going to change the analysis protocol to `processed matrix generation` since it's more accurate

**Comment by idazucchi** [comment]
Verified in the broser
