### ISSUE TITLE
SCP1289 - Impaired local intrinsic immunity to SARS-CoV-2 infection in severe COVID-19

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1091]
### Project short name:
Shalek-Human-SeqWellS3

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1-xo2YZ3YJNqPrzjotjsEaICKzQRf9PV6)

### Published study links

* Paper: [Impaired local intrinsic immunity to SARS-CoV-2 infection in severe COVID-19](https://doi.org/10.1016/j.cell.2021.07.023)

* Accessioned data: https://singlecell.broadinstitute.org/single_cell/study/SCP1289

* Ingest [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=111d272b-c25a-49ac-9b25-e062b70d66e0)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Will use 1 cell suspension for each specimen after [this slack](https://embl-ebi-ait.slack.com/archives/C016FKV4JS1/p1683033830957539) discussion.

**Comment by arschat** [comment]
After submitting, get the following error in ingest:
`Project is Invalid. Please go back and edit the project.`
`* should NOT have additional properties at root of document`

Investigating.

**Comment by anu-shiva** [comment]
edit the project fields through API and to edit the template

**Comment by arschat** [comment]
New submission is now graph valid, and ready for secondary review.

**Comment by idazucchi** [comment]
Hi Arsenios! The dataset looks great I only have two comments:

Specimen
- I'd suggest `cryopreservation, other` since the cells are not dead 

Analysis protocol
- you can add the derivation process

Analysis file
- there is no good ontology label for UMAP in HCAO right now, maybe it would be worth it to open an ontology ticket and request a new term
- I think you swapped the protocols for `20210220_NasalSwab_NormCounts.txt` and `20210220_NasalSwab_RawCounts.txt`

**Comment by arschat** [comment]
Applied sec review suggestions (thanks Ida), and submitted.
Input form to be filled when exported.

**Comment by arschat** [comment]
Input form sent

**Comment by ESapenaVentura** [comment]
Error in R28 - Neither project nor supplementary file metadata have submission_date stablished (Value: `null`). This may have been a side effect of programmatic updates.

Actions: 
- [ ] Update staging area with submission date (Take from submission entity) for both project and supplementary file metadata
- [ ] Update ingest with that same information for project

**Comment by amnonkhen** [comment]
I believe we have a gap in our validation process. Our metadata validation should have caught this error. Please create a bug ticket.

**Comment by ESapenaVentura** [comment]
yep - system fields are not validated because they are generated on the go

**Comment by ofanobilbao** [comment]
@ESapenaVentura to confirm if we need to do the changes in Ingest. Otherwise this ticket could move to close right?

**Comment by ofanobilbao** [comment]
Was this resolved by Amnon as part of the R28 errors remaining to be sorted in Ingest that Amnon did last week? @ESapenaVentura ? Trying to understand if we can close this

**Comment by idazucchi** [comment]
missing submissionDate was add back to ingest by Amnon - this ticket can be closed!
