### ISSUE TITLE
GSE136831 - COPDalveolarNiche

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1092]
### Project short name:
COPDalveolarNiche
### Primary Wrangler:
Enrique
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/114irVPxmVwsJcNZLWYAyvR1CqAT7mcEe) 

### Published study links

* Paper: [Characterization of the COPD alveolar niche using single-cell RNA sequencing](https://doi.org/10.1038/s41467-022-28062-9)

* Accessioned data: 
   - [GSE136831](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE136831) - scRNA-seq patients
   - [GSE168299](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE168299) - scRNA-seq mouse
   - ~~[GSE47460](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE47460)~~ - microarray from total RNA

* Ingest [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=d8d2419a-ea4b-49fa-8cae-e87d597d2031)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
I'm not sure which accession the network is interested in. My guess would be GSE136831 - scRNA-seq patients but the original paper for this data is actually  [Single-cell RNA-seq reveals ectopic and aberrant lung-resident cell populations in idiopathic pulmonary fibrosis](https://doi.org/10.1126/sciadv.aba1983)

The re-analysis paper uses a subset of the accession too.

I've emailed Ciro (lung bionetowork) and I'm waiting for a reply

**Comment by ofanobilbao** [comment]
Linking the two tickets here not to forget they both reference one single entry in the Lung Bionetwork tab (Rosas_Kaminsky 2022). #1084

**Comment by arschat** [comment]
only human data are required. @idazucchi to check if the fastq files exist in the DCP

**Comment by idazucchi** [comment]
lungPopulationsIPF was publisehd in the DCP in April 2022, while fastq files from GSE136831 only became public on 2022-10-03 so they are not in DCP.
I'm checking with CIro if they need both analysis and sequence files, but regardless of that I think we should update the project and add sequence files

reopening the [old ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/750) for lungPopulationsIPF ?

**Comment by ofanobilbao** [comment]
@gabsie to reach out the lung integration contact. We can close the ticket. @ESapenaVentura to reference the zenhub ticket in Ingest and mark as stalled.
