### ISSUE TITLE
Test updating project to include bionetworks information

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1095]
**Description of the task:**
For testing purposes, we want to test updating a project JSON to the latest version ([17.1.0](https://schema.humancellatlas.org/type/project/17.1.0/project))

The chosen dataset is ebi-ait/hca-ebi-wrangler-central#1031

**Acceptance criteria for the task:**
- [x] Project has been updated to 17.1.0

**Comment by ofanobilbao** [comment]
Some of the new datasets have already the information. So probably no need to test anything.
@arschat to add link to the dataset that already contains the information

**Comment by ESapenaVentura** [comment]
Pushed the latest bionetworks schema PR to do this - Project has v17.1.1 now.

Submission does not move status - I am going to restart the state tracker

**Comment by ESapenaVentura** [comment]
Pushed the latest bionetworks schema PR to do this - Project has v17.1.1 now.

Submission does not move status - I am going to restart the state tracker

**Comment by ESapenaVentura** [comment]
Project done - No need to send an import form
