### ISSUE TITLE
KidneyFibroticMicroenvironment

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1096]
### Project short name:
KidneyFibroticMicroenvironment
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1oCEUX3JMpTkLqIgwXx4xwr8ymO3BQwej)

### Published study links

* Paper: [Spatially resolved human kidney multi-omics single cell atlas highlights the key role of the fibrotic microenvironment in kidney disease progression](https://doi.org/10.1101/2022.10.24.513598)

* Accessioned data: GSE211785 - not public yet! 
 - data available from [dropbox](https://www.dropbox.com/scl/fo/urrpad9q1824ovdh5nurg/h?dl=0&rlkey=q80mm0vnj1am5bb7al16xzo3n)
 - visium images from [drive](https://drive.google.com/drive/folders/1mh6tDpsDDoD7GP0wN5LMP4OG6uwNj4Tq?ts=645a58dd&usp=drive-slack), it might be shared just with Ida
* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=e925633f-abd9-486a-81c6-1a6a66891d23)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
see thread to get the data [here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/ZBHDr_AvOcc/m/YtzQGcdOAQAJ)

**Comment by idazucchi** [comment]
see thread to get the data [here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/ZBHDr_AvOcc/m/YtzQGcdOAQAJ)

**Comment by idazucchi** [comment]
**Donors**
Looks like there are actually 48 donors, HK2895 is repeated in the metadata table. The number of samples is correct though

**Comment by idazucchi** [comment]
this is almost ready for review, I'm just waiting for the authors to send me the image files for Visium

**Comment by idazucchi** [comment]
ready for secondary review!

**Comment by Wkt8** [comment]
Taking for secondary review!

**Comment by Wkt8** [comment]
Looks good! Just a couple minor edits - 

Project Field: 
Change Estimated Cell Count to 453,782? 

Donor_Organism Tab:
Disease Field: 
The annotation in Supplementary Table 1 (patient clinical demographics) is unclear regarding HKD vs Hypertension. There are several individuals marked as in the 'Control' group but who are also marked as 'Yes' for hypertension. These individuals are separate from those marked as in the 'HKD' (hypertensive kidney disease) group, and they should be labelled separately with 'non-kidney specific hypertension' in the disease field, as they are in the control group. 

Dissociation_Protocol Tab: 
ID is sc_mechanical dissociation but the name and ontology term is for enzymatic_dissociation
