### ISSUE TITLE
COPDIncreasesCovid19

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1098]
### Project short name:
COPDIncreasesCovid19

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=2c4647ba-c814-4158-8ea9-6889930e4dfe&tab=project 

### Associated files

* Google Drive:

### Published study links

* Paper: [Increased SARS-CoV-2 Infection, Protease, and Inflammatory Responses in Chronic Obstructive Pulmonary Disease Primary Bronchial Epithelial Cells Defined with Single-Cell RNA Sequencing](https://doi.org/10.1164/rccm.202108-1901oc)

* Accessioned data: NA

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ofanobilbao** [comment]
Where data lives I could not find. Wrangler will need to reach out to contributors

**Comment by idazucchi** [comment]
I've emailed the contributors to ask about the data, I'm moving onto a different dataset in the meantime

**Comment by idazucchi** [comment]
I emailed the authors again, if I don't get a reply in one month I'll close this ticket
