### ISSUE TITLE
Haniffa Fetal Liver

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#110]
**Short name**
FetalLiverHaematopoiesis

**Primary Wrangler:**
Marion

**Secondary Wrangler:**
Paris

**Google drive**
https://drive.google.com/open?id=1Jnz57fWwNud05ktdih5_ZqzLGPm_9NXY

**Publication**
https://www.nature.com/articles/s41586-019-1652-y

[**Ingest**](https://contribute.data.humancellatlas.org/projects/detail?uuid=f2fe82f0-4454-4d84-b416-a885f3121e59)
This is a continuation from https://github.com/HumanCellAtlas/hca-data-wrangling/issues/153

I will be tracking the extra work required to get as much data as possible ready for DCP2 MVP

**Comment by mshadbolt** [comment]
I emailed Muzz and co today to get their go ahead but my general plan of attack here is:
1. Submit the SS2 data as a stand alone submission and progress through archiving
2. Link the 10x expression libraries to the existing donors above in a new submission, but don't submit for archiving (try to have this also include the VDJ libraries)
3. work with ArrayExpress to incorporate the VDJ libraries into the existing ArrayExpress project ([E-MTAB-7407](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-7407/))
4. work with ArrayExpress to create an SS2 project from the submission I made in step 1.

Then when DCP2 is ready, export both the submissions.

**Comment by ESapenaVentura** [comment]
I just reviewed it, I think it's almost ready to go, I have added some minor change:

- in project role for Marion and Anja, the ontology label is missing

And 2 observations:
- For the Fetal donor with stage "l8pcw", I think this term would match in the description: https://www.ebi.ac.uk/ols/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000046 as it describes between 8 and 9 weeks
- The last cell suspension doesn't have an estimated cell count, was it missing from the metadata or is it just an oversight?

Otherwise, LGTM 👍

**Comment by mshadbolt** [comment]
This is 'done' in terms of MVP. I would like to one day add SS2 and VDJ to this project

**Comment by mshadbolt** [comment]
I'd like to try to finish this before I leave so will try to get in contact with the lab next week

**Comment by mshadbolt** [comment]
sadly I have not really progressed this since Aug 2020 :( sorry for leaving a bit of a mess for this. I think I ran into various road blocks at various times and wasn't the best at navigating around them and was hoping to update when we had more functionality to help with that.

The current data in the DCP reflects what is in ArrayExpress but doesn't contain all data that was referenced in the paper.

I believe the addition of SS2 data will need to be done in two batches because some is referring to existing specimens and some is from a brand new donor. (should be checked with a dev, it may be possible to combine into one spreadsheet instead)

The specimens already in our database are: F06-KID,F06-LIV,F06-SKI, So the SS2 files could be added to ingest using the uuids for these specimens to link to. I created a spreadsheet with that linking here: https://drive.google.com/file/d/1ZhjxkQRYRj_fngNyCdZ0fTnWLJ3XvaQC/view?usp=sharing

The remaining specimen, F17, is not in the original submission so would need to be added as donor, specimen as well as the rest of cell suspension and sequence files. If this donor is added after the submission above, the various protocol duplicates can be referred to by their uuids rather than  I created a spreadsheet with this donor here: https://drive.google.com/file/d/1ZqmEKwdvL9c0gphjsSsFoy-jvC9fVnkX/view?usp=sharing 

I tried out uploading these spreadsheets to ingest to see if they were at least valid, but they cannot progress at the moment due to file format validation not allowing a `.` in the filename apart from the extension of the file.

It would probably be good to also archive the SS2 data publicly somewhere.

I don't think I ever got full confirmation about the VDJ aspects of the data and how they link in to the gene expression libraries that we have already submitted.

General thoughts:
- There was a lot of confusing ID matching because different identifiers are used in the paper vs internal lab tracking 
- happy to have a dedicated meeting about this if it is gotten to in the near future because it was pretty confusing and not sure how easy it is to follow the work I have done
- There are various conversations on the wrangler google group, I had been communicating with Simone and Emily from the Haniffa lab about it. My last attempt at communication was : https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/SieP-KyKaBo/m/xsH-vspyBAAJ

**Comment by Wkt8** [comment]
Going to try and pick this up!

**Comment by Wkt8** [comment]
Deprioritizing over other datasets for now.

**Comment by idazucchi** [comment]
I emailed the authors to see if they have already deposited the missing data from the paper (SS2 and 10x VDJ) or if they need help archiving it.

**Comment by ofanobilbao** [comment]
@idazucchi I guess you have not heard back from the authors on this right?

**Comment by idazucchi** [comment]
no answer so far - I am working on a different project from the same lab, I can try to ask if there is any news for this project as well

**Comment by ofanobilbao** [comment]
@idazucchi I guess we could update the project with that. Did we learn if the authors had published the other data (SS2 and 10x VDJ)? I'll move the Project to needs Update, and if we don't do anything beyond that based on silence from contributors I would add a comment in Ingest, label the Project as Needs Update, and add a reference to the ticket in the notes in Ingest and close this ticket. It's been here forever

**Comment by idazucchi** [comment]
SS2/VDJ data is still missing but cell count matrices are available in Array-Express. No capacity to wrangle them to DCP at the moment 
I've put the details in ingest and I'm closing the ticket for now
