### ISSUE TITLE
GSE154826 - Single-cell analysis of human non-small cell lung cancer lesions refines tumor classification and patient stratification

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1100]
### Project short name:
Merad-Human-10x3pv2 (Name to be changed by wrangler to more human readable if wanted)

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=b208466a-6fb0-4385-8cfb-8e03ff6b939e&tab=project

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1S1xQSVm6-Bmu7sIUzjB9mLaVq5Eclpme

### Published study links

* Paper: [Single-cell analysis of human non-small cell lung cancer lesions refines tumor classification and patient stratification](https://doi.org/10.1016/j.ccell.2021.10.009)

* Accessioned data: [GSE154826](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE154826)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
@Wkt8 to download with ncbi delivery

**Comment by Wkt8** [comment]
Request submitted. should be delivered to hca-ncbi-cloud-delivery within 48 hours.

**Comment by ofanobilbao** [comment]
Quite a big dataset. Probably will go to secondary review today even if the files are not there yet. But Enrique will run graph validation locally and do other checks

**Comment by ofanobilbao** [comment]
@Wkt8 to graph validate the spreadsheet locally and start the review

**Comment by ESapenaVentura** [comment]
Submitted

**Comment by ESapenaVentura** [comment]
Exported, import form submitted

**Comment by ESapenaVentura** [comment]
Reviewed in the browser - I somehow swapped institute with department. Not a huge impact, will solve for next release

**Comment by ESapenaVentura** [comment]
Updated - Filled import form

**Comment by ESapenaVentura** [comment]
Verified - We can close it!
