### ISSUE TITLE
GSE227136 - eQTL-lung

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1101]
### Project short name:
eQTL-lung

### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1IBB9ZkvBCcuNxCAcfAuHQTk6JhL6Mu_R)

### Published study links

* Paper: [Cell type-specific and disease-associated eQTL in the human lung](https://doi.org/10.1101/2023.03.17.533161)

* Accessioned data: [GSE227136](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE227136)

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=7bc1f14b-5e64-4c7f-86b0-23596b97e2aa)
### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
This paper is described as follows: 

Contains unpublished data and previously published data from four separate papers. None of the data is new primary data from this dataset. 

Have decided not to continue wrangling this for now due to not having a way to represent meta-analysis and data that is not primary data in Ingest and the DCP.

**Comment by arschat** [comment]
@idazucchi to contact network if they want all the primary data

**Comment by idazucchi** [comment]
this could be a candidate for [ticket 973](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/gh/ebi-ait/dcp-ingest-central/973)

**Comment by idazucchi** [comment]
discussed in ops review 6-09-23

**Comment by idazucchi** [comment]
I'm trying to figure out which samples are primary data, based on the samples in this [dataset](https://www.nature.com/articles/s41467-021-24467-0#Abs1) and on the samples used for the v1 lung atlas

**Comment by arschat** [comment]
extracted metadata matrix from 23gb seurat object with code here
## Bash
> ssh codon-login
## Codon cluster login-node
> cd /nfs/production/tburdett/hca/arsenios/
> wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE227nnn/GSE227136/suppl/GSE227136%5FILD%5Fall%5Fcelltypes%5FSeurat.rds.gz
> bsub -Is $SHELL
## Codon cluster interactive shell
> module load r-4.1.1-gcc-9.3.0-jkdw35f  
> module load hdf5-1.12.1-gcc-9.3.0-py4fnly  
> module load r-magrittr-2.0.1-gcc-9.3.0-th6svrw  
> module load r-igraph-1.2.6-gcc-9.3.0-r3z6ni3  
> module load r-lattice-0.20-44-gcc-9.3.0-r5kphdk  
> module load r-rcpp-1.0.7-gcc-9.3.0-l2fkz6p
> gunzip /nfs/production/tburdett/hca/arsenios/GSE227136_ILD_all_celltypes_Seurat.rds.gz
> R
## Codon cluster interactive shell R-session
> .libPaths( c('/homes/arsenios/rLib_arsenios', .libPaths() ) )
> library(Seurat)
> seu <- readRDS("/nfs/production/tburdett/hca/arsenios/GSE227136_ILD_all_celltypes_Seurat.rds")
> write.csv(seu@meta.data, "/nfs/production/tburdett/hca/arsenios/GSE227136_ILD_all_celltypes_Seurat.csv")
> quit('n')
## Codon cluster login node (download file)
> _for mac: Apple menu -> System Preferences -> General -> Sharing -> Remote Login *turn on* & click (i) and `Allow full disk access` and get IP used to ssh_
> scp /nfs/production/tburdett/hca/arsenios/GSE227136_ILD_all_celltypes_Seurat.csv USER@XXX.XXX.XXX.XXX:/Users/USER/Desktop/

**Comment by idazucchi** [comment]
Donor
I Included VUHD071_donor because it's one of the samples in the [lung atlas manifest](https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-023-02327-2/MediaObjects/41591_2023_2327_MOESM3_ESM.xlsx) listed for this paper and the corresponding library is in at least one cell count file
There is a big mismatch in the donor numbers/samples between the paper and GEO - the authors are aware and got multiple emails about it apparently - and it's due to GEO asking them to reupload some samples.

I've applied the suggestions and I'm graph validating

**Comment by idazucchi** [comment]
exported and filled import form

**Comment by idazucchi** [comment]
verified in browser
