### ISSUE TITLE
Build consolidated flow of DPC experiments

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1104]
[1. JAX](https://miro.com/app/board/uXjVPhuBdDE=/)
[2. MSK](https://miro.com/app/board/uXjVMZgEKBo=/)
[3. UCSF](https://miro.com/app/board/uXjVMWQIbGg=/)
[4. NWU](https://miro.com/app/board/uXjVMPIj5gM=/)

**Comment by ESapenaVentura** [comment]
https://encyclopedia.pub/entry/28064#:~:text=The%20procedure%20of%20metabolomics%20analysis,impact%20on%20the%20final%20results.

Metabolomics assay explanation

**Comment by ESapenaVentura** [comment]
Rough consolidated workflow for Genomics/transcriptomics (Still pending on lipidomics/metabolomics) https://miro.com/app/board/uXjVMIvmTc8=/?userEmail=enrique@ebi.ac.uk&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-board&utm_content=go-to-board
