### ISSUE TITLE
Automatic Wrangling Status Update after project making it life in the browser not working as expected

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1106]
At least in 2 instances I can see projects that were exported to DCP for Release 26, and have already made it life to the Browser, but where the wrangling status has remained as "Submitted". As this is also linked to the DCP link showing in the Catalog, we are also missing that.

The projects where I've seen this are the following:

https://contribute.data.humancellatlas.org/projects/detail?uuid=f3825dfe-990a-431f-b971-9c26d39840db&tab=project

https://contribute.data.humancellatlas.org/projects/detail?uuid=c281ab63-7b7d-4bdf-b761-9b1baaa18f82&tab=project

Older project in the same situation:
https://contribute.data.humancellatlas.org/projects/detail?uuid=a1375150-dda4-4081-8318-c1593622da55&tab=project

Instances with projects in Submitted status (they are published in DCP already) but Graph invalid submissions:

https://contribute.data.humancellatlas.org/projects/detail?uuid=65858543-530d-48a6-a670-f972b34dfe10&tab=project

https://contribute.data.humancellatlas.org/projects/detail?uuid=34cba5e9-ecb1-4d81-bf08-48987cd63073&tab=project

**Comment by ofanobilbao** [comment]
The 1st two entries, are now resolved. It looks as if there is some sort of delay. Maybe worth adding a bug ticket to investigate at some point.

**Comment by ofanobilbao** [comment]
The last two are two datasets originally wrangled by Tiana Pereira (UCSC)

**Comment by ofanobilbao** [comment]
I am keeping this for the older project and the ones with graph invalid submissions. But I have created a Dev bug for the issue that originally made me open/create this ticket in the first place. I'll link here

**Comment by ofanobilbao** [comment]
https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/gh/ebi-ait/dcp-ingest-central/957

**Comment by idazucchi** [comment]
working on #1220 should address this issue as well
