### ISSUE TITLE
Correct and Re-export Datasets Removed from DCP and not included in R27

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1109]
There were errors encountered during the indexing of catalog dcp27 due to metadata documents containing the `||` character sequence. Two of these projects had been added in previous catalogs, however they were added before stronger validation code was in place to prevent indexing projects with `||` .

Now that that validation is in place, these projects are failing to be indexed in dcp27.

Projects with || will cause issues when generating a manifest from the Data Browser, so these three projects will be removed from the catalogs until we can get an updated version without the `||` character sequence.

Find below the UUID of the projects that have been removed or not added to R27 (the first one in this list) and the fields that have issues:

- [x] [5f607e50-ba22-4598-b1e9-f3d9d7a35dcc](https://contribute.data.humancellatlas.org/projects/detail?uuid=5f607e50-ba22-4598-b1e9-f3d9d7a35dcc): new for dcp27, not included in dcp27 ([CovidImmuneAtlas](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/953))
*donor_organism..biomaterial_description

- [x] [e6773550-c1a6-4949-8643-1a3154cf2670](https://contribute.data.humancellatlas.org/projects/detail?uuid=e6773550-c1a6-4949-8643-1a3154cf2670&tab=project): removed from dcp26, not included in dcp27 ([Milich2021MouseSpinal](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/946))
* analysis_protocol.computational_method
* analysis_protocol.matrix.derivation_process

- [x] [61515820-5bb8-45d0-8d12-f0850222ecf0](https://contribute.data.humancellatlas.org/projects/detail?uuid=61515820-5bb8-45d0-8d12-f0850222ecf0): removed from dcp26, not included in dcp27 ([GSE171668_SingleCellAndSpatialAtlasCovid](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/317))
* I wasn’t able to download the spreadsheet to check everything
* donor_organism.death.cause_of_death

**Comment by ESapenaVentura** [comment]
Staging areas have been cleaned up, @idazucchi to trigger re-export !

**Comment by idazucchi** [comment]
two of them are stuck (?) in graph validation [5f607e50-ba22-4598-b1e9-f3d9d7a35dcc](https://contribute.data.humancellatlas.org/projects/detail?uuid=5f607e50-ba22-4598-b1e9-f3d9d7a35dcc) & [61515820-5bb8-45d0-8d12-f0850222ecf0](https://contribute.data.humancellatlas.org/projects/detail?uuid=61515820-5bb8-45d0-8d12-f0850222ecf0)

**Comment by idazucchi** [comment]
filled out the import form for Milich2021MouseSpinal

**Comment by ESapenaVentura** [comment]
@ESapenaVentura working on this for now

**Comment by ESapenaVentura** [comment]
CovidImmuneAtlas was validated - Exporting

**Comment by ESapenaVentura** [comment]
Dataset broke ingest on export - Broke it at the stage of metadata export

**Comment by ESapenaVentura** [comment]
Dataset broke ingest on export - Broke it at the stage of metadata export

**Comment by ofanobilbao** [comment]
Was submitted by Amnon yesterday. And Arsenios filled out the import form for R28

**Comment by gabsie** [comment]
@ESapenaVentura to ask Mary to include in the release, and fill out import form if necessary.
