### ISSUE TITLE
Single-cell transcriptomic analysis reveals key immune cell phenotypes in the lungs of patients with asthma exacerbation

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1110]
### Project short name:

Yang-Human-10x3pv3 (Zhang_Yang_2021 in Spreadsheet)

### Link to Ingest
https://contribute.data.humancellatlas.org/projects/detail?uuid=54c91ebc-78a2-4616-87c7-7dcedb19903a&tab=project

### Associated files

* Google Drive:

### Published study links

* Paper: https://www.sciencedirect.com/science/article/abs/pii/S0091674920314007

* Accessioned data: tbd

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
No answer until now.
Emailed contributors again.
