### ISSUE TITLE
McCormack-Human-10x3pv2

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1116]
### Associated files

* [Google Drive](https://drive.google.com/drive/folders/1kiRWIQO_ywIAb8IdxIZnOjCQOIulfhhM)

### Published study links

* Paper: [Xu_2020](https://www.atsjournals.org/doi/10.1164/rccm.201912-2445OC)

* Accessioned data: [GSE135851](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE135851)
### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Hey Anu, looks good! Just a couple things that I wasn't sure where you got the information from. 

Project_Cell_Count 
- seems really low, where did you get this number from? 
- 12374 cells? 
- In the paper just the LAM cells are already 21,964 cells 

Dissociation_protocol
- Optional, but consider splitting up the "Tissue pieces were dounced 40 times with a loose pestle followed by 20 times with a tight pestle and transferred to a 15 mL conical tube to which 2 mL of Nuclei EZ lysis buffer was added." into a 
	- mechanical and 
	- non-enzymatic chemical dissociation nuclei extraction step 

Enrichment_protocol
- Why are they using uM as the units? micromolar? Shouldn't it be micrometers... 
- Should the maximum size for enrichment_single_nuclei_size be 30um? 
- There is a typo in the cell markers for (enrichment_single_nuclei_facs) 'DAPI + s'

Cell_suspension
- cell viability should be 'pass' 
- There aren't any dissociation or enrichment protocols for the normal single-cell lung 
	- We could potentially assume here that as a control it underwent the same protocols as the LAM scRNA-seq lungs. Or we could send an email checking this. 

Sequencing_protocol
- For some reason, the GEO page states that a number of the samples were sequenced using Illumina HiSeq 2500 even though it's not mentioned anywhere in the paper

**Comment by anu-shiva** [comment]
Hi Wei! Thanks for the comments, I have made the changes.

- So the cell count of 12374 was generated by Ingest. Corrected it to 21,964.
- enrichment - ya I think they misspelled it as uM in the supplemental info  instead of um. I have changed this,
- for seq protocol- I could not find Illumina HiSeq 2500 anywhere - it might be a mistake on the SRA.

**Comment by arschat** [comment]
As mentioned in #1205 an update on the linking needs to be done (cell suspension is linked directly to donors)

**Comment by arschat** [comment]
Link update was done through ingest UI, exporting

**Comment by arschat** [comment]
Closing as last update was verified in browser.
