### ISSUE TITLE
GSE155249 - Circuits between infected macrophages and T cells in SARS-CoV-2 pneumonia

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1117]
### Project short name: 
Budinger-Human-10x

### Primary Wrangler: 
Wei

### Secondary Wrangler:
ida

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1UGVJiVRbiTI0uWRckWuBsySoBgCNUy0w

### Published study links

* Paper: https://www.nature.com/articles/s41586-020-03148-w

* Accessioned data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE155249
* 
Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=b91c623b-1945-4727-b167-0a93027b0d3f&tab=project

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Graph valid! Ready for secondary review.

**Comment by Wkt8** [comment]
Edited, exporting, need to fill in the import form once export is confirmed done.

**Comment by ofanobilbao** [comment]
Exported and import form submitted
