### ISSUE TITLE
GSE123904 - RegenerativeLineagesLungMetastasis

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1118]
### Project short name:
RegenerativeLineagesLungMetastasis
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1zWEGrrwA5E3gDJmy6ln15D2LaMK7vhGs)

### Published study links

* Paper: [Regenerative lineages and immune-mediated pruning in lung cancer metastasis](https://doi.org/10.1038/s41591-019-0750-6)

* Accessioned data: superseries [GSE123904](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE123904)
   *  [GSE123903](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE123903) mouse host, humans scRNA-seq
   *  [GSE123902](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE123902) human scRNA-seq
* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=bc5512cc-9544-4aa4-8b75-8af445ee2257)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
**Mouse host data**
Mice are employed as xenograft metastasis model. Mice are injected with H2087-LCCs (lung cell cancer) then:
1. metastasis are collected from 6 mice, cultured with antibiotic to select human cells over host cells
> We isolated lung cancer cells from two BLI-negative kidneys that showed no signs of metastasis, yet contained DTCs. We also isolated cancer cells from one case of incipient lung metastasis and from three individual lung macrometastases that evolved spontaneously. 
Cells were uniformly isolated through antibiotic selection for one passage in culture and then subjected to scRNA-seq. This selection step, which was essential because DTCs are extremely rare, likely has some effect on gene expression and is a limitation of our model.
2. 6 mice are treated to depleate NK cells, to increase metastasis potential. Metastasis are collected
> H2087-LCCs were intracardially injected  into the arterial circulation of athymic mice. Thirty days later, we administrated anti-GM1 antibody to trigger NK cell depletion which facilitates the robust outbreak of macrometastases as evidenced by BLI signal.

**Comment by idazucchi** [comment]
when reviewing please pay attention to the ontology terms and the inDrop library preparation (it would be good to review the entry in the cheat sheet)

**Comment by arschat** [comment]
Hello, Ida! Here are my comments.

## Secondary review
### Project 
- [ ] `Lung atlas` is now available in `hca_bionetwork.name` module in the latest update [here](https://schema.humancellatlas.org/module/project/1.0.1/hca_bionetwork).
- [ ] Emails can be added for the two corresponding authors.

### Dissociation protocol
- [ ] In the [best practice](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Metadata_spreadsheet/wrangling_best_practices.html#dissociation) document, it is mentioned: `No dissociation protocol for blood and other fluids`, since the cells are already separated. Here, since we don't have separate RBC suspension (would be considered an enrichment protocol), I would suggest to skip the `red_blood_cells_lysis` protocol. It is however, worth discussion whenever we have more time.

### Analysis file
- [ ] missed formula at tab Analysis file, cell H37

TO BE UPDATED soon with comments on lib_prep & files

**Comment by idazucchi** [comment]
thank you for reviewing!
from my prerspective the point of `red_blood_cells_lysis` as a dissociation protocol is to highlight that red blood cells have been excluded from the lung cell suspension. Since the methods say "_Red blood cells were lysed in red blood cell lysis solution (once or twice depending on red blood cell content)_" it felt like a meaningful thing to record

Library preparation --> I'm going to put 19 as cell barcode length for now, but I'm not sure what's the best way to represent split barcodes like this one. Is it more important to get the total barcode length or the nucleotide lenght in the read, also accounting for the gap?

Thanks for spotting the formula! I've checked the submission and it looks like the formula didn't make it to ingest, which is surprising 
If we get a weird validation issue it might be related this!

**Comment by idazucchi** [comment]
After discussing the dataset with the wrangler I've changed `red_blood_cells_lysis` into an enrichment protocol and updated the cell barcode length for inDrop to 41, to include the spacer length

**Comment by idazucchi** [comment]
additional cellxgene info in [this thread](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/IOUxacd3Ir8)
