### ISSUE TITLE
Transferring raw data from public archives to ingest-prod. for DCP2

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#112]
This is a ticket for the transfer of raw fastq data for 5 projects from public archives (GEO) to ingest prod. for DCP2.

These 5 projects are projects that I (Ami) have worked on. I  have uploaded the relevant metadata to ingest prod., and they are all valid. However, for full validation and preparation for their export to DCP2, the raw fastq files need to be transferred from public archives to ingest prod.

For each of these projects, I have created an s3 upload area and transferred the raw data from the public archives to these upload areas using this script: https://raw.githubusercontent.com/ebi-ait/hca-ebi-wrangler-central/esv-improve-insdc-script/src/move_data_from_insdc.py. The full data transfer was 100% complete.

I then used the hca-util sync command to transfer the data from the upload area to the relevant ingest prod. s3 bucket upload area. Accordinf to the terminal, the full data transfer was 100% complete. **However** the fastq files are not showing up as 'validating' or 'valid' in the ingest prod. UI.

Below I list the project short name and upload area ids. All final project metadata submissions were made on 4th August 2020, please use this latest version while there is a bug trying to delete previous submissions.

**Comment by ami-day** [comment]
DevelopingCardiacSystem

s3://org-hca-data-archive-upload-prod/0e05e76f-9385-428e-b8e2-0b8dc136c512/
72685c2d-11cb-4239-a365-f3c7b2772627

HealthyAndCirrhoticLiver

s3://org-hca-data-archive-upload-prod/0b69d960-d38d-4862-b2ed-1df47e27e0fb/
22eaa68c-673a-4d05-939e-4bfb104987cf

Lung_Fibroblasts 

s3://org-hca-data-archive-upload-prod/d8bcfa5a-d8a7-4dd0-8953-3c3bafdbf87e/
08558dcf-ea1b-484c-a725-50ada40b6d10

Pit2xDevelopingHeart

s3://org-hca-data-archive-upload-prod/c0a76ad2-ca77-47b7-86b6-4687bfa8f9e3/ 
ec41a47f-9c87-423d-895b-630643e05d9a

HumanAdultKidneyLiaoMo

s3://hca-util-upload-area/ b7c71215-4dda-43bd-a20e-aeae8918201c
hca-util select b7c71215-4dda-43bd-a20e-aeae8918201c

Note: transferred bam files
ftp://ftp.sra.ebi.ac.uk/vol1/run/SRR103/SRR10377488/possorted_genome_bam1.bam.1
ftp://ftp.sra.ebi.ac.uk/vol1/run/SRR103/SRR10377489/possorted_genome_bam2.bam.1
ftp://ftp.sra.ebi.ac.uk/vol1/run/SRR103/SRR10377490/possorted_genome_bam3.bam.1

**Comment by ami-day** [comment]
Update: I have downloaded the above listed bam files to EC2 and am currently converting them to fastq using the 10X bamtofastq tool. Please ignore the HumanAdultKidneyLiaoMo project for now, as I believe I will need to re-transfer the fastq files instead in a new upload area.

**Comment by ESapenaVentura** [comment]
I think this ticket can be closed now @ami-day ?
