### ISSUE TITLE
dataset problem - Revert ocularAnteriorSegmentAtlas from complete to valid

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/hca-ebi-wrangler-central#1124]
**Dataset/group this task is for:**

- project uuid - `16e99159-78bc-44aa-b479-55a5e903bf50`
- [link to browser HCA data portal](https://data.humancellatlas.org/explore/projects/16e99159-78bc-44aa-b479-55a5e903bf50)
- [link to ingest UI](https://contribute.data.humancellatlas.org/submissions/detail?uuid=1bd9055c-0eea-461a-8744-7c28ed826204&project=16e99159-78bc-44aa-b479-55a5e903bf50)

**Relevant People**
- Wrangler - Rachel, William, Jason

**Description of the problem with the dataset**

New files and metadata need to be added to this submission so the status needs to be reverted from complete.

**Comment by amnonkhen** [comment]
Submission state changed to Metadata Valid.
