### ISSUE TITLE
GSE132771 - CollagenProducingLungCell

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1125]
### Project short name:
CollagenProducingLungCell
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1DcBZ5qjiNgJ3T9SEoZnHnNPKgRd03JO9?usp=drive_link)

### Published study links

* Paper: [Collagen-producing lung cell atlas identifies multiple subsets with distinct localization and relevance to fibrosis](https://doi.org/10.1038/s41467-020-15647-5)

* Accessioned data: [GSE132771](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE132771) primary data

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=1c4cbdd4-33e3-4ded-ab43-5958de817123) 

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
**Data available**
there are two accession in the availability section:
1. GSE132771 - definitely primary data, wrangled
2. GSE147066 - subset of an existing dataset, cell type specific, not wrangled --> not sure if this is of interest for the bionetwork. I'm also reasonably sure they are aware/involved of the original dataset

**Comment by Wkt8** [comment]
Assigning self for secondary review.

**Comment by Wkt8** [comment]
Good job! Two things: 
Library_Preparation_Protocol - I would change 1x105 cells to 1 x 10^5 cells just for clarity. 

The cell count doesn't necessarily match up between the project and the sum of the analysis files but as we discussed I think that's okay. Great job!
