### ISSUE TITLE
revert from complete to exported: melanomaBrainMetastasisAtlas

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1129]
*Project Info*
uuid: `0efecd20-2b52-4e4f-96c5-9b4b94158713`
project short name: melanomaBrainMetastasisAtlas
primary wrangler: Rachel Schwartz

*background*
need to add several analysis files
* slack link: 
* email: 

Note:
assign to the current dev on operations.

**Comment by ofanobilbao** [comment]
https://github.com/rachadele The partial manifest was shared yesterday. Remember to tell the Import team if they have to hold off from importing this one just yet

@amnonkhen could you, please, revert the status to Exported?

**Comment by amnonkhen** [comment]
Seems ticket requests the wrong thing. Dataset should be moved to "Metadata Valid" status for the additional wrangling changes to take place.

**Comment by amnonkhen** [comment]
I changed the [submission status](https://contribute.data.humancellatlas.org/submissions/detail?uuid=54d36b50-fa76-4b99-8ece-59e1fb1c3cad&project=0efecd20-2b52-4e4f-96c5-9b4b94158713) to Metadata Valid.
