### ISSUE TITLE
Metadata schema for Study

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/hca-ebi-wrangler-central#1133]
- [x] discuss the required study fields
- [x] set up the schema
- [x] get approval/review from other DRACC members
- [ ] introduce the Dataset relevant fields as well under a study: DUO code and assay type
- [ ] get feedback/comments etc on the fields from DPC members

**Comment by gabsie** [comment]
- [ ] establish the MVP for dataset fields.
- [ ] Sketch out the form interface
- [ ] break down the technical tasks

**Comment by gabsie** [comment]
@gabsie has to finally review @ESapenaVentura doc on dataset and align with the discussion with Tony.

**Comment by gabsie** [comment]
Update the schema and docs with the new idea of the study as the plan with all characteristics we had before of a dataset, and then establish a dataset entity with:
UUID
assay type
DUO Code

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/16)
