### ISSUE TITLE
phs030434.v1.p1 - AllergicInflammatoryMemory

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1136]
### Project short name:
 AllergicInflammatoryMemory
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1IqULVVRFM8qRZKLW1Fu3PDQpJQ0w0c-i?usp=sharing)

### Published study links

* Paper:  [Allergic inflammatory memory in human respiratory epithelial progenitor cells](https://doi.org/10.1038/s41586-018-0449-8)

* Accessioned data: [phs030434.v1.p1](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs030434.v1.p1)

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=326b36bd-0975-475f-983b-56ddb8f73a4d)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
**Donor linking**
[Extended data figure 6](https://www.nature.com/articles/s41586-018-0449-8/figures/11) has a good breakdown of the specimens collected, which matches up with Supplementary table 9.
However some linking info is missing: for at least 3 donors 2 distinct samples were collected, but there is no way to tell which specimens have the same donor

This is blocked until I get further info ([email thread](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/LoQ7LG7Msxk) - we have a reply already but we are waiting on someone currently on paternity leave)

**Comment by idazucchi** [comment]
I got a very fast reply for the linking issue!

other things to note:  the dupilumab donor sampling timeline is recoded in [this figure](https://www.nature.com/articles/s41586-018-0449-8/figures/15)

**Comment by arschat** [comment]
Hello Ida, great job once again!

Only two minor comments, probably typos.
### Dissociation protocol
* Single character in dissociation protocol K6, for catalog number.
### Cell suspension
* Dissociation protocols for "scrape" suspensions (`Polyp17BEPI`, `Polyp19BEPI`, `Polyp21BEPI`) are `surgical_mechanical_dissociation||surgical_enzymatic_dissociation`, not align `collection_protocol` in `Specimen from organism` and with `SupTable_9`.

**Comment by idazucchi** [comment]
I've pinged the author again - I'll apply the corrections from the secondary review att the same time as the new information.

**Comment by idazucchi** [comment]
made required changes, exported and filled out import form

**Comment by w513142106** [comment]
Hello, I am a scholar from China, and I am doing related research in this field. Recently, I read this article and really wanted to see the raw data to inform our research. Excuse me, what should I do to download the data? I have requested access to data in Google Drive, but have not received a response yet. Is there any other method?

**Comment by idazucchi** [comment]
Verified in the browser
