### ISSUE TITLE
BALPreschoolCF

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1138]
### Project short name:
BALPreschoolCF
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1LmgAXA-xdakU3G51W39HQZ2V-dTGKBHK)

### Published study links

* Paper: [Single-cell atlas of bronchoalveolar lavage from preschool cystic fibrosis reveals new cell phenotypes](https://doi.org/10.1101/2022.06.17.496207)

* Accessioned data: [zenodo](https://zenodo.org/record/6651465) 

* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=1eba4d0b-2d15-4ba7-bb3c-d4654dd94519)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
the metadata for the donors is in the supplementary pdf --> copied [here](https://docs.google.com/spreadsheets/d/1w9NyiJdn68atv9Zq7uWUnqFStCqHQD6V/edit#gid=1552073802) in xlxs

the analysis files come from https://oshlacklab.com/paed-cf-cite-seq/

**Comment by Wkt8** [comment]
Hey! Looks good, well done! 

Project Tab
- The word 'abstract' in the project description could be removed 

Enrichment_Protocol
- A lot of the chemical things here are missed out (the sample being resuspended in media and chilled freezing solution, etc. how the cryopreserved BAL was thawed) 

Library_Preparation_Protocol
- Looks good! I wasn't sure where you found the information about the umi_barcode offset, etc. for the CITE-seq technique though. Should we addd it to the online excel sheet? (https://docs.google.com/spreadsheets/d/1H9i1BK-VOXtMgGVv8LJZZZ9rbTG4XCQTBRxErdqMvWk/edit#gid=0) 

Cell_Count of the Analysis_Files is really high considering the project cell count is 42,658

**Comment by idazucchi** [comment]
Applied corrections, exported and filled out the import form

**Comment by idazucchi** [comment]
Verified in Data Browser
