### ISSUE TITLE
Review of GSE129605 prior to export

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#114]
Following from this issue https://github.com/HumanCellAtlas/hca-data-wrangling/issues/444

I am reviewing the datasets prior to submission and consideration for DCP2.

## Review

**Project - Contributors**:

- Added Ami's institution, laboratory, corresponding contributor and project role fields.
- Added `no` to most contributors for corresponding contributor field and added one more `yes`. This info was extracted from the author's disclosure in the supplementary material for the paper.

**Donor organism**:

- Added "Purchased from Taconic" at the end of the description.
- Added "Medication" and "Treatment" fields to reflect the treatment the mice were given prior to extraction of the lungs.

**Collection protocol**:

- Changed the description to include the full procedure (indicated in the supplementary material)
- Changed the method to "Collecting specimen from organism postmortem"

**Specimen from organism**:

- Changed the id for all specimens from the accession number to the name indicated on the right. Also added a final "s" to indicate both lungs were extracted.
- Deleted BioSamples and INSDC sample accession. Looking at them it feels like they refer to the cell suspension, not the specimen.

**Dissociation protocol**:
- Completely changed the descriptio, deleted the copies and changed the ID to generic. It felt like one copy for each condition was created, but the dissociation protocol was the same no matter the experimental condition. The new description can be found under the subsection "single cell isolation" in the supplementary materials

**Enrichment protocol**:
- Added 2 enrichment protocols (And the tab itself). There was an enzymatic red blood cell removal (for which I couldn't find a good ontology term so for now I just left it as "enrichment protocol") and a dead cell removal protocol using MACS.

**Cell suspension**:
- Changed the IDs of all the suspensions, it's not wrong but I don't like to use accessions as IDs
- Added the INSDC sample accessions and re-matched the BioSamples accessions (They weren't matching the actual cell suspensions)
- Added the enrichment protocol linkings and the dissociation protocol id change.

**Library preparation protocol**:
- Changed the method to reflect the more accurate ontology (10x 3' v2 sequencing)
- Changed end bias from `3 prime end bias` to `3 prime tag`

**Sequence file**:
- Changed the `process.process_core.process_id` to match the library prep ID (Not necessary, just that I prefer them to match)

## Notes

The new spreadsheet is under the same folder, but with the "_ES_review" suffix in the name.

**Comment by ami-day** [comment]
This one has already been handed over to scea a while ago.
