### ISSUE TITLE
GSE196638 - LungStromaEmphysema

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1140]
### Project short name:
LungStromaEmphysema

### Primary Wrangler:
@arschat

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1zsd920t8fQ7s7Ipt53H3_y5B6O59nV0F?usp=drive_link)

### Published study links

* Paper: [Dysregulated lung stroma drives emphysema exacerbation by potentiating resident lymphocytes to suppress an epithelial stem cell reservoir](https://doi.org/10.1016/j.immuni.2023.01.032)

* Accessioned data: 
     - [GSE196638](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE196638)
     - [GSE206721](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE206721)
     - ~[GSE209734](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE209734)~ (bulk RNA-seq)
     - ~[GSE209735](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE209735)~ (bulk RNA-seq)
* [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=f7b46477-0f2a-4bff-a9b7-719e000499a3)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Number of mouse donors not mentioned in paper.
Mapping of human donors not verified (3 healthy + 3 diseased but not exact mapping between table and GEO)

**Comment by arschat** [comment]
Sent email requesting information about:
* mouse donors metadata
* clarification between inconsistencies among paper and GEO archive.
* verify the following human donor mapping

| TableS1 id  | Age | Sex | GEO description | FigureS1 b |
|-------------|-----|-----|-----------------|-----------|
| Control 1   | 63  | M   | NL_1            | Cont1     |
| Control 2   | 60  | M   | NL_2            | Cont2     |
| Control 3   | 61  | F   | NL_3            | Cont3     |
| Emphysema 1 | 65  | F   | TXP24           | Emp1      |
| Emphysema 2 | 73  | F   | TXP25           | Emp2      |
| Emphysema 3 | 63  | F   | TXP26           | Emp3      |

**Comment by arschat** [comment]
Authors replied with the following info:
* 3 mouse donors per group but not labeled individually and therefore we are unable to trace back from the files.
* 10x 3' version Human v2/ Mouse v3
* Sequencer NovaSeq 6000 
* Table mapping verified

**Comment by arschat** [comment]
Graph valid and ready for sec review.

### Notes

- `bamtofastq` provided 4 lanes for each bam file although GEO has 1 SRR accession for each sample. Paper mentions 1 lane too:
    > Briefly, live human lung cells or mouse ivCD45-negative immune cells were sorted and resuspended in 50 μl PBS with 0.04% BSA at 1,000 cells/μl and **loaded onto a single lane** into the Chromium Controller to produce gel bead-in emulsions (GEMs)

    Proceeding with 1 cell suspension for each specimen.
- Added `Gli1creERT2/+:Hhipflox/flox` as genotype, not sure which mouse strain is used.
- Collection from mouse, not described. Euthanasia mentioned but not specified furthermore.
- Enrichment protocols: RBC lysis for humans is mentioned only in the GEO
- Sequencing protocols: difference between 2 protocols is the version of cellranger used
- Analysis protocols: same with sequencing in description

**Comment by Wkt8** [comment]
Taking for secondary review

**Comment by Wkt8** [comment]
Hi Arsenios. Great job - the number of discrepancies between GEO and the paper are incredible. Well done on sorting them out! 

Project
- Add GSE206721 to the accessions 

Collection_Protocol
- the description for the 'mouse_postmortem' protocol could have some additional detail or be edited (e.g. Mouse were euthanised and then specimens were collected) 

Dissociation_Protocol
- For human_mechanical_dissociation - I would add 'A distal piece of 10cm^3 lung was further diced with razor blades...'

Enrichment_Protocol
- the FACS incubation for the human live lung cells isn't included - is there a reason to exclude it? 

Cell_suspension
- For mouse it seems like only the ivCD45-negative immune cells were sequenced. Can we add this to the cell suspension description or the cell-types column? 

Sequencing_Protocol
- 10x_v3_sequencing - change the name to also be v3!

**Comment by arschat** [comment]
On hold until ingest cluster is functional.
* Corrected spreadsheet uploaded in google drive folder ([here](https://docs.google.com/spreadsheets/d/1M6SoCXQHBBuir92BulsAEfB7f4JZrqp2/edit?usp=drive_link&ouid=101176945353039944995&rtpof=true&sd=true))
* Data in the `hca-util` upload area with uuid: `c1312765-bad1-402b-bc44-a0b3c7f55203`

**Comment by idazucchi** [comment]
First to export!

**Comment by arschat** [comment]
Metadata validating...

**Comment by arschat** [comment]
Verified in [Data Browser](https://data.humancellatlas.org/explore/projects/f7b46477-0f2a-4bff-a9b7-719e000499a3?catalog=dcp30).
Analysis portal url in supplementary link but other than that everything is good.
