### ISSUE TITLE
update published dataset - regnerGynecologicMalignancies

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1147]
**Dataset/group this task is for:**

regnerGynecologicMalignancies - A multi-omic single-cell landscape of human gynecologic malignancies
- project uuid - 9746f4e0-d3b2-4543-89b3-10288162851b
- [link to browseHCA data portal](https://data.humancellatlas.org/explore/projects/9746f4e0-d3b2-4543-89b3-10288162851b)
- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=9746f4e0-d3b2-4543-89b3-10288162851b)

**Relevant People**
- Wrangler: Rachel Schwartz
- Contributor: hfranco@med.unc.edu

**Description of the problem with the dataset**

Received feedback from contributor that some experimental metadata is incorrect and needs to be updated in the data portal. To do this, project must be reverted from complete -> submitted (or exported?)

 **screenshots/attachments**

![Screen Shot 2023-07-19 at 9 31 43 AM](https://github.com/ebi-ait/hca-ebi-wrangler-central/assets/51383714/404c606a-cd7d-4867-b007-522214949164)

**Comment by arschat** [comment]
@ESapenaVentura

**Comment by ESapenaVentura** [comment]
Reverted to valid
