### ISSUE TITLE
revert to exported - GrNewald-Human-10x3pv3

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1148]
**Dataset/group this task is for:**

GrNewald-Human-10x3pv3 - Single-cell sequencing of human midbrain reveals glial activation and a Parkinson-specific neuronal state.
- project uuid - 739ef78a-ba5d-4487-a013-9982db66d222
- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=739ef78a-ba5d-4487-a013-9982db66d222)

**Relevant People**
- Wrangler: Rachel
- Contributor: [anne.gruenewald@uni.lu](mailto:anne.gruenewald@uni.lu), [malte.spielmann@uksh.de](mailto:malte.spielmann@uksh.de)
- dev

**Description of the problem with the dataset**

need to add corresponding author details, please revert complete -> exported (or submitted? not sure the difference)

**Comment by ESapenaVentura** [comment]
Reverted to valid

**Comment by ESapenaVentura** [comment]
Reverted to valid
