### ISSUE TITLE
revert to exported - Tasic-Human-Smartseq

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1149]
**Dataset/group this task is for:**

Single-cell and single-nucleus RNA-seq uncovers shared and distinct axes of variation in dorsal LGN neurons in mice, non-human primates, and humans. - Tasic-Human-Smartseq

project uuid - bfaedc29-fe84-4e72-a461-75dc8aabbd1b
[link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=bfaedc29-fe84-4e72-a461-75dc8aabbd1b)

**Relevant People**

Wrangler: Rachel
Contributor: Bosiljka Tasic bosiljkat@alleninstitute.org

**Description of the problem with the dataset**

need to add corresponding author details, please revert complete -> exported (or submitted? not sure the difference)

**Comment by arschat** [comment]
@ESapenaVentura

**Comment by ESapenaVentura** [comment]
Reverted to valid

**Comment by rachadele** [comment]
Now stuck in graph validating; all I changed was adding a contributor email.
[](https://contribute.data.humancellatlas.org/projects/detail?uuid=bfaedc29-fe84-4e72-a461-75dc8aabbd1b&tab=upload)

**Comment by ESapenaVentura** [comment]
@rachadele apologies! I didn't see this ticket was not completed. I will update it and hit export
