### ISSUE TITLE
Review of GSE131181 prior to exporting

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#115]
Followed from https://github.com/HumanCellAtlas/hca-data-wrangling/issues/455

## Review:

**Donor organism**:
- Changed "Age" and "Age unit" to "Gestational Age" and "Gestational Age Unit"

## Notes:

Saved in the google drive folder with a stamp of the day.

**Comment by ESapenaVentura** [comment]
Reopening to track SCEA brokering

**Comment by mshadbolt** [comment]
This is already in SCEA so will move to finished https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-14/
