### ISSUE TITLE
revert to exported - Pfister-Human-10x3pv2

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1150]
Dataset/group this task is for:

Pfister-Human-10x3pv2 - Cellular development and evolution of the mammalian cerebellum

project uuid - 279f1766-3319-4e3c-9f99-6fb59ba9b3e5
[link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=279f1766-3319-4e3c-9f99-6fb59ba9b3e5)

Relevant People

Wrangler: Rachel
Contributor: Stefan,,Pfister  s.pfister@kitz-heidelberg.de

Description of the problem with the dataset

need to add corresponding author details, please revert complete -> exported (or submitted? not sure the difference)

**slack references**

**Comment by arschat** [comment]
@ESapenaVentura

**Comment by ESapenaVentura** [comment]
Reverted to valid
