### ISSUE TITLE
DCP published project missing fastq files

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1152]
**Context**
While cleaning up the hca-util areas a few projects had a different number of fastq files in the hca-util area from what is available in ingest. No explanation is given in the original ticket to indicate why the files are not included in the project.

**Task**
- [ ] add missing files to DCP
- [ ] ~~investigate other projects to ensure the correct number of files is available~~

**Involved datasets**
- [ReconstituitionHumanThymus](https://contribute.data.humancellatlas.org/projects/detail?uuid=3e92c74d-256c-40cd-9273-16f155da8342&tab=project)
   - [ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/834)
   - 3 files are missing for accession SRP287966 - run SRR12857069 is missing
   - spreadsheet generation fails due to sequence_file schema version error

```
{"log":"2023-08-03 10:56:23,020 - TerraSpreadsheetExporter - ERROR - submission_uuid:d1ce4d66-ad64-4a4d-9ac6-cd1eabc0aa20 - export_job_id:64cb879b1bfdb743144de671 - project_uuid:3e92c74d-256c-40cd-9273-16f155da8342 - The concrete entity schema version should be consistent across entities. Multiple versions of same concrete entity schema found: ['https://schema.humancellatlas.org/type/file/9.4.0/sequence_file', 'https://schema.humancellatlas.org/type/file/9.5.0/sequence_file']\n","stream":"stderr","time":"2023-08-03T10:56:23.02120782Z"}
```
   - Amnon to change status so Ida can edit the metadata and update schema to 9.5.0
   
- [HighlyParallelExpressionProfiling](https://contribute.data.humancellatlas.org/projects/detail?uuid=3c9d586e-bd26-4b46-8690-3faaa18ccf38&tab=project)
   - [ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/835)
   - 2 fastq files in the hca-util area missing from ingest (PRJNA267857)
SRR1853183_1.fastq.gz
SRR1853184_1.fastq.gz
- [LongitudinalMultiomicsCovid19](https://contribute.data.humancellatlas.org/projects/detail?uuid=ec6476ee-2949-41f3-947b-8eef41d6d3ac)
   - [ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/715)
   - missing 4 fastqs SRR13082809 SRR13082810

**Comment by idazucchi** [comment]
1. correct the existing issues
2. how do we avoid the problem in the future? secondary review from ingest spreadsheet + comparing hca-util/ingest
3. no investigation at this point

**Comment by idazucchi** [comment]
I need help with 2 submissions: they are in Complete status and need to be put back to metadata valid to be editable

1. [HighlyParallelExpressionProfiling](https://contribute.data.humancellatlas.org/projects/detail?uuid=3c9d586e-bd26-4b46-8690-3faaa18ccf38&tab=project) 
2. [LongitudinalMultiomicsCovid19](https://contribute.data.humancellatlas.org/projects/detail?uuid=ec6476ee-2949-41f3-947b-8eef41d6d3ac)

**Comment by idazucchi** [comment]
export failed for ReconstituitionHumanThymus

**Comment by idazucchi** [comment]
I'm unable to finsh work on projects 2 & 3. They've been put back to metadata valid but the files sync has an error.
All files transfer but give this message:
```
 Transferred. Notify failed.
``` 
Although the new files are in the ingest s3 bucket they don't show up in the submission ui or the api, [ex](https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/62d05ee0d05a6c41edc23374/files?page=0&size=25)

**Comment by idazucchi** [comment]
**ReconstituitionHumanThymus**
I patched the schema version to 9.5.0 for all sequence files and I'm exporting again

**Comment by idazucchi** [comment]
none of these datasets are part of a network list

**Comment by arschat** [comment]
@arschat to check if this is viable & if not close ticket

**Comment by idazucchi** [comment]
the only known workable workaround for this issue would be recreating the submissions, given that these projects are not part of a bionetwork it's not worth spending this much effort on this
