### ISSUE TITLE
Updating datasets with non-organically described analysis files 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1153]
### Context
Prior to the current method of recording analysis files in the metadata schema, we had a method of adding analysis files to datasets that described just enough metadata to be indexed by Azul and exposed in the Data Browser (Details in the DCP/2 spec here https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.aohbnknu370j) 

In this ‘non-organic’ method of describing analysis_files and attaching them to datasets, we described them by adding them to this spreadsheet (https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY/edit#gid=0) 

We have 101 datasets with 324 analysis files that were described in this way. 

### Issue
We have analysis files that are 
- not described in the metadata
- Will not be in generated spreadsheets
- Will not be in Ingest (as data files) 

### Potential Solutions: 
Fortunately, described in the spreadsheets are the following columns: 
date_added, project_uuid, project_shortname, get matrix, cell type, other, file_name, file_source, genusSpecies, development stage, organ, libraryconstructionapproach, date_imported, and Notes.  

1. Pure Brute Force and Labour 
- Wranglers manually add analysis files to the subgraph of each experiment, adding additional metadata
- This takes a lot of effort. 

2. Programatically add links 
- There should be enough information to programatically add the analysis files to some extent
- Issues will arise with deciding which cell suspensions to link to the analysis file, and creating the analysis_protocols from scratch (as they were not written out in the non-organic method and have no metadata stored on them)

**Comment by idazucchi** [comment]
the time and effort required is not justified at the moment

each project needs to be reviewed individually to remove the existing links and matrices from the terra record (see #1226)
