### ISSUE TITLE
Myocyte-Specific Upregulation of ACE2 in Cardiovascular Disease

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1154]
### Associated files

* Google Drive:

### Published study links 

* [Paper](https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.120.047911)

* Accessioned data:[ Single cell broad institute portal](https://singlecell.broadinstitute.org/single_cell/study/SCP846/myocyte-specific-upregulation-of-ace2-expression-in-cardiovascular-disease-implications-for-sars-cov-2-mediated-myocarditis)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=d84fd289-1b4b-43f0-aa84-9f0928937106)
### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
@idazucchi check if there's enough metadata to wrangle

**Comment by idazucchi** [comment]
there have been 2 previous attempts to get more data/metadata ([one](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/QRdYIzXopYA/m/07kHKXDrAgAJ), [two](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/4KLusfUpzq8/m/gVkbiSBqBAAJ)) but no no reply came through 

there is minimal donor metadata (id + disease) but the gene expression is only available for 3 genes 

is it worth wrangling this?
