### ISSUE TITLE
Decision on JSON schema delivery

### ISSUE THREAD

**Issue by dipayan1985** [ebi-ait/hca-ebi-wrangler-central#1158]

**Comment by dipayan1985** [comment]
**Standard requirements:**

1. List schemas / query for particular schema version by type
2. Resolve the schema URI to the schema document itself
3. Provide persistent storage for all versions of all schemas

**Proposed solution:**

1. Store MorPhic JSON schemas in AWS (same as HCA)
2. Have a separate MorPhic context in the HCA JSON schema retrieval API so that the same API can be used to retrieve MorPhic schemas, Marcin's UI uses the API to get the schemas

**Reason for the proposal:** 
Not diverging from how things are done in ingest with the view that ingest can be used as a platform service for multiple projects (HCA, MorPhic) and not building project specific solutions

**Notes:**
What we also know that the requirement 1 is not well implemented anywhere so we can try to improve this either in ingest or in JSON schema store by adding more data sources to it.

/cc @KociOrges, @gabsie

**Comment by gabsie** [comment]
Hey @KociOrges I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/morphic-639854c8f6eea5001f67ae06/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by gabsie** [comment]
[Document](https://docs.google.com/document/d/1CiAk8dsq8npIPbmbZfSAh1FI45F793uI/edit) after the cross-workstream meeting yesterday, with some actions for the Fairification stream, as well as timelines.

**Comment by amnonkhen** [comment]
tickets created. MVP is under release Morphic Schema 1.0

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/11)
