### ISSUE TITLE
Review of GSE136103 prior to exporting

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#116]
I couldn't find the previous ticket for this dataset

## Review

**Project - Contributors**:
- Added the missing "corresponding contributor" as no

**Donor organism**:
- Changed developmental term "Adult" to "Human adult stage" for human donors
- Added details for medication/treatment for mice

**Collection protocol**:
- Deleted extra collection protocol for mouse liver (The protocol itself is the same, just changing the conditions of the mice) and modified description of the protocol to not include the previous treatment of the mice.

**Specimen from organism**:
- Linked the specimens that came from mice to the "general" collection protocol

**DIssociation protocol**:
- I would like to discuss this one. Looking at the paper it may seem that they used 2 methods for dissociation, but in GEO metadata they state the same dissociation protocol for everything. Based on that, I have removed the other 3 extra protocols as I feel they are the same protocol, just applied to different specimens.

**Enrichment protocol**:
- Corrected marker separation to be with spaces instead of `;`

**Cell suspension**:
- Corrected linkings to dissociation/enrichment based on what's indicated above.

**Sequence file**:
- Changed '...content.ontology_label` values to `DNA sequence` from `DNA sequence (raw)`

## Notes

- As indicated in the dissociation protocol section, I'd really like Ami's insight into this, because I am pretty unsure about it.

- The updated spreadsheet has been saved with the suffix "_ES_20200813"

**Comment by ami-day** [comment]
preparing for SCEA: E-HCAD-19 & E-HCAD-20 (split by organism)
