### ISSUE TITLE
GSE205013 - human pancreatic adenocarcinoma and its tumor microenvironment

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1161]
### Project short name: 
Tsirigos_10x_pdac

### Primary Wrangler: 
@anu-shiva 

### Secondary Wrangler:
Ida

### Associated files

* [Google Drive](https://drive.google.com/drive/folders/16I2zAWZKpBVTyRMcjJ-iUA9-BDBe588c)

### Published study links

* Paper: [Single-cell RNA sequencing reveals the effects of chemotherapy on human pancreatic adenocarcinoma and its tumor microenvironment](https://www.nature.com/articles/s41467-023-36296-4)

* Accessioned data:[GSE205013](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE205013)

[**Ingest**](https://contribute.data.humancellatlas.org/projects/detail?uuid=7f9766ff-bb12-4279-b340-78d140bdd7ba)
### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
bam files converted to fastq!

**Comment by anu-shiva** [comment]
Ready for secondary review!

**Comment by anu-shiva** [comment]
Thanks, resolved the comments and exporting it now

**Comment by anu-shiva** [comment]
Submitted. import form filled

**Comment by idazucchi** [comment]
updated institution names, export is stuck

**Comment by idazucchi** [comment]
the second submission can be deleted, the updated info is in the project and can be exported with the first submission

**Comment by ESapenaVentura** [comment]
I have deleted the submission AND the staging area - Some things were duplicated

Please re-export the first submission completely, data files included :)

**Comment by idazucchi** [comment]
the project was exported again in full but it looks like the second submission was exported rather than the first one
see the stagin area for donors for example
```
```
 will this be an issue for the import team? 
- [ ] Are these biomaterials considered new entities? - remove from manifest, delete staging area, delete second submission and re-export the first submission
- [ ] not an issue - no action (?)

**Comment by anu-shiva** [comment]
Exported again (the first orginal submission) successfully
