### ISSUE TITLE
GSE178454 - PituitariesStemCellRegulation

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1162]
### Project short name: 
PituitariesStemCellRegulation
### Primary Wrangler: 
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1uA6vFsH54rFIeE6clcpI78pw-se5pIex?usp=drive_link)

### Published study links

* Paper: [Single nucleus transcriptome and chromatin accessibility of postmortem human pituitaries reveal diverse stem cell regulatory mechanisms](https://doi.org/10.1016/j.celrep.2022.110467)

* Accessioned data:  Superseries [GSE178454](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE178454) :
    * [GSE178451](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE178451) snATAC-seq
    * [GSE178452](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE178452) snRNA-seq
    * [GSE178453](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE178453) snMultiome

**[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=48f60534-ba4e-45bc-aa5b-6d3a6c45962e)**

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Ready for secondary review :)

**Comment by arschat** [comment]
Excellent work, Ida! Everything is well wrangled.

**Comment by idazucchi** [comment]
reviewed in the browser
