### ISSUE TITLE
create a bucket for schema files

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1164]

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/10)

**Comment by amnonkhen** [comment]
-[x] create bucket
-[ ] configure policy, CORS
-[x] copy files
-[x] create cloudfront distribution
-[ ] verify access through aws url
-[ ] connect to morphic.bio domain and verify access
