### ISSUE TITLE
add Isuru and Amnon to morphic's github

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1166]
add Isuru and Amnon as members to https://github.com/morphic-bio/metadata-schema	1.0

**Comment by ESapenaVentura** [comment]
Done for metadata-schema!

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/9)
