### ISSUE TITLE
add Amnon & Enrique to Morphic AWS

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1167]
Amnon & Enrique need SSO access to the morphic dev and prod AWS accounts

**Comment by dipayan1985** [comment]
Requested cloud consultants for the same.

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/8)
