### ISSUE TITLE
populate s3 bucket with schema files

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1168]
- [ ] manually copy schema files to s3 bucket according to structure of HCA bucket
- [ ] copy index.html that exposes bucket contents

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/7)
