### ISSUE TITLE
expose schema bucket as HTTP server

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1169]
- [ ] decide on a domain name - can it be: `schema.morphic.bio`
- [ ] expose s3 bucket using the domain name

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/6)
