### ISSUE TITLE
GSE125188 - LiverHeterogenicityZhaoJ

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#117]
**Primary Wrangler:**
Enrique
**Secondary Wrangler:**

**Associated files:**

Google Drive: https://drive.google.com/drive/folders/1ndQ9TluwHot1CwUlZM_47QCWz5h55phl

**Published study links**

Paper: https://www.nature.com/articles/s41421-020-0157-z

Accessioned data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE125188

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [ ] manually curate dataset to meet HCA metadata standard
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production

**Comment by ami-day** [comment]
Closing this ticket as a new ticket for this dataset has been created (didn't see this ticket, it wasn't in the tracker).
