### ISSUE TITLE
automated updates of schema changes

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1171]
In HCA schema changes are propagated to AWS using a webhook and a lambda function.
Similar approach can be used here.
See [discussion document](https://docs.google.com/document/d/1CiAk8dsq8npIPbmbZfSAh1FI45F793uI/edit)

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/4)
