### ISSUE TITLE
move morphic tickets to morphic github org

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1172]
- [ ] decide on repo for issues
- [ ] copy issues
- [ ] notify team
- [ ] include issues in HCA team boards.

**Comment by ESapenaVentura** [comment]
Kamino closed and cloned this issue to [morphic-bio/data-ingestion-development](https://github.com/morphic-bio/data-ingestion-development/issues/3)
