### ISSUE TITLE
Investigate status of metadata-only submissions

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1177]
- [x] Create a submission
- [x] Validate metadata
- [x] Validate graph
- [ ] Export

**Comment by idazucchi** [comment]
@gabsie should we prioritise investigation for export of metadata-only submissions?
this is probably going to be a problem downstream 
discuss again the aim of this export with Will?

**Comment by idazucchi** [comment]
at the moment metadata only submissions are non exportable
discuss priority of making metadatata only submission exportable
@idazucchi add to wrangler agenda
