### ISSUE TITLE
HCA Tier 1 metadata mapping to DCP metadata fields

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1178]
**Description of the task:**

We are given a list of the Tier 1 metadata that are gonna be used in the integration. We are asked to map those metadata to fields in our metadata schema, and provide example values of each field.

Here is the drive folder with the spreadsheet https://drive.google.com/drive/folders/1fobiz332ylmPc738dSoLSQEM7TxjYJBF?usp=sharing

**Acceptance criteria for the task:**

Wranglers have given their feedback and @arschat has summarised all feedback and reply to HCA Bionetworks committee, with a suggested mapping and some comments and questions.

**Comment by arschat** [comment]
## Notes on differences in fields:
- **intistute**: the most proper field would be `process.process_core.location` for the specific process that we would (collection/ dissociation/ library preparation/ sequencing etc.) but it is not usually collected. `project.contributors.institute` would be and array with all the institutes of the authors of the publication
- **ethnicity_2**: `donor_organism.human_specific.ethnicity.ontology_label` can include more than 1 entries (type: array)
- **sampled_site_condition**: combination of `specimen_from_organism.diseases.ontology_label` and `specimen_from_organism.adjacent_diseases.ontology_label` could be used
- **reference_genome_ensembl_release**: conversion of `analysis_file.genome_patch_version` to Ensembl release version with http://www.ensembl.org/info/website/archives/assembly.html

## Conditional fields
- **study_PI**: if `project.contributors.project_role.ontology_label` == "Principal Investigator" then `project.contributors.name`
- **sample_collection_relative_timepoint**: if multiple `specimen_from_organism.biomaterial_core.biomaterial_id` have the same `donor_organism.biomaterial_core.biomaterial_id` then `specimen_from_organism.collection_time`  
- **age_years**: in the `donor_organism.organism_age` if a `-` the age is a range
				if `donor_organism.organism_age_unit.ontology_label` is not "year" we could devide with corresponding value to convert to decimal year
- **age_gestational**: in the `donor_organism.gestational_age` if a `-` the age is a range
				if `donor_organism.gestational_age_unit.ontology_label` is not "year" we could devide with corresponding value to convert to decimal year
- **age_range**: if `-` in `donor_organism.organism_age` fill here instead
- **sample_cultured**: if `cell_line.biomaterial_core.biomaterial_id` exists

## Questions about fields:

**Comment by arschat** [comment]
suggestions have been sent, waiting for any feedback or questions.

**Comment by arschat** [comment]
Got a reply

> There are now 11 gaps I still need to fill, and I wanted to ask whether you would be able to work with me to fill these gaps - while I'm enthusiastically learning about metadata I don't have the depth of expertise required to define ontology terms. I'd also be keen to discuss some of your comments.

**Comment by arschat** [comment]
After discussion with Tony, I will create a report to describe current situation between CellxGene, DCP, Integration teams, mapping of those terms, and propose some options.

**Comment by arschat** [comment]
Ellen Todres verified that in **sample_source**, _organ donor_ refers to allograft/ xenograft, and _surgical donor_ to other types of collection. Therefore condition described above is valid.
> if PR.FIELD == allograft then "organ donor"
else if donor_organism.is_living == no then "postmortem donor"
else "surgical donor"

**Comment by arschat** [comment]
Malte replied 
>  I don't think that "organ_donor" covers any organs that were at some point transplanted into another host and then removed for sampling. It was my understanding that these tissue samples are from individuals who donate their organs to science and maybe their organs were previously considered not fit for transplantation (this is what I meant with rejected). I'm checking this with some bionetwork coordinators now to check that my understanding is correct though. Maybe Chloe could weigh in here too.
> 
> Surgical donor would then be where the individual is still alive and part of their tissue is taken out. Overall I don't think xenograft/allografts play a role in this metadata field at all. But again, I'm not an expert in tissue sampling.
> 
> As for the reason for tissue transplant rejection, I don' think we would be able to get that information. It may also be restricted access/protected.

**Comment by arschat** [comment]
Current snapshot of Tier 1 mapping:
- `alignment_software` pr has been made HumanCellAtlas/metadata-schema#1534
- `sample_source` discussions about definitions and differentiations of 3 options stalled
- `library_ID` internal (EBI/UCSC) discussions on how to model this information

**Comment by arschat** [comment]
Update on `library_ID` after EBI internal discussion today.
We have the following options:
1. library as a new biomaterial entity:
    * create a new entity, that has the following fields:
        1. library.biomaterial_core
        2. library.preparation_batch
        3. library.sequencing_batch
        4. cell_suspension.biomaterial_core.biomaterial_id
2. cell_suspension as library:
    * instead of creating a new library biomaterial entity, we will use the cell_suspension entity to describe libraries
    * we will need two new fields in cell_suspension, to describe the `library_preparation_batch` & `library_sequencing_batch`
3. batch module in analysis_file
    * create a **batch** module in analysis_file that contains `library_ID`, `sequence_batch`, `cell_suspension_ID`, `analysis_file_ID`
    * module will be in a separate tab (the way *projects.publication* does) but will also include an `analysis_file_ID` to connect back to specific analysis_file

Option 1 will result in multiple redesigns of ingest, import and data browser, and will need a lot of time to design and apply those changes. It was voted down by both UCSC and EBI wranglers.

Between option 2 and 3 we (EBI wranglers) decided to proceed with the option 2 since it will need less changes in the schema, and ingesting of the data, and will be more intuitive for the wrangler to fill compared with option 3.

**Comment by arschat** [comment]
## Alignment software PR
After Hannes' comments, `alignment_software` & `alignment_software_version` was moved to analysis_protocol & converted to optional (alignment_software in dependentRequired for alignment_software_version)

**Comment by arschat** [comment]
### Gene Annotation 
FIeld **gene_annotation_version**
* Description: Ensembl or NCBI/RefSeq release version number
* Examples: v110; GCF_000001405.40

**Comment by idazucchi** [comment]
Pending discussion on the library id and sample source - schedule discussion with Tony @arschat

**Comment by arschat** [comment]
Current options for library_ID:
- **Cell_suspension** as a library_ID:
    - This would not be accurate since cell_suspension is **not** identical to the library. However, since Tier 1 have 3 biomaterials (`donor`, `sample`, `library`) it would be similar to our (`donor_organism`, `specimen_from_organism`, `cell_suspension`) 3 level biomaterials of a simple experimental design. For most experiments we've describe however, one cell_suspension provides one library.
    - we could store the batch and run information in the sequence_file, in the fields we already have for this.
- Library field in the **sequence_file** tab:
    - we could create a new field in the sequence tab, where we could record the `library_ID`s associated for each. However, this way, we would not be able to associate analysis_files with the library_IDs, if the libraries from 1 cell_suspension are pooled.
    <img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWQvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a96bbc77c02e74521217e8d1072768024ea42d6/image.png" alt="image.png" />
- Library as a new **biomaterial**:
   - This would be the most accurate, however, it would take much more time to implement
   - The simple experimental design would be described by 4 biomaterials in contrast to the 3 biomaterials described in Tier 1, and this might confuse bionetwork contributors that are filling the spreadsheet.

**Comment by arschat** [comment]
About `organ_donor` in `sample_source` we got the following clarification from Lucia & Malte.
>  If I recall correctly, this is relevant as post-mortem tissue that is no longer properly perfused shows a distinct transcriptomic effect (you never get tissue immediately after death, usually 2-3 hours is minimum). Organ donor samples are from individuals that are e.g., brain dead but where the organ is still kept alive so that no cellular degeneration is evident due to lack of perfusion. This looks more like living tissue than post-mortem. On the other hand, surgical tissue is from an individual who is still very much alive and may have e.g., eaten and metabolized food recently.
>
> I'm not sure I would say "organ donor from a living subject", as organs will only be removed if the donor is declared brain-dead... which I'm not sure counts as living. Any bionetwork coordinator for bionetwork that collected tissue blocks of some sort will know this better than me though.

There are two options.
- `donor_type` enum field
    - organ_donor: biomaterial was intended for organ transplantation
    - surgical_donor: biomaterial was collected during a surgical, medical or non-invasive procedure (for example biopsy, blood draw, bronchoalveolar lavage, nasal brush, scraping etc').
- `organ_donor` boolean field
    - Whether biomaterial was intended for organ transplantation.

**Comment by arschat** [comment]
Last update on mapping [here](https://docs.google.com/spreadsheets/d/12LzqHj78CLpalRiaPIoCJcAKM1mCmzpu/edit?usp=drive_link)
Template with tier 1 at row 4 [here](https://docs.google.com/spreadsheets/d/1SiMOxFR64MJp7xgE8LFD9WEF_bvPDJ96/edit?usp=drive_link&ouid=101176945353039944995&rtpof=true&sd=true)

**Comment by arschat** [comment]
Conversion from anndata tier 1 object, to DCP spreadsheet with a jupyter notebook and a interchangeable mapping dictionary [here](https://drive.google.com/drive/folders/1TvYUeFjHty6AsXvelCQarMS8pduebtwx?usp=drive_link).

**Comment by arschat** [comment]
`transplant_organ` PR merged!
Will now work on intron_inclusion PR.

**Comment by idazucchi** [comment]
`intron_inclusion` PR merged!

**Comment by arschat** [comment]
`library_sequence_run`:
This could be either the ID of the sequence RUN or the sequence BATCH. Asked for clarification and got the following replies:
> my assumption is that we're interested in the batch (as there shouldn't be any differences between runs if they're all being processed at the same time. However, I'm absolutely not an expert so need to check with someone and get back to you

> Confirming that library_sequencing_run is a custom field. Also, Library_sequencing_run is the higher order term. Whereas, library_preparation_batch i think is the lower order term as it's referring to libraries sequenced on the same plate/chip

**Comment by arschat** [comment]
`sequence_run_batch` which is equivalent to `library_sequence_run` is now merged in [prod](https://schema.humancellatlas.org/type/file/9.6.0/sequence_file). `sample_collection_site` can be recorded in the `process.process_core.location`.

Mapping of Tier 1 has been completed, referenced [here](https://docs.google.com/spreadsheets/d/12LzqHj78CLpalRiaPIoCJcAKM1mCmzpu/edit?gid=505822894#gid=505822894).

Tier 1 fields that are not mapped:
> batch_condition, default_embedding, comments, author_batch_notes, tissue_type, is_primary_data, author_cell_type, cell_type_ontology_term_id

All mapping here.

| Tier 1 | HCA metadata schema |
| ------ | ------------------- |
| title | project.project_core.project_title |
| study_pi | project.contributors.name |
| batch_condition | NA |
| default_embedding | NA |
| comments | NA |
| sample_id | specimen_from_organism.biomaterial_core.biomaterial_id |
| donor_id | donor_organism.biomaterial_core.biomaterial_id |
| protocol_url | library_preparation_protocol.protocol_core.protocols_io_doi |
| institute | project.contributors.institute |
| sample_collection_site | process.process_core.location |
| sample_collection_relative_time_point | specimen_from_organism.biomaterial_core.timecourse.value |
| library_id | cell_suspension.biomaterial_core.biomaterial_id |
| library_id_repository | cell_suspension.biomaterial_core.biomaterial_name |
| author_batch_notes | NA |
| organism_ontology_term_id | donor_organism.biomaterial_core.ncbi_taxon_id |
| manner_of_death | donor_organism.death.hardy_scale |
| sample_source | donor_organism.is_living & specimen_from_organism.transplant_organ |
| sex_ontology_term_id | donor_organism.sex |
| sample_collection_method | collection_protocol.method.text |
| tissue_type | NA |
| sampled_site_condition | donor_organism.diseases.text & specimen_from_organism.diseases.text |
| tissue_ontology_term_id | specimen_from_organism.organ.ontology |
| tissue_free_text | specimen_from_organism.organ.text |
| sample_preservation_method | specimen_from_organism.preservation_storage.storage_method |
| suspension_type | library_preparation_protocol.nucleic_acid_source |
| cell_enrichment | enrichment_protocol.markers |
| cell_viability_percentage | cell_suspension.cell_morphology.percent_cell_viability |
| cell_number_loaded | cell_suspension.estimated_cell_count |
| sample_collection_year | specimen_from_organism.collection_time |
| assay_ontology_term_id | library_preparation_protocol.library_construction_method.ontology |
| library_preparation_batch | sequence_file.library_prep_id |
| library_sequencing_run | sequence_run_batch |
| sequenced_fragment | library_preparation_protocol.end_bias |
| sequencing_platform | sequencing_protocol.instrument_manufacturer_model.text |
| is_primary_data | NA |
| reference_genome | analysis_file.genome_assembly_version |
| gene_annotation_version | analysis_protocol.gene_annotation_version |
| alignment_software | analysis_protocol.alignment_software_version |
| intron_inclusion | analysis_protocol.intron_inclusion |
| author_cell_type | NA |
| cell_type_ontology_term_id | NA |
| disease_ontology_term_id | donor_organism.diseases.ontology |
| self_reported_ethnicity_ontology_term_id | donor_organism.human_specific.ethnicity.ontology |
| development_stage_ontology_term_id | donor_organism.development_stage.ontology

This ticket can now close.

**Comment by arschat** [comment]
All mapping here.

| Tier 1 | HCA metadata schema |
| ------ | ------------------- |
| title | project.project_core.project_title |
| study_pi | project.contributors.name |
| batch_condition | NA |
| default_embedding | NA |
| comments | NA |
| sample_id | specimen_from_organism.biomaterial_core.biomaterial_id |
| donor_id | donor_organism.biomaterial_core.biomaterial_id |
| protocol_url | library_preparation_protocol.protocol_core.protocols_io_doi |
| institute | cell_suspension.processing_institute | 
| sample_collection_site | specimen_from_organism.collection_institute.name |
| sample_collection_relative_time_point | specimen_from_organism.biomaterial_core.timecourse.value |
| library_id | cell_suspension.biomaterial_core.biomaterial_id |
| library_id_repository | cell_suspension.biomaterial_core.biomaterial_name |
| author_batch_notes | NA |
| organism_ontology_term_id | donor_organism.biomaterial_core.ncbi_taxon_id |
| manner_of_death | donor_organism.death.hardy_scale |
| sample_source | donor_organism.is_living & specimen_from_organism.transplant_organ |
| sex_ontology_term_id | donor_organism.sex |
| sample_collection_method | collection_protocol.method.text |
| tissue_type | NA |
| sampled_site_condition | donor_organism.diseases.text & specimen_from_organism.diseases.text |
| tissue_ontology_term_id | specimen_from_organism.organ.ontology |
| tissue_free_text | specimen_from_organism.organ_part.text |
| sample_preservation_method | specimen_from_organism.preservation_storage.storage_method |
| suspension_type | library_preparation_protocol.nucleic_acid_source |
| cell_enrichment | enrichment_protocol.markers |
| cell_viability_percentage | cell_suspension.cell_morphology.percent_cell_viability |
| cell_number_loaded | cell_suspension.estimated_cell_count |
| sample_collection_year | specimen_from_organism.collection_time |
| assay_ontology_term_id | library_preparation_protocol.library_construction_method.ontology |
| library_preparation_batch | sequence_file.library_prep_id |
| library_sequencing_run | sequence_run_batch |
| sequenced_fragment | library_preparation_protocol.end_bias |
| sequencing_platform | sequencing_protocol.instrument_manufacturer_model.ontology |
| is_primary_data | NA |
| reference_genome | analysis_file.genome_assembly_version |
| gene_annotation_version | analysis_protocol.gene_annotation_version |
| alignment_software | analysis_protocol.alignment_software & analysis_protocol.alignment_software_version |
| intron_inclusion | analysis_protocol.intron_inclusion |
| author_cell_type | NA |
| cell_type_ontology_term_id | NA |
| disease_ontology_term_id | donor_organism.diseases.ontology |
| self_reported_ethnicity_ontology_term_id | donor_organism.human_specific.ethnicity.ontology |
| development_stage_ontology_term_id | donor_organism.development_stage.ontology |

This ticket can now close.
