### ISSUE TITLE
revert from complete to exported: entorhinalCortexAlzheimers

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1180]
*Project Info*
uuid: dcc28fb3-7bab-48ce-bc4b-684c00e133ce
project short name: entorhinalCortexAlzheimers
primary wrangler: Rachel Schwartz

*background*

Need to revert from complete to exported so that donor genus species can be updated [(https://github.com/DataBiosphere/azul/issues/5530)](url)

Note:
assign to the current dev on operations.
@ESapenaVentura

**Comment by ESapenaVentura** [comment]
Reverted - Ready for metadata update :)

**Comment by rachadele** [comment]
submitted!
