### ISSUE TITLE
contributor account for: Sven Wischnewski

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1182]
Please create an account a contributor.

*Contributor details:*
* name: Wischnewski, Sven
* email: _contributor email address_
S.Wischnewski@stud.uni-heidelberg.de
Request Details:
* Requested by: Rachel Schwartz raschwar@ucsc.edu
* request email details:

>  "Hi Rachel,
> 
> see attached the abstract and title of the paper. If you need more information, please let me know.
> Would it be possible, to upload the data there, but make it accessible to the public only after publishing? And would it be possible to provide us a non-public link for the data, which we could then share with the reviewers?
> 
> 
> Best,
> Sven
> "

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Introduction/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by rachadele** [comment]
@ESapenaVentura

**Comment by ESapenaVentura** [comment]
The user has been created but I don't have the permission to add them to the hca-contributor group

Once @amnonkhen adds it I will send you the credentials @rachadele!

**Comment by rachadele** [comment]
👌🏻

**Comment by ESapenaVentura** [comment]
Credentials have been sent and @rachadele confirmed everything was alright :)
