### ISSUE TITLE
stuck in export - no such table: responses

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1185]
### Error
More than one project are effected by this error
`no such table: responses`
It doesn't seem to be very consistent, we tried reproducing it in staging (see [here](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=8699d2ef-908e-4cdd-8305-16ceab5b76a6&tab=project)) and it exported with no issues

#### More urgent project - ~~for R32 if possible~~
*Project Info*
uuid: `645b20c9-5ed0-4500-86b5-7aef770d010a`
project short name: [cerebralCortexOrganoids22q11DS](https://contribute.data.humancellatlas.org/projects/detail?uuid=645b20c9-5ed0-4500-86b5-7aef770d010a)
[grafana](https://monitoring.ingest.archive.data.humancellatlas.org/d/yK-iu984z/export-single-submission?orgId=1&from=now-7d&to=now&var-submission_uuid=8585aff3-6cd3-4664-b814-3bf4b3cd6930)
primary wrangler: Rachel

*background*
* slack link: [R32 discussion](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1695673989294569) if we can export this today (28/9/23) it will be included in R32
* email: raschwar@ucsc.edu

#### Not urgent
*Project Info*
uuid: `5bd01deb-01ee-4611-8efd-cf0ec5f56ac4`
project short name: [ChronicInflammatorySkinClassification](https://contribute.data.humancellatlas.org/projects/detail?uuid=5bd01deb-01ee-4611-8efd-cf0ec5f56ac4)
[grafana](https://monitoring.ingest.archive.data.humancellatlas.org/d/yK-iu984z/export-single-submission?orgId=1&from=now-7d&to=now&var-submission_uuid=03ef202e-bde7-4307-afd3-c3b755743272)
primary wrangler: ida

*background*
* [ticket](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/1183): this got stuck once already with the same error, Enrique pushed it back to graph valid. I exported it again but it got stuck again with the same error, although this time it did manage to export files and some metadata
* email: idazucchi@ebi.ac.uk

**Comment by ESapenaVentura** [comment]
First submission has been moved to Graph valid - Hitting export right now

**Comment by ESapenaVentura** [comment]
First submission has been moved to Graph valid - Hitting export right now

**Comment by arschat** [comment]
Same error in another project:

Project Info
uuid: `aecfd908-674c-4d4e-b36e-0c1ceab02245`
project short name: [ArutyunyanHumanPlacenta](https://contribute.data.humancellatlas.org/projects/detail?uuid=aecfd908-674c-4d4e-b36e-0c1ceab02245)
primary wrangler: Arsenios

**Comment by idazucchi** [comment]
Also affecting [this project](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/1188)
uuid:`cc35f94e-e93b-4dbd-a08c-702978d9046f`
project short name: [FetalSkinDevImmune](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc35f94e-e93b-4dbd-a08c-702978d9046f)
[grafana](https://monitoring.ingest.archive.data.humancellatlas.org/d/yK-iu984z/export-single-submission?orgId=1&var-submission_uuid=0c619e36-accf-4367-b137-d19cedb07431)
primary wrangler: Ida

**Comment by amnonkhen** [comment]
- [x] 645b20c9-5ed0-4500-86b5-7aef770d010a - done
- [ ] 5bd01deb-01ee-4611-8efd-cf0ec5f56ac4
- [ ] aecfd908-674c-4d4e-b36e-0c1ceab02245
- [ ] cc35f94e-e93b-4dbd-a08c-702978d9046f
