### ISSUE TITLE
GSE182861-Single-cell RNA sequencing unveils the clonal and transcriptional landscape of cutaneous T-cell lymphomas

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1189]
### Associated files

* Google Drive:

### Published study links

* [Paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9197926/)

* [GSE182861](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE182861)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by anu-shiva** [comment]
Unassigning myself here +ingest as Rachel is handling Skin Bionetwork

**Comment by idazucchi** [comment]
this paper was part of the skin atlas roadmap but it's not in the official wave 2 list
