### ISSUE TITLE
stuck in metadata validating: Cortex-MGE-fusion-organoids

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#1192]
*Project Info*
uuid: da77bd06-43ae-4012-a774-e4d62797df51
project short name: Cortex-MGE-fusion-organoids
primary wrangler: Rachel Schwartz

stuck in metadata validating for ~2 days

Note:
assign to the current dev on operations.
@ESapenaVentura @amnonkhen

**Comment by idazucchi** [comment]
2 files got stuck in validation - I fixed it with the script to re-trigger validation [here](https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/retrigger_file_validation)

**Comment by rachadele** [comment]
thank you! how did you know 2 files were stuck?

**Comment by idazucchi** [comment]
I filtered each section of the submission by `Validating` and luckily the only entities that were stuck were files
