### ISSUE TITLE
Stuck in metadata validating 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#1198]
Submission for HCA dataset is stuck in 'metadata validating' - https://contribute.data.humancellatlas.org/submissions/detail?uuid=5002a0b7-eead-4a98-83b6-23d5da6ac48a&project=925f9a4c-cac0-444a-ad2c-612656ab3a85 

Created on October 31st, 13:54

**Comment by idazucchi** [comment]
I had a look and the only thing stuck were fastq files. I've re-triggered validation following the instructions [here](https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/retrigger_file_validation)
