### ISSUE TITLE
export problems for healthyAirwaysAtlas

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1200]
[submission in ui](https://contribute.data.humancellatlas.org/submissions/detail?uuid=73f6ac55-30e6-463b-a1eb-35620bfd3806)

error message during export of metadata when writing the staging_area.json file:

```
Could not verify completed upload for blob prod/ef1e3497-515e-4bbe-8d4c-10161854b699/staging_area.json within maximum wait time of 3600 seconds
```

See [monitoring](https://monitoring.ingest.archive.data.humancellatlas.org/d/yK-iu984z/export-single-submission?orgId=1&var-submission_uuid=73f6ac55-30e6-463b-a1eb-35620bfd3806&from=now-1h&to=now&refresh=30s)

**Comment by amnonkhen** [comment]
The problem is reproduced when I export the project again.
I still don't know what the cause is.

**Comment by idazucchi** [comment]
The failed export produced at least the project json so we filled out the import form to get the new lung atlas metadata to the browser.
The project has been forced to exported status - the export issues are not solved but might not show up again

**Comment by idazucchi** [comment]
Closing the ticket because this is low priority and we don't have capacity to investigate
