### ISSUE TITLE
Brokering test project to EGA

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1202]
**Description of the task:**
The DCP is preparing to accept managed access projects, but as a back up plan / to be ready for Organoid/Morphic (?) data we're testing a submission route to EGA

- meeting with Mallory and Marcos to discuss requirements
see summary workflow here - add miro board

Key points:
organaisation signs the DPA once (for HAC it could be HCA inc) and covers all wranglers working on managed access - we can then submit multiple projects
Each submitted projects need to have their DAC outlined and can differ datasets by dataset

**Acceptance criteria for the task:**
- [x] map one test project to the EGA schema
- [ ] get feedback from Marcos
- [ ] test with a real project?

**Comment by idazucchi** [comment]
to do:
- [ ] generate xmls
- [ ] generate all xmls
- [ ] test xmls with script - migth be out of date schemas?
- [ ] what is required for EGA submission account
- [ ] test webin submission
- [ ] validate xmls with webin

**Comment by idazucchi** [comment]
- [ ] sign DPA
- [ ] what alias do we use for run before we have the ERR?
- [ ] center name: wrangler's institute or submitter's?
- [ ] analysis type: sequence_variation and transcriptomics?
- [ ] analysis type: can we associate a file to a specific sample like for runs? multiple analysis?
- [ ] filetype for matrices: other? no better name?

**Comment by idazucchi** [comment]
credentials to do curl validation need to be the webin ones - I've gone through run, experiment, dataset - need to check the rest
also fix the samples

**Comment by idazucchi** [comment]
- [ ] add sampling location and date - see [missing fields practices](https://www.insdc.org/news/insdc-spatiotemporal-metadata-minimum-standards-update-03-03-2023/) and [here](https://www.insdc.org/submitting-standards/missing-value-reporting/)

**Comment by arschat** [comment]
@idazucchi to write documentation and close.

**Comment by idazucchi** [comment]
summary document [here](https://docs.google.com/document/d/1KAChfqVi_rpG-muBIMpyGACRsFhasuSYXThLYOnbGJw/edit?tab=t.0), with example spreadsheets linked
