### ISSUE TITLE
Incorrect linking in published DCP projects

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1205]
In the new Data Portal, there were [two projects](https://explore.data.humancellatlas.org/projects?filter=%5B%7B%22categoryKey%22%3A%22sampleEntityType%22%2C%22value%22%3A%5Bnull%5D%7D%5D) with sample type `unspecified`. After some investigation we found those projects are:

- `bfaedc29-fe84-4e72-a461-75dc8aabbd1b` ([DCP](https://explore.data.humancellatlas.org/projects/bfaedc29-fe84-4e72-a461-75dc8aabbd1b), [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=bfaedc29-fe84-4e72-a461-75dc8aabbd1b))
Although all specimens and cell suspensions fields exist and are connected as expected *(Donor->Specimen->Cell suspension)*, analysis_files are connected directly to donors.
- `65cbfea5-5c54-4255-a1d0-14549a86a5c1` ([DCP](https://explore.data.humancellatlas.org/projects/65cbfea5-5c54-4255-a1d0-14549a86a5c1), [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=65cbfea5-5c54-4255-a1d0-14549a86a5c1), #1116)
Although specimen fields exists, cell suspensions are linked directly to donor_organism instead of specimen.

Actions:
- [x] Update projects
    - [x] Allen Institute project ([DCP](https://explore.data.humancellatlas.org/projects/bfaedc29-fe84-4e72-a461-75dc8aabbd1b), [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=bfaedc29-fe84-4e72-a461-75dc8aabbd1b))
    - [X] McCormack-Human-10x3pv2 [DCP](https://explore.data.humancellatlas.org/projects/65cbfea5-5c54-4255-a1d0-14549a86a5c1), [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=65cbfea5-5c54-4255-a1d0-14549a86a5c1), #1116)
- [ ] Investigate why graph validation test were passed and investigate which test to have to avoid such cases

**Comment by arschat** [comment]
For the update, since the data is already published, maybe we should use the script to keep the uuids for all biomaterials & files since we will just change the linking.

**Comment by arschat** [comment]
Action items for the projects update:
- McCormack-Human-10x3pv2
    - [X] Link biomaterials
    - [X] Metadata valid, Graph valid, Submit & export
    - [X] Import form sent
- Allen Institute project 
    - There are 3 donors, 1209 specimens, 1209 cell suspensions and 4 analysis files all linked to all donors. We should instead link all 4 analysis files to all 1209 cell suspensions.
    - It is worth noting that on ingest there are 2 files with the same name, while on [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE182211) there is an extra _metadata file which is missing from DCP. 
    - [ ] Arsenios to write api script to update biomaterial linking
    - [ ] Ida and Enrique to review the script before is run
    - [ ] Graph valid, submit for metadata only & export
    - [ ] Import form sent

**Comment by arschat** [comment]
It was difficult to delete linking through api, and since there were only 3 donor x 4 processes =12 links, it was done through ingest UI. 
Correct linking is being done (started ~ 10:40 today) through api by Enrique with the following code snippet.

For future reference, the linking was available when done with `api.post(biomaterial/inputToProcess, process)`

<details>
  <summary>Code snippet</summary>

```
from hca_ingest.api.ingestapi import IngestApi
token = "<INGEST_TOKEN>"

api = IngestApi(url="https://api.ingest.archive.data.humancellatlas.org/")
# api = IngestApi(url="https://api.ingest.staging.archive.data.humancellatlas.org/")
api.set_token(f"bearer {token}")

submission_url = "https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/64aea7083d548a3f1b6a74e6"

# Collect processes url
query = [{
    "field": "content.describedBy",
    "operator": "REGEX",
    "value": "analysis_file"
},
    {
        "field": "project.id",
        "operator": "IS",
        "value": "641865a272536c7f2bdc225e"
    }
]
query_url = 'https://api.ingest.archive.data.humancellatlas.org/files/query?operator=AND'
analysis_files = api.post(query_url, json=query).json()['_embedded']['files']
processes_inputBiomaterials = []
for file in analysis_files:
    process_url = file['_links']['derivedByProcesses']['href']
    process = api.get(process_url).json()
    processes_inputBiomaterials.extend(process['_embedded']['processes'])

# Collect cell suspensions url
cell_suspensions = []
all_biomaterial_url = submission_url + '/biomaterials'
all_biomaterial = api.get_all(all_biomaterial_url, 'biomaterials')
for biomaterial in all_biomaterial:
    if biomaterial['content']['describedBy'].rsplit('/', 1)[-1] == 'cell_suspension':
        cell_suspensions.append(biomaterial)

# Add linkings to cell suspensions
for cs in cell_suspensions:
    cs_input_uri = cs['_links']['inputToProcesses']['href']
    for process_input in processes_inputBiomaterials:
        process_uri = process_input['_links']['self']['href']
        request = api.post(cs_input_uri, data=process_uri)
```
</details>

**Comment by arschat** [comment]
Both projects have been updated, exported and import form has been sent.
Discuss weather we need to keep ticket open to investigate how the linking was not detected by graph validator.

Here is the graph valid, donor to file, incorrect linked spreadsheet for the AllenInstitute Project for potential investigating purposes [ddc98eb6-e4be-451e-b446-40bb95d67f8f_20231121-153331.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4168d071b91e85cbc57c4aed3e44e10eb98eec40/ddc98eb6-e4be-451e-b446-40bb95d67f8f_20231121-153331.xlsx)

**Comment by idazucchi** [comment]
Enrique can't push changes to the IGV becaue he's locked out of GitLab

**Comment by idazucchi** [comment]
@idazucchi to test in staging

**Comment by idazucchi** [comment]
the test was deployed correclty - I'm closing the ticket
