### ISSUE TITLE
Retraction of dataset alzheimersFrontalCortex

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1211]
**What dataset is being retracted?**

- Project shortname: alzheimersFrontalCortex
- Project UUID: `c7a7fde7-aa8c-4ef0-9424-612b7cd2cdb4`
- Submission UUID: [256045f6-89cd-4f64-8cd0-05af92c0c7a8](https://contribute.data.humancellatlas.org/submissions/detail?uuid=256045f6-89cd-4f64-8cd0-05af92c0c7a8&project=c7a7fde7-aa8c-4ef0-9424-612b7cd2cdb4)
(if archived)
- DSP submission UUID: NA
- BioStudies accession: NA
- ENA Study/Project accession: NA

**Sources of \[meta]data**

- [x] Amazon buckets/EC2 instance
   - [x] Ingest upload area
   - [x] hca-util
- [x] Staging area
- [x] Spreadsheet
- [ ] ~~Ingest UI~~ not necessary

**Acceptance criteria for the task**:
- [x] All possible sources for data/metadata have been included
- [ ] The retraction SOP has been followed for all the possible sources

**Comment by ESapenaVentura** [comment]
Deleted staging area: `gsutil -m rm -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c7a7fde7-aa8c-4ef0-9424-612b7cd2cdb4`

**Comment by ESapenaVentura** [comment]
Ingest UI:
- [x] Hide project from catalogue
- [x] Mark it as delete
- [ ] Delete submission
- [ ] Delete project?

**Comment by ESapenaVentura** [comment]
Depending on their input, I will delete the project or just keep it in ingest and outside of the catalogue

**Comment by idazucchi** [comment]
check with Rachel that the hca-util was removed

**Comment by idazucchi** [comment]
bucket was removed
