### ISSUE TITLE
SCP1479 - CrossTissueNucleiEraslan

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1214]
### Project short name:
CrossTissueNucleiEraslan ~~Segr-Human-10x3pv2~~

### Primary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1DqPKiyTv1OoYeLp8CvPgadiH5SkXXjys)
* Ingest: [c14f788a-a438-459d-b470-ccb65e9e259e](https://contribute.data.humancellatlas.org/projects/detail?uuid=c14f788a-a438-459d-b470-ccb65e9e259e)

### Published study links

* Paper: [10.1126/science.abl4290](https://doi.org/10.1126/science.abl4290)

* Accessioned data: [SCP1479](https://singlecell.broadinstitute.org/single_cell/study/SCP1479/)
[phs000424](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000424.v9.p2)
[anvil.terra.bio/](https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GTEx_V9_hg38) (managed access)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Although no cause of death is defined for any of the donors, all donors have 0 (ventilator case) in **hardy scale**. This information is derived from the public metadata of the GTEx portal of the corresponding fixed tissue that is provided in the supplementary table 1 ([example](https://gtexportal.org/home/histologyPage/GTEX-1R9PN-0326))

**Comment by arschat** [comment]
Sequencing machine not clear.
[Manuscript methods](https://www.science.org/doi/10.1126/science.abl4290#sec-3):
> Libraries for snRNA-seq were generated using the Chromium Single Cell 3′ v2 Reagent Kit (10x Genomics), and sequencing was performed with Illumina HiSeq X (96 samples) or NextSeq (three samples), according to the manufacturer’s protocols. 

[Supplementary materials](https://www.science.org/doi/suppl/10.1126/science.abl4290/suppl_file/science.abl4290_sm.pdf) (page 5):
> Libraries were sequenced on an Illumina HiSeq X or NextSeq

Sending contributors email.

**Comment by arschat** [comment]
Besides the minor inconsistency mentioned before, I have filed the dataset for verification using only the first of the two sequencers mentioned. Before final submission, I will discuss that internaly.

**Comment by idazucchi** [comment]
Hi Arsenios! Nice job on this dataset! I only have a few comments

### Donor
-  the hardy scale correct?

### Specimen
- are the ids you're using matching those in the h5ad? if not I would reuse the publiaction's
- for esophagus samples: I would use [esophagus mucosa](https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002469) UBERON:0002469 and [smooth muscle of esophagus](https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002112) UBERON:0002112


### Dissociation
- dissociation seems more mechanical (pestle/scissors) or enzyme-free chemical dissociation since they're using detergent to break down the membrane


### Cell suspension
- description is missing
- Are the pooled samples missing from the h5ad?

### Library prep
- primer should be `poly-dT`

### sequencing
- if you want you can add this
>Libraries for snRNA-seq were sequenced with Illumina HiSeq X (96 samples) or NextSeq (three samples), according to the manufacturer’s protocols.

**Comment by arschat** [comment]
Applied changes.
- Changed the biomaterial_ID in both specimen & cell suspension to match `Sample ID` and `channel` columns respectively. Alternative name is in biomaterial_name
- Added also mechanical dissociation protocols and changed existing to enzyme-free chemical dissociation
- Pooled samples are not present (or presented as distinct samples) in h5ad. No `pooling` is mentioned in any of the adata.obs columns

Submission is now in graph valid. As discussed in standup we will wait for the first contact to authors to verify the sequence machine of all samples.

**Comment by arschat** [comment]
the pre-print of this publication has been already [published in DCP](https://explore.data.humancellatlas.org/projects/31887183-a72c-4308-9eac-c6140313f39c)
[ingest link](https://contribute.data.humancellatlas.org/projects/detail?uuid=31887183-a72c-4308-9eac-c6140313f39c)
