### ISSUE TITLE
contributor account for: Mattia Gerli

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1217]
Please create an account a contributor.

*Contributor details:*
* name: Mattia Gerli
* email: m.gerli@ucl.ac.uk

Request Details:
* Requested by: ida idazucchi@ebi.ac.uk @ida

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Introduction/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by ESapenaVentura** [comment]
Done - Sent to @idazucchi over slack
