### ISSUE TITLE
Update Spreadsheet Quick Guide

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1218]
**Description of the task:**
[Spreadsheet Quick Guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html) does not include instructions to fill the analysis file tab. There is an [open PR](https://github.com/ebi-ait/hca-metadata-community/pull/3) (ticket #431) on that but we should consider one of the following:
1. we merge the existing pr
1. we update the existing pr with more information about more recent analysis_file fields

Also, last commit was on 2020, so we might consider investigating for outdated pages in the SOP when capacity allows

**Acceptance criteria for the task:**

- [x] Merge PR (potentially update before)
- [ ] Investigate outdated pages in Quick Guide

**Comment by idazucchi** [comment]
@idazucchi to review the PR

**Comment by idazucchi** [comment]
next steps:
- [ ] ida to review
- [ ] merge --> the aim is to have at least some instructions rather than having a gap 
- [ ] second pass to add more detail where needed

**Comment by idazucchi** [comment]
Comment from Wei in the PR to address in next update --> _The only thing I would wonder is if we should add the 'Analysis_Files' content descriptions and ontology terms here or not._

**Comment by idazucchi** [comment]
the html didn't update - I have to check what happened

**Comment by arschat** [comment]
@ESapenaVentura To investigate

**Comment by ESapenaVentura** [comment]
I updated the quick guide in the ebi-wrangler repo , not the spreadsheet quick guide (Which is on another repo https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html, https://github.com/ebi-ait/hca-metadata-community/blob/gh-pages/contributing/spreadsheet-guide.md).


For some reason the page points out to that other one, don't really know why

**Comment by arschat** [comment]
There was an inconsistency with css units that caused the error in building.
I uncommented a variable definition in [_sass/custom/custom.scss](https://github.com/ebi-ait/hca-metadata-community/blob/gh-pages/_sass/custom/custom.scss) and now gh-pages is build and deployed.
[guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html)
