### ISSUE TITLE
E-MTAB-11268 - PressureInducedHypertrophicHeart

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1219]
### Project short name:
PressureInducedHypertrophicHeart
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1z8rqVNX4Ffcm1jScRII3x2rxOah34TQ-)

### Published study links

* Paper:  [A human cell atlas of the pressure-induced hypertrophic heart](https://doi.org/10.1038/s44161-022-00019-7)

* Accessioned data:  [E-MTAB-11268](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-11268)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=902dc043-7091-445c-9442-d72e163b9879)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
ready for secondary review

**Comment by arschat** [comment]
Very solid work Ida, on such a compact dataset. Well done.

The only comment I would make is that you could add in the biomaterials name or description the `Assay Name` : i.e.`3005` and `individual` ID : i.e.`103799-001-001` from array express [sdrf](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-11268/sdrf?full=true).

**Comment by idazucchi** [comment]
do we need to wrangle the other publication as well? the samples indicated in the list are : (14) + 5 so we might need to wrangle [this publication](https://pubmed.ncbi.nlm.nih.gov/32971526/) as well

**Comment by idazucchi** [comment]
applied suggestion, exported and filled in import form

**Comment by idazucchi** [comment]
reviewed in browser, needs minor update to add corresponding author

**Comment by idazucchi** [comment]
verified in browser
