### ISSUE TITLE
GSE203275 - MultiomicCongenitalHeartDisease

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1223]
### Project short name:
MultiomicCongenitalHeartDisease
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/14AEJaiEhxLupDE2SXBsOsjJGXImtyR-t?usp=drive_link)

### Published study links

* Paper: [Integrated multi-omic characterization of congenital heart disease](https://doi.org/10.1038/s41586-022-04989-3)

* Accessioned data:
    * [GSE203273](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE203273) atac
    * [GSE203274](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE203274) snRNA-seq
    * [SCP1852](https://singlecell.broadinstitute.org/single_cell/study/SCP1852/integrated-multiomic-characterization-of-congenital-heart-disease#study-download)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=c9e83418-a9f0-4ed1-ab4f-56d9513417bf&tab=project)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Controls:
Donor 1 - should be primary
Donor 2 - mystery - is it primary?
Donor 3
Donor 4
Donor 5
LVAdult2 - not in geo
LVAdult3 - not in geo

All other samples should be fine

Table 2 - master table  --> notes section has info on sample provenance & synonyms

**Comment by idazucchi** [comment]
ready for secondary review!

**Comment by arschat** [comment]
Excellent work, Ida! Well done figuring out all the specimen origins. I got only some very minor comments.

## Project
- Project description/ abstract has reference numbers that can be removed

### Donor organism
- `fixed subaortic stenosis` seems to be the most accurate to describe the "subaortic membrane resection with subaortic stenosis"

### Enrichment protocol
- Nice catch in having nuclei isolation in enrichment and not in dissociation so you can use the more detailed `density gradient centrifugation`

### Analysis protocol
- Description of `ATAC_tracks` includes a typo "Reads were mapped to the ~~mouse genome~~ human genome (hg19)"

**Comment by idazucchi** [comment]
thank you for your comments Arsenios!
I've fixed the things you suggested and I'm exporting now
