### ISSUE TITLE
SCP1849 - EndStageHeartFailureSimonson

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1225]
### Project short name: EndStageHeartFailureSimonson
(~~Ellinor-Human-10x3pv3--2~~)

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1E-Sk-zqvT2uOqax46xC-ssRzwn8a1LA_?usp=sharing)
* ingest: [c6ef0270-eafc-43bd-8097-c10020a03cfc](https://contribute.data.humancellatlas.org/projects/detail?uuid=c6ef0270-eafc-43bd-8097-c10020a03cfc)
* hca-util upload area `0eeae571-7ca2-4164-a6a4-8653340d1e1a`

### Published study links

* Paper: [Single-nucleus RNA sequencing in ischemic cardiomyopathy reveals common transcriptional profile underlying end-stage heart failure](https://www.cell.com/cell-reports/fulltext/S2211-1247(23)00097-9)

* Accessioned data: 
[SCP1849](https://singlecell.broadinstitute.org/single_cell/study/SCP1849/)
[phs001539.v4.p1](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001539.v4.p1)
[PRJNA433594](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA433594) (SRA has some public metadata but files are managed access redirecting to dbGaP in order to request access)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
## Notes

- **Known diseases** Mondo ontology does not have an term for ~ischemic cardiomyopathy~ (ICM). Although there is a cardiomyopathy term [MONDO:0004994](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes?short_form=MONDO_0004994), myocardial ischemia [MONDO:0024644](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes?short_form=MONDO_0024644) might be more appropriate for the term according to this widely cited [paper](https://www.ahajournals.org/doi/10.1161/circulationaha.106.174287)  classifying cardiomyopathies.
   > Therefore, the commonly used term “ischemic cardiomyopathy,” referring to myocardial ischemia and infarction, is not supported by this panel, nor is it part of the formal classification scheme.

**Comment by arschat** [comment]
Project files could not validate, see more at ebi-ait/dcp-ingest-central#988 .
Files successfully uploaded in util area & upload area
upload area: `s3://org-hca-data-archive-upload-prod/a9a75b4f-1539-4aa1-93f4-8a87f09963c2/`
util area: `s3://hca-util-upload-area/0eeae571-7ca2-4164-a6a4-8653340d1e1a/`

Other than that ready for sec review.

**Comment by arschat** [comment]
hca-util problem is fixed and project is in graph valid. ready for sec review

**Comment by idazucchi** [comment]
Hi Arsenios! Nice work on this dataset :)
I like that you mapped all the biosamples and experiment accessions to the CS since the files are manged access and can't be downloaded

### project 
- cell count should be 99,684

### Donor
- hardy scale - I didn't see ventilators being mentioned, where did you find this information

### analysis protocol
- can add the cited paper doi for processed matrix

**Comment by arschat** [comment]
Thanks for the review, Ida!
I have updated the project info and the analysis protocol with your suggestions.

About the organ donor - hardy scale:
It is indeed not mentioned in the paper that there is a ventilator, however, in order to for a deceased person to become an heart donor, the person has to be verified as brain dead (see [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4133543/))
> The primary survey of the donor includes the confirmation of brain death, verification of consent for donation, ABO blood typing, demographics, identification of potential co-morbid conditions (including high risk behavior, substance abuse history, mechanism of death) and the need for cardiopulmonary resuscitation (and if so duration from initiation to return of vital signs).

So, if a person donated their heart a brain death would be verified which (according to [this](https://www.nhs.uk/conditions/brain-death)) is
> Brain death (also known as brain stem death) is when a person on an artificial life support machine no longer has any brain functions. This means they will not regain consciousness or be able to breathe without support.

Therefore, if a person donated their heart, they were on artificial life support machine which includes ventilator.
We use the hardy scale that includes a scale 0 for "ventilator case"
> 0) Ventilator Case All cases on a ventilator immediately before death.

So, I am leaning towards filling the hardy scale with 0 for deceased heart donor. (All of that is due to the Tier 1 including the hardy scale field)

**Comment by arschat** [comment]
Project is now exported and import form sent.

**Comment by arschat** [comment]
Verified in the browser[.](https://dcp2.data.humancellatlas.org/explore/projects/c6ef0270-eafc-43bd-8097-c10020a03cfc?catalog=dcp35)
