### ISSUE TITLE
GSE183684 - CREDiseaseRetina

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1229]
### Project short name:
CREDiseaseRetina
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1N8KJ4_LEYBY3avXvgsYjvWveinqLqgSj?usp=drive_link)

### Published study links

* Paper: [Cell-specific cis-regulatory elements and mechanisms of non-coding genetic disease in human retina and retinal organoids](https://doi.org/10.1016/j.devcel.2022.02.018)

* Accessioned data: [GSE183684](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE183684)

- [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=aebc99a3-3151-482a-9709-da6802617763&tab=project)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
**Donors**
there's 10 donors + 2 for hiPSC cell lines - Donor 2 was used as starting point for all the organoids --> 12 donors
>The human induced pluripotent stem cell (hiPSC) lines (designated as cell line 1 and cell line 2) were derived from peripheral blood mononuclear cells from two separate, unaffected patients: one male donor, 61 years old; and one female donor, 58 years old. The male donor line was designated as cell line 1, and the female line was designated as cell line 2. 

post-mortem interval --> I'm assuming it's in hours but I'm not sure

**Comment by idazucchi** [comment]
the hca-util area is ready but I can't validate the files due to the issue with [hca-util sync](https://app.zenhub.com/workspaces/hca-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/gh/ebi-ait/dcp-ingest-central/988) so it's ready for secondary review

**Comment by idazucchi** [comment]
Amnon fixed the sync issues so I'm getting to graph valid before secondary review

**Comment by arschat** [comment]
Very well done, Ida! Nice work figuring out the organoids and cell lines experimental graph.
Only a few comments here.

### Cell suspension
- Should the cell_suspensions inherit the genotype of the KO organoids?
### Analysis protocol
- The `analysis_protocol.alignment_software` for the ATAC version is **Cellranger-atac**. Cellranger is a different software than Cellranger-atac.


Another minor comment I wanted to make is that the input for **cell_suspension** is in the `input specimen` column for all the CS, although some are from **organoids** and some from **cell_lines**. Similarly, in organoids tab, the input in `input specimen` column but the **cell_lines** are listed there. However, it does not break graph validator and ingest seems to detect the correct linking, and fix it (the downloaded spreadsheet is showing different input biomaterials).

**Comment by idazucchi** [comment]
Hi - thanks for catching the linking issue with the different biomaterials, I'm suprised ingest didn't throw an error for this one

for the genotype I think it makes sense to keep the info because they're still the same cells and have the same genotype
I've updated the alignment software and I'm exporting

**Comment by idazucchi** [comment]
minor update needed to add correspondent 

filled import form
