### ISSUE TITLE
Assess wrangling the new MVP datasets into SCEA

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#123]
**Description of the task:**

For the 17 datasets that will make it into the MVP, we want to assess the possibility of including them in the next Single Cell Expression Atlas (SCEA) release. 

In order to achieve this:

- [x] Check with SCEA when is their next release date.
- [ ] Ask SCEA to look if any dataset is unsuitable
- [ ] Assess wrangling capacity (If suitable)

**Acceptance criteria for the task:**

- [ ] Suitability for all 17 datasets is assesed.
- [ ] A plan has been talked through with SCEA
- [ ] This plan is documented and accessible.
- [ ] (If capacity) A new ticket is made specifying the plan to follow for all datasets

**Comment by ESapenaVentura** [comment]
Ask about establish adding data in a regular flow - Requirements, how to, is it possible?

**Comment by ESapenaVentura** [comment]
Apologies, I skipped the question at the end.

Yes, this sounds like an appropriate outline of what should be done. I can start investigating point 1

**Comment by ESapenaVentura** [comment]
I have created a draft based on the docs I've found. @clairerye if you can coordinate with whoever wrangler is in operations so they can take a look and improve this, it would be great.

https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/hca_to_scea_tools_SOP.html

**Comment by lauraclarke** [comment]
@ESapenaVentura Given the new wrangling board, is this something better tracked with the individual dataset tickets on the wrangling board?

I assume al datasets which need to go to SCEA should go into the SCEA column?

**Comment by ESapenaVentura** [comment]
@lauraclarke that is correct, with the newly-discussed procedures (which include SCEA suitability assessment while inputting the dataset in the tracking sheet) they should be tracked with the columns in the ZH board

**Comment by lauraclarke** [comment]
What about the 17 datasets we have curated that haven't gone to the SCEA yet? what needs to happen there to get them to the right place in zenhub?

**Comment by ESapenaVentura** [comment]
We need to:

- Re-open the tickets (if closed)
- Move them to the column
- Assign them the proper label

I can work on that tomorrow and we can close the ticket

**Comment by lauraclarke** [comment]
fantastic, thanks

**Comment by ESapenaVentura** [comment]
Done!

All datasets are labelled and under either the column "Needs update" or "SCEA/AE brokering"
