### ISSUE TITLE
GSE224995 - RiskVariantsAF

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1230]
### Project short name:
RiskVariantsAF
### Primary Wrangler:
Ida
### Secondary Wrangler:
Anu

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1n7c2XL4e6KUKqum2fewB40OARWqBcP16?usp=drive_link)

### Published study links

* Paper: [Single-cell genomics improves the discovery of risk variants and genes of atrial fibrillation](https://doi.org/10.1038/s41467-023-40505-5)

* Accessioned data: [GSE224997](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE224997) superseries
   * [GSE224995](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE224995) snRNA-seq
   * [GSE224996](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE224996) sATAC-seq

[**Ingest**](https://contribute.data.humancellatlas.org/projects/detail?uuid=377c35d1-93bf-470c-8067-08f954b269bd&tab=project)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
the paper doen't explicitly say that the donors are healthy but I think they are, no disease is mentioned and they are not refferred to as patients

**Comment by anu-shiva** [comment]
Hi Ida,
very minor comments, most of these are not absolutely needed, but optional
**Dissociation protocol**: You can add reagents
**Enrichment protocol**: For the size selection- MAX SIZE SELECTED can be added
**Sequencing protocol** :
- The SEQUENCING PROTOCOL NAME is sequencing protocol for both rows- is this unintentional? 
- Should NextSeq500 be added too in the IINSTRUMENT MANUFACTURER AND MODEL?

**Analysis protocol**: typo in Row 7 column B
**Analysis file**: process name and description can be added.


Some descriptions (analysis protocol, library prep have reference numbers still

**Comment by idazucchi** [comment]
Thanks for reviewing! 
I'm exporting the project now

**Comment by idazucchi** [comment]
reviewed in browser

**Comment by arschat** [comment]
Lattice team has uploaded a project for this DOI in march 25. Currently there are two duplicates of the same project. [DCP](https://explore.data.humancellatlas.org/projects/377c35d1-93bf-470c-8067-08f954b269bd)
[lattice](https://explore.data.humancellatlas.org/projects/0d737cce-1c1c-493a-8e2e-b00143bccc12). Project exists in [CELLxGENE platform](https://cellxgene.cziscience.com/collections/20eea6c8-9d64-42c9-9b6f-c11b5249e0e9) as well.
