### ISSUE TITLE
GSE165839 - HeartCellsGeneRegulation

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1234]
### Project short name:
HeartCellsGeneRegulation
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1eA9AOeYPNY3em9L1_769M6PwTGgo4K9u?usp=sharing)

### Published study links

* Paper: [Cardiac cell type-specific gene regulatory programs and disease risk association](https://doi.org/10.1126/sciadv.abf1444)

* Accessioned data: [GSE165839](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE165839) superseries
       * [GSE165837](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE165837) snATAC-seq
       * [GSE165838](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE165838) snRNA-seq
- UCSC cell browser? no accession
 
[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=87f519b4-8862-41f9-acff-75e823e0e430)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
useful sample breakdown in the first figure's description
donor metadata in supp table 1

**Comment by idazucchi** [comment]
ready for secondary review

**Comment by arschat** [comment]
Hi Ida! Well done wrangling that project so quickly!
I noticed only a couple of happy accidents. 

## Project - Contributors
- `project.contributors.laboratory` for some contributors there is a tab character separator and duplication of information
- Nice catch for filling all the provided orcid!

## Project - Funders 
- `project.funders.grant_id` There are two grant_ids collapsed in one

## Donor organism
- `donor_organism.death.cold_perfused` could be filled 
    > Donated hearts were **perfused** with **cold** cardioplegia before cardiectomy and then explanted immediately into an ice-cold physiologic solution as we previously described 

## Specimen & Cell suspension
- Typo in the `_.biomaterial_core.biomaterial_description` specimen/CS **form** -> specimen/CS **from**

## Library prep
- In the ATAC_library_prep the `library_preparation_protocol.nucleic_acid_source` is set to 'bulk nuclei' although it should be 'single nucleus'

## Analysis protocol
- You could include a 'raw matrix generation' protocol type, either to a new protocol or add it to a processed matrix generation existing one to describe that the creation of the raw count matrix (both for RNA & ATAC).

**Comment by idazucchi** [comment]
thanks for reviewing!
I applied the suggestions, exported and filled in the import from

**Comment by idazucchi** [comment]
Tier 2 dataset for Heart atlas v1.0

OA DCA --> signed on 11/3/26

I've reviewed the metadata sent by Amirhossein via email, and I've updated our project in ingest.
The project is exported and the import form filled for R59
