### ISSUE TITLE
HLCA v2 - Tier 2 fields

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1235]
Lung atlas integration team has reached to us with a list of fields they would like to introduce as Tier 2 fields for lung.
[Provided Lung Tier 2 spreadsheet](https://docs.google.com/spreadsheets/d/1agYkdTaEW75aaAJRLNQfgsOG2HB1MAj9/edit?usp=drive_link&ouid=101176945353039944995&rtpof=true&sd=true)

We should create a prototype template spreadsheet with mapping to existing fields, and with the new fields that we will incorporate.

- [x] Map existing fields to HLCA v2 - Tier2 fields
- [x] Generate the prototype template

[Here](https://docs.google.com/spreadsheets/d/1Ljfh29I919HEpYCo47cA3KXoxe603f3J/edit?usp=drive_link&ouid=101176945353039944995&rtpof=true&sd=true) is the spreadsheet that a mapping is being incorporated.

**Comment by arschat** [comment]
The ethnicity needs to be collected in IGSR codes. [In this spreadsheet](https://docs.google.com/spreadsheets/d/1SQTKya-fKj0LvZ1MYzhsO7YPpEFMV3cNzDbUKDUVw9w) is a mapping between the two ontologies, that is based on the codes for the population (we got them [here](https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/README_populations.md			)) and the HANCESTRO ontology description for example [here](https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0009)
> Includes individuals who either self-report or have been described by authors as East Asian or one of the sub-populations from this region (e.g Chinese). This category also includes individuals who genetically cluster with reference populations from this region, for example 1000 Genomes and/or HapMap CDX, CHB, CHS and JPT populations.



https://docs.google.com/spreadsheets/d/1SQTKya-fKj0LvZ1MYzhsO7YPpEFMV3cNzDbUKDUVw9w/edit#gid=0

**Comment by arschat** [comment]
## Notes

- [ ] ethnicity fields should be recorded in `superpopulation` of IGSR's definitions. [Here](https://docs.google.com/spreadsheets/d/1P3zhl_R9wQCWZqjPz8QfyiI18AVWhtHu/edit?rtpof=true) is a mapping that was attempted
- [X] the`bmi` -> `donor_organism.human_specific.body_mass_index`
- [ ] Smoking: Introduction of three new fields will be required `SMOKING STATUS`, `YEARS SINCE SMOKING CESSATION`,`SMOKING PACK YEARS` since `donor_organism.medical_history.smoking_history` does is recording "cigarettes smoked per day" as free text.
- [ ] the `protocol_tissue_dissociation` contains an enum of the specific enzymes used. We could introduce a field in the dissociation protocol to record the enzymes but the enum provided is lung specific, and enum contains different times as well (i.e. "Cold protease 1h" and "Cold protease overnight")
- [X] `height` -> `donor_organism.height`
- [X] `age_at_sampling` -> `donor_organism.organism_age` & `donor_organism.organism_age_unit.text`
- [ ] `Bronchitis` -> `donor_organism.diseases.text` in the Tier 2 metadata they provide an enum with True/ False/ Unknown. If we model it as a part of the diseases field, we would not be able to distinguish between False & Unknown.
- All other fields are test results & information about the COPD therapy given

**Comment by arschat** [comment]
There are three prototypes made.

In all cases, the not lung specific fields are introduced as part of donor_organism biomaterial or dissociation_protocol. More details on that in [this](https://docs.google.com/spreadsheets/d/1Ljfh29I919HEpYCo47cA3KXoxe603f3J/edit?usp=drive_link&ouid=101176945353039944995) spreadsheet.

1. [One Module](https://docs.google.com/spreadsheets/d/1tRsJHYpsZz31yRD1COYo2y-AXtv6QqjL/edit?usp=drive_link&ouid=101176945353039944995) for all fields that are most likely lung specific (test results, treatments, disease stages)
2. [Three Modules](https://docs.google.com/spreadsheets/d/1XumKIoNBtAxTonYwaTwDysFcpPLnH5bx/edit?usp=drive_link). One for test results, one for treatments, one for disease stages. This would be beneficial if we have the same field from multiple bionetworks, we could use interchangeably, without referencing a different bionetwork.
3. [Ontologised tests module](https://docs.google.com/spreadsheets/d/1UKhLIg_lDguFrGpreGMtAsWgi7jBI7-e/edit?usp=drive_link&ouid=101176945353039944995). In the `SNOMED` ontology, there are fields for **most** of the test results we have here. We could potentially, use a separate tab to capture the test results per donor & collapse all the results in 3 fields (`medical_test`, `medical_test_result`, `medical_test_result_unit`). The benefit of this is that we would have a very large amount of test available, that are bionetwork agnostic. The disadvantage is that this would require a script to convert the user-friendly, seperated tab view, into 3 arrays. Also, for tests that are not ontologised we should make an ontology request, or find a different alternative.

**Comment by arschat** [comment]
After discussion with Gabs & Ida, we sent the three module option, and there were two templates, a [default](https://docs.google.com/spreadsheets/d/11OD6KE5_uLj5amAIHkR3l5WlxmHH51yD/edit?usp=drive_link&ouid=101176945353039944995&rtpof=true&sd=true) one with all fields unhidden and a [minimal](https://docs.google.com/spreadsheets/d/1sM0eERTluXfHFtbVFLVdy_4G7bB8vfDa/edit?usp=drive_link&ouid=101176945353039944995&rtpof=true&sd=true) one, with only Tier 1 & 2 & DCP required fields.

**Comment by arschat** [comment]
Malte agreed with the mapping [here](https://docs.google.com/spreadsheets/d/11OD6KE5_uLj5amAIHkR3l5WlxmHH51yD/edit?usp=drive_link) but requested to have one flat sheet in the sample/ specimen level for Tier 2.

For HLCAv2 Malte verified that there would not be cell-line, organoid or spatial data and that there is no FACS sorting for these datasets, therefore the experimental design for all projects would be
`donor`-**collection**-->`specimen`--**dissociation**-->`cell_suspension`--**library_prep**/**seq**-->`seq_files`

Given that there would not be more biomaterials and protocols than that, we could provide a [flat spreadsheet](https://docs.google.com/spreadsheets/d/1El-fJQNKR0jNKAXBN4qj-QnwNu-RwpXm/edit#gid=1631729748) with the Tier 2 metadata, and if we also have Tier 1 and additional file metadata (not part of Tier 1 & 2) we would populate our spreadsheet that way.

**Comment by arschat** [comment]
Lung team got feedback from data generators on the Tier 2 list, and decided to add more fields. 
Stalled until we get more info on that.

**Comment by arschat** [comment]
Malte replied
* `donor_recruitment_site` is part of T1 and will be removed from T2
* `protocol_tissue_dissociation` adding "Mechanical dissociation (chilled) + detergent-based nuclei isolation", and
"Mechanical dissociation (frozen) + citric-acid based nuclei isolation" as well
* `secondary_disease_ontology_term_id` 
    >  We discussed this a bit, but actually feel like it would be quite important to separate the primary and secondary disease ontology term IDs, as data contributors may only give us a single disease ontology term if we ask for this in a single column. The secondary disease ontology term ID column should capture comorbidities, especially for COPD patients. Also, the medical doctor on the team mentioned that the order of diseases registered in a hospital has more to do with the ward a patient presents at, rather than any ordering of severity or importance. We could ask for "comorbidities" as disease ontology terms as well if you think this is better. But I think this wouldn't be too different from a secondary_disease_ontology_term_id.

**Comment by arschat** [comment]
Discuss Tier 2 ingestion process
> Would you be able to send us a final version of the metadata table with these changes? Or is there anything else that is missing?
> 
> Also, it would be good to confirm the metadata collection process with you. As I understand it at the moment we would proceed as follows:
> 
> The bionetwork coordinator/champion/team contacts data contributors asking for Tier 2 metadata, attaching the google sheet or excel file, CC'ing someone from your side in the email and mentioning that this sheet would need to be sent to you.
> 
> You follow-up with data contributors sending them an agreement about storing the metadata under managed access
> You monitor the collection of tier 2 metadata, occasionally updating us about the ingestion status (maybe via the tracker?).
> 
> Is that correct? Or are there other steps that we would be involved in?

**Comment by arschat** [comment]
We have concluded that HLCA tier2 fields will be the above, and contributors will provide a single tab, simplified version of the DCP spreadsheet ([example](https://docs.google.com/spreadsheets/d/13LzXeKgnueSL7bSZ9QtDre-WK2VG75Xz/edit?gid=1268900243#gid=1268900243)).

This ticket can now close.

**Comment by arschat** [comment]
To keep track, Malte requested another field to be added named "Percentage of Emphysema". They also provided a definition. Field is added in the [template](https://docs.google.com/spreadsheets/d/13LzXeKgnueSL7bSZ9QtDre-WK2VG75Xz/edit?gid=1939708684#gid=1939708684) that way:
`emphysema_percentage`
Description: "Indicate the percentage of the lung that is affected by emphysema as judged based on non-invasive imaging, such as from a CT scan"

**Comment by arschat** [comment]
To keep track, Malte requested another field to be added named "Percentage of Emphysema". They also provided a definition. Field is added in the [template](https://docs.google.com/spreadsheets/d/13LzXeKgnueSL7bSZ9QtDre-WK2VG75Xz/edit?gid=1939708684#gid=1939708684) that way:
`emphysema_percentage`
Description: "Indicate the percentage of the lung that is affected by emphysema as judged based on non-invasive imaging, such as from a CT scan"

**Comment by idazucchi** [comment]
### Metadata collection
We're going to use a spreadsheet with two tabs:
- tier 2 - prioritised
- GD - recommended
We need to explain this in the email we send and specify that the first one is more important, and that where the information is not available they can fill in with unkonwn

**Comment by arschat** [comment]
After the #1245 discussion with genetic diversity we concluded to the removal of the ethnicity list field from the lung tier 2 in favour of the selfreported_freetext field.
