### ISSUE TITLE
contributor account for: Luozixian Wang

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1236]
Please create an account a contributor.

Contributor details:
* name: Luozixian Wang
* email: luozixianw@student.unimelb.edu.au

Request Details:
* Requested by: @arschat 
* request email details:
> Authors want to submit their data to HCA ([emails here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/rJ6OOpFmZbc/m/6VExPhWeAAAJ))

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Introduction/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by ESapenaVentura** [comment]
Sent credentials to @arschat 🙂
