### ISSUE TITLE
GSE226314 - CardiacFunctionalRecovery

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1238]
### Project short name:
CardiacFunctionalRecovery
### Primary Wrangler:
Ida
### Secondary Wrangler:
arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1rwHm_xYj3zBx7cVyp7fdmwF6urjOWV1a?usp=drive_link)

### Published study links

* Paper: [Defining cardiac functional recovery in end-stage heart failure at single-cell resolution](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10426763)

* Accessioned data: [GSE226314](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE226314)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=c0fecf0b-af86-41b8-ba82-d5fd81b7542a)
### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
### Donors
there are 3 donors in GEO that are not described in the supplementary table, so I'm including them with minimal metadata.
ETOH Hx --> alcohol history y/n - the information is extremly vague and doesn't match our metadata format. I would skip this but please tell me what you think
substance abuse --> description?
is there a specific term for the types of Cardiomyopathy or just Cardiomyopathy?

**Comment by idazucchi** [comment]
ready for secondary review

**Comment by arschat** [comment]
Hey Ida! Well done wrangling this project too, I have some minor comments.
I have uploaded the metadata of the rds file in the google drive folder just in case it is needed, since the rds is quite big to open locally.

## Project - contributors
- Typo in institute of Christoph,,Kuppe and Rafael,,Kramann


## Donor 
- `substance abuse` we don't have a field for that, it could be recorded in the description
- `alcolhol abuse` is indeed very vague but I would record that information since the field allows such flexibility
    Here is a list with all biomaterials with this field filled, in which for almost half of them the value is not units/day.
    <details>
	<summary>Alcohol History field</summary>

	`5cdd1fd5d96dad00085af1e6`	No alcoholism reported
	`5cdd1fd5d96dad00085af1e7`	No alcoholism reported
	`5cdd1fd5d96dad00085af1e8`	No alcoholism reported
	`5cdd1fd5d96dad00085af1e9`	No alcoholism reported
	`5cdd1fd5d96dad00085af1ea`	No alcoholism reported
	`5cdd1fd5d96dad00085af1eb`	No alcoholism reported
	`5cdd1fd6d96dad00085af1ec`	No alcoholism reported
	`5cdd1fd6d96dad00085af1ed`	No alcoholism reported
	`5cdd1fd6d96dad00085af1ee`	No alcoholism reported
	`5cdd1fd6d96dad00085af1ef`	No alcoholism reported
	`5cdd1fd6d96dad00085af1f0`	No alcoholism reported
	`5cdd1fd6d96dad00085af1f1`	No alcoholism reported
	`5cdd1fd6d96dad00085af1f2`	No alcoholism reported
	`5d76adf5aa252400084a0d3a`	Yes, amount unknown
	`5d76adf5aa252400084a0d3b`	4-6 per week
	`5d850511bddf5d0008993518`	daily (alcoholic)
	`5d850511bddf5d0008993519`	not reported
	`5d850511bddf5d000899351a`	socially
	`5d850511bddf5d000899351b`	heavy
	`5d850511bddf5d000899351c`	not reported
	`5f0f273432d8c765c3fdfa33`	unknown
	`5f0f273432d8c765c3fdfa34`	<1U/day (for 20 years)
	`5f1b0ea3fe9c934c8b835c82`	non-drinker
	`5f1b0ea3fe9c934c8b835c84`	<1u/day for 30 years
	`5f1b0ea3fe9c934c8b835c85`	<1u/day
	`5f1b0ea3fe9c934c8b835c86`	1-2u/day for 50 years
	`5f1b0ea3fe9c934c8b835c87`	<1u/day
	`5f1b0ea3fe9c934c8b835c88`	3-6u/day for 41 years
	`5f1b0ea3fe9c934c8b835c89`	>9U/day for 20 years
	`5f2bea2a4f36d156a8be1a48`	<1u/day
	`5f2bea2a4f36d156a8be1a49`	<1u/day
	`5f2bea2a4f36d156a8be1a4a`	3-6u/day fo 41 years
	`5f2bea2a4f36d156a8be1a4b`	unknown units but previously a heavy drinker for 25 years
	`5f2bea2a4f36d156a8be1a4c`	non-drinker
	`5f2bea2a4f36d156a8be1a4d`	non-drinker
	`5f5fa002db657458f1bdc3b8`	<1u/day
	`5f5fa002db657458f1bdc3c5`	non-drinker
	`5f5fa002db657458f1bdc3c6`	<1u/day
	`602e967491708e06ec03296b`	Occassional
	`602e967491708e06ec03296c`	Yes
	`602e967491708e06ec03296d`	No
	`602e967491708e06ec03296e`	Occassional
	`602e967491708e06ec03296f`	Occassional
	`602e967491708e06ec032970`	Yes
	`602e967491708e06ec032973`	No
	`602e967491708e06ec032974`	No
	`602e967491708e06ec032975`	Occassional
	`602e967491708e06ec032976`	Yes
	`602e967491708e06ec032977`	Yes
	`602e967491708e06ec032979`	Yes
	`602e967491708e06ec03297a`	Occassional
	`602e967491708e06ec03297b`	No
	`602e967491708e06ec03297c`	No
	`602e967491708e06ec03297d`	No
	`602e967491708e06ec03297e`	No
	`602e967491708e06ec03297f`	Yes
	`602e967491708e06ec032980`	No
	`602e967491708e06ec032981`	No
	`602e967491708e06ec032982`	Yes
	`602e967491708e06ec032983`	No
	`602e967491708e06ec032984`	Yes
	`602e967491708e06ec032985`	Yes
	`602e967491708e06ec032986`	No
	`602e967491708e06ec032987`	Yes
	`602e967491708e06ec032988`	Occassional
	`602e967491708e06ec032989`	Occassional
	`602e967491708e06ec03298b`	Occasional
	`602e967491708e06ec03298c`	Yes
	`602e967491708e06ec03298d`	No
	`602e967491708e06ec03298e`	No
	`602e967491708e06ec03298f`	No
	`6050248d91708e06ec074ec0`	unknown
	`6050248d91708e06ec074ec1`	unknown
	`6050248d91708e06ec074ec2`	unknown
	`6050248d91708e06ec074ec3`	unknown
	`6050248e91708e06ec074ec4`	unknown
	`6050248e91708e06ec074ec5`	unknown
	`6050248e91708e06ec074ec6`	unknown
	`6050248e91708e06ec074ec7`	unknown
	`6050248e91708e06ec074ec8`	unknown
	`6050248e91708e06ec074ec9`	unknown
	`60c1df436c83615dd894498a`	1 unit/week
	`623c613fb06b223527d25e98`	1-2u/day for 50 years
	`623c613fb06b223527d25e99`	<1u/day for 10 years
	`623c613fb06b223527d25e9a`	3-6u/day for 41 years
	`623c613fb06b223527d25e9c`	nondrinker
	`623c613fb06b223527d25e9d`	nondrinker
	`624d8df5b06b223527d4d5d6`	1-2 alcohol units  per day
	`624d8df5b06b223527d4d5d9`	4 alcohol units per day
	`624d8df5b06b223527d4d5e7`	6 alcohol units per day
	`62f0ef509e42135dda854a3f`	0 alcohol units/day
	`62f0ef509e42135dda854a40`	0 alcohol units/day
	`62f0ef509e42135dda854a41`	0 alcohol units/day
	`62f0ef509e42135dda854a42`	0 alcohol units/day
	`62f0ef509e42135dda854a43`	0 alcohol units/day
	`62f0ef509e42135dda854a44`	0 alcohol units/day
	`62f0ef509e42135dda854a45`	0 alcohol units/day
	`62f0ef509e42135dda854a46`	0 alcohol units/day
	`62f0ef509e42135dda854a47`	0 alcohol units/day
	`633c2c3980fa451243ce2790`	1-2 units/day for 50 years
	`633c2c3980fa451243ce2791`	<1unit/day for 10 years
	`633c2c3980fa451243ce2792`	>9units/day for 20 years
	`633c2c3980fa451243ce2793`	1-2units/day for 35 years
	`633c2c3980fa451243ce2794`	nondrinker
	`633c2c3980fa451243ce2795`	3-6units/day for 20 years
	`633c2c3980fa451243ce2796`	3-6units/day for 40 years
	`633c2c3980fa451243ce2797`	<1unit/day for 45 years
	`64260264c99baf0c6c9f1d67`	0.3 drink per day
	`64260264c99baf0c6c9f1d68`	1 drink per day
	`64260264c99baf0c6c9f1d69`	1.1 drink per day
	`64260264c99baf0c6c9f1d6e`	1.4 drink per day
	`64260264c99baf0c6c9f1d75`	0.6 drink per day
	`64260265c99baf0c6c9f1d76`	1 drink per day
	`64260265c99baf0c6c9f1d7a`	2 drink per day
	`64260265c99baf0c6c9f1d7c`	2 drink per day
	`64260265c99baf0c6c9f1d7d`	1.7 drink per day
	`64260265c99baf0c6c9f1d7e`	0.3 drink per day
	`64260265c99baf0c6c9f1d7f`	1.1 drink per day
	`64260265c99baf0c6c9f1d81`	0.7 drink per day
	`64260265c99baf0c6c9f1d82`	0.6 drink per day
	`64260265c99baf0c6c9f1d86`	2 drink per day
	`64260266c99baf0c6c9f1d8c`	1.4 drink per day
	`64260266c99baf0c6c9f1d8d`	1.4 drink per day
	`64260266c99baf0c6c9f1d92`	2 drink per day
	`64260266c99baf0c6c9f1d96`	0.4 drink per day
	`64260266c99baf0c6c9f1d97`	0.1 drink per day
	`64260266c99baf0c6c9f1d99`	0.4 drink per day
	`64260266c99baf0c6c9f1d9c`	2 drink per day
	`64260267c99baf0c6c9f1d9d`	0.1 drink per day
	`64260267c99baf0c6c9f1d9e`	0.4 drink per day
	`64260267c99baf0c6c9f1da1`	2 drink per day
	`64260267c99baf0c6c9f1da2`	2 drink per day
	`64260267c99baf0c6c9f1da4`	0.4 drink per day
	`64260267c99baf0c6c9f1da7`	2.1 drink per day
	`64260267c99baf0c6c9f1da9`	0.1 drink per day
	`64260268c99baf0c6c9f1db3`	0.3 drink per day
	`64260268c99baf0c6c9f1db7`	3 drink per day
	`64260268c99baf0c6c9f1db8`	1 drink per day
	`64260268c99baf0c6c9f1dba`	1.4 drink per day
	`64260268c99baf0c6c9f1dbf`	0.6 drink per day
	`64260269c99baf0c6c9f1dc5`	0.9 drink per day
	`64260269c99baf0c6c9f1dc7`	0.7 drink per day
	`64260269c99baf0c6c9f1dc8`	0.7 drink per day
	`6446bfe35178b3171274db7b`	<1 unit/day
	`6446bfe35178b3171274db7c`	<1 unit/day
	`6446bfe35178b3171274db7d`	>9 units/day
	`6446bfe35178b3171274db7e`	>9 units/day
	`6446bfe35178b3171274db7f`	2 units/day
	`6446bfe35178b3171274db80`	<1 unit/day
	`6446bfe35178b3171274db81`	<1 unit/day
	`6446bfe35178b3171274db84`	>3 units/day
	`6446bfe35178b3171274db85`	<1 unit/day
	`6446bfe35178b3171274db86`	<1 unit/day
	`65201cd7fb47305198b91797`	history of alcohol abuse
	`656a01847741856bcf3c7e18`	3-6 units/day, 40 years
	`656a01847741856bcf3c7e19`	1 unit/day
	`656a01857741856bcf3c7e1a`	Heavy drinker 25 years but units/day unknown
	`656a01867741856bcf3c7e1b`	3-6 units / day, 20 years
	`656a01877741856bcf3c7e1c`	0
	`656a01877741856bcf3c7e1d`	1 unit/day, 30 years
	`656a01887741856bcf3c7e1e`	1-2 units/day, 20 years
	`656a01897741856bcf3c7e1f`	0
	`656a01897741856bcf3c7e20`	1 unit/day, 30 years
	`656a018a7741856bcf3c7e21`	1 unit / day, 50 years
	`656a018b7741856bcf3c7e22`	7-9units/day
	`656a018b7741856bcf3c7e23`	7-9 units/day
	`656a018c7741856bcf3c7e24`	1-2 units/day, 50 years
	`656a018d7741856bcf3c7e25`	1 unit/day
</details>


## Library preparation
- the cell barcode length is 14. However, in [this](https://www.10xgenomics.com/support/single-cell-immune-profiling/documentation/steps/sequencing/sequencing-requirements-for-single-cell-v-d-j) document, the "Single Cell 5' Gene Expression Libraries (v1 and v1.1)" specifies that Read 1 which contain cell barcode + UMI has 26 bp length. I am not 100% sure about this, and the [teichman lab page](https://teichlab.github.io/scg_lib_structs/) does not specify structure for 5' GEX v1.1. Let me know what you think.

## Analysis files
- you could specify the matrix cell count for the analysis file:
    > 62459 features across **185881** samples within 2 assays
    > RNA (33694 features, 0 variable features
    > SCT (28765 features, 3000 variable features)
- you could specify the file source of the data (GEO)

**Comment by idazucchi** [comment]
thanks for the review!
I've applied the suggestions and started the export

**Comment by idazucchi** [comment]
`||` were found during the indexing process, I've updated the project and re-released for R37

**Comment by idazucchi** [comment]
verified in the browser!
