### ISSUE TITLE
Identify outstanding gaps in data lifecycle SOPs

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#124]
**Description of the task:**
As a member of the EBI ingest team, I would like to have a clear idea of what are the SOPs followed through the life cycle of data in ingest.

Currently, wranglers have [a visual index](https://ebi-ait.github.io/hca-ebi-wrangler-central/) with somewhat incomplete SOPs, and developers have combination of a [wiki](https://github.com/ebi-ait/hca-ebi-dev-team/wiki) and [google docs](https://drive.google.com/drive/u/0/folders/137ztd4LRMzWBRDdccBCNSricfq_vmp7L)

For this sprint, I'd like to identify gaps in data lifecycle-related SOPs:

I have created a blank google doc to be used to initially collect the URL to the SOP and the missing/out of date information
   - Google doc [here](https://docs.google.com/document/d/1AX_1Uvk-BQCj9SzMngay9oZD6tNGZo615OCO8VwHmTo/edit)
   - Please fill it in with a link to the document and a general outline of what is missing/outdated

@rays22 @aaclan-ebi @ESapenaVentura will fill this in by mid-sprint and @ESapenaVentura will create the tickets about which documents need to be updated.

This is a background task: the intention is to fill in the ticket when we are following the SOPs and the documentation itself will be updated through tickets

**Acceptance criteria for the task:**
- [x] Gaps have been identified and notified
- [x] A ticket for each document has been updated

**Comment by ESapenaVentura** [comment]
There is a big gap in archiving, as we rely in a google doc instead of an actual SOP in the repo

I have added a new SOP for that part of the wrangling process:

- https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/docs/SOPs/archiving_SOP.md

And added it to the wrangler visual index, accessible via clicking the box "submit to dsp"

**Comment by rays22** [comment]
* Gaps to fill:
Create a new SOP to update the Dataset Tracking Sheet https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/140
* Documentation update needed:
Update Ontologies SOP with latest process https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/142

**Comment by ESapenaVentura** [comment]
All tickets have now been opened so this ticket is not necessary

Closing
