### ISSUE TITLE
GSE215403 - OSCC-GBTwoCellularPrograms

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1241]
### Project short name:
OSCC-GBTwoCellularPrograms
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1n-1uGcmwcv5CHZzjTtzJSgQCkUDpLFNC?usp=sharing)

### Published study links

* Paper: [Single-cell transcriptomic analysis of gingivo-buccal oral cancer reveals two dominant cellular programs](https://onlinelibrary.wiley.com/doi/10.1111/cas.15979)

* Accessioned data: [GSE215403](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE215403)

[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=46a7e4bf-0474-4a8f-8d18-43afcde90491)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
ready for review!

**Comment by arschat** [comment]
Great job Ida, I have only a couple of very minor comments.

### Library prep protocol
- `library_preparation_protocol.nucleic_acid_source` is **"single nucleus"** however in the publication there is no mention of nucleus but only **"single cell"**.
 
### Sequence file
- You could specify the "file source" field.

**Comment by idazucchi** [comment]
reviewed and started exoprt

**Comment by idazucchi** [comment]
export completed and filled import form

**Comment by idazucchi** [comment]
verified in browser
