### ISSUE TITLE
GSE188478 - MappingParotidGland

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1242]
### Project short name:
MappingParotidGland
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1vI_LSD398gwLl-usWFwGFfJ87Sq9X2Ln?usp=sharing)

### Published study links

* Paper: [Transcriptomic Mapping of Human Parotid Gland at Single-Cell Resolution](https://doi.org/10.1177/00220345221076069)

* Accessioned data: [GSE188478](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE188478)

[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=750b455a-e3cf-4721-9581-8609a6c9d561)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Excellent job, Ida! No comments at all from my sec review :)

**Comment by arschat** [comment]
Excellent job, Ida! No comments at all from my sec review :)

**Comment by idazucchi** [comment]
filled out import form

**Comment by idazucchi** [comment]
reviewed in browser
