### ISSUE TITLE
GSE217720 - FibroblastProgenitorImmunomodulation

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1244]
### Project short name:
FibroblastProgenitorImmunomodulation
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1adqJTRmj1wOIww3PeT5_dJ1blfjvfLui?usp=sharing)

### Published study links

* Paper:  [Distinct fibroblast progenitor subpopulation expedites regenerative mucosal healing by immunomodulation](https://doi.org/10.1084/jem.20221350)

* Accessioned data: [GSE217720](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE217720) mouse + human donors

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=6836c1e4-906b-4c34-a11c-cb025167896d)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
**Donors**
I think it's just one mouse, but I'm not sure. There is very little donor metadata, it's all in GEO

**Comment by anu-shiva** [comment]
Hi Ida :) 

Here are my thoughts-

- **Project funders**
The grants look duplicated to me- NCIDR = National Institute of Dental and Craniofacial Research

- **Donor organism** mouse developmental ontology is mentioned from HsaDv? Are we not using EFO now?

- **Enrichment protocol**
The ENRICHMENT PROTOCOL NAME can be filled out for FACS enrichment

- **Library prep** + **Analysis protocol**
 I am assuming you relied on the SRA description of 10X3' v2 for library prep. The paper mentions only 10X genomics
however, in the NUCLEIC ACID SOURCE -shouldn't it be _single cell_ ? 
for the Analysis protocol - the paper doesn't mention the version and the first sentence in the description
(at first I thought that library prep and analysis were a mix up from another dataset but then I found the library prep on SRA but not on analysis protocol)

And a ques
- **Dissociation protocol**
The paper just mentions that the human samples were processed 'as described above'. I am guessing that is why we used the same dissociation info for both human and mouse? and is that the reason you have tied the two enrichments to only mouse as it is is not clear from the paper if cell size enrichment was performed for human samples.

**Comment by idazucchi** [comment]
Thanks for reviewing!
I didn't fill in the experiment accession because it is only meant for the sequence file tab, to describe the sequencing experiment.

The dissociation protocol is the same for human and mouse, based on GEO and the paper. Only the mouse cells were subjected to FACS, as described in the GEO sample

**Comment by idazucchi** [comment]
I've made the corrections and I'm exporting

**Comment by idazucchi** [comment]
verified in browser
