### ISSUE TITLE
SpatialRetinoblastomaWong

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1248]
### Project short name: 
SpatialRetinoblastomaWong

### Primary Wrangler:
LUOZIXIAN WANG; Arsenios

### Secondary Wrangler:
Ida

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1nGpNJA9GC4961I-pTdWw7QOYdsvwVseZ?usp=drive_link)

### Published study links

* Paper: [Spatial transcriptomic profiling of human retinoblastoma](https://www.biorxiv.org/content/10.1101/2024.02.05.578886v1)

* Accessioned data:

* ingest: [1662accf-0e0c-48c4-9314-5aba063f2220](https://contribute.data.humancellatlas.org/projects/detail?uuid=1662accf-0e0c-48c4-9314-5aba063f2220&tab=project)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Comments made for the provided spreadsheet.
- Authors in "Project - Publications" should be separated by double pipe, '||'
- "Biological sex" & "Alive at collection" fields should be lowercase
- If donor does not have "Known diseases" we fill "normal" for the PATO:0000461 ontology entry so we can search for non-diseased tissue
- would "phakic eyes" and "bilateral intraocular lens" be more relevant to treatment instead of known diseases? If not what ontology from MONDO would be relevant? https://www.ebi.ac.uk/ols4/ontologies/mondo
- Since "retrieval time to collect the sample" is recorded in the specimen timecourse level, we don't have to record that in the donor level too. We prefer to record at the specimen level since it is sample metadata.
- "Adjacent disease" should be used if specimen is not affected by disease but close to the collected specimen there is affected tissue of the disease. it is mostly used for "healthy" vs tumor specimens from the same tissue
- "Visium_permeabilization_protocol" might be better described in the Image preparation protocol instead of dissociation protocol since in "Dissociation Method" we should have one of mechanical/ enzymatic/ non enzymatic dissociation
- for visium datasets, we don't have cell_suspensions but sequencing & analysis files are derived directly from image_specimen. see more at the Visium curation guidelines [here](https://ebi-ait.github.io/hca-ebi-wrangler-central/technology_types_guide/10X_Visium/Curation_guidelines.html), sorry for not providing this guide before. 
- We would also require the "Magnification" field in the Imaging protocol. If no magnification is used you could fill 1x.

**Comment by arschat** [comment]
I sent a spreadsheet with the comments applied and waiting for contributor to verify that all changes are correct and to upload files.

**Comment by idazucchi** [comment]
Hi Arsenios! The dataset looks great, I have only small comments
- why is this marked as a mix of open and managed? where is the managed access data? should they become part of the pilot?

### Specimen
- specimen 1, organ should be eye
- other specimens: aren't these all retinas?
- timecourse and post-mortem are redundant, you can keep just post-mortem

### imagined specimen
- move the permeabilisation time to permeabilisation_time in the imaging prep protocol

### library
- the cell barcode should be empty, you need to fill in the umi barcode and the spatial barcode length is not right, see the [cheat sheet](https://docs.google.com/spreadsheets/d/1H9i1BK-VOXtMgGVv8LJZZZ9rbTG4XCQTBRxErdqMvWk/edit#gid=0)

### sequencing
- paired end should be no

### imaging
- the microscopy setup is missing

### analysis protocol
- descrition: move the github link to the supplementary materials and remove the references
- you can add quantification to derivation process

**Comment by arschat** [comment]
Thanks Ida! I've updated the submission, and project is now in:
- [X] metadata valid
- [X] graph valid
- [ ] exported
- [ ] import form sent


About the question:
> why is this marked as a mix of open and managed? where is the managed access data? should they become part of the pilot?
There is no submitted data on any other archive yet. Their project includes data from deceased and living donors. The raw data from living donors have not been included in the submission. I can get in contact with them about making this a pilot project for MA. We will discuss today @ ops review

**Comment by arschat** [comment]
Verified in browser.
