### ISSUE TITLE
Japan MA pilot - Hon

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1249]
### PI
Chung-Chau Hon

### Associated files:

- Published paper: not sure if it's available 
- [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=35d5b057-3daf-4ccd-8112-196194598893)

### Key Events

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [ ] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by idazucchi** [comment]
The AIDA coordinator has sent us the list of signers for the DCA
I'm registering an empty project in ingest to have a project uuid to reference in the DCA

**Comment by idazucchi** [comment]
Today I met with Kian Hong - AIDA project data coordinator - to review the metadata spreadsheet before submission.
We agreed on a few small edits, the spreadsheet is practically ready for ingestion.
Kian also provided useful feedback on the spreadsheet and guide, I will add to a ticket or make a new one and address it

todo:
- [ ] improve spreadsheet guide + template
- [ ] wait for greenlight on DPA + ingest
- [ ] send credentials
- [ ] send uuid
- [ ] prep script for ontologies?
- [ ] notify dcp components

**Comment by idazucchi** [comment]
hca-util credentials received

**Comment by idazucchi** [comment]
I've reviewd the metadata and linking, uploaded the final spreadsheet for the submission and sync'ed the files

for MA datasets it's essential to remove the metadata files from the sumbission or it won't validate

now it's graph valid and I'm exporting

**Comment by idazucchi** [comment]
exported and filled in import form!

**Comment by idazucchi** [comment]
Kian asked us to add variant calling data
and I'm updating the title as well

**Comment by idazucchi** [comment]
Added vcf file, analysis protocol and process
Linked file to CSs
Updated project title
Exported
Filled in import form

**Comment by arschat** [comment]
Verified that one `vcf.gz` file is now available for the project.
