### ISSUE TITLE
Identify and document acknowledgment of datasets

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#125]
**Description of the task:**

As a data wrangler, I would like to set up a regular cadence at which we acknowledge new datasets and assess them. Before writing/updating a SOP, we should identify:

- How many data sources we have:
   - ArrayExpress
   - GEO
   - Single cell studies database

- If it's possible to set up a programmatic way to extract new data from those sources and compare it with the tracking sheet (Dev ops)
    - How much data is needed to avoid duplication

- How frequently do we want to run this script 

- Who runs the script

- The wrangler that acknowledges the dataset needs to assess it?

I will be making a proposal and posting it in the ticket soon.

**Acceptance criteria for the task:**
- [x] The proposal has been written and posted in the ticket
- [ ] The proposal has been reviewed by Laura, @clairerye and other wranglers
- [ ] The proper tickets for devOps have been created so the SOP can be written on the next sprint

**Comment by ESapenaVentura** [comment]
Proposal [here](https://docs.google.com/document/d/10yjBLGpxBoyjZORWXnBaGeq1yf17klWcNtbCt8eU9b0/edit#) 

If @clairerye , @lauraclarke and @ebi-ait/hca-wranglers could review it, it would be great.

It is a fairly simple SOP, it mainly answers 3 questions: who, when and how

**Comment by lauraclarke** [comment]
Need to merge with https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-wrangler-central/140

@mshadbolt thinks at least some of these issues will be resolved by the hackathon on Thursday. A positive outcome of Thursday would be what the next steps are to give the operations team a standard SOP so this could be run every sprint as a standing task

**Comment by lauraclarke** [comment]
@ESapenaVentura is this needed anymore with the updates to the data tracker?

**Comment by ESapenaVentura** [comment]
Yes, this one is needed because the SOP actually reflects how to "mine" datasets from databases (although the title is a little bit misleading). This ticket should be merged with https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-wrangler-central/140

**Comment by lauraclarke** [comment]
What details in this ticket are needed for 140?

It would be good to kill duplicate tickets so I don't have to ask this question again in a week

**Comment by ESapenaVentura** [comment]
The SOP proposal I already worked on is the only needed document as it summarises some of the questions in there

I will update that ticket!
