### ISSUE TITLE
Data Portal inconsistency on project title

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#1261]
## Description of the task:

Update the project title to match the publication on the project [A single-cell reference map of transcriptional states for human blood and tissue T cell activation ](https://explore.data.humancellatlas.org/projects/4a95101c-9ffc-4f30-a809-f04518a23803). Note this is a Lung v1.0 atlas source dataset. 

### Inconsistency/ incompleteness:
 [A single-cell reference map of transcriptional states for human blood and tissue T cell activation ](https://explore.data.humancellatlas.org/projects/4a95101c-9ffc-4f30-a809-f04518a23803) links to the differently named journal article [Single-cell transcriptomics of human T cells reveals tissue and activation signatures in health and disease](https://www.nature.com/articles/s41467-019-12464-3). 

Note that the associated CELLxGENE collection [Single-cell transcriptomics of human T cells reveals tissue and activation signatures in health and disease](https://cellxgene.cziscience.com/collections/24d42e5e-ce6d-45ff-a66b-a3b3b715deaf) uses exactly the journal title.

### Field:
project title

### Project uuids:
4a95101c-9ffc-4f30-a809-f04518a23803

### Expected behavior:
The project title is updated to "Single-cell transcriptomics of human T cells reveals tissue and activation signatures in health and disease" matching the behavior.

A SOP is put in place if it does not already exist to:

1. Match the publication title exactly for the project title.
2. Update the project title when the publication title changes, for example, when a preprint is published in a journal article.

Thanks!

## Acceptance criteria for the task:

- [x] Wrangler assigned
- [x] Investigate solution
- [x] Update project(s)
- [x] Export project(s)
- [ ] Verify fix

**Comment by arschat** [comment]
Updated project title through ingest-api ([project](https://api.ingest.archive.data.humancellatlas.org/projects/5d76adf5aa252400084a0d39)). Exported & import form sent. Will wait for next release to validate.
