### ISSUE TITLE
Update HCA docs to showcase responsibility of data owners

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1263]
**Description of the task:**

After legal discussions about MA, we discovered that if we get written consent from contributor (email) that they want (have consent) to publish potentially person-identifiable metadata, we can proceed with publishing.
This is a little bit different from what we thought previously (that we are not allowed to publish any data from living donors if it was not published before), and it is not reflected in the docs that we hold.

We have identified places where such changes might be good:
1 - https://data.humancellatlas.org/contribute/contributing-data-suitability
2 - https://contribute.data.humancellatlas.org/guide
3 - https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Triage/dataset_suitability_SOP.html

We discussed that docs 1,2 might need to be identical, and doc 3 is lower priority.

**Acceptance criteria for the task:**

- [ ] update docs for https://data.humancellatlas.org/contribute/contributing-data-suitability
- [ ] update docs for https://contribute.data.humancellatlas.org/guide
- [ ] update docs for https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Triage/dataset_suitability_SOP.html

**Comment by arschat** [comment]
## Updates needed in Data portal - [Data Suitability](https://data.humancellatlas.org/contribute/contributing-data-suitability)
- Remove `Data Processing Pipeline Support` from diagram & text
- Add Managed access option in the `Consent` Criteria, current text:
    > The current HCA data policy requires fully open access datasets. Any managed access data cannot be accepted at this time.

## Updates needed in Data portal - [Data Processing and Results](https://data.humancellatlas.org/contribute/contributing-data-processing-results)
- Remove mention of archiving on contributor's behalf

There is no mention of living donors here, therefore, no rephrasing to showcase responsibility of data owner.

**Comment by arschat** [comment]
## Update in [Contributor Guide](https://contribute.data.humancellatlas.org/guide) - [MD](https://github.com/ebi-ait/ingest-ui/blob/dev/src/assets/guide-markdown/data-requirements.md)
- Refactor `Data Coordination Platform` to `Data Platform`
- Update Open and Controlled access field
    > ## Open and Controlled access
    > Depending on the data access documents supporting the study and the respective data, datasets eligible for the Human Cell Atlas would either be
    > 
    > #### Open access
    > - where the raw data is available for open access by the scientific community and can be made publicly, e.g. in a public archive)
    > #### Controlled access
    > - where data with perssonally identifiable information. E.g raw sequences, is uder controlled access. This type of access usually has to be granted by a nominated DAC (Data Access Committee)
    >
    > The Human Cell Atlas Data Coordination Platform accepts datasets featuring both data access types, with an important note on the data and metadata files required for each type:
    > ### Open access datasets - accepted data and metadata:
    > - Raw sequencing files (fastq, bam)
    > - Donor and sample metadata
    > - Analysis files (raw/normalised matrices; cell type annotations; spatial embeddings)
    > ### Controlled access datasets - accepted data and metadata:
    > - Sample metadata (no donor-identifiable metadata)
    > - Analysis files (raw/normalised matrices; cell type annotations; spatial embeddings)

- Update [Contribution checklist](https://contribute.data.humancellatlas.org/guide/data-requirements#contributionchecklist)
    > ### Contribution checklist
    > To contribute data to the Human Cell Atlas Data Coordination Platform, follow this checklist:
    > 
    > 1. Make sure your dataset conforms to the suitability criteria above.
    > 1. Get informed about the data access type for your dataset (Open access, Controlled access, or a mix of both). E.g. Data from living donors is always Controlled access.
    > 1. Prepare the data files and metadata for your dataset, based on the requirements for your data access type.
    > 1. Fill in the HCA dataset questionnaire to inform us of dataset details.
    > 1. Contact HCA Data Coordination Platform data wrangling team to get you started.

**Comment by arschat** [comment]
## Update [Data suitability in Wrangler's SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Triage/dataset_suitability_SOP.html) - [MD](https://github.com/ebi-ait/hca-ebi-wrangler-central/tree/master/docs/SOPs/Triage/dataset_suitability_SOP.md)
- Update `Assess data availability`

This SOP is lower priority since it's target readers are wranglers who are already familiar with current availability.

**Comment by idazucchi** [comment]
@idazucchi check our gdpr doc and our communication doc -

**Comment by idazucchi** [comment]
### [GDPR_Guidelines](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Triage/GDPR_Guidelines.html) - [md](https://github.com/ebi-ait/hca-ebi-wrangler-central/tree/master/docs/SOPs/Triage/GDPR_Guidelines.md)
We need to update the diagram :
- add managed access option for HCA - not strictly related to this ticket
- add option to release additional metadata for living donors where the authors provide written consent for it

> Wranglers are only allowed to take the information that the authors have made already of public domain. **if the authors provide more metadata that what's already publicly available and also provide written consent for its public release then the additional metadata can be wrangled as open access**


### Contributor communication SOP 
no edit needed for now but we will need to update it after the managed access pilot is done

**Comment by arschat** [comment]
PR for Contributor Guide ebi-ait/ingest-ui#196
PR for Data suitability & GDPR guidelines in Wrangler's SOP #1273
For Data portal update, we need to investigate the process for updates in the [DataBiosphere/data-portal](https://github.com/DataBiosphere/data-portal/tree/main) repo.

**Comment by arschat** [comment]
In order to do a PR in the [DataBiosphere/data-portal](https://github.com/DataBiosphere/data-portal/tree/main), we would need to create ticket that describes changes needed, make PRs and ask Dave's review. The changes proposed are:
PR 1: Removing Pipeline support from docs
- [Data suitability](https://data.humancellatlas.org/contribute/contributing-data-suitability): Remove `Data Processing Pipeline Support` from diagram & text 
- [Data processing and Results](https://data.humancellatlas.org/contribute/contributing-data-processing-results): Remove the whole `Data Processing and Results` page
PR 2: Add processed files option
- [Data Submission Process](https://data.humancellatlas.org/contribute/contributing-expect-prepare): Add `Processed data files` after `Unprocessed data files` option
PR 3: Add Managed Access option
- [Data suitability](https://data.humancellatlas.org/contribute/contributing-data-suitability): Add managed access consent for the `Criteria - Consent` field in diagram & text

**Comment by arschat** [comment]
HCA exec office will review [data.humancellatlas.org](data.humancellatlas.org) (HCA-OPS point -> needs a thorough review)

**Comment by arschat** [comment]
Asking execs if there is a published DCA pdf that will be updated, so we could link to that in [Contributor Guide](https://contribute.data.humancellatlas.org/guide)

**Comment by arschat** [comment]
Until DCA is finalised, there won't be a linkable published DCA pdf. We can share wrangler's email if people want to ask about DCA.

**Comment by arschat** [comment]
#1273 is merged but there are issues with the mermaid diagram in github pages (previously a png image).

**Comment by arschat** [comment]
The commit a3d8214 fixed the issue above.
