### ISSUE TITLE
Review archiving SOP

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#127]
**Description of the task:**
Related to #124 , I have identified and fixed a gap that we have in the documentation (How to archive).

This ticket will serve for @rays22 to review the documentation, ensuring that there are no gaps and that the steps are clear and can be followed without a deep knowledge of how to run the archiver. I have also looped @aaclan-ebi in this task to review that the documentation doesn't have any technical issues

Document here: https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/archiving_SOP.html

**Acceptance criteria for the task:**
- [x] @rays22 Review the document and post any issues here
- [x] @aaclan-ebi Review the document and post any issues here
- [x] @ESapenaVentura Review the comments and apply the suggestions

**Comment by rays22** [comment]
The SOP looks good to me. I have just two questions:
* Does this SOP apply only to 10xV2 and 10xV3 datasets?
* What AAP token to use? Is it a personal one or is there a specific one to use with the Ingest Archiver?

**Comment by ESapenaVentura** [comment]
Hi @rays22 apologies for the delay

> Does this SOP apply only to 10xV2 and 10xV3 datasets?
- No, it does apply to any technology. The current problem we might face is that DSP doesn't support more than 1 file per run, so technologies like SS2 are not currently supported until we figure out how to send more than 1 file per run/convert the R1/R2 from SS2 to bam.

Are you asking this because in the upload_file_plan structure there's only specified the 10Xv2 and v3 schemas?

>What AAP token to use? Is it a personal one or is there a specific one to use with the Ingest Archiver?

Great catch, I forgot to add a section for this! Ideally we will use the ingest token, so we need to contact a dev when we need it.

**Comment by ESapenaVentura** [comment]
We've gone through it and, at a first glance, it looks fine. 

We have agreed that is a hard SOP to evaluate without someone actually going through it so once another wrangler archives following the SOP they should update it if they find difficulties.

@lauraclarke I think this ticket is ready to be closed
