### ISSUE TITLE
Data Portal tracker - Data Repository tasks

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1270]
The [tracker](https://tracker.data.humancellatlas.org/) in the Data Portal, has lists of datasets for each bionetwork. Progress of ingesting for each of the three platforms (CAP, CxG, Data Repo) is recorded here. Two extra tasks for Data Repo is also included:
* Add primary data.
* Ingest source study.
* Update project title to match publication title.

We have created [here](https://docs.google.com/spreadsheets/d/1Zl4lQlkxjouD4ybu_7UtRwtzndmooWS9AZRjsmmGaIc/edit?gid=0#gid=0) a copy of the tracker to compare with our lists.

This is a breakdown of the unfinished tasks assigned to the Data Repo in the tracker
tasks:
 - 50 : add primary data -> means missing fastqs?
 - 34 : update project title
 - 211: ingest source dataset —> projects in the tracker that couldn't be mapped to projects in the dcp, based on doi & title

projects in the tracker as todo:
- 98 from wave 3 - organoid and adipose - we never had lists for them so it makes sense
- 113 from wave 1 & 2 - further divided in:
  - 8 published/submitted projects
  - 14 stalled
  - 19 + 14 eligible - the 14 are not ingest yet
  - 2 not eligible
  - 52 unpublished —> compare with numbers from our tracking sheet

1 test project was removed from tracker (`Helmsley Gut Cell Atlas - Dupe - Delete Me`) so all stats have been lowered by 1

**Comment by arschat** [comment]
Tasks:
- 33 wave 1 & 2 datasets eligible for wrangling
    <details><summary>datasets</summary>
        
    		| Atlas        | DOI | UUID |
	|--------------|-----|------|
	| Gut v1.0     | [10.1093/ibd/izac201](https://doi.org/10.1093/ibd/izac201)| #N/A |
	| Kidney v1.0  | [10.1038/s41467-022-34255-z](https://doi.org/10.1038/s41467-022-34255-z)  | #N/A|
	| Gut v1.0     | [10.1101/2023.09.06.23295056](https://doi.org/10.1101/2023.09.06.23295056) | #N/A|
	| Lung v1.0    | [10.1101/2023.07.30.551145](https://doi.org/10.1101/2023.07.30.551145)   | #N/A|
	| Gut v1.0     | [10.1371/journal.pbio.3002124](https://doi.org/10.1371/journal.pbio.3002124) | #N/A|
	| Gut v1.0     | [10.1016/j.jcmgh.2020.12.014](https://doi.org/10.1016/j.jcmgh.2020.12.014) | #N/A|
	| Gut v1.0     | [10.7554/elife.91792.1](https://doi.org/10.7554/elife.91792.1)         | #N/A|
	| Gut v1.0     | [10.1126/science.abd1449](https://doi.org/10.1126/science.abd1449)      | #N/A|
	| Gut v1.0     | [10.1038/s41586-023-05915-x](https://doi.org/10.1038/s41586-023-05915-x)  | #N/A|
	| Gut v1.0     | [10.1053/j.gastro.2020.12.030](https://doi.org/10.1053/j.gastro.2020.12.030) | #N/A|
	| Liver v1.0   | [10.1016/j.jhep.2024.02.017](https://doi.org/10.1016/j.jhep.2024.02.017)  | #N/A|
	| Liver v1.0   | [10.1101/2024.02.02.578633](https://doi.org/10.1101/2024.02.02.578633)  | #N/A|
	| Heart v1.0   | [10.1101/2022.10.17.512579](https://doi.org/10.1101/2022.10.17.512579)  | #N/A|
	| Liver v1.0   | [10.1016/j.jhep.2023.12.023](https://doi.org/10.1016/j.jhep.2023.12.023)  | #N/A|
	| Heart v1.0   | [10.1161/circulationaha.121.055690](https://doi.org/10.1161/circulationaha.121.055690) | [01cade75-483a-46c6-a07d-7c1b19b6791b](https://contribute.data.humancellatlas.org/projects/detail?uuid=01cade75-483a-46c6-a07d-7c1b19b6791b) |
	| Lung v2.0    | [10.1038/s41467-021-26770-2](https://doi.org/10.1038/s41467-021-26770-2)  | [04bb1408-8c11-404e-b84a-e26c9284424e](https://contribute.data.humancellatlas.org/projects/detail?uuid=04bb1408-8c11-404e-b84a-e26c9284424e) |
	| Lung v2.0    | [10.1038/s41467-020-16164-1](https://doi.org/10.1038/s41467-020-16164-1)  | [087efc3c-2601-4de6-bbe9-0114593050d1](https://contribute.data.humancellatlas.org/projects/detail?uuid=087efc3c-2601-4de6-bbe9-0114593050d1) |
	| Heart v1.0   | [10.1161/circulationaha.120.051391](https://doi.org/10.1161/circulationaha.120.051391) | [14255967-e584-463e-9317-d0bd8af66692](https://contribute.data.humancellatlas.org/projects/detail?uuid=14255967-e584-463e-9317-d0bd8af66692) |
	| Pancreas v1.0| [10.1038/s42255-023-00806-x](https://doi.org/10.1038/s42255-023-00806-x)  | [1e618693-aa16-4414-bb11-5c8baf9a5c4d](https://contribute.data.humancellatlas.org/projects/detail?uuid=1e618693-aa16-4414-bb11-5c8baf9a5c4d) |
	| Lung v2.0    | [10.1186/s12964-023-01322-x](https://doi.org/10.1186/s12964-023-01322-x)  | [206fb350-46dd-4afb-a91d-0862781eb063](https://contribute.data.humancellatlas.org/projects/detail?uuid=206fb350-46dd-4afb-a91d-0862781eb063) |
	| Lung v2.0    | [10.3389/fimmu.2023.1162087](https://doi.org/10.3389/fimmu.2023.1162087)  | [327bf861-afbb-474a-b3b9-2f657f09e998](https://contribute.data.humancellatlas.org/projects/detail?uuid=327bf861-afbb-474a-b3b9-2f657f09e998) |
	| Gut v1.0     | [10.1016/j.cell.2020.06.001](https://doi.org/10.1016/j.cell.2020.06.001)  | [3373e59c-525f-4a83-8c9c-d8b280454697](https://contribute.data.humancellatlas.org/projects/detail?uuid=3373e59c-525f-4a83-8c9c-d8b280454697) |
	| Lung v2.0    | [10.1126/sciadv.aaw385](https://doi.org/10.1126/sciadv.aaw385)         | [3627473e-b6d6-45c9-87b5-b9f12ce57a10](https://contribute.data.humancellatlas.org/projects/detail?uuid=3627473e-b6d6-45c9-87b5-b9f12ce57a10) |
	| Lung v2.0    | [10.1038/s41586-022-04552-0](https://doi.org/10.1038/s41586-022-04552-0)  | [5f1a1aee-6c48-4dd4-a2c4-eb4ca6aadf74](https://contribute.data.humancellatlas.org/projects/detail?uuid=5f1a1aee-6c48-4dd4-a2c4-eb4ca6aadf74) |
	| Lung v2.0    | [10.1016/j.xcrm.2023.101078](https://doi.org/10.1016/j.xcrm.2023.101078)  | [87aefc20-bb6b-4d75-b474-9ea62ce07d6e](https://contribute.data.humancellatlas.org/projects/detail?uuid=87aefc20-bb6b-4d75-b474-9ea62ce07d6e) |
	| Lung v2.0    | [10.1164/rccm.202207-1384oc](https://doi.org/10.1164/rccm.202207-1384oc)  | [8c4e43fb-f7f3-4446-8367-a3fe9e0b8fd7](https://contribute.data.humancellatlas.org/projects/detail?uuid=8c4e43fb-f7f3-4446-8367-a3fe9e0b8fd7) |
	| Immune v1.0  | [10.1126/scitranslmed.abh2624](https://doi.org/10.1126/scitranslmed.abh2624) | [90588227-d8c1-47ee-a397-0d0b1d79aea9](https://contribute.data.humancellatlas.org/projects/detail?uuid=90588227-d8c1-47ee-a397-0d0b1d79aea9) |
	| Heart v1.0   | [10.1101/2021.06.23.449672](https://doi.org/10.1101/2021.06.23.449672)  | [9ff75ece-ce81-483a-bb1f-85e727f3805b](https://contribute.data.humancellatlas.org/projects/detail?uuid=9ff75ece-ce81-483a-bb1f-85e727f3805b) |
	| Lung v2.0    | [10.1172/jci.insight.125895](https://doi.org/10.1172/jci.insight.125895) | [c619cd54-a7cb-4c47-92fc-4ede5d61fd17](https://contribute.data.humancellatlas.org/projects/detail?uuid=c619cd54-a7cb-4c47-92fc-4ede5d61fd17) |
	| Lung v2.0    | [10.1038/s41467-023-40173-5](https://doi.org/10.1038/s41467-023-40173-5)  | [cbefbecc-1b0f-43d1-ac81-b6319a1881d9](https://contribute.data.humancellatlas.org/projects/detail?uuid=cbefbecc-1b0f-43d1-ac81-b6319a1881d9) |
	| Lung v2.0    | [10.1016/j.ccell.2021.09.008](https://doi.org/10.1016/j.ccell.2021.09.008)  | [da922da8-eabe-4f99-8b58-425fd2af83df](https://contribute.data.humancellatlas.org/projects/detail?uuid=da922da8-eabe-4f99-8b58-425fd2af83df) |
	| Lung v2.0    | [10.1164/rccm.202305-0924oc](https://doi.org/10.1164/rccm.202305-0924oc)  | [e870ab56-3537-4b6d-a66f-534fbf8cc57f](https://contribute.data.humancellatlas.org/projects/detail?uuid=e870ab56-3537-4b6d-a66f-534fbf8cc57f) |
    
    <details>
- 3 datasets have now primary data (fastq files)
    - **[tabulaSapiens](https://contribute.data.humancellatlas.org/projects/detail?uuid=10201832-7c73-4033-9b65-3ef13d81656a)**:`10201832-7c73-4033-9b65-3ef13d81656a` data in https://registry.opendata.aws/tabula-sapiens/
    - **[HtanPreCancerAltas](https://contribute.data.humancellatlas.org/projects/detail?uuid=50154d1e-2308-44bf-9608-10c7afaa560b)**:`50154d1e-2308-44bf-9608-10c7afaa560b` data in https://data.humantumoratlas.org/explore?selectedFilters=%5B%7B%22group%22%3A%22AtlasName%22%2C%22value%22%3A%22HTAN+Vanderbilt%22%7D%5D
    - **[lungPopulationsIPF](https://contribute.data.humancellatlas.org/projects/detail?uuid=c16a754f-5da3-46ed-8c1e-6426af2ef625)**:`c16a754f-5da3-46ed-8c1e-6426af2ef625` data in https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA563828

**Comment by arschat** [comment]
script for updating project title and project_schema version based on [project_title.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0Z5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b66a60ede655f3c2f9b892eccda43f3734e4fce/project_title.txt):
```python
from hca_ingest.api.ingestapi import IngestApi
import pandas as pd

# token = '<TOKEN>'

api = IngestApi(url="https://api.ingest.archive.data.humancellatlas.org/")
headers_json = {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token}
api.set_token(f"bearer {token}")

df = pd.read_csv('~/Desktop/hca_atlas_tracker/project_title.txt', delimiter = '\t')
df.set_index('doi', inplace=True)

updatable_schemas = [
						'https://schema.humancellatlas.org/type/project/18.0.0/project',
						'https://schema.humancellatlas.org/type/project/17.1.1/project',
						'https://schema.humancellatlas.org/type/project/17.1.0/project',
						'https://schema.humancellatlas.org/type/project/17.0.0/project',
						'https://schema.humancellatlas.org/type/project/14.1.0/project'
					]

for doi in df.index:
	changed = False
	query = [
				{
				"field": "content.publications.doi",
				"operator": "IS",
				"value": doi
				}
			]
	projects = api.post('https://api.ingest.archive.data.humancellatlas.org/projects/query?operator=OR', json=query).json()
	if '_embedded' not in projects:
		print(f"No project with doi {doi}. Skipping")
		continue
	if len(projects['_embedded']['projects']) > 1:
		print(f"Multiple projects with doi {doi}. Skipping.")
		continue
	project = projects['_embedded']['projects'][0]
	# change title
	project_title = project['content']['project_core']['project_title']
	for pub in project['content']['publications']:
		pub_title = pub['title'].rstrip('.')
		if pub_title == df.loc[doi, 'expected'] and project_title == df.loc[doi, 'actual']:
			project['content']['project_core']['project_title'] = df.loc[doi, 'expected']
			changed = True
			print(f'{doi}\tTitle updated')
			continue
		elif pub_title != df.loc[doi, 'expected']:
			print(f"{doi}\tPublication title not the expected!")#\nActual:\t{pub_title}\nExpected:\t{df.loc[doi, 'expected']}")
		elif pub_title != df.loc[doi, 'expected']:
			print(f"{doi}\tProject title not the provided in tracker!")#\nActual:\t{project_title}\nTracker:\t{df.loc[doi, 'actual']}")
		else:
			print(f'{doi}\tDid not changed title')
	# change project schema version
	if project['content']['describedBy'] in updatable_schemas:
		project['content']['describedBy'] = 'https://schema.humancellatlas.org/type/project/19.0.0/project'
		project['content']['data_use_restriction'] = 'NRES'
		print(f'{doi}\tProject version updated')
	else:
		print(f'{doi}\tNo project version update {project['content']['describedBy']}')
	# patch changes if changed
	if not changed and 'data_use_restriction' not in project['content']:
		continue
	elif changed and 'data_use_restriction' in project['content']:
		note = ' June24: fixed title and bumped project version & NRES'
	elif not changed and 'data_use_restriction' in project['content']:
		note = ' June24: bumped project version & NRES'
	elif changed and 'data_use_restriction' not in project['content']:
		note = ' June24: fixed title'
	project['wranglingNotes'] = project['wranglingNotes'] + note if project['wranglingNotes'] else note
	# print(project['content']['project_core']['project_title'], project['content']['describedBy'])
	# response = api.patch(project['_links']['self']['href'], json = project['content'], headers=headers_json)
	# if not response.ok:
	# 	print(f'Problem in patching {doi}')
```

**Comment by arschat** [comment]
I completed the change of titles and the data_use_restriction in the following projects
```
065e6c13-ad6b-46a3-8075-c3137eb03068
cddab57b-6868-4be4-806f-395ed9dd635a
50151324-f3ed-4358-98af-ec352a940a61
425c2759-db66-4c93-a358-a562c069b1f1
1c6a960d-52ac-44ea-b728-a59c7ab9dc8e
ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad
4bec484d-ca7a-47b4-8d48-8830e06ad6db
d3446f0c-30f3-4a12-b7c3-6af877c7bb2d
16ed4ad8-7319-46b2-8859-6fe1c1d73a82
4d6f6c96-2a83-43d8-8fe1-0f53bffd4674
4a95101c-9ffc-4f30-a809-f04518a23803
1538d572-bcb7-426b-8d2c-84f3a7f87bb0
40272c3b-4697-4bd4-ba3f-82fa96b9bf71
b963bd4b-4bc1-4404-8425-69d74bc636b8
2ef3655a-973d-4d69-9b41-21fa4041eed7
51f02950-ee25-4f4b-8d07-59aa99bb3498
135f7f5c-4a85-4bcf-9f7c-4f035ff1e428
577c946d-6de5-4b55-a854-cd3fde40bff2
2d4d89f2-ebeb-467c-ae60-a3efc5e8d4ba
c6ad8f9b-d26a-4811-b2ba-93d487978446
c1a9a93d-d9de-4e65-9619-a9cec1052eaa
c16a754f-5da3-46ed-8c1e-6426af2ef625
10201832-7c73-4033-9b65-3ef13d81656a
dc0b65b0-7713-46f0-a339-0b03ea786046
c5ca43aa-3b2b-4216-8eb3-f57adcbc99a1
ad04c8e7-9b7d-4cce-b8e9-01e31da10b94
c4077b3c-5c98-4d26-a614-246d12c2e5d7
027c51c6-0719-469f-a7f5-640fe57cbece
99101928-d9b1-4aaf-b759-e97958ac7403
```
We need to figure out which submission we want to export for the following:
```005d611a-14d5-4fbf-846e-571a1f874f70``` two submissions
The following should NOT be exported.
```b08269ec-7a56-4e9d-a2f5-40498976fbd4``` lattice - no submission
```6164d96c-fd0a-450c-aa41-5966ad35b298``` lattice - no submission
```3d49e5e5-976f-44cb-b6b9-079016c31c56``` lattice - no access
The following was wrongfully wrangled, since the pre-print was already in [DCP](https://explore.data.humancellatlas.org/projects/31887183-a72c-4308-9eac-c6140313f39c).
```c14f788a-a438-459d-b470-ccb65e9e259e``` stalled - not exported yet (heart dataset)

**Comment by arschat** [comment]
Created ingest project for all the projects that did not have (except gut projects which UCSC is working on)

**Comment by arschat** [comment]
Out of the 3 datasets that primary/raw/sequence data is now available,
- ~~**[tabulaSapiens](https://contribute.data.humancellatlas.org/projects/detail?uuid=10201832-7c73-4033-9b65-3ef13d81656a)**~~ [data](https://registry.opendata.aws/tabula-sapiens/) requires data transfer agreement
- ~~**[HtanPreCancerAltas](https://contribute.data.humancellatlas.org/projects/detail?uuid=50154d1e-2308-44bf-9608-10c7afaa560b)**~~ [data](https://data.humantumoratlas.org/explore?selectedFilters=%5B%7B%22group%22%3A%22AtlasName%22%2C%22value%22%3A%22HTAN+Vanderbilt%22%7D%5D) needs access from dbGAP to download
- **[lungPopulationsIPF](https://contribute.data.humancellatlas.org/projects/detail?uuid=c16a754f-5da3-46ed-8c1e-6426af2ef625)** [raw files](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA563828) published later, zh issue: #750

**Comment by arschat** [comment]
Dave Rogers shared with us an update on 8 published/submitted projects

| n | DOI | uuid |
| - | ---- | ---- |
| 1 | [10.1038/s41591-018-0096-5](https://www.doi.org/10.1038/s41591-018-0096-5) | [453d7ee2-319f-496c-9862-99d397870b63](https://contribute.data.humancellatlas.org/projects/detail?uuid=453d7ee2-319f-496c-9862-99d397870b63) |
| 2 | [10.1038/s41591-019-0733-7](https://www.doi.org/10.1038/s41591-019-0733-7) | [9d97f01f-9313-416e-9b07-560f048b2350](https://contribute.data.humancellatlas.org/projects/detail?uuid=9d97f01f-9313-416e-9b07-560f048b2350) |
| 3 | [10.1038/s41467-021-24607-6](https://www.doi.org/10.1038/s41467-021-24607-6) | [7f351a4c-d24c-4fcd-9040-f79071b097d0](https://contribute.data.humancellatlas.org/projects/detail?uuid=7f351a4c-d24c-4fcd-9040-f79071b097d0) |
| 4 | [10.1038/s42255-022-00531-x](https://www.doi.org/10.1038/s42255-022-00531-x) | [daef3fda-2620-45ae-a3f7-1613814a35bf](https://contribute.data.humancellatlas.org/projects/detail?uuid=daef3fda-2620-45ae-a3f7-1613814a35bf) |
| 5 | [10.1038/s43018-020-00121-4](https://www.doi.org/10.1038/s43018-020-00121-4) | [bcdf233f-9246-4c0c-9843-0514120b7e3a](https://contribute.data.humancellatlas.org/projects/detail?uuid=bcdf233f-9246-4c0c-9843-0514120b7e3a) |
| 6 | [10.1126/science.abg0928](https://www.doi.org/10.1126/science.abg0928) | [c211fd49-d980-4ba1-8c6a-c24254a3cb52](https://contribute.data.humancellatlas.org/projects/detail?uuid=c211fd49-d980-4ba1-8c6a-c24254a3cb52) |
| 7 | [10.1038/s41586-021-04044-7](https://www.doi.org/10.1038/s41586-021-04044-7) | [031980e6-9f2b-433a-8f6e-081bd9aad0a3](https://contribute.data.humancellatlas.org/projects/detail?uuid=031980e6-9f2b-433a-8f6e-081bd9aad0a3) |
| 8 | [10.1177/00220345221147908](https://www.doi.org/10.1177/00220345221147908) | [ccc3b786-1da0-427f-a45f-76306d6143b6](https://contribute.data.humancellatlas.org/projects/detail?uuid=ccc3b786-1da0-427f-a45f-76306d6143b6) |


Projects 1, 4, 5, 8 have been successfully updated in the tracker.
Project 2, 7 are not present in DCP
Project 3 tracker links to publication [10.1038/s41467-021-24607-6](doi.org/10.1038/s41467-021-24607-6) but DCP has wrangled [10.1002/art.41813](https://doi.org/10.1002/art.41813). Both point to the same GEO accession [GSE138669](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138669). Need to investigate if the exact same specimens are used for both publications.
Project 6 dcp links to pre-print [10.1101/2020.12.21.423830](https://doi.org/10.1101/2020.12.21.423830), we need to update the project to use the published paper's DOI [10.1126/science.abg0928](https://doi.org/10.1126/science.abg0928)

**Comment by arschat** [comment]
List of projects that need project metadata re-export (ideally for R40 on monday 24/06)
* 1 published/submitted project that was not listed in tracker
```
c211fd49-d980-4ba1-8c6a-c24254a3cb52
```
* 30 update project title
```
065e6c13-ad6b-46a3-8075-c3137eb03068
cddab57b-6868-4be4-806f-395ed9dd635a
50151324-f3ed-4358-98af-ec352a940a61
425c2759-db66-4c93-a358-a562c069b1f1
1c6a960d-52ac-44ea-b728-a59c7ab9dc8e
ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad
4bec484d-ca7a-47b4-8d48-8830e06ad6db
d3446f0c-30f3-4a12-b7c3-6af877c7bb2d
16ed4ad8-7319-46b2-8859-6fe1c1d73a82
4d6f6c96-2a83-43d8-8fe1-0f53bffd4674
4a95101c-9ffc-4f30-a809-f04518a23803
1538d572-bcb7-426b-8d2c-84f3a7f87bb0
40272c3b-4697-4bd4-ba3f-82fa96b9bf71
b963bd4b-4bc1-4404-8425-69d74bc636b8
2ef3655a-973d-4d69-9b41-21fa4041eed7
51f02950-ee25-4f4b-8d07-59aa99bb3498
135f7f5c-4a85-4bcf-9f7c-4f035ff1e428
577c946d-6de5-4b55-a854-cd3fde40bff2
2d4d89f2-ebeb-467c-ae60-a3efc5e8d4ba
c6ad8f9b-d26a-4811-b2ba-93d487978446
c1a9a93d-d9de-4e65-9619-a9cec1052eaa
c16a754f-5da3-46ed-8c1e-6426af2ef625
10201832-7c73-4033-9b65-3ef13d81656a
dc0b65b0-7713-46f0-a339-0b03ea786046
c5ca43aa-3b2b-4216-8eb3-f57adcbc99a1
ad04c8e7-9b7d-4cce-b8e9-01e31da10b94
c4077b3c-5c98-4d26-a614-246d12c2e5d7
027c51c6-0719-469f-a7f5-640fe57cbece
99101928-d9b1-4aaf-b759-e97958ac7403
```
`31887183-a72c-4308-9eac-c6140313f39c` is a published pre-print in DCP, [re-wrangled](https://contribute.data.humancellatlas.org/projects/detail?uuid=c14f788a-a438-459d-b470-ccb65e9e259e&tab=project) peer-reviewed but not published. Identical datasets, now added peer-reviewed publication & added data_use_restriction in the already published one, need to re-export project only
`005d611a-14d5-4fbf-846e-571a1f874f70` has two submissions, the might be complementary, if we can do ONLY project metadata export it would be great

**Comment by arschat** [comment]
about 2 projects that are listed as published in ingest but do not exist in the platform
* project [2](https://contribute.data.humancellatlas.org/projects/detail?uuid=9d97f01f-9313-416e-9b07-560f048b2350):
    It was soft deleted from DCP, cause we wanted to update the DCP-generated-matrices [slack thread](https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1643221976027100). There is no record of re-import in the [DCP import requests spreadsheet](https://docs.google.com/spreadsheets/d/1xApi-qay1H9ef2JQAmPNXH63Xy-0cNYBN4wBaq-YC3U/edit#gid=398656126).
* project [7](https://contribute.data.humancellatlas.org/projects/detail?uuid=031980e6-9f2b-433a-8f6e-081bd9aad0a3):
    Submission is marked as [complete](https://contribute.data.humancellatlas.org/submissions/detail?uuid=f30028a0-9768-4356-8396-8ea6be17b108&project=031980e6-9f2b-433a-8f6e-081bd9aad0a3) in ingest, but no project uuid is not listed in the import request spreadsheet, nor in the [import staging area](gs://broad-dsp-monster-hca-prod-ebi-storage/prod/031980e6-9f2b-433a-8f6e-081bd9aad0a3).

**Comment by idazucchi** [comment]
I've exported the project metadata for [these projects](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/gh/ebi-ait/hca-ebi-wrangler-central/1270#issuecomment-2182524608). Since there's quite a few I've asked Travis to add them to the R40 manifest directly rather than fill out the import form 
I'm waiting for the import process to check that everything went fine

**Comment by arschat** [comment]
[lungPopulationsIPF](https://contribute.data.humancellatlas.org/projects/detail?uuid=c16a754f-5da3-46ed-8c1e-6426af2ef625)`c16a754f-5da3-46ed-8c1e-6426af2ef625`:
* has been exported with the additional fastq files

**Comment by arschat** [comment]
These projects (that their title changed) have submissions that were reverted to `graph valid` in order to be exported. However, since export was done manually, the state did not change, and we need to revert back to `exported`.
> `065e6c13-ad6b-46a3-8075-c3137eb03068`
`cddab57b-6868-4be4-806f-395ed9dd635a`
`50151324-f3ed-4358-98af-ec352a940a61`
`425c2759-db66-4c93-a358-a562c069b1f1`
`1c6a960d-52ac-44ea-b728-a59c7ab9dc8e`
`ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad`
`4bec484d-ca7a-47b4-8d48-8830e06ad6db`
`d3446f0c-30f3-4a12-b7c3-6af877c7bb2d`
`16ed4ad8-7319-46b2-8859-6fe1c1d73a82`
`4d6f6c96-2a83-43d8-8fe1-0f53bffd4674`
`4a95101c-9ffc-4f30-a809-f04518a23803`
`1538d572-bcb7-426b-8d2c-84f3a7f87bb0`
`40272c3b-4697-4bd4-ba3f-82fa96b9bf71`
`b963bd4b-4bc1-4404-8425-69d74bc636b8`
`2ef3655a-973d-4d69-9b41-21fa4041eed7`
`51f02950-ee25-4f4b-8d07-59aa99bb3498`
`135f7f5c-4a85-4bcf-9f7c-4f035ff1e428`
`577c946d-6de5-4b55-a854-cd3fde40bff2`
`2d4d89f2-ebeb-467c-ae60-a3efc5e8d4ba`
`c6ad8f9b-d26a-4811-b2ba-93d487978446`
`c1a9a93d-d9de-4e65-9619-a9cec1052eaa`
`c16a754f-5da3-46ed-8c1e-6426af2ef625`
`10201832-7c73-4033-9b65-3ef13d81656a`
`dc0b65b0-7713-46f0-a339-0b03ea786046`
`c5ca43aa-3b2b-4216-8eb3-f57adcbc99a1`
`ad04c8e7-9b7d-4cce-b8e9-01e31da10b94`
`c4077b3c-5c98-4d26-a614-246d12c2e5d7`
`027c51c6-0719-469f-a7f5-640fe57cbece`
`99101928-d9b1-4aaf-b759-e97958ac7403`

**Comment by arschat** [comment]
State reverted back to exported for projects above.

- all projects titles have been updated (small task left in #1284) in R40
- all available fastq files will be upload in R41
- all wave 1&2 projects have been created in ingest (UCSC team took over gut)

Therefore, this ticket can now close.

**Comment by arschat** [comment]
Noting here, that the Tabula Sapiens dataset, does not have primary data. DR asked us if we can have the fastq files since we now support MA. Data is currently available in aws open data [here](https://tabula-sapiens.sf.czbiohub.org/whereisthedata) but in order to get access to them you have to sign a Data Use Agreement. 

We have to get in contact with the Tabula Sapiens team or someone from CZI to check if we can have these data in our portal OA or MA.

**Comment by idazucchi** [comment]
from the TabulaSapiens [Data use agreement](https://us.services.docusign.net/webforms-ux/v1.0/forms/a6c0eb9af42c45ce9ed78a1292f56dab):
>(c) I will not publish the Data or otherwise make it publicly available. To the extent I want to
publish findings from the Research, I agree to acknowledge Donor Network West as follows:
“Research organization/authors hereby express its thanks for the cooperation of Donor Network
West and all of the organ and tissue donors and their families, for giving the gift of life and the
gift of knowledge, by their generous donation”; and
(d) I will not transfer the Data to any third party
