### ISSUE TITLE
Scan for MRC publications and start template emails

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#128]
**Description of the task:**
To understand where the MRC awardees are in the process of data generation, and if we should provide with any support, I will begin scanning for pre-prints for the 13 datasets and begin working on template emails. 

Will update later with sections for each awardee.

Holding off on sending the emails for now until we get notification for project registration availability.

**Acceptance criteria for the task:**
- [x] A scan has been made for the 13 projects to identify pre-prints
- [x] A template email has been redacted for each of the groups

**Comment by ESapenaVentura** [comment]
**Scan**
- Cell atlas of the human female reproductive system across the lifespan: No data
- How heterogeneous are oligodendroglia from normal human brain and spinal cord?: No data
- A cell atlas of the human outflow tract of the heart: No data
- The Joint Atlas: A cellular map of key anatomical structures in the human synovial joint during development and in healthy adults: No data
- Defining regional anatomical variation in cellular composition, transcriptome and epigenome in the human kidney: https://www.biorxiv.org/content/10.1101/2020.06.14.151167v1.full ?
- Definition of human colonic mesenchymal origins and of mesenchymal epithelial cross-talk in health and disease: No data
- Understanding the molecular and cellular complexity of human cornea through single cell analyses: https://www.biorxiv.org/content/10.1101/2020.07.09.195438v1
- scEye-Map: Developmental trajectories of progenitor cell populations in the human eye at single cell resolution: No data
- A protein-transcriptome atlas of haematopoiesis across the human lifespan: No data
- Decoding cell lineages in human oesophagus, stomach and duodenal development for the Human Cell Atlas and to understand disease: No data
- The thymus stromal compartment across developmental stages: Determining single cell transcription, chromatin accessibility and spatial position: No data
- Charting cellular changes in the human breast associated with embryogenesis, parity, age, menopause and germline mutations: No data
- Human Lung Cell Atlas Project: genetic regulation of foetal and healthy adult lung cell states in 3D spatial resolution: No data but found this https://www.biorxiv.org/content/10.1101/2020.05.22.111187v2 seems interesting?

**Comment by ESapenaVentura** [comment]
As an AI from a conversation with @lauraclarke , I will use this ticket as a template to search for updates to the MRC awardees and seek out to them if necessary.

Moving it to "in progress"

**Comment by ESapenaVentura** [comment]
Definition of human colonic mesenchymal origins and of mesenchymal epithelial cross-talk in health and disease: https://www.nature.com/articles/s41 I think this paper's data was partly funded by the MRC grant, at least according to this https://gtr.ukri.org/publication/overview?outcomeid=5c77be8f7d2266.86092922&projectref=MR/S036377/1

**Comment by lauraclarke** [comment]
Is this the MRC Development Cell Atlas or another MRC award, the MRC does have multiple lines of funding and the acknowledgements don't mention it https://www.nature.com/articles/s41586-019-0992-y#Ack1

**Comment by ESapenaVentura** [comment]
According to the GTR website, the grant associated to this paper is `MR/S036377/1`, which is, unless I'm wrong, the grant of the MRC Dev Cell Atlas.

I found it going here https://gtr.ukri.org/projects?ref=MR%2FS036377%2F1 and looking for publications (although there are many publications that do not relate specifically to single cell, so I don't know what to think)

**Comment by ESapenaVentura** [comment]
I have searched for the rest of the projects and didn't find anything that caught my attention (Found some mouse datasets, but no human sc datasets aside from the one we already have wrangled)

I will start the emails and attach them in a doc here

**Comment by ESapenaVentura** [comment]
Also the new batch of data from valentine's spreadsheet has brought a new dataset into attention: for the project `Definition of human colonic mesenchymal origins and of mesenchymal epithelial cross-talk in health and disease`, there is a paper https://doi.org/10.1016/j.cell.2020.12.016

I have added myself as primary wrangler and will create a ticket soon

**Comment by ESapenaVentura** [comment]
I am actually doing a further scan and found one of the projects I somehow missed https://www.nature.com/articles/s41467-020-17305-2#Ack1 for the grant Decoding cell lineages in human oesophagus, stomach and duodenal development for the Human Cell Atlas and to understand disease
