### ISSUE TITLE
GSE233476  - Chen-Human-ATACseq

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1297]
### Associated files

* Google Drive:
* ingest: [de0bb4b0-b691-46d7-83db-55670f0afc3a](https://contribute.data.humancellatlas.org/projects/detail?uuid=de0bb4b0-b691-46d7-83db-55670f0afc3a)

### Published study links

* Paper:[10.21203/rs.3.rs-3343318/v1](https://doi.org/10.21203/rs.3.rs-3343318/v1)

* Accessioned data: [GSE233476](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE233476)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
scRNA-seq data is referenced in paper but not provided in the [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE233476)

**Comment by idazucchi** [comment]
should we get in touch with the bionetwork about this project?
