### ISSUE TITLE
GSE237204 - RetinaEvolutionHumanHahn

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1298]
part of Retina Atlas v1.0

### Project short name: 
RetinaEvolutionHumanHahn
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1gvRWm05l7_LTcerdst8ffuObWqoCNnMr)
* ingest: [c3dd819d-abab-4957-b209-88f1e0900368](https://contribute.data.humancellatlas.org/projects/detail?uuid=c3dd819d-abab-4957-b209-88f1e0900368)

### Published study links

* Paper: [Evolution of neuronal cell classes and types in the vertebrate retina](https://doi.org/10.1038/s41586-023-06638-9)
* Accessioned data: [GSE237204](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE237204) - human data

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
I didn't find any donor metadata, the only metadata available is about samples [here](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-023-06638-9/MediaObjects/41586_2023_6638_MOESM4_ESM.xlsx)

About sample `Hu218OSmAll` - the sample key says it's `mac_neun-_218` but this sample is absent in extended data [Fig1](https://www.nature.com/articles/s41586-023-06638-9/figures/6) - instead there is `mac_all_218` 
I think `mac_neun-_218` is a mistake and the sample is not enriched

**Comment by arschat** [comment]
Hi Ida! There were very limited metadata available but you've done a nice job.
I only have two suggestions and one comment.

### Project 
* `abstract` you can remove the reference numbers

### Analysis protocol
* `intron_inclusion` you could fill yes here
    > To include both exonic and intronic reads in the quantification of gene expression for each sample, regardless of cellular or nuclear origin, we applied velocyto to the corresponding.bam files. This generated two separate gene expression matrices (GEMs) (genes × cells) for each sample, corresponding to ‘spliced’ and ‘unspliced’ reads.

### Analysis file
* `input biomaterials` Each of the 4 files, should have different input. If you open the count matrices the cell index includes the sample_ID. I've removed the UMI and the duplicates

<details><summary>sample_id extraction</summary>

```bash
for file in GSE237204*; do echo $file; zcat < $file | head -1 | sed 's/\,/\n/g' | sed 's/.\{18\}$//' | sort | uniq; done
```

GSE237204_Human_count_mat_1.csv.gz
> Hu032616OD_macula_NeuNPos.possorted_genome_bam_PNH7N
Hu035516OS_macula_NeuNPosS1.possorted_genome_bam_TXN7J
Hu035516OS_macula_NeuNPosS2.possorted_genome_bam_D2QGV
Hu035516OS_macula_NeuNPosS2.possorted_genome_bam_PNH7N
Hu056316OD_macula_NeuNPos.possorted_genome_bam_M7UFG
Hu056416OS_macula_NeuNPos.possorted_genome_bam_RCC8P
Hu082219_macular_All.possorted_genome_bam_M28FQ
Hu086916OD_macula_NeuNPos.possorted_genome_bam_VL2TA

GSE237204_Human_count_mat_2.csv.gz
> Hu086916OD_macula_NeuNPos.possorted_genome_bam_VL2TA
Hu088716OS_macula_NeuNPos.possorted_genome_bam_2L1A9
Hu105916OD_macula_NeuNPos.possorted_genome_bam_C9Z7N
Hu218OSPeriRetina.possorted_genome_bam_WYD8B
Hu218OSmAll.possorted_genome_bam_DGNOI
Hu218OSmRGC.possorted_genome_bam_Q49J3

GSE237204_Human_count_mat_3.csv.gz
> Hu218OSPeriRetina.possorted_genome_bam_WYD8B
Hu220235OSmAll.possorted_genome_bam_V6O4A
Hu220OSPeriRetina.possorted_genome_bam_L340L
Hu220OSmRGC.possorted_genome_bam_Z9VX3
Hu235OSPeriRetina.possorted_genome_bam_3URIL
Hu235OSmRGC.possorted_genome_bam_W3LJK
HuCMixS1.possorted_genome_bam_B7X1A

GSE237204_Human_count_mat_4.csv.gz
> HuCMixS1.possorted_genome_bam_B7X1A
HuCMixS2.possorted_genome_bam_HGXY1
HuPRet1059fc564mc.possorted_genome_bam_56BDZ
HuPRet326mc355fc.possorted_genome_bam_RJJ6M
HuPRet563mc.possorted_genome_bam_PYRF4
HuPRet887mc869fc.possorted_genome_bam_CHBYN

</details>

<details><summary>CS assignment</summary>

`GSE237204_Human_count_mat_1.csv.gz` -> `Hu032616OD_macula_NeuNPos||Hu035516OS_macula_NeuNPosS1||Hu035516OS_macula_NeuNPosS2||Hu056316OD_macula_NeuNPos||Hu056416OS_macula_NeuNPos||Hu082219_macular_All||Hu086916OD_macula_NeuNPos`

`GSE237204_Human_count_mat_2.csv.gz` -> `Hu086916OD_macula_NeuNPos||Hu088716OS_macula_NeuNPos||Hu105916OD_macula_NeuNPos||Hu218OSPeriRetina||Hu218OSmAll||Hu218OSmRGC`

`GSE237204_Human_count_mat_3.csv.gz` -> `Hu218OSPeriRetina||Hu220235OSmAll||Hu220OSPeriRetina||Hu220OSmRGC||Hu235OSPeriRetina||Hu235OSmRGC||HuCMixS1`

`GSE237204_Human_count_mat_4.csv.gz` -> `HuCMixS1||HuCMixS2||HuPRet1059fc564mc||HuPRet326mc355fc||HuPRet563mc||HuPRet887mc869fc`

</details>

**Comment by idazucchi** [comment]
fixed the issues and tried to export but the dataset is stuck on [export](https://monitoring.ingest.archive.data.humancellatlas.org/d/yK-iu984z/export-single-submission?orgId=1&var-submission_uuid=feb1c0ad-2d30-47ee-b7b1-c24de2ec2745&from=now-2d&to=now)

**Comment by idazucchi** [comment]
Enrique restarted the export and it worked - I've filled in the import form

**Comment by idazucchi** [comment]
verified in the browser
