### ISSUE TITLE
Estimate average cloud costs by meaningful scientific measures

### ISSUE THREAD

**Issue by tburdett** [ebi-ait/hca-ebi-wrangler-central#130]
We would like to be able to realistically evaluate and project the costs of operating the DCP based on meaningful scientific measures (e.g. projects, cells). This is needed so that our funders and the oversight committee can track the overall costs of running the DCP, and project how much it *might* cost in future based on anticipated growth rates of experimental data in the HCA. 

Right now, we have insight into roughly how much the DCP costs to run based on GB of data. For example, we know (calculated by Justin) that data Ingest costs approximately $0.05/gb data ingested, based on:

1. Data storage (assuming prompt cleanup of data after ingeston) 
2. Data egress charges (export from upload service to staging area) and 
3. Small overheads of running ingest system/web interfaces. 

Wrangling twice in different environments (i.e. staging and prod) doubles this cost.

We would like to produce useful insight into how much the DCP costs per cell, per project and how this has varied over time (e.g. has any of the development work we have done produced significant costs savings). Projecting into the future where we know how much data might be coming is a nice to have but not required.

A plot showing the total number of projects, cells ingested, and costs incurred, over time would win a gold star

This has a tight deadline - oversight have asked for an initial draft by next Monday 28th - so it is more important to estimate this quickly than get it perfect. I can share additional context or requirements if any is needed

Objectives:
- [x] Insight into how much the DCP costs per cell and per project 
- [ ] Insight into how DCP costs per cell and per project have varied over time
- [ ] A plot showing the total number of projects over time
- [ ] A plot showing the total number of cells ingested over time
- [ ] A plot showing the costs incurred over time
- [ ] SOP to create these numbers every sprint as part of the operations goals

**Comment by lauraclarke** [comment]
@tburdett are you happy with the outcome of this, please close this ticket if you are happy and open a new ticket for future work

**Comment by tburdett** [comment]
This isn't finished yet AFAIK. I seem to have lost the link to the spreadsheet too. Should this ticket be assigned to @ESapenaVentura?

**Comment by lauraclarke** [comment]
I have assigned it to @ESapenaVentura 
Can you post the spreadsheet link?

What remaining steps are there @tburdett ?

**Comment by ESapenaVentura** [comment]
Google sheet https://docs.google.com/spreadsheets/d/1oZ-6KHyyccktTCVij5udfOqJAo-kXPyiS1qrXtAJTUA/edit#gid=0

Diagram https://app.diagrams.net/?src=about#G1kC6WV4nBOnIsSm2tYgbBR-TnmszhVSWV

**Comment by tburdett** [comment]
Thanks for the links @ESapenaVentura!

I think we're here (I'll transfer this checklist to the description in the issue too)

- [x] Insight into how much the DCP costs per cell and per project 
- [ ] Insight into how DCP costs per cell and per project have varied over time
- [x] A plot showing the total number of projects over time
- [x] A plot showing the total number of cells ingested over time
- [ ] A plot showing the costs incurred over time

Is it going to be possible to get the last two items or is this not feasible given our current knowledge?

**Comment by tburdett** [comment]
On next steps, in case this is helpful: 

1. I'll need to produce an executive summary for oversight (I'll create some slides for this, so if you have information about how the costs were calculated that would be useful.
2. Ideally we'd repeat this exercise for the whole DCP, not just ingest, so setting up a spreadsheet with standard formulae in would be amazing, if that can come out as a bi-product of the spreadsheet we already have. This isn't required right now, just nice to have in case you have something that can be easily adapted

**Comment by lauraclarke** [comment]
If we are happy to have dates hardcoded for this first tranche @ESapenaVentura I am happy to help you figure them out between memory and email

**Comment by tburdett** [comment]
Estimated dates for projects work just fine for this task (aside: might be worth feeding back that original submission date is a useful piece of data to retain).

The other challenge is cost changes over time, though. I guess we have no idea how much the DCP was costing us per-project a year ago?

**Comment by lauraclarke** [comment]
Yeah, as we haven't been tracking this from the get-go, I don't think there is any way to do that retrospectively without a lot of forensics which probably isn't worth it

**Comment by tburdett** [comment]
If it's easily obtainable, great (even DCP v1 vs DCP v2 might be interesting), but point taken it might be too much effort. A side effect here might be for us to consider how better to log this information in future (maybe the tagging work @prabh-t is looking into at the moment will help)

**Comment by lauraclarke** [comment]
So I couldn't edit @ESapenaVentura's sheet but I took a copy and have slightly more fine grained dates for many of the DCP1 datasets here

https://docs.google.com/spreadsheets/d/1PUkNXDz5kRMLTGgT5oU2Osvdr03DNC8o4QeTIGt16e0/edit#gid=0

There have been two datasets redacted from the system since the DCP began, I don't think we can easily track those here but a quirk we will need to address going forward
