### ISSUE TITLE
schirmerSpatialMS

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1310]
Handed over from UCSC team ([mail thread](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/mW_QFaK5kfo))

### Project short name:
schirmerSpatialMS

### Primary Wrangler:
Arsenios

### Secondary Wrangler:
Ida

### Associated files:
[spreadsheet](https://docs.google.com/spreadsheets/d/1OS_kyLfG6mOmXZ-4TYp6R99Wt9EHnpaaA74O_s0WKd4/edit?usp=sharing)

* Google Drive: [folder](https://drive.google.com/drive/folders/1om-aFKFI-iGXFJqN5KhIZJ1zS-S4tUKF?usp=drive_link), [latest spreadsheet](https://docs.google.com/spreadsheets/d/1V2ButUzksaO45icWxt-iIlmGyivcH-W5/edit?usp=drive_link&ouid=101176945353039944995&rtpof=true&sd=true)
* ingest: [4c8e9d75-d85a-47de-9598-06549cf44b91](https://contribute.data.humancellatlas.org/projects/detail?uuid=4c8e9d75-d85a-47de-9598-06549cf44b91)

### Key Events

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [ ] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by arschat** [comment]
- [ ] Reply to contributor with the appropriate spreadsheet including the spatial omics tabs.

Will said that they had credentials but I couldn't find any ticket mentioning something like that. Waiting for reply from Will to verify that Celia has credentials, and then reply with this email.

> Hi Celia,
> We are happy to take over this project, thank you `@Will for helping Celia.
> 
> You've done a very nice job filling the spreadsheet. There were indeed a couple of tabs for spatial transcriptomics missing, but I've added them in the attached file. [Here](https://ebi-ait.github.io/hca-ebi-wrangler-central/technology_types_guide/10X_Visium/Curation_guidelines.html) is a guide on curating the 10x Visium experiments.
> 
> I would like to ask if there is any publication or pre-print manuscript related to this study. We could link it to this project and add any future publication in a later update.
> 
> After you fill the imaging related tabs, please send back the spreadsheet so I can review and get back to you with any potential comments.
> 
> In the meantime you could also upload your data files in the appropriate area (using [this guide](https://ebi-ait.github.io/hca-metadata-community/contributing/uploading-data.html)) with the credentials that has been sent to you.
> 
> If you have any questions or queries let us know. We could also have a zoom to help you with the submission if you prefer that.
> 
> Best,
> Arsenios
[schirmerSpatialMS_image_tabs.xlsx](https://github.com/user-attachments/files/17277485/schirmerSpatialMS_image_tabs.xlsx)

**Comment by arschat** [comment]
Contributor was not sure of the modelling for the experimental design. I will share the following with them.

```mermaid
flowchart TD
    A(["Donor organism"]) -- Collection protocol --> B(["Specimen from Organism"])
    B -- Image preparation protocol --> C(["Imaged specimen"])
    B -- Dissociation protocol --> D(["Cell suspension"])
    C -- Imaging protocol --> G("Image file")
    C -- Sequencing protocol --> E("Sequence file")
    D -- Sequencing protocol --> E
    C -- Analysis protocol --> F("Analysis file")
    D -- Analysis protocol --> F
```

**Comment by arschat** [comment]
Verified the modality of each sample:
  | snRNA | visium
-- | -- | --
CO37 | x | x
CO40 | x | x
CO41 | x | x
CO45 | x |  
CO74 | x | x
CO85 | x | x
CO96 |   | x
MS94 |   | x
MS197D | x | x
MS197U |   | x
MS229 | x | x
MS377N | x | x
MS377T | x | x
MS377I | x | x
MS411 | x | x
MS497I | x | x
MS497T | x | x
MS549H | x | x
MS549T | x | x

**Comment by idazucchi** [comment]
Hello! I'm done with the review
It looks great, I have only minor comments

### project
Is the project marked as NRES? It's not in the spreadsheet
### imaging protocol
minor detail, but the description includes all the analysis too, is this intentional?
### image file
imaged_speciment_MS377N doesn't have the 2 png jpeg json block
### dissociation protocol
The description mentions muscle dissociation rather than brain tissue and includes imaging prep description, is this the correct protocol?
###  library prep 
10x v3 is missing the cell barcode fields
### analysis file
there is some difference in the type of files offered for different imaged specimens
most of them have a set of 5, except for imaged_speciment_MS377N who only has 3
and then these have one set of 3 plus a set of 5
- imaged_speciment_CO96
- imaged_speciment_MS94
- imaged_speciment_MS197U

do you know if that's intentional?

**Comment by arschat** [comment]
exported and import form sent
