### ISSUE TITLE
GSE195665 - SpatiallyAdultBreastKumar

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1327]
### Project short name:
SpatiallyAdultBreastKumar
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1EDdbGYXo1sjx_rxiuLdZhJnsFDeEy2mj?usp=sharing)

### Published study links

* Paper: [A spatially resolved single-cell genomic atlas of the adult human breast](https://doi.org/10.1038/s41586-023-06252-9)

* Accessioned data: [GSE195665](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE195665)
    * [GSE234814](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE234814) visium
    * [GSE234817](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE234817) snRNA-seq
    * [GSE235326](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE235326) scRNA-seq

[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=9bb5fff9-5233-43bd-81ff-c226443ad58f)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
I've found a few discrepancies in the metadata for visium slides 8-10 and I've relied on the cxg metadata
I've also taken metadata or donors 133-1335 from cxg

I need to check withh Dave that we're still using the external portal sheet

**Comment by arschat** [comment]
Project has already been published by lattice.
https://explore.data.humancellatlas.org/projects/1ffa2223-28a6-4133-a5a4-badd00faf4bc
