### ISSUE TITLE
contributor account for: Jieun Kim

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1338]
Please create an account a contributor.

*Contributor details:*
* name: _Jieun Kim_
* email: _jekim2022@chauniv.ac.kr_

Request Details:
* Requested by: _arsenios_
> contributor would like to submit a dataset #1337 

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/Introduction/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by KociOrges** [comment]
Done. The credentials have been sent to Arsenios
