### ISSUE TITLE
HUTER project - HCA DCP meeting actions

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#138]
**Description of the task:**

1. Review HUTER spreadsheet example and clinical information shared with us to map variables to our current standard and identify any gaps.

2. Review HUTER anatomy/phyisological info and map to the ontologies we use. Provide a general summary of the ontologies we use to HUTER so they can build that info into their own platform.

3. Add new paper [Wang W, Vilella F, Alama P, et al. Single-cell transcriptomic atlas of the human endometrium during the menstrual cycle. Nature Medicine. 2020 Sep. DOI: 10.1038/s41591-020-1040-z.](https://doi.org/10.1038/s41591-020-1040-z)
PMID:32929266

4. Share the Fetal/Maternal Interface metadata spreadsheet with the HUTER team.

5. Share a template spreadsheet with the HUTER team and contact them about testing our new services to get feedback

Meeting notes, slides and other material: <https://drive.google.com/drive/u/0/folders/1oHy4Fl5GBNua2Zr3FZi817tx2bFrzgtu>

**Acceptance criteria for the task:**

~~* [ ] HUTER spreadsheet example and clinical information have been reviewed and the variables have been mapped to our current standard. If there were any gaps, then they would have been identified.~~

~~* [ ] The HUTER project anatomy/phyisological info have been mapped to the ontologies we use.
    * [ ] The HUTER team has been provided a general summary of the ontologies we expect them to use so they can build that info into their own platform.~~

* [x] The HUTER project paper [Wang W, Vilella F, Alama P, et al. Single-cell transcriptomic atlas of the human endometrium during the menstrual cycle. Nature Medicine. 2020 Sep. DOI: 10.1038/s41591-020-1040-z.](https://doi.org/10.1038/s41591-020-1040-z>) PMID:32929266 has been added to the dataset tracking sheet.

* [x] The Fetal/Maternal Interface metadata spreadsheet has been sent to the HUTER team.

* [x] An HCA DCP template spreadsheet has been generated and shared with the HUTER team.
    * [x] If possible, the new HCA DCP service is use for generating the spreadsheet.
    * [x] Feed back is collected after testing the service.
* [x] Need to work out if/how contributors can submit bioinformatics pipeline-related metadata

**Comment by lauraclarke** [comment]
Thanks @rays22 did the example paper of theirs look like something we could prioritize or not?

**Comment by rays22** [comment]
> Thanks @rays22 did the example paper of theirs look like something we could prioritize or not?

It looks like a high priority paper/dataset to me (primary human tissue, healthy donors, 10x technology).

**Comment by lauraclarke** [comment]
@rays22 how are you getting on with this ticket? What support do you need to complete it?

@gabsie when is the UX interview scheduled for?

**Comment by gabsie** [comment]
Hello - I have an interview with Beatriz only today - to go through the registration and the spreadsheet creation. I have directed them for all their usual questions to continue talking to the data wrangler team.

**Comment by rays22** [comment]
@aaclan-ebi , @clairerye 
A meeting has been scheduled for 
5 November, Thursday 13:00-13:30 BST /14:00-14:30 CEST
[to find out more](https://docs.google.com/document/d/11TMo2NKkf4W3DRU80uzLAMKovmRT8RV4Xrw8otSSDUs/) about the requirements of the HUTER project in order to support data flow from HUTER to HCA DCP. The meeting is also to follow up on their technical questions.

* Question 1:

>We are planning to organize our data structure with directories and subdirectories in HUTER platform so are you going to support this folder structure in the near future? Otherwise should we rename each file to upload the data to HCA-DCP in order to avoid file name collision?

* Question 2:

>In HUTER platform we are going to keep metadata in JSON format, but not under HCA-DCP schemas (researchers will also include specific metadata variables that are not going to be uploaded to HCA-DCP). Thus, we would like to explore a way to send you the metadata in the most suitable format for you. Could you tell us how it would be the best metadata format for you? Do you prefer a spreadsheet form or JSON files?

**Comment by rays22** [comment]
> @rays22 how are you getting on with this ticket? What support do you need to complete it?

I need developer support to follow up on technical questions from HUTER. I think I have that support. Other than that, I would need allocated time to complete the remaining tasks.

**Comment by lauraclarke** [comment]
So I don't think this is super urgent as they don't have a dataset they are ready to submit. Do you want to put it back into the product backlog and we can bring it back next time you are on operations?

**Comment by rays22** [comment]
# 2020-11-19 HCA-DCP & HUTER meeting minutes

1. Raw data file uploads (for example fastq sequence files, cell-gene expression matrices, cell-type annotations and possibly image files).
We have discussed the possibility of sub-directories for data files, because the `hca-util` tool does not support [sub-directory structures for data uploads.](https://github.com/ebi-ait/hca-documentation/wiki/How-to-upload-data-to-an-upload-area-using-hca-util)
*Action*: Cristóbal to send a slide or diagram of their planned directory tree/structure, so that the HCA DCP developers can assess the feasibility of supporting it or alternative solutions.

2. Metadata format for HCA DCP.
We have discussed the feasibility of direct JSON submissions to the HCA DCP, but we have come to the conclusion that the HCA DCP Excel metadata spreadsheet would be the preferred format for the HCA DCP in the first instance. We are going to pilot the spreadsheet format submissions, and we can re-visit the format options if that format proves to be problematic for any reason.

3. Units of data flow/submissions from the HUTER project.
In addition to the above two discussion points, we have also discussed if the HUTER project data would be submitted in one go or in subsets. I think the multi-submission model for the data flow was the consensus, but we might need further discussions on that.

**Comment by lauraclarke** [comment]
It looks like this meeting went well.

@rays22 What do you think needs to be done to close off this ticket? Are there further actions for which the ticket is useful to keep on top of?

**Comment by rays22** [comment]
> It looks like this meeting went well.
> 
> @rays22 What do you think needs to be done to close off this ticket? Are there further actions for which the ticket is useful to keep on top of?

I have added the remaining action items from this ticket to <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/139> so we can close it.
We can make new tickets for any emerging issues that may come up to support the HUTER project. I am closing this issue.

**Comment by lauraclarke** [comment]
Thanks for clarifying

I reopened it and put it in the done column as that will make it easier to track how much we completed this sprint
