### ISSUE TITLE
Update Ontologies SOP with latest process

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#142]
**Description of the task:**

Previously we made all ontology requests through our HCA ontology repo but in a meeting with David today it seems like it would be more efficient to make tickets directly in each of the individual git repos for each ontology. This ticket is to both confirm the process that we should use with David and/or Zoe as well as update the SOP documentation here: https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/docs/SOPs/request_ontology_terms.md

**Acceptance criteria for the task:**

**Comment by lauraclarke** [comment]
Based on our conversation with Paola yesterday, it might be better to default to using the HCAO repo and only post issues to the specific ontology repos when we have certainty that a new term is needed

**Comment by mshadbolt** [comment]
Some information from latest ontology call:
l). Paola suggests a “decision tree” along the following: 
Are you requesting a cell type or anatomy term? If yes,
Are you requesting a term that already exists in another ontology?
Then open a ticket in the HCAO tracker and request that we import that term
Are you requesting a term similar to one that already exists in another ontology?
Try to make an explicit case for having a new term; clarify what the differentia is with the existing term (e.g. "PMID:123456 suggests that cells in zone A and B of organ X are functionally different because..." rather than just listing PMID:123456). 
If you think you have a reasonably strong case, then open a ticket in the appropriate source ontology tracker (CL, Uberon…)
If you think your case is not strong enough at the moment, but may become stronger in the future when more experimental evidence is available, then open a ticket in the HCAO tracker
If you are unsure, then open a ticket in the HCAO tracker
Are you requesting a grouping term, e.g. lumping together 2 or more existing cell types or anatomical structures?
Follow the same procedure as above
Are you requesting a term that doesn’t exist at all in CL or Uberon, possibly because it’s specific to mammals?
Then open a ticket in the CL or Uberon tracker; provide references and suggest appropriate taxon restrictions if applicable.
Are you requesting a term other than cell type or anatomy? If yes,
Open a ticket in the EFO tracker
It is advisable to keep term requests, and specific questions/update requests about existing tickets, within the GitHub trackers please, rather than on Slack. It’s easier to keep track in GitHub. Of course, feel free to ping Paola on Slack if it’s urgent (just be aware that she’s part-time so may not respond immediately).  

https://docs.google.com/document/d/1PXLco-VtpRIFA1DuDDafxqQl2PSW2ZZMG82qA_-1xIE/edit#

**Comment by mshadbolt** [comment]
I tried to make a diagram of this flow here: https://app.diagrams.net/?libs=general;flowchart&src=about#G1CSUSllc_1LWz3QG3dKXkIMLe-t_1PqgG

I still have some questions about it so I am trying to set up a time to talk to paola and get those questions answered before incorporating into the SOP.

**Comment by mshadbolt** [comment]
This is waiting on feedback from ontology team on what the process should be, should check back up on it the week of 30/11

**Comment by mshadbolt** [comment]
Pinged paola to ask if a suitable process and decision tree has been worked out that we can incorporate into the SOP.

**Comment by mshadbolt** [comment]
I made some updates based on the latest communications with Paola but still have some open questions before closing this ticket

**Comment by mshadbolt** [comment]
I would like another wrangler to have a quick read through before classifying as done.

**Comment by rays22** [comment]
I have read the SOP and it looks easy to follow and clear to me.
I have found a potential typo in the sentence
`Does it already exist in FAO?`.
<https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/request_ontology_terms.html#decision-tree>
Did you mean `FMA` in place of `FAO`?
Other than this, the SOP looks fine to me.

**Comment by mshadbolt** [comment]
Thanks for the review and feedback, I have fixed the typo and will close this issue, we can update if people come across any further issues
