### ISSUE TITLE
Human heart snRNA-seq, snATAC-seq and Visium data

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#146]
* Project short name: HumanMyocardialInfarctionSpatialMap
* Ingest project UUID: `e9f36305-d857-44a3-93f0-df4e6007dc97`
* Kuppe C, Ramirez Flores RO, Li Z, et al. Spatial multi-omic map of human myocardial infarction. bioRxiv; 2020. [DOI: 10.1101/2020.12.08.411686](https://doi.org/10.1101/2020.12.08.411686)

### Primary Wrangler:
Ray

### Associated files:

Google Drive:

### Key Events

- [x] initial meeting with Rafael Kramann and colleagues -- [minutes](https://docs.google.com/document/d/1FBihZW6bEOrNRML1LL7hRjvIyYL0aqDiMWH2CtLWHq4/)
- [x] generate custom metadata spreadsheet
- [x] Assign the Primary Wrangler
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data files
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data (to a sufficient standard to submit dataset)
- [ ] sumbit matrix files to ArrayExpress
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Email UX to inform that they're ready to send survey

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by rays22** [comment]
Some of the data is sensitive and may require controlled access.  
Alternative approaches to support the contributors in sharing their data: <https://docs.google.com/document/d/189A0zdttGDTc6usimWDKcvapeiFyaCTmrvjHi7d908s/>

**Comment by rays22** [comment]
Today I sent a [follow up email to Rafael Kramann.](https://docs.google.com/document/d/17M3C2MUjNxBmOR3YkuoMpz26DtrtFys0xyx-_nfznWU/).

**Comment by rays22** [comment]
* They have decided to use a Zenodo entry to share processed data to reviewers during the submission process. They are planning to continue with the HCA submission during the paper revision process.

**Comment by rays22** [comment]
Stalled until contributors are ready to progress with their submission after their paper is accepted.

**Comment by ami-day** [comment]
@rays22 to follow up on this

**Comment by rays22** [comment]
* I have found a pre-print that I think is related to this project:
Kuppe C, Ramirez Flores RO, Li Z, et al. Spatial multi-omic map of human myocardial infarction. bioRxiv; 2020. [DOI: 10.1101/2020.12.08.411686](https://doi.org/10.1101/2020.12.08.411686)
* I have sent a follow-up email to the contributors to request cell type annotations and cell-gene expression matrix files to share via the HCA DCP.

**Comment by rays22** [comment]
I have not received any cell annotation or gene expression matrix files from the contributors.
The wrangling of this project is stalled, because there is not any public data available yet for this project.

**Comment by ESapenaVentura** [comment]
Pre-curated spreadsheet, sent instructions to upload matrix and asked for review of the pre-filled template

**Comment by ESapenaVentura** [comment]
Duplicated in #661
