### ISSUE TITLE
Data retraction SOP

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#147]
While we have had to retract data a couple of times we don't have a defined SOP or any documentation about the places where data and metadata needs to be cleaned up from if we get a retraction request for GDPR or another reason

We need a written SOP which can live in https://ebi-ait.github.io/hca-ebi-wrangler-central/ that identifiers all the different places data might live and what steps need to be taken to remove it

This isn't about writing new code to do a cleanup, just what the steps would be right now either using an existing processor with an indication that a script would need to be written to carry out the cleanup.

When we get a retraction request, we should be able to act on it in a 24hr timeframe. If there are blockers which would prevent that these should be identified so we can work with @clairerye to figure out how to prioritize

- Where are all the places could data and metadata be? when in the data lifecycle might they have reached those places. This should include backups (at least an understanding of when such backups expire
- Who can clean up from those locations?
- What process can they use?
- Who are the downstream folks we would need to inform about the retraction request so they can also clean up data

**Acceptance criteria for the task:**

- [x] An SOP document that defined the retraction process
- [ ] Review of the SOP by both @ebi-ait/hca-dev and @ebi-ait/hca-wranglers 
- [ ] What are the pain points/difficulties with the SOP as it currently stands

This SOP should enable all data and metadata from a project to be removed within 24hrs. If that isn't possible we should understand why

**Comment by ESapenaVentura** [comment]
Re-opening as linking the PR closed this issue automatically.

I have mostly finished with the task, I need some input from the @ebi-ait/hca-dev and @ebi-ait/hca-wranglers to finish up a couple of sections.

I have merged to master to be able to visualise [in the git pages](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/data_retraction_SOP.html), but kept the branch for further changes.

**Comment by mshadbolt** [comment]
First it says to delete a bunch of stuff, then it says before deleting, make sure you save copes of x, y, z. I wonder if upfront we should say something like, create a folder that will hold copies of things you will need later, save x, y, z here and delete the things elsewhere. 

Otherwise we risk someone stepping through to that point having deleted the things they need for the subsequent steps. Then once the whole process is finished, the last step is to delete that folder we made at the start which is the last copy.

Other thing is maybe some instruction on where to get that information that we need to keep, I am not sure how I could find the `DSP submission UUID` for example

**Comment by ESapenaVentura** [comment]
>First it says to delete a bunch of stuff, then it says before deleting, make sure you save copes of x, y, z. I wonder if upfront we should say something like, create a folder that will hold copies of things you will need later, save x, y, z here and delete the things elsewhere.
Otherwise we risk someone stepping through to that point having deleted the things they need for the subsequent steps. Then once the whole process is finished, the last step is to delete that folder we made at the start which is the last copy.

I will review the "before you start" section to include your feedback! It's just a bunch of UUIDs and accessions, nothing that needs a folder, but I will be more clear on that

>Other thing is maybe some instruction on where to get that information that we need to keep, I am not sure how I could find the DSP submission UUID for example

I gave a pointer to the archiving instructions to retrieve the DSP uuid, but I will make it more clear at the beginning or just attach the instructions

**Comment by lauraclarke** [comment]
Thanks for this @ESapenaVentura I have reviewed and put some first comments here

https://docs.google.com/document/d/1iOvrlGoOrsaRpW_a35Zv8HCapnPVV7-qghUJbQ9XaMI/edit#

Some specific things, this is solely from the wrangler perspective. We need to get @ebi-ait/hca-dev input and have one SOP which covers everything that needs doing and has better instructions for infrastructure cleanup than as a dev

Is there anything here which someone who wasn't responsible for wrangling a dataset wouldn't be expected to know and might need to find out? It should be possible for anyone to be asked to remove any dataset so if there are any aspects which might not be obvious so someone who didn't wrangle it, that needs to be covered here

No data can be left behind, even if it isn't public, we might need to have a discussion about what that actually means but just because it isn't public isn't a reason to not delete it
Are there backups that also need to be addressed?
Are there any steps needed to ensure something doesn't get inadvertently released/uploaded again?

Could you put the email templates into say a google doc as I have some editorial suggestions which might be easier in suggestion mode? in a document. Warn is definitely not the right English word here (as an aside I would be interested to know what the Spanish equivalent to warn is and if there is a reason for the misunderstanding!)

**Comment by ESapenaVentura** [comment]
>Some specific things, this is solely from the wrangler perspective. We need to get @ebi-ait/hca-dev input and have one SOP which covers everything that needs doing and has better instructions for infrastructure cleanup than as a dev

I was writing this from a wrangler perspective, I will update with the dev details then! There are some specifics that wranglers can't carry on their own, and some others that will need scripts to be easily reproducible by everyone (e.g. modifying the DSP metadata for a submission)

I have flagged some sections as [script missing] so @clairerye can prioritise the dev work on that

>Is there anything here which someone who wasn't responsible for wrangling a dataset wouldn't be expected to know and might need to find out? It should be possible for anyone to be asked to remove any dataset so if there are any aspects which might not be obvious so someone who didn't wrangle it, that needs to be covered here

I think I have covered everything that any person responsible should know beforehand about the dataset in the "before you start" section.

>No data can be left behind, even if it isn't public, we might need to have a discussion about what that actually means but just because it isn't public isn't a reason to not delete it

In my initial approach that was my idea but the latest version should not contain anything stating that non-public data should not be deleted. To anyone reviewing please let me know if you find a line where that is not the case as it might have slipped after several edits.

> Are there backups that also need to be addressed?
Are there any steps needed to ensure something doesn't get inadvertently released/uploaded again?

From my point of view I have covered all possible backup options (hca-util areas, ingest areas, EBI cluster, DSP, ingest submission + metadata archiver) but I can't be 100% sure without a dev confirming

>Could you put the email templates into say a google doc as I have some editorial suggestions which might be easier in suggestion mode? in a document. Warn is definitely not the right English word here (as an aside I would be interested to know what the Spanish equivalent to warn is and if there is a reason for the misunderstanding!)

Sure, I have created [this doc](https://docs.google.com/document/d/1uFidbJnHVylK7zUmV46VU_05Ef5dC7uGqzcsSckgvQI/edit#). The Spanish verb I thought of was "advertir", it makes sense in spanish but I guess the wording in english is different!

**Comment by lauraclarke** [comment]
@ESapenaVentura I just wanted to list what we discussed yesterday and briefly this morning

This document should cover all tasks to do with retraction regardless of which members of the team who can do that. Including statements what permissions someone needs to be able to complete each step

If there is a step which needs database statements or unix commands right now but ultimately should be automated via a script or other function, please make sure there are details about what would need to happen now if a request came in and then you/the team should give @clairerye a list of pain points that can be added to the impact map/prioritized for resolution

**Comment by lauraclarke** [comment]
For backup cleanup, the requirement for a backup expiration policy needs to be listed (I think there is already a ticket about this) so we can be clear when backups expire and make a decision if more action is required

**Comment by lauraclarke** [comment]
@prabh-t just updating this before the operations meeting

The goal is to make sure this SOP has all the instructions needed so one or two people with the appropriate rights in the system can completely remove a dataset we are asked to retract. There are likely to be manual steps right now, the SOP should cover how to complete this step now and once this is finished we should work with @clairerye to figure out how to prioritize the improvements needed to improve the automation of the process.

@ESapenaVentura have all the revisions you made been merged? Is there anything @prabh-t needs to know before taking over this task and filling in the gaps where knowledge of the infrastructure is needed?

**Comment by prabh-t** [comment]
@ESapenaVentura Some initial dev input to the data retraction SOP can be found in this [branch](https://github.com/ebi-ait/hca-ebi-wrangler-central/tree/data-retract-dev-input).

**Comment by ESapenaVentura** [comment]
@aaclan-ebi agreed on taking a look at the PR https://app.zenhub.com/workspace/o/ebi-ait/hca-ebi-wrangler-central/issues/171

**Comment by aaclan-ebi** [comment]
@ESapenaVentura I've updated the branch and added comments in that PR.

**Comment by aaclan-ebi** [comment]
The doc seems good and well thought of. It would be nice to support the following in Ingest to simplify the data retraction process.

1. Auto delete of submission upload area when submission is deleted via UI/API
2. Auto delete of archive entities in Ingest when submission is deleted
3. Auto delete of spreadsheet when submission is deleted
3. Auto delete of project in TDR when project is deleted

**Comment by ESapenaVentura** [comment]
Those points would be great to work on. Should we open a ticket?

Also, I just finished with the (hopefully) last review. @aaclan-ebi can you check everything is in order and, if it is, can you merge?

Thanks!

**Comment by lauraclarke** [comment]
Probably best to consult with @clairerye about how to prioritize those issues, they need to be associated with an impact and prioritized again everything else we need to do.

As this isn't something we have to do super often, having manual steps in the first instance might not be the end of the world

**Comment by lauraclarke** [comment]
@ESapenaVentura can you coordinate with @jacobwindsor on the final merge needed here

The automation that you want to add to the prioritization list, you need to work with @clairerye to record in the right place

**Comment by lauraclarke** [comment]
Looks like https://docs.google.com/document/d/1h-oUrbOb5OZS8L_F023eYP9mYwyuimTH7jdPQEMGj-E/edit# is the best place to add the automation requirements

@ESapenaVentura is it that and the merge of the PR which are needed for this to be done
