### ISSUE TITLE
Define wrangling board

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#148]
As an operations task this sprint, we have decided to define a wrangling board to better understand where each dataset is in the process of brokering.

**Outstanding tasks**:
- [x] Define how to pull only wrangling tickets
- [x] Define the columns of the board
- [ ] Define clear guidelines on when to move each ticket through the board.

**Comment by mshadbolt** [comment]
I am thinking we can attempt to do this as part of the hackathon tomorrow, because I think some of the things we are trying to define in the tracker might be better suited to being defined in the board and could be answered with some of the reporting functionality of zenhub.

**Comment by ESapenaVentura** [comment]
The board has been already created, so I guess the last standing item from this ticket would be to update the documentation to reflect the guidelines on when to move the tickets in GH

**Comment by lauraclarke** [comment]
Where is the board?

**Comment by mshadbolt** [comment]
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/148#workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/board?repos=261790554
