### ISSUE TITLE
Archive snRNA-seq_for_human_retina

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#16]
This ticket will need input from the ingest dev team in order to facilitate archiving.

The most current spreadsheet is in the Brokering folder here:
https://drive.google.com/open?id=142eVL47TVV3m5WKMe3SZ7ldC283QRh89

The data is in the DCP DSS

all files need conversion to BAM

There are known issues that need to be addressed in the current metadata. 

The overall experimental graph needs to be checked and updated, Stanford contacted the contributor and drew this as the confirmed graph https://docs.google.com/drawings/d/1JqfKkD3qcOVyqThN5OC4Z78BN7BV28V76daXeUMZQNA/edit

Notes from Stanford:
> All the fastqs with process date 8/2/19 batch 2 had abbreviated/clipped reads. Read1 is only 26 bp and does not contain the last 2 bp of the UMI. The contributors state they are excluding these libraries from their analysis for publication.
	
>19D013_fovea and 19D013_foveaR (and 19D014_fovea and 19D014_foveaR) are being analysed as separate libraries by the contributors. They are combined as one library prep in the DCP.

>The DCP ingest spreadsheet that we originally saw has 9 specimens, duplicating 19D013_fovea and 19D014_fovea. (The DCP system ignored the duplication.)
There’s also a typo in cell_suspension.biomaterial_core.biomaterial_description

Once the project is archived we would need to update the metadata to include accessions

**Comment by mshadbolt** [comment]
Added the fact that this project has linking issues to the ticket body and to the 'Datasets for MVP' spreadsheet and pinged Kylee

**Comment by ami-day** [comment]
I'm not sure I understand what needs to be done or has been done here and what to do next...

**Comment by Wkt8** [comment]
Lattice is looking after this. Not us. No more actions required.
