### ISSUE TITLE
Update script to retrieve data from NXNs database

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#160]
**Description of the task:**

Once the re-ordering of the dataset tracking sheet is definite, update the script to [compare tracking sheet with nxn's database](https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/src/compare_tracker_with_nxn_sheet.py) 

**Acceptance criteria for the task:**

- [x] The script is updated so it can compare nxn's database with the dataset tracking sheet again
- [x] (optional) add feature to avoid that re-ordering of the columns will break it again

**Comment by mshadbolt** [comment]
I have noticed sometimes the script might introduce weird encoding in the text for symbols it doesn't recognise, e.g. `Single‚Äêcell transcriptomes reveal characteristic features of human pancreatic islet cell types`

Not sure if this is something easy to address

**Comment by ESapenaVentura** [comment]
Weird,  I'll look into that! I do include a utf-8 decoding for valentine's database, as sometimes some symbols would break reading the database, but I always assumed after that all the symbols would be alright

**Comment by ESapenaVentura** [comment]
The PR has already been merged.

I will keep an eye on the encoding issue but, for now, I'll close this issue!
