### ISSUE TITLE
Investigate doubling of AWS costs when exporting datasets

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#161]
Looking at the AWS October costs, I identified two spikes on the S3 cost, on the 22 (271$) and 23rd (260$), both catalogued by the AWS console as "Data Transfer Out".

Today Enrique confirmed that around those dates only one dataset was re-exported. It was dataset "HeartSingleCellsAndNucleiSeq", that was already in ingest S3 buckets and that has a size of 3054.23GB. 

If the dataset was already in ingest S3 buckets, and only needed re-exporting, at 0.09$/GB the cost should have been of ~275$, whereas here we are seeing double that cost.

Investigation needs to take place to see why this happened, if it is the normal scenario (in which case we would need to update the costing documents etc) or something odd has happened this time.

**Comment by lauraclarke** [comment]
@prabh-t will you have time to take this on during this sprint?

**Comment by prabh-t** [comment]
@lauraclarke yes I'll take a look.
@ESapenaVentura was the export probably done in staging (or dev) first, then in prod?

**Comment by ESapenaVentura** [comment]
@prabh-t @aaclan-ebi will have a better understanding but I think it was done only in prod

**Comment by prabh-t** [comment]
Ok, I've just checked the UI in all envs, and it looks like the HeartSingleCellsAndNucleiSeq dataset was exported in prod only.

**Comment by aaclan-ebi** [comment]
It makes sense since it was reexported twice. In the first try, we found out that the file descriptor changes wasn't deployed to production. We had to redeploy the file descriptor changes and reexport the project again :(

**Comment by ofanobilbao** [comment]
That answers what this ticket was aiming at, which was to understand why if we only exported once we had charges equivalent to having done it twice. From Alegria's explanation it was actually exported twice. So it makes sense. And we don't need to worry about this. @prabh can we then consider this done? Thanks!

**Comment by ESapenaVentura** [comment]
Makes total sense now. I completely forgot about the file descriptors issue we had.

That solves the mystery!

**Comment by aaclan-ebi** [comment]
cool, we've also proven that our formula to compute ingest cost is almost accurate!

**Comment by prabh-t** [comment]
Interesting to note we do not run export in pre-prod environments. Not sure if this is for this dataset only, or it is intended so to avoid the data transfer charges. Also there is no way to know if the export was triggered more than once with not history of export maintained.

**Comment by lauraclarke** [comment]
@clairerye export history sounds like it might need some sort of impact/value analysis, what sort of audit trail is needed here?

**Comment by lauraclarke** [comment]
Sounds like this ticket can be closed though? @prabh-t @ESapenaVentura @aaclan-ebi do you agree?
