### ISSUE TITLE
Anna Williams - MS/Unaffected brain

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#162]
Related to https://github.com/HumanCellAtlas/hca-data-wrangling/issues/130

Opening ticket to track brokering into SCEA

**Comment by ESapenaVentura** [comment]
Need to update so that there is the link to this portal shown
https://cells.ucsc.edu/?ds=oligodendrocyte-ms

**Comment by ofanobilbao** [comment]
@ESapenaVentura moving this to Finished in the Wrangling board as I believe there is nothing left in the SCP route. Is that correct? Thanks!
