### ISSUE TITLE
GSE132658 DevelopingCardiacSystem

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#164]
Related to https://github.com/HumanCellAtlas/hca-data-wrangling/issues/454

**Comment by mshadbolt** [comment]
This is already in SCEA here: https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-16/results/tsne, moving to finished

**Comment by mshadbolt** [comment]
I am reviewing what is currently in ingest and this project has two 'exported' projects and I am not sure which should be kept and which should be deleted:
https://contribute.data.humancellatlas.org/projects/detail?uuid=2086eb05-10b9-432b-b7f0-169ccc49d270
https://contribute.data.humancellatlas.org/projects/detail?uuid=e07897dc-c25e-453d-b04c-27ca33adb630
