### ISSUE TITLE
Elisa Laurenti - AdultHemOrgans

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#165]
This ticket is to track the brokering of this project to the SCEA. This project has two submissions. The first one is tracked here: <https://github.com/HumanCellAtlas/hca-data-wrangling/issues/394>. The second (data addition) update is tracked here: <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/211>.

* HCA project short name: AdultHemOrgans
* Study/project accessions: S-SUBS4, PRJEB36885 

**Primary Wrangler:** Ray

**Secondary Wrangler:**

**Associated files:**

Google Drive: <https://drive.google.com/drive/folders/1wPFQvAVYX8_F5rlYlgFIxuI4w-Fmr8J->

**Comment by ofanobilbao** [comment]
@rays22 is this dataset done from the DCP perspective? Can I move it to Finished on the wrangling board? Thanks!
