### ISSUE TITLE
HumanAdultKidneyLiaoMo - GSE131685

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#166]
Broker dataset to SCEA

Google Drive folder: https://drive.google.com/drive/folders/1Sw7ZjUwPt32C-X711DeBJy66Q2bNq-OD

Ingest submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=4cb04823-f4b8-4255-a06f-ecc00991304c&project=2ef3655a-973d-4d69-9b41-21fa4041eed7

No previous ticket was made for this dataset

**Comment by ami-day** [comment]
preparing for SCEA: E-HCAD-21

**Comment by lauraclarke** [comment]
Has this been exported @ami-day if it is entirely complete you should move to Done rather that closed as Zenhub doesn't give us good stats otherwise
