### ISSUE TITLE
Ingest Dev docs re-org and clean up

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/hca-ebi-wrangler-central#168]
The Ingest Dev docs [here](https://ebi-ait.github.io/hca-ebi-dev-team/) needs some re-organisation.

- [x] Write System Maintenance in markdown
- [x] add some hierarchy to the dev docs
- [x] clean up (remove duplicates and delete out of data docs) 
- [ ] optionally, merge dev with wrangler docs all in one place

**Comment by prabh-t** [comment]
@aaclan-ebi I have some local changes not pushed yet, as I need to review them before. It's mostly fixing the duplicate issues and trying a slightly different hierarchy. I'll try to push asap.

**Comment by aaclan-ebi** [comment]
@prabh-t the actual pages in the github page https://ebi-ait.github.io/hca-ebi-dev-team/  seems missing

**Comment by prabh-t** [comment]
@aaclan-ebi that should be fixed now. It haven't completely got how the nav works so I've been playing a bit. I've committed a round of re-org and cleaning up. I think this should be an ongoing process and should be included as a task for the developer on ops.

**Comment by aaclan-ebi** [comment]
Yeah, I agree. Thanks for fixing it @prabh-t !

**Comment by lauraclarke** [comment]
Is this done? I know there is a merge between https://ebi-ait.github.io/hca-ebi-dev-team/ and https://ebi-ait.github.io/hca-ebi-wrangler-central/ is desired but we could do that another time?
