### ISSUE TITLE
GSE139324 - HnsccImmuneLandscape

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#172]
**Primary Wrangler:**
@ESapenaVentura 
**Secondary Wrangler:**
Marion

**Associated files:**

Google Drive: https://drive.google.com/drive/folders/16QJM0IVnfidO3S9jTWI6zUqb6uLqmt5v

**Published study links**

Paper: [Immune Landscape of Viral- and Carcinogen-Driven Head and Neck Cancer](https://www.sciencedirect.com/science/article/pii/S1074761319304959?via%3Dihub)

Accessioned data: [GSE139324](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE139324)

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production

**Comment by ESapenaVentura** [comment]
Files are currently being validated - https://contribute.data.humancellatlas.org/submissions/detail?id=5fb3a736706b4c65fc989e03&project=3089d311-f9ed-44dd-bb10-397059bad4dc

**Comment by mshadbolt** [comment]
Have you already done the ingest graph validation step and forgot to tick the box or would you like me to do that as part of review?

**Comment by ESapenaVentura** [comment]
I have asked @rays22 to do it as the ingest-graph-validator is completely broken for me at the moment

If you are happy to do it we can tell him to not continue with the validation!

(Also on another note, apparently some files are invalid so I will need to re-upload to the s3 bucket)

**Comment by mshadbolt** [comment]
As discussed the ingest graph validator seems a bit broken. I did my own checking of the links and everything seems ok from my point of view.

I changed the ethnicity to 'european' rather than american as we had discussed

I also removed the 'oral cavity' ontology as the uberon term doesn't seem to have the same meaning as we think of it or as the authors intended.

I think it would be good to add any available matrix and/or cell annotation as supplementary files until we figure out a better way (not sure if there are any available in GEO or as supp files on the publication

**Comment by ESapenaVentura** [comment]
Ran ingest graph validator with the latest version, tests succeeded. 

I have uploaded the latest files (currently validating) and once I am sure they succeeded I will delete them from my ncbi cloud bucket

**Comment by ESapenaVentura** [comment]
Files are valid! It's ready for exporting

**Comment by rays22** [comment]
This dataset has been exported to the Terra staging area.

**Comment by ofanobilbao** [comment]
@ESapenaVentura I just moved this to Finished as I believe it's done from DCP perspective. Please, let me know if this was not the case. Thanks!
