### ISSUE TITLE
How to track regular operations task 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-wrangler-central#176]

**Comment by lauraclarke** [comment]
This is linked to  a document Rodrey wrote before he left
https://docs.google.com/document/d/1jfCClZ8gfNxOWZSPzj9xr1tx99-C9d8Lpcw_G85yvL8/edit

and the operations tasks listed in https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/operations_tasks.html

I would like the table in the operations notes updated with what the regular tasks are, and how frequently they should be run
https://docs.google.com/document/d/1O2nCBtnFY-AWh_1_s188xLTyvaZpwbUUp3Pvs_aV_jc/edit?ts=5f1816b8#heading=h.1c86hlw8cv82

**Comment by jacobwindsor** [comment]
Thans Laura - hadn't seen the document.

I had started a branch to document all this as well as some e2e tests and will copy the tasks into that table.
