### ISSUE TITLE
SOP for cleaning up dev and staging upload areas

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/hca-ebi-wrangler-central#177]
Currently when cleaning up dev and staging mongodb, we often forget to clean up the data in the upload areas for those environments. 
The dev and staging upload areas currently occupies close to 30TB of data in two S3 buckets. This incurs a huge monthly bill (approx. 700$/mo.).

Previously we have deleted data directly in those buckets. We should come up with a correct SOP for this. As data in these S3 upload areas are managed by Upload Service.

**Comment by prabh-t** [comment]
from slack:

deleting directly from the bucket means the upload service isn't updated of this. there is an api endpoint to do that, but it doesn't seem to actually remove the data, it probably just marks the area as deleted in the upload postgres. ideally the postgres entry should be removed.

**Comment by jacobwindsor** [comment]
This is likely not needed anymore since @prabh-t added expiration policies to dev and staging buckets. Thanks for reminding me @aaclan-ebi
