### ISSUE TITLE
Docker pull rate limit fix

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-wrangler-central#178]
Quay.io docker image builds are failing with the following error: 

```
Could not pull base image: API error (500): toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
For more info on this error, see https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/
https://www.openshift.com/blog/mitigate-impact-of-docker-hub-pull-request-limits

To resolve the issue we're moving all the base images of the ingest components to quay.io https://quay.io/repository/ebi-ait/ingest-base-images and change the Dockerfile's of each components.

**Comment by aaclan-ebi** [comment]
This ticket should have been created in hca-dev-team repo. Keeping this ticket in this repo anyway.

**Comment by lauraclarke** [comment]
As we view it all through zenhub I don't think it necessarily matters which repo it is in

**Comment by aaclan-ebi** [comment]
forgot to tag this issue for commit in core https://github.com/ebi-ait/ingest-core/commit/5a8a6b5022d0f9fd77541d15f8e1ec844f06256c

**Comment by aaclan-ebi** [comment]
The  base images are now moved to quay.io  and Dockerfile updated for all the following components:

ingest-ui
ingest-core
ingest-state-tracker
ingest-broker
ingest-validator
ingest-exporter
ingest-archiver
ingest-file-archiver

**Comment by lauraclarke** [comment]
Can this be closed? is it finished?

**Comment by lauraclarke** [comment]
ignore that, I was looking at the wrong column
