### ISSUE TITLE
Discuss best approach to curate dataset tracking sheet

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#182]
**Description of the task:**

After the discussion on the hackathon, it was decided that each wrangler would curate ~230 rows. Once into the task, the wranglers decided that was not feasible and other approach should be taken. 

On the operations review meeting, there was a discussion about what could be the best approach. The outcomes of this discussion were:
- Curate thoroughly datasets that are:
   - Ingested
   - In progress
- Create a filter view to decide which datasets are of high value to curate.
- From now on, addition of new datasets will involve full curation

**Acceptance criteria for the task:**

- [ ] A final decision is made on what the best approach is
- [ ] The decision is documented

**Comment by lauraclarke** [comment]
@ami-day will complete the next steps in this 

She will identify the rows that need more curation and setup a filter so they can be found
She will do curation of a subset

Ami also wants to look at the currently unsuitable datasets in the spreadsheet and see if they can be shifted to something which could be wrangled now we are better able to get fastq files from the NCBI
