### ISSUE TITLE
Retrieve and host DCP1 project matrix files and host them

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#184]
The matrix service is being retired as part of the retirement of DCP1 at the end of the year. 
The original plan was to serve the static matrix if you asked for a matrix for a project, and if you asked for a combined matrix across multiple projects, to return a sensible error as part of DCP2. There is now a significant risk of this not being delivered and SCEA and others rely on this. 
We need to get a copy of all project matrices from DCP1 and transfer them to an FTP site where they can be publicly accessed. 
FTP site setup instructions: https://tsc.ebi.ac.uk/article/ftp-request-new-ftp-site

We then need to work with SCEA to adapt their tool to pull the matrix files from the FTP site instead of the DCP1 matrix service.
https://github.com/ebi-gene-expression-group/hca-matrix-downloader

**Comment by mshadbolt** [comment]
Recording some questions here while they are in my head:

* What level of granularity will the projects need to be? i.e. will they need to be split by:
  * technology SS2/10x etc
  * species
  * tissue type i.e. primary vs cell line vs organoid
  * organ
  * developmental stage
  * other?

* will we be expected to maintain this in the future? i.e. when there is an MVP where matrices can be downloaded from will we need to continue to add them to this ftp site? Will we need to replace these with the new matrices as they are generated under the 'phased' plan?

* will we be expected to edit the code again if there is a new matrix service/alternative way of getting matrices programmatically?

**Comment by clairerye** [comment]
https://humancellatlas.usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Febi-gxa%2Fhca_matrix_downloader%2Fhca_matrix_downloader%2Fv0.0.3%2Bgalaxy0

**Comment by clairerye** [comment]
Pablo's email comments:
1.- re-write the underpinnings of:

https://github.com/ebi-gene-expression-group/hca-matrix-downloader

so that it would retrieve results from, say, an ftp directory or an object store, after an initial search against something (a json file metadata->data path?) holding the exactly searchable metadata (Project title, Project label or ID) as explained on that repo.

If that is done without any changes to the interface, after some testing:

2.- we could simply bump the version of that repo and make a release of that
3.- bump the version of the bioconda package (https://bioconda.github.io/recipes/hca-matrix-downloader/README.html)
4.- update the Galaxy wrapper (https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/develop/tools/tertiary-analysis/data-hca/matrix-service.xml) to look at the newer version of the bioconda package. I would still add that the data is currently being retrieved from EBI with some wording explaining why this is not coming from the HCA.

While the CLI does allow a more complex Matrix API query in json, we are not exposing this AFAIK in the Galaxy tool, so we can get away with not serving that part (with proper explanation on the CLI).

2, 3 and 4 are relatively straightforward if interfaces (how you use the CLI) are kept without changes in point 1.

**Comment by mshadbolt** [comment]
currently working on trying to set up the ftp, we first need to set up a virtual user who will be able to write to the ftp, I have asked @tburdett to follow this up as needs to be requested by the GTL

**Comment by mshadbolt** [comment]
i forked the repo and setup a branch to begin work on refactoring

https://github.com/ebi-ait/hca-matrix-downloader/tree/hca-dcp-ftp

**Comment by mshadbolt** [comment]
Changes to the code are on a branch with a PR here: https://github.com/ebi-ait/hca-matrix-downloader/pull/1

We think the code should work but we are waiting for the ftp folder to be set up and the files to move there before we can test it properly. 

@ESapenaVentura downloaded the matrix files to the cluster so they are ready to be moved to the ftp folder when it is created.

After we are confident the code changes work, I think the next step would be to contact Pablo to see if he is happy with the changes and to get his help with releasing the code to bioconda and testing it works in their galaxy instance.

**Comment by ESapenaVentura** [comment]
The FTP site is ready and with all the matrix files available

I have tested the code:
- Got UUID with all 3 types of search (UUID, project_shortname, project_title)
- Tested what happens when it doesn't exist (prints and exits)
- Downloaded a mtx file with project name
- Downloaded a loom file with project name

And it works fine. Currently talking with Pablo about what are the best next steps

**Comment by ESapenaVentura** [comment]
Since the next steps are on their end (even if we end up helping) should we move this ticket to done @clairerye ?

**Comment by ESapenaVentura** [comment]
Pablo said that this is ok and that they will test on their end and put the package in BioConda.

We are done on our side so moving to done

**Comment by clairerye** [comment]
thanks @mshadbolt and @ESapenaVentura for getting this done so efficiently!
