### ISSUE TITLE
New dataset: ComprehensiveTranscriptomicsHumanKidney

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#186]
**Dataset/group this task is for:**

ComprehensiveTranscriptomicsHumanKidney

**Wrangler responsible for this dataset/lab:**

Primary wrangler: Ami
Secondary Wrangler: Ray

File location

https://docs.google.com/spreadsheets/d/14qhg6tXRAC8H2lPJtjbO4BOUhga5nqCX/edit#gid=1719629469

**Acceptance criteria for the task:**

- [x] Convert metadata
 
- [x] Add ontologies

- [x] Assign secondary reviewer and make any necessary changes

- [x] Validate linking with graph validator

- [x]  Validate metadata: upload to ingest staging

- [x] Obtain cell type annotations and cellxgene matrix (either from publication supplements or by contacting the authors)

- [x] Complete submission: upload metadata and fastq files in ingest production

**Comment by rays22** [comment]
@ami-day 
I have reviewed the metadata spreadsheet `ComprehensiveTranscriptomicsHumanKidney_ontologies.xlsx`.
It looks like you did a nice job filling in the spreadsheet, but I still have found some issues.

1. The URL you provided is a link to the abstract of the paper and not the full text pre-print.
project.publications.url: https://europepmc.org/article/ppr/ppr21054

The link should be either
https://www.biorxiv.org/content/biorxiv/early/2017/12/21/238063.full.pdf
or
https://doi.org/10.1101/238063

2. Kidney donor 4 is not described in the pre-print text nor the supplements. Actually, they mention only 3 donors in the pre-print text. Is donor 4 a separate donor or could it be a separate kidney from the same donor? Have you asked the authors about donor 4 in the dataset?

```
isolate	Kidney4
age	66
biomaterial provider	UCHC Biorepository
sex	male
tissue	kidney

isolate	Kidney3
age	66
biomaterial provider	UCHC Biorepository
sex	male
tissue	kidney
```

3. Dissociation protocol

The sentence in
dissociation_protocol.protocol_core.protocol_description: `Cells were spun down and treated with ACK lysis buffer (A1049201, GIBCO) for 3 min on ice and washed with collection buffer.`
does not belong to the dissociation protocol.
The ACK lysis step is to remove red blood cells, therefore it should be part of an enrichment protocol.

4. Sequence files and associated processes look wrong.

Cell suspension `SRX3445567` has three fastq files (one read1 and two read2 files) associated with it, while cell suspension `SRX3445570` has only one fastq (read1 only) files.

```
FILE NAME (Required)    READ INDEX (Required)   INPUT CELL SUSPENSION ID (Required)
The name of the file.   The sequencing read this file represents.   A unique ID for the biomaterial.
Include the file extension in the file name. For example: R1.fastq.gz; codebook.json    If a sequencing experiment is single-end, enter 'read1'. For example: Should be one of: read1, read2, index1, index2   
sequence_file.file_core.file_name   sequence_file.read_index    cell_suspension.biomaterial_core.biomaterial_id
FILL OUT INFORMATION BELOW THIS ROW     
SRR6348585_1.fastq.gz   read1   SRX3445568
SRR6348585_2.fastq.gz   read2   SRX3445568
SRR6348586_1.fastq.gz   read1   SRX3445567
SRR6348586_2.fastq.gz   read2   SRX3445567
SRX3445570_1.fastq.gz   read1   SRX3445570
SRX3445570_2.fastq.gz   read2   SRX3445567
SRR6348584_1.fastq.gz   read1   SRX3445569
SRR6348584_2.fastq.gz   read2   SRX3445569

```

This explains why the spreadsheet also fails validation by the ingest-graph-validator:

```
20-12-14 19:02:45 [ingest_graph_validator.ingest_graph_validator] - INFO: using neo4j server at neo4j-server:7687
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - INFO: loading tests
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - INFO: loaded [19] test queries
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - INFO: running tests
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - ERROR: test [10x_has_more_than_2_files.adoc] failed: non-empty result.
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - ERROR: result: [{'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}]
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - ERROR: test [paired_end_2_files.adoc] failed: non-empty result.
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - ERROR: result: [{'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}, {'num_files': 1}]
20-12-14 19:02:45 [ingest_graph_validator.actions.test_action] - INFO: all tests finished 
```
You need to fix this problem.

**Comment by ami-day** [comment]
Thank you @rays22 , I will make the relevant changes

**Comment by ami-day** [comment]
@rays22 I have finished making changes so will upload it to ingest prod. now. 
I was also confused about the sample Kidney 4, because there is no donor 4 mentioned in the publication but the sample in SRA is labelled Kidney 4. I think you're right that 2 samples were taken from the same donor (Kidney donor 3).

**Comment by ami-day** [comment]
Waiting for ingest prod. to become available again (there is an error when ingest tries to access the schema)

**Comment by ami-day** [comment]
Successfully uploaded to ingest prod. Now converting to SCEA format with ID: E-HCAD-26.

**Comment by ami-day** [comment]
Closing because we have decided it is unsuitable. Both because the read lengths in the raw data were not correct initially, and then the raw data later seems to have been removed from NCBI/ENA. Also because the preprint was published in 2017, but a formal publication was never released.
