### ISSUE TITLE
Archive 1M immune cells

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#19]
This ticket will need input from the ingest dev team in order to facilitate archiving.

The most current spreadsheet is in the Brokering folder here:
https://drive.google.com/open?id=1wa3fDISO-fH-fevijZRpvLMAj381lZeQ

The data is in the DCP DSS

all files need conversion to BAM

It has a linked AUDR ticket here:

https://github.com/HumanCellAtlas/hca-data-wrangling/issues/356

but these issues should have been fixed in the latest version of the spreadsheet in preparation for the r-release.

Once the project is archived we would need to update the metadata to include accessions

**Comment by rays22** [comment]
Submission `179d98b2-1e4e-4685-bb28-7505f8a93e87` passes all the current **ingest-graph-validator** tests. It would fail the old test `10x_has_3-4_files.adoc` that has been removed from the current version of <https://github.com/ebi-ait/ingest-graph-validator/tree/master/graph_test_set>.

**Comment by rays22** [comment]
I am stuck at the point of transferring data files to Ingest s3.

**Comment by rays22** [comment]
I am stuck here:
1. What is the best place to look for the data files from DCP1 that I need to archive?
2. How do I transfer large datasets to Ingest-specified s3 areas without downloading and re-uploading them when local file storage is limited?

**Comment by rays22** [comment]
I am blocked here:
How do I transfer the fastq.gz data files from the HCA Data Storage System (DSS) S3 to the Ingest S3 upload area in bulk (S3 to S3)?
I have found a way to transfer files from DSS based on the file_UUIDs one-by-one, but I am wondering if there is a more efficient way to transfer all the files as a set based on the project UUID or some other collective identifier.

**Comment by aaclan-ebi** [comment]
There's no extra step needed here. When the archiver is ran using the file upload plan generated by the archiver, the downloading from DSS should be automatic.

**Comment by rays22** [comment]
Thanks @aaclan-ebi for confirming that.

**Comment by aaclan-ebi** [comment]
@rays22 to simplify the process of file uploading we can use the script from this ticket https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-dev-team/159

I think it'll be worth waiting for this one :)

**Comment by ESapenaVentura** [comment]
**Updates**:

- Ran the metadata archiver
- Ran the file archiver: 4 files left!
- DSP submission URL: https://submission.ebi.ac.uk/api/submissions/8f42a7b1-1e5d-469f-b1d6-7f23b5fa58c6

**Comment by aaclan-ebi** [comment]
I see 1M Innmune cells has accessions now :) https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?uuid=85e72912-9f91-4489-8169-3b43cc65a16a

**Comment by ESapenaVentura** [comment]
Oh great, maybe it just takes some time!

Next steps: 

- [ ] Make sure all the accessions have been written back to ingest
- [ ] Write the accessions back in the metadata spreadsheet

**Comment by ESapenaVentura** [comment]
Accessions have been written back to ingest and the metadata spreadsheet.

Closing the ticket.
