### ISSUE TITLE
Improve failed upload on move_data_from_indsc script

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#192]
Currently, some of the files being uploaded get truncated when using the move_data_from_insdc.py script

The plan is:
- Detect cases in which the upload has stopped
- Throw a warning and delete a file

In the future, it would be great if it could re-launch those files, but for now this should work so a wrangler can re-launch the script if any process fails.

**Comment by clairerye** [comment]
Moved to product dev repo https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/228
