### ISSUE TITLE
Review code review: new code for comparison and filtering of entries in nxn's database

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#194]
**Description of the task:**

I recently made updates to the code which compares and filters entries in Valentine's DB compared to the tracker sheet. This was to make the filtering process more stringent and avoid duplicate entries.
Enrique reviewed the code changes, refactored it and made a pull request. However, looking at the pull request, it looks like some of updated functionality might have been lost. This ticket is for me to review the changes to the code and either accept the pull request or reject it and make further changes.

Pull request: https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/191

**Acceptance criteria for the task:**

- [x] Review the new code changes and identify if there is missing functionality.

- [ ] Update the code so that it is working as expected, if needed, or else accept the pull request if no updates are required

- [ ] Update the tracking sheet SOP to reflect the new code changes

**Comment by ami-day** [comment]
@ESapenaVentura and I have had a discussion about the code and here is what we have decided to do today and on Monday:

**Today**

- @ESapenaVentura is going to merge the pull request for his refactored code for version 2 of the script (compare_tracker_with_nxn_sheet_version2.py)

- The refactored code is missing some of the functionality initially written in  compare_tracker_with_nxn_sheet_version2.py. @ESapenaVentura  is going to add them to the merged code and create another pull request. The updates will be:

1. Remove ChangedHeaders function
2. Updates to checking publication title duplication by identifying distance metric values above the defined threshold (>97%)

- @ESapenaVentura is also going to merge the 'remove_duplicates.py' script with this script, due to re-use of many of the functions while keeping the functions unique to remove_duplicates.py. A new argument will be added to the parser to allow for users to specify between adding new datasets from Valentine's DB and scanning the tracker for duplicates among all its rows. The 'Main()' code will not change, the relevant functions will be triggered by which argument is parsed.

**Monday** (separate ticket):

- The refactored code is missing some of the functionality initially written in  compare_tracker_with_nxn_sheet_version2.py. We will make updates to check duplication of accessions by accounting for multiple accessions (a list of accessions) in a single row in the tracker.

- We will review all the changes together and aim to merge all further changes by Monday afternoon.

**Comment by clairerye** [comment]
closing this ticket - further work on this will be tracked https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/227
