### ISSUE TITLE
Investigate possible deletion of rows in tracking sheet

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#199]
While working with the dataset tracking sheet, I noticed some rows were missing, at least for DCP1 datasets. We need to make a careful check to see if data is missing by comparing it with the backup

**Comment by lauraclarke** [comment]
I found 30 by comparing the publication URL column

https://pubmed.ncbi.nlm.nih.gov/30573816/
https://doi.org/10.1681/ASN.2018020125
https://www.biorxiv.org/content/10.1101/742320v1
https://www.ncbi.nlm.nih.gov/pubmed/31436334
https://doi.org/10.1186/s13059-017-1362-4
https://doi.org/10.1038/s41586-019-0933-9
https://pubmed.ncbi.nlm.nih.gov/30814735/
https://doi.org/10.1126/science.aao4174
https://doi.org/10.1101/467225
https://doi.org/10.1016/j.cmet.2016.08.020
https://pubmed.ncbi.nlm.nih.gov/28457750/
https://www.ncbi.nlm.nih.gov/pubmed/30518681
https://pubmed.ncbi.nlm.nih.gov/31160568/
https://www.biorxiv.org/content/10.1101/2020.04.03.024075v2.full
https://pubmed.ncbi.nlm.nih.gov/31320652/
https://pubmed.ncbi.nlm.nih.gov/29545397/
https://doi.org/10.1038/s41586-019-1506-7
https://www.biorxiv.org/content/10.1101/832444v1
https://doi.org/10.1101/753806
https://doi.org/10.1101/2020.03.22.002261
10.1016/j.cels.2020.06.004
https://www.ncbi.nlm.nih.gov/pubmed/31209336 ; https://www.biorxiv.org/content/10.1101/527408v1
https://doi.org/10.1126/science.aay3224
https://pubmed.ncbi.nlm.nih.gov/30257215/
https://doi.org/10.1101/742320
https://www.sciencedirect.com/science/article/pii/S1534580720300654
https://www.nature.com/articles/s41586-018-0394-6#citeas
https://doi.org/10.7150/thno.32734
https://www.ncbi.nlm.nih.gov/pubmed/30270042
https://www.biorxiv.org/content/10.1101/2019.12.21.884759v1

**Comment by ESapenaVentura** [comment]
I don't think this is needed anymore
