### ISSUE TITLE
How much HCA data can ingest not currently support (metadata and managed access?)

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#205]
The goal of this ticket is to quantify how much data could the ingest system currently not support.

The assumption is that there is a large quantity of data we can't support and there are two reasons we can't support it. This data was collected with requirements for managed access data distribution and/or the data is from a technology or sample type that our metadata schema doesn't currently support.

There are two main sources that we can use to quantify this.

The HCA publication list https://www.humancellatlas.org/publications/ 
Valentine Svennson's database https://docs.google.com/spreadsheets/d/1En7-UV0k0laDiIfjFkdn7dggyR7jIk3WH8QgXaMOZF0/edit?usp=sharing

Our existing data tracker should also be able to help with this assessment
https://docs.google.com/spreadsheets/u/1/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit?usp=drive_web&ouid=105690965550825472636

Assessing the HCA publication list is the top priority. An assessment of Valentine's database is a nice extra if there is time.

**For the HCA publication list. The quantification that we need are**

1. How many of the HCA publications refer to cellular resolution data generated for that study?
2. How many datasets can we either only partially support or not support at all(This is focused on the cellular resolution data in their papers rather than "all" data)
3. Why can't we support them? Is it because they are managed access, it is because they have used a technology that we don't support or both?

Some nice to have outcomes from this assessment include:

Ensuring all publications with data in the HCA list are listed in the HCA data tracker, there is a hca_pub column, if a dataset was added independent of the publication list, this might not be 100% accurate
Establishing a list of HCA publications which don't have data so they don't need to be reviewed again in future.
How many of the unsupported datasets are health primary tissue vs disease vs cell line/organoid etc

**For Valentine Svennson's database a similar set of questions**

1. How many human or human/mouse datasets are in Valentine's list which doesn't have the following technologies
Chromium, drop-seq, dronc-seq, smart-seq2, smarter, smarter (C1)
2. What is the distribution between RNA-seq and other measurements?
3. How many have archive accessions?
4. How many with archive accessions are in GEO or ArrayExpress 
5. How many are from EGA or dbGAP
6. What other accession styles exist?

This ticket will be complete when we have quantitative answers to each of these questions for the versions of the two datasets when the assessment started

**Comment by Wkt8** [comment]
Most recent statistics can be found here: https://docs.google.com/spreadsheets/d/1iYJl0oSA6qSudAwgL78sZb44Nvui9ZCU/edit#gid=1987761408
