### ISSUE TITLE
Revise AUDR SOP with new update/edit process

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#207]
As the new update process is under review we need to review this SOP with current process and ensure it is up to date.

**Comment by mshadbolt** [comment]
I have started editing the SOP and completely changed the name: https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/update_a_project_SOP.html

Still needs some filling out and need to come to agreement with wranglers on the right process as well as getting a better understanding of what is actually possible to do at the moment.

**Comment by lauraclarke** [comment]
@rays22 to update this based on he new process

**Comment by Wkt8** [comment]
I have updated this with our current process. There are some changes to the part on how we notify downstream components, based on a conversation happening in slack right now: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1613736665028000
