### ISSUE TITLE
Review metadata schema docs in repository

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#208]
**Description of the task:**
Review the docs under this folder https://github.com/HumanCellAtlas/metadata-schema/tree/master/docs and make sure they are up to date with the latest procedures.

**Acceptance criteria for the task:**
- [ ] All docs have been reviewed

**Comment by ESapenaVentura** [comment]
I have added the "externally blocked" label - Until we know the actual requirements on schema evolution we won't be able to identify which documents need updates

**Comment by ofanobilbao** [comment]
Has this moved at all? If not I would just add it to the stalled pipeline. It has never really even started, as I understand

**Comment by ESapenaVentura** [comment]
It has moved - there's a PR in the metadata schema repo, forgot to post it here https://github.com/HumanCellAtlas/metadata-schema/pull/1392

**Comment by ESapenaVentura** [comment]
Done - Merged to master and staging
