### ISSUE TITLE
HumanMousePancreas 

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#212]
**Dataset/group this task is for:**

HumanMousePancreas - f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc

https://data.humancellatlas.org/explore/projects/f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc?catalog=dcp2

https://contribute.data.humancellatlas.org/projects/detail?uuid=f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc

**Description of the task:**

Publication needs to be added to the project and exported 
https://pubmed.ncbi.nlm.nih.gov/27667365/

**Acceptance criteria for the task:**

- [x] publication added in ingest
- [ ] updated project metadata exported to DCP

**Comment by ami-day** [comment]
We need a @ebi-ait/ait-dev to change the status from Complete to Valid so the updated metadata can be re-submitted.

**Comment by clairerye** [comment]
@yusra-haider and this one please

**Comment by ofanobilbao** [comment]
@ami-day if I got it right, this has already been done by Yusra and it has been exported. The only remaining bit would be to send the import form, is that correct?

**Comment by ami-day** [comment]
Yes, done now.
