### ISSUE TITLE
Drop-seq, DroNc-seq, Fluidigm C1 Comparison

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#213]
**Dataset/group this task is for:**

Drop-seq, DroNc-seq, Fluidigm C1 Comparison - a9c022b4-c771-4468-b769-cabcf9738de3

https://data.humancellatlas.org/explore/projects/a9c022b4-c771-4468-b769-cabcf9738de3?catalog=dcp1

https://contribute.data.humancellatlas.org/projects/detail?uuid=a9c022b4-c771-4468-b769-cabcf9738de3

**Description of the task:**

Update the bioarxiv publication to the scientific reports publication

https://www.nature.com/articles/s41598-020-58327-6

**Acceptance criteria for the task:**

- [x] project updated in ingest
- [ ] project metadata exported to DCP

**Comment by ami-day** [comment]
We need one of @ebi-ait/ait-dev to switch the status from Complete to Valid to be able to re-submit the updated metadata only.

**Comment by clairerye** [comment]
@yusra-haider and this one please?

**Comment by ofanobilbao** [comment]
@ami-day if I got it right Yusra has already done this and the only thing left is to complete the import form. Is that correct?

**Comment by ami-day** [comment]
Yes, done now
