### ISSUE TITLE
Diabetic Nephropathy snRNA-seq

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#214]
**Dataset/group this task is for:**

Diabetic Nephropathy snRNA-seq - 577c946d-6de5-4b55-a854-cd3fde40bff2

https://data.humancellatlas.org/explore/projects/577c946d-6de5-4b55-a854-cd3fde40bff2?catalog=dcp2

https://contribute.data.humancellatlas.org/projects/detail?uuid=577c946d-6de5-4b55-a854-cd3fde40bff2

**Description of the task:**

Bioarxiv publication needs to be updated to peer-reviewed paper: https://www.pnas.org/content/116/39/19619
`pericardial effusion` updated to `pleural effusion`

**Acceptance criteria for the task:**

- [x] publication updated in ingest
- [ ] new metadata exported to DCP

**Comment by mshadbolt** [comment]
I also noticed that the ontology annotation for disease `pleural effusion` is incorrectly `pericardial effusion` so this should also be updated

**Comment by ami-day** [comment]
I was able to update the publication but it won't save this disease ontology update: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0002202
The initial incorrect ontology term has correctly been deleted however

**Comment by ami-day** [comment]
I am unable to re-export the edited project here: https://contribute.data.humancellatlas.org/projects/detail?uuid=577c946d-6de5-4b55-a854-cd3fde40bff2 Is this perhaps because the "Primary Wrangler" in the "Admin" tab is set to Marion?

**Comment by ami-day** [comment]
We need one of @ebi-ait/ait-dev to switch the status from Complete to Valid to be able to re-submit the updated metadata only.

**Comment by clairerye** [comment]
@yusra-haider are you able to manually set the status on this back?

**Comment by yusra-haider** [comment]
@clairerye, this one has already been re-exported

https://contribute.data.humancellatlas.org/submissions/detail?uuid=a69c731b-9db7-45e3-938f-daf2e4636a6e&project=577c946d-6de5-4b55-a854-cd3fde40bff2

this is the main ticket for tracking all these projects: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/347

**Comment by clairerye** [comment]
thank you!
