### ISSUE TITLE
figure out why two pancreas projects in ingest

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#216]
**Description of the task:**

This DCP1 project has two project entries in ingest:
https://contribute.data.humancellatlas.org/projects/detail?uuid=592a97ab-d575-4e91-b68e-547d1d66d087 
This one is in 'draft' status

https://contribute.data.humancellatlas.org/projects/detail?uuid=cddab57b-6868-4be4-806f-395ed9dd635a
this is the one that is exported to the DCP

**Acceptance criteria for the task:**

- [x] unneeded project is deleted from ingest

**Comment by ESapenaVentura** [comment]
The project with the draft submission - https://contribute.data.humancellatlas.org/projects/detail?uuid=592a97ab-d575-4e91-b68e-547d1d66d087 - Contains exactly the same data files and it does not seem to have been exported 

I think it's secure to delete the first one. It is not reflected in any downstream component or in the archives, so the UUIDs are not used anywhere

**Comment by lauraclarke** [comment]
@ESapenaVentura do you know who has power to delete this? can you do it?

**Comment by ESapenaVentura** [comment]
I can do it!

**Comment by ESapenaVentura** [comment]
I have deleted the extra project - Moved this to done
