### ISSUE TITLE
GSE150132: TCellsNeuroinflammation

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#219]
**Wrangler responsible for this dataset/lab:**

Primary: Ami

Secondary: Ray

**Description of the task:**

GSE150132: TCellsNeuroinflammation

~~https://docs.google.com/spreadsheets/d/1vDUU36zcg5h3eUQMqO3GajI8VEKDvuZ0/edit#gid=851060064~~

https://drive.google.com/drive/folders/1uN_y_rAfOpuynQ1sdhP1XJd69zst_HqV

**Acceptance criteria for the task:**

- [x] convert metadata

- [x] add ontologies

- [x] get secondary review and make necessary changes

- [x] validate with graph validator

- [x] upload to ingest prod. for validation

- [x] get cell type annotations and gene expression matrices

**Comment by rays22** [comment]
@ami-day  : The `ingest-graph-validator` reported some errors when I checked the spreadsheet, but all of them looked like false errors.
The metadata spreadsheet looks all right overall, but I have some questions below.

1. `Cell suspension` tab:
You have used the same `process.process_core.process_id` for all the five cell suspensions. I think they should be five separate processes even though they share the same protocol.
Using the same process IDs results in a strange experimental graph where biologically independent specimen converge on a single process that in turn outputs five independent cell suspensions: [exp_design_graph.svg](https://drive.google.com/file/d/10mZZgFnuC1n8U71Uhaud8yoNhsUYfbwx/view?usp=sharing) .
I think one process would have output one (combined) cell suspension. Is it really one process that would best model the experiment?

2. `Sequence file` tab:
The libraries are split across sequencing lanes, but the lane index fields (`sequence_file.lane_index`) are not filled in. If I remember correctly, I was told to fill them in similar cases, I think for the pipeline.

3. dissociation protocol?
I was told to add a dissociation protocol (dissociation method: blood draw) in the case of an earlier dataset where they studied peripheral blood cells. Blood is not a solid tissue, so I am not sure what the right approach is about adding or omitting a dissociation protocol in this case.

**Comment by ami-day** [comment]
Thanks @rays22! I'll make the above first 2 changes and upload to ingest. Regarding the 3rd point, I agree it's a little ambiguous but I prefer to leave this blank when blood samples are concerned, because it is not solid tissue and so is not dissociated.

**Comment by ami-day** [comment]
@rays22 I just realised the same process id in the cell suspension tab was intended, as they all underwent the same process. I'll message you on slack about this.

**Comment by rays22** [comment]
This dataset has been exported to the Terra staging area.

**Comment by ami-day** [comment]
Converting to scea format.
