### ISSUE TITLE
GSE116222: EpithelialDiversityHealthInflammation

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#220]
**Wrangler responsible for this dataset/lab:**

Primary: Ami

Secondary: Enrique

**Description of the task:**

GSE116222: EpithelialDiversityHealthInflammation

https://docs.google.com/spreadsheets/d/1vDUU36zcg5h3eUQMqO3GajI8VEKDvuZ0/edit#gid=851060064

**Acceptance criteria for the task:**

- [x] convert metadata 

- [x] add ontologies 

- [x] get secondary review and make necessary changes 

- [x] validate with graph validator 

- [x] upload to ingest prod. for validation 

- [x] get cell type annotations and gene expression matrices

**Comment by ESapenaVentura** [comment]
I'll add myself as a secondary wrangler as this dataset is under the MRC grant!

**Comment by lauraclarke** [comment]
@ami-day you should make sure you charge all the time you spent wrangling this dataset to the MRC cost centre, if you don't have access to it (42687) please say and we can sort it

**Comment by ESapenaVentura** [comment]
I have reviewed the dataset, overall looks great! Just a couple of things I've changed and bit I would like to discuss:

### Changes
**Project**
- Added their GH source code as a supplementary link
- Added link to PRIDE for their proteomics data in supplementary link

**Enrichment protocol**
- Changed text of method to `cell size selection method` (just for consistency)

### Discuss

**Specimen**
- Organ and organ part: I see that you included `colon` as the organ, and left the organ part alone. In the dataset I am wrangling, there are several parts of the digestive tract (and even within the colon). I thought about adding `digestive system` as the organ and `colon` as the organ part. What do you think about it?

**Cell suspension**
- Process: Why is the flow cytometry analysis indicated as a process? Wouldn’t it be part of the enrichment protocol?


I have saved the new spreadsheet in the folder with the addition of `_ES_review` to the filename

**Comment by lauraclarke** [comment]
@ami-day would it be possible for you to charge your work on this dataset to the MRC award in your timesheets?

**Comment by ami-day** [comment]
Thanks @ESapenaVentura for this review, I'll have a look at this tomorrow and get back to you

**Comment by rays22** [comment]
This dataset has been exported to the Terra staging area.

**Comment by ami-day** [comment]
Converting to SCEA.

**Comment by lauraclarke** [comment]
@ami-day will the SCEA submission for this project also need to be fixed?

**Comment by ami-day** [comment]
I'm not sure why it was moved to Finished before, I haven't finished converting it, think it still needed validation and then review by the SCEA team. I will also make the necessary changes to the idf and sdrf files.

**Comment by ami-day** [comment]
Submitted the metadata update in ingest, so I'm moving this ticket to the scea brokering column.

**Comment by lauraclarke** [comment]
Did you confirm it was successfully exported and did you complete the export SOP for it?

**Comment by lauraclarke** [comment]
https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/280 looks like there are still some export validation needed to confirm this is okay before completing the export SOP

**Comment by ami-day** [comment]
Status in ingest prod. is 'valid' not 'exported'. I think @aaclan-ebi and @MightyAx are still working on export of this since the updates to the metadata were made?

**Comment by lauraclarke** [comment]
@aaclan-ebi I think this is dependent on the work you are Alexie are doing to re-arrange existing files in the staging area in order to enable safe updates

Do you have a timeframe for this work being finished

**Comment by aaclan-ebi** [comment]
I just finished the script to fix this. Just waiting for 1 more PR approval and I plan to run the script and this resolved by eod. Apologies for the delay.

**Comment by aaclan-ebi** [comment]
Btw, Alexie has worked on a different fix which I believe wasn't blocking this ticket. The [fix](https://github.com/ebi-ait/dcp-ingest-central/issues/246) I was working on has now been applied. I asked @ami-day to confirm her updates and file the import request form to the Data Import team.

**Comment by ami-day** [comment]
@aaclan-ebi this project is in the 'valid' state currently, not exported. Is that how it should be? I guess I need to submit the metadata changes?

**Comment by ami-day** [comment]
Oh actually there are 2 projects, 1 has been exported https://contribute.data.humancellatlas.org/projects/detail?uuid=c893cb57-5c9f-4f26-9312-21b85be84313

**Comment by lauraclarke** [comment]
@ami-day are there two versions of this project in the ingest system? do you know which one to delete?

Do the one which is "correct" still need the fixes described in https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/280

**Comment by ami-day** [comment]
I deleted the project which was not the correct one (in the 'valid' state). The correct one was in the 'exported' state and is the one I updated and @aaclan-ebi  then fixed. I have submitted the import form for this dataset with a note that the metadata has been updated.

**Comment by ami-day** [comment]
Converting to SCEA format with E-HCAD-39

**Comment by ami-day** [comment]
This dataset has been exported but is missing some DNA content metadata for multiple records. This needs to be updated and re-exported. However it requires the ability to make bulk updates, so I am moving it to the stalled column for now.

**Comment by rays22** [comment]
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/220

**Comment by lauraclarke** [comment]
@rays22 you seem to have linked the ticket to itself, is there an ops board ticket you meant to link to?

**Comment by rays22** [comment]
> @rays22 you seem to have linked the ticket to itself, is there an ops board ticket you meant to link to?

Sorry about that. I think the relevant ops board ticket is this: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/280#issuecomment-832162128

**Comment by ami-day** [comment]
The original errors were corrected, but the dataset is still missing the file content text and ontology field (value: DNA sequence) in multiple rows (https://data.humancellatlas.org/explore/projects/c893cb57-5c9f-4f26-9312-21b85be84313/project-metadata)

**Comment by ami-day** [comment]
This update is blocked by our inability to make bulk updates.

**Comment by ofanobilbao** [comment]
@ami-day does the SCEA submission that you originally did need an update? Or this ticket can be closed?

**Comment by ami-day** [comment]
This can be closed, the SCEA files do not need to be updated.

**Comment by ESapenaVentura** [comment]
Re-opening to investigate this https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/554

**Comment by Wkt8** [comment]
Does not need any further changes. The data files are technically not inaccurate, simply not processed.
