### ISSUE TITLE
GSE157277,SRP279608: TCellsHumanCentralNervousSystem

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#221]
**Wrangler responsible for this dataset/lab:**

Primary: Ami

Secondary: Wei

**Description of the task:**

GSE157277,SRP279608: TCellsHumanCentralNervousSystem

https://docs.google.com/spreadsheets/d/1mvrU3S-cPkwR0yQfpgOnpC32xVACe0ct/edit#gid=212382820

**Acceptance criteria for the task:**

- [x] convert metadata

- [x] add ontologies

- [x] get secondary review and make necessary changes

- [x] validate with graph validator

- [x] upload to ingest prod. for validation

- [x] get cell type annotations and gene expression matrices

**Comment by Wkt8** [comment]
**Secondary Review**
Hi @ami-day - had some questions / discrepancies I noticed from looking through at the spreadsheet that I hoped you could answer! 

- In the Project - Contributors tab, you've added email addresses to the Phone number column

- In the Specimen from Organism tab: I was looking for the information for Post-Mortem Interval (43200) but couldn't find it attached to the paper anywhere. I probably missed it, but where did the information come from? 

- In the Enrichment protocols tab, the minimum and maximum sizes for enrichment_protocol_size_selection are the same (35um). Shouldn't the maximum be 35um, but the minimum be 0?

- In the Sequence File tabs, each individual cell suspension has a different process. Is there any process metadata linked with the process, or is it just for differentiating the separate uses of the protocol?

Apart from that it looks really good :)

**Comment by ami-day** [comment]
Have had a chat with @Wkt8 and will make the necessary changes, then upload to ingest.

**Comment by rays22** [comment]
This dataset has been exported to the Terra staging area.

**Comment by ami-day** [comment]
Converting to SCEA.

**Comment by lauraclarke** [comment]
@ami-day https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/286 can you confirm when this is resolve and the Export SOP for updates has been followed for it

**Comment by ami-day** [comment]
Export form submitted.

**Comment by ami-day** [comment]
Re-submitted SCEA format version to Gitlab following update and review.

**Comment by ami-day** [comment]
merge request: https://gitlab.ebi.ac.uk/ebi-gene-expression/scxa-metadata/-/merge_requests/110 waiting for SCEA team to review

**Comment by ofanobilbao** [comment]
@ami-day I have moved this to Finish on the wrangling board and put it in the Review/QA column in the SCEA board. I believe that the DCP journey is finished. But please, feel free to amend if I did not get it right. Thanks!
