### ISSUE TITLE
What needs to be prepared to enable metadata updates?

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#224]
**Description of the task:**

As described in the [evolving the schema](https://docs.google.com/document/d/1Z4dJJrcgWRMRAdb4dXY9mTjU4EacUUmeH9PmS481rHY/edit?ts=5ffec395#) document, we are currently working on a method to enable to update the HCA metadata schema while causing minimal disruption.

In order to enable this, a list of preparation tasks should be mentioned in the ticket, with links to the actual tickets in the [metadata-schema](https://github.com/HumanCellAtlas/metadata-schema) repository. 
 
- [ ] Prepare documentation
- [ ] Review scripts used for linting/checking schemas
- [ ] Github repository with the structure of the staging area

This list will get updated as I go through the proposed process.

**Acceptance criteria for the task:**
- [ ] All tasks have been listed above
- [ ] All tasks have a ticket in the metadata-schema repository

**Comment by lauraclarke** [comment]
@ESapenaVentura I am closing this ticket as I am assuming it has been superseded by product development tickets
