### ISSUE TITLE
SRR8703773, syn22213200: Nuclei multiplexing with barcoded antibodies for single-nucleus genomics

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#228]
This is a HCA publication which seems to be a proof-of-new-technique type of paper. May require metadata schema evolution for capturing nucleus hashing data. 

**Primary Wrangler:**
Wei

**Secondary Wrangler:**
Ami

In ingest here: https://contribute.data.humancellatlas.org/submissions/detail?id=60d09d61e259f0766126379c&project=dc1a41f6-9e09-42a6-959e-3be23db6da56

**Associated files:**

Google Drive:
https://drive.google.com/open?id=1vVQJon-IBKhQnDIaltaHtFRFz3LftI0E&authuser=mshadbolt%40ebi.ac.uk&usp=drive_fs

**Published study links**
Paper: https://www.nature.com/articles/s41467-019-10756-2 

Accessioned data:
https://www.synapse.org/#!Synapse:syn22213200
https://www.ncbi.nlm.nih.gov/sra/?term=SRR8703773
https://www.ncbi.nlm.nih.gov/sra/?term=SRR8703774

portal link: https://portals.broadinstitute.org/single_cell/study/SCP377/experiment-2-mouse-pbs

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [x] Transfer files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production

**Comment by mshadbolt** [comment]
The human part of this project is managed access through the AMP-AD Knowledge portal, so we will most likely need to skip raw data for these samples.

**Comment by mshadbolt** [comment]
emailed corresponding authors to clarify experimental structure and ask a few questions.

**Comment by mshadbolt** [comment]
I have requested the mouse fastqs via cloud delivery 
Matrices and metadata containing cell type annotations are available via the various SCP accessions that are listed in the paper.

**Comment by mshadbolt** [comment]
fastqs for mouse samples are in hca-util upload area.

**Comment by mshadbolt** [comment]
I don't think this is worth progressing until we are able to submit projects without raw sequencing files. Will move to stalled

**Comment by ami-day** [comment]
This can be curated without the raw sequencing files so it's not longer blocked.

**Comment by Wkt8** [comment]
Starting to have a look at this - I think we'll be able to export this for this milestone.

**Comment by Wkt8** [comment]
This is ready for secondary review. I'd particularly want someone to look at ontologies for the Analysis_Protocol and Analysis_File tabs!

**Comment by ami-day** [comment]
Hi @Wkt8 it all mostly looks good, just some small changes may be needed listed below:

Donor organism tab:
- no age unit ontology
- no developmental stage, this can be added based on their age in years
- no genus species ontology
- maybe check all the ontology fields have been added?
- could add the mouse strain: C57BL/6J mice

Specimen from organism tab
- missing ontologies e.g. organ, species

Dissociation protocol
- I corrected some minor typos

Cell suspension tab
- I think maybe this field also should have a double pipe? NCBITaxon:10090; NCBITaxon:9606
- There is a BioSamples accession for only 1 cell suspension. Is this correct? Why would they only assign 1 of the pooled samples a BioSample accession?

Library preparation protocol
- Are we able to validate multiple library constructions methods? it looks good how it is done but I thought we needed to update the schema to enable this?

Analysis protocol & Analysis file tabs
- I would split the analysis protocols into 2: 1 for the expression matrix and associated files and another for the PCA analyses files. The method description would need to be split too following the generation of the expression matrices and before the dimensionality reduction and differential gene expression analyses.
- PCA and t-SNE are dimensionality reduction methods, they are not differential expression analyses methods. So while they perform both, the protocol type associated with the pca coordinates and t-SNE files should be "dimensionality reduction" if it is available.
- Are the experimental metadata files needed? if the info. is all in the HCA metadata tabs I think I wouldn't add it. Unless you think it adds something I am not aware of?

**Comment by Wkt8** [comment]
Have made the changes you recommended. This will require an update for analysis_file ontologies. 
There is only a BioSamples accession for only 1 cell suspension because that was the only one that was utilised for snRNA-seq. All of the sequence files were derived from that 1 cell suspension.

**Comment by Wkt8** [comment]
Submitted to production! This does need an update though.

**Comment by Wkt8** [comment]
Also needs an update to include sequencing and library preparation protocols to be linked to the analysis_files.

**Comment by Wkt8** [comment]
@idazucchi is this the one blocked by unable to download an up-to-date spreadsheet?

**Comment by idazucchi** [comment]
I'm still unable to download the spreadsheet and do a bulk update, but I've prepared the information that need to be updated on the old spreadsheet available in Drive

**Comment by jacobwindsor** [comment]
@idazucchi I think youre unblocked now right?

**Comment by idazucchi** [comment]
All updates are done apart from the linking for process `exp2_dimensionality_reduction` which has sequence files as input for analysis files.
This update:
- can't be done from the ui
- requires further discussion on what we want to use as input for analysis files: sequence files or cell suspension?


To do:
- [ ] discuss the analysis file input in the next Wrangler call (11/2/2022)
- [ ] link input for `exp2_dimensionality_reduction` 
- [ ] validate
- [ ] export

**Comment by Wkt8** [comment]
We discussed with UCSC wranglers that we want to use cell suspensions as the input for analysis files.

**Comment by idazucchi** [comment]
The updates required to modify the project's linking so before exporting @Alegria and I are checking with the Data Import team and Azul team to make sure that they can process the updates

**Comment by idazucchi** [comment]
the project was successfully re-indexed in dev, I've completed the import request for prod
