### ISSUE TITLE
SCP846: Myocyte Specific Upregulation of ACE2 in Cardiovascular Disease: Implications for SARS-CoV-2 mediated myocarditis

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#229]
Email was previously sent out as in (https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/54) but received no reply. Should try and get in touch with the corresponding author about location and consent of raw data, as raw data is not in the paper. 

**Primary Wrangler:**

**Secondary Wrangler:**

**Associated files:**

Google Drive:

**Published study links**

Paper: https://www.medrxiv.org/content/10.1101/2020.04.09.20059204v1
Accessioned data: https://singlecell.broadinstitute.org/single_cell/study/SCP846/myocyte-specific-upregulation-of-ace2-expression-in-cardiovascular-disease-implications-for-sars-cov-2-mediated-myocarditis#study-summary 

**Key Events**

- [ ] convert published metadata to HCA spreadsheet
- [ ] manually curate dataset to meet HCA metadata standard
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production

**Comment by ami-day** [comment]
It seems there is no raw data or gene expression matrix made available for this study. They have made the expression levels of few specific genes available in the single cell portal. Moving this to stalled and will email the corresponding author to ask about the raw data / matrices.

**Comment by ami-day** [comment]
Closing this ticket as there is no raw fastq data or gene expression matrices.
