### ISSUE TITLE
CNP0000325, GSE134355: Construction of a human cell landscape at single-cell level (HCA Publication) 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#230]
**Primary Wrangler:**
Ami

**Secondary Wrangler:**

**Associated files:**

Google Drive: https://docs.google.com/spreadsheets/d/1PEpUcm0C8xWTKv_DIrXhwPluuxC6KjuW/edit#gid=37156403

**Published study links**

Paper: https://www.nature.com/articles/s41586-020-2157-4#data-availability 

Accessioned data:  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE134355
https://db.cngb.org/search/project/CNP0000325/

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production

**Comment by ami-day** [comment]
This is a UCSC dataset so I am closing this ticket.

**Comment by lauraclarke** [comment]
@ami-day It would be good to know more about why UCSC decided to leave it, what were the issues they found? We should record this reason in the data tracker so we can report if required

**Comment by ami-day** [comment]
Hi @lauraclarke I'm not sure that they did decide to leave it? It looks like a pretty good dataset. There were no issues found. Microwell technology was used which cannot be processed by pipelines but we can still curate the metadata.

**Comment by lauraclarke** [comment]
@ami-day did you ever follow up on this?

**Comment by lauraclarke** [comment]
Need to follow up on details with UCSC on this

**Comment by ami-day** [comment]
Followed up with UCSC, they identified it as not adequate quality due to raw data. Agreed I would look into the data, see if we find any problems, and if not, will curate it on our side.

**Comment by ami-day** [comment]
I don't see an issue currently with this dataset, and in the publication they state it is an HCA paper and that the PI is part of the HCA project, so I've started curating it

**Comment by ami-day** [comment]
This is stalled for now.

1. I have requested an new ontology term for Microwell-Seq as a scRNA-Seq library construction method in HCAO (https://github.com/HumanCellAtlas/ontology/issues/83)
2. The authors have not provided the links between BioSample Accessions and the Donor ids in their GEO metadata submission and publication supplements. There are multiple BioSamples per Donor id in many cases and we need this linking info. Have emailed the authors this morning.

**Comment by ami-day** [comment]
The author got back and I have asked them additional questions, so I am waiting to hear back again. The new ontology term request is in progress.

**Comment by ami-day** [comment]
The new ontology term for Microwell-Seq as a scRNA-Seq library construction method in HCAO is expected to be available from Tuesday 18th May

**Comment by ami-day** [comment]
Waiting to hear back from author - they sent me an email but forgot to attach the mentioned files.

**Comment by ami-day** [comment]
-Waiting to hear back again this time about technology barcode specifics.
-Error downloading fastq from ENA even though they are available. Discussing with Eugene in ENA team.

**Comment by ami-day** [comment]
the data is transferring a to hca-util area

**Comment by ami-day** [comment]
To ask:
- what is the model organ for iPSC differentiation
- cord and blood samples: clarify from which samples CD34+ cells were enriched

**Comment by lauraclarke** [comment]
@ami-day quick question, I know on slack we were talking about urine as the source of cells, that isn't the model organ though, that is the organ the cells came from (I guess bladder in that case), where they differentiated? in which case what into as that is the model organ?

**Comment by ami-day** [comment]
I have cleared the milestone as we are waiting to hear back about some required metadata to be able to move forward.

**Comment by ami-day** [comment]
> @ami-day quick question, I know on slack we were talking about urine as the source of cells, that isn't the model organ though, that is the organ the cells came from (I guess bladder in that case), where they differentiated? in which case what into as that is the model organ?

Hi @lauraclarke I already put the model organ as pancreas for iPSCs or Embryoid Body for the hESCs. The organ I entered in the "specimen from organism" tab is uterus (iPSC) and embryo (hESC) as this is from where they were derived, and so the specimen_from_organism in this case is linked to the cell lines in the cell line tab as the specimen id.

**Comment by ami-day** [comment]
Barcode information from authors:

1.     Microwell-Seq is a 3' end tag/bias method.

2.     Cell barcode in Microwell-Seq bead is 18bp(3X6bp).

3.     UMI barcode in Microwell-Seq bead is 6bp.

4.     Cell barcode offset in Microwell-Seq sequencing read1

BASE_RANGE=1-6:22-27:43-48

5.     UMI offset in Microwell-Seq sequencing read1

BASE_RANGE=49-54

6.     The cell barcode and umi barcode are on read1, they are on the same read

 

bead-conjugated oligo:

5-TTTAGGGATAACAGGGTAATAAGCAGTGGTATCAACGCAGAGTACGT[6bp cell barcode part1]CGACTCACTACAGGG[6bp cell barcode part2]TCGGTGACACGATCG[6bp cell barcode part3] [6bp UMI] (T)30VN-3’

**Comment by ami-day** [comment]
Now I have asked them about the model organ and which are the CD34+ enriched samples. They are probably starting to think I am very annoying...

**Comment by ami-day** [comment]
Other answers:

1. We cultured the Embryoid Body for random, it didn't have any specific target organs. Besides, EB9, EB18 and EB20 are embryoid body derived from hiPSCs instead of hESC.
2. In the method, it states" CD34 + cord blood and CD34 + mPB were enriched using a human CD34 selection kit (StemCell Technologies)." We just enrich CD34+ for umbilical cord blood in two batches:Cord Blood1 (CD34+) and Cord Blood1 (CD34+). And CD34+ mPB is just for CD34 + mobilized peripheral blood and the data is from another paper in our lab: “Comparative transcriptomic analysis of hematopoietic system between human and mouse by Microwell-seq”. No fluorescence-activated cell sorting (FACS) step was used in other HCL experiments.

**Comment by ami-day** [comment]
Updated the metadata based on the author's response. However I need to update the HCA metadata schema to allow for multiple barcode offset ranges to reflect the above oligo structure.

**Comment by ami-day** [comment]
Blocked as waiting to be able to make additional metadata schema updates. I need to be able to change the allowed barcode length and offset format.

**Comment by ami-day** [comment]
The latest library_preparation_protocol schema is here: https://schema.humancellatlas.org/module/process/sequencing/5.2.6/barcode The umi and cell barcode offset and length value types have not yet been updated to enable a range in values.

**Comment by ofanobilbao** [comment]
I have added details in Ingest, and Ami had already linked the ticket. So closing this ticket for now
