### ISSUE TITLE
E-MTAB-8498: Re-evaluation of human BDCA-2+ DC during acute sterile skin inflammation (HCA Publication) 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#231]
**Primary Wrangler:**
Ami

**Secondary Wrangler:**
Wei

**Associated files:**

Google Drive: https://docs.google.com/spreadsheets/d/1ko6Ia2L3pFSRZs6149JgPCSzWOKVDBsB/edit#gid=1476656329

**Published study links**

Paper: https://rupress.org/jem/article/217/3/e20190811/132796/Re-evaluation-of-human-BDCA-2-DC-during-acute

Accessioned data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE139952

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production

**Comment by ami-day** [comment]
Contacted the authors as there is no information about sample donors.

**Comment by ami-day** [comment]
Have emailed the authors again including more contacts

**Comment by ami-day** [comment]
Metadata done and validated in ingest staging (except file names not yet added). Getting an error uploading the fastq files to hca-util, not sure why. Have messaged Enrique about it.

**Comment by Wkt8** [comment]
Secondary Review: 
Project Tab:
Should include the ArrayExpress Accession: E-MTAB-8498 

Donor tab: 
Seems very odd that there is only one donor for the specimens, especially since the paper explicitly references ‘donors’ multiple times, and once even says ‘pooled from 6 - 9 donors’. I know you already reached out to them directly, but this is **really** strange. Could they have misunderstood what you were asking for? 

Library preparation protocol tab: add the Picellie et al., publication DOI to the publication DOI column? 
10.1038/nprot.2014.006 

Sequencing Protocol:  
I was a bit confused with the sequencing protocol, as the .idrf file in Array Express, states the libraries were sequenced using either the Illumina HiSeq 2500 and Illumina HiSeq 2000. The sequencing protocol in the spreadsheet says Illumina Mi-Seq was used, but I think that was used for the targeted skin RNA seq, not the single-cell RNA seq? 

It might be a good idea to reach out to contributors to check whether the HiSeq 2500, HiSeq 2000 or HiSeq 4000 (in the .idrf file they label the protocol with a HiSeq 4000) was used and for which samples. 

Sequence Files
Some of the sequence files do not have library protocols or sequencing protocols attached to them, but some of them do! Was there a specific reason for this? 

The publication states that the scRNA-seq data is available on the E-MTAB-8498 ArrayExpress submission, but the processed data is not available there, might be good to contact the authors for this?

**Comment by ami-day** [comment]
Thanks @Wkt8 I have emailed the authors to clarify again. I had taken their word for it the last time I asked, I think sometimes they reference multiple donors/samples in the publication but then add data for fewer samples due to quality concerns. Let's see what they say! The other points all look good, will make the changes.

**Comment by ami-day** [comment]
Wei and I decided to remove the May 24th milestone and have discussed with Claire too, as we're not convinced of the donor metadata and wanted to reach back out to the authors.

**Comment by ami-day** [comment]
I take it back, the author just got back 💃🏻

**Comment by ami-day** [comment]
I am having issues downloading the raw data files from ENA. It is a problem on the ENA server side. I have message Eugene about this.

**Comment by ami-day** [comment]
Requested NCBI cloud delivery of data. It can only be delivered in SRA object format so I will need to convert it to fastq.

**Comment by ami-day** [comment]
Currently exporting: https://contribute.data.humancellatlas.org/submissions/detail?uuid=fe536fd5-3343-462a-8026-42b2fccb5367&project=67a3de09-45b9-49c3-a068-ff4665daa50e

**Comment by ami-day** [comment]
Exported and submitted import form.
