### ISSUE TITLE
What changes do we need to define distinct library preparations?

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#237]
Related to #187

Based on the discussion [here](https://docs.google.com/document/d/1TMQFXnGThhnpBRMdHHgY0UZ7Dx1oxQ1PuFmrZAW01Mg/edit#), one of the key points was that we need to distinguish between the purpose of different library preparations.

Putting as an example CITE-SEQ, library preparations can contain information for different things: Gene expression, Antibody-derived Tags (ADT) and HTO (HashTag Oligos). These can be usually distinguished by the filename, but doing so is bad practice.

At the meeting, we discussed 2 options:

1. Use the `content description` field in `sequence_file` to indicate the different contents that each library has
1. Add a new, optional field to describe the type of library in `sequence_file`

We need to expand on this and discuss the ideas.

**ACCEPTANCE CRITERIA**:
- [ ] Options are discussed and reviewed with pros/cons
- [ ] An option is chosen
- [ ] A metadata ticket is opened

**Comment by ofanobilbao** [comment]
Could someone again add the reason why this was moved to In Progress? There is nothing recorded here at the minute. @ami-day @ESapenaVentura @Wkt8 @rays22 . Thanks!

**Comment by ami-day** [comment]
It was moved because we haven't yet finalised and documented how to fill the metadata for the various library preparation methods that are not standard like 10X, smart-seq2. We agreed I would create an SOP for this.

**Comment by Wkt8** [comment]
This will be the spatial transcriptomics document that ami is working on

**Comment by Wkt8** [comment]
@ami-day to put a link to the spatial transcriptomics document here.

**Comment by aaclan-ebi** [comment]
@ami-day is working on this.

**Comment by ESapenaVentura** [comment]
I need to review it further but overall it looked ok, I think I would just suggest to group technologies and/or order them alphabetically to make them easier to find

**Comment by ami-day** [comment]
Linked to pull requests.

**Comment by ami-day** [comment]
I am going to create a metadata schema update ticket for the above "Add a new, optional field to describe the type of library in sequence_file". Once the schema change is made, we should update the curation guidelines to include this info.

**Comment by ami-day** [comment]
> I need to review it further but overall it looked ok, I think I would just suggest to group technologies and/or order them alphabetically to make them easier to find

Thanks for the feedback @ESapenaVentura , I have grouped and reordered the technologies. Alphabetical order is applied within the groups.

**Comment by ESapenaVentura** [comment]
Reviewed

**Comment by ofanobilbao** [comment]
Ami to address comments

**Comment by ESapenaVentura** [comment]
https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/415 this is the PR
