### ISSUE TITLE
Discuss ontology term used for CITE-SEQ data

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#238]
**Description of the task:**
Related to #187 and the conclusions of a discussion meeting (Notes [here](https://docs.google.com/document/d/1TMQFXnGThhnpBRMdHHgY0UZ7Dx1oxQ1PuFmrZAW01Mg/edit#)

We need to discuss what ontology would we use for CITE-SEQ data. In the meeting, 2 options arose:
1. Use the CITE-SEQ ontology term in the method.
2. Use a more general term (e.g. Surface protein assay) and add "CITE-SEQ" in the description

**Acceptance criteria for the task:**
- [ ] Options are reviewed and discussed
- [ ] An option is decided
- [ ] Actions are taken for that option

**Comment by ESapenaVentura** [comment]
This still needs to be discussed - I guess we can move it to "To Do"

**Comment by rays22** [comment]
We have a meeting on 1/4/2021 with SCEA curators and ontologists to discuss ontology term options in EFO for CITE-seq (feature barcode) technologies.

**Comment by ami-day** [comment]
I am closing this ticket as Enrique has recorded the outcome of this discussion in another ticket.
