### ISSUE TITLE
MultipleSclerosisLineageDiversity

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#243]
**Dataset/group this task is for:**

MultipleSclerosisLineageDiversity
https://docs.google.com/spreadsheets/d/1cjAbPo_5Ie_yT9a7wfmDFGA9G13xUyLY/edit#gid=1330482754
https://contribute.data.humancellatlas.org/submissions/detail?uuid=a91a7a21-4443-481d-8466-9282a401c5cf

**Wrangler responsible for this dataset/lab:**

Ami

**Acceptance criteria for the task:**

- [x] fill metadata
- [x]  add ontologies
- [x]  validate with graph validator
- [x]  validate in ingest staging
- [x]  secondary review
- [x]  upload to ingest prod.
- [x]  upload raw data to ingest prod.

**Comment by Wkt8** [comment]
Adding myself as secondary reviewer.

**Comment by Wkt8** [comment]
Have finished with the secondary review: the entities in the different spreadsheets match up, and are linked. There are just two things:
- I did not manage to check whether the files in the s3 upload bucket match up to the files in the spreadsheet, but have spoken to @ami-day about this, we normally sync the files to the s3 upload bucket after finishing the secondary review to avoid having to resubmit a spreadsheet and re-sync the files in case of any changes
- There are a couple optional fields (e.g. read length in sequence files) which could be filled in, but i'm not quite sure if that is that useful / possible to do in an efficient way! 

Apart from that everything looks great!

**Comment by ami-day** [comment]
Hi @Wkt8, I usually don't fill in the read lengths or checksums. I'm going to upload the fastq files so it's ready for export. Thank you!

**Comment by ami-day** [comment]
- [ ] Need to check for cell type annotations
- [ ] Need to check for gene expression matrix
- [ ] If any of above 2 missing, need to email authors

**Comment by ami-day** [comment]
Obtained gene expression matrix from GEO. Emailed authors about cell type annotations.

**Comment by ami-day** [comment]
Validating data files: check validity later today.

**Comment by ami-day** [comment]
Check syncing - 2 files invalid

**Comment by ami-day** [comment]
All data is now valid.

**Comment by rays22** [comment]
This project was exported for HCA Data Portal release 4 on 2021-03-19.

**Comment by ami-day** [comment]
Converted with scea id: E-HCAD-35
