### ISSUE TITLE
ImmuneCellExhaustianHIV

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#245]
**Dataset/group this task is for:**

ImmuneCellExhaustianHIV
https://docs.google.com/spreadsheets/d/1hM8lEwC8yhJ6auiHV0ixFdXrJms2PeaX/edit#gid=541030374
https://contribute.data.humancellatlas.org/submissions/detail?id=601985b3ac1792031eee0bdf

**Wrangler responsible for this dataset/lab:**
Ami
** Secondary wrangler **
Ray

**Acceptance criteria for the task:**

- [x]  fill metadata
- [x]  add ontologies
- [x]  validate with graph validator
- [x]  validate in ingest staging
- [x]  secondary review
- [x]  upload to ingest prod.
- [x]  upload raw data to ingest prod.

**Comment by rays22** [comment]
## Secondary review
### Minor issues:
* Project - Contributors
    * Please, add the ORCID ID `0000-0001-5614-030X` for Maile Ann Young,,Karris
* Project - Publications
    * `project.publications.url` : I would use a direct link to the publication (`https://doi.org/10.1080/22221751.2020.1826361`) instead of the link to the PubMed abstract.

### More serious issue
* Sequence files
I am not sure if the fastq files are grouped correctly by the process.process_core.process_id fields. I think you need to add lane indeces.
I would like to get a second opinion on this from the other wranglers.

**Comment by mshadbolt** [comment]
hi both
@rays22 is correct, if you have more than one set of fastq files within a single process_id, they need to be given lane indices. 

So for example, if there are 24 files that are assigned one process_id, we are saying all of these came from the same library, then each fastq file pair needs to be assigned a lane index to ensure they are paired correctly by pipelines, so you would need to number them 1-12, or 1-20 for those that have 40 files.

I think it would be good to add a test for this in the ingest-graph-validator if there isn't one already.

**Comment by mshadbolt** [comment]
I looked up the ingest-graph-validator and there is a test `ensure_lane_index`, that is supposed to catch this error, @ami-day can you confirm whether it failed this test?

**Comment by ami-day** [comment]
Thanks @mshadbolt and @rays22, making those changes now.

**Comment by ami-day** [comment]
I think I ignored that graph validator error, because I thought it meant it was more of a general warning that I hadn't adding lane indices, and should check if they are present in the file names (i.e. didn't realise the test checked for specific use cases). Because the fastq files didn't have lane indices, I got confused and thought it wasn't relevant.

**Comment by ami-day** [comment]
I also thought that if there are separate run accessions for the same cell suspension, then that is enough info. to distinguish them.

**Comment by lauraclarke** [comment]
I thought the lane id was essential if there where multiple sequencing files in the same library but otherwise not vital, is that true?

**Comment by ami-day** [comment]
Validates in ingest. Transferring the raw data to hca-util upload area.

**Comment by ami-day** [comment]
Downloading files to hca-util upload area.

**Comment by rays22** [comment]
This project was exported for HCA Data Portal release 4 on 2021-03-19.

**Comment by ami-day** [comment]
Converted with scea id: E-HCAD-37

**Comment by ESapenaVentura** [comment]
This dataset does not have a data curator (@ami-day you're appearing as a contributor) https://data.humancellatlas.org/explore/projects/0fd8f918-62d6-4b8b-ac35-4c53dd601f71

We need to update the metadata

**Comment by ami-day** [comment]
Oh no! definitely need to update that. Thanks @ESapenaVentura for checking it
