### ISSUE TITLE
Update list of users in repository documentation

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#25]
**Description of the task:**
The documentation for this repository and the HCA metadata repository needs to be updated to reflect the changes in the composition of the teams/delegation of tasks moving to DCP2. 

Please discuss below if delegations are not clear.

List of documents that need updating:

- [EBI onboarding document](https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/docs/ebi-wrangler-onboarding.md): Wranglers currently working at the HCA DCP 2.0

- [Pullapprove config file](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L30-L35): People mentioned in DCP schema and groups

- [Snyk updates SOP](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/snyk_security_updates.md): People allowed to make changes 

**Acceptance criteria for the task:**

- [ ] A list of the changes for each document is posted in the ticket
- [ ] Changes are made in each document

**Comment by ESapenaVentura** [comment]
Please feel free to add more documents if I'm forgetting anything.

I haven't added the HCA/wrangling-repo documents that have not been transferred yet to this repository as we don't yet know what we will be transfering.

**Comment by mshadbolt** [comment]
I already updated the onboarding doc.

**Comment by lauraclarke** [comment]
@ESapenaVentura Did this get done? Does it need to be done?

**Comment by ESapenaVentura** [comment]
Pullapprove is also done, it's just sitting in dev until we start releasing to prod

Snyk still needs changes, will open a quick PR for that

**Comment by lauraclarke** [comment]
Are there other things in dev which would prevent the release of the pull approve?
