### ISSUE TITLE
Organoid pilot dataset: Oli stegle, Jeongbin, Anna

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#252]
We are using their brain and organoid projects as a pilot to address how we curate and obtain mixed open/managed access and more complex organoid project experimental designs. We have met with Oli, Jeongbin and Anna. I (Ami) am now exploring their data via the links and accessions they sent me.

**Acceptance criteria**

- [ ] Get all their metadata and raw data into HCA ingest and/or archives in correct format. Provide them with accessions if needed.

**Comment by lauraclarke** [comment]
@ami-day I am confused as to why this isn't a standard new project data ticket? is there something different about Anna's data that isn't suited to that?

**Comment by ami-day** [comment]
> @ami-day I am confused as to why this isn't a standard new project data ticket? is there something different about Anna's data that isn't suited to that?

I think because I wasn't sure exactly what this task would involve, whether it would involve more than our standard curation process. But I will move it to the data wrangling board.
