### ISSUE TITLE
Talk with BioStudies about metadata missing from submission

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#26]
**Description of the task:**
As a Data Wrangler that is using DSP to submit curated datasets, I would like that all the possible metadata about the article a dataset might relate to display properly in BioStudies.

A good example is here: https://www.ebi.ac.uk/biostudies/studies/S-SUBS3

The metadata only displays authors, Issue number, issue year and volume. We also sent information about the DOI, article title, and journal information.

This metadata was sent correctly, looking at the `.json` version of the submission, but it doesn't display. I would like to talk to BioStudies to know what is going on and how to resolve it.

**Acceptance criteria for the task:**

- [x] A proper communication channel is decided
- [x] A message is sent asking for help in this matter.
- [ ] A follow-up decision is made based on their answer.

**Comment by lauraclarke** [comment]
@ESapenaVentura were you able to pin down if this was a issue with BioStudies or with DSP?

**Comment by ESapenaVentura** [comment]
I haven't worked on this issue, so no.

I will open a ticket later in BioStudies addressing this and they can confirm on which end the problem is.

**Comment by ESapenaVentura** [comment]
They just answered to the ticket:
>Hi Enrique,
>
>Thank you for bringing this to our attention. The missing information is
probably due to how links are provided in the publication section. We are
working towards fixing the current submissions at our side and will get back
to you soon.
>
>Best,
>
>Awais

I'll wait until they know what is going on. They didn't give a timeline so this might take a while, hopefully we have something before the next sprint ends!
