### ISSUE TITLE
Check adhoc updates won't be overwritten by updates

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#260]
**Description of the task:**
For the DCP2 MVP, we did a couple of ad-hoc updates directly into the staging area to avoid data transfer errors

We need to make sure these updates are reflected in the spreadsheet/ingest so they don't get overwritten if we make updates to a project

**Acceptance criteria for the task:**
- [x] Ad-hoc changes are identified
- [x] Changes are reflected in ingest and latest spreadsheet

**Comment by ESapenaVentura** [comment]
Found the doc related to staging area modification: https://docs.google.com/document/d/19ZT3XV7N-V2kvNd3ARGPClbWSImB9_LN06xI7QRrp9w/edit#

**Comment by ESapenaVentura** [comment]
[DevelopingCardiacSystem](https://contribute.data.humancellatlas.org/submissions/detail?uuid=0e05e76f-9385-428e-b8e2-0b8dc136c512&project=2086eb05-10b9-432b-b7f0-169ccc49d270):
- Library prep needs revision in ingest
- Ami's name needs to be formatted appropiately in ingest

**Comment by ESapenaVentura** [comment]
I have created a human-readable log of all the differences, tomorrow I will check everything is there.

Project: [﻿DevelopingCardiacSystem:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- library_preparation_protocol.end_bias: "3 prime tag"
- library_preparation_protocol.library_construction_method.text: "10X 3' v2 sequencing"
- library_preparation_protocol.library_construction_method.ontology_label: "10X 3' v2 sequencing"
- library_preparation_protocol.library_construction_method.ontology: "EFO:0009899"
- project.contributors.name: "Ami,,Day"


Project: [Lung_fibroblasts:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- library_preparation_protocol.end_bias: "3 prime tag"
- library_preparation_protocol.library_construction_method.text: "10X 3' v2 sequencing"
- library_preparation_protocol.library_construction_method.ontology_label: "10X 3' v2 sequencing"
- library_preparation_protocol.library_construction_method.ontology: "EFO:0009899"
- specimen_from_organism.diseases.text: "pulmonary fibrosis"


Project: [HumanAdultKidneyLiaoMo:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- library_preparation_protocol.end_bias: "3 prime tag"
- library_preparation_protocol.library_construction_method.text: "10X 3' v2 sequencing"
- sequence_file.file_core.format: "fastq.gz"


Project: [HealthyAndCirrhoticLiver:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- project.publications.url: "https://www.nature.com/articles/s41586-019-1631-3"


Project: [AdultHemOrgans:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- project.publications.url: "https://www.biorxiv.org/content/10.1101/2020.01.26.919753v1"
- project.contributors.name: "Ray,,stefancsik"
- project.contributors.email: "ray@ebi.ac.uk"
- project.contributors.institution: "EMBL-EBI"
- project.contributors.laboratory: "Human Cell Atlas Data Coordination Platform"
- project.contributors.adress: "Wellcome Genome Campus, Hinxton, Cambridge CB10 1SA"


Project: [adress:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- project.contributors.address: "Wellcome Genome Campus, Hinxton, Cambridge CB10 1SA"
- project.contributors.country: "UK"
- project.contributors.corresponding_contributor: False
- project.contributors.project_role.text: "HCA data wrangler"


Project: [PulmonaryFibrosisGSE135893:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- project.publications.url: "https://advances.sciencemag.org/content/6/28/eaba1972"
- project.publications.doi: "10.1126/sciadv.aba1972"


Project: [nktpbmcZhou:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- project.publications.url: "https://www.frontiersin.org/articles/10.3389/fcell.2020.00384/full"


Project: [Oligodendrocyte_MS:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- sequence_file.file_core.format: "fastq.gz"


Project: [pbmcCov19Flu:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- project.project_core.project_description: "Although most severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)–infected individuals experience mild coronavirus disease 2019 (COVID-19), some patients suffer from severe COVID-19, which is accompanied by acute respiratory distress syndrome and systemic inflammation. To identify factors driving severe progression of COVID-19, we performed single-cell RNA sequencing using peripheral blood mononuclear cells (PBMCs) obtained from healthy donors, patients with mild or severe COVID-19, and patients with severe influenza. Patients with COVID-19 exhibited hyperinflammatory signatures across all types of cells among PBMCs, particularly up-regulation of the tumor necrosis factor/interleukin-1β (TNF/IL-1β)–driven inflammatory response as compared with severe influenza. In classical monocytes from patients with severe COVID-19, type I interferon (IFN) response coexisted with the TNF/IL-1β–driven inflammation, and this was not seen in patients with milder COVID-19. We documented type I IFN–driven inflammatory features in patients with severe influenza as well. On the basis of this, we propose that the type I IFN response plays a pivotal role in exacerbating inflammation in severe COVID-19."


Project: [ColonImmune10XSS2VDJ:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):


Project: [FetalLiverHaematopoiesis:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- donor_organism.diseases.text: "normal"
- specimen_from_organism.diseases.text: "normal"


Project: [HeartSingleCellsAndNucleiSeq:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- donor_organism.diseases.text: "normal"


Project: [Substantia_nigra_and_locus_coeruleus:5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47):
- project.insdc_project_accessions: "SRP186408"
- project.insdc_study_accessions: "PRJEB39719"

**Comment by ESapenaVentura** [comment]
This ticket still needs to be done - I have updated the acceptance criteria

**Comment by ofanobilbao** [comment]
Moving this ticket to Stalled while Bulk Updates is ready in Prod

**Comment by ESapenaVentura** [comment]
Corrected version of the human-readable list from above:

- [ ] Project [2086eb05-10b9-432b-b7f0-169ccc49d270](https://contribute.data.humancellatlas.org/projects/detail?uuid=2086eb05-10b9-432b-b7f0-169ccc49d270)
- ff7925dc-34f2-4e0b-a56b-a5b2f8ad68ef = end_bias: 3 prime tag
- ff7925dc-34f2-4e0b-a56b-a5b2f8ad68ef = library_construction_method.text: 10X 3' v2 sequencing
- ff7925dc-34f2-4e0b-a56b-a5b2f8ad68ef = library_construction_method.ontology_label: 10X 3' v2 sequencing
- ff7925dc-34f2-4e0b-a56b-a5b2f8ad68ef = library_construction_method.ontology_id: EFO:0009899
- 2086eb05-10b9-432b-b7f0-169ccc49d270 = contributors.name: Ami,,Day
- [ ] Project [b4a7d12f-6c2f-40a3-9e35-9756997857e3](https://contribute.data.humancellatlas.org/projects/detail?uuid=b4a7d12f-6c2f-40a3-9e35-9756997857e3)
- 1faeb12e-22f1-49d8-a6a8-3e6b196993e6 = end_bias: 3 prime tag
- 1faeb12e-22f1-49d8-a6a8-3e6b196993e6 = library_construction_method.text: 10X 3' v2 sequencing
- 1faeb12e-22f1-49d8-a6a8-3e6b196993e6 = library_construction_method.ontology_label: 10X 3' v2 sequencing
- 1faeb12e-22f1-49d8-a6a8-3e6b196993e6 = library_construction_method.ontology: EFO:0009899
- 681be034-c735-4ad0-9909-10bb531c3069 = diseases.text: pulmonary fibrosis
- dd2d4cc8-48b9-4ff8-a4cd-4c61ebb8cd80 = diseases.text: pulmonary fibrosis
- b8d9b87e-3145-4176-8b2d-d252ac59d893 = diseases.text: pulmonary fibrosis
- 11a7eee4-a2ce-4cff-9295-a81e9a60878f = diseases.text: pulmonary fibrosis
- 7b91aa53-8aa6-471e-937b-9fce1d0848e3 = diseases.text: pulmonary fibrosis
- de1d9bcf-e4d2-43bc-b095-73d2f7c85b7b = diseases.text: pulmonary fibrosis
- cf1ccd9c-565e-46ea-bd3f-12914cd49093 = diseases.text: pulmonary fibrosis
- e2a0dc4c-aee5-400d-8038-62ae203f8391 = diseases.text: pulmonary fibrosis
- 2def03e5-d9c1-4eeb-af9f-1fb4a93554e5 = diseases.text: pulmonary fibrosis
- f2f63c80-d507-46c8-9149-b286dcfb65c7 = diseases.text: pulmonary fibrosis
- 5170679e-4ae1-4efb-af39-a4f7cb181e4e = diseases.text: pulmonary fibrosis
- [ ] Project [2ef3655a-973d-4d69-9b41-21fa4041eed7](https://contribute.data.humancellatlas.org/projects/detail?uuid=2ef3655a-973d-4d69-9b41-21fa4041eed7)
- f334fb81-2a6a-4097-89ec-e97f3b53d8a9 = end_bias: 3 prime tag
- f334fb81-2a6a-4097-89ec-e97f3b53d8a9 = library_construction_method.text: 10X 3' v2 sequencing
- a6152467-f0ee-4be3-90c0-7635450a58ae = file_core.format: fastq.gz
- 1f95fe97-e8de-4b13-9a0d-df1c1648479f = file_core.format: fastq.gz
- 02252d26-d677-4053-9123-fe7c2d294bfe = file_core.format: fastq.gz
- 4beb39ee-03ad-4100-976a-eb48038232a2 = file_core.format: fastq.gz
- 1ad21ed6-e0d4-4b30-bf9b-eaa8a248f119 = file_core.format: fastq.gz
- c3b6828d-585d-44f8-96c3-30974f33dad0 = file_core.format: fastq.gz
- b5a78d96-efc1-4af8-8877-bbdafab852e6 = file_core.format: fastq.gz
- d0749e50-a04e-45af-9b01-05209e6429de = file_core.format: fastq.gz
- e545db88-0543-4769-a7cf-95b69c4e237f = file_core.format: fastq.gz
- 27639c1d-bcd9-4c65-9a72-9177b410f357 = file_core.format: fastq.gz
- 786f53cd-3f93-4224-b2e2-a45e21b02934 = file_core.format: fastq.gz
- 3f7d6a00-1fd0-4e36-b4bb-b8cfc2aad40c = file_core.format: fastq.gz
- 77644f23-10f8-4378-b94b-3431ae3496f7 = file_core.format: fastq.gz
- a1c4b2d2-e667-49cf-894e-913bc166f8c3 = file_core.format: fastq.gz
- 2d902942-2532-46ad-9651-b606a955d407 = file_core.format: fastq.gz
- 4f49933e-88d5-49df-a065-a192de2e39e5 = file_core.format: fastq.gz
- a0831cd1-a400-46f1-934f-de78c65567a8 = file_core.format: fastq.gz
- 91662592-0c8b-43a9-9ae1-fb4f8e6e81c1 = file_core.format: fastq.gz
- 30d74891-bca7-4ad9-8eeb-5ee9a1d8c162 = file_core.format: fastq.gz
- 6593375f-8c8a-48d5-9246-0dcfeabd5d97 = file_core.format: fastq.gz
- 58ac64da-8016-4296-8054-23206291b2d4 = file_core.format: fastq.gz
- 6722de63-59a2-4974-a242-7c243a71a140 = file_core.format: fastq.gz
- ff61c1de-eb09-448e-aa19-3b17afc1c44e = file_core.format: fastq.gz
- f512abe7-20a3-416b-93a7-94e3712fadcd = file_core.format: fastq.gz
- 23d95038-a805-432b-ac0d-9a59bbebf45b = file_core.format: fastq.gz
- 9f0f0269-d0bb-48e4-b46d-3b3970c9ebeb = file_core.format: fastq.gz
- 021b9592-06b5-467c-b351-614e375c1747 = file_core.format: fastq.gz
- d877e389-dfb9-4534-b1fa-9ebc80b8f8ef = file_core.format: fastq.gz
- 30f1d8c3-83ef-42ed-b846-f9e3bf6b2aff = file_core.format: fastq.gz
- bfc735fc-ea3e-4e0b-b8e7-785edc4fd42e = file_core.format: fastq.gz
- b543a57b-7cbc-4b95-a457-9adbd2c2fcf8 = file_core.format: fastq.gz
- 475741a1-c7f5-44c6-94e3-39f79529fb9e = file_core.format: fastq.gz
- b3e4c7ac-262a-416b-ab60-8f950f52e015 = file_core.format: fastq.gz
- 3848a15b-0e65-4225-954c-69228726c7e7 = file_core.format: fastq.gz
- [ ] Project [c41dffbf-ad83-447c-a0e1-13e689d9b258](https://contribute.data.humancellatlas.org/projects/detail?uuid=c41dffbf-ad83-447c-a0e1-13e689d9b258)
- c41dffbf-ad83-447c-a0e1-13e689d9b258 = publications.url: https://www.nature.com/articles/s41586-019-1631-3
- [ ] Project [455b46e6-d8ea-4611-861e-de720a562ada](https://contribute.data.humancellatlas.org/projects/detail?uuid=455b46e6-d8ea-4611-861e-de720a562ada)
- 455b46e6-d8ea-4611-861e-de720a562ada = publications.url: https://www.biorxiv.org/content/10.1101/2020.01.26.919753v1
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.name: Ray,,stefancsik
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.email: ray@ebi.ac.uk
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.institution: EMBL-EBI
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.laboratory: Human Cell Atlas Data Coordination Platform
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.address: Wellcome Genome Campus, Hinxton, Cambridge CB10 1SA
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.country: UK
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.corresponding_contributor: False
- 455b46e6-d8ea-4611-861e-de720a562ada = contributors.project_role.text: HCA data wrangler
- [ ] Project [c1a9a93d-d9de-4e65-9619-a9cec1052eaa](https://contribute.data.humancellatlas.org/projects/detail?uuid=c1a9a93d-d9de-4e65-9619-a9cec1052eaa)
- c1a9a93d-d9de-4e65-9619-a9cec1052eaa = publications.url: https://advances.sciencemag.org/content/6/28/eaba1972
- c1a9a93d-d9de-4e65-9619-a9cec1052eaa = publications.doi: 10.1126/sciadv.aba1972
- [ ] Project [f48e7c39-cc67-4055-9d79-bc437892840c](https://contribute.data.humancellatlas.org/projects/detail?uuid=f48e7c39-cc67-4055-9d79-bc437892840c)
- f48e7c39-cc67-4055-9d79-bc437892840c = publications.url: https://www.frontiersin.org/articles/10.3389/fcell.2020.00384/full
- [ ] Project [38449aea-70b5-40db-84b3-1e08f32efe34](https://contribute.data.humancellatlas.org/projects/detail?uuid=38449aea-70b5-40db-84b3-1e08f32efe34)
- 5ec56acd-62cd-4312-8c16-8ed5b2d046df = file_core.format: fastq.gz
- 4d9b025b-4510-460b-810e-3ddd314f0c11 = file_core.format: fastq.gz
- 2cac8393-789d-4d20-94cd-96f19fc22adc = file_core.format: fastq.gz
- 7e1fcd67-141a-4d17-9b5c-9764631da471 = file_core.format: fastq.gz
- eecb5e8e-cce3-4d91-b799-41d29c9c9f78 = file_core.format: fastq.gz
- 1f34a4e8-2b53-40d4-a8e3-a2323fa16864 = file_core.format: fastq.gz
- 73194fad-4b70-4fe3-9834-a846cc874387 = file_core.format: fastq.gz
- 746c31f3-1f78-466c-89f7-69be6808b87c = file_core.format: fastq.gz
- ce8dfec1-4d8c-4d7a-add2-4a474e24dba2 = file_core.format: fastq.gz
- 25ce2040-3b86-4e80-8b30-0d33eb5ac1e4 = file_core.format: fastq.gz
- f8652890-e779-4569-9a5b-a49a980514c1 = file_core.format: fastq.gz
- 2e6e6108-7c2c-42c5-a7a2-83447414c9f9 = file_core.format: fastq.gz
- c6f226f9-b61a-4694-9ca4-14620cb588b3 = file_core.format: fastq.gz
- dc89e405-5709-459f-8e11-0b9612af91d6 = file_core.format: fastq.gz
- 4e7eb317-5348-4860-8fbb-58495ca283c3 = file_core.format: fastq.gz
- 3cfd25ae-eb76-4d36-9e28-6a685d651e56 = file_core.format: fastq.gz
- 95dad37a-151f-4847-b9ea-7b39eca8fa8d = file_core.format: fastq.gz
- 9617922e-979d-457a-bc77-0402edf21d38 = file_core.format: fastq.gz
- 41b03d81-a0f4-425d-ac24-d3310ed82eba = file_core.format: fastq.gz
- d6a319d6-6456-403e-8c8f-1e8a65ac5562 = file_core.format: fastq.gz
- 4d286c95-36aa-4ef6-b266-f218007aa0ec = file_core.format: fastq.gz
- 488c6e6c-2526-4fc7-b695-96876b9cd20f = file_core.format: fastq.gz
- a82f78cc-ec53-4560-9314-4ee8bba771d5 = file_core.format: fastq.gz
- 2d66ab75-8349-4523-be47-aa3a93328ada = file_core.format: fastq.gz
- ed87b053-4669-4212-808b-8296b94b6d19 = file_core.format: fastq.gz
- 4e57d82a-524e-498c-a418-97a24c026790 = file_core.format: fastq.gz
- 9abd905d-73fe-4554-be65-1b13683f4629 = file_core.format: fastq.gz
- 1de69e71-d3c7-44a4-9817-a19692032d6c = file_core.format: fastq.gz
- f8e55e54-00f2-4189-86f0-3fbfd7d8760c = file_core.format: fastq.gz
- b3219553-2487-4354-a202-44df3fbfc117 = file_core.format: fastq.gz
- 01d7a986-52a7-449d-a6c1-c212807768f8 = file_core.format: fastq.gz
- 228c5695-20a9-45db-8568-7e4214d94886 = file_core.format: fastq.gz
- 0513660e-a925-4329-be70-29971129e22b = file_core.format: fastq.gz
- ed77368d-d2b3-4c6a-8612-3ecf34de2b7b = file_core.format: fastq.gz
- 55f12186-900f-4460-a423-00951d0eadc6 = file_core.format: fastq.gz
- 8bbd9c40-4b7e-4c13-bb6e-d2a147353319 = file_core.format: fastq.gz
- 918fd451-004a-45b2-b370-d208b9fe7257 = file_core.format: fastq.gz
- e503d15b-095a-434e-a925-03790ca1eddb = file_core.format: fastq.gz
- 082731a4-2e36-4727-b6a2-a0b73f622daa = file_core.format: fastq.gz
- 73eda164-f924-4387-8a9e-ce9f2e0bea28 = file_core.format: fastq.gz
- 73a82e16-b836-4407-94da-0d74233fd8ce = file_core.format: fastq.gz
- 238da323-45c4-4790-bc0e-1eb4d3dd8aa9 = file_core.format: fastq.gz
- c58f2db5-875c-4f3b-b408-5cec9bbc4c25 = file_core.format: fastq.gz
- 4525803f-8444-44a2-9f16-0ad5859955f5 = file_core.format: fastq.gz
- ef2b7b91-e352-4eca-b381-66a92ee52611 = file_core.format: fastq.gz
- fc74d0bd-7e61-4dc5-a1c4-4d4989c1a760 = file_core.format: fastq.gz
- f9b5eccd-f548-4657-a676-4ac9ac06b070 = file_core.format: fastq.gz
- 25bc1b25-c7fb-460d-8b58-21d1229d4078 = file_core.format: fastq.gz
- f628d00c-53e9-4b34-aa8a-13720c130233 = file_core.format: fastq.gz
- 2d0c9d52-bfc8-465d-96f2-2a03c64f52ae = file_core.format: fastq.gz
- a4b39f2e-476c-4ed5-af83-be9130480731 = file_core.format: fastq.gz
- 1e37925f-04d8-4fe9-b48f-90c80db8f5f6 = file_core.format: fastq.gz
- bbc01a00-0129-4006-856d-f7a12c593829 = file_core.format: fastq.gz
- dbb6086c-f459-45a9-89f5-b93a76ea4643 = file_core.format: fastq.gz
- 075d6ca6-3142-4d81-9e68-ef58b2a2531a = file_core.format: fastq.gz
- 095b9603-75b5-456b-8ef8-01c1343e0e53 = file_core.format: fastq.gz
- 2843c3a5-a6f0-4ad8-a5c6-0ded6434c0c6 = file_core.format: fastq.gz
- 19f293bc-d62b-474a-9789-a6fba98a6a97 = file_core.format: fastq.gz
- 6e58b595-f36f-4e3d-ae3a-e755b785cf4e = file_core.format: fastq.gz
- 8bceb377-5ae8-4376-ae44-0034644d39cc = file_core.format: fastq.gz
- [ ] Project [95f07e6e-6a73-4e1b-a880-c83996b3aa5c](https://contribute.data.humancellatlas.org/projects/detail?uuid=95f07e6e-6a73-4e1b-a880-c83996b3aa5c)
- 95f07e6e-6a73-4e1b-a880-c83996b3aa5c = project_core.project_description: Although most severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)–infected individuals experience mild coronavirus disease 2019 (COVID-19), some patients suffer from severe COVID-19, which is accompanied by acute respiratory distress syndrome and systemic inflammation. To identify factors driving severe progression of COVID-19, we performed single-cell RNA sequencing using peripheral blood mononuclear cells (PBMCs) obtained from healthy donors, patients with mild or severe COVID-19, and patients with severe influenza. Patients with COVID-19 exhibited hyperinflammatory signatures across all types of cells among PBMCs, particularly up-regulation of the tumor necrosis factor/interleukin-1β (TNF/IL-1β)–driven inflammatory response as compared with severe influenza. In classical monocytes from patients with severe COVID-19, type I interferon (IFN) response coexisted with the TNF/IL-1β–driven inflammation, and this was not seen in patients with milder COVID-19. We documented type I IFN–driven inflammatory features in patients with severe influenza as well. On the basis of this, we propose that the type I IFN response plays a pivotal role in exacerbating inflammation in severe COVID-19.
- [ ] Project [f2fe82f0-4454-4d84-b416-a885f3121e59](https://contribute.data.humancellatlas.org/projects/detail?uuid=f2fe82f0-4454-4d84-b416-a885f3121e59)
- 9478b757-912f-43d9-b71f-f95783a03620 = diseases.text: normal
- 1b5a4bc7-5a90-4782-a657-536a8b533156 = diseases.text: normal
- 85dc3748-6751-482b-b7cd-c1e08f7df5c0 = diseases.text: normal
- 5baa7164-60f5-4b28-8bad-e9a0563cac70 = diseases.text: normal
- ba005942-3abb-4988-90a4-57747fb05b8b = diseases.text: normal
- 8f63d864-87e5-40f3-8f68-936640010c7d = diseases.text: normal
- 793d9bf6-00cb-49e6-acc2-2cc724036645 = diseases.text: normal
- d0baedfe-0556-4c2b-a1a0-d1e28ef07bb5 = diseases.text: normal
- 39046bdd-483c-44ad-9b50-dea608d34255 = diseases.text: normal
- ae71343b-df16-49a3-829d-a6e61afdc079 = diseases.text: normal
- e8fbe9c1-ab25-4300-a40d-65d0e8f627e0 = diseases.text: normal
- 52a4be55-4150-4489-8361-88af5a97e67e = diseases.text: normal
- eed4d335-880b-4735-9d04-cdbf706e3d44 = diseases.text: normal
- dd19fdc7-35a9-432f-9a97-670637433eda = diseases.text: normal
- f2ed99b4-a68d-4d54-8c65-9534ad5931b5 = diseases.text: normal
- 9417041b-2952-41d5-b0d8-b42694f4fd4a = diseases.text: normal
- ae073235-e422-4c3a-8bf4-9892d6e769b3 = diseases.text: normal
- 46e825a2-e355-4869-a3b0-fcd56b198dc1 = diseases.text: normal
- 31899978-a518-4d78-b85a-f62bca7ed723 = diseases.text: normal
- 0d27ca8e-5325-4e47-9807-8afd92e9bf89 = diseases.text: normal
- 94259313-d341-4b1f-b9cc-48a760d81c19 = diseases.text: normal
- 1edb7ccc-0cb3-41c4-a193-181542bce479 = diseases.text: normal
- 15e7f794-9207-4289-a694-e09639333c18 = diseases.text: normal
- bed46309-3752-4115-a307-8c20d93dce55 = diseases.text: normal
- d9679ba8-5eb3-4dc9-9614-37a91f08289f = diseases.text: normal
- 5b53b020-d678-42d0-8612-1c8d2f2a2b3c = diseases.text: normal
- 19d67e4e-18d8-4c7e-a788-28851a19e932 = diseases.text: normal
- b6d749e1-8c32-4dc8-9066-f7e9e17a5e01 = diseases.text: normal
- 9588a360-9b8b-42b0-b457-7355bfa0687e = diseases.text: normal
- 75b6d713-08dc-4eff-9347-95c9519a34cd = diseases.text: normal
- ac95f44c-9abd-4438-827e-ae1f8cbcb14f = diseases.text: normal
- 55c6a0e6-d8ce-47af-a877-711da756a0f6 = diseases.text: normal
- b8912f33-12a7-4bf8-9f25-e91fbc77517c = diseases.text: normal
- b00157c9-d8c4-4c3b-8bc4-80403305eb4d = diseases.text: normal
- dba60b5a-af86-4fde-8cfc-49b008f5adad = diseases.text: normal
- 6b94e023-9280-45df-ac3d-5a258e19bf29 = diseases.text: normal
- 54bfca9c-a1f8-4632-a0cb-5f7b5edf48d6 = diseases.text: normal
- 8b122a1f-3535-4483-832c-9bcd26b0a7f2 = diseases.text: normal
- c0e1df3a-317a-41ee-940d-f08813742e78 = diseases.text: normal
- 31cee6c8-50a2-4c5e-ac37-3e834590a50a = diseases.text: normal
- fbed02e6-1547-469c-b96f-45c61111af53 = diseases.text: normal
- 619887a0-67fb-4e24-be95-409f9b3e8474 = diseases.text: normal
- 2d0ef769-fcc0-44c3-ae16-98762b132c15 = diseases.text: normal
- 69576784-ca06-4ccb-bab7-d6e8353a8036 = diseases.text: normal
- [ ] Project [ad98d3cd-26fb-4ee3-99c9-8a2ab085e737](https://contribute.data.humancellatlas.org/projects/detail?uuid=ad98d3cd-26fb-4ee3-99c9-8a2ab085e737)
- f6a1741e-8a24-435f-b57e-c7897175bc0f = diseases.text: normal
- 2ff6b64f-c1f3-413f-bf30-7a1b7a2ad62c = diseases.text: normal
- 1460c0c6-b265-4a20-a4ac-2657554557c4 = diseases.text: normal
- 97dd8817-7c22-48cb-8451-77936fc1cdff = diseases.text: normal
- 092c9a21-3e90-4e39-b7a8-294377bec28f = diseases.text: normal
- f141b80f-70c3-42ac-83f9-f77af6dac71c = diseases.text: normal
- 4d72ef99-5ce9-43bd-9aed-b867d466eb84 = diseases.text: normal
- 981597b0-882f-4797-8d31-a4353bc49371 = diseases.text: normal
- 5beade7e-dfeb-45db-9d97-afc594bc7ee2 = diseases.text: normal
- 73689cb0-8a83-4d84-a642-b3af2a72a086 = diseases.text: normal
- bcc392bb-ca37-428e-8513-58c53a8116a0 = diseases.text: normal
- c2723205-b835-4ca5-8ff1-d0e3989018f7 = diseases.text: normal
- 96dd85dd-6f2e-4b2a-947f-9a66ff2ba8f0 = diseases.text: normal
- 818a588a-50a6-429a-85a1-8e8d85b0ea37 = diseases.text: normal
- [ ] Project [5b5f05b7-2482-468d-b76d-8f68c04a7a47](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b5f05b7-2482-468d-b76d-8f68c04a7a47)
- 5b5f05b7-2482-468d-b76d-8f68c04a7a47 = insdc_project_accessions: SRP186408
- 5b5f05b7-2482-468d-b76d-8f68c04a7a47 = insdc_study_accessions: PRJEB39719

**Comment by ESapenaVentura** [comment]
On pause until we solve the migration issue

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to check with alegria

**Comment by ESapenaVentura** [comment]
Projects updated in ingest (left in valid):
- f2fe82f0-4454-4d84-b416-a885f3121e59

Projects that had an update in the project metadata and have been re-exported:
- f48e7c39-cc67-4055-9d79-bc437892840c: Sent import request

Projects that had an update in the project metadata **AND COULDN'T BE RE-EXPORTED**:
- c41dffbf-ad83-447c-a0e1-13e689d9b258: 10x_has_more_than_2_files.adoc
- c1a9a93d-d9de-4e65-9619-a9cec1052eaa: "Exported" status won't change
- 95f07e6e-6a73-4e1b-a880-c83996b3aa5c: Stuck in "Exported" status
- ad98d3cd-26fb-4ee3-99c9-8a2ab085e737: Stuck in "Archived". @aaclan-ebi this is a dataset that couldn't be exported in the migration process
- 5b5f05b7-2482-468d-b76d-8f68c04a7a47: Didn't export @aaclan-ebi this is another dataset that couldn't be exported in the migration process


Projects already updated in ingest (No further action needed):
- 455b46e6-d8ea-4611-861e-de720a562ada
- 38449aea-70b5-40db-84b3-1e08f32efe34

**Comment by ESapenaVentura** [comment]
Need to act on:
- c41dffbf-ad83-447c-a0e1-13e689d9b258: 10x_has_more_than_2_files.adoc
- c1a9a93d-d9de-4e65-9619-a9cec1052eaa: "Exported" status won't change
- 95f07e6e-6a73-4e1b-a880-c83996b3aa5c: Stuck in "Exported" status
- ad98d3cd-26fb-4ee3-99c9-8a2ab085e737: Stuck in "Archived". @aaclan-ebi this is a dataset that couldn't be exported in the migration process
- 5b5f05b7-2482-468d-b76d-8f68c04a7a47: Didn't export @aaclan-ebi this is another dataset that couldn't be exported in the migration process

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to create ticket on actions and put in ops backlog
