### ISSUE TITLE
GSE146165, GSE144038 - Microglia Require CD4 T Cells to Complete the Fetal-to-Adult Transition

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#268]
### Primary Wrangler:
Ray
### Associated files:
* Google Drive: <https://drive.google.com/drive/folders/1MYi5OHuARUQIIewc4WUWRISbQwsrktfD>

### Published study links
* Paper:  Pasciuto E, Burton OT, Roca CP, et al. Microglia Require CD4 T Cells to Complete the Fetal-to-Adult Transition. Cell. 2020 Aug;182(3):625-640.e24. [DOI: 10.1016/j.cell.2020.06.026.](https://doi.org/10.1016/j.cell.2020.06.026)
Pubmed ID: [32702313](http://europepmc.org/article/MED/32702313)
* Accessioned data:
    * [GSE146165](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146165): Homo sapiens
    * [GSE144038](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144038): Mus musculus

### Key Events

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project.
- [x] Submit dataset to Production 
- [x] Export project
- [x] Upload matrix files

**Comment by rays22** [comment]
Some of the donors are presumably living Europeans.

**Comment by rays22** [comment]
I have uploaded the expression matrix files that I found at
* <ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE146nnn/GSE146165/suppl/GSE146165_RAW.tar> and
* <ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE144nnn/GSE144038/suppl/GSE144038_RAW.tar>

to the gdrive folder [gene-cell_expression_matrices](https://drive.google.com/drive/folders/1b8B0kU6gP8iHLh5Gyu57q1pgjAthjV1_).

**Comment by lauraclarke** [comment]
I had added this to the April milestone with the goal of getting it in as the matrix files, as I said in the operations call we should probably prioritize a managed access project first but if that works there should be nothing that holds us back adding this too @Wkt8 FYI if you are looking for test cases

**Comment by rays22** [comment]
* Transferred 78 fastq data files to the hca-util upload area from NCBI Cold Storage buckets.
*  Sent a follow up email to the authors about cell annotation and matrix files and asked about the number of human PBMC donors.

**Comment by rays22** [comment]
2021-03-22: The authors have provided some information on the donor-sample relationships which was not clear from the paper of the GEO metadata. There are two human donors:

* 1 PBMC donor
* 1 brain tissue donor

**Comment by rays22** [comment]
I have validated the metadata on staging and also by the ingest-graph-validator.
I have uploaded the [validated HCA metadata spreadsheet](https://drive.google.com/file/d/1IK3ID1tirMNVYDwqx18UxOQ89h1wxyjE/) to the gdrive.
It is ready for secondary review.
Please note that I used Ingest UI to create the project and the excel template, so the project related metadata is not in the spreadsheet. I have added only a rudimentary project tab to the metadata spreadsheet, because the ingest-graph-validator could not validate the metadata without it.

**Comment by Wkt8** [comment]
Assigning myself for secondary review.

**Comment by Wkt8** [comment]
I have had a look at this for secondary review, looks good apart from a few comments! 

Specimen From Organism: 
human_PBMCs - I noticed you put PBMC as the Organ. I know that in the past we have used 'Blood' as an organ, perhaps that would be more accurate as PBMC is a cell type? 

Cell Suspension ID
GSM4367466 (linked to human_PBMCs) - Add PBMC as a Selected Cell Type here.

Enrichment_protocol1 
The description should be changed from 'a 100mm mesh' to 'a 100um mesh'. 
'maximum size selected' should be 100 

Sequence File: (optional changes) 
Add the Content Description Ontology ID: data:3494
Content Description Ontology Label: DNA sequence

Following from Laura's comment, are you going to 
- ingest the mouse sequence data files, and not the human ones, or 
- ingest none of the sequence files and only the CGMs?

As they will result in different changes to the spreadsheet!

**Comment by rays22** [comment]
Thanks Wei for reviewing it.
Good suggestions and good error catching.

I will change the spreadsheet according to your suggestions.

With regards to your question about human *vs.* mouse sequence data, I am considering two options.

### Option 1

Split the dataset into two based on the donor organisms.
First I can export the full mouse dataset including sequence data and the mouse expression matrix file that I have already collected.

I can submit the full human dataset at a later date when we can handle living human donor sequence data.

* Advantage: less risky than Option 2, because it would follow a tested and tried process.
* Disadvantage: the entire human dataset will have to wait.

### Option 2

Do not split the metadata.
Export the metadata for both the human and the mouse experiments.
Export the mouse sequence data too.
Export both the human and the mouse expression matrix files that I have collected for the dataset.

I can submit the human sequence data at a later date when appropriate.

* Advantage: more complete data export than in Option 1.
* Disadvantage: The process of linking matrix files without sequence data files for export/import has not been tested yet.

**Comment by rays22** [comment]
I have split the dataset into two (as in Option 1 above). I have uploaded the **mouse** data and metadata to Ingest production.
I am waiting for Ingest to finish validation.

**Comment by rays22** [comment]
I have created a new issue https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/288
to track the status of the human subset of the data that needs to be exported when we can export data related to living European donors.

**Comment by rays22** [comment]
I have started exporting the mouse subset with option `Submit metadata and data to the Human Cell Atlas. This will be made public with the next snapshot.`

**Comment by rays22** [comment]
The Ingest status is still `Exporting`. It looks like that there is a problem with exporting.

**Comment by rays22** [comment]
The issue with Ingest exporting has been resolved
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/289
Remaining tasks to complete:
- [ ] notify the data import team
- [ ] change the project status in the Dataset Tracking Sheet to exported
- [ ] fill in [metadata about matrix files](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY/)
- [ ] upload files to the contributor matrix [google bucket](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/contributor_matrix_addition_SOP.html#uploading-the-files-to-the-google-bucket)

**Comment by rays22** [comment]
The export of the mouse subset (GSE144038) of the data is complete.

**Comment by lauraclarke** [comment]
@rays22 was there a reason this didn't get added to the SCEA queue?

**Comment by rays22** [comment]
It has the `broker_to_scea: no` status in the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit?pli=1#gid=0). I believe that column was filled in by SCEA curators when they assessed datasets some time ago.

**Comment by rays22** [comment]
Needs an update of the missing donor `genus_species` information.
Action:
- [ ] Add `genus_species` in Ingest UI.
- [ ] Export metadata update.
- [ ] Notify the [HCA production data import team.](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#exporting-the-submission-to-dcp)
