### ISSUE TITLE
installing SCEA validation software on EC2 so it can be run alongside conversion

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#269]
@ami-day can you provide details of what is needed 
This will be done when the two software tools for validating SCEA submissions are installed on EC2 so wranglers can run them on SCEA files without having to download them to their personal machines

**Comment by ami-day** [comment]
Yes. I sent them to Jacob on slack already but I'll paste them here too

**Comment by ami-day** [comment]
There are 2 different validators:

1. is python based: https://pypi.org/project/atlas-metadata-validator/ https://bioconda.github.io/recipes/atlas-metadata-validator/README.html

2. a perl script: I am attaching the perl script and environment yaml file for the perl tool (there isn't a repo for this tool). 

The path to the hca-to-scea tool itself and how to activate the required environment are on EC2 as following:
/data/tools/hca-to-scea-tools/hca2scea-backend
source venv/bin/activate

**Comment by amnonkhen** [comment]
Installation instructions are in [to SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/hca_to_scea_tools_SOP.html#section-d-validation-of-idf-and-sdrf-files).

**Comment by amnonkhen** [comment]
@ami-day is the validators not being installed on the EC2 instance blocking you in any way, or is it merely a nuisance? In other words, are you stuck or is there a workaround?

**Comment by ke4** [comment]
I installed both the python and the perl validator.
Python validator folder on EC2: `/data/tools/scea-python-atlas-validator`
Perl validator folder on EC2: `/data/tools/scea-perl-atlas-validator`

**Comment by ke4** [comment]
PR for the Installation instruction SOP: [Installing validators for SCEA tools onto Wranglers' EC2 instance](https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/340)

**Comment by ami-day** [comment]
Thanks @ke4!
I had some issues getting it running on EC2. I think this is because of what you had mentioned previously, about it perhaps not working when I am logged in as me. I discussed @MightyAx and he helped me get it working. However, he said that we would need to install and run it in our home or other subdirectory separately. I have updated the hca-to-scea SOP with the relevant information, so I am closing this ticket (https://github.com/ebi-ait/hca-to-scea-tools/blob/master/README.md).

**Comment by MightyAx** [comment]
The virtual environment in the shared folder
`/data/tools/scea-python-atlas-validator/venv`
Was actually made using a python installation in the `ubuntu` user’s home folder, which stopped the wranglers from executing the commands.
Without this venv the wranglers can use the python / anaconda installation in their own home folder can simply run the following:
```
pip install atlas-metadata-validator
export VALIDATION_CONFIG_REPO='https://github.com/ebi-gene-expression-group/metadata-validation-config'
export VALIDATION_CONFIG_FILE='atlas_validation_config.json'
```
taken from https://pypi.org/project/atlas-metadata-validator/

@ke4 I believe the folder you created with the git repo can be deleted, but I've not gone too in depth on my investigation.
