### ISSUE TITLE
GSE116256 - AMLImmunity

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#270]
**Primary Wrangler:**
@ESapenaVentura 
**Secondary Wrangler:**
TBD

**Associated files:**

Google Drive: https://drive.google.com/drive/folders/1dT5O1Q6Lg-sdbCx9zNCBZE1NPYLlDWS4

**Published study links**

Paper: [Single-Cell RNA-Seq Reveals AML Hierarchies Relevant to Disease Progression and Immunity](https://www.cell.com/cell/fulltext/S0092-8674(19)30094-7?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867419300947%3Fshowall%3Dtrue)

Accessioned data: [GSE116256](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE116256)

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [ ] collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Sent an email asking for a couple more details and data

**Comment by ESapenaVentura** [comment]
Need to follow up after no response

**Comment by ESapenaVentura** [comment]
The files are not available fully (Only 1 fastq file for paired end sequencing), and the file headers seem to indicate there should be 2:

`@SRR8521732.1 NS500400:396:HYLFGBGXY:1:11101:15952:1058_AGTGTCTT_ACATGTCTGATT_GTAGCGGG/1`

Not worth to spend too much time investigating the issue, moving to stalled

**Comment by ami-day** [comment]
@ESapenaVentura and @gabsie shall we close this ticket and move it it ineligible status in ingest?

**Comment by ofanobilbao** [comment]
@ESapenaVentura my recommendation for this would be to add your observations to ingest in the Admin notes section and label it as Eligible again and remove yourself, as long as you did not progress much on it. Indicate why you down prioritise and explain difficulty obtaining the data, and put it as Priority 3 and close the ticket in ZenHub.

**Comment by ESapenaVentura** [comment]
Closing the ticket. Looked at it again and marked as ineligible, the data is not available anywhere in the right format
