### ISSUE TITLE
Metadata Updates for DCP3 Catalog

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#271]
This ticket is currently blocked by 
https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/77 and https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/204

Details in the google doc: https://docs.google.com/document/d/1PqN1j925fMh2C1_N-rjCeFCuZZkZWot8rp8aXOXiaGE/edit?userstoinvite=rye@ebi.ac.uk&ts=604b49eb&actionButton=1# 

**Dataset/group this task is for:**
- A cell atlas of human thymic development defines T cell repertoire formation
HumanThymicDevelopment
- Transcriptomic characterisation of haematopoietic stem and progenitor cells from human adult bone marrow, spleen and peripheral blood
AdultHemOrgans
- Single-cell transcriptional landscape of human embryonic limb development
EmbryonicHindlimb
- A human single cell atlas of the substantia nigra reveals novel cell specific pathways associated with the genetic risk of Parkinson’s disease and neuropsychiatric disorders
HumanBrainSubstantiaNigra

**Description of the task:**
For each individual dataset: 
1. Work out what are the required changes to the metadata
2. Perform changes in ingest UI
3. Confirm changes
4. Export dataset submission
5. Fill in [Broad import form](https://docs.google.com/forms/d/e/1FAIpQLSeokUTa-aVXGDdSNODEYetxezasFKp2oVLz65775lgk5t0D2w/viewform), notifying that we are requesting an import 
6. Broad notifies us as UCSC that import and snapshot is completed
7. UCSC notifies us that indexing is complete
8. Final checks 

Some of these changes are required as a result of this issue: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/260 in which we made ad-hoc changes to the data in the staging area, and these changes were not reflected in ingest. 
We have now confirmed that to be displayed as the Data Curator Role, a wrangler needs the ontology label (data curator (EFO:0009737)

**Acceptance criteria for the task:**
The above four projects are updated with correct metadata in the [dcp3 catalog ](https://data.humancellatlas.org/explore/projects?catalog=dcp3)

HumanThymicDevelopment to display Marion Shadbolt as the data curator 
AdultHemOrgans to display Ray Stefancsik as the data curator 
EmbryonicHindlimb to display Enrique Sapena Ventura as the data curator
HumanBrainSubstantiaNigra to display 10X 3' v2 instead of 10X 3' v3 as the technique used

**Comment by lauraclarke** [comment]
Closing this issue as superceeded by dataset specific ticksts
