### ISSUE TITLE
Update hca to scea SOP

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#273]
**Description of the task:**

Summary: Update hca to scea SOP

Goal: add a basic introduction to the tool and link to the hca to scea repo where all the tool and curation instructions live.

Acceptance criteria:

- [x] remove the outdated hca to scea SOP
- [x] add a link to the new guide in the repo and a basic introduction to using the tool. Pull request with changes accepted.

**Comment by yusra-haider** [comment]
@ami-day  can we close this? Since it's done?

**Comment by ami-day** [comment]
I need to update it further since making additional changes so keeping it open for now.

**Comment by lauraclarke** [comment]
@ami-day is this actively being worked on so a ticket is useful or is it something you are doing slowly, as an when you have time so the ticket might not really help with tracking progress?
