### ISSUE TITLE
Delete project that has been replaced with new project

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#275]
A project was recently submitted for export but didn't export due to linking issues

The original project needs to be deleted in ingest and in the staging area.

Project to be deleted: `a097320f-3706-48d8-8c32-77093684792a`

Acceptance criteria:
- [x] ensure the new project exported correctly `1ce3b3dc-02f2-44a8-96da-d6d107b27a76`
- [x] `a097320f-3706-48d8-8c32-77093684792a` project, submission and data files deleted from staging area (if export started? assuming not?)
- [x] `a097320f-3706-48d8-8c32-77093684792a` project, submission and data files deleted from ingest

**Comment by yusra-haider** [comment]
@clairerye, I can see that all the acceptance criteria boxes are check marked. Does anything still need to be done for this one?

**Comment by clairerye** [comment]
So I am a little confused, I can still see the project in ingest? Or am I misunderstanding...?
![Uploading image.png…]()

**Comment by yusra-haider** [comment]
yes, I guess it hasn't been deleted yet. I was confirming as I saw the all the acceptance criterias ticked

**Comment by clairerye** [comment]
Thank you! I agree, super weird that they were all ticked!

**Comment by jacobwindsor** [comment]
I have actioned the following items for project `a097320f-3706-48d8-8c32-77093684792a` and submission `c6c763eb-7ee4-4b31-8dcc-d6e9c66d2cca`:

- Ensured not in staging or prod terra buckets
- Deleted the object `/org-hca-data-archive-upload-prod/c6c763eb-7ee4-4b31-8dcc-d6e9c66d2cca` (upload area for submission)
- Deleted submissionEnvelope from ingest (ID: `605261cb91708e06ec076716`)
- Ensured there is no resource at `archiveSubmissions/605261cb91708e06ec076716` (submission wasn't archived)

I think that's everything, @clairerye?

**Comment by clairerye** [comment]
Thats great, thank you
