### ISSUE TITLE
SARSCov2ChildrenAdults - Meyer

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#276]
**Short name**
SARSCov2ChildrenAdults

**Primary Wrangler:**
Ida

**Secondary Wrangler:**

**Associated files:**

Google Drive:
https://drive.google.com/open?id=1uyLOWN3lvfuZcehgzokAFkLmSudlpVz4

Paper:
[preprint](https://www.medrxiv.org/content/10.1101/2021.03.09.21253012v1) 
[The local and systemic response to SARS-CoV-2 infection in children and adults](https://www.nature.com/articles/s41586-021-04345-x)
GEO:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE168215

Project in ingest:
https://contribute.data.humancellatlas.org/projects/detail?uuid=1538d572-bcb7-426b-8d2c-84f3a7f87bb0

**Key Events**

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Curate projetct metadata
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by mshadbolt** [comment]
This is a collaborative project with some data coming from Kerstin Meyer and other data coming from Chicago. 

Chicago processed data is currently in GEO here https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE168215 and raw data will be in dbGaP, no accession provided as yet.

UK processed data will be in ArrayExpress, with raw data in EGA with no accessions provided as yet. processed data is also on covidcellatlas, I believe the top entry here: https://www.covid19cellatlas.org/index.patient.html but doesn't appear to have all data from the paper.

**Comment by mshadbolt** [comment]
requested new term for 'tracheal brush' https://github.com/EBISPOT/efo/issues/1026

sent email to contributor of geo data to clarify splitting of patients across samples

**Comment by mshadbolt** [comment]
moving this to stalled as it relies on submission of project without seq files.

**Comment by mshadbolt** [comment]
I think this project can be moved forward if the process for managed access projects without sequence files is ticked off this release. I will tag @Wkt8 as I think it makes most sense as he has connections to the contributors and I believe this project is somewhat linked to the Haniffa managed access project and the WSSS in general.

### Current progress:

#### US based metadata & matrices

Metadata and processed matrices were extracted from the GEO accession `GSE168215`

I communicated with Alexander Misharin to clarify some aspects of the study design, email is saved in `files_received` as `Email_From_Alex_Chicago_samples.txt`

I have annotated as much information from GEO and the paper as possible into the spreadsheet.

There is not as much metadata available for these donors, it could be worth reaching out to Kerstin to see if any further information could be gained about these donors so they are more comparable to the UK sourced donors.

#### UK based metadata:

This project is one that I was communicating with Elena about getting their metadata directly into BioSamples and linking to an EGA submission. As of now I am not aware of whether there is a valid EGA Accession for this project. The paper says processed data and metadata will be in ArrayExpress but no accession given.

Elena sent me a spreadsheet with metadata 05/03/2021, the spreadsheet is saved in the 'files_received' folder on the google drive `CV001_biosamples_EGA submission_04032021.xlsx`

I extracted metadata from this sheet into the spreadsheet. The spreadsheet isn't complete however so more details would need to be sought from Elena.

I am also not 100% sure about the structure of the experiment, for example there are samples `CS1A-PBMC` & `CS1B-PBMC` from donor `PC2`, I am not clear if these were two separate blood draws from the patient, or 2 separate cell suspensions.

The processed matrix from the UK donors is supposed to be on the COVID cell atlas, but when I downloaded the matrix `ucl-sanger_covid_airway.submit_to_czi.cellxgene.20200911_obs_metadata.h5ad` and looked at the obs metadata, it only had 3 donors present, `AP1-N`, `AP4-N`, `AP5-N`. I extracted the metadata from this file and saved it in `files_received` as `ucl-sanger_covid_airway.submit_to_czi.cellxgene.20200911_obs_metadata.csv`

### Next steps

- Reach out to Elena to see if metadata for the rest of the donors, samples are available and check in on EGA archiving (might need to have a catchup with Tony/Melanie about the next steps for the BioSamples side of this before that)
- Check whether there will be a matrix containing all the donors in the paper ~52 donors all up
- Check whether there is more metadata available for the US cohort
- Confirm structure in terms of specimens/sample/cell suspension splitting

**Comment by ami-day** [comment]
Tagging @Wkt8 in this ticket as I first assigned myself then saw that Wei has links to these contributors.

**Comment by ofanobilbao** [comment]
@Wkt8 this has now a preview of an accepted publication: 10.1038/s41586-021-04345-x

**Comment by ofanobilbao** [comment]
@ESapenaVentura to secondary review

**Comment by ESapenaVentura** [comment]
@idazucchi I have looked into it! Overall looks great :) 

Just a couple of minor comments about the protocols:

### Dissociation protocol
- For the Chicago_dissociation_protocol, can we add a bit more info about the protocol? (It says previously reported protocol, but we don’t have that info in the database so it doesn’t make that much sense)
- For the UK_nasal_brushing_enzymatic protocol, there are reference numbers in there (e.g. protocol26), we need to take them out

### Library preparation protocols
- I think the cell barcode read is not indicated well for all the protocols, shouldn’t it be Read 1?

**Comment by idazucchi** [comment]
Thank you @ESapenaVentura for catching the error in the library protocols!
I've fixed the errors, expanded the descrption for Chicago_dissociation_protocol and added an ezymatic dissociation protocol.

The project exported without issue and I filled out the export form
