### ISSUE TITLE
Investigate missing file

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#279]
Reported on slack https://humancellatlas.slack.com/archives/C9XD6L0AD/p1616612174036700

Project:7adede6a-0ab7-45e6-9b67-ffe7466bec1f
Exported to the staging area -  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/7adede6a-0ab7-45e6-9b67-ffe7466bec1f/ 

has a sequence_file missing. metadata/sequence_file/9f938259-1f7c-4262-bf47-709e04e76d6b_2021-03-08T19:18:18.899000Z.json is referring to file_name SRR3541799_R1.fastq.gz, but that file does not appear to be present in the data folder.

Can we check if the export was incomplete from ingest as the file is present in ingest

![image.png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/e6279656-7899-46fe-80d8-d1b0f3390481)

we will need to reexport the file if it is actually missing, are there any other files that could be missing?

**Comment by yusra-haider** [comment]
A quick check showed that the number of data files in the staging area is 1591, whereas the total number of files in ingest UI and the ingest submission area is 1600

**Comment by yusra-haider** [comment]
checking the gcp status on this export job (https://api.ingest.archive.data.humancellatlas.org/exportJobs/604693db91708e06ec05d630) shows that the job was successful and 1600 files were transferred:

```Returned transferOperations: {
    "operations": [
        {
            "name": "transferOperations/transferJobs-604693db91708e06ec05d630-1615238115515823",
            "metadata": {
                "@type": "type.googleapis.com/google.storagetransfer.v1.TransferOperation",
                "name": "transferOperations/transferJobs-604693db91708e06ec05d630-1615238115515823",
                "projectId": "mystical-slate-284720",
                "transferSpec": {
                    "awsS3DataSource": {
                        "bucketName": "org-hca-data-archive-upload-prod"
                    },
                    "gcsDataSink": {
                        "bucketName": "broad-dsp-monster-hca-prod-ebi-storage"
                    },
                    "objectConditions": {
                        "includePrefixes": [
                            "e20e2ab7-3e89-4f9f-8ce2-91b2e1866a78"
                        ]
                    }
                },
                "startTime": "2021-03-08T21:15:15.528597501Z",
                "endTime": "2021-03-08T21:16:38.474849892Z",
                "status": "SUCCESS",
                "counters": {
                    "objectsFoundFromSource": "1600",
                    "bytesFoundFromSource": "188553572053",
                    "objectsCopiedToSink": "1600",
                    "bytesCopiedToSink": "188553572053"
                },
                "transferJobName": "transferJobs/604693db91708e06ec05d630"
            },
            "done": true,
            "response": {
                "@type": "type.googleapis.com/google.protobuf.Empty"
            }
        }
    ]
}
job is done
```

**Comment by yusra-haider** [comment]
the project is currently being re-exported. We couldn't figure out what caused the issue as there were no logs, and the gcp status showed this as successful
