### ISSUE TITLE
GSE67833 neural stem cells

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#282]
### Primary Wrangler:
Ray

### Secondary Wrangler:
Wei Kheng

### Associated files:

Google Drive:
* [GSE67833_neural_stem_cells](https://drive.google.com/drive/folders/1vK5gm1TbxHabprdtl2IbKyKZ9OfhzOVR?usp=sharing)

### Published study links

* Paper:
Llorens-Bobadilla E, Zhao S, Baser A, et al. Single-Cell Transcriptomics Reveals a Population of Dormant Neural Stem Cells that Become Activated upon Brain Injury. Cell Stem Cell. 2015 Sep;17(3):329-340. [DOI: 10.1016/j.stem.2015.07.002.](http://doi.org/10.1016/j.stem.2015.07.002)
PMID: [26235341](http://europepmc.org/article/MED/26235341)

Accessioned data:
* [GSE67833](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE67833)
* [PRJNA281015](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=%09PRJNA281015&o=acc_s%3Aa)

### Key Events

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] collect any matrix and cell-type annotation files
- [x] upload sheet to validate metadata
- [x] check linking using ingest graph validator
- [ ] transfer raw files to ingest to validate data files
- [x] ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] submit dataset to Production

**Comment by rays22** [comment]
I have uploaded two expression matrix files
to the folder: [GSE67833_Gene_expression_matrices](https://drive.google.com/drive/folders/1OyCE3z52C4-eXwL5Ma60WsNBo2ldV07a).

**Comment by rays22** [comment]
* The metadata [spreadsheet](https://drive.google.com/file/d/17HSykL5y_BhMeL9PqAXLbs-cXxj1u50L/) is ready for secondary review.
* There is an issue with validating one of the ontology terms.
The term [full length single cell RNA sequencing](http://www.ebi.ac.uk/efo/EFO_0008441) is a child of [assay](http://purl.obolibrary.org/obo/OBI_0000070) in the latest EFO,
yet I am getting this validation error in Ingest:

>    "errorType" : "METADATA_ERROR",
    "message" : "Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070]",
    "userFriendlyMessage" : "Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070] at .method.ontology",
    "absoluteDataPath" : ".method.ontology"

The very same term passed validation yesterday.
When I check the term on the HCA custom OLS (Updated 21 Apr 2021 14:42), there the term `full length single cell RNA sequencing` is only in the `transcription profiling` branch and not under `assay`:
<https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008441>

**Comment by rays22** [comment]
> * There is an issue with validating one of the ontology terms.
> 
> > "errorType" : "METADATA_ERROR",
> > "message" : "Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070]",
> > "userFriendlyMessage" : "Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070] at .method.ontology",
> > "absoluteDataPath" : ".method.ontology"
> 

The ontology validation issue has been fixed by https://github.com/ebi-ait/hca-ebi-dev-team/issues/409#issuecomment-824806835 .

**Comment by Wkt8** [comment]
Assigning myself as secondary reviewer

**Comment by Wkt8** [comment]
Looks great! Just a couple comments: 

1. Consider adding an additional enrichment step for Cell Picking?
Immediately after sorting cells were manually picked with a thin gel-loading micropipette under continuous visual inspection in a Zeiss microscope. To ensure that only one cell was picked, we transferred sequentially 1μl of the cell suspension to the picking plate where a single cell was immediately picked in 0.3μl with another pipette before the addition of a new cell to the plate.

Ontology label: EFO:0010181 
Cell Picking

2. Change library preparation protocol  DOI  from 
10.1038/nprot.2014 to 10.1038/nprot.2014.006

3. I understand the subventricular zone is not present in the adult cerebral cortex, but am unsure if the 'layer of developing cerebral cortex' ontology label should also apply to the other cerebral cortex samples, as they are probably also in the developing stage. Happy for you to make a judgement call on this! 

Apart from that the linking, ontologies and protocols look good. Nice job, Ray!

**Comment by rays22** [comment]
Many thanks @Wkt8 .
Good suggestions and good catch of the truncated DOI. I will implement your suggestions.
I will also try to find a more specific ontology term in place of the `layer of developing cerebral cortex`. It does not look the best choice indeed.

**Comment by rays22** [comment]
The export of this dataset from Ingest seems to be stuck in the `Exporting` state. It has been `Exporting` for three days.

**Comment by rays22** [comment]
I have created an operations ticket [here](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/309).

**Comment by rays22** [comment]
The exporting issue has been solved.
The dataset export is complete now.
The `broker_to_scea` column has the value `no` for this dataset in the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/), so I am moving the ticket to the `Finished` column of the [Dataset wrangling board]( https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/board?repos=261790554&search=282).
