### ISSUE TITLE
Investigate data structure 

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#286]
Dataset - slack conversation: https://humancellatlas.slack.com/archives/C01360XN04S/p1617115584115200
project uuid: d3a4ceac-4d66-4984-9704-2570c0647a56
name: Transcriptomic and clonal characterization of T cells in the human central nervous system. (https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22publicationTitle%22,%22terms%22:%5B%22Transcriptomic%20and%20clonal%20characterization%20of%20T%20cells%20in%20the%20human%20central%20nervous%20system.%22%5D%7D,%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%22d3a4ceac-4d66-4984-9704-2570c0647a56%22%5D%7D,%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D,%7B%22facetName%22:%22specimenOrgan%22,%22terms%22:%5B%22brain%22%5D%7D,%7B%22facetName%22:%22libraryConstructionApproach%22,%22terms%22:%5B%2210x%203%27%20v3%20sequencing%22%5D%7D%5D)
After handoff to the workspace, there is an unexpected structure to the sequencing_input.biomaterial_core.biomaterial_id like SRX9052643 || SRX9052644 for one of them. See in photo. Workspace here. We're seeing failures when trying to run Optimus for most of the lane sets and are trying to debug why. Seeing this in the inputs made us wonder if it's something about how the data is structured that is causing issues.

Can we check if this is the expected structure - ![image (6).png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/061ad711-f485-479c-89fb-8f8619e7bb1d)

**Comment by ami-day** [comment]
I think I have solved this - I have updated the project metadata in ingest prod. It needs to be re-exported with the updates (metadata only). I am unable to do this, as following the edit, the status is still 'exported'. I have put this as a message on the dev slack channel.

**Comment by ami-day** [comment]
This error type was similar to the other project that got stalled when it reached pipelines. I am creating a ticket to add a new test for this error type in the graph validator tests.

**Comment by aaclan-ebi** [comment]
https://contribute.data.humancellatlas.org/projects/detail?uuid=d3a4ceac-4d66-4984-9704-2570c0647a56

**Comment by aaclan-ebi** [comment]
What we did so far:

1. Ami updated the assay processes to fix cell suspension inputs to assay processes
2. We updated all assay processes metadata to increment the version so that it's going to create a new version of the links.json file in the Terra staging area. However, this added process_description attribute with an empty string in the updated processes.

What else needs to be done:

Undo the process_description empty string changes.

**Comment by aaclan-ebi** [comment]
Done 1 & 2

Below is the list of the files which were updated and exported:
```
➜  ~ gsutil ls -l -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56 | grep -v 2021-02-18
gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/data/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/descriptors/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/descriptors/sequence_file/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/:
      3821  2021-04-06T16:18:51Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/66c2b980-c550-48ca-8338-1de9839ff071_2021-04-06T16:17:09.772Z_d3a4ceac-4d66-4984-9704-2570c0647a56.json
      3821  2021-04-06T16:18:50Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/72cc7f55-e7b0-451a-969c-3e8c89f7d398_2021-04-06T16:17:54.717Z_d3a4ceac-4d66-4984-9704-2570c0647a56.json
      3627  2021-04-06T16:18:51Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/95602b67-3c71-4ac1-bd9f-544770cc81e6_2021-04-06T16:15:12.058Z_d3a4ceac-4d66-4984-9704-2570c0647a56.json
      3105  2021-04-06T16:18:48Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/b943c11d-504e-4031-a495-62be7694702c_2021-04-06T16:15:50.433Z_d3a4ceac-4d66-4984-9704-2570c0647a56.json
      3821  2021-04-06T16:18:51Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/c10934f3-4af8-4586-9a90-78535e61975f_2021-04-06T16:16:36.125Z_d3a4ceac-4d66-4984-9704-2570c0647a56.json
      3366  2021-04-06T16:18:49Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/cfc00dd7-fe77-4661-a247-653a63bfae60_2021-04-06T16:13:47.678Z_d3a4ceac-4d66-4984-9704-2570c0647a56.json

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/cell_suspension/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/collection_protocol/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/dissociation_protocol/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/donor_organism/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/enrichment_protocol/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/library_preparation_protocol/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/:
       430  2021-04-06T16:18:48Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/66c2b980-c550-48ca-8338-1de9839ff071_2021-04-06T16:17:09.772000Z.json
       430  2021-04-06T16:18:48Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/72cc7f55-e7b0-451a-969c-3e8c89f7d398_2021-04-06T16:17:54.717000Z.json
       430  2021-04-06T16:18:48Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/95602b67-3c71-4ac1-bd9f-544770cc81e6_2021-04-06T16:15:12.058000Z.json
       430  2021-04-06T16:18:46Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/b943c11d-504e-4031-a495-62be7694702c_2021-04-06T16:15:50.433000Z.json
       430  2021-04-06T16:18:48Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/c10934f3-4af8-4586-9a90-78535e61975f_2021-04-06T16:16:36.125000Z.json
       430  2021-04-06T16:18:47Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/cfc00dd7-fe77-4661-a247-653a63bfae60_2021-04-06T16:13:47.678000Z.json

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/project/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/sequence_file/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/sequencing_protocol/:

gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/specimen_from_organism/:
TOTAL: 465 objects, 183728805602 bytes (171.11 GiB)
```

**Comment by aaclan-ebi** [comment]
```
$ gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/links/ | grep 2021-04-06 |  xargs -I % sh -c 'export gsfile="%"; echo $gsfile; gsutil cat $gsfile | jq'   >> d3a4ceac-4d66-4984-9704-2570c0647a56-all-links.txt
```

[d3a4ceac-4d66-4984-9704-2570c0647a56-all-links.txt](https://app.zenhub.com/files/261790554/49ab1620-9b8c-4388-96c0-7eb25cbdadf0/download)


```
gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/d3a4ceac-4d66-4984-9704-2570c0647a56/metadata/process/ | grep 2021-04-06 |  xargs -I % sh -c 'export gsfile="%"; echo $gsfile; gsutil cat $gsfile | jq'   >> d3a4ceac-4d66-4984-9704-2570c0647a56-all-processes.txt
```
[d3a4ceac-4d66-4984-9704-2570c0647a56-all-processes.txt](https://app.zenhub.com/files/261790554/425c554d-75ba-4e24-a6f1-7aa273c934f9/download)

**Comment by aaclan-ebi** [comment]
Hi @ami-day could you confirm if the content of the links.json files contains the changes you expected?

Please note that the links.json file is using the process metadata version timestamp as designed in the exporter. Because of this, the process metadata version timestamps were updated in order to create a newer version of the links.json file.

**Comment by ami-day** [comment]
Submitted an import form for the updates to this dataset.
