### ISSUE TITLE
GSE146165 - Microglia Require CD4 T Cells to Complete the Fetal-to-Adult Transition

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#288]
This issue is related to <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/268>.
The purpose of this ticket is to track the status of the human subset of the data that has not been exported, because of living European donors.

### Primary Wrangler:
Ray

### Secondary Wrangler:
Wei

### project short name: CD4_T_cells_in_brain

* Ingest project: <https://contribute.data.humancellatlas.org/projects/detail?uuid=e5d45579-1f5b-48c3-b568-320d93e7ca72>

### Associated files:
* Google Drive: <https://drive.google.com/drive/folders/1MYi5OHuARUQIIewc4WUWRISbQwsrktfD>

### Published study links
* Paper:  Pasciuto E, Burton OT, Roca CP, et al. Microglia Require CD4 T Cells to Complete the Fetal-to-Adult Transition. Cell. 2020 Aug;182(3):625-640.e24. [DOI: 10.1016/j.cell.2020.06.026.](https://doi.org/10.1016/j.cell.2020.06.026)
Pubmed ID: [32702313](http://europepmc.org/article/MED/32702313)
* Accessioned data:
    * [GSE146165](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146165): Homo sapiens
    * [GSE144038](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144038): Mus musculus

**Key Events**

- [x] Collect any matrix and cell-type annotation files.
- [ ] Upload spreadsheet that contains the human subset of the metadata to validate.
- [ ] Check linking using ingest graph validator.
- [ ] Transfer raw human data files to ingest to validate data files.
- [ ] Submit the update to Production.
- [ ] Export the human subset of the data as an update

**Comment by ipediez** [comment]
Only the mouse data seems to have been wrangled. I'll check the paper to try identifying why, and add all the human metadata and data. I'm adding too the analysis files for both mouse and human samples.

**Comment by Wkt8** [comment]
I think the reason for the human data is because it was from living europeans! Should be able to add analysis files and openly available human metadata though but definitely not fastqs.

**Comment by ipediez** [comment]
- Original spreadsheet: https://docs.google.com/spreadsheets/d/125l_1HEO059TmbWA3EnZu-s1KscU0eSR/edit?usp=sharing&ouid=112854478400213800085&rtpof=true&sd=true
- Update spreadsheet: https://docs.google.com/spreadsheets/d/127W9zA8ExnUhLzaS1MRo6QyCiFo1B1PY/edit?usp=sharing&ouid=112854478400213800085&rtpof=true&sd=true

Changes performed:

- Added all the metadata and analysis files for human samples
- Added analysis files for the already wrangled mouse samples

**Comment by MightyAx** [comment]
Secondary Reviewer assigned: @idazucchi

**Comment by idazucchi** [comment]
Hello!
I've finished reviewing, overall it's good there are just a few small things to fix

**Specimen from organism**
- storage method: the field is enum, so cold on wet ice is not allowed. Maybe the best available option is fresh? in the sense that the specimen wasn’t frozen
 - known disease: you could consider adding epilepsy as disease, as it affects the brain sample

**Enrichment protocol**
- markers: the formatting rules are unclear —> either with spaces or ; 

**Analysis file**
- missing analysis protocol id

**Comment by ipediez** [comment]
Asked for data delivery to s3://hca-ncbi-cloud-data-iperez for the human FASTQ files

**Comment by ipediez** [comment]
Graph validator does not work OK with two submissions, waiting on a decision on how to proceed, or if we are gonna apply a workaround.

**Comment by ipediez** [comment]
Unlocked and exporting!

**Comment by jacobwindsor** [comment]
No longer blocked
