### ISSUE TITLE
Lavaert et. al. -Integrated scRNA-Seq Identifies Human Postnatal Thymus Seeding Progenitors and Regulatory Dynamics of Differentiating Immature Thymocytes

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#29]
### Dataset/group this task is for:

*Publication: Lavaert M, Liang KL, Vandamme N, et al. Integrated scRNA-Seq Identifies Human Postnatal Thymus Seeding Progenitors and Regulatory Dynamics of Differentiating Immature Thymocytes. Immunity. 2020 Apr. 
DOI: 10.1016/j.immuni.2020.03.019. 
PMID: 32304633

<https://doi.org/10.1016/j.immuni.2020.03.019>

The accession number for the sequencing data reported in this paper is GEO: GSE144870.

#### Associated files:

Google Drive:
<https://drive.google.com/drive/folders/1ehg_dhIM0PkQb06W3qObUygF0RBHX0ig>

### Wrangler responsible for this dataset/lab:

**Primary Wrangler:**
Ray

**Secondary Wrangler:**
@ami-day 

### Description of the task:

Contains CITE-seq data. There will be some metadata/barcoding collection that we need to work on to collect this data accurately.

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Assign the Primary Wrangler
- [x] Add dataset to the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE)
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data files
- [x] Receive data (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata
- [x] Check linking
- [x] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production and hand off tracking to data dashboard

### Acceptance criteria for the task:

- [x] Collect cell-gene expression matrices and cell type annotations if available
- [ ] Receive data and metadata (to a sufficient standard to submit dataset)
- [ ] Metadata and data pass Ingest validation
- [ ] Submit to DCP via Ingest

**Comment by ami-day** [comment]
@rays22 I have added the pre-converted metadata spreadsheet here: https://drive.google.com/drive/folders/1ehg_dhIM0PkQb06W3qObUygF0RBHX0ig of course it still needs manual curation too. Feel free to change the name of the folder, I couldn't find the folder you created for this project if you had done already.

**Comment by rays22** [comment]
> @rays22 I have added the pre-converted metadata spreadsheet here: https://drive.google.com/drive/folders/1ehg_dhIM0PkQb06W3qObUygF0RBHX0ig of course it still needs manual curation too. Feel free to change the name of the folder, I couldn't find the folder you created for this project if you had done already.

Thanks @ami-day for converting it. I will add/curate any necessary extra information from the paper or feedback from the contributor.

**Comment by rays22** [comment]
I sent a reminder about T&C forma and a custom metadata template spreadsheet to Marieke Lavaert on 1/6/2020.

**Comment by ami-day** [comment]
Hi @rays22 just checking you haven't heard back and aren't waiting on me to do the 2ndary review?

**Comment by rays22** [comment]
Hi @ami-day ,
No I have not heard back from them. Thanks.

**Comment by rays22** [comment]
I have transferred all the 27 fastq files originally submitted to SRA using the NCBI cloud data delivery service. The fastq files are in the wrangler/contributor bucket in directory named `Lavaert-issue29`.
```
CISE10_ADT_S21_I1_001.fastq.gz.1
CISE10_ADT_S21_R1_001.fastq.gz.1
CISE10_ADT_S21_R2_001.fastq.gz.1
CISE10_S10_I1_001.fastq.gz.1
CISE10_S10_R1_001.fastq.gz.1
CISE10_S10_R2_001.fastq.gz.1
CISE11_ADT_S22_I1_001.fastq.gz.1
CISE11_ADT_S22_R1_001.fastq.gz.1
CISE11_ADT_S22_R2_001.fastq.gz.1
CISE11_S11_I1_001.fastq.gz.1
CISE11_S11_R1_001.fastq.gz.1
CISE11_S11_R2_001.fastq.gz.1
TTA15_I1.fastq.gz.1
TTA15_R1.fastq.gz.1
TTA15_R2.fastq.gz.1
TTA16_I1.fastq.gz.1
TTA16_R1.fastq.gz
TTA16_R2.fastq.gz.1
s1_S1_I1_001.fastq.gz.1
s1_S1_R1_001.fastq.gz.1
s1_S1_R2_001.fastq.gz.1
s2_S2_I1_001.fastq.gz.1
s2_S2_R1_001.fastq.gz.1
s2_S2_R2_001.fastq.gz.1
s3_S3_I1_001.fastq.gz.1
s3_S3_R1_001.fastq.gz.1
s3_S3_R2_001.fastq.gz.1
```

**Comment by rays22** [comment]
* I have uploaded a new version of the metadata spreadsheet ([GSE144870-LavaertHumanThymus.xlsx](https://drive.google.com/drive/folders/1ehg_dhIM0PkQb06W3qObUygF0RBHX0ig)) to the gdrive that has passed all the tests in Ingest [Staging](https://staging.contribute.data.humancellatlas.org/submissions/detail?id=5fb56811f423490510b86dfb). @ami-day : it is ready for secondary review.
* The HCA application ontology needs to be updated so that [CITE-seq](http://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009294) is placed under the EFO branch `single cell library contruction`. It is already under the [single cell library contruction](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009294&viewMode=All&siblings=false) branch in the current EFO.

**Comment by ami-day** [comment]
@rays22 I'm wondering if you created a ticket for the above ontology term update with in the HCAO repo?

**Comment by ami-day** [comment]
@rays22 I have made a copy of the metadata sheet here with changes I made:
https://docs.google.com/spreadsheets/d/1BYfaPb8RVkSik7sZTsWD1XzpLCzqn-BA/edit#gid=1457586729

It mostly looks good to me.

**Here are my review comments below**

- I added names and descriptions next to biomaterial ids and protocol ids.

- I added 'unspecified' to the 'known disease(s)' field since the samples were taken from paediatric patients undergoing cardiac surgery (i.e. not healthy)

- Project contributors: I added your name, but the job role field needs to be added so you can enter 'data curator'. I also split the addresses into separate fields (institute/address/country). I added the corresponding contributor.

- I removed the pre-print from the publication tab.

- I merged the CD34+ enrichment step into the 3 separate SORT enrichment protocols.

- Library preparation protocol: I added more info. to the TotalSeq Abs and CITE-Seq description. 

- I agree with what you said above about updating the HCA application ontology so that CITE-seq is placed under the EFO branch single cell library construction. We should wait for the update before exporting this project (have you created an HCAO ticket for this?)

- I can't find where each sequence file is mapped to either CITE-Seq or standard 10X 3' v2 technology in NCBI or GEO. Where were you able to find this information?

**Comment by rays22** [comment]
This is blocked by <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/187>.

**Comment by rays22** [comment]
I have uploaded a file archive that includes matrices, barcodes and genes to <https://drive.google.com/drive/folders/1mKwzZl8NZ5gBRvME8N6klcDl__IuxVRe>.

**Comment by rays22** [comment]
> * I can't find where each sequence file is mapped to either CITE-Seq or standard 10X 3' v2 technology in NCBI or GEO. Where were you able to find this information?

@ami-day 
* **Figure 1.A** provides some information on the experimental design. It indicates that the `SORT 2` samples correspond to `2 donors / scRNAseq + CITEseq`. I have interpreted this as two pairs of samples from two donors provided input for separate 10x and CITE-seq experiments. This interpretation is supported by the number of sequence files in the dataset and their naming pattern. Figure 1 (A) also tells me that the rest of the donors and samples provided input for 10x scRNAseq experiments exclusively.
* **Figure S1.E** indicates that samples (specimens) from donors D1 and D2 have been processed by the `SORT 2` protocol and thus must have provided input biomaterials to subsequent CITE-seq and 10x protocols.
According to Fig. S1.E, another specimen pair from donors D1 and D2 have been processed by the `SORT 1` protocol. The only specimen from donor D3 has also been processed by the `SORT 1` protocol. 
Specimens from donors D4 and D5 have been processed by protocol `SORT 3` exclusively (based on Fig. S1E).

* The donor-->specimen-->cell suspension relationships in the table below are in agreement with the GEO metadata, the information in the text of the paper, as well as figures 1.A and S1.E. 
```
GEO Sample_characteristics_ch1  GEO sample relation GEO Sample title    GEO Sample_supplementary_file_1 Figs.1A and S1E]    GEO Sample relation
donor_organism.biomaterial_core.biomaterial_id  specimen_from_organism.biomaterial_core.biomaterial_id  specimen_from_organism.biomaterial_core.biomaterial_name   cell_suspension.biomaterial_core.biomaterial_name   enrichment_protocol.protocol_core.protocol_id process.insdc_experiment.insdc_experiment_accession
D1  SAMN14051827    D1_CITEseq  GSM4299781  CD34_enrichment_protocol||SORT2_enrichment_protocol SRX7691510
D2  SAMN14051826    D2_CITEseq  GSM4299782  CD34_enrichment_protocol||SORT2_enrichment_protocol SRX7691511
D1  SAMN14051825    CISE10_D1_scRNAseq  GSM4299783  CD34_enrichment_protocol||SORT2_enrichment_protocol SRX7691512
D2  SAMN14051824    CISE11_D2_scRNAseq  GSM4299784  CD34_enrichment_protocol||SORT2_enrichment_protocol SRX7691513
D1  SAMN14051823    S1_D1_scRNAseq  GSM4299785  CD34_enrichment_protocol||SORT1_enrichment_protocol SRX7691514
D2  SAMN14051822    S2_D2_scRNAseq  GSM4299786  CD34_enrichment_protocol||SORT1_enrichment_protocol SRX7691515
D3  SAMN14051821    S3_D3_scRNAseq  GSM4299787  CD34_enrichment_protocol||SORT1_enrichment_protocol SRX7691516
D4  SAMN14051820    TTA15_D4_scRNAseq   GSM4299788  CD34_enrichment_protocol||SORT3_enrichment_protocol SRX7691517
D5  SAMN14051816    TTA16_D5_scRNAseq   GSM4299789  CD34_enrichment_protocol||SORT3_enrichment_protocol SRX7691518
```

The `SRX` experiment accessions are linked to `SRR` run accessions in the NCBI SRA Run Selector. In turn, the `SRR` metadata contains the fastq file names. Actually, the [geo_to_hca.py](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/geo_to_hca_SOP.html#producing-the-metadata-spreadsheet) script has figured out the correct `SRX`-->`SRR`-->filename  relationships and filled them in automatically.

**Comment by rays22** [comment]
> * I added names and descriptions next to biomaterial ids and protocol ids.

The text you added to the **DONOR ORGANISM DESCRIPTION** fields look useful.
The donor names do not appear to differ from the biomaterial ids, so I am not sure if it adds anything useful. Maybe I could add names like `donor 1` instead of `D1` etc?
* * * *

> * I added 'unspecified' to the 'known disease(s)' field since the samples were taken from paediatric patients undergoing cardiac surgery (i.e. not healthy)

You are correct that we can not state that the donors were healthy.
I see why you would like to add `unspecified` to **KNOWN DISEASE(S)**. I do not think we can be sure if the thymus from these donors can be considered diseased or not.

You would add `unspecified` in a relational database field, because they usually use a [Closed World Assumption.](https://en.wikipedia.org/wiki/Closed-world_assumption)
However, theses are ontology fields:

```
donor_organism.diseases.text    donor_organism.diseases.ontology    donor_organism.diseases.ontology_label
specimen_from_organism.diseases.text    specimen_from_organism.diseases.ontology   specimen_from_organism.diseases.ontology_label
```

Ontologies use what is called an [Open World Assumption.](https://en.wikipedia.org/wiki/Open-world_assumption)
With the Open World Assumption (OWA) we do not make any assumptions based on the absence of statements. In the present case, we want to leave these ontology fields empty, and the lack of any statements does not meant that the donors were healthy (or normal PATO:0000461), we are just unable to list any **KNOWN DISEASE(S)**.
* * * *

> * Project contributors: I added your name, but the job role field needs to be added so you can enter 'data curator'. I also split the addresses into separate fields (institute/address/country). I added the corresponding contributor.

Thank you @ami-day . Should we add your name as well? You also worked on this dataset as a wrangler.
* * * *

> * I removed the pre-print from the publication tab.

I think it might be useful to keep it there, because it is the pre-print that is listed as an [HCA publication](https://www.humancellatlas.org/publications/), so it might look like as we missed wrangling an HCA publication. On the other hand, I can see your point of removing it, because the paper is peer-reviewed, and as such, it should be the reference for this dataset.
* * * *

> * I merged the CD34+ enrichment step into the 3 separate SORT enrichment protocols.

OK, that is fine.

The ontology annotations have disappeared after you merged the enrichment protocols. The `enrichment_protocol.method.ontology` and `enrichment_protocol.method.ontology_label` fields are empty in your version.
I have added them back. For example, I have added `EFO:0009108||EFO:0009109`.

- I had to fix the following error before I could successfully load your spreadsheet into Ingest UI:

```
An error occurred importing the file.
A link from a biomaterial with id SAMN14051827 to a protocol with id, "collection_protocol", is not found in the spreadsheet.
```

Apparently you have changed the `collection_protocol.protocol_core.protocol_id` in the `Collection protocol` tab, but you have not updated the same field in the `Specimen from organism` tab. 

There is a similar problem with `dissociation_protocol.protocol_core.protocol_id` that I had to fix before I could validate your version of the spreadsheet.

```
An error occurred importing the file.
A link from a biomaterial with id SRX7691510 to a protocol with id, "dissociation_protocol", is not found in the spreadsheet.
```

* Ingest has found 27 metadata errors, but fortunately they are all related to missing data files.

Now everything looks fine with your enrichment protocol merges.

* * * *

> * Library preparation protocol: I added more info. to the TotalSeq Abs and CITE-Seq description.

If you added the extra text to the description because you think the protocol in the Methods section of the paper and the supplementary material is quite short and missing key information, then I completely agree with you.
While your text provides some nice theoretical background about the library preparation method, I do not think it adds any practical information to help somebody reproduce the experiment. I do not think the extra text is necessary. I would also avoid using typographical symbols (e.g. trade mark symbol), because they tend to cause display problems for downstream users of the metadata due to various character encodings.
* * * *

> * I agree with what you said above about updating the HCA application ontology so that CITE-seq is placed under the EFO branch single cell library construction. We should wait for the update before exporting this project (have you created an HCAO ticket for this?)

We as [wranglers need to decide how to model CITE-seq metadata](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/187) and after that I can request an appropriate edit or new term in HCAO.

**Comment by rays22** [comment]
> ~Now everything looks fine with your enrichment protocol merges.~

I have reverted the secondary wrangler suggested changes related to enrichment protocol merges, because that makes the metadata invalid and fail validation.
After input from other wranglers, it is clear now that
1. you are not allowed to add two process ontology terms to the same protocol, and
2. it is fine to add two enrichment protocols as in my original version of the HCA spreadsheet.

**Comment by ami-day** [comment]
Thanks @rays22 for this feedback. 

I understand why you have reverted some changes (or plan to), and it sounds good to me. Also interesting to know about the 'open-world assumption' vs 'closed-world assumption' and agree the open-world assumption makes sense here.

**To answer some of your questions:**

- **The donor names do not appear to be different from the description, I'm not sure it adds anything:** I added the extra text assuming that users might query samples/metadata by the id, the name or the description (and not necessarily all). That's why I prefer to fill out all even if the information is duplicated.

- I didn't add my name: we don't usually do this for secondary reviewers.

- I removed the pre-print because the samples and data associated with the pre-print might differ vs. the actual publication following peer-review if changes/updates are made.

- I'm sorry that some of the protocol ontology and linking information disappeared when I made updates! and thankful ingest checks for this upon metadata upload.

- **We need to decide how to model CITE-seq metadata:** I thought we had decided in the wrangler meeting to keep how you had modelled it already? where the CITE-seq & 10X 3' v2 sequencing and the 10X 3' v2 sequencing only protocols are kept as 2 separate protocols, and CITE-Seq is placed under the EFO branch single cell library construction (once requested). Then, the library_preparation_protocol.library_construction_method.ontology_label for the CITE-Seq samples would be: CITE-seq||10X 3' v2 RNA sequencing. However, I am not sure if multiple ontology terms is valid for this field. I am also not sure if the multiple values entered in the library_preparation_protocol.input_nucleic_acid_molecule.text field is valid? (DNA-barcoded antibodies; polyA RNA)
@ESapenaVentura @mshadbolt do you have thoughts about this?

**Comment by rays22** [comment]
* I have uploaded the latest version of the HCA metadata spreadsheet as `GSE144870-LavaertHumanThymus.xlsx` to the [gdrive.](https://drive.google.com/drive/folders/1ehg_dhIM0PkQb06W3qObUygF0RBHX0ig)
* The metadata (excluding file uploads) in this version have passed ingest validation (including two library preparation protocols and the relevant CITE-seq and 10x library preparation ontology terms) on [staging.](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=6e6b10e4-448c-4b8f-8869-272bbeaeb6d2)
* Export to HCA is blocked, because of living donor data protection issues.

**Comment by mshadbolt** [comment]
FYI there is now a project in prod ingest with only project information available here: https://contribute.data.humancellatlas.org/projects/detail?uuid=dbd836cf-bfc2-41f0-9834-41cc6c0b235a
