### ISSUE TITLE
Investigate whether GCP dev credentials work on prod (& vice-versa)

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#292]

**Comment by lauraclarke** [comment]
Is this a security issue? I have created a security label to help identify security issues and I don't know if this one should get that label

**Comment by jacobwindsor** [comment]
Confirmed that the dev credentials work with the prod bucket with `gsutil ls  gs://broad-dsp-monster-hca-prod-ebi-storage/prod` and vice versa. Used `cloud auth activate-service-account --key-file terra-gcp-credentials-prod.json` and `cloud auth activate-service-account --key-file terra-gcp-credentials-dev.json`, repectively.

Is this a problem? AFAIK the dev credentials are used in the following two ways:

- By devs for operational work - defined [here](https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html#using-ingest-exporters-gcp-service-account)
- By the exporter

Devs need to access prod, dev, and staging buckets. Having different credentials will make things harder. Is it a security risk if only these two processes are using the credentials?

**Comment by aaclan-ebi** [comment]
I'm linking the SOP to setup access Terra staging area buckets here for reference
https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html#using-your-google-account
