### ISSUE TITLE
Update Terra Staging Access instructions

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#293]
https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html#setting-up-access-to-terra-staging-area

**Comment by clairerye** [comment]
I believe this has been done as per ticket #405 https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/405 so closing.
