### ISSUE TITLE
Project stuck exporting 429b

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#294]
Notified on slack: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1617828214099600

Project UUID: [05be4f37-4506-**429b**-b112-506444507d62](https://contribute.data.humancellatlas.org/projects/detail?uuid=05be4f37-4506-429b-b112-506444507d62)
Submission UUID:	[2f03df05-521c-**4115**-8964-bdef07c5dbd2](https://contribute.data.humancellatlas.org/submissions/detail?uuid=2f03df05-521c-4115-8964-bdef07c5dbd2&project=05be4f37-4506-429b-b112-506444507d62)

**Comment by MightyAx** [comment]
I think this was stuck behind: ebi-ait/hca-ebi-wrangler-central#72
I've restarted the exporter, hopefully this will release the pods for this project.

**Comment by MightyAx** [comment]
Have unstuck the exporter in ticket #403 so this should be in progress again.
