### ISSUE TITLE
Edit 'library construction method' ontologies

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#296]
We have been requested to update all non prime-specific `library_constuction_method` ontology terms to the specific 3' or 5' term.

In addition there are cases where there are case differences between the label specified in the ontology and the one provided in the spreadsheet which is causing the browser to display multiple options for the same method, e.g. 'Drop-Seq' vs 'Drop-seq'

I am also not sure if we should fix up the 'tag' vs 'end_bias' for some protocols while we are at it.

This sheet summarises all protocols in the system to date and points out where there are errors:

https://docs.google.com/spreadsheets/d/1Wk7SGxEz00AkNokYv3YlFHJVF9U6THKcrvgHARsnau8/edit#gid=0

**Comment by clairerye** [comment]
Dave has now made specific tickets to track this work so will close this ticket
