### ISSUE TITLE
GSE156707 - HumanHeartMaturationsnSeq

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#298]
**Primary Wrangler:**
Marion

**Secondary Wrangler:**
Ray

**Associated files:**

Google Drive:
https://drive.google.com/open?id=1LA9gWB3uCuoRo7OSY6tNZEGTLo4R1GXh

**Published study links**

Paper:
https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.120.051921

Accessioned data:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE156707

in ingest here: https://contribute.data.humancellatlas.org/projects/detail?uuid=bd400331-54b9-4fcc-bff6-6bb8b079ee1f

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by mshadbolt** [comment]
I have made contact with the author (Enzo) in order to get access to the paper and supplements. They seem enthusiastic about their paper being part of the HCA!

**Comment by mshadbolt** [comment]
Did large amount of wrangling from the paper and supplemental information.

Decided for now to only wrangle the single nuclei and bulk RNA and bulk ATAC from the fetal donors that had single nuclei sequencing as well. There is also organoid, mouse and ipsc cell line data and bulkRNA/bulkATAC from filtered cardiomyocytes from more donors. Not 100% sure on whether I should try to wrangle everything or focus on the snRNAseq.

Have ordered raw data from cloud delivery.

Will send a few questions to the authors on Monday.

**Comment by mshadbolt** [comment]
Sent through some questions

Have a first pass valid submission (apart from data files) here: https://contribute.data.humancellatlas.org/submissions/detail?id=607e5994dd9aab1232d2edb5&project=bd400331-54b9-4fcc-bff6-6bb8b079ee1f

All fastqs are in hca-util upload area in txt file in the brokering folder along with some graph diagrams.

**Comment by mshadbolt** [comment]
Currently in contact with authors to get some remaining metadata information and the analysed matrices.

Hoping to be finished for the next release.

**Comment by mshadbolt** [comment]
I received correspondence from Evangelyn and Belinda in order to get more metadata and analysis files. Now ready for secondary review.

**Comment by rays22** [comment]
## Secondary review
The metadata look fine and complete to me. I have only one question about one of the graph validation tests.

### 1. Graph validation test to check

>Test description
When a sequencing protocol is paired-end, test whether it has 2 or more files linked.

* [paired_end_2_files.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/paired_end_2_files.adoc)
    - The entities that cause the test to fail are:

```
    Fetal6_PCM1_RNAseq_R1.fastq.gz SRX8994893
    Fetal4_PCM1_RNAseq_R1.fastq.gz SRX8994891 
    Fetal5_PCM1_RNAseq_R1.fastq.gz SRX8994892
```

- Could you confirm that the correct `sequencing_protocol.paired_end` value should be `yes` yet we are expecting one fastq sequence file for the three processes above?

### 2. False graph validation errors
I will write bug report tickets so we can fix the following ingest graph validator tests to avoid the following false errors in the future.
Please, correct me if these were real errors.

1. [contains_cell_barcode_info.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/contains_cell_barcode_info.adoc)
    - The entity that causes the test to fail is: `bulkatacseq_library_protocol`
    - I think this test should be conditional depending on the `library_preparation_protocol.nucleic_acid_source` value.

> Test description
>When a sequencing protocol is non-10x, non-ss2, test whether metadata is complete.

2. [contains_umi_barcode_info.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/contains_umi_barcode_info.adoc)
    - The entity that causes the test to fail is: `bulkatacseq_library_protocol`
    - I think this test should be conditional depending on the `library_preparation_protocol.nucleic_acid_source` value.

>Test description
>When a sequencing protocol is non-10x, non-ss2, test whether metadata is complete.

3. [10x_has_more_than_2_files.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/10x_has_more_than_2_files.adoc)
    - I think this test should take into account and check the `sequence_file.lane_index` field before raising an error. 

>Test description
Processes using 10x library preparation protocols have 2 to 4 files linked.

**Comment by mshadbolt** [comment]
thanks for the review @rays22 
I think the one you point out is another false positive because those three fastq files are linked with the `bulkrnaseq_sequencing_protocol` which I specified as `paired_end` == no

I will sync files now to start validating

**Comment by rays22** [comment]
I have recorded the graph tests that produced the [false errors **here**](https://github.com/ebi-ait/ingest-graph-validator/issues/29#issuecomment-841132102 ) so that we can fix them at some point in the future.

**Comment by mshadbolt** [comment]
just clicked submit on this

**Comment by ami-day** [comment]
I will take this on

**Comment by ofanobilbao** [comment]
@ami-day I just moved this to Finished on the wrangling board as I believe that's the state. The only remaining thing would be the SCEA brokering that is being tracked in the SCEA board. Please, feel free to amend if it's not the case. Thanks!
