### ISSUE TITLE
Define requirements and potential solutions for suitable unique identifiers for papers and linking pre-prints to journal publications

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#30]
**Description of the task:**

- [ ] What would be the best unique bibliographic identifier for us to use when [tracking datasets](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/), pre-prints and journal publications? Consider the advantages and disadvantages of various bibliographic identifiers for tracking datasets and the source/related journal articles, pre-prints. The identifier should help us to avoid duplicate rows/records, i.e. not to add the same publication multiple times. It should also help programmatic queries and comparisons of bibliographic sets.
- [ ] How should we link pre-prints to the published journal articles? We need a way to link pre-prints and published journal articles when they are related to the same dataset to avoid redundant records.

**Acceptance criteria for the task:**

- [ ] Best bibliographic identifiers are selected
- [ ] A solution for linking pre-prints to final publications is proposed
- [ ] The [software-based tracking requirement document](https://docs.google.com/document/d/1JHAwe1cG344VWxEBqXiUaWkz53ZNVQU1vvHOogIXvk0) is updated to reflect all these

**Comment by lauraclarke** [comment]
I see this is tagged as operations, isn't defining software requirements development rather than operations? @clairerye ?

**Comment by ami-day** [comment]
@rays22 @lauraclarke I just noticed this ticket is still open, but I think Ray resolved this by adding DCP specific identifiers to the tracker?
