### ISSUE TITLE
Project Stuck Exporting 4e78

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#300]
Notified on Slack: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1618343411133700

Project UUID: [03c6fce7-789e-**4e78**-a27a-664d562bb738](https://contribute.data.humancellatlas.org/projects/detail?uuid=03c6fce7-789e-4e78-a27a-664d562bb738)
Submission UUID: [da17a2ee-dab3-**4a0f**-93fb-7b82fd9b8a4f](https://contribute.data.humancellatlas.org/submissions/detail?uuid=da17a2ee-dab3-4a0f-93fb-7b82fd9b8a4f&project=03c6fce7-789e-4e78-a27a-664d562bb738)

**Comment by MightyAx** [comment]
This errored due to rate limits, example:
```
{
  '@type': 'type.googleapis.com/google.rpc.ErrorInfo',
  'reason': 'RATE_LIMIT_EXCEEDED',
  'domain': 'googleapis.com',
  'metadata': {
    'service': 'storagetransfer.googleapis.com',
    'quota_limit': 'ReadOnlyRequestsPerMinutePerUser',
    'quota_metric': 'storagetransfer.googleapis.com/read_only_requests',
    'consumer': 'projects/612961917858'
  }
```

I'm going to redeploy the exporters now in the hope that this rate limit is resolved.

**Comment by MightyAx** [comment]
Unblocked, appears to be exporting, will check in tomorrow.

**Comment by MightyAx** [comment]
Not fixed, investigating.

**Comment by MightyAx** [comment]
One pod timed-out waiting for an upload to finish so that file was never marked complete.
I've verified the file exists, marked it as uploaded and deleted the pod, which will ensure the action is retried.

Other processes that were blocked waiting for that file to finish, have resumed and I can see that the submission has been marked complete.

**Comment by clairerye** [comment]
thank you!
