### ISSUE TITLE
Update to UCSC project 4082

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#302]
Data Browser Project: [7b947aa2-43a7-**4082**-afff-222a3e3a4635](https://data.humancellatlas.org/explore/projects/7b947aa2-43a7-4082-afff-222a3e3a4635)

Ingest UI Project: [7b947aa2-43a7-**4082**-afff-222a3e3a4635](https://contribute.data.humancellatlas.org/projects/detail?uuid=7b947aa2-43a7-4082-afff-222a3e3a4635)
Old Submission UUID: 5f4d719e-f974-**495d**-b16d-008fd463983e (Now Deleted)
New Submission [27868ae9-6938-**4f73**-b7e7-3eb5e016f80b](https://contribute.data.humancellatlas.org/submissions/detail?uuid=27868ae9-6938-4f73-b7e7-3eb5e016f80b&project=7b947aa2-43a7-4082-afff-222a3e3a4635)

Chat on slack: https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1618410267170000

1 process has been created per file instead of per group of files that will be analysed.
This would involve update deletions which are not scoped for any part of the DCP at the moment so we will not attempt to do this via updates

**Comment by MightyAx** [comment]
Actions:
1. Delete Terra Staging Bucket: 7b947aa2-43a7-4082-afff-222a3e3a4635
2. Delte ingest Submission: 5f4d719e-f974-495d-b16d-008fd463983e
3. Delete files in upload area

**Comment by MightyAx** [comment]
Rachel,

We have deleted:
- The terra upload
- The ingest upload area (and all the data files)
- The ingest submission

But we have kept the project so that the project UUID will be retained.

Please submit to the project from the data upload tab [here](https://contribute.data.humancellatlas.org/projects/detail?uuid=7b947aa2-43a7-4082-afff-222a3e3a4635), which will create an upload area for your data files.

Thanks

Alexie (on behalf of ingest operations)

**Comment by MightyAx** [comment]
New submission [9d69f0cf-4c5a-**45a3**-a799-b425332e0a79](https://contribute.data.humancellatlas.org/submissions/detail?uuid=9d69f0cf-4c5a-45a3-a799-b425332e0a79&project=bd400331-54b9-4fcc-bff6-6bb8b079ee1f) added to ingest, waiting for data file to be re-uploaded.

**Comment by ESapenaVentura** [comment]
Sorry, I need to reopen this - What was done here?

The submission still has an incorrect number of bundles

**Comment by clairerye** [comment]
Enrique has re-started this conversation with UCSC and they will update the spreadsheet and make a new submission keeping the same project UUID

**Comment by ke4** [comment]
As Enrique asked me I did the following steps:
- Deleted the submission from ingest (UUID:27868ae9-6938-4f73-b7e7-3eb5e016f80b, objectId: 6079c3c9dd9aab1232d2d4db)
- Removed the project related data from Terra staging prod bucket (project UUID: 7b947aa2-43a7-4082-afff-222a3e3a4635)

**Comment by ESapenaVentura** [comment]
The new submission is being exported - Once it's exported, I'll ask Rachel if I can submit the import form!
