### ISSUE TITLE
GSE119373 Human retinoic acid-regulated CD161+ regulatory T cells support wound repair in intestinal mucosa

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#303]
* project short name: GSE119373_intestinal_mucosa

### Associated files:

* Google Drive: 

### Published study links

*  Povoleri GAM, Nova-Lamperti E, Scottà C, et al. Human retinoic acid-regulated CD161<sup>+</sup> regulatory T cells support wound repair in intestinal mucosa. Nature Immunology. 2018 Dec;19(12):1403-1414. [DOI: 10.1038/s41590-018-0230-z](https://doi.org/10.1038/s41590-018-0230-z). PMID : [30397350](http://europepmc.org/article/MED/30397350)
* Accessioned data:
[GSE119373](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE119373)
[S-EPMC6474659](https://www.ebi.ac.uk/biostudies/studies/S-EPMC6474659) 

### Key Events

- [ ] convert published metadata to HCA spreadsheet
- [ ] manually curate dataset to meet HCA metadata standard
- [ ] collect any matrix and cell-type annotation files
- [ ] upload sheet to validate metadata
- [ ] check linking using ingest graph validator
- [ ] transfer raw files to ingest to validate data files
- [ ] ask the Secondary Wrangler for an end-to-end review of the project
- [ ] submit dataset to Production 
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
This dataset contains GDPR subjects (3 UK blood donors), probably needs to be moved to stalled

**Comment by Wkt8** [comment]
Closing until it comes back up again as it makes no sense to be in the Queued for wrangling column as opposed to other tickets which are higher priority
