### ISSUE TITLE
Review HCA_to_scea documentation

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#308]
We need to review https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/hca_to_scea_tools_SOP.html and make sure that the whole process can be run without previous knowledge of the tools.

Identified missing bits:
- How to assign a HCAD accession
- How to send fastq files
- How and when to update the ticket with information about process in SCEA
- How to get updates about process on the SCEA dataset
- How to check a dataset has been successfully brokered into SCEA

**Acceptability criteria**:
- [x] The documentation has been reviewed and modified
- [x] A tool-agnostic wrangler reviews the SOP after doing a full conversion of a dataset and lists anything missing in this ticket
- [x] Ami will again update the documentation to cover any missing or unclear information in a PR
- [x] Another tool-agnostic wrangler reviews the SOP and if needed, suggests further changes, or closes this ticket to reflect it is done.

**Comment by Wkt8** [comment]
I'm taking on vague responsibility with doing this - but this probably would be better with more people!

**Comment by Wkt8** [comment]
I have written a PR to the documentation for Ami to have a look at, which includes links, things that were missing, and things that I thought were unclear for a first-time user. 

The PR is here: https://github.com/ebi-ait/hca-to-scea-tools/pull/42

**Comment by Wkt8** [comment]
Apart from the things in the PR, I do think that the method of immediately updating the output E-HCAD-id in the tracker as soon as possible is not sustainable - especially if you want to generate another output E-HCAD-id (e.g. same project, different tech, therefore needs to be split up) to link, but have not created that spreadsheet yet. Wranglers may need to be in contact with one another when they start SCEA wrangling. 

e.g. Notify in hca-wrangler-metadata that they are doing some SCEA wrangling to ensure the E-HCAD-id does not get duplicated. 

Actually, I might add this to the PR.

**Comment by ami-day** [comment]
> Apart from the things in the PR, I do think that the method of immediately updating the output E-HCAD-id in the tracker as soon as possible is not sustainable - especially if you want to generate another output E-HCAD-id (e.g. same project, different tech, therefore needs to be split up) to link, but have not created that spreadsheet yet. Wranglers may need to be in contact with one another when they start SCEA wrangling.
> 
> e.g. Notify in hca-wrangler-metadata that they are doing some SCEA wrangling to ensure the E-HCAD-id does not get duplicated.
> 
> Actually, I might add this to the PR.

I agree @Wkt8, I wasn't sure what was best here. Since it isn't every day or even every week that we individually convert datasets to SCEA format, it might be better that the --accession argument becomes mandatory, and we check the tracker sheet for ourselves, and with other wranglers, to choose a suitable accession. I will update the script to reflect this, unless you think otherwise?

**Comment by ami-day** [comment]
I have updated the script.py and README.md to reflect the above discussion. It is probably best if 1 other wrangler reviews the SOP and makes sure it all makes sense to them? Either @rays22 or @ESapenaVentura once they are back from annual leave. Or feel free to just close the ticket.

**Comment by ESapenaVentura** [comment]
I have been trying to follow the SOP, for the most part is pretty straight forward but I think it needs a couple of clarifications in certain areas:
- Adding the fastq uris is kinda confusing. I feel there should be a guidance of some type, tips on how to get the fastq uris, what is acceptable (e.g. links starting with `ftp.` are not recognised by the validator), and a list of the fields needed. Saying "See examples" is not really much of a guidance and may be confusing for some people
- The controlled vocabulary bit in the SDRF curation instructions is a bit unclear. What document should I be looking from in the folder shared? What fields in the SDRF should I be looking for? Do I need to apply this curation after the automatic conversion or does the tool apply it and I only need to apply it for new fields I want to add?
- The validator instructions (How to run it, install it etc) need to be updated. A couple of ideas:
   - Include where to find the errors (In my run I found these errors: `SC-E03, SC-E04, SC-E02, SC-E05, GEN-E06`, and I have no idea where should I look)
   - If you include the `hca` flag when running the tool it looks for 2 fields not mentioned in the SOP, `HCA bundle UUID` and `HCA bundle version`

I am currently stuck in the validation step so I can't progress further for now, but will write further suggestions once I finish it

**Comment by ofanobilbao** [comment]
Tagging @ESapenaVentura. Otherwise easy to forget that he is going to continue giving suggestions. And moving to In Progress, as the task already started way back

**Comment by ami-day** [comment]
Hi @ESapenaVentura Thanks for the review!
I have updated the SOP to reflect the above comments: https://github.com/ebi-ait/hca-to-scea-tools/pull/47
I have removed the sentence about controlled vocabulary as I think the shared doc. from scea is confusing. All the required controlled vocab. terms should be added automatically to the sdrf file. I do think that when unsure about a particular column name and what the respective values should be, it is very helpful to look at a few of the uploaded E-HCAD datasets in the Gitlab page as the format and column names used should be consistent and therefore act as a example/template to follow. This is what I have been doing when I am not completely sure.
In terms of the validator questions: I have asked on the scea slack channel about those.

**Comment by ofanobilbao** [comment]
What is the status of this? Is it done? From what I can see it has been reviewed by at least two wranglers, which was the remaining acceptance criteria.

**Comment by ESapenaVentura** [comment]
I have tried running the SOP to convert [this dataset](https://app.zenhub.com/workspaces/brokering-to-scea-60af47517f6e370017b3d5bf/issues/ebi-ait/hca-ebi-wrangler-central/193)

I am currently stuck at the point of SDRF curation, due to the files not being publicly available as fastqs. In the original submission, we converted the files to fastqs using `bamtofastq` from nunofonseca's toolset.

So far, I have a couple of comments about the SOP:

## SOP review
- Missing instructions on how to copy files (Spreadsheets) to the EC2: Some kind of instructions would be nice, even an example scp command!
- Tracking by the DTS for the next E-HCAD- accession available is a bit tricky. Isn't there any other way?
- On the flags and values table:
    - The `-name` part of the table is a bit weird formatted
    - The `-ac` field requires a bit more explaining (Especially since it does not appear in the example command)

- On the IDF curation:
    - I am a bit confused as to why it points to the fastq provider tool from SCEA? what should we look for there?
    - *You need to add the chosen factor values given as an input argument in the idf file in both of these fields: Experimental Factor Name and Experimental Factor Type* : These values seem to be already added, is the SOP outdated on this?
- On SDRF curation:
    - It's not clear where the examples are, there should be a link to SCEA's gitlab for it
    - It's not super clear how to get the FASTQ URIs, some more guidelines/tips would be nice!
    - For the fastq uris and factor value, the actual name of the column is not super clear unless you take a look an example

I think that is mostly it!

I have timeboxed it for the first steps:
- Converting spreadsheet to SDRF/IDF: 20-30 minutes, depending on how much info you need to extract for the command and if you know where to extract it from
-  IDF curation: <20 minutes. It took me around 20 minutes but I was just confused about a couple of fields, I think with some practice this can easily be around 10 minutes

**Comment by ofanobilbao** [comment]
@ESapenaVentura @Wkt8 happy to move this to Review/QA so that Ami can take your feedback and improve/amend the SOP?
