### ISSUE TITLE
Roser Vento - Endometrium across menstrual cycle

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#31]
**Primary Wrangler:**
@ESapenaVentura 

**Secondary Wrangler:**
TBD

**Associated files:**

Google Drive:  https://drive.google.com/drive/folders/19JgmlhKOnQFE3wtmgJ2wVa2-TGD3pASU

**Key Events**

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data files
- [x] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata
- [x] Run graph validator
- [x] Check linking
- [x] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Get final approval of submission including metadata spreadsheet and data files
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Email UX to inform that they're ready to send survey

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by Wkt8** [comment]
This is now a HCA publication, see email: 

Dear Roser

Thank you for submitting your recent paper entitled “Mapping the temporal and spatial dynamics of the human endometrium in vivo and in vitro [biorxiv.org]” for consideration by the HCA Publications Committee.

**Comment by ESapenaVentura** [comment]
The HCA publication email links to a preprint, but there's an actual publication in the _Circulation_ journal: [Integrated Single Cell Atlas of Endothelial Cells of the Human Lung](https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.120.052318)

Raw data is in [GSE164829](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164829)

**Comment by ESapenaVentura** [comment]
Data can be found here https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10287/

Preprint is here https://www.biorxiv.org/content/10.1101/2021.01.02.425073v1

This is an MRC + WSSS dataset

**Comment by ESapenaVentura** [comment]
https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10287/ is undergoing maintenance to add the new file so will work on this when available

**Comment by ESapenaVentura** [comment]
@Wkt8 about your review!

Donor organism tab:
- I got it from inferring from the name of the samples (MRC_Endo). Good eye catching the third donor, I mislabelled it!

Dissociation protocol:
- I have moved that part of the protocol to enrichment :)

I'm going to create the submission!

**Comment by ESapenaVentura** [comment]
Looks great in the browser

Closing!

**Comment by ESapenaVentura** [comment]
Updated metadata of 3 of the donors (E1, E2, E3) to normal

**Comment by ofanobilbao** [comment]
@ESapenaVentura updated and sent import form for Release 12

**Comment by ESapenaVentura** [comment]
Update looks good in the browser

**Comment by ofanobilbao** [comment]
@ESapenaVentura this is now published as peer reviewed paper.

DOI: 10.1038/s41588-021-00972-2
PMID: 34857954
https://www.nature.com/articles/s41588-021-00972-2
