### ISSUE TITLE
Review lattice --> DCP mapping

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#310]
**Description of the task:**

Lattice has approached us with a list of unmapped fields Lattice --> HCA, as one of the final checks to know if they have missed anything in their approach

This is a public repository so I'm not going to post the file they sent, all wranglers should have had received the email with the title `Lattice-to-DCP schema mapping`.

We need to review the mapping and come back to lattice with suggestions/feedback/approval.

**Acceptance criteria for the task:**

- [ ] The document has been reviewed thoroughly. Each unmapped lattice field will be checked against the schema to see if we can host it.
- [ ] An answer has been written and sent to lattice

**Comment by Wkt8** [comment]
@Wkt8 to discuss with Claire

**Comment by Wkt8** [comment]
Have decided to close the ticket as lattice have since submitted projects to the DCP. Can revisit this if it is an issue again.
