### ISSUE TITLE
PRJNA640427 A Protocol for Revealing Oral Neutrophil Heterogeneity by Single-Cell Immune Profiling in Human Saliva

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#311]
* project short name: PRJNA640427_human_neutrophils

### Primary Wrangler:
Ray

### Secondary Wrangler:
Wei

### Associated files:

* Google Drive: [PRJNA640427_human_neutrophils](https://drive.google.com/drive/folders/1imiv4d74z8mNbMRkE51GoHd_8bLNGfbl)
* hca-util s3 area name: `human_neutrophils-issue311`

### Published study links

*  Choudhury SN, Novotny M, Aevermann BD, et al. A Protocol for Revealing Oral Neutrophil Heterogeneity by Single-Cell Immune Profiling in Human Saliva. Research Square; 2020. [DOI: 10.21203/rs.3.pex-953/v2.](http://doi.org/10.21203/rs.3.pex-953/v2)

### Accessioned data:
* [PRJNA640427](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA640427) --> [SRA Run Selector](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA640427&o=acc_s%3Aa)
* Secondary Study Accession: [SRP271375](https://www.ebi.ac.uk/ena/browser/view/PRJNA640427)

### Key Events

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] collect any matrix and cell-type annotation files
- [x] upload sheet to validate metadata
- [x] check linking using ingest graph validator
- [x] transfer raw files to ingest to validate data files
- [x] ask the Secondary Wrangler for an end-to-end review of the project
- [x] submit dataset to Production

**Comment by rays22** [comment]
- [x] I have transferred the sequence data files to the `hca-util` area called `human_neutrophils-issue311` for storage until the files can be uploaded to Ingest.
- [x] I have cleaned up the temporary bucket that I used for the [NCBI cold storage data file transfer.](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/NCBI_SRA_cold_storage_how_to.html)

**Comment by rays22** [comment]
The [metadata spreadsheet](https://drive.google.com/file/d/1fTXiZB2h_ej_tWev_BZN48W7V9EEV5JQ/) is ready for secondary review.
#### NOTE
The **Project** tab in the spreadsheet can be ignored, because I curated the project-level metadata directly in Ingest UI.
I need the **Project** tab only for testing.

**Comment by Wkt8** [comment]
Assigning self for secondary review

**Comment by Wkt8** [comment]
Ignoring the Project tab as you said! 

Enrichment Protocol
* Add 10um as minimum size selected for centrifugation and filtering steps. 
* This might be a stylistic difference in wrangling, but I would put a bit more information in the enrichment protocol description? 
    * For enrichment_protocol1 I would put ‘Centrifuged and filtered through 40um, 20um and 10um cell strainers in succession.'

Cell Suspension
* Need to drag down and fill in the Genus Species, Genus Species ontology ID, Genus Species Ontology Label (Homo sapiens, NCBITaxon:9606)
* Same with filling in the selected cell type ontology label and ontology id (CL:0000775, neutrophil) 

Sequencing Protocol:
* Might change the description from ‘a suitable Illumina NGS platform’ to ‘an Illumina NovaSeq 6000) as It is already stated that is the instrument used. I believe the MiSeq is only used as a quick version to randomly test quality rather than to actually produce usable sequencing data 

Also, don’t forget to delete the schema’s tab! 
Linking and ontologies look good 🙂

**Comment by rays22** [comment]
- [ ] Enrichment Protocol
The paper itself is basically a very detailed protocol with some data for illustrations. This is why the protocol in the metadata may be too brief. OK, I am adding the size selection values and more information as you suggest.

- [ ] Cell Suspension
I have double checked and the Genus Species, Genus Species ontology ID, Genus Species Ontology Label are already filled in on all lines in tabs Cells Suspension, Donor Organsism and Specimen from organism.
Similarly, I have double checked and the selected cell type ontology is also already filled in the spreadsheet.
I prefer to double checking field to missing any of them! :)

- [ ] Sequencing Protocol:

I think the paper is trying to convey that the protocol can work with any a 'suitable Illumina NGS platform'.
However, I agree that it is also useful to know the specific model that was used in this instance as an example for what a suitable NGS platform can be.
I am changing the text to reflect what you suggest and include the information on the specific model.
 
The purified pooled-NexteraXT library was subjected to paired-end sequencing on an Illumina NovaSeq 6000 platform.

- [ ] Deleted the schema tab.

**Comment by rays22** [comment]
I have copied the data files to Ingest prod.

**Comment by rays22** [comment]
The export of the dataset is complete.

**Comment by rays22** [comment]
Filled in the Broad `HCA Import Request for Production Releases` form.

**Comment by ofanobilbao** [comment]
@rays22 I just moved this to Finished in the Wrangling Board as I believe that this is the state on the DCP journey and that what remains is only the brokering to SCEA, which is going to be tracked on the SCEA board. Is that correct? If not, feel free to move it in the board. Thanks!

**Comment by rays22** [comment]
> @rays22 I just moved this to Finished in the Wrangling Board as I believe that this is the state on the DCP journey and that what remains is only the brokering to SCEA, which is going to be tracked on the SCEA board. Is that correct? If not, feel free to move it in the board. Thanks!

@ofanobilbao Yes, I believe the DCP journey of this project is complete.
Thanks for moving it to the `Finished` column.
