### ISSUE TITLE
GSE132465 Lineage-dependent gene expression programs influence the immune landscape of colorectal cancer

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#315]
### Project short name:
GSE132465_colorectal_cancer

### Primary Wrangler:
Ray
### Secondary Wrangler:
Wei

### Associated files

* Google Drive folder: [isslue315-GSE132465_colorectal_cancer](https://drive.google.com/drive/folders/1KsFi0ZobU9bWafEZRvkaGdRgIOSZV54P)

### Published study links

* Paper:
Lee HO, Hong Y, Etlioglu HE, et al. Lineage-dependent gene expression programs influence the immune landscape of colorectal cancer. Nature Genetics. 2020 Jun;52(6):594-603. DOI: [10.1038/s41588-020-0636-z](https://doi.org/10.1038/s41588-020-0636-z)
PMID: 32451460

* Accessioned data: 
    * Samsung Medical Center (SMC) metadata and matrix files: [GSE132465](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE132465)
    * [GSE132457](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE132457)
    * The raw scRNA-seq data of the SMC cohort are available in the European Genome-phenome Archive database (EGAS00001003779, EGAS00001003769).
    * KU Leuven (KUIL3) metadata and matrix files: [GSE144735](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144735)
    * KUL3 cohort raw scRNA-seq data: [E-MTAB-8410](http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-8410)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by lauraclarke** [comment]
@rays22 I am confused by your creating a ticket for this one, it seems to be managed access cancer data https://www.nature.com/articles/s41588-020-0636-z#data-availability

Is this a HCA pub or has a contributor contacted us about it?

**Comment by rays22** [comment]
> @rays22 I am confused by your creating a ticket for this one, it seems to be managed access cancer data https://www.nature.com/articles/s41588-020-0636-z#data-availability
> 
> Is this a HCA pub or has a contributor contacted us about it?

I created the ticket so that wranglers can pick a new published dataset without spending time to identify a suitable project from the dataset tracking sheet. My understanding was that I was supposed to create a backlog of about 10 dataset issues for this reason.
I chose this dataset for the backlog, because I could not find any other that would be in a higher priority category according to the document that defines [HCA eligibility criteria “once and for all”](https://docs.google.com/document/d/1mkRIRyHe25UkJ1yKfGqSrFxXed0bqRcaJ-SMKFFEmEk/).

A. Directly contributed data: they are all already being processed and have github issues assigned to primary wranglers.
B. Data from official Human Cell Atlas publications: I could not find any new suitable HCA publication in the dataset tracking sheet that is not already being wrangled.
C. Published Data
a. **Be referenced in a peer-reviewed journal or be available as pre-print:** This peer-reviewed paper is published in a high-profile scientific journal.
b. **Contain at least some samples derived from healthy human donors.** It contains matched normal tissues samples.
Arguably, the donors are not healthy, but some of the tissue samples are assumed to be normal by the research scientist and peer-reviewers.
c. **Be derived from a recognised single cell technology.** Yes, 10X v2 3' is a recognised technology.

The raw sequence data is managed access, but the expression matrices are available publicly.
My understanding is that managed access data would be still valuable for the HCA.

This published study appears to match our eligibility criteria and I could not find enough datasets matching higher priority categories. I believe wranglers can always pick higher priority projects to wrangle, but when they are scarce they still have a choice to do datasets like this.
 
Let me know if my explanations are not addressing the issues causing you confusion.

**Comment by lauraclarke** [comment]
I guess I surprised that a managed access cancer dataset was highest up our eligibility criteria

**Comment by rays22** [comment]
I have collected [6 cell annotation and expression matrix files for this project.](https://drive.google.com/drive/folders/1E8tn4x-YNCm7RDsA9Nr_FhELNGVQhOKO)

**Comment by rays22** [comment]
I have collected [3 additional cell annotation and expression matrix files for this project.](https://drive.google.com/drive/folders/1E8tn4x-YNCm7RDsA9Nr_FhELNGVQhOKO)

**Comment by rays22** [comment]
I have uploaded a valid [metadata spreadsheet to the gdrive.](https://docs.google.com/spreadsheets/d/1J61Mm_vzfUxxq4QIAB_xW7M7AJkUGnHZ)
Some of the project donors are living Europeans. The raw data related to the Korean donors are controlled access (in EGA).
I am planning to upload the matrix files with the metadata to the DCP.

**Comment by Wkt8** [comment]
Hey Ray, this looks great!!! Just a few small comments and questions, but overall - it looks really clean, really organised. Well done!

**Project**
Add GSE144735 and GSE132257 into the GEO accessions 
Add E-MTAB-8410 and E-MTAB-8412 to the ArrayExpress Accessions


**Enrichment Protocol**
Maximum size for SMC_enrichment_protocol2 is 70um


**Sequencing Protocol**
I believe that GPL20301 may be sequencing in paired-mode ‘yes’, due to the text in the paper stating 

'Sequencing was performed in 100 bp paired-end modeon a HiSeq 4000 system (Illumina) at 120 million reads per sample.'



**Library Preparation Protocol**
Typo in Library Preparation Protocol name ‘single cell 3’ v2 librarly preparation protocol’


**Analysis Protocol:**
What is the relevance of having data processing protocol 1a AND 1b (they are both identical?) and data processing protocol 2a AND 2b (they are both identical?)

**Comment by rays22** [comment]
Thank you @Wkt8 for the secondary review.
Adding the EGA accessions is blocked by <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/382>.

**Comment by rays22** [comment]
Thank you Wei for the secondary review. I have uploaded the [updated metadata spreadsheet to the gdrive](https://docs.google.com/spreadsheets/d/1J61Mm_vzfUxxq4QIAB_xW7M7AJkUGnHZ/edit?rtpof=true#gid=1087179674)
and [Ingest prod.](https://contribute.data.humancellatlas.org/projects/detail?uuid=c715cd2f-dc7c-44a6-9cd5-b6a6d9f075ae)

- [ ] I still need to add the EGA accessions.

* * * *

- [x] Enrichment Protocol:

> Maximum size for SMC_enrichment_protocol2 is 70um

I have added `70` as the maximum size value.

- [x] Sequencing Protocol

> I believe that GPL20301 may be sequencing in paired-mode ‘yes’, due to the text in the paper stating

You are right that it should be `yes`, but I was told that the wranglers agreed some time ago to put `no` in case it was a 10x experiment. I just wanted to be consistent here with earlier metadata curation, but I see your point that it does not look correct.

- [x] Library Preparation Protocol

> Typo in Library Preparation Protocol name ‘single cell 3’ v2 librarly preparation protocol’

Fixed.

- [x] Analysis Protocol:

> What is the relevance of having data processing protocol 1a AND 1b (they are both identical?) and data processing protocol 2a AND 2b (they are both identical?)

**Comment by rays22** [comment]
Thanks to the fix in <https://github.com/ebi-ait/dcp-ingest-central/issues/387>
I can add the EGA accessions now.

**Comment by rays22** [comment]
* I have exported the project to the DCP and [filled in the data import form.](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#exporting-the-submission-to-dcp)
* Target: Release 8.

**Comment by ESapenaVentura** [comment]
EGA accessions now are showing up properly

Closing!
