### ISSUE TITLE
Error syncing 2 files to ingest 

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#316]
Dataset submission page: https://contribute.data.humancellatlas.org/submissions/detail?uuid=b3c6a0c2-b74c-4daf-8391-30e9c3493322&project=9ec2e9e4-e8e9-46c7-b6f7-477e9b332dbd

I synced many files and 2 of these files caused an error: they can not be opened.
I have re-uploaded 2 new files with the same content, but we different names. The file names changed  because I had uploaded them from an alternative source. I changed them in the UI by clicking edit and renaming them with 2 newly uploaded files.
The old names were descriptive whereas the new names follow the ENA Run Accession convention ERR[0-9].fastq.gz. After syncing the new files, I still see the same old error referring to the old file names. Any chance you could somehow fix this?

**Comment by jacobwindsor** [comment]
Renaming files is not supported currently! There is [a ticket](https://github.com/ebi-ait/dcp-ingest-central/issues/290) to disallow renaming in ingest. @ami-day to make a new submission

**Comment by clairerye** [comment]
I am curious @ami-day why you wanted to rename the files. I am wondering if this was a one off or something that happens commonly and so if we should be supporting renaming as a feature.
