### ISSUE TITLE
Wrangling of new dataset: GSE124494 (pre-converted by geo-to-hca.py)

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#32]
**Dataset/group this task is for:**

GSE124494

**Wrangler responsible for this dataset/lab:**
Enrique

**Description of the task:**

- [ ] Complete conversion of the dataset by manual curation. The pre-converted version can be found here: https://drive.google.com/drive/folders/1zWFxJ1RIx_2sl2_kpBH437hH6yegZIB3

- [ ] Secondary review of dataset

- [ ] Validate the dataset by uploading to ingest

- [ ] Validate the dataset with graph validator?

- [ ] Add to list of datasets 'Complete' for MVP: https://docs.google.com/spreadsheets/d/1DfRFfZpZEmWU6aubKwIZ4D0lfm038IW0fmHRigS8yBU/edit#gid=552473761

**Comment by ESapenaVentura** [comment]
I will take this dataset for this sprint!

**Comment by ESapenaVentura** [comment]
I have taken a look at the dataset. Looks interesting, I have filled a couple of rows but I wanted to try and download the files before proceeding and there is a strange thing about this dataset. 

Taking a look at the ENA warehouse https://www.ebi.ac.uk/ena/data/warehouse/filereport?accession=SRP175077&result=read_run it looks like for each SRR accession there is only 1 file, and e.g. SRR8387856 and SRR8387857 are R1 and R2 of the same prep.

But taking a look at SRA [SRR8387856](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8387856) and [SRR8387857](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8387857), it suggests that there are 2 different sets of fastq files (probably coming from the same cell suspension/library prep).

I can't proceed without the files and this dataset does not have too many cells for it to be worth spending days investigating this issue. @lauraclarke should we deem it as unsuitable? For now I just put the status "blocked" in the tracking sheet

**Comment by lauraclarke** [comment]
Thanks @ESapenaVentura I think this sounds reasonable, if it is a low cell count dataset and the effort involved in figuring out the files is high it is likely no worth it.

Can you move this ticket into the icebox?

**Comment by ami-day** [comment]
@ESapenaVentura @gabsie shall we close this ticket and move the status to ineligible in ingest?
