### ISSUE TITLE
contributor account for: Ioannis (Giannis) Moustakas

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#323]
Please create an account a contributor.

*Contributor details:*
* name: Ioannis (Giannis) Moustakas
* email: I.Moustakas@lumc.nl

Request Details:
* Requested by: Parisa Nejad
* [slack link](https://embl-ebi-ait.slack.com/archives/C021LFT41DG/p1620762435000100)

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by jacobwindsor** [comment]
Email from Ioannis: 

"Dear Jacob,

Thank you for your mail and for sharing the access keys through google docs. I had a quick look at the instructions and they appear clear to me.

It might take some time before I can upload the files, as I will soon leave for holidays and I am not sure I can complete the task before that time. In any case I will mail you when the process is complete."
