### ISSUE TITLE
Orphaned Library Preparation Protocol

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#331]
The library_preparation_protocol_id (s)

a56bedfb-f2d1-4984-a468-b4375aa116ad
f151bb74-b149-4992-9728-923f1943968f 

 do not seem to be connected to any project through links.

See row 72 in https://docs.google.com/spreadsheets/d/1Wk7SGxEz00AkNokYv3YlFHJVF9U6THKcrvgHARsnau8/edit#gid=0

For context see https://github.com/HumanCellAtlas/dcp2/issues/13

**Comment by clairerye** [comment]
If these are orphaned protocols, are they ever shown anywhere? I suspect we could spend a long time tracking these down without any useful output.

**Comment by rays22** [comment]
1. a56bedfb-f2d1-4984-a468-b4375aa116ad
    - This protocol belongs to project `b176d756-62d8-4933-83a4-8b026380262f`.
    - This `library_preparation_protocol` appears to be linked to other metadata entities in the metadata that we have in Ingest UI. I am not sure what to fix, because it does not appear to be an orphan in the project metadata that I could edit.
2. f151bb74-b149-4992-9728-923f1943968f
    - I have not been able to find this protocol UUID in the metadata of any of the projects that we had exported from Ingest to `gs://broad-dsp-monster-hca-prod-ebi-storage/` or `gs://broad-dsp-monster-hca-dev-ebi-staging/`.

**Comment by ofanobilbao** [comment]
Maybe we need to make a decision on whether we still want to spend more time on this or close it. No-one has complained and it's been 1.5 years since it was open

**Comment by ofanobilbao** [comment]
@gabsie based on Claire's comments on the ticket and the fact no-one has complained in the last 1.5 years, I would suggest we close this ticket. Thoughts?

**Comment by gabsie** [comment]
agree, kill it
