### ISSUE TITLE
Library construction ontology now exists for null ontology_ids and can be updated

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#332]
For context see https://github.com/HumanCellAtlas/dcp2/issues/13

See rows 2,3,4 of https://docs.google.com/spreadsheets/d/1Wk7SGxEz00AkNokYv3YlFHJVF9U6THKcrvgHARsnau8/edit#gid=0

Project Detail Page | project_id | library_preparation_protocol_id | ontology_id | ontology_label | text
-- | -- | -- | -- | -- | --
https://data.humancellatlas.org/explore/projects/88ec040b-8705-4f77-8f41-f81e57632f7d | 88ec040b-8705-4f77-8f41-f81e57632f7d | 5bd07f13-2672-4a90-8ae4-97ca56b1ac23 | null | null | sci-RNA-seq
https://data.humancellatlas.org/explore/projects/88ec040b-8705-4f77-8f41-f81e57632f7d | 88ec040b-8705-4f77-8f41-f81e57632f7d | 5e21e36c-f789-42f1-b81c-f8e280622d78 | null | null | Seq-Well
https://data.humancellatlas.org/explore/projects/88ec040b-8705-4f77-8f41-f81e57632f7d | 88ec040b-8705-4f77-8f41-f81e57632f7d | ee388b7a-9eed-40ad-be52-9626db47a204 | null | null | CEL-seq2

The terms  sci-RNA-seq, Seq-Well, and CEL-seq2

now exist under OBI:0000711 

https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo/OBI_0000711

and the ontology IDs for these library preparation protocols can be updated.

**Comment by clairerye** [comment]
We agreed these should be updated now the terms are available and we should be able to do this is a straight forward manner using updates in the UI.

**Comment by rays22** [comment]
I tried to edit the ontology labels of the library preparation protocols for this project in Ingest, but the `Protocols` tab failed to load on several attempts on 2021-05-28.
The tab seemed to be stuck in a state of
`Loading...`
for more than an hour.
On another day I will check if this failure of loading the protocols is persistent or just a one-off.

**Comment by rays22** [comment]
The project has a status of `Complete`. I need an EBI HCA dev to set it to `Valid` so that I can do any metadata edits in the UI.

**Comment by rays22** [comment]
* I have managed to add the missing library protocol method ontology terms in Ingest UI.
- [x] EFO:0010550 sci-RNA-seq
```
    "library_construction_method" : {
      "ontology" : "EFO:0010550",
      "ontology_label" : "sci-RNA-seq",
      "text" : "sci-RNA-seq"
    },
```

- [x] EFO:0008919 Seq-Well
```
    "library_construction_method" : {
      "ontology" : "EFO:0008919",
      "ontology_label" : "Seq-Well",
      "text" : "Seq-Well"
    },
```

- [x] EFO:0010010 CEL-seq2
```
    "library_construction_method" : {
      "ontology" : "EFO:0010010",
      "ontology_label" : "CEL-seq2",
      "text" : "CEL-seq2"
    },
```

* I still need the project status to be reverted from `Complete` to `Valid` before I can export the update.

**Comment by rays22** [comment]
I am still blocked from exporting this update, because of the `Complete` status of the project.

**Comment by clairerye** [comment]
@yusra-haider are you able to look into this please?

**Comment by rays22** [comment]
@yusra-haider has changed the project status to `Valid`, but I was told to wait with exporting the updates, because this is a DCP1 project.

**Comment by clairerye** [comment]
Thanks, it has now been clarified so we can go ahead and export. Slack conversation - https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1623070775056500

**Comment by rays22** [comment]
The export of the [update](https://contribute.data.humancellatlas.org/projects/detail?uuid=88ec040b-8705-4f77-8f41-f81e57632f7d) is blocked by [unresponsive Ingest project page.](https://github.com/ebi-ait/dcp-ingest-central/issues/342)

**Comment by yusra-haider** [comment]
@clairerye , @rays22 

We can't export it yet, it's a dcp 1 dataset and requires that I make changes to the `dcpVersion` values in the database.

The referenced slack conversation was just me confirming that we can export dcp 1 metadata to the staging area for dcp 2 projects

**Comment by clairerye** [comment]
ok thanks, apologies I misunderstood the slack thread

**Comment by yusra-haider** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=d1610c4a-76c6-4b69-af63-c74af869fa75&project=88ec040b-8705-4f77-8f41-f81e57632f7d has been successfully exported

**Comment by rays22** [comment]
Thank you @yusra-haider .
I have filled in an [import request](https://docs.google.com/forms/d/e/1FAIpQLSeokUTa-aVXGDdSNODEYetxezasFKp2oVLz65775lgk5t0D2w/viewform?gxids=7628) for this update targeting **release 7**.
