### ISSUE TITLE
Incorrect ontology_label used

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#333]
Project Detail Page | project_id | library_preparation_protocol_id | ontology_id | ontology_label | should be
-- | -- | -- | -- | -- | --
https://data.humancellatlas.org/explore/projects/a9c022b4-c771-4468-b769-cabcf9738de3 | a9c022b4-c771-4468-b769-cabcf9738de3 | 95485ec8-0ce3-4f7a-b56e-e49cdb221942 | EFO:0008720 | DroNc-Seq | DroNc-seq
https://data.humancellatlas.org/explore/projects/a9c022b4-c771-4468-b769-cabcf9738de3 | a9c022b4-c771-4468-b769-cabcf9738de3 | db3445bd-59c3-40a9-a489-ac429e02c967 | EFO:0008722 | Drop-Seq | Drop-seq
https://data.humancellatlas.org/explore/projects/6c040a93-8cf8-4fd5-98de-2297eb07e9f6 | 6c040a93-8cf8-4fd5-98de-2297eb07e9f6 | 9c5a9c68-eb09-43f4-a8a4-03532cf80176 | EFO:0009899 | 10x 3' v2 | 10x 3' v2 sequencing

See 

https://docs.google.com/spreadsheets/d/1Wk7SGxEz00AkNokYv3YlFHJVF9U6THKcrvgHARsnau8/edit#gid=0

and

https://github.com/HumanCellAtlas/dcp2/issues/13

for context.

**Comment by clairerye** [comment]
We agreed that we would not do this in favour of azul doing the change to look up the ontology ID rather than the label. Closing this for now, but we can re-open/reassess if circumstances change.
