### ISSUE TITLE
Ability to make bulk metadata updates in ingest production

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#341]
As a wrangler, sometimes we need to make updates to the metadata for a project in ingest production in bulk. Currently, it is not possible to bulk update multiple rows, for example, 10s-100s of sequence files. It requires us to do it manually. It is not feasible to make the updates manually if there are 10s-100s of files/other entities. 

Acceptance criteria:

- [ ] Claire and Amnon to discuss a solution

- [ ] Implementation of a temporary workaround so that we can update projects for the June Release 7 milestone

- [ ] Implementation of a longer term solution to making bulk metadata updates in ingest production (if you think this should be a separate ticket for a later time, please do edit this ticket and remove any unnecessary criteria)

**Comment by clairerye** [comment]
Thanks for making this ticket Ami. We have a ticket here - https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/147 for bulk updates. Can we have a chat about what updates need to be made for the June release? As I agree thinking about one off versus sustainable solutions would be sensible. Do you think a chat you, me and @amnonkhen would be the best place to start?
