### ISSUE TITLE
Curate rows in Project Catalogue

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#342]
Gabs is presenting a poster on the Project Catalogue in late June. In order for her to do this, we need to update and improve the Project Catalogue. 

The first task to finish curating the project statuses in the tracker sheet i.e. where the hca_status is set to '' or 'uncurated'. Ami, Wei and Ray are working on this.

The list of dcp_ids assigned to each of us can be found here: https://docs.google.com/spreadsheets/d/1OUFVhvRWcDSPRwiyyXm-xZk_FCWY-kyGbqdnuuAUvVs/edit#gid=0 and the guidelines on how to review the eligibility and enter the required metadata in the row can be found here: https://docs.google.com/spreadsheets/d/1OUFVhvRWcDSPRwiyyXm-xZk_FCWY-kyGbqdnuuAUvVs/edit#gid=0

The deadline agreed by Tony, Claire and Amnon is next Wednesday June 3rd. If you think you can't make it due to other tasks or annual leave, let me know and I will add more dcp_ids to my list. Thanks!

**Comment by rays22** [comment]
I have curated the dataset tracking sheet rows [assigned to me.](https://docs.google.com/spreadsheets/d/1OUFVhvRWcDSPRwiyyXm-xZk_FCWY-kyGbqdnuuAUvVs/)

**Comment by Wkt8** [comment]
I have also done so.

**Comment by ami-day** [comment]
Closing this as it's done
