### ISSUE TITLE
contributor account for: Jay Shin

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#343]
Please create an account a contributor.

*Contributor details:*
* name: _Jay Shin_
* email: _jay.shin@riken.jp_
* institution: RIKEN Center for Integrative Medical Sciences (IMS)

Request Details:
* Requested by: [_WilliamGordanSullivan_](https://embl-ebi-ait.slack.com/team/U8NA0E6D9)
* [slack link](https://embl-ebi-ait.slack.com/archives/C021LFT41DG/p1622072461002700)

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by ke4** [comment]
I created the AWS account and access key for Jay Shin and sent it to William Gordan Sullivan.
