### ISSUE TITLE
project in dev env has biostudies_accessions as string instead of array of string

### ISSUE THREAD

**Issue by yusra-haider** [ebi-ait/hca-ebi-wrangler-central#345]
Link for the project: https://api.ingest.dev.archive.data.humancellatlas.org/projects/5e623fb9f02bb753344c6e59

`"biostudies_accessions" : "S-SUBS9"`

**Comment by amnonkhen** [comment]
@yusra-haider @ami-day please add some context to this ticket. What needs to be done? Is this already in-progress?

**Comment by amnonkhen** [comment]
@yusra-haider, would you please update here the motivation for this ticket? Why was it created?
Is this reporting a problem? Suggestion for improvement?

**Comment by yusra-haider** [comment]
for reference:

PR comment that led to the creation of this ticket: https://github.com/ebi-ait/projects-index/pull/42#discussion_r640751666

Slack thread about the discovery of this issue: https://embl-ebi-ait.slack.com/archives/C01Q3RMJZ6K/p1621953577025300

**Comment by yusra-haider** [comment]
As reported by @aaclan-ebi 

data is fixed now in prod and dev https://api.ingest.archive.data.humancellatlas.org/projects/5e623fb9f02bb753344c6e59
https://api.ingest.dev.archive.data.humancellatlas.org/projects/5e623fb9f02bb753344c6e59

It was probably fixed when the data in prod was synced to dev

Closing this ticket
