### ISSUE TITLE
Complete to Valid Status Update needed

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#347]
https://contribute.data.humancellatlas.org/projects/detail?uuid=f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc - still in exporting status

https://contribute.data.humancellatlas.org/projects/detail?uuid=a9c022b4-c771-4468-b769-cabcf9738de3 - can't see in browser if it has exported yet or exporting

https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/332 https://contribute.data.humancellatlas.org/projects/detail?uuid=88ec040b-8705-4f77-8f41-f81e57632f7d - can't see in browser if it has exported yet or exporting

https://contribute.data.humancellatlas.org/submissions/detail?uuid=a69c731b-9db7-45e3-938f-daf2e4636a6e&project=577c946d-6de5-4b55-a854-cd3fde40bff2 - exported

- [x] Status has been changed from Complete to Valid (Yusra)

- [x] The project has been re-submitted and is exporting (Ami)

**Comment by yusra-haider** [comment]
set https://contribute.data.humancellatlas.org/submissions/detail?uuid=7b4cd093-bfa5-477e-9c95-69bafc1cb6bf&project=f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc as valid using the core end point

set https://contribute.data.humancellatlas.org/submissions/detail?uuid=a69c731b-9db7-45e3-938f-daf2e4636a6e&project=577c946d-6de5-4b55-a854-cd3fde40bff2 as valid using the core end point

https://contribute.data.humancellatlas.org/projects/detail?uuid=a9c022b4-c771-4468-b769-cabcf9738de3 isn't accessible via UI as the page doesn't load. This might be linked to this ticket here: https://github.com/ebi-ait/dcp-ingest-central/issues/336

redeployed state tracker using `kubectl delete pod ingest-state-tracking-54fcf94c7c-89rmm`

**Comment by yusra-haider** [comment]
@ami-day  you should be able to re-export two out of three projects now

**Comment by yusra-haider** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=bf3116e5-1af1-46c2-8bbd-44dac49d1e7f&project=a9c022b4-c771-4468-b769-cabcf9738de3 is the submission page for https://contribute.data.humancellatlas.org/projects/detail?uuid=a9c022b4-c771-4468-b769-cabcf9738de3

Setting it to valid using the core end point

redeployed state tracker using `ingest-state-tracking-54fcf94c7c-96d95`

**Comment by yusra-haider** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=a69c731b-9db7-45e3-938f-daf2e4636a6e&project=577c946d-6de5-4b55-a854-cd3fde40bff2 has now been re-exported

https://contribute.data.humancellatlas.org/submissions/detail?uuid=7b4cd093-bfa5-477e-9c95-69bafc1cb6bf&project=f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc and https://contribute.data.humancellatlas.org/submissions/detail?uuid=bf3116e5-1af1-46c2-8bbd-44dac49d1e7f&project=a9c022b4-c771-4468-b769-cabcf9738de3 seem to be dpc1 data set, and that' causing issues with the re-export. I'm looking at what the appropriate fix for this would be

**Comment by ami-day** [comment]
This one too please: https://contribute.data.humancellatlas.org/submissions/detail?uuid=7a81ac3e-e824-4c03-9bb5-f862ced23860&project=5ee710d7-e2d5-4fe2-818d-15f5e31dae32 @yusra-haider thanks!

**Comment by yusra-haider** [comment]
@ami-day 

https://contribute.data.humancellatlas.org/submissions/detail?uuid=7a81ac3e-e824-4c03-9bb5-f862ced23860&project=5ee710d7-e2d5-4fe2-818d-15f5e31dae32 was successfully re-exported

**Comment by yusra-haider** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=bf3116e5-1af1-46c2-8bbd-44dac49d1e7f&project=a9c022b4-c771-4468-b769-cabcf9738de3

and 

https://contribute.data.humancellatlas.org/submissions/detail?uuid=7b4cd093-bfa5-477e-9c95-69bafc1cb6bf&project=f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc

were also successfully exported

**Comment by ofanobilbao** [comment]
@ami-day should this issue not be in the Operations board mainly? And be done already? Thanks!

**Comment by ami-day** [comment]
Thanks @ofanobilbao for helping out here. Yep I have submitted the import forms now. About the ticket, I have noticed a few tickets appearing on multiple or the wrong boards recently. I am not sure if there is an issue with Zenhub or something else, I'll look into it again! We also had some weird stats in the cumulative graph reports, not sure if it might be related.
