### ISSUE TITLE
Incorrect species in project InfiltratingNeoplasticCellsHumanGlioblastoma

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#350]
Species is "homo sapiens", expecting "Homo sapiens" in the project:

Single-Cell RNAseq analysis of diffuse neoplastic infiltrating cells at the migrating front of human glioblastoma
https://data.humancellatlas.org/explore/projects/2d846095-8a33-4f3c-97d4-585bafac13b4

**Comment by ami-day** [comment]
Made the updates and re-submitted the metadata only: https://contribute.data.humancellatlas.org/submissions/detail?uuid=d35d9af6-c532-4944-b520-3ec5ca369dc9&project=2d846095-8a33-4f3c-97d4-585bafac13b4

**Comment by ami-day** [comment]
Submitted import form.
