### ISSUE TITLE
Incorrect species in project HumanGermlineCells

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#351]
The species is "Homo sapeins". Expecting "Homo sapiens" in the project:

Single-Cell RNA-Seq Analysis Maps Development of Human Germline Cells and Gonadal- Niche Interactions
https://data.humancellatlas.org/explore/projects/08b794a0-519c-4516-b184-c583746254c5

Seeing this in catalog dcp5

**Comment by ami-day** [comment]
This project is not loading properly in ingest prod.

**Comment by ami-day** [comment]
Made updates: https://contribute.data.humancellatlas.org/submissions/detail?uuid=c160f207-5e75-4e7b-b43c-4bf84684dcae&project=08b794a0-519c-4516-b184-c583746254c5

It is exporting atm

**Comment by ami-day** [comment]
submitted update form.
