### ISSUE TITLE
Incorrect species in project lymphaticEndothelialCells

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#352]
Species is "Homo Sapiens", expecting "Homo sapiens" in project

Single-cell survey of human lymphatics unveils marked endothelial cell heterogeneity and mechanisms of homing for neutrophils

https://data.humancellatlas.org/explore/projects/5ee710d7-e2d5-4fe2-818d-15f5e31dae32

This is in the dcp5 catalog.

**Comment by ami-day** [comment]
The status in ingest prod. is "Complete" it needs to be changed back to valid for re-export.

**Comment by ami-day** [comment]
The import form has been submitted for metadata re-export.
