### ISSUE TITLE
Some projects with contributor matrices from GEO do not have GEO accessions

### ISSUE THREAD

**Issue by NoopDog** [ebi-ait/hca-ebi-wrangler-central#354]
## Overview

Feedback from our first interview was that the accession links for the projects containing CGMs were useful to find out more about the project. However, it was also noticed that some of the projects with matrices from GEO did not have a GEO accession link.

It is possible to determine the GEO accession by looking at the file names of the CGMs but it was pointed out that some of the accession links are missing and it would be helpful to add them. 

We did a query pull back the 62 projects tagged as having a File Source = GEO and scanned them programmatically to check if they also had a GEO accession. 

https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22fileSource%22,%22terms%22:%5B%22GEO%22%5D%7D%5D

Of the 62 projects listed in catalog dcp5 with `File Source = GEO` the six below do not have GEO accessions.

## Projects Missing GEO Accessions

1. [A single-cell reference map of transcriptional states for human blood and tissue T cell activation](https://data.humancellatlas.org/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803)

1. [Bone marrow plasma cells from hip replacement surgeries](https://data.humancellatlas.org/explore/projects/a29952d9-925e-40f4-8a1c-274f118f1f51)

1. [Cell hashing with barcoded antibodies enables multiplexing and doublet detection for single cell genomics](https://data.humancellatlas.org/explore/projects/f81efc03-9f56-4354-aabb-6ce819c3d414)

1. [Comparison, calibration, and benchmarking of high-throughput single cell RNA-Seq techniques for unbiased cell-type classification]
(https://data.humancellatlas.org/explore/projects/a9c022b4-c771-4468-b769-cabcf9738de3)

1. [Single Cell Transcriptomics of a Human Kidney Allograft Biopsy Defines a Diverse Inflammatory Response](https://data.humancellatlas.org/explore/projects/027c51c6-0719-469f-a7f5-640fe57cbece)

1. [Single-nucleus RNA sequencing of human cortex affected by multiple sclerosis](https://data.humancellatlas.org/explore/projects/ce7b12ba-664f-4f79-8fc7-3de6b1892183)

## Definition of Done
The projects above have a GEO accession showing on the project's detail page. Similar to:

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/84758d4d-b9be-438f-8732-002319d75b7c)

**Comment by ESapenaVentura** [comment]
I'm going to triage this to see what team needs to do the updates (For simplicity, if the wrangler is no longer working in the project I'll tag Parisa or myself), projects belong to:
1. @pnejad 
1. @ESapenaVentura 
1. @pnejad 
1. @pnejad 
1. @pnejad 
1. @ami-day

**Comment by willrockout** [comment]
@NoopDog All the ones from us were live wrangling not sure why the file source says from GEO.

**Comment by ESapenaVentura** [comment]
@NoopDog @ami-day is right, checking both ingest and the staging area (gs://broad-dsp-monster-hca-prod-ebi-storage/prod/ce7b12ba-664f-4f79-8fc7-3de6b1892183/data/) I can't see any matrix files. Something is a bit off here

**Comment by ipediez** [comment]
One option proposed for Hannes: Update the submission and do clean ups, from ingest's staging area

**Comment by ami-day** [comment]
Latest status: the GEO matrix file shouldn't be associated with this project: https://data.humancellatlas.org/explore/projects/ce7b12ba-664f-4f79-8fc7-3de6b1892183/project-matrices
