### ISSUE TITLE
contributor account for: Anne Senabouth

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/hca-ebi-wrangler-central#365]
Please create an account for a contributor.

*Contributor details:*
* name:  Anne Senabouth
* email:  a.senabouth@garvan.org.au

Request Details:
* Requested by: William Sullivan

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by yusra-haider** [comment]
created user:

```
aws iam create-user --user-name anne.senabouth --tags Key=project,Value=hca Key=owner,Value=tburdett Key=service,Value=ait --profile embl-ebi                ✔  10197  13:03:31

{
    "User": {
        "Path": "/",
        "UserName": "anne.senabouth",
        "UserId": "AIDA4WBQCFL3EVXY3Z5YL",
        "Arn": "arn:aws:iam::871979166454:user/anne.senabouth",
        "CreateDate": "2021-06-18T12:04:24Z",
        "Tags": [
            {
                "Key": "project",
                "Value": "hca"
            },
            {
                "Key": "owner",
                "Value": "tburdett"
            },
            {
                "Key": "service",
                "Value": "ait"
            }
        ]
    }
}
```
added user to group:

```
aws iam add-user-to-group --group hca-contributor --user-name anne.senabouth
```

created access key
```
aws iam create-access-key --user-name anne.senabouth
```

**Comment by willrockout** [comment]
Hey guys my users are getting the below error when trying to upload data, any ideas?

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Comment by jacobwindsor** [comment]
Hi @willrockout are you referring to the user with username `anne.senabouth`? I see they have the correct permissions so should be okay

**Comment by willrockout** [comment]
Hi @jacobwindsor,  yes Anne is having this issue when trying to upload. I've also tried to use their access/secret keys and see the same error
