### ISSUE TITLE
Check overlap of SCEA dataset list with the Dataset Tracking List

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#37]
**Description of the task:**

Do a comprehensive comparison between the SCEA dataset list at
<https://www.ebi.ac.uk/gxa/sc/experiments?species=homo%20sapiens>
and the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0)

This is a follow up of the question here: <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/9#issuecomment-631389298>.

**Acceptance criteria for the task:**

- [ ] Determine which are the non-overlapping datasets on the SCEA list
- [ ] Assess the newly identified datasets and if appropriate add them to the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0).

**Comment by lauraclarke** [comment]
is there an SCEA API that might give you AE or GEO accession numbers for the SCEA datasets?

**Comment by rays22** [comment]
> is there an SCEA API that might give you AE or GEO accession numbers for the SCEA datasets?

I have not found it.

**Comment by lauraclarke** [comment]
Maybe ask John or Pablo on the HCA to SCEA channel? they might have suggestions on how to automate this part

**Comment by lauraclarke** [comment]
@rays22 have you been able to progress this at all? It would be great to be able to see anything we don't have from SCEA in https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0

**Comment by rays22** [comment]
> @rays22 have you been able to progress this at all? It would be great to be able to see anything we don't have from SCEA in https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0

No, I have not been able to make any progress on it.
Preprints, papers, accession identifiers define datasets very loosely both in SCEA and the our tracking spreadsheet, which makes it very difficult to find the elements of the SCEA complement set with HCA datasets computationally.

**Comment by lauraclarke** [comment]
https://www.ebi.ac.uk/gxa/sc/json/experiments/hca/human is all the human experiments

https://www.ebi.ac.uk/gxa/sc/json/experiments is all the experiments

**Comment by rays22** [comment]
> https://www.ebi.ac.uk/gxa/sc/json/experiments/hca/human is all the human experiments
> 
> https://www.ebi.ac.uk/gxa/sc/json/experiments is all the experiments

Thank @lauraclarke . I will check the overlap using the accessions in the JSONs.

**Comment by lauraclarke** [comment]
As a note

https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-124263/results/tsne

E-GEOD-124263 maps to GSE124263 so you can replace the E-GEOD- with GSE by the look of it

**Comment by lauraclarke** [comment]
I don't know if it will be easier or more difficult ot get the info from https://www.cambridgecellatlas.org/

**Comment by lauraclarke** [comment]
I suspect we have enough to do that this probably won't ever be a priority so I am going to close it
