### ISSUE TITLE
alerts from grafana

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#372]
- [x] pods not running
- [x] increase in memory usage
- [x] max replica count for exporter
- [x] max allowed pods on a node

**Comment by jacobwindsor** [comment]
Apparently learning PromQL well enough to make good alerts is quite difficult... So far I have alerts set up for:

- If a pod fails
- If ingest-core memory usage is coming close to the maximum
- If we are coming close to the number of pods allowed on a node (110), threshold for alert set at 90

**Comment by Wkt8** [comment]
Hi @jacobwindsor is this done?

**Comment by jacobwindsor** [comment]
Yes but there is a PR still pending https://github.com/ebi-ait/ingest-kube-deployment/pull/25
