### ISSUE TITLE
GSE161255 (organoids): Recultured ureteric epithelium line 1, Recultured ureteric epithelium line 2

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#375]
**Dataset/group this task is for:**

Barbara Treutlin, Melissa Little

**ingest production:**
https://contribute.data.humancellatlas.org/submissions/detail?uuid=fc4feb0b-3749-49b5-b15b-0a9dc1dd6e2f

**Wrangler responsible for this dataset/lab:**

Ami

**Google Sheet:** 
https://docs.google.com/spreadsheets/d/15XI426pOSmGTzjjSNaBmtVUZrMj6yTl7/edit#gid=578411706

**Publication:** 
Howden SE, Wilson SB, Groenewegen E, Starks L et al. Plasticity of distal nephron epithelia from human kidney organoids enables the induction of ureteric tip and stalk. Cell Stem Cell 2021 Apr 1;28(4):671-684.e6. PMID: 33378647

![image](https://user-images.githubusercontent.com/25744951/124604206-a026f100-de62-11eb-841c-0866de8d2bae.png)

**Acceptance criteria for the task:**

- [x] curate metadata
- [x] add ontologies
- [x] graph validator
- [x] secondary review
- [x] validate in ingest staging
- [x] upload to ingest production

**Comment by ami-day** [comment]
Uploading data to hca-util upload area: 9ee13fe4-3f81-4d5a-b234-91133364b986

**Comment by ami-day** [comment]
I am removing the July 26th milestone as this has not been secondary reviewed yet. I will change it to the August milestone.

**Comment by ESapenaVentura** [comment]
I have reviewed the dataset:

# Review

## Project - Publications

-Authors: Corrected some names with a starting space
-Publication URL: Corrected URL to not include `?via=…`


## Cell line
-Catalog number: Added catalog ID
-Description: Added cell line-specific info to the end of the description
-Organ model: Changed to kidney, which is what organ that cell line is modelling
-Karyotype: added karyotype
-tissue: Added tissue type for GATA3 cell line
-Publication: Added publication info about the cell lines

## Enrichment protocol
-EPCAM protocol is missing method (Seems to also be FACS?)

## Cell suspension
-Bulk cells do not count as cell suspensions (I think there were only 2 single cell suspensions in this dataset?)


## Sequence file
-Lane indexes are missing for libraries SRX9474286 and SRX9474287 (single cell)

## Analysis files
-Missing all the analysis file tabs





# Suggestions

## Donor/specimen
-Donor/Specimen/Collection protocol tabs: I would delete this, these are bought cell lines

#  Cell line
-IDs: Can we make them a bit smaller? They are gigantic and mix 2  special chars (`-`, `/`)


I found a couple of things, corrected some and suggested here what I would do with the others

The corrected spreadsheet is in the same brokering folder, with the date it was reviewed and appended at the end of the name

**Comment by ami-day** [comment]
Uploaded to ingest production: https://contribute.data.humancellatlas.org/submissions/detail?uuid=04fa73ed-12e1-418b-9330-e372ef3594d5 need to transfer fastq and analysis files to ingest

**Comment by ofanobilbao** [comment]
@ami-day does this dataset need to be brokered to SCEA? If yes, I will add the label and remove from this board. If no, I will just close the ticket. Thanks!
