### ISSUE TITLE
Review where operations documentation should live and check it is up to date.

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#38]
As a wrangler I want to know where to look for information about specific steps in the wrangling process and for that information to be up to date.

Review where documentation should be stored given the new repo. Are we using wikis etc from the old one or new?
Examples of Documentation that needs a home is the graph validator documentation (https://docs.google.com/document/d/1lTvY7U02AT6uLe1pcvFTkt3GYfTP0JY8VJS-EBOSRaU/edit) and also the Ingest to archives documentation (https://docs.google.com/document/d/1S4fyCSqB3nLrCUssNMwSp6ff8tmeipMi_slnXW2Lrq4/edit#heading=h.n3qy5yl0auvs) and possibly others?

And where feedback doc should live: https://docs.google.com/document/d/1h-oUrbOb5OZS8L_F023eYP9mYwyuimTH7jdPQEMGj-E/edit#

**Comment by lauraclarke** [comment]
Is there a reason not to put all of this on https://ebi-ait.github.io/hca-ebi-wrangler-central/

**Comment by clairerye** [comment]
I think it hopefully has been. I need to check.
