### ISSUE TITLE
automate monthly backup verification

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#380]
**Description of the task:**

The monthly task of restoring from backup can be automated.
Let's brainstorm a few alternative way to implement it.

**Acceptance criteria for the task:**

- [ ] backup verification is automated
- [x] failures reported in slack/email
- [x] success is logged somewhere (file, grafana, ???)
- [x] docs in ops review doc

**Comment by Wkt8** [comment]
@jacobwindsor is this complete?

**Comment by ESapenaVentura** [comment]
@jacobwindsor is this done? if not please move to in progress

**Comment by jacobwindsor** [comment]
Yes it's done. I opened up #391 to cover it as this turns out to be a bigger task than originally thought
