### ISSUE TITLE
delete incorrect submission for 403c3e76-6814-4a2d-a580-5dd5de38c7ff

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#381]
**403c3e76-6814-4a2d-a580-5dd5de38c7ff**

The Developmental Heterogeneity of Human Natural Killer Cells Defined by Single-cell Transcriptome

**Rachel Swchwartz, UCSC**

**Description of the task:**

Project was exported for release 7. There were linking issues found by Hannes. Rachel corrected the issues on the original spreadsheet and uploaded it as a new submission and exported it. 
There are now 2 submissions in the staging area, the correct one (latest date) (02f0b557-9e58-4f14-bc45-de16180643ce) and the original (earliest date) (ae4b73ba-7b74-4fc2-b36c-13fed3fa7ca4), we need to delete the original so that the data import team can proceed.

slack conversation: https://humancellatlas.slack.com/archives/C9XD6L0AD/p1625590317104900?thread_ts=1625244791.102700&cid=C9XD6L0AD

**Acceptance criteria for the task:**

delete the original submission
notify the broad team in slack

**Comment by clairerye** [comment]
@jacobwindsor the spreadsheet is uploaded, now ready to have data files synced. https://contribute.data.humancellatlas.org/projects/detail?uuid=403c3e76-6814-4a2d-a580-5dd5de38c7ff

**Comment by jacobwindsor** [comment]
Commenting this here as may be useful to other devs/wranglers:

After moving the files from the old to new submission area (via AWS UI), I notified the upload service of the change to trigger validation again with this command:

`BUCKET=d84784da-4a17-49ee-b5aa-ea76a60769ef`

`for file in $(aws s3 ls s3://org-hca-data-archive-upload-prod/$BUCKET/ | awk '{print $4}'); do; curl -i -X POST https://upload.archive.data.humancellatlas.org/v1/area/$BUCKET/$file; done`
