### ISSUE TITLE
Some of the ontology term names are displayed in Chinese characters by the HCA OLS instance

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#383]

**Comment by rays22** [comment]
Some of the ontology term names are displayed in Chinese characters by the HCA OLS instance.
For example:
<https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000922>
I think it has a negative impact on finding the correct ontology terms by wranglers.
Expected behaviour: The terms should be displayed in the correct character encoding.

**Comment by ofanobilbao** [comment]
Closing as it was resolved. No longer relevant
