### ISSUE TITLE
heart cell atlas data file replacement in ENA

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#385]
Sarah Teichmann reports many groups are having trouble accessing the raw reads for our study on the **_Adult Human Heart (Litvinukova et al., Nature, 2020)_** – and then write to us directly. 

Project: 
   ad98d3cd-26fb-4ee3-99c9-8a2ab085e737
   HeartSingleCellsAndNucleiSeq

- [ ] update the BAM files that are in the ENA so they are usable with cellranger
- [ ] add FASTQ files for this project to give users the option of format
    * option 1 - ~using archiver and DSP~ - DSP does not accept 3 fastq files
    * option 2 - dsp-less archiver - ENA bit needs to be written
    * option 3 - manual /scripted upload using ENA submission API (webin CLI)
- [ ] according to the option selected - move to Dev Board or keep on Ops Board
- [ ] Inform Sarah T when this is done

**Comment by clairerye** [comment]
this is a specific example of #250

**Comment by aaclan-ebi** [comment]
Closing this in favor of ebi-ait/dcp-ingest-central#399 All work needed for correcting HeartSingleCellsAndNucleiSeq data in ENA is being tracked there.
