### ISSUE TITLE
Fix ingest-backup-verify

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/hca-ebi-wrangler-central#391]
The ingest-backup-verify cronjob is not fit for purpose, outdated and difficult to update.
 
The setup.sh file uses a CSV with AWS access credentials. This is not how we do it with other helm charts, they are usually grabbed from the config/environment_ENV files. 

The `verify.py` script does not work. It is passing successfully but it should not. It is silently failing due to an error when connecting to mongo (`DBClientConnection failed to receive message from localhost:27017 - HostUnreachable: Connection closed by peer`).

You can see the logs by looking at the logs of the most recently ran cronjob (e.g. `kubectl logs ingest-backup-verify-TIMESTAMP verification`)

- [x] ~Refactor so that we no longer use the CSV and it is easier to deploy. Look at the ingest-monitoring charts for inspiration~ There is no need for this. See [PR](https://github.com/ebi-ait/ingest-kube-deployment/pull/31) for details.
- [x] Fix the `verify.py` script so that it doesn't silently fail.
Note: The script wasn't silently failing. The mongo connection failure messages were just warnings. The slack webhook needs to be updated to notify in EBI-AIT hca-dev-notifications channel.
- [x] Change the `verify.py` script so that it reports successful verifications to Slack
- [ ] Ensure the `verify.py` script is fit for purpose. It is checking enough DB attributes?
Successful backup restore and some data completeness checks would be nice. The db restore and a basic check on no. of submissions is being done already. Do we want to add more checks?
- [x] ~Update the Slack webhook in AWS secrets to the same webhook used by ingest-monitoring. We may also just be able to put this straight into the values.yaml without much risk~ It's already in the `ingest/env/alerts` secrets but it needed to be updated.
- [x] Update READMEs
- [x] Link READMEs in ops tasks google doc

**Comment by ESapenaVentura** [comment]
@jacobwindsor what is the status on this?

**Comment by amnonkhen** [comment]
reassigning to @aaclan-ebi

**Comment by ami-day** [comment]
@Wkt8  to check with @jacobwindsor if this is in progress or done?

**Comment by aaclan-ebi** [comment]
I'll work on this today but I'll prioritise the fix for verify.py script silent failure and makes sure it reports to Slack.

**Comment by aaclan-ebi** [comment]
Some fixes are already applied in dev. There's a PR for the changes. I will apply them to staging and prod once merged.

**Comment by aaclan-ebi** [comment]
Update: This is in dev and staging. But there was an issue deploying to prod. 
![Screenshot 2021-09-30 at 17.07.29.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/1b141823-49ff-4422-be11-453e28a696ae)

**Comment by Wkt8** [comment]
@aaclan-ebi is there a lot of work left on this??
