### ISSUE TITLE
AWS summary stats by scientific metrics

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#397]

**Comment by ami-day** [comment]
@ofanobilbao shall I close this ticket? I think you are working on this, I think I opened it when I ran the script and it gave some errors in the output due to a lack of cell count for some projects.

**Comment by ofanobilbao** [comment]
Please, keep it there for now. As it is not resolved. It's just not done yet. Thanks!

**Comment by ami-day** [comment]
Ok, can I unassign myself though, I think there is not anything I should do further on this?

**Comment by ofanobilbao** [comment]
Closing this for the same reasons as closing the blocking issue. Will be addressed in a separate ticket in the Development board
