### ISSUE TITLE
Get fastq using Aspera: sra objects returned

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#398]
**Description of the task:**

As I a wrangler I want to use Aspera to obtain fastq files for a project when necessary, using the instructions found here: https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/docs/SOPs/dataset_wrangling_SOP.md

However when i run the command with the following accession: SRP292174 the SRA objects are downloaded rather than fastq files, even though the fastq files are available here: https://www.ebi.ac.uk/ena/browser/view/PRJNA676040?show=reads

The command I ran is:
`cat filereport_read_run_PRJNA676040_json.txt | jq '.[].fastq_ftp' | grep -E -o "ftp\.[^;]*fastq\.gz" | sed 's/ftp.sra.ebi.ac.uk\///g' | xargs -I{} -P 5 sh -c "ascp -QT -l 300m -P33001 -i ~/.aspera/cli/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:{} \$( echo organoids_plasticity/{} | cut -d\"/\" -f6 )"`

Is there a way to tweak it so that fastq files are downloaded? or a reason why the sra objects are chosen instead?

**Comment by ESapenaVentura** [comment]
There is an error in the script

it's not returning SRA objects, it's trying to name the fastq objects with the string obtained from `echo organoids_plasticity/{} | cut -d\"/\" -f6 ` . 

-f6 indicates the field number, so when you include another field, it doesn't pick it up correctly.

I have simplified the code a bit and put an example of how to do it in these situations in the [Wrangling SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#raw-data-fastq-download)
