### ISSUE TITLE
Discuss with pipelines team multiplexed 10x organoid data

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#406]

**Comment by Wkt8** [comment]
Currently there is no way for EBI to send multiplexed data to analysis components without making pipelines fail. We were asked to demultiplex data before sending it. 
- Open question about whether we should be demultiplexing data before we send it to them, or they should be demultiplexing data.
     - From the initial design of the HCA, data should always be demultiplexed before sending to downstream components. 
- Concerns about us editing data that contributors have sent to us.

**Comment by ESapenaVentura** [comment]
Kylee sent an email asking for a meeting, waiting for other pipeline members to confirm availability

**Comment by Wkt8** [comment]
There is an action to document the [outcomes](https://docs.google.com/document/d/1qyT2yqbnr0MK5gzsVPrcQd62-TsS2KnFM1XVADzrxA0/edit#heading=h.ff1ee0r777h1) (when to wrangle what data shapes, what to do with demultiplexed data, etc.) probably included in [Wrangling SOPs ](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/SOPs.html) or eligibility criteria.

**Comment by ami-day** [comment]
I have edited our wrangling SOPs to reflect this, and have opened a pull request for updates to the project catalogue eligibility criteria.
