### ISSUE TITLE
Benchmark getting data from archived project into s3 Bucket

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#41]
**Description of the task:**

Benchmark the time/effort needed to move data from ENA into an s3 bucket for upload into ingest. 

Steps:
- Given an accession, retrieve all URIs for the files
- Set up an upload session in the EC2 
- Begin upload from ENA URIs
- Verify all files are valid by uploading to ingest (in dev? staging?)

**Acceptance criteria for the task:**

- [ ] A summary of the steps followed is created for other wranglers to be able to use it if needed.
- [ ] Blockers have been identified for the process
- [ ] Blockers have been adressed in tickets for future prioritisation

**Comment by ESapenaVentura** [comment]
I have created a script that should do part the job easier https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/57

It's under review, once it's been accepted and merged I can proceed to benchmark how much will it take

**Comment by ESapenaVentura** [comment]
I have used the script and benchmarked the results:

For a total of 1080 GB of data (~1TB) it took approx 5 h 30 minutes with 5 threads (Simultaneous uploads) given a INSDC accession (SRP).

This data was extracted from the ENA mirror data (warehouse), so it is equivalent to extracting from an ENA ftp.

The biggest blocker identified is the amount of time it takes, but setting up a virtual session in tmux in the EC2 you can leave it running and it causes no problem.

Will begin upload to ingest soon. This was done for the dataset on #61 so I am waiting for secondary review before uploading files to ingest.

**Comment by clairerye** [comment]
@ESapenaVentura this looks done to me, is that fair? Or were there issues identified that we should resolve before using this to transfer the files for other datasets?

**Comment by ESapenaVentura** [comment]
I agree that this is almost done, maybe today I can find a piece of our documentation where I can put a really simple `how-to` use this tool (it's only 1 command, but I'd like it documented). Then we can close it!

**Comment by clairerye** [comment]
Yes, good point, getting this procedure documented will be really useful!

**Comment by ESapenaVentura** [comment]
Documented in here https://ebi-ait.github.io/hca-ebi-wrangler-central/tools/handy_snippets.html#uploading-files-to-an-s3-bucket-from-the-archives

Closing the ticket!
