### ISSUE TITLE
Human fetal atlas

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#411]
### Project short name:
dcp6600438190759903

### Primary Wrangler:
@ESapenaVentura 

### Secondary Wrangler:
@Wkt8 

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1_f0nsFsbLEQldudXAPgBcVHdaF9v44ZA

### Published study links

* Paper: https://science.sciencemag.org/content/370/6518/eaba7721

* Accessioned data: phs002003.v1.p1, [GSE156793](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE156793)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Couple of notes:

- I am not super sure about some fields in the analysis protocol, so whoever secondary reviews please pay attention to these
- There are some ontologies missing (sci-RNA-seq3) that will be added in the new release

**Comment by ESapenaVentura** [comment]
Project info has been updated: https://contribute.data.humancellatlas.org/projects/detail?uuid=a9301beb-e9fa-42fe-b75c-84e8a460c733

**Comment by ESapenaVentura** [comment]
Thanks for the review @Wkt8 !

I have looked and corrected the dissociation protocols and added the 2 enrichment protocols mentioned, as well as updated the linking to the protocols in the cell suspension tab

About the cell suspension tab... It's showing all the descriptions for me? 

And last thing: I wasn't sure about the content description for the annotation files. Any ideas?

The new file can be found in the same folder, with the suffix "_20210902"

**Comment by Wkt8** [comment]
Hi @ESapenaVentura!

Nice! Sorry, I did not communicate what I meant about the cell suspension tab properly. In Row 22 on the cell suspension tab, there's the additional description "47,Xy,+18" which is not present in the other tabs. 

As for the annotation files I'm not quite sure either. "Annotation operation:0226" works but it is really broad and none of the child terms under "Annotation" are quite right. I'd be tempted to leave it either as "annotation" or perhaps request a new term for "Genome annotation".

**Comment by ESapenaVentura** [comment]
Ready except for missing ontology

**Comment by ESapenaVentura** [comment]
The new ontology is "out"! (Still a couple of days before the deployment is effective) I will correct the dataset with the new ontology: `sci-RNA-seq3` (EFO:0030028)

**Comment by ESapenaVentura** [comment]
Updated with the latest ontologies, both the ones requested by @Wkt8 and the one requested by me. Trying to ingest it now!

**Comment by ESapenaVentura** [comment]
Uploaded submission

- Files are ok

Run ingest graph validator:
- Failed 2 tests: `contains_cell_barcode` (This technology has another type of barcodes) and `paired_end_2_files` due to linking to analysis files

Other than that, submission is valid. Hitting submit!
