### ISSUE TITLE
Write proposal to approach developmental scientists about metadata

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#42]
**Description of the task:**
Write a proposal so @lauraclarke can approach developmental scientists to improve the metadata we collect for developmental samples, increasing the value we provide to our users.

Discussion in here: https://humancellatlas.slack.com/archives/GP5GZF09Z/p1591179541035500

Research plan in : https://docs.google.com/document/d/1R2lLRo_LbVJNcftNQN9NajtpLI4Ck1jbNDsewj8FcOw/edit#

**Acceptance criteria for the task:**
- [x] An email is draft with a proposal to researchers.
- [x] A google survey is created to present them with information and ask for feedback
- [x] @gabsie reviews the form
- [x] The form with the email is sent to contributors before the end of next week.

**Comment by lauraclarke** [comment]
Added the start of a research plan @gabsie if you have time to read it and comment that would be appreciated but I totally get if you don't

**Comment by lauraclarke** [comment]
@ESapenaVentura I have started the survey here. This is a very rough structure, feel free to edit this as much as you want

https://docs.google.com/forms/d/1TIhGq2_cIpet6xpC7XzvMmiMezVanAlSCYwe87lQVCw/edit

The idea is to have a question about what is collected for people who get the samples and a question about what is needed during analysis when doing it, then a relative ranking for the fields we already record

**Comment by ESapenaVentura** [comment]
I'll take a closer look to add more things but overall sounds reasonable to me!

For now I have added the Neck-Rump Length and the Crown-Rump Length, even if we don't currently collect it I would like to know how much this measures (related to developmental stage) are useful to researchers

**Comment by lauraclarke** [comment]
Do check spelling etc, I might not have got that right

Do we have any ontology terms, they might be worth adding a question about if we do?

**Comment by clairerye** [comment]
I think it would also be valuable to go one step further than the survey does at the moment and understand what is trying to be achieved with the analysis in terms of what value does knowing precise developmental stage give to the way the results are determined? 
I may not be explaining this very well, but what I am trying to say is, we need to understand why Scientist 1 wants Neck-Rump Length and why Scientist 2 wants Crown-Rump Length because they may (or may not) be trying to achieve the same thing but its standard or personal preference to use one measurement over the other. 
Is one measurement actually more accurate at identifying the same versus different developmental stages?

**Comment by lauraclarke** [comment]
@clairerye you are right we will want to understand the differences between preference vs scientific differences between different measures

I am not sure how easy it will be to capture that in a survey though, would it be better to see how consistent people respond and target those who have different views to present why?

**Comment by lauraclarke** [comment]
@ESapenaVentura it would be great to get this finished up today

First, I realised this only really applies to human developmental samples,  so I have edited the text to try and make it is clear this is human we are referring to

Second, I am trying to figure out how to check if our ontology term choices are reasonable https://www.ebi.ac.uk/ols/ontologies/hsapdv 

Is there a good way to ask that question or shall we just leave it?

**Comment by lauraclarke** [comment]
@gabsie have you had chance to look at the survey yet?

**Comment by ESapenaVentura** [comment]
@lauraclarke We can probably point them to the ontologies under the pre-natal stage https://www.ebi.ac.uk/ols/ontologies/hsapdv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000045

I am currently looking at `webowl` to see if we can actually show it visually to them

**Comment by gabsie** [comment]
hi, @lauraclarke - I have not. I just got set up in my mom's house. will find some time today in the afternoon to do that.
gabs

**Comment by lauraclarke** [comment]
> @lauraclarke We can probably point them to the ontologies under the pre-natal stage https://www.ebi.ac.uk/ols/ontologies/hsapdv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000045
> 
> I am currently looking at `webowl` to see if we can actually show it visually to them

I was thinking at a much higher level, in terms of we use this ontology to get the terms, are there other ontologies you use or we should consider

I am not sure if the survey the best place to show them all of the relevant terms in the ontology

**Comment by ESapenaVentura** [comment]
Ok, I thought you wanted to give some additional insight in the email

Maybe we can have one open-text question like: "For human development, we use Carnegie stages to define embryonic stages and post-conception weeks to define fetal stages. We use the controlled vocabulary defined under this term: https://www.ebi.ac.uk/ols/ontologies/hsapdv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000045 . Is there any other ontologies you currently use and think that would better define human development stages?"

Does that question sound alright?

**Comment by lauraclarke** [comment]
That sounds good, I have added it under the collection section

**Comment by lauraclarke** [comment]
@ESapenaVentura @gabsie there is also draft email text in https://docs.google.com/document/d/1R2lLRo_LbVJNcftNQN9NajtpLI4Ck1jbNDsewj8FcOw/edit#

I would really like to get these sent by next Tuesday

**Comment by ESapenaVentura** [comment]
Looks good to me, I have added a couple of suggestions!

**Comment by lauraclarke** [comment]
Thanks, I accepted most of them, I left out the specific examples though as I am not sure that is needed
