### ISSUE TITLE
should past team members have access

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#421]

**Comment by amnonkhen** [comment]
See, for example https://github.com/HumanCellAtlas/metadata-schema/settings/access.
Many past team members have permissions there.

The question is also relevant for:
- google drive
- slack
- git

Should they be removed?

**Comment by ipediez** [comment]
@amnonkhen should we close this ticket? Or do we need to have a discussion about removing permissions for past team members?

**Comment by ofanobilbao** [comment]
@amnonkhen I would suggest either we do something about it now or we close the ticket. How does that sound?

**Comment by ofanobilbao** [comment]
If we need to resurface this ticket we can do it in the future. More than a ticket I'd say that we actively remove people when we identify and can. So I will close the ticket that has been lingering here for quite a while. I have removed all past members of the HCA team from the DCP/HCA shared Google drive where I have permissions to remove people. Someone with permissions will need to do the same for AIT. I see that slack is up to date. Maybe a dev can remove permissions for past staff in Ingest (wrangler permissions)
