### ISSUE TITLE
Investigate how many matrix files do not have content_description: "Matrix"

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#423]

**Comment by ESapenaVentura** [comment]
Some quick insight on analysis files:
- 414 files that don't have content_description nor file source
- 163 files that don't have content_description but have file_source
- 28 files with content description but not file source
Restrictions applied:
- Analysis Files that have schema version >= 6.3 (When file_source was introduced)
- Analysis files with dcpVersion > 2021-05-21 (Last date we used the import spreadsheet and moved onto describing matrices in the metadata)

**Comment by ESapenaVentura** [comment]
All the analysis files in ingest, grouped by project UUID:
[https://app.zenhub.com/files/261790554/0780c10c-d7bf-472a-948f-1fbc8a7dc4e1/download](https://app.zenhub.com/files/261790554/0780c10c-d7bf-472a-948f-1fbc8a7dc4e1/download)

**Comment by ESapenaVentura** [comment]
### Changes done to the list:

- Deleted errored files (Assumed error in file == submission not sent)
- Deleted files from projects not submitted (Status != Exported, Complete)

Questions I tried to answer:
- How many of the files with file source AND content_description have wrong content description?
    - How many files do we need to manually check? 14 projects - 105 files
    - How many files we suspect are matrices? 4 projects - 14 files

- How many of the files have no file source but have content description and content description is wrong?
    - 0 files

- How many of the files have no file source nor content description?
   - Suspected matrix: 12 files from 2 projects
   - Need manual check: 92 files from 3 projects

### How this list was generated

1. Find all analysis files in ingest
1. Rule out files that have schema <6.3 (Before file source)
1. Rule out files that were submitted before 2021-05-21 [Row 326](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY/edit#gid=0)
1. Rule out errored files (if file.get('errorMessage'))
1. Rule out files from non-submitted submissions (requests.get(file['_links']['submissionEnvelope']['href']).json()['submissionState'] in ['Completed', 'Exported']
1. Group them by project uuid (requests.get(file['_links']['project']['href']).json()['uuid']['uuid'])
1. Further group them by:
   * Do they have content description?
   * Do they have file source?
1. For each group:
   * Get how files that have content description
   * Check content description for “matrix”, “mtx”, “loom”, “hd5” in filename, if yes then suspect matrix, if not, manual check

Generated files are here:
[https://app.zenhub.com/files/261790554/84763e66-aacb-4e04-a7e8-903d23a6bc64/download](https://app.zenhub.com/files/261790554/84763e66-aacb-4e04-a7e8-903d23a6bc64/download)

**Comment by Wkt8** [comment]
Further details to be agreed at the wrangler call with UCSC today, then meet the browser team after the meeting to handover details.

**Comment by ESapenaVentura** [comment]
Moving forward, only file_source and entity type will be determinant for what's considered a CGM

That means, we need to correct the files without a file source and (if possible but optional) the content_description

**Comment by gabsie** [comment]
Thanks, Enrique, for the analysis and follow up.

So from your list above, ... how many still need checking? whether their content description is right/wrong/missing?
I guess now we are not that bothered about file source, since the relaxing of the rule?

Thanks!

**Comment by ESapenaVentura** [comment]
@gabsie the contrary, what is being relaxed is the matrix ontology in the content description

Now we need to make sure that files do have file_source

From the projects above, we have all of them covered in our lists

We can re-run the analysis after we make the fixes to the CGMs

**Comment by gabsie** [comment]
Hey - I know the rule about 'matrix' is relaxed for content description, however I feel we need to always have the right one entered there as well as not have missing ones, because if they decide to show that text in the table, we don't want it to appear empty.. 

So I guess my question is, for how many do we have to update file source?
Additionally, are we confident with the content descriptions we have?

Sorry for the misunderstanding! I only want to know if we have to have any updates at all to these two 'entities'. (If not, wonderful!)
:) Gabs

**Comment by ESapenaVentura** [comment]
I agree, we should always fill those fields to the best of our extent!

All the analysis files with the file_source missing are covered by the other CGM tickets

On the content descriptions side, let me have a look

And to the last question, I meant the other CGM tickets!

**Comment by ESapenaVentura** [comment]
The content description issue is covered also in the other CGM tickets

**Comment by gabsie** [comment]
shall we close this one?

**Comment by ESapenaVentura** [comment]
I think so 👍

**Comment by gabsie** [comment]
Yupeee - they are all filled!
