### ISSUE TITLE
CGM fixes for Release 7 and 8

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/hca-ebi-wrangler-central#426]
**Description of the task:**
Fixed content descriptions and project source fields.

**Project List:**

**Release 7**
- [x] [d3446f0c-30f3-4a12-b7c3-6af877c7bb2d](https://contribute.data.humancellatlas.org/projects/detail?uuid=d3446f0c-30f3-4a12-b7c3-6af877c7bb2d) Fix Content Description, Analysis protocol Type, and File Source
- [x] [8a40ff19-e614-4c50-b23b-5c9e1d546bab](https://contribute.data.humancellatlas.org/projects/detail?uuid=8a40ff19-e614-4c50-b23b-5c9e1d546bab) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [403c3e76-6814-4a2d-a580-5dd5de38c7ff](https://contribute.data.humancellatlas.org/projects/detail?uuid=403c3e76-6814-4a2d-a580-5dd5de38c7ff) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [7880637a-35a1-4047-b422-b5eac2a2a358](https://contribute.data.humancellatlas.org/projects/detail?uuid=7880637a-35a1-4047-b422-b5eac2a2a358) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [71436067-ac41-4ace-be1b-2fbcc2cb02fa](https://contribute.data.humancellatlas.org/projects/detail?uuid=71436067-ac41-4ace-be1b-2fbcc2cb02fa) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1](https://contribute.data.humancellatlas.org/projects/detail?uuid=d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [78b2406d-bff2-46fc-8b61-20690e602227](https://contribute.data.humancellatlas.org/projects/detail?uuid=78b2406d-bff2-46fc-8b61-20690e602227) Fix Content Description, and Analysis protocol Type
- [ ] [faeedcb0-e046-4be7-b1ad-80a3eeabb066](https://contribute.data.humancellatlas.org/projects/detail?uuid=faeedcb0-e046-4be7-b1ad-80a3eeabb066) Fix Content Description, Analysis protocol Type, and File Source

**Release 8**
- [ ] [414acced-eba0-440f-b721-befbc5642bef](https://contribute.data.humancellatlas.org/projects/detail?uuid=414acced-eba0-440f-b721-befbc5642bef) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [3cfcdff5-dee1-4a7b-a591-c09c6e850b11](https://contribute.data.humancellatlas.org/projects/detail?uuid=3cfcdff5-dee1-4a7b-a591-c09c6e850b11) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [ebacfc36-19d5-4adb-bc6e-122e8fbbc68a](https://contribute.data.humancellatlas.org/projects/detail?uuid=ebacfc36-19d5-4adb-bc6e-122e8fbbc68a) Fix Content Description, Analysis protocol Type, and File Source
- [ ] [dbcd4b1d-31bd-4eb5-94e1-50e8706fa192](https://contribute.data.humancellatlas.org/projects/detail?uuid=dbcd4b1d-31bd-4eb5-94e1-50e8706fa192) Fix File Source

**Acceptance criteria:**

- [ ] Datasets have been corrected and exported

**Comment by ESapenaVentura** [comment]
@willrockout Are all of these UCSC datasets?

**Comment by rachadele** [comment]
@ESapenaVentura yes

**Comment by willrockout** [comment]
@ESapenaVentura Sorry went over my time completing this on Friday. As Rachel said these are only UCSC datasets, I've listed below which are complete status/need kicking, have been newly exported, and a final one where there is a linking problem:

Need kicking:

1. 403c3e76-6814-4a2d-a580-5dd5de38c7ff
2. 7880637a-35a1-4047-b422-b5eac2a2a358
3. 71436067-ac41-4ace-be1b-2fbcc2cb02fa
4. d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1
5. faeedcb0-e046-4be7-b1ad-80a3eeabb066
6. 3cfcdff5-dee1-4a7b-a591-c09c6e850b11
7. ebacfc36-19d5-4adb-bc6e-122e8fbbc68a
8. dbcd4b1d-31bd-4eb5-94e1-50e8706fa192


Re-Exported:

1. d3446f0c-30f3-4a12-b7c3-6af877c7bb2d
2. 8a40ff19-e614-4c50-b23b-5c9e1d546bab
3. 78b2406d-bff2-46fc-8b61-20690e602227

Needs to be Soft Deleted:

1. 414acced-eba0-440f-b721-befbc5642bef error in linking floating enrichment protocol

**Comment by ESapenaVentura** [comment]
@jacobwindsor

**Comment by ESapenaVentura** [comment]
@willrockout for the dataset that needs to be soft-deleted:

Why does it need to be soft deleted? You can update the processes to add the enrichment protocol. I think I didn't go through it because we had limited time but if you go to the `process` tab and expand on the processes, you can re-link existing processes (That includes associating protocols)

**Comment by willrockout** [comment]
@ESapenaVentura Oh didn't know that we could fix graph things is this because it is just attaching to a process rather than creating a new entitity?

**Comment by ESapenaVentura** [comment]
Exactly :)

We also have programmatic ways of creating new processes (and with this "re-linking" you are effectively creating new processes), but that's a bit more advanced (Happy to teach it if needed, I just don't want to have a "hacker" way of doing this written down!).

Also due to how the data is created in the staging area, you'll need to update the "bundle" process (the process linking a biomaterial to a file). the `links.json` files use the timestamp and UUID of those processes so those won't update unless you modify those processses

**Comment by ESapenaVentura** [comment]
In the UI, actually, there's no way to update processes in the spreadsheet currently

**Comment by jacobwindsor** [comment]
I have set the following projects to "valid" status so that they are ready to be reexported:

```
403c3e76-6814-4a2d-a580-5dd5de38c7ff
7880637a-35a1-4047-b422-b5eac2a2a358
71436067-ac41-4ace-be1b-2fbcc2cb02fa
d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1
faeedcb0-e046-4be7-b1ad-80a3eeabb066
414acced-eba0-440f-b721-befbc5642bef
cfcdff5-dee1-4a7b-a591-c09c6e850b11
dbcd4b1d-31bd-4eb5-94e1-50e8706fa192
```

The project `ebacfc36-19d5-4adb-bc6e-122e8fbbc68a` does not seem to exist anymore.

Please re-export these when ready and ensure you click the "Submit only metadata to the Human Cell Atlas." option

@ESapenaVentura @willrockout

**Comment by rachadele** [comment]
for some reason I'm not able to access cfcdff5-dee1-4a7b-a591-c09c6e850b11 ?

**Comment by rachadele** [comment]
also, the correct UUID for ebacfc36-19d5-4adb-bc6e-122e8fbbc68a is actually 8bd2e5f6-9453-4b9b-9c56-59e3a40dc87e. Can we get the status changed to "valid" on that project?

**Comment by jacobwindsor** [comment]
@rachadele Sorry, that was a typo, fixed now. 

8bd2e5f6-9453-4b9b-9c56-59e3a40dc87e is now in "valid" state

**Comment by Wkt8** [comment]
@rachadele and @willrockout is this ticket now complete with the import forms sent for all the tickets?

**Comment by rachadele** [comment]
@Wkt8 yes!
