### ISSUE TITLE
GSE168405_organoidendometrial

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#429]
### Secondary Wrangler:
@ami-day / @ESapenaVentura 

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1SEI5pASMURCDo6IvPvrvWvK5AUt7Tk1V

**Latest google sheet:**
https://docs.google.com/spreadsheets/d/1MKzczXQV94nZHhSCiLWElAMhpeCe7Cjk2bZXZg_4g5Y/edit#gid=390429689

### Published study links

* Paper: https://elifesciences.org/articles/69603

* Accessioned data: [GSE168405](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE168405)

### Key Events

- [X] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Started wrangling but it's a difficult dataset - Contains assembloids

I will contact @ami-day when capacity allows

**Comment by ami-day** [comment]
Shall we discuss this dataset tomorrow @ESapenaVentura ?

**Comment by ami-day** [comment]
Hi @ESapenaVentura I have completed the unfilled metadata and aded ontologies. Also, we should discuss the experimental design. I have highlighted in yellow some differences to how I would have modelled it, in particular to:

- cell_line.biomaterial_core.biomaterial_id

- organoid.biomaterial_core.biomaterial_id

- aggregate_generation_protocol.protocol_core.protocol_id

- differentiation_protocol.protocol_core.protocol_id

**Comment by Wkt8** [comment]
Hi Ami. I had a look at the existing spreadsheet and noted down where I think things should be modelled differently / were not filled in. Overall I agree with the assembloids being modelled as organoids generated from the existing organoids and purified cells, but have noted down some changes below in the respective tabs. Let me know if you have any questions! 

Donor Organism Tab:
- This would be a good target for updating for when we add menstrual cycle to the metadata schema 

Collection protocol:
- I'm not sure about the collection method 'curretage'. Looking at the Wallach Endocell Endometrial Cell Sampler, it appears to work via suction aspiration - and there is a paper which explicity compares the Wallach Endocell Enometrial Cell Sampler method (calling it endometrial sampling) against curretage (https://obgyn.onlinelibrary.wiley.com/doi/10.1111/j.1447-0756.2010.01376.x) 
- I would probably recommend using 'vacuum aspiration' EFO:0010727 instead. 

Specimen_from_organism
- Collection protocol ID is not linked to the specimens. Needs to be added. 

Cell_line
- I think the cell_line description should actually be a separate enrichment_protocol? It is technically an enrichment_protocol aimed at isolating the adherent EnSCs from non-adherent cells and there is an ontology term for it 'isolation of adherent cells' (OBI:0000540)
- For 'cell_line.type' I don't think it should be stem cell-derived, as the cell_lines don't come from stem cells, they come from endometrial stromal cells. Would recommend 'primary' as the cell line type. 
- Similarly cell_line.cell_type should not be 'stem cell', rather 'stromal cell of endometrium' (CL:0002255)

Organoid
- The endometrial gland-like organoids have a 'specimen_from_organism' as the input. I would have modelled it as the cell_line as the input.
- Additionally, the assembloids should have the 'cell_line' and the 'endometrial_gland_like_organoid' as the input. (as the cell_line has gone through the dissociation and enrichment processes to obtain the EnSCs)

Cell suspension
- There is an 'input specimen_from_organism_ID' column which instead has BioSamples Accessions. This should be replaced with an 'input_organoid_ID' column with the correct assembloid IDs. 

Analysis protocol 
- does not have an analysis_protocol_type. I would recommend 'processed matrix generation' (EFO:0030023)

Sequence_file
- The file_name column is empty!

**Comment by ami-day** [comment]
Thanks @Wkt8 , re-reading the Methods, I agree with all your suggested changes and have made them, except for this one:

"The endometrial gland-like organoids have a 'specimen_from_organism' as the input. I would have modelled it as the cell_line as the input."

In the **Endometrial gland-like organoid culture** Methods section, it says "Freshly isolated endometrial gland fragments were resuspended...". This suggest to me that the input material is primary tissue specimen. Then, the EnSCs and the gland-like organoids are then used as input for the **Establishment of assembloid cultures**

Hope that sounds ok to you!

Will download the fastq files now.

**Comment by ESapenaVentura** [comment]
Checked that the number of donors look right, health status, tissues, and number of data files/matrices. All of that looks alright

However, the data curator is missing. Moving to needs update

**Comment by ami-day** [comment]
Added the curator (me): https://contribute.data.humancellatlas.org/submissions/detail?uuid=e36ea62d-cecf-48fa-a1a2-6e202e2071e3&project=91af6e2f-65f2-44ec-98e0-ba4e98db22c8

**Comment by ami-day** [comment]
exported.

**Comment by ami-day** [comment]
looks as expected in the hca data portal.
