### ISSUE TITLE
Update contributor spreadsheet instructions with analysis files information

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#431]
**Description of the issue**:
As a contributor, new to the HCA schema and methods for collecting metadata, I would like to know what the `analysis_file` tabs are for and how to fill them out.

**Acceptance criteria**:
- [ ] The [Spreadsheet quick guide](https://ebi-ait.github.io/hca-metadata-community/contributing/spreadsheet-guide.html) has been updated

**Comment by ESapenaVentura** [comment]
PR here https://github.com/ebi-ait/hca-metadata-community/pull/3/files

**Comment by prabh-t** [comment]
@Wkt8 to check PR.
