### ISSUE TITLE
Write SOP for the contributor -> project submission wrangling workflow

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#44]
**Description of the task:**

The wranglers currently do not have a complete, up to date SOP for the **contributor** wrangling process, in terms of accepting metadata and data from a new contributor through to submitting their dataset in production ingest. This includes submitting to EBI archives and/or DCP2.0 (instructions about DCP2.0 will be added when this becomes possible).

Link to 1st draft (in-progress): https://docs.google.com/document/d/1ZLPFw4jeFaEnNAxLT_Iz5T-QyM5cQp4lMkgkP8IIS6g/edit

**Acceptance criteria for the task:**

- [x] Write SOP (Ami)

- [x] Integrate old draft SOP into new SOP

- [x] Get feedback on SOP from other wranglers and update it based on feedback (Ami)

- [x] Add the SOP to Marion's Github HCA webpage (Marion)

**Comment by mshadbolt** [comment]
Ami and I worked on this and it is now live on the website here: https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/contributor_dataset_SOP.html

I kinda skipped the feedback step... but happy to incorporate any feedback either into the markdown document if it is put into the google doc first.

Wranglers should feel free to edit the markdown here: https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/docs/SOPs/contributor_dataset_SOP.md

And if they aren't sure about the change they can make a pull request and ask others to review
