### ISSUE TITLE
Fastq file removal required to unblock dataset for release 10

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#442]
I have an in-progress dataset in which too many files were synced (we are not yet able to sync specific files using hca-util sync, only a directory containing files). In order to submit this dataset some of the fastq files need to be removed from ingest prod.

**Comment by ofanobilbao** [comment]
@ami-day could you, please, add link to the dataset?

**Comment by ami-day** [comment]
It's done
