### ISSUE TITLE
Issues uploading a dataset with imaging tabs to ingest prod.

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#445]
I am working on an imaging technology dataset, and I am getting an error importing the spreadsheet to ingest production. I think this is because of known problems with the imaging tabs, but it is difficult to interpret the error message I am getting.

submission in ingest production: https://contribute.data.humancellatlas.org/submissions/detail?uuid=3cf32c24-c2a8-4874-a413-aeb1ab66b2af

**Comment by jacobwindsor** [comment]
I think this should be on the dev board
