### ISSUE TITLE
Updating / Overwriting Lavaert thymus 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#446]
**Description of the task:**
Ray exported a project only with processed data due to GDPR concerns
(https://data.humancellatlas.org/explore/projects/dbd836cf-bfc2-41f0-9834-41cc6c0b235a , https://contribute.data.humancellatlas.org/projects/detail?uuid=dbd836cf-bfc2-41f0-9834-41cc6c0b235a&tab=project) 

Stanford has now wrangled that project with all of the fastqs 
https://humancellatlas.slack.com/archives/C9ENBPVNW/p1631642559002000 

Need to figure out a plan of action on whether Stanford should update / how it will be done. Or to manage a soft-delete and for them to update in the staging area. 

**Acceptance criteria for the task:**
fastqs are added to the project in the data portal (https://data.humancellatlas.org/explore/projects/dbd836cf-bfc2-41f0-9834-41cc6c0b235a)

**Comment by Wkt8** [comment]
We need to inform stanford about next actions / future actions for now 
- will this work if they're still using an older version of the schema?

**Comment by ofanobilbao** [comment]
Enrique sent an email to Jason yesterday. A meeting will take place today to make sure that we capture all the metadata that they have gathered from the contributors etc so that we can update the dataset not to mess the UUID

**Comment by amnonkhen** [comment]
- Meeting with Jason took place on Friday

**Comment by ESapenaVentura** [comment]
Lattice has regenerated the project - @ESapenaVentura to add this topic to the demo next tuesday

**Comment by prabh-t** [comment]
Enrique - will speak about how to proceed with deletion in the next dcp demo.

**Comment by ESapenaVentura** [comment]
AI
- Ask for deletion to Andrew (Data import team)
- Ask lattice to re-export to their staging area with SAME PROJECT UUID(May be done already)
- Ask Lattice to fill an import form

**Comment by aaclan-ebi** [comment]
@ESapenaVentura to send Andrew the list of projects that needs to be deleted. This may include submissions from #541 and #551

**Comment by jacobwindsor** [comment]
@ESapenaVentura to set up a meeting to discuss how to move on from this

**Comment by ofanobilbao** [comment]
@ESapenaVentura to reach out to Jason for Lattice to import their version of the project

**Comment by ESapenaVentura** [comment]
Jason has confirmed they have sent a request to import their version of the project
