### ISSUE TITLE
snRNA-seq_for_human_retina: needs update (DCP1 dataset)

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#447]
This DCP1 dataset: **snRNA-seq_for_human_retina** needs updating. Specifically lane indices are needed to distinguish the multiple files per input cell suspension. However it is a **DCP1 dataset**, we cannot update DCP1 datasets currently. The submission in ingest prod. is here: https://contribute.data.humancellatlas.org/submissions/detail?uuid=7d515499-b5b6-4083-95cd-6a393344865e&project=9c20a245-f2c0-43ae-82c9-2232ec6b594f **N.B.** it was wrangled by Zina.

**Comment by ofanobilbao** [comment]
This project was deleted and Lattice will submit to DCP. So this ticket no longer needed
