### ISSUE TITLE
Prepare presentation to the DCP about wrangling

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#45]
**Description of the task:**

As wranglers we need to create a presentation to the DCP. Some of the questions we would like answered are (specified by @lauraclarke ):

How do you help contributors?
What are the steps involved in getting data from them to the DCP?
What other tasks are you involved in?
What challenges do you face in supporting contributors sharing their data? 

Laura would like to see:
> a focus on the needs of the contributors and consumers of the data and how the services we offer meet those needs rather than any detailed description of the internals of ingest

Original request from Kathleen:
>“I was talking with Jonathan today about controlled access, and we both realized that it would be helpful for us (and possibly others) to understand more about how the wrangling process works -- from the first contact with the data contributor to wrangled data being finally ingested and released. I don’t think we need to understand in great detail what happens in each phase, but more what the usual contacts, steps, meetings, and handoffs are along that path. Would one or more of you be willing to do an overview for any interested parties?”

We will be working with Paris and Will to create this.

We will also introduce all wranglers

We need to provide a copy of the final presentation to Clay and Laura by 19th June

We will give the presentation on 24th June at 4pm BST

**Acceptance criteria for the task:**

- [ ] Slides created in collaboration with Paris and Will
- [ ] Slides sent to Clay and Laura for feedback
- [ ] Presentation complete

**Comment by ami-day** [comment]
slides from UCSC: https://docs.google.com/presentation/d/1QAdGRvA00EkN_A_-KQ5tuJGvj2rPfHCE7NpBK4WxKY8/edit?ts=5ee20b24#slide=id.p

**Comment by ami-day** [comment]
@mshadbolt shall we meet on Monday to discuss?

**Comment by lauraclarke** [comment]
having had a quick scan, I think the broad audience will be interested in our metadata work/ontology mapping so it would be good to see that included

**Comment by mshadbolt** [comment]
@ami-day sounds good. 

@lauraclarke Do we know who originally created the slides above? Not sure if we should use them as a starting point or start from scratch.

**Comment by lauraclarke** [comment]
@mshadbolt, as I understand if, the UCSC wranglers were asked to present the wrangling process to people at CZI at some point last year, given neither you nor Enrique, are on the slides I suspect it was early last year.

As they were presenting to CZI I think that somewhat explains the very technical focus of the slides about the process and how data moves rather than the user goals and the data itself

**Comment by mshadbolt** [comment]
Provided link to slides to all wranglers and UCSC team 
https://docs.google.com/document/d/1kIyh1NOc8HamEilydLKNgw555A0rIh32Cn5abV1_uPA/edit?usp=sharing

**Comment by mshadbolt** [comment]
Presentation given, added to AIT drive and posted on slack channel. Closing...
