### ISSUE TITLE
Clean up unused labels in the repository

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#453]
**Description of the issue**
There are several labels that are not used in the repository, or are duplicates. We need to clean these up as they may lead to confusion

**Acceptance criteria**
- [ ] Unused/duplicated etc labels have been identified and deleted

**Comment by amnonkhen** [comment]
@ESapenaVentura are there any specific labels that need attention or cleanup? If not, I believe this can be closed.

**Comment by ipediez** [comment]
@ESapenaVentura can we close this?

**Comment by ESapenaVentura** [comment]
Sure, I think it's been done as part of other conversations
