### ISSUE TITLE
b7259878-436c-4274-bfff-ca76f4cb7892 not showing species, organ/part, disease in the data browser

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#458]
**Description of the issue**
The project `Fate-mapping within human iPSC-derived kidney organoids reveals conserved mammalian nephron progenitor lineage relationships.` (`b7259878-436c-4274-bfff-ca76f4cb7892`) is not showing species, organ/part, disease in the data browser.

**Ingest**
[Fate-mapping within human iPSC-derived kidney organoids reveals conserved mammalian nephron progenitor lineage relationships.](https://contribute.data.humancellatlas.org/submissions/detail?uuid=bdd1b6ca-7431-413e-97ec-71e36bf6073d&project=b7259878-436c-4274-bfff-ca76f4cb7892)

**Data browser**
[Fate-mapping within human iPSC-derived kidney organoids reveals conserved mammalian nephron progenitor lineage relationships.](https://data.humancellatlas.org/explore/projects/b7259878-436c-4274-bfff-ca76f4cb7892)

**Primary wrangler**
@ami-day 

**Other useful information**
* Conversation [here](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/420#issuecomment-923849871)

**Comment by ami-day** [comment]
I need to look into Hannes response about this

**Comment by ami-day** [comment]
Latest update: no species or disease status https://data.humancellatlas.org/explore/projects/b7259878-436c-4274-bfff-ca76f4cb7892

**Comment by ami-day** [comment]
Added a collection protocol, donor and skin tissue specimen for the human fibroblast cell line, and linked them together in 2 new processes. Re-graph validating.

**Comment by ami-day** [comment]
Re-submitted.

**Comment by ofanobilbao** [comment]
@ami-day is this Done? Last comment says you re-submitted but the ticket is still In Progress

**Comment by ami-day** [comment]
I need to update the normal ontology label and then re-submit

**Comment by ami-day** [comment]
Graph validating

**Comment by ami-day** [comment]
This project is stuck in "graph validation requested" status.

**Comment by MightyAx** [comment]
Graph valid

**Comment by ofanobilbao** [comment]
Re-opening the ticket as from what I can see Ami never exported the update after Alexie helped to unblock it. It should be ready for a wrangler to just push the export I guess. Moving to the To Do list

**Comment by ofanobilbao** [comment]
Just submitted the metadata update in Ingest. Will complete the import form once the submission is Exported

**Comment by ofanobilbao** [comment]
The submission has been stuck in "Exporting" for the last 24h. No idea if that's to be expected or not. Will check in Stand-Up

**Comment by ofanobilbao** [comment]
@MightyAx just sorted the issues on https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/985 

Project updates have now been exported. I will fill the Import form and add to wrangling board as well to track that we check the Updates on Release 23

**Comment by ofanobilbao** [comment]
Import form submitted

**Comment by ofanobilbao** [comment]
Looks good in the browser. So closing it
