### ISSUE TITLE
e57dc176-ab98-446b-90c2-89e0842152fd Not showing some biomaterial information in browser

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#460]
**Description of the issue**
The project `Plasticity of distal nephron epithelia from human kidney organoids enables the induction of ureteric tip and stalk` (`e57dc176-ab98-446b-90c2-89e0842152fd`) is not showing species, organ/part, disease in the data browser.

**Ingest**
[Plasticity of distal nephron epithelia from human kidney organoids enables the induction of ureteric tip and stalk.](https://contribute.data.humancellatlas.org/projects/detail?uuid=e57dc176-ab98-446b-90c2-89e0842152fd)

**Data browser**
[Plasticity of distal nephron epithelia from human kidney organoids enables the induction of ureteric tip and stalk.](https://data.humancellatlas.org/explore/projects/e57dc176-ab98-446b-90c2-89e0842152fd)

**Primary wrangler**
@ami-day 

**Other useful information**
* Conversation [here](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/420#issuecomment-923849871)

**Comment by ami-day** [comment]
I need to look into Hannes response about this

**Comment by ami-day** [comment]
No species or disease status: https://data.humancellatlas.org/explore/projects/e57dc176-ab98-446b-90c2-89e0842152fd

**Comment by ami-day** [comment]
Note: the "normal" ontology option is not displaying in the ingest browser when selecting the disease status. I was able to save "normal" but without an ontology label selection. This might mean that the disease status still does not get displayed in the data browser. Need to check this.

**Comment by ami-day** [comment]
Pasting the relevant latest info here:
the processes linked to sequence files need to be updated. At the moment, there are 2 processes per pair of read files as opposed to 1. This needs to be updated in bulk. We need to be able to make bulk linking updates in ingest (we have a ticket for it). So this is stalled for now.

**Comment by idazucchi** [comment]
I fixed the linking issues by grouping R1/R1/I1 in the same process and deleted the redundant processes.
The species, organ/part, disease don't show up in the browser because there is no donor. 
I've added a donor and linked it to the cell lines with a collection protocol. The donor is the same for both cell lines because they have the same parental cell line

**Comment by idazucchi** [comment]
I've filled out the import form

**Comment by idazucchi** [comment]
the species and model organ are showing up correctly in the Data platform
