### ISSUE TITLE
EGAS00001004481 - COVID_19AirwayEpitheliumImmune

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#461]
### Project short name:
COVID-19AirwayEpitheliumImmune
### Primary Wrangler:
@Wkt8 
### Secondary Wrangler:
@ESapenaVentura 

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1ou0wngCn4doty64158WrhTl14RpjPhgO

### Published study links

* Paper: [COVID-19 severity correlates with airway epithelium–immune cell interactions identified by single-cell analysis](https://www.nature.com/articles/s41587-020-0602-4)

* Accessioned data: [EGAS00001004481](https://ega-archive.org/studies/EGAS00001004481)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [x] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Added to the google drive!

**Comment by ESapenaVentura** [comment]
After a hard day of collaboration, @Wkt8 and I managed to curate the metadata and data!

Ingest-graph-validator throws an error for the analysis files, but this is a known issue with one of the tests not being specific enough (Should apply only to sequence files, not analysis files)

**Comment by ESapenaVentura** [comment]
Dataset is exported!

**Comment by Wkt8** [comment]
Import form completed for release 10!
