### ISSUE TITLE
Managed Access Taskforce DAC EGAS00001004481

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#463]
**Description of the task:**
For the Managed Access Taskforce (https://docs.google.com/document/d/15NsoqNYKAh1-tesj9H-G9lw3Nmt_Gu9uyzxcaqDM8hs/edit#heading=h.r43bcafrvlxd) we have selected and wrangled a specific dataset (https://ega-archive.org/studies/EGAS00001004481) 

Need to reach out to the Data Access Committee (DAC) and get the Data Access Agreement (DAA) and see what fields are required. 

Dataset Info:
Dataset ID: EGAD00001006339	
Title: COVID-19 severity correlates with airway epithelium–immune cell interactions identified by single-cell analysis
Technology: Illumina NovaSeq 6000	
Samples: 36
Files: 228 fastqs

**Acceptance criteria for the task:**
- email the DAC for dataset id
- confirm if we need one DAC signed per institution
- confirm the required fields for this application 
- relevant parties (Broad) or (Broad and EBI) have a login to have access to the data

**Comment by Wkt8** [comment]
Waiting for contributor to get back to us

**Comment by ESapenaVentura** [comment]
@Wkt8 to have a look at the DAA and come back to them

**Comment by ofanobilbao** [comment]
Wranglers waiting for now

**Comment by prabh-t** [comment]
Wei - meeting yesterday. Couple of actions @wei can comment here.

**Comment by Wkt8** [comment]
Tony/Wei will draft a data flow diagram - Friday 5th
Enrique/Nikelle/Marcos will provide input on the figure - Weds 10th

**Comment by Wkt8** [comment]
We have created a document for the usage of the EGA dataset: https://docs.google.com/document/d/1jJKOIQrb_2bxn7zkbrEMyLKuu_VYNlTwkFDjXhS10Wk/edit# and have reviewed and revised. 

It requires a bit more information from the Broad side.
