### ISSUE TITLE
check Release 10 datasets are published correctly in the data portal

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#464]
Wranglers to check datasets are published correctly in the data portal

- [x] #498
- [x] #499
- [x] #500
- [x] #501
- [ ] #502
- [x] #503
- [x] #504
- [x] #505
- [ ] #506
- [ ] #507

**Comment by Wkt8** [comment]
Have checked all - three tickets left which are open.
