### ISSUE TITLE
Sending Imaging Test Data 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#465]
**Description of the task:**

We want to start submitting and exporting datasets with imaging data to the DCP. Before we do this in prod, we want to make sure we send the appropriate test data. 

**Acceptance criteria for the task:**
Figure out: 
- what metadata-schema-changes are necessary
- prioritise them in the 'Schema prioritisation SOP' and make a PR involving those changes
- are we going to send test data via the schema-test repo or as a test submission in dev
- generate the test data
- send the test data
- get it approved
- clear that we are going to export datasets in prod

**Comment by Wkt8** [comment]
There are 3 schema-change tickets related to imaging schemas: 
- Updates to imaging protocol schema #1405
- New schema update to specimen_from_organism schema #1406
- Schema update: update library preparation protocol barcode fields #1407

#1405 and #1406 are related to NanoString and RNAScope, whilst #1407 is focused on spatial barcodes and Visium. There may be additional metadata schema changes necessary for microscopy in the future. 

We want to push #1407 first for the Visium datasets. We should talk about this in the wrangler-ucsc-catchup and the prioritisation SOP.

**Comment by ofanobilbao** [comment]
@Wkt8 is this still stalled?

**Comment by Wkt8** [comment]
I need to check in with will from UCSC about the progress of the metadata schema update, because we are sending the data with that.

**Comment by Wkt8** [comment]
Created imaging test data here: 

https://drive.google.com/drive/folders/15MOmkLStw7AzSoK6sSEbdv_HJY0bZcZF

**Comment by gabsie** [comment]
When Will makes the PR for the metadata changes, he will attach the imaging test data and we will ask for reviews from the other components. @Wkt8  will check with Will if any help is needed.

**Comment by Wkt8** [comment]
Will has made the PRs - he stated he has posted in the slack channel to get reviews.

**Comment by aaclan-ebi** [comment]
@gabsie to follow up on the reviews with DCP reviewers.

**Comment by Wkt8** [comment]
Imaging PRs have been merged into master - channel and probe are no longer required.

**Comment by ofanobilbao** [comment]
@Wkt8 to submit in staging the project that is ready to submit. Tag Hannes and the relevant people to check

**Comment by Wkt8** [comment]
Will submit in staging.

**Comment by Wkt8** [comment]
After a conversation with at the DCP demos - we have decided to submit imaging test data via the schema-test-data repo. Currently, the submissions are stuck in a 'pending' state in staging.

**Comment by idazucchi** [comment]
staging is not functioning well right now - @jacobwindsor is investigating

**Comment by aaclan-ebi** [comment]
@amnonkhen and @jacobwindsor to look into the issue in staging.

**Comment by aaclan-ebi** [comment]
@Wkt8 is still encountering the issue where submission gets stuck in Pending. @jacobwindsor to look further.

**Comment by MightyAx** [comment]
Taking over as the Dev on Ops.
Scheduled handover meeting with Jacob.

**Comment by jacobwindsor** [comment]
@MightyAx we worked through this yesterday and it is fine now so no action needed from you

**Comment by jacobwindsor** [comment]
@Wkt8 has requested reviews

**Comment by Wkt8** [comment]
Only reviews left are from Amnon and Dave. Will tag them in the PR informing them we , and then follow the SOP to merge it into the schema-test-data repo.

**Comment by Wkt8** [comment]
Completed.

**Comment by gabsie** [comment]
Yay! let's get some Visium datasets in!
