### ISSUE TITLE
contributor account for: Leah Marquez-Curtis

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#472]
Please create an account a contributor.

*Contributor details:*
* name: Leah Marquez-Curtis
* email: marquezc@ualberta.ca

Request Details:
* Requested by: Rachel Schwartz
raschwar@ucsc.edu

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by aaclan-ebi** [comment]
As of now, all devs should still have permission to create accounts and access keys.

@rachadele I cc-ed you on the email containing the zipped file of the access keys. I've also already emailed the contributor with the password to open the zip file.
