### ISSUE TITLE
GSE120386_Genomic programming of IRF4-expressing human Langerhans cells.

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#483]
### Associated files

* Google Drive: 

### Published study links

* Paper: https://doi.org/10.1038/s41467-019-14125-x

* Accessioned data: GSE120386.

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
The metadata schema update needed for a treatment/stimulus protocol has been prioritised.

**Comment by ami-day** [comment]
Treatment protocol has now been added to the hca metadata schema. This dataset can now be curated with treatment protocol metadata included.
