### ISSUE TITLE
EGAS00001004772_Hypertension delays viral clearance and exacerbates airway hyperinflammation in patients with COVID-19

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#484]
### Associated files

* Google Drive: https://drive.google.com/drive/folders/1IiJBwe7HP2P1eO8-DiEENU2zobV1MPZk

### Published study links

* Paper: https://www.nature.com/articles/s41587-020-00796-1

* Accessioned data: EGAS00001004772

Processed data: https://figshare.com/articles/dataset/Hypertension_delays_viral_clearance_and_exacerbates_airway_hyperinflammation_in_patients_with_COVID-19/13200278

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [x] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
I have taken a look at the dataset and I think still needs a couple of adjustments:

### Project
- Label needs to be changed
- EGA accession and paper DOI needs to be removed from supplementary links
- Contributor metadata needs to be reviewed and filled
- Grant metadata needs to be reviewed and filled
- Admin area needs to be updated

### Donor organism
- Corrected covid patient 14 (Had asterisk in id)

### Specimen from organism 
- I think it’s missing the donor linking?

### Cell suspension
- Missing genus species
- Missing input specimen
- There are extra rows, which I suppose were there to join them for linking of the analysis file?

**Comment by Wkt8** [comment]
Have updated the project in prod and the brokering drive based on your comments! 
Project in prod: https://contribute.data.humancellatlas.org/submissions/detail?uuid=d07d2c6f-ff0b-483d-a961-f1a09117a919&project=769a08d1-b8a4-4f1e-95f7-6071a9827555
Brokering Drive: 
https://drive.google.com/drive/folders/1IiJBwe7HP2P1eO8-DiEENU2zobV1MPZk

**Comment by Wkt8** [comment]
Project in data browser also has cell count unspecified: https://data.humancellatlas.org/explore/projects/769a08d1-b8a4-4f1e-95f7-6071a9827555
But it is present in prod in project-level and analysis-level: 
https://contribute.data.humancellatlas.org/projects/detail?uuid=769a08d1-b8a4-4f1e-95f7-6071a9827555

**Comment by Wkt8** [comment]
Project cell count amd matrix-cell count is not showing yet in data portal. Cell count is obtained by summing biomaterials at the cell suspension level.
