### ISSUE TITLE
phs001908_Spatial and single-cell transcriptional landscape of human cerebellar development

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#485]
### Project short name:
CerebellarDevLandscape
### Primary Wrangler:
@ipediez 

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1zGQpeqRoySCgXlLnPO10pY_l9y5X_-te

### Published study links

* Pre-print: https://www.biorxiv.org/content/10.1101/2020.06.30.174391v1.full
* Paper: https://www.nature.com/articles/s41593-021-00872-y

* Accessioned data: phs001908

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [x] Add linkings to covid19 and UCSC on the [External Portals spreadsheet](https://docs.google.com/spreadsheets/d/1XyDA1-4XfmJGvL4qzlkd_FZGfjNxrphVHwYwlmDWCD0/edit#gid=0)
- [x] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by prabh-t** [comment]
Irene mostly finish with this one and to move to secondary review soon.

**Comment by ipediez** [comment]
Needs an update of Ingest Graph Validator. There's already a [PR](https://github.com/ebi-ait/ingest-graph-validator/pull/35) by @ESapenaVentura that has been already approved by @Wkt8 but it's missing another approval. I'll review it tomorrow.

**Comment by ipediez** [comment]
For secondary review, pay attention to:
- It is managed access, so I have not found any sequence file.
- Only 50 cell suspensions seem to be indexed in Biosamples, the rest do not have accession number.
- The individuals are of prenatal stage, and the 'Age' column is defined as 'Age of organism in Age units measured since birth'. I've written the age of the individuals under 'Gestational age', but I'm not sure if this column is only intended to be used when the donor is a gestating person.
- Laser capture microdissection (LCM): I have defined this as a collection protocol. I've modelled the dissection of cerebellums as general dissection, and from the cerebellums (specimen from organism) a subsample is taken with LCM.
- SPLiTseq: Used in this case for snRNAseq
- I've extracted from an excel file the results of differential expression analysis and functional enrichment (KEGG)
- For the aldinger20.processed.h5ad file in the analysis file tab, the value for File Source shoud be Publication or HCA release? This file was accesible through the Covid Cell Atlas, but I have written for now "Publication"

**Comment by idazucchi** [comment]
@ipediez to contact BioSamples and SRA about potentially missing cell suspension.

**Comment by ipediez** [comment]
@Wkt8 to have a look today

**Comment by Wkt8** [comment]
Hello! I kind of went deep into this and buried my head in it. There was a lot! I thought you did a good job modelling it - it was a huge project and quite complicated with the TruSeq and SplitSeq. Feel free to discuss about my comments, and drop me any questions. 

Publication Funders - 
I don't think MR/R006237/1 (MRC and Wellcome Trust) is a grant or funder. The project obtained specimens from the HDBR, but don't think they are funders! 

Collection protocol
- I think only one protocol here is necessary, 'collection_protocol_dissection', and could add a bit more to the collection_protocol_description column. 
	- Specimens from fetal (9–21 PCW) human cerebellum were obtained from the Birth Defects Research Laboratory at the University of Washington or the Joint MRC/Wellcome (MR/R006237/1) Human Developmental Biology Resource
- I would move collection_protocol_LCM to the enrichment protocol tab as enrichment_protocol_LCM


dissociation protocol
- keep dissociation_protocol_nuclei with the ontology term mechanical dissociation for the nuclei undergoing split-seq but add a bit more information in the 'description' cell
	- Frozen tissue samples (whole or half cerebellum) were pulverized on dry ice using a ceramic mortar and pestle. Pulverized samples were transferred to chilled microcentrifuge tubes and stored at −80 °C until use.
	- Where did you get the information for 'dounce homogenisser, Wheaton'? 
- keep dissociation_protocol_lysis with the ontology term enzymatic dissociation 
- add another dissociation protocol for dissociation_protocol_lcm_mechanical including
	- Whole cerebellum was dissected from 16 fetal specimens that had intact calvaria to ensure correct orientation of the cerebellum. Intact cerebella were embedded in OCT, frozen at −80 °C and cryosectioned at 16 μm in the sagittal plane through the cerebellar vermis onto PEN Membrane Glass Slides (Applied Biosystems).
	- use ontology term mechanical dissociation
	- Link this dissociation protocol to the cell suspensions from LCM 

Enrichment protocol
- move collection_protocol_LCM to here as enrichment_protocol_LCM

Specimen from Organism
- Would be useful to fill in the 'known diseases' column as 'normal' 
- Instead of using the 'collection_protocol_LCM' to link the cerebellum samples to the RLVZ_ samples, I would add a columns here for 'enrichment_protocol.protocol_core.protocol_id', linking the moved enrichment_protocol_LCM

Cell Suspension
- I see that some of the BioSamples accessions are missing? I was actually surprised to see that the managed access project had biosample accessions at all but that's cool! Did the cell suspensions missing the biosample accessions have a reason for not having them? 
- It's entirely optional, but filling in the 'selected_cell_types' cells can be really useful for some researchers! 
	- e.g. cerebellar granule cell http://purl.obolibrary.org/obo/CL_0001031

Library preparation protocol
- i think for the library_preparation_protocol.library_construction_method.txt for the TruSeq, it's okay to leave it as TruSeq as that is what is in the journal, as long as the ontology and label match for cDNA library construction
- I tried looking up a bit about TruSeq - it seems the barcodes are applied to the wells, which I found confusing - and I couldn't find out much about the offset and length of the   barcodes and umis either

Sequencing protocol
- bulk rna portocol you can add a bit more to the description which is currently blank: 
	- RNA libraries were barcoded and sequenced including 6–8 samples per lane on an Illumina HiSeq 2000.
- The ontology term for the split-seq protocols should not be 'full length single cell' but rather  'tag based single nucleus RNA sequencing' http://www.ebi.ac.uk/efo/EFO_0009811 
	-  I wasn't sure about this as i looked up split-seq and it seems to be a mix of random hexamers AND poly-dt primers but https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5561556/ seems to say it is a 3'-end counting transcript 


Analysis file
- There is an extra library_preparation_protocol column - this should be removed! 
- Beyond that I wasn't sure where you'd gotten all the analysis files! I could only find the aldinger.h5ad file

**Comment by ipediez** [comment]
Thank you! I'll check all your comments and make the appropriate changes. Regarding some of the points:

- About the funders: you are right, MRC and Wellcome Trust are not funders. Thanks for noticing!
- About the dounce homogenisser, Wheaton: I think I mixed it from another paper, because in this work is only specified that they used a ceramic mortar and pestle. I'll change it.
- About the analysis files: they come from several sources. All the .csv files come from the publication's supplementary materials. The last three files (.tsv.gz, .tsv and .rds) come from UCSC cell browser (https://cells.ucsc.edu/?bp=cerebellum). I was just thinking, does it mean that the dataset has been already wrangled by UCSC? Or is it available here just like it is on covid19 cell atlas (https://www.covid19cellatlas.org/aldinger20/)?

**Comment by ESapenaVentura** [comment]
This is a release 13 dataset!

**Comment by ofanobilbao** [comment]
As per conversation in the DCP-OPS channel it looks as if this dataset failed to be imported on the Broad side again.

**Comment by ipediez** [comment]
I've taken a look at this issue and found the UTF-8 characters in the metadata that are causing problems downstream. I'll change them and re-export the project.

**Comment by ipediez** [comment]
The project has been re-exported. I've asked the team downstream to try to check if now the dataset is good to go, so I'll keep this here until they get back to me.

**Comment by Wkt8** [comment]
Pipelines have said they are not having problems with ASCII characters, but having problems with UTF-8 exclusive characters. 

One potential cause could be copy + paste from different places. 
Still not 100% certain if the accents in contributor names are an issue. 
Maybe we should get pipelines to do some of the work - giving us a list of characters they have an issue with. 
For now, action is to 
- discuss this at the DCP demos post-demo. 
- @amnonkhen to schedule a discussion with... pipelines.

**Comment by ipediez** [comment]
Jeff Korte told me yesterday that "The Broad has an internal meeting on Thursday, Feb 3 to discuss how to correct our import code to allow for UTF-8 characters.  I'll let you know the outcome and the timeline for change, but our goal is to be able to support them as soon as possible." Maybe we should wait until they have discussed this, as they plan to support those characters. Tagging @amnonkhen to make sure that you see this before planning the discussion

**Comment by aaclan-ebi** [comment]
@ipediez waiting for today's meeting decision.

**Comment by gabsie** [comment]
@aaclan-ebi and @ipediez to just check if there's anything on our side
