### ISSUE TITLE
EGAS00001004419_SARS‐CoV‐2 receptor ACE2 and TMPRSS2 are primarily expressed in bronchial transient secretory cells

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#486]
### Project short name:
SARS_COV_2_receptorsBronchial
### Primary Wrangler:
@ESapenaVentura 
### Secondary Wrangler:
@Wkt8 

### Associated files

* Google Drive: https://drive.google.com/drive/u/0/folders/1AxrBpN_pgH237xcEfg4xQkM5S1Z3zRRJ

* Ingest project page: https://contribute.data.humancellatlas.org/projects/detail?uuid=58028aa8-0ed2-49ca-b60f-15e2ed5989d5&tab=project

### Published study links

* Paper: https://www.embopress.org/doi/full/10.15252/embj.20105114

* Accessioned data: EGAS00001004419
Processed data: https://doi.org/10.6084/m9.figshare.11981034.v1.

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [x] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
No data curator in the browser, needs an update

Other than that, LGTM

**Comment by ESapenaVentura** [comment]
Updated with wrangler, sent import submission form

**Comment by ofanobilbao** [comment]
@ESapenaVentura an update will go through for Release 13 then, right?

**Comment by ESapenaVentura** [comment]
Yep!
