### ISSUE TITLE
GSE164829 - Integrated Single Cell Atlas of Endothelial Cells of the Human Lung

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#487]
### Primary Wrangler: 

Ami

### Secondary Wrangler: 

@Wkt8 

### Associated files

**Google Drive:**

https://docs.google.com/spreadsheets/d/1w6peXCe6elE1eiWjhkqMkKEystrHALxk/edit#gid=805828623

https://contribute.data.humancellatlas.org/submissions/detail?uuid=c9033c6f-08f7-4a33-bb55-aab37f80c3e5

### Published study links

* Paper: https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.120.052318

* Accessioned data: [GSE164829](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164829)

* HCA Project ID: [dcp7359019377184957](https://contribute.data.humancellatlas.org/projects/detail?uuid=40931ab4-6c1b-4b60-93d0-2a676b0cc08d)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
The project description seems a bit too short (and it's equal to the project title?) but if it was agreed that that's ok, it's fine to me

Another issue is that the fields were not filled for the project catalogue and the flag was not used. Please remember to fill out these and click on the flag for future datasets

Other than that, looks fine in the browser
