### ISSUE TITLE
Message to pipelines for demultiplexing SS2

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#488]
- [x] Send a message to Farzaneh to ask about demultiplexing SS2 files, scripts/tools

**Acceptance criteria**
- [ ] A decision is reached about how to proceed with the multiplexed SS2 dataset

**Comment by ESapenaVentura** [comment]
Sent a message today, waiting for reply

**Comment by amnonkhen** [comment]
still waiting for an answer

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to answer to Farzaneh's questions regarding SS2 demux

**Comment by ESapenaVentura** [comment]
We decided we no longer want to do this. Closing the ticket
