### ISSUE TITLE
Curation of auto-imports

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#489]
**Description of the issue**
Related to the work being done in https://github.com/ebi-ait/dcp-ingest-central/issues/382, this new import will cause hundreds of new projects to be added to the ingest database.

The script will carry on filling most of the projects data. The projects will not immediately appear on the project catalogue,  as the metadata is incomplete, but the objective of this task is to fill in as much metadata so they can appear in the catalogue.

**Steps to curate**
1. Look at the datasets assigned to you [here](https://docs.google.com/spreadsheets/d/1ktD7Ld74HLJLA5Kl_Mn5ij4i1semiNkXMj6VgmQeLbI/edit#gid=0) 
1. Go to the project page, and curate the following from the paper:
   - Technology: Add the library preparation technologies
   - Organ: Add the organs used in the experiment
   - Cell count: Add how many cells were **generated** in the paper
   - Data access: Fill in the type of data access (Managed, open, mix, it's complicated)
   - Release date: Add today's date
   - Publications: Check if it's an HCA paper by looking for the string "Human cell atlas"
   - Contributors/funders: If a required text field is missing, add `unspecified`. This will be curated when working on the project.
   - Accessions: Make sure that all accessions mentioned in the paper are present
   - Status: Change the status to `eligible` or `non-eligible`
   - Priority: Set the priority based on the chart below

**Priority chart**

| Priority number | Requisites (Any/All) |
|----------------|-----------|
| 1 | HCA paper, Contributor |
| 2 | Primary tissue, Human data, literature | 
| 3 | Other |

**Edge case 1 (Reanalysis paper)**: Add everything aside from cell count, set cell count to 0, status "not eligible"
**Edge case 2 (Review paper)**: Add everything aside from cell count and accessions, set cell count to 0, status "not eligible"

**Acceptability criteria**

- [ ] All datasets with the `New suggestion` label have been curated according to the above guidelines

**Comment by ESapenaVentura** [comment]
Spreadsheet with a link to all projects [here](https://docs.google.com/spreadsheets/d/1ktD7Ld74HLJLA5Kl_Mn5ij4i1semiNkXMj6VgmQeLbI/edit#gid=0) 

TBD how the datasets will be distributed

**Comment by Wkt8** [comment]
Blocked by https://github.com/ebi-ait/dcp-ingest-central/issues/478

**Comment by ofanobilbao** [comment]
Moving to In Progress, as at least my ticket is on that state.

**Comment by jacobwindsor** [comment]
@ESapenaVentura to move this to an SOP

**Comment by ESapenaVentura** [comment]
This has been moved to an SOP: https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_acknowledgement_SOP.html#manual-curation-after-addition

Modifying the tickets to point there and moving this to done
