### ISSUE TITLE
Several organoid datasets show species = Unspecified

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#491]
**Description of the issue**
Some release 10 datasets have an issue with the species not showing in the data portal:
- https://data.humancellatlas.org/explore/projects/b7259878-436c-4274-bfff-ca76f4cb7892
- https://data.humancellatlas.org/explore/projects/e0c74c7a-20a4-4505-9cf1-38dcdd23011b
- https://data.humancellatlas.org/explore/projects/e57dc176-ab98-446b-90c2-89e0842152fd
- https://data.humancellatlas.org/explore/projects/5bb1f67e-2ff0-4848-bbcf-17d133f0fd2d

This is a known issue, due to those datasets not containing a donor_organism or specimen_from_organism and therefore missing the value for the browser.

This is a modelling issue and we need to discuss with the browser team before proceeding.

**Acceptance criteria**

- [x] A discussion is scheduled on how to proceed with this issue.
- [ ] AI emerge from the meeting that will solve this issue and the proper tickets are created
- [ ] The datasets are corrected to include the new specimens/cell lines/specimens/donors

**Comment by ofanobilbao** [comment]
Close if we have tickets for all EBI datasets

**Comment by ofanobilbao** [comment]
https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/460 - Stalled (one of the affected datasets)

https://contribute.data.humancellatlas.org/projects/detail?uuid=e0c74c7a-20a4-4505-9cf1-38dcdd23011b&tab=project - The Operations ticket was marked as Done but Ami did not pushed the update to DCP (I will re-open the original Ops ticket and add to the To Do list)

https://contribute.data.humancellatlas.org/projects/detail?uuid=b7259878-436c-4274-bfff-ca76f4cb7892&tab=project - - The Operations ticket was marked as Done but Ami did not pushed the update to DCP (I will re-open the original Ops ticket and add to the To Do list)

Last in the list is Project https://contribute.data.humancellatlas.org/projects/detail?uuid=5bb1f67e-2ff0-4848-bbcf-17d133f0fd2d (UCSC) - I will add to the Operations Notes and decide course of action on this one. 

Closing the ticket as 3/4 are already covered in separate tickets (EBI) and the fourth we will define what to do today in Ops Review Meeting
