### ISSUE TITLE
PRJNA694128 - Co-evolution of tumor and immune cells during progression of multiple myeloma

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#492]
### Project short name: 
MultipleMyelomaCoevolution

### Secondary Wrangler:
@ipediez 

### Associated files

* Google Drive: https://drive.google.com/drive/folders/15YF3CExkNVKc0fh21vBKv2v0S5Ej6-bH

### Published study links

* Paper: https://doi.org/10.1038/s41467-021-22804-x

* Accessioned data: [PRJNA694128](https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA694128)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate
- [ ] Clean up files in cluster and cloud-delivery area

Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=2ad191cd-bd7a-409b-9bd1-e72b5e4cce81

**Comment by idazucchi** [comment]
I uploaded the metadata spreadsheet.
The graph validation is currently blocked by the missing fastq files [#516](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/516).
I contacted the authors again, since 2 weeks have passed from their last reply. The missing information I am trying to obtain is the sequencing platform for each sample, since the

**Comment by idazucchi** [comment]
Newly concatenated fastq files uploaded to ingest: **109/121 validated** 

#### Problem: Fastq files truncated
Fastq for 3 SRRun accession are invalid. Errors again about files being truncated or sequence and quality length not matching.

- **SRR13509448** --> puzzling as there fastq file was split in just one part, so files can only be truncated if something went wrong with bam-to-fastq conversion
- SRR13509424
- SRR13509453

I will investigate the issues

**Graph validation blocked**

**Comment by idazucchi** [comment]
**Graph validation unblocked** 
The graph validation returns no_orphans.adoc error. I think this is due to the sequencing_protocol_1 which isn't linked to anything while I wait for the authors reply.
Deleting the protocol is not possible from the ingest UI so @ESapenaVentura deleted it through the API. The error however is still present so I have to look into it

**Comment by idazucchi** [comment]
**no_orphans error**
Error due to the presence of unlinked supplementary file. 
Discussed with Wei and @ESapenaVentura and we agreed that supplementary files should be allowed to be unlinked and the test needs to be modified.
I made a [ticket](https://github.com/ebi-ait/ingest-graph-validator/issues/53) in the graph validator repo.

**Comment by idazucchi** [comment]
For some reason each fastq file was assigned to a different process ID, so the graph validator raised an error.
I modified the spreadsheet to manually assign process IDs so that the right fastqs are grouped together.

As soon as the graph validator changes are in production the no_orphan error should disappear and I will move the dataset to secondary review.

**Comment by idazucchi** [comment]
The authors confirmed that all the samples were processed with Illumina NovaSeq 6000

**Comment by ipediez** [comment]
A very complete submission, good job! Here you have some suggestions:

**Project** 
- Add INSDC study accession field: PRJNA694128

**Project - Contributors**
- Add Ravi Vij and Li Ding the corresponding author role at the corresponding contributor field, and mark the rest as "no". You could also add them as corresponding authors in ingest.

**Project - Publications**
- Make sure that all the authors are listed in the same line, as they are co-authors of the same publication "Co-evolution of tumor and immune cells during progression of multiple myeloma". This is Liu R|| Gao Q|| Foltz SM|| etc.

**Donor organism**
- Just a reminder that donor name (not ID) is a user-friendly field, and doesn't have to be necessarily programmatic. It's OK as it is, but you can write those fields without the underscore if you want.

Sequencing protocol
- Sequencing protocol name and description are missing

**Supplementary file:**
- Content description and ontology is missing. I would suggest going with Sample annotation (data:3113)

**Comment by idazucchi** [comment]
I've applied the changes and the project has been exported

**Comment by hlmfw** [comment]
The work is pretty good. I am a Phd candidate and hope to analyze some information in your data. However, [PRJNA694128] documents in the article are not available. Would you please give me a site to download all single cell data of the work. Thank you very much!
