### ISSUE TITLE
Schema update priority ticket - 2021-10-11

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#493]
**What are the next schema updates?**
Update number 1) Loading the barcode module for spatial_barcode fields: https://github.com/HumanCellAtlas/metadata-schema/issues/1407
Update number 2) Change sequence_file.read_index enum to include Read3/Read4: https://github.com/HumanCellAtlas/metadata-schema/issues/1401 

These changes will affect the following schemas:
- type/protocol/sequencing/library_preparation_protocol.json
- type/file/sequence_file.json

**Why are these changes needed?**
Update number 1)
This is needed as this is vital information for interpreting and analysing 10x visium and other imaging experiments. We have several datasets containing imaging data which are currently in stalled as they require this change: 
- https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/339
- https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/317
- https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/236

Update number 2)
Data needs to be accurately described for these two assays. This also is holding up submission of two datasets linked below:
GSE117498
GSE102580

**Type of change and time frame**
Update number 1 constitutes a minor change (adding optional fields)
Update number 2 constitutes a patch change (extending a controlled vocabulary enumeration) 

We are expecting to push both updates before 25th October 2021 (25/10/2021)

**Comment by ESapenaVentura** [comment]
@Wkt8 Merged 1 PR into staging - Other had conflicts. Fixed that issue, will check with @ESapenaVentura .

Once conflicts solved will merge into staging then prod
