### ISSUE TITLE
a9301beb-e9fa-42fe-b75c-84e8a460c733: "A human cell atlas of fetal gene expression" (New): enrique@ebi.ac.uk

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#502]

**Comment by yusra-haider** [comment]
@ESapenaVentura , I think you want to re-export this now? Please make sure to use the `export only metadata` option

**Comment by ESapenaVentura** [comment]
Done, hit export and filled out import form

**Comment by ESapenaVentura** [comment]
Looks fine in data browser, added release to project
