### ISSUE TITLE
e0c74c7a-20a4-4505-9cf1-38dcdd23011b: "GSE117211_KidneyMicroOrganoids" (New): ami@ebi.ac.uk

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#503]
Project: Kidney micro-organoids in suspension culture as a scalable source of human pluripotent stem cell-derived kidney cells

Short name: GSE117211_KidneyMicroOrganoids

**Comment by ami-day** [comment]
Latest update: no species and disease status https://data.humancellatlas.org/explore/projects/e0c74c7a-20a4-4505-9cf1-38dcdd23011b

**Comment by ami-day** [comment]
Added new collection protocol, cell line donors and cell line specimens and linked them to the input cell line. Re-graph validating.

**Comment by ami-day** [comment]
Re-submitted.

**Comment by ami-day** [comment]
Note: the "normal" ontology option is not displaying in the ingest browser when selecting the disease status. I was able to save "normal" but without an ontology label selection. This might mean that the disease status still does not get displayed in the data browser. Need to check this.

**Comment by ami-day** [comment]
Exporting.

**Comment by ofanobilbao** [comment]
@ami-day is this Done? Last comment says exporting but still in the In Progress

**Comment by ami-day** [comment]
I need to resubmit with the normal ontology label

**Comment by ami-day** [comment]
Graph validating

**Comment by ami-day** [comment]
This project is stuck in "graph validation requested" status.

**Comment by MightyAx** [comment]
graph valid

**Comment by ofanobilbao** [comment]
I identified that Ami never ended up pushing the update to this dataset after Alexie helped making it Graph valid. This should be ready for a wrangler to take and just hit the export I guess

**Comment by ofanobilbao** [comment]
From what I can see Wei already submitted the update and filled the Import form. Project shows up as exported already. Moving this to Done
