### ISSUE TITLE
Curation of Auto-Imports - #1

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#508]
**Projects to be curated**
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=27e2e0ae-5971-4927-aac1-19e81804097b
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=81962a88-9d10-493f-9d6c-a94275a0191d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=22ae032f-a09a-4f2f-9f01-fa404e12f7ff
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=aa46ead1-3ec9-4bab-9469-a257146b1dff
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1efa0f0e-148e-4621-adbf-df4e5473c145
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1e316bac-f03f-40e0-92a8-7d52d4d2affd
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2e56ff07-ab38-4ab8-b596-7d9a19bd34e9
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=d809163b-7894-4c8b-9ec2-ff916d74601c
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=f275df57-83a8-4c50-90c9-ae8755c4d929
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=54e835ce-7679-49ba-9bcb-206d6fc17dd2
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=fa532930-2347-40b5-9402-a36d312c2803
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1d7c6d48-1f7a-47cb-9dcf-4fd234084993
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=9d112eae-6ac4-4071-bdae-8eca6e99a20e
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2b641ced-dcae-4e63-b6d7-03b3b9260c3d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=9b9efe68-adbe-4638-92a0-b96f3a895e19
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=ccfa8caf-b5ea-42d3-ad69-3ed2f6ad9b6c
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2f58dba8-70cf-4499-aa8e-61eee087db94
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=dcef0b42-3ff1-4b04-ae0e-c0bac523edac
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=12925b5f-3704-443b-8ced-ce3f17bdd573
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=84f7f444-e561-4c86-9193-4d3b24c7ea40
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=9e7d7055-a771-4fb7-8868-b725ae13b8d1
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=22e3cd9b-6600-4c69-b1c2-ef8b42dd6219
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=09d0bc04-708c-4255-9d97-82cbac509b3b
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=ca0edd36-e56c-46ed-b247-1af69d49fe4e
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=00cdb1f5-1bde-405b-bc9d-c28766661da9
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=e28e1097-10f1-4c7d-a628-da1b7e90adc7
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=e22ecac5-7dfb-4002-bfbd-2fd04da395a4
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=b31097e6-fcf0-4154-81d9-582dcda9fbeb
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=0562d2ae-0b8a-459e-bbc0-6357108e5da9
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=ad3aab85-acf2-49e0-aae1-52365e0d5cb0
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=bfe3ebd3-75c6-438a-bc6a-40d948734f9d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2869e1b8-1944-4baf-b747-1c273593933b
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=046317a1-9933-49c4-a8a4-2e486ac35f82

**Tracking spreadsheet**
https://docs.google.com/spreadsheets/d/1ktD7Ld74HLJLA5Kl_Mn5ij4i1semiNkXMj6VgmQeLbI/edit#gid=625949729

**Acceptance criteria**
- [x] All projects have been curated according to the instructions in the [SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_acknowledgement_SOP.html#manual-curation-after-addition)
- [x] Projects show in the catalogue correctly

**Comment by ofanobilbao** [comment]
Enrique to start from the bottom and I'll start from the top

**Comment by ESapenaVentura** [comment]
https://contribute.data.humancellatlas.org/projects/detail?uuid=046317a1-9933-49c4-a8a4-2e486ac35f82 has an issue, I have put a comment in the spreadsheet. Was completely unable to find accession

**Comment by jacobwindsor** [comment]
@ofanobilbao done her half

**Comment by ESapenaVentura** [comment]
https://contribute.data.humancellatlas.org/projects/detail?uuid=e22ecac5-7dfb-4002-bfbd-2fd04da395a4 : Couldn't find 10x's specific version

**Comment by Wkt8** [comment]
@ESapenaVentura to do one last check and then to move to done.
