### ISSUE TITLE
Curation of Auto-Imports -#2

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#509]
**Projects to be curated**
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1eb673d2-6c82-4617-bd03-0092b06d300a
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=c65c16a9-912a-420f-98c9-dfe512f39ec8
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=266fcbe4-bfc7-409e-86a9-b6c0e4882a40
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=989140d5-96f4-4127-87d0-140c09c3448d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=b2727d7f-08ca-4b33-9057-c0565f8966cf
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a06b4918-f6a1-4e51-b25f-45b65bcc2549
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=89421d36-e179-4590-84fa-5941c193da5b
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=82c2b8cf-06f6-4528-94f6-97e4390342ce
- contacted authors to ask about data availability
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=ac4c3aee-6b5a-4de7-af22-4ad2a6573c89
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=791ebecf-ac09-45b9-82f0-b66ce48738e7
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=54eb9ae2-a853-4359-bb6f-49796e2f3061
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=0154988a-4463-4424-8358-8b0515444719
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=3ac80253-c282-42f7-84db-0ad547d3b767 - I deleted this project, it is a duplicate of the project above.
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1932afd8-5d54-48a2-9401-9a7fbfa8931d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=19c899e5-54de-4df1-b7d8-414728a2c461
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=4e6e55d7-3887-4d04-924d-bd85c6b0785c
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=28a9c545-5b90-4455-8ad7-6cbf026aa20b
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=207671be-5ea0-496f-92af-931ab7551b67
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=270c8d27-1f1c-442f-af58-de88b99456f6
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=9b0d2936-10c1-45b8-ab7b-3fd65963fb9c
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=15ba72cb-75f8-4654-9255-0cff02f15f1f
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=4a05a69a-d925-44cd-a43a-7a3583484f17
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a93847fe-db7c-4e54-8194-9e1c7b96cd13
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=77f9c54f-d9c0-4d7f-b204-88229e2458b5
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7b393e4d-65bc-4c03-b402-aae769299329
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=3179744a-5eff-4d5d-8de8-a51192327b95
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=334298f8-8173-46f2-8da6-c5b7821fe7d5
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=b8694375-c8de-4d85-83bd-c4843dcc581a
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=29132597-067f-4fcf-b0e9-6678b565d62f
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=dbf218cc-3523-4b74-9001-00ba3a8c832d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2d6a80c7-34b2-417e-9375-244b061540a0
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=78846cb1-bd7c-4822-bdcb-d5e3c55fbca6
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=ec36a215-2401-44e6-970d-6beead8e6aaa

**Tracking spreadsheet**
https://docs.google.com/spreadsheets/d/1ktD7Ld74HLJLA5Kl_Mn5ij4i1semiNkXMj6VgmQeLbI/edit#gid=1759117474

**Acceptance criteria**
- [ ] All projects have been curated according to the instructions in [SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_acknowledgement_SOP.html#manual-curation-after-addition)
- [ ] Projects show in the catalogue correctly

**Comment by ofanobilbao** [comment]
Irene will start from the bottom and Ami from the top

**Comment by prabh-t** [comment]
Irene will attempt to finish by Friday.

**Comment by jacobwindsor** [comment]
Irene completed her half. @ami-day do you have an update?

**Comment by ami-day** [comment]
Completed these. Just waiting to hear back from an author about data availability  for 1 of the projects, and for a dev to correct an error I get when saving metadata for 1 of the projects.

**Comment by ofanobilbao** [comment]
@ami-day I would probably add as much as you can for the remaining project. And add if it would be Eligible. And state Priority. In the Admin notes you could say that you could not find the data. And if at some point is prioritised then whoever takes it can try and go to the authors to try and find that out. I'd do that and close this ticket.

**Comment by ami-day** [comment]
We decided to mark the remaining project as ineligible, the authors never got back and there is no data available.
