### ISSUE TITLE
Curation of Auto-Imports - Ida

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#510]
**Projects to be curated**
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a8aaa1e5-a28e-4b51-861f-9811952e2169
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=bd308491-ffcb-41a9-95e6-84c8f834b8c2
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=3373e59c-525f-4a83-8c9c-d8b280454697
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=d3f54e41-d80a-4827-9f63-ddc6dd4fb8fa
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a08b4e90-1c5c-454c-90cd-78cba9cb7896
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=13a28aee-eec2-4dfd-bd08-0ba242c326fe
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a273ec92-a236-44f9-bc68-5d916c8ad27b check EGA not-eligible
- [x]  https://contribute.data.humancellatlas.org/projects/detail?uuid=390e9498-5831-40d0-aea5-fb5c837c9134
- [x]  https://contribute.data.humancellatlas.org/projects/detail?uuid=6d5d69a9-2263-4ecc-94f5-df1eda092cb1 preprint not in GEO yet
- [x]  https://contribute.data.humancellatlas.org/projects/detail?uuid=92892ab2-1334-4b1c-9761-14f5a73548ea
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=d6424aa7-a5b1-4c4c-a3d6-0fd1d820bb9b CNP0001218 not available yet
- [x]  https://contribute.data.humancellatlas.org/projects/detail?uuid=44d018c2-b7a2-4bfc-90af-e0d33568f66f
- [x]  https://contribute.data.humancellatlas.org/projects/detail?uuid=d064943a-96ab-48b1-8f6b-30f026b73df7
- [x]  https://contribute.data.humancellatlas.org/projects/detail?uuid=ba7ac133-15ab-4d8a-a52a-b3ee7a5353b6
- [x]  https://contribute.data.humancellatlas.org/projects/detail?uuid=80154136-ea5c-4023-b288-178fc4fa5235 managed access, no available matrices --> non eligible 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=3cd88693-08eb-423b-a1b6-abbdecc3d837
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=8b954fb2-bccb-44c5-84e3-9f91e9189c40
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2c633e94-954c-490f-a768-c74b83d28491
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a3b9b95c-89fd-46d7-aa9a-f6f01645800e HRA000086 not available yet
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=68b878fa-bfc6-449d-b33a-31fc99945360 managed access, no available matrices --> non eligible 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=012ac8b0-45e8-4876-99d7-e89526d0ddee
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1516c703-9a7a-4e7b-8683-e039760b1d23
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=573bdf43-6185-4966-a30f-9f3b25580be9
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=6c1ed269-3fdf-4142-9ffa-1d0004373698
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=15b267bf-848f-46b4-ae2b-748dcf466327
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=645904dc-6fc0-4129-bda3-5ac996041842
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=67e22df2-6189-44d0-909f-cce7b133d3b2
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7d6ce956-3590-4334-9160-7a59a1c161e5
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=3d79add7-6447-4a14-8127-be2736cc919b
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=0fe8f952-c73a-4f05-850c-c82272068768
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=445d3182-ab53-4ede-80bc-a6a4d43acfe0
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=41db1719-eb48-4c38-9b02-2ba789752131 managed access, no matrices available --> not eligible
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=572762a1-1ff6-4dc0-a118-f894c9bc4582

**Tracking spreadsheet**
https://docs.google.com/spreadsheets/d/1ktD7Ld74HLJLA5Kl_Mn5ij4i1semiNkXMj6VgmQeLbI/edit#gid=507130609

**Acceptance criteria**
- [x] All projects have been curated according to the instructions in the [SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_acknowledgement_SOP.html#manual-curation-after-addition)
- [x] Projects show in the catalogue correctly

**Comment by aaclan-ebi** [comment]
@idazucchi will focus on this next week.

**Comment by ipediez** [comment]
@idazucchi to continue today

**Comment by idazucchi** [comment]
####  Issues with the project catalogue
- [ ]  https://contribute.data.humancellatlas.org/projects/detail?uuid=67e22df2-6189-44d0-909f-cce7b133d3b2& not chowing ENA accession correctly

**Comment by ipediez** [comment]
@ESapenaVentura to take a look

**Comment by idazucchi** [comment]
Added the ENA secondary study accession, which is now showing up in the catalogue. The link points to the ENA project page.

**Comment by ESapenaVentura** [comment]
I took a look, the main problem is that the project catalogue is not displaying the accessions under `project.insdc_study_accessions`. As a workaround I added the ERP accession, but I think we should probably have a discussion about why is this happening
