### ISSUE TITLE
Curation of Auto-Imports - Oihane

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#511]
**Projects to be curated**
- https://contribute.data.humancellatlas.org/projects/detail?uuid=1eb69a39-b5b2-41ec-afae-5fe37f272756
- https://contribute.data.humancellatlas.org/projects/detail?uuid=3d7cb308-d4e5-4764-8751-d302f179ff9c
- https://contribute.data.humancellatlas.org/projects/detail?uuid=d2801b3a-ef64-428c-93dc-93b8be0cd236
- https://contribute.data.humancellatlas.org/projects/detail?uuid=e09ff95d-ed7a-4188-a583-9c8a66d94489
- https://contribute.data.humancellatlas.org/projects/detail?uuid=920b3f4f-f820-450c-bded-692b75688a97
- https://contribute.data.humancellatlas.org/projects/detail?uuid=03b9acf2-d401-4c37-b062-9649d1947c6d
- https://contribute.data.humancellatlas.org/projects/detail?uuid=e1e3ffb7-1dc6-4bf7-9f7a-5f0c50f07fe0
- https://contribute.data.humancellatlas.org/projects/detail?uuid=b834d9b9-59e9-4a1b-bb24-37dca1cd8f1d
- https://contribute.data.humancellatlas.org/projects/detail?uuid=f85ec856-82ac-4b0c-9109-5f767d46b7c8
- https://contribute.data.humancellatlas.org/projects/detail?uuid=f8dd9b7f-9fc2-4bcf-bdd9-913bdf59b14e
- https://contribute.data.humancellatlas.org/projects/detail?uuid=62d35577-2505-40f4-a731-e56958fb3d6a
- https://contribute.data.humancellatlas.org/projects/detail?uuid=fc3be91d-dc7c-4385-aa35-4975cae47f65
- https://contribute.data.humancellatlas.org/projects/detail?uuid=25c85683-4117-4416-8ae4-6757e96cd697
- https://contribute.data.humancellatlas.org/projects/detail?uuid=13bca115-700e-49b4-b01a-c6e01f03d226
- https://contribute.data.humancellatlas.org/projects/detail?uuid=4627f43e-a43f-44dd-8c4b-7efddb3f296d
- https://contribute.data.humancellatlas.org/projects/detail?uuid=026c42dc-3337-43c0-b60a-507752d3ced2
- https://contribute.data.humancellatlas.org/projects/detail?uuid=52a706b6-10cc-491d-bf5c-48aac17fbec6
- https://contribute.data.humancellatlas.org/projects/detail?uuid=325686dd-90fc-4f0d-a6dc-3cfc2922c77d
- https://contribute.data.humancellatlas.org/projects/detail?uuid=f3aa9a6d-fa8b-454f-877a-c8393cd625c6
- https://contribute.data.humancellatlas.org/projects/detail?uuid=c575cd60-fb3b-4b09-8516-6529450e1ab2
- https://contribute.data.humancellatlas.org/projects/detail?uuid=28af1923-a533-40c5-a82d-7d14325919ae
- https://contribute.data.humancellatlas.org/projects/detail?uuid=ae0b27dc-641b-4d9b-b0dc-390ac07c4a32
- https://contribute.data.humancellatlas.org/projects/detail?uuid=0ef6b834-7815-4ea6-a6b0-9423cc966255
- https://contribute.data.humancellatlas.org/projects/detail?uuid=54a7c18c-2b2e-42a8-b227-ca4f352a6479
- https://contribute.data.humancellatlas.org/projects/detail?uuid=9e31f3fe-c648-4624-9382-c7069817b9b8
- https://contribute.data.humancellatlas.org/projects/detail?uuid=56db04ed-c143-45b9-b812-e2e2d9c27050
- https://contribute.data.humancellatlas.org/projects/detail?uuid=24d0ccaf-82c1-4b08-9670-1cf4e40fa56a
- https://contribute.data.humancellatlas.org/projects/detail?uuid=974df02f-fc85-4773-bbc5-a772baad95ef
- https://contribute.data.humancellatlas.org/projects/detail?uuid=976c4054-70d5-4e46-a7e1-9c6d2621c5ce
- https://contribute.data.humancellatlas.org/projects/detail?uuid=9c27b4a6-cad4-4a37-b88f-6a3a66fe0844
- https://contribute.data.humancellatlas.org/projects/detail?uuid=88961093-700c-4581-a571-14ab4cfc92be
- https://contribute.data.humancellatlas.org/projects/detail?uuid=9f4d2195-ca25-4db9-90fc-134f0b757a25
- https://contribute.data.humancellatlas.org/projects/detail?uuid=2973a42c-f810-4812-9a23-5bbc9644588d

**Tracking spreadsheet**
https://docs.google.com/spreadsheets/d/1ktD7Ld74HLJLA5Kl_Mn5ij4i1semiNkXMj6VgmQeLbI/edit#gid=528808393

**Acceptance criteria**
- [x] All projects have been curated according to the instructions in #489
- [x] Projects show in the catalogue correctly

**Comment by ofanobilbao** [comment]
Even if it was not priority yet I wanted to try and do one before going on annual leave. Had issues after saving bypassing validation. I will report today

**Comment by ofanobilbao** [comment]
3/4 done

**Comment by ofanobilbao** [comment]
Finished with the task
