### ISSUE TITLE
HumanGumsNormalandDiseased (UCSC dataset) - Needs Update

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#514]
Slack conversation from UCSC wranglers:

"we want to make some changes to HumanGumsNormalandDiseased– would it be possible to revert it from complete status?

It’s part of this next release wasn’t sure if we just go about updating stuff the normal way or if because it hasn’t entered the rest of the dcp we can just revert.

Project UUID - 783c9952-a4ae-4106-a6ce-56f20ce27f88"

**Comment by yusra-haider** [comment]
@ESapenaVentura we can go ahead with the update, it should work okay now.

Please let me know when the submission occurs so I can keep an eye on the logs
