### ISSUE TITLE
Converting bam to fastq in bulk 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#516]
**Description of the task:**
As a wrangler I want to be able to download bam files and convert them into fastq files in bulk. We previously used the EC2 instance to do this, but have encountered a dataset with a large number of bam files (~500GB), 29 bam files, which may prove problematic for the EC2 due to its limited processing power. 

This is blocking https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/492
Files here: [here](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP302898&f=librarysource_s%3An%3Atranscriptomic%2520single%2520cell%3Ac&o=library_name_s%3Aa&s=SRR13509359,SRR13509362,SRR13509363,SRR13509367,SRR13509370,SRR13509372,SRR13509380,SRR13509381,SRR13509385,SRR13509389,SRR13509392,SRR13509395,SRR13509401,SRR13509405,SRR13509409,SRR13509411,SRR13509413,SRR13509414,SRR13509420,SRR13509424,SRR13509426,SRR13509430,SRR13509434,SRR13509439,SRR13509440,SRR13509448,SRR13509450,SRR13509453,SRR13509456) 

@aaclan-ebi mentioned that it might be a good idea to do this on the ebi cluster which will require dev support 

**Acceptance criteria for the task:**
- Able to download and store large number of bam files in bulk
- Able to run the bamtofastq script to generate read1, read2 and index1 files from the bam files
- Able to transfer those fastq files into a hca-util upload area

**Comment by amnonkhen** [comment]
@yusra-haider uploaded the files on Friday, will check status today.

**Comment by yusra-haider** [comment]
files uploaded to hca-util upload area with id 869ebec1-19bc-4549-8106-d13107415b79.

@idazucchi , please take a look and verify

**Comment by ESapenaVentura** [comment]
@idazucchi to review!

**Comment by idazucchi** [comment]
I uploaded the files in ingest. Ingest points out some errors about the files being truncated or the length of quality and sequence not matching. I wrote a new script to concatenate the fastq

**Comment by idazucchi** [comment]
The fastq have been concatenated and transferred to the hca-util area 4bfbef98-8699-4c0c-8519-8899d187b020

**Comment by ofanobilbao** [comment]
@idazucchi to reach out to a dev for help

**Comment by idazucchi** [comment]
Fastq for 3 SRRun accession are invalid. Errors again about files being truncated or sequence and quality length not matching.

- **SRR13509448** --> puzzling as there fastq file was split in just one part, so files can only be truncated if something went wrong with bam-to-fastq conversion
- SRR13509424
- SRR13509453

**Comment by ESapenaVentura** [comment]
@idazucchi to try manually converting the bams for the runs above

**Comment by idazucchi** [comment]
bam file download not done yet

**Comment by aaclan-ebi** [comment]
Some files may need to be converted again due to errors in the fastq files when uploaded to Ingest. @idazucchi tried yesterday but a file couldn't be downloaded to her machine. Need dev support from @jacobwindsor .

**Comment by idazucchi** [comment]
There are three files that need be converted from bam to fastq format following the [SOPs](https://ebi-ait.github.io/hca-ebi-wrangler-central/tools/handy_snippets.html#downloading-10x-files-from-archives) using the option `--reads-per-fastq=500000000`

**Where**
The files are in the cluster in the folder /nfs/production/hca/multiple_myeloma_immune_cells_coevolution/bam_files

**Which files**
SRR13509448/scRNA.unsorted.27522_Relapse_2.bam
SRR13509424/scRNA.unsorted.56203_Relapse_1.bam
SRR13509453/scRNA.unsorted.98433_Primary.bam

**Comment by jacobwindsor** [comment]
Running on screens `SRR13509448`, `SRR13509424`, and `SRR13509453`

**Comment by jacobwindsor** [comment]
I think there is some problems with these BAMs. These files have been outputted

- `SRR13509448/fastq/27522_4_MissingLibrary_1_HCWFWDSXX`
- `SRR13509424/fastq/56203_2_MissingLibrary_1_HCMCFDSXX`
- `SRR13509424/fastq/56203_2_MissingLibrary_1_HNVV5BBXX`
- `SRR13509453/fastq/98433_MissingLibrary_1_HNJJVBBXX`

**Comment by jacobwindsor** [comment]
Done! 

Files have been outputted into the same directories as the BAM file under the `fastq` subdirectory

**Comment by idazucchi** [comment]
Fastq correctly converted for:
 - SRR13509424
 - SRR13509453

##### 3rd time conversion SRR13509448
Attempting again the bam-to-fastq conversion for **SRR13509448**
The fastq files collectively occupy 174M which is suspicious, however bam-to-fastq didn't raise errors

**Comment by ESapenaVentura** [comment]
It is indeed very weird

I checked the metadata provided in the ENA run selector https://www.ebi.ac.uk/ena/browser/view/SRR13509448?show=reads

Comparing the MD5 provided in their metadata (Available if you select to show the column) and the md5 of the file in the cluster, it does not seem that this has to do with the file download.

If this happens again we'll need to investigate why the file is not being converted correctly

**Comment by idazucchi** [comment]
Conversion completed for SRR13509448!
The fastq now occupy 44GB so something definitely happened

**Comment by ESapenaVentura** [comment]
@idazucchi to test if fastq files 

Need a dev to delete old submission and then @idazucchi will re-upload the submission and the files @ke4

**Comment by idazucchi** [comment]
@aaclan-ebi said that if the hca-util area is synced to the ingest area a second time it will trigger file validation again. 

All fastq are ready to be transferred to the hca-util area but both me and @ke4 couldn't install pip3 which is necessary to install hca-util.

**Comment by idazucchi** [comment]
To use pip3 in the cluster we used conda environments.
All the files have been uploaded in ingest and passed validation!

**Comment by idazucchi** [comment]
To use pip3 in the cluster we used conda environments.
All the files have been uploaded in ingest and passed validation!
