### ISSUE TITLE
Check MRC projects for data

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#517]

**Comment by ofanobilbao** [comment]
@ESapenaVentura this is probably no longer relevant right? can I close?

**Comment by ofanobilbao** [comment]
@ESapenaVentura is this still required? If no answer I will close next week

**Comment by ESapenaVentura** [comment]
@gabsie are we still interested in specifically targetting MRC datasets?

**Comment by ofanobilbao** [comment]
Closing as it does not seem like we are targeting this right now
