### ISSUE TITLE
Projects in DCP not in catalogue

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#518]
**Description of the issue**
There are 38 projects in the the data portal that do not appear in the project catalogue. From these, 4 are not in ingest either, so they are probably datasets from lattice.

List of the 34 remaining projects:

- https://contribute.data.humancellatlas.org/projects/detail?uuid=8a40ff19-e614-4c50-b23b-5c9e1d546bab
- https://contribute.data.humancellatlas.org/projects/detail?uuid=403c3e76-6814-4a2d-a580-5dd5de38c7ff
- https://contribute.data.humancellatlas.org/projects/detail?uuid=d3446f0c-30f3-4a12-b7c3-6af877c7bb2d
- https://contribute.data.humancellatlas.org/projects/detail?uuid=7880637a-35a1-4047-b422-b5eac2a2a358
- https://contribute.data.humancellatlas.org/projects/detail?uuid=71436067-ac41-4ace-be1b-2fbcc2cb02fa
- https://contribute.data.humancellatlas.org/projects/detail?uuid=d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1
- https://contribute.data.humancellatlas.org/projects/detail?uuid=78b2406d-bff2-46fc-8b61-20690e602227
- https://contribute.data.humancellatlas.org/projects/detail?uuid=faeedcb0-e046-4be7-b1ad-80a3eeabb066
- https://contribute.data.humancellatlas.org/projects/detail?uuid=3e329187-a9c4-48ec-90e3-cc45f7c2311c
- https://contribute.data.humancellatlas.org/projects/detail?uuid=376a7f55-b876-4f60-9cf3-ed7bc83d5415
- https://contribute.data.humancellatlas.org/projects/detail?uuid=e77fed30-959d-4fad-bc15-a0a5a85c21d2
- https://contribute.data.humancellatlas.org/projects/detail?uuid=e526d91d-cf3a-44cb-80c5-fd7676b55a1d
- https://contribute.data.humancellatlas.org/projects/detail?uuid=414acced-eba0-440f-b721-befbc5642bef
- https://contribute.data.humancellatlas.org/projects/detail?uuid=3cfcdff5-dee1-4a7b-a591-c09c6e850b11
- https://contribute.data.humancellatlas.org/projects/detail?uuid=dbcd4b1d-31bd-4eb5-94e1-50e8706fa192
- https://contribute.data.humancellatlas.org/projects/detail?uuid=ad04c8e7-9b7d-4cce-b8e9-01e31da10b94
- https://contribute.data.humancellatlas.org/projects/detail?uuid=34cba5e9-ecb1-4d81-bf08-48987cd63073
- https://contribute.data.humancellatlas.org/projects/detail?uuid=b9484e4e-dc40-4e38-9b85-4cecf5b8c068
- https://contribute.data.humancellatlas.org/projects/detail?uuid=56e73ccb-7ae9-4fae-a738-acfb69936d7a
- https://contribute.data.humancellatlas.org/projects/detail?uuid=8dacb243-e918-4bd2-bb9a-aac6dc424161
- https://contribute.data.humancellatlas.org/projects/detail?uuid=da2747fa-2921-42e0-afd4-39ef57b2b88b
- https://contribute.data.humancellatlas.org/projects/detail?uuid=dd7f2436-0c56-4709-bd17-e526bba4cc15
- https://contribute.data.humancellatlas.org/projects/detail?uuid=8999b456-6fa6-438b-ab17-b62b1d8ec0c3
- https://contribute.data.humancellatlas.org/projects/detail?uuid=9bab0f03-a725-4a13-9ab1-196e46cd80ed
- https://contribute.data.humancellatlas.org/projects/detail?uuid=4af795f7-3e1d-4341-b867-4ac0982b9efd
- https://contribute.data.humancellatlas.org/projects/detail?uuid=79b13a2a-9ca1-42a4-97bd-70208a11bea6
- https://contribute.data.humancellatlas.org/projects/detail?uuid=20f37aaf-caa1-40e6-9123-be6ce8feb2d6
- https://contribute.data.humancellatlas.org/projects/detail?uuid=50151324-f3ed-4358-98af-ec352a940a61
- https://contribute.data.humancellatlas.org/projects/detail?uuid=504e0cee-1688-40fa-b936-361c4a831f87
- https://contribute.data.humancellatlas.org/projects/detail?uuid=3c27d2dd-b180-4b2b-bf05-e2e418393fd1
- https://contribute.data.humancellatlas.org/projects/detail?uuid=a80a63f2-e223-4890-81b0-415855b89abc
- https://contribute.data.humancellatlas.org/projects/detail?uuid=602628d7-c038-48a8-aa97-ffbb2cb44c9d
- https://contribute.data.humancellatlas.org/projects/detail?uuid=65858543-530d-48a6-a670-f972b34dfe10
- https://contribute.data.humancellatlas.org/projects/detail?uuid=8d566d35-d8d3-4975-a351-be5e25e9b2ea

**Acceptance criteria**
- [ ] Identify which of the 34 projects in the DCP are duplicated in ingest
- [ ] Delete the duplicates
- [ ] Set the `isIncatalogue` flag to true for the submitted projects and curate the project description

**Comment by ofanobilbao** [comment]
I believe we already covered this through other tickets at least with regards to the Projects that are in DCP, and were submitted by EBI. So I will close this ticket. We probably still need some clean-up on the UCSC front.
