### ISSUE TITLE
Script to fill 'File name' at wrangling spreadsheet

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#533]
There's a new script that can fill for you the File name column at the 'Sequence file' tab if you have already filled the INSDC experiment accesion ID at the 'Cell suspension' tab. This is particularly useful for spreadsheets generated with the tool geo_to_hca, and a lot of files from different technologies. It requieres to download a report in JSON format from ENA, including the list of available files and their matching to different identifiers. 

It would be great if someone with knowlege of the ENA API could add a function to directly donwload the JSON report by just specifying the Project ID. 

@ipediez has created a [PR #532](https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/532) including the new script to the src folder at hca-ebi-wrangler-central and updating the dataset_wrangling_SOP to include information about this script in the 'Filling in metadata about the files' section. 

**Acceptance criteria for the task:**

- The PR is reviewed and accepted

**Comment by amnonkhen** [comment]
waiting for PR review

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to work on this today - tag @ipediez when finished

**Comment by ofanobilbao** [comment]
Irene working on this

**Comment by ofanobilbao** [comment]
Needs reviewing by @ESapenaVentura again
