### ISSUE TITLE
lungFibrosisProteinSignatures

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#538]
### Associated files

* Google Drive: https://drive.google.com/drive/folders/1WFzOjfExCwj3ODzln_iSz5D611mL9YlQ

### Published study links

* Paper: [Needs registering for sneak peak](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3538700&download=yes)

* Accessioned data: [Matrix associated with paper from Munich Cohort](https://github.com/theislab/2020_Mayr)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [x] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Drop-seq paper, only has Munich Cohort - but took data from two other papers (Nashville and Chicago) for integration

**Comment by Wkt8** [comment]
Ready for secondary review - see brokering drive google link!

**Comment by ipediez** [comment]
Hello! I've read the pre-print and gone through the data available at GitHub. I have a few comments that I think can improve the metadata, but feel free to discuss any of them!

**Cell suspension**
- As cell size is selected, maybe we could add it to the 'cell size' column as a range with μm as the 'cell size unit' ("micrometer", UO:0000017). Nevertheless, we don't know the bottom range, so maybe adding a 0-40 μm range is not correct. In this case, leave it blank as it is. 

**Library preparation protocol**
- This is completely optional, but as I see you added the DOI for other protocols it might be worth adding protocol DOI for the original pipeline ( https://doi.org/10.1016/j.cell.2015.05.002 ) and the modifications (https://doi.org/10.1038/s41467-019-08831-9, https://doi.org/10.1101/705244)
- Primer is missing. I see that in the [assay spreadsheet](https://docs.google.com/spreadsheets/d/1H9i1BK-VOXtMgGVv8LJZZZ9rbTG4XCQTBRxErdqMvWk/edit#gid=0) it is also missing. Shouldn't it be polydT? 

**Analysis protocol**
- The 'processed matrix generation' ontology actually includes normalization, so I would add to the description of this protocol "Expression matrices were normalized using scran’s normalization based on size factors which are calculated and used to scale the counts in each cell." and delete it from the 'analysis of matrices' protocol and change "SF (size factor)" at data normalization from one protocol to the other

**Comment by Wkt8** [comment]
Thank you! I've taken on board your suggestions for library preparation protocol and analysis protocol.

- Have added the doi for the original pipeline
- Have added the primer as poly-dT
- Have moved the normalization of expression matrices and the 'SF (size factor' from the data normalization fields

I have not added 0 - 40um as the cell size because I'm not sure it adds as much, given that the information is already there in the enrichment protocol.

**Comment by Wkt8** [comment]
@ESapenaVentura https://contribute.data.humancellatlas.org/submissions/detail?uuid=9f243640-a7ad-41d9-bfce-712d8794ebda&project=2f676143-80c2-4bc6-b7b4-2613fe0fadf0 

https://drive.google.com/drive/folders/1WFzOjfExCwj3ODzln_iSz5D611mL9YlQ

**Comment by ESapenaVentura** [comment]
Finished the review! Overall LGTM, just a couple of comments/corrections:

## Project main page
- Added PXD urls to the accessions in the supplementary links
Project - Publications
- Deleted `.` at the end of last contributor

## Project - Funders
- Replaced all `-` in grant ids for “unspecified”

## Admin area
- Added Irene as secondary wrangler 
- Added wrangling priority (1)
- Added release number

## Donor organism
- Could we try to keep the age out of the description? This is related to the work we’ve done with k-anonymity, since we already have it in another field, let’s try to keep it outside
- Related to the description as well, for the control donors, please take out the “Donor” part at the end
- Please delete the `nan` values in smoking history


## Collection protocol
- I think the ILD_tissue_collection protocol is missing `surgery` at the end

## Specimen from organism
- Maybe use the Storage method field instead of the preservation method? filling the storage time and then filling the preservation method feels a bit off


## Library preparation protocol
- Please add `PhiX` as the spike-in retail name and 5% in spike-in dilution

## Analysis file
- Please add the File source (Publication)

**Comment by ofanobilbao** [comment]
@ESapenaVentura to apply corrections and submit dataset

**Comment by ESapenaVentura** [comment]
Done and exported - Filled the import form as well

**Comment by Wkt8** [comment]
Project is in the data portal here: https://data.humancellatlas.org/explore/projects/2f676143-80c2-4bc6-b7b4-2613fe0fadf0
But Cell Count Estimate does not show the cell count estimate at project / analysis-file level which was 41,888

**Comment by Wkt8** [comment]
Project cell count amd matrix-cell count is not showing yet in data portal. Cell count is obtained by summing biomaterials at the cell suspension level.
