### ISSUE TITLE
GSE121611,GSE122960 - pulmonaryFibrosisPathobiology

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#539]
### Project short name:
pulmonaryFibrosisPathobiology
### Primary Wrangler:
@ESapenaVentura 
### Secondary Wrangler:
@idazucchi 

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1YgokNPGtmo0bslk_1JCun6EmQfzuCEP8

### Published study links

* Paper: https://doi.org/10.1164/rccm.201712-2410OC

* Accessioned data: 
   * [GSE121611](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE121611)
   * [GSE122960](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE122960)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by aaclan-ebi** [comment]
@ESapenaVentura worked on curating the spreadsheet.

**Comment by ke4** [comment]
@ESapenaVentura almost ready with this dataset. Probably will goes to secondary review today.

**Comment by ESapenaVentura** [comment]
Ready for secondary review, ingest submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=c5051364-f177-444c-bcc0-1cc2bd594296&project=daf9d982-7ce6-43f6-ab51-272577290606

**Comment by Wkt8** [comment]
Assigning self for secondary review

**Comment by idazucchi** [comment]
Hello, I've finished the review! I have a few notes/questions:

### Donor organism
- the IDs match with the publication but not with GEO, which is more useful? Genuine question I don't have an answer
- Donor PM_ILD: the authors refer to her disease both as polymyositis and myositis, is polymyositis an umbrella term?

### Specimen
A few fields are missing:
- Donor organism ID
- Collection process ID
- BioSamples accessions
- SRA accession missing for mice (non-existent for humans)

The known diseases field is different from donor known disease for:
   - SSc_ILD_1_specimen
   - SSc_ILD_2_specimen
   - PM_ILD_specimen

### Cell suspension
- Cell viability:  you could fill out those fields, from the methods section 

> cell viability exceeded 80% as determined by AO/PI reagent staining

- Cell size: is it worth specifying that it is  <40micron ?


### Collection
- The collection method ontology ID and label are missing

### Dissociation
- There is a mechanical dissociation step (cutting with scissors) that you included in the enzymatic dissociation. Is it worth separating them?
- The enzymatic dissociation described is form mice, maybe two different protocols for human and mice are needed. I think that the information in GEO for the human dataset are misleading in that sense

### Library prep
- I didn’t see library pre-amplification or cDNA library amplification mentioned in the paper. Is it implicitly part of the library preparation?

### Data
As we said the files are not in ingest, this is just here as a reminder.

**Comment by ofanobilbao** [comment]
@idazucchi finished with the secondary review

**Comment by ESapenaVentura** [comment]
Hi Ida! About the review:
## Donor organism
- Donor ID: It doesn't really matter that much, it may help some people but at the same time an ID is just a unique identifier in our system, does not really need to match up to anything. About your question that they don't match in GEO, in GEO you usually see samples (which may not be the same as donors), so I tend to go with the paper metadata for donors.
- About the PM_ILD donor, I have researched it and polymyositis is a subset of myositis (So myositis would be the umbrella term), where have you read that it has both? (I took the info from the tables)

## Specimen from organism
- About the missing links: Oh no, I don't know how I skipped that haha adding it now
- About the accessions: I usually only add the accessions in the cell suspension, which usually resembles better the "sample" (Which is what is usually archived), I'll check the cell suspensions and add them if missing
- The disease field is different because I try to add only the diseases that may affect the tissue, but in this case maybe the disease is affecting the tissue sample too, so I'll add it

## Collection protocol
- I don't know how I missed this, great catch!

## Dissociation
- Yeah, I took the decision to not split it, because then I would need 3 protocols to describe it and they describe that part of the protocol as `...followed by gentle teasing using forceps into small (1-2 mm)...`. To me it seems that they kind of poked at it and moved around rather than dissociating by force
- About the different protocols, I could only find the description of the protocol in the GEO accession. Did you find it somewhere else?

## Library prep
- Yeah, 10x has a standard library amplification part (https://www.salk.edu/wp-content/uploads/2017/11/10XUserGuide.pdf, protocol step 2). I have to say that I don't always remember to put it, tbh!

## Supplementary materials
- I will link the portal via a [different spreadsheet](https://docs.google.com/spreadsheets/d/1XyDA1-4XfmJGvL4qzlkd_FZGfjNxrphVHwYwlmDWCD0/edit#gid=0), we need to do this for portals (Not yet a standard procedure, that's why it's not stated anywhere) 

Thanks for the review @idazucchi ! Let me know if you have any additional concerns :)

**Comment by idazucchi** [comment]
Sorry to reply so late, I hadn't noticed your comment!

### Donor organism
- PM_ILD (polymyositis) appears as Myositis_ILD_01 in GEO and in Table 1 of the Methods section as Myositis.
 I didn't know which one was the umbrella term but I thought you knew and had already figured it out

![Screenshot 2021-12-02 at 17.14.44.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/2eefcbf5-7268-4fa3-9847-b0a9c8a234d3)

### Specimen from organism
Interesting about the BioSamples accessions and known disease field, I will keep it in mind when I'm wrangling

### Dissociation
The information about the dissociation protocol for the human lungs is in the [supplementary material](https://thoracic-prod-cdn.literatumonline.com/journals/content/ajrccm/2019/ajrccm.2019.199.issue-12/rccm.201712-2410oc/20191230/suppl/reyfman_data_supplement.pdf?b92b4ad1b4f274c70877518510abb28b4b52684e04957b0ffa32428805db72bf1ae006baafd3547213af4e27a9ab55be6f5fc777ab96e15781ad06e2d51bc8850eec0c01f1f318ea45d60f96b528f17fa04a1080eec676ef261c9ced62886f94373968ca95181a3107ab57b9064a051dc4e4c139a171ddb9a1db306ced50e779ea07afab69886dc320569053e36c3c816bc0ecdd17ad1cd20fb71f033e1489040064281e), which on the other hand doesn't specify the mice dissociation protocol

**Comment by ESapenaVentura** [comment]
I have added the project uuid in the [analysis portal spreadsheet](https://docs.google.com/spreadsheets/d/1XyDA1-4XfmJGvL4qzlkd_FZGfjNxrphVHwYwlmDWCD0/edit#gid=0)

Other than that, I have checked:
- Matrices
- Disease info
- Cell count (project-level estimated cell count still not implemented)
- fastq files

And it looks fine!

**Comment by ESapenaVentura** [comment]
Updated the term and filled the import form

**Comment by ESapenaVentura** [comment]
Updated the missing term, updated project to 17.0.0, and filled out import form
