### ISSUE TITLE
Respond to emails about new HCA publications

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#54]
# Respond to emails about new HCA publications

There have been two new emails to wrangler-team about new publications to be added to the HCA publication list this week

"Cross-talk between the airway epithelium and activated immune cells defines severity in COVID-19 "
"Myocyte Specific Upregulation of ACE2 in"

These datasets should be listed in the dataset tracking sheet

We should figure out how these datasets look against our suitability criteria, noting their presence on the HCA publication list is a strong prior on acceptance

We should reach out to the authors to initiate the wrangling of this data (if they are based inside the timezones we are responsible for)

We should consider how to record the process for this in the wrangling/operations SOP

## Acceptance criteria
- [x] Datasets are listed in the data tracking sheet https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0
- [x] Both Datasets compared to our suitability criteria
- [ ] Email sent to the authors of "Cross-talk between the airway epithelium and activated immune cells defines severity in COVID-19" about how to submit (if appropriate)
- [x] Email sent to authors of "Myocyte Specific Upregulation of ACE2 in" about how to submit (if appropriate)

**Comment by lauraclarke** [comment]
@ESapenaVentura @ami-day who is going to send these emails?

Do you have a plan?

**Comment by ami-day** [comment]
Update: assessed suitability of Myocyte dataset and wrote draft email. Waiting for feedback on these kinds of emails.

**Comment by ami-day** [comment]
Update: 
We can't currently work with the following dataset: "Cross-talk between the airway epithelium and activated immune cells defines severity in COVID-19" - Roland Eils
Statement in the  publication: "Due to potential risk of de-identification of pseudonymized RNA sequencing data the raw data will be available under controlled access in the EGA repository upon journal acceptance."

Therefore I did not send an email.

**Comment by ami-day** [comment]
Update:
Sent an email to Nathan asking about data consent for this publication:
""Myocyte Specific Upregulation of ACE2 in..."

**Comment by lauraclarke** [comment]
Thanks, is the Roland Eils one listed as managed access in the data tracker?

**Comment by lauraclarke** [comment]
In fact, are both of these listed in the data tracker?

**Comment by ami-day** [comment]
They weren't by I have just added them and included the note about managed access for the Roland Eils dataset.

**Comment by ami-day** [comment]
Closing this ticket since it is complete.
