### ISSUE TITLE
EGAS00001004082 - healthyAirwaysAtlas

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#540]
### Project short name:

healthyAirwaysAtlas

### Primary Wrangler:

Irene Perez Diez

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1p_x2VznKkUlhpqMIImjLUJ4aCxpl01d3

https://www.genomique.eu/cellbrowser/HCA/

### Published study links

* Paper: https://www.atsjournals.org/doi/10.1164/rccm.201911-2199OC

* Accessioned data: [EGAS00001004082](https://ega-archive.org/studies/EGAS00001004082)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Unable to obtain pdf of the publication / we don't have access to it at the moment.

**Comment by gabsie** [comment]
@ipediez started work on this one as well.

**Comment by ESapenaVentura** [comment]
@ESapenaVentura assigned as secondary wrangler

**Comment by ESapenaVentura** [comment]
I have reviewed the dataset and applied the following corrections:
## Project
- Description: I have corrected the HTML tags
- I have removed the UCSC cell browser link, we need to report it somewhere else so it appears as an analysis portal. Once this is exported talk to me and we can sort it out!

## Dissociation protocol
- Corrected protocols.io DOI with DOI (Before it was a URL)

##Sequencing protocol
- I have split the protocols into Illumina NextSeq 500 and 550

## Analysis file
- I have linked all the missing protocols (Library prep, sequencing)
- I have corrected file format (.tsv.gz —> tsv.gz)
- I have added file source (Publication)

The new version can be found in the drive folder, an excel file with the suffix `ESV_review`

Other than the corrections I did, LGTM! I think it's ready for submission

Let me know if you have any query!
