### ISSUE TITLE
Document undocumented wrangling choices

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#541]
**Description of the issue**

Due to the length of the project, and the many people coming and going, there are "unspoken rules/best practices" for wrangling that have been kept undocumented and may re-surface as problems when they are not being followed

For this purpose, we are writing guidelines on best practices.

**Acceptance criteria**
- [x] A dump of all best practices is done before christmas
- [x] Wranglers meet to coordinate on outcomes
- [x] Decisions are written in a SOP

**Comment by ESapenaVentura** [comment]
The dump is ready - I had a meeting with the UCSC wranglers yesterday

AI - Enrique to check all the UCSC guidelines and we'll work on the document offline

**Comment by gabsie** [comment]
review and tidy up the doc and go through it at next wrangler catchup.

**Comment by idazucchi** [comment]
@ESapenaVentura will work on this today

**Comment by aaclan-ebi** [comment]
@ESapenaVentura and Paris prepping the doc for review for the next wrangler call.

**Comment by ipediez** [comment]
Waiting on Paris input

**Comment by ipediez** [comment]
https://docs.google.com/document/d/1xZOyAg35iDqJYga9UZOYMD1tSllFPuL8BOvuQcKBFK4/edit

**Comment by MightyAx** [comment]
For review by all wranglers

**Comment by ESapenaVentura** [comment]
@idazucchi @ipediez @ESapenaVentura @Wkt8 @ami-day to review

**Comment by ESapenaVentura** [comment]
Reviewed

Also document is not the one stated above, it's this one https://docs.google.com/document/d/1mz5HJ9-Irr9NOHMNZYV5xt5fwsasdULO2rrllwfFyN4/edit#

**Comment by aaclan-ebi** [comment]
Review is due this thursday before wrangler meeting on fri

@ami-day to review this

**Comment by Wkt8** [comment]
Has been reviewed - we should add this to (https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/SOPs.html) once we confer with UCSC

**Comment by Wkt8** [comment]
Consensus from UCSC call and Stanford call was to add it separately to our individual repos... but I'm not sure that's the best way forwards as the copies will get out of sync with each other.

**Comment by Wkt8** [comment]
@Wkt8 to add to our SOPs

**Comment by ESapenaVentura** [comment]
https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/942

**Comment by Wkt8** [comment]
Enrique reviewed and happy to merge.

**Comment by ESapenaVentura** [comment]
Merged
