### ISSUE TITLE
Wrangle urgent project SCEA - PulmonaryFibrosis

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#542]
**Description of the issue**
Wrangle this dataset to SCEA https://app.zenhub.com/workspaces/brokering-to-scea-60af47517f6e370017b3d5bf/issues/ebi-ait/hca-ebi-wrangler-central/87

Was partially wrangled to SCEA before, got stopped for a metadata issue.

More or less urgent

**Acceptance criteria**
- [ ] Dataset has been uploaded to SCEA's GitLab
- [ ] Dataset is approved and merged into SCEA

**Comment by amnonkhen** [comment]
@ami-day to investigate today

**Comment by gabsie** [comment]
@ami-day - if you need to chat to @ESapenaVentura about this, but first take a look at the dev bug ticket.

**Comment by yusra-haider** [comment]
@ESapenaVentura is working on this and it should get done soon
