### ISSUE TITLE
standardisation of ontology choices

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#546]
**Description of the task:**

There's no centralized documentation about what ontology terms we are using in each type of file content, analysis, or process. It would be great to have a table where we can look up this information, include new entries, and include discrepancies as comments, so we can have a discussion and agree on a standardised way of doing the annotation. 

A discussion between @ESapenaVentura and @ipediez took place about the content of the different types of matrices and what ontology term should they be mapped to, realising that maybe we need a deeper knowledge on the differences between the matrices and change the ontology terms we've been using, or even add new ontology terms. 

Notes and things to discuss: https://docs.google.com/document/d/1YlQf7iVcm16tP3JWBNQxQVZeOEbSk_MTniql-rMjJE8/edit?pli=1#

Spreadhseet with term proposals. Please **add any file/analysis that might be missing and any coment you think is useful**: https://docs.google.com/spreadsheets/d/1X-lDkdykICWsCXEBYov4-FiwSdzR6czxN4uVk8RA9gg/edit?pli=1#gid=0

- [ ] Create a centralised database with the ontology terms we are using
- [ ] Create a database including the different types of matrices and files
- [ ] Propose ontology terms for the different types of matrices and files, and have a discussion about them

**Acceptance criteria for the task:**

- [ ] There's an ontology term database agreed by the wranglers

**Comment by ipediez** [comment]
Spreadsheet proposal: https://docs.google.com/spreadsheets/d/1X-lDkdykICWsCXEBYov4-FiwSdzR6czxN4uVk8RA9gg/edit?usp=sharing

**Comment by ipediez** [comment]
It would might be worth to check the work started by Marion on Zooma, it should be under the /src folder related with harvesting ontologies

**Comment by ESapenaVentura** [comment]
@ipediez and @ESapenaVentura had a meeting yesterday for reporting this, waiting on @tburdett 's feedback

**Comment by ke4** [comment]
@ipediez would like other wranglers to review this issue.

**Comment by prabh-t** [comment]
Irene - waiting for input from UCSC.

**Comment by Wkt8** [comment]
Work here is to check with UCSC

**Comment by ipediez** [comment]
Created an issue with the ontology team (https://github.com/HumanCellAtlas/ontology/issues/97) asking about their thoughts on the cell barcode files
