### ISSUE TITLE
Rui-chen retina dataset - Lattice import

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#548]
**Description of the issue**
Similar to lavaert dataset (#446), Lattice wants to update a dataset. 

This dataset needs a deletion and a re-upload, as it includes deletion of subgraphs

More details on the subgaph structure [here](https://docs.google.com/drawings/d/1ZppCC7FswX4mFQKZqmr9RHecPOjTI7dbWJiw33G8014/edit)

**Acceptance criteria**
- [x] The dataset has been discussed at the demo
- [ ] Action items from comment below have been completed

**Comment by ofanobilbao** [comment]
@ESapenaVentura will raise this in the DCP demo

**Comment by ESapenaVentura** [comment]
AI
- Ask for deletion to Andrew (Data import team)
- Ask Lattice to re-export to their staging area WITH THE SAME PROJECT UUID
- Ask Lattice to fill an import form

**Comment by ofanobilbao** [comment]
@ESapenaVentura to reach out to Jason so that Lattice can import their version of the project

**Comment by ESapenaVentura** [comment]
Jason has confirmed they have sent a request to import their version of the project
