### ISSUE TITLE
Continue conversation with HUTER 

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#549]
**Description of the issue**
Around Jan this year, we started a conversation with HUTER about their submission to the HCA DCP. Since then, we have not maintained a conversation, but there was an H2020 meeting recently and we were informed they are closer to being ready for submission.

In order to make the submission process faster and easier, we need to continue with the conversation and gather the requirements they need.

**Acceptance criteria**
- [x] @ESapenaVentura to speak with @tburdett about the meeting
- [x] @ESapenaVentura to send an email to HUTER following the conversation that happened early this year

**Comment by ipediez** [comment]
@ESapenaVentura to have a meeting with @gabsie and @tburdett

**Comment by prabh-t** [comment]
Meeting scheduled for next week.

**Comment by ESapenaVentura** [comment]
Meeting scheduled for today - Will update later

**Comment by gabsie** [comment]
Had the meeting, followed up with Tony as well. To place a reminder (Gabs) to check in with the group in a few months.
