### ISSUE TITLE
Prepare proposal for supporting managed access submissions from Sanger

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#55]
Meeting is Thursday 18th of June, we need to have a proposal of some kind for Paul.

In the short term 'we' refers to EBI not the DCP, as the DCP will not be compliant for managed access in the timeframes that a lot of the contributors require. Best way we can add value is to make enhanced metadata available via Biosamples, Biostudies and anonymised expression matrices via AE or DCP2? Will DCP2 accept metadata/anonymised expression matrices only?
Realistically, how can we assist and add value to the current direct submission processes? This, I think, is what we should be proposing in the meeting.

My (Claire) best take on this is that we need to research from the EBI side 'all' current submission processes to EGA. I think this is, but I am not fully clear:
1. data and metadata via Sanger Datahose
2. data direct to EGA (via secure encrypted file upload), metadata via webin
3. data direct to EGA (via secure encrypted file upload), metadata via webin and metadata and matrices via AE (or not).

How do we confirm 1-3?
How do we work out where and how we can support providing enhanced metadata?

**Comment by mshadbolt** [comment]
Started initial brain dump in this doc https://docs.google.com/document/d/1kIyh1NOc8HamEilydLKNgw555A0rIh32Cn5abV1_uPA/edit#

currently very rough and will refine more as I go

had a short brainstorming meeting with Mallory which helped bring forward a few ideas

scheduled a meeting with isuru on monday to find out a bit more about biosamples and phenopackets

**Comment by mshadbolt** [comment]
Based on meeting today it seems like there will only be public metadata which means all metadata will go to biosamples. Closing for now
