### ISSUE TITLE
Update data file for DCP2 MVP dataset (83f5188e-3bf7-4956-9544-cea4f8997756)

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#550]
**Description of the issue**

Related to dataset https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/109 and the conversation carried in https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1636400461045700 

### Summary of the issue
- One file is displaying as gzipped (`28284_1#34.cram-2.fastq.gz`)
- When using the command file | grep -q compressed it doesn't show as compressed
- Decompressing and compressing again does the trick

### Desired outcome
- The file is corrected
- The file is updated in the staging area
- The file is sent as an update to a data file

### Useful info 
- Name of the file: `28284_1#34.cram-2.fastq`
- How to find upload area: `hca-util list -b | grep "bk-mfreeberg-james-colon-0"`
- Ingest submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=52e21998-8500-46db-8f22-ea6b1eaf67c0&project=83f5188e-3bf7-4956-9544-cea4f8997756

**Acceptance criteria**

- [ ] The file is corrected
- [ ] The file is uploaded following the [dcp2 procedures](https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_system_design.rst#update-a-data-file)
- [ ] The update is scheduled for next release

**Comment by ipediez** [comment]
They won't process this file, as it blocks the pipelines. @gabsie will suggest the team to bypass this to fix the file

**Comment by ofanobilbao** [comment]
@ESapenaVentura is this ticket still required? With the pipelines not there anymore ... does that change anything?

**Comment by ESapenaVentura** [comment]
Since we're not processing the data anymore, no, this ticket is not needed

**Comment by ofanobilbao** [comment]
Closing as per Enrique's comment. No longer required as this was a requirement for the pipelines
