### ISSUE TITLE
Duplicate projects in ingest 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#551]
**Description of the task:**
https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1636481936082700 

There are duplicate projects in ingest:
A single-cell atlas of the healthy breast tissues reveals clinically relevant clusters of breast epithelial cells / Single cell atlas of the healthy breast
- https://data.humancellatlas.org/explore/projects/a004b150-1c36-4af6-9bbd-070c06dbc17d
- https://data.humancellatlas.org/explore/projects/9bab0f03-a725-4a13-9ab1-196e46cd80ed

Single-cell analysis of Crohn’s disease lesions identifies a pathogenic cellular module associated with resistance to anti-TNF therapy.
- https://data.humancellatlas.org/explore/projects/504e0cee-1688-40fa-b936-361c4a831f87
- https://data.humancellatlas.org/explore/projects/992aad5e-7fab-46d9-a47d-df715e8cfd24

- [x] Where have the datasets come from?
- [x] which ones are more up-to-date?
- [x] why were the datasets duplicated?
- [x] Next steps to fix??

**Acceptance criteria for the task:**
- Preliminary Investigation is complete and we have clear steps and responsibilities for next steps to fix the duplicate projects 
- Have clear steps for documenting / meeting on how to prevent this on happening again

**Comment by ESapenaVentura** [comment]
@Wkt8 took a look, will get an answer by noon about UCSC/EBI wrangled dataset

**Comment by Wkt8** [comment]
For the Single cell atlas of the healthy breast, the two projects are from Lattice and UCSC. Going by the seed-network funding rules, we should remove the one curated by Tiana Pereira.  

- [ ] Remove https://data.humancellatlas.org/explore/projects/9bab0f03-a725-4a13-9ab1-196e46cd80ed

For the Crohn's disease lesions EBI/UCSC dataset, there are some missing metadata from both sides. However, the UCSC dataset is more up-to-date, and includes analysis_file and analysis_protocol as it was exported after we made those metadata changes. Should delete the EBI dataset.

- [ ] delete https://data.humancellatlas.org/explore/projects/992aad5e-7fab-46d9-a47d-df715e8cfd24

Have added this to the agenda for the ucsc-stanford catchup. There's two issues, one of which is checking for seed network funding, the other which is ensuring that EBI and UCCSC dont wrangle the same datasets which is already in place due to the changes in using ingest as our back-office. 

These were duplicated because of the lack of QC and checking for seed-network funding, checking in the browser, and lack of a shared wrangling list between UCSC and EBI - but now we have one.

**Comment by gabsie** [comment]
@gabsie to send the email request to Dave, to arrange the redirects. Then inform @ESapenaVentura to go on with soft deletion request.

**Comment by gabsie** [comment]
I have now requested the redirect arrangement, waiting for go-ahead by Dave & Trevor

**Comment by ofanobilbao** [comment]
When re-direction is confirmed we can move this ticket to done.

**Comment by ESapenaVentura** [comment]
Dave has confirmed this will be re-directed.
