### ISSUE TITLE
Investigate issue with dataset c893cb57-5c9f-4f26-9312-21b85be84313

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#554]
**Description of the issue**
As described [here](https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1636989524104300), analysis of the files from dataset [220](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/220) has brought up an issue with the R1 files.

I need to investigate if the length is correct and, if not, devise the actions needed to correct this.

**Acceptance criteria**
- [x] The reason the R1 files are longer than 26 bp is determined
- [ ] A set of actions is determined from the research

**Comment by aaclan-ebi** [comment]
The issue is brought about by pipelines. There were read files that weren't trimmed.

**Comment by ESapenaVentura** [comment]
Pipelines will omit analysis for these files

**Comment by ESapenaVentura** [comment]
R1 files are showing an abnormal size because the data was not trimmed.

For now, the problem is solved for the pipelines. This is something we'll need to address for the Update release, scheduled probably after christmas.

**Comment by Wkt8** [comment]
We are not going to modify contributor-offered fastq files. This data is not 'incorrect', it just has not been processed in a certain method.
