### ISSUE TITLE
K-anonymity of HCA's database

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#556]
**Description of the task:**

We are interested in knowing what's currently our k-anonymity score, based on donor and project information. 

**Acceptance criteria for the task:**

- [x] The full database has been downloaded, with one row per donor including the project information
- [x] A screening of the features that have to be dropped or added has been performed
- [x] Current k-anonymity score has been computed

**Currently waiting on feedback to decide whether this task is finished or has to be expanded**

**Comment by aaclan-ebi** [comment]
Gabs, Tony, Irene and Enrique had a meeting and discussed this yesterday. Irene and Enrique to meet tomorrow to see if this is possible with the expected timeframe.

**Comment by ESapenaVentura** [comment]
@ipediez and @ESapenaVentura had a meeting yesterday for reporting this, waiting on @tburdett 's feedback

**Comment by jacobwindsor** [comment]
@ipediez and @ESapenaVentura reviewed document and are okay with it
