### ISSUE TITLE
Train other members of the team on how to do schema releases

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#56]
@ESapenaVentura are you happy to lead this training? 

Could we perhaps use changing around insdc_project_accessions and insdc_study_accessions so they are correct. 
Perhaps @lauraclarke could comment on how we proceed with this kind of change in terms of informing people  or what level of "approval" is required with regards to this level of change.

**Comment by ESapenaVentura** [comment]
Happy to lead the training!

We will need confirmation to go ahead with that specific change, though, so until we hear from whatever people that might be affected by this change (I don't think anyone aside from browser/azul?) we can't proceed with it

**Comment by lauraclarke** [comment]
Given we don't have an update mechanism or schema migration mechanism yet I think picking a change which won't make all our existing project json documents invalid according to the schema is probably better

**Comment by clairerye** [comment]
Sounds like I need much more understanding about our schema. I had assumed we previously had a mechanism for migrating schemas.

**Comment by ESapenaVentura** [comment]
We have a mechanism to update our schemas, but the metadata in our system will retain their version of the schema.

We began a long time ago to prepare a migration tool for the schemas but @lauraclarke is right in that we don't have any mechanism to update already existing data.

**Comment by lauraclarke** [comment]
@ESapenaVentura @mshadbolt am I correct in thinking you have both now release schema?

Where is the documentation and is it in a state that it either @ami-day or @rays22 could do the next schema update with support from either of you?

**Comment by ESapenaVentura** [comment]
I did have a conversation with @mshadbolt on the 17th on how to do a "hotfix" release of the schema, and both @rays22 and @ami-day were present.

The information on how to create a metadata pull request is here: https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md#specific-how-to-for-making-changes

All the information about how to release a schema is here: https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/release_process.md (At the end there is a subsection on how to do a hotfix)

Happy to supervise if they want to push a schema update

**Comment by lauraclarke** [comment]
Thanks @ESapenaVentura is there anything preventing that PR from being merged?

**Comment by ESapenaVentura** [comment]
What PR? There is currently no open PR in the metadata schema repo

**Comment by lauraclarke** [comment]
Ah, I read this too quickly 

> The information on how to create a metadata pull request is here: https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md#specific-how-to-for-making-changes

and thought it was a pull request, not instructions on how to make a PR 🤦

**Comment by lauraclarke** [comment]
Sounds like this issue can be closed then, is that correct @ESapenaVentura ?

**Comment by ESapenaVentura** [comment]
Yes, I think waiting until we have a new PR and @ami-day or @rays22 can try to lead while being supervised by me or @mshadbolt is a good idea, and this ticket is not needed then.
