### ISSUE TITLE
Number of reads differ between fastq1 and fastq2

### ISSUE THREAD

**Issue by nikellepetrillo** [ebi-ait/hca-ebi-wrangler-central#560]
**Description of the task:**
The pipelines team started processing this [melanoma mouse ss2 dataset](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22Melanoma%20infiltration%20of%20stromal%20and%20immune%20cells%22%5D%7D,%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Mus%20musculus%22%5D%7D,%7B%22facetName%22:%22libraryConstructionApproach%22,%22terms%22:%5B%22Smart-seq2%22%5D%7D,%7B%22facetName%22:%22nucleicAcidSource%22,%22terms%22:%5B%22single%20cell%22%5D%7D,%7B%22facetName%22:%22pairedEnd%22,%22terms%22:%5B%22true%22%5D%7D,%7B%22facetName%22:%22fileFormat%22,%22terms%22:%5B%22fastq.gz%22%5D%7D,%7B%22facetName%22:%22specimenOrgan%22,%22terms%22:%5B%22tumor%22%5D%7D%5D)

The pipeline is failing as there is a pair of fastq files that do not have the same number of reads. 

gs://broad-datarepo-terra-prod-hca2-bucket/d30e68f8-c826-4639-88f3-ae35f00d4185/211aa09c-7e9f-4afc-adcb-465c5ce657fe/22028_5#9_1.fastq.gz  has 626 reads

gs://broad-datarepo-terra-prod-hca2-bucket/d30e68f8-c826-4639-88f3-ae35f00d4185/d3562cae-96ef-4e9d-8576-c9da53c0f1fe/SRR6585812_2.fastq.gz has 146001 reads 

Another thing to note is SRR6585812_2_fastq.gz does not follow the naming convention of any other fastqs in this dataset. I am seeing most other fastqs named something like:
22467_7#84_1.​fastq.​gz
22028_3#100_1.​fastq.​gz
21935_7#295_1.​fastq.​gz
22011_1#216_2.​fastq.​gz
22467_7#33_2.​fastq.​gz
etc. 

I am wondering if SRR6585812_2_fastq.gz really belongs in this dataset?

**Acceptance criteria for the task:**

**Comment by nikellepetrillo** [comment]
In the meantime, I will process this dataset without this pair. Please let me know if this is not what we want to do!

**Comment by ofanobilbao** [comment]
This is a dataset that Mallory and Dani wrangled. So it was probably already analysed for DCP1

**Comment by gabsie** [comment]
This will be prioritised for our Updates focus sprint, but for now this is fine.

**Comment by ofanobilbao** [comment]
Do we still need this ticket?

**Comment by ofanobilbao** [comment]
Is this ticket still required now that the pipelines are no longer involved? @ESapenaVentura ?

**Comment by ofanobilbao** [comment]
Is this ticket still required @ESapenaVentura ? If no answer in a week I will close

**Comment by ESapenaVentura** [comment]
Sorry, didn't see the previous comment

I don't think we want to modify the data, even less without a proper reason (pipelines using it)

**Comment by ofanobilbao** [comment]
Shall we then close the ticket @ESapenaVentura ? Thanks for your response
