### ISSUE TITLE
missing metadata field in optimus dataset 

### ISSUE THREAD

**Issue by nikellepetrillo** [ebi-ait/hca-ebi-wrangler-central#561]
**Description of the task:**

the pipelines team are running into an error trying to process this dataset: 
[Stress-induced RNA–chromatin interactions promote endothelial dysfunction](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22workflow%22,%22terms%22:%5B%22Unspecified%22%5D%7D,%7B%22facetName%22:%22libraryConstructionApproach%22,%22terms%22:%5B%2210X%203%27%20v2%20sequencing%22,%2210x%203%27%20v2%20sequencing%22,%2210x%203%27%20v2%22%5D%7D,%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22Stress-induced%20RNA%E2%80%93chromatin%20interactions%20promote%20endothelial%20dysfunction%22%5D%7D%5D)

We depend on the field specimen_from_organism__organ to be in the metadata but we are not seeing it. Can someone please take a look? Please let me know if I can help or provide anymore information!

**Acceptance criteria for the task:**

**Comment by ofanobilbao** [comment]
This is a Lattice dataset

**Comment by ESapenaVentura** [comment]
@nikellepetrillo we are not responsible for this dataset, is it ok if we close this ticket?

**Comment by ESapenaVentura** [comment]
@nikellepetrillo Please feel free to re-open the ticket if you want to discuss further!

**Comment by nikellepetrillo** [comment]
Hi @ESapenaVentura, sorry for the delay! Thanks for letting me know
