### ISSUE TITLE
SRP135960 - mouse_nervous_system

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#562]
### Primary Wrangler:
Ami

### Secondary Wrangler:

Google sheet: https://docs.google.com/spreadsheets/d/1sqyJAkyIrpyvt6I57UjA-SeVGBDMGsgrNOUsHb3jqdk/edit#gid=1026916226

### Associated files

* Google Drive:

### Published study links

* Paper: [Molecular architecture of the mouse nervous system](https://www.sciencedirect.com/science/article/pii/S009286741830789X)

* Accessioned data: SRP135960

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Please note I have assigned myself as primary wrangler to give lattice/UCSC an easy way to check if we are targeting this dataset

**Comment by ami-day** [comment]
Validated spreadsheet in ingest. Now syncing SRA object files to hca-util upload area.

**Comment by ami-day** [comment]
Downloading the bam files, the SRA objects convert only the cDNA read files.

**Comment by aaclan-ebi** [comment]
@ida to help on this

**Comment by ida** [comment]
@aaclan-ebi Hi, you probably wanted to ping someone else :)

**Comment by aaclan-ebi** [comment]
@ida sorry about the wrong tagging, thanks for pointing it out :))

@idazucchi to help on this

**Comment by ami-day** [comment]
It's ok, I found the 10X bamtofastq tool I already installed on EC2 previously. So they are converting to fastq now. It will likely continue to run over the weekend

**Comment by ami-day** [comment]
Files are uploading to hca-util upload area in a tmux session: de7633e2-5e38-4248-bb1d-593045b510eb

**Comment by Wkt8** [comment]
fed comments back to ami for secondary review :)

**Comment by ofanobilbao** [comment]
Blocked by https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/620

**Comment by idazucchi** [comment]
@jacobwindsor will try to delete the extra files

**Comment by ami-day** [comment]
this is done.
