### ISSUE TITLE
phs001790 - conservedCellTypesHumanMouse

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#563]
### Project short name:
conservedCellTypesHumanMouse
### Primary Wrangler:
Irene Perez-Diez
### Associated files

* Google Drive: https://drive.google.com/drive/folders/17RcdxQxVItpm49AJU-N-Jx2zsfKlP2I7?usp=sharing

### Published study links

* Paper: [Conserved cell types with divergent features in human versus mouse cortex](https://www.nature.com/articles/s41586-019-1506-7)

* Accessioned data: [phs001790](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001790)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ipediez** [comment]
@amnonkhen and @ipediez to have a discussion about Ingest and run out of memory issue

**Comment by ipediez** [comment]
Blockers:

- [ ] Ingest runs out of memory when importing with the spreadsheet
- [ ] The analysis file cannot be linked to all the cell suspensions, it overruns Excel's maximum number of characters per cell

**Comment by ipediez** [comment]
We agreed on aggregating the cell suspensions per donor and cell type and including as supplementary material the metadata.csv file provided by the authors, with all the information of a cell level. It has to be clear that that file is available and what information contains. As this only includes analysis files, would not affect the pipelines downstream.

This would change in this specific situation how we model an SS2 dataset, making it similar to a 10X modeling.

**Comment by ami-day** [comment]
Hi @idazucchi , my review comments are below:

**Collection Protocol**

- I would add the following to the cp_postmortem-tissue collection protocol:
"Middle temporal gyrus (MTG) was identified on and removed from frozen slabs of interest, and subdivided into smaller blocks for further sectioning. Individual tissue blocks were processed by thawing in PBS supplemented with 10 mM DL-dithiothreitol (DTT, Sigma Aldrich), mounting on a vibratome (Leica), and sectioning at 500 µm in the coronal plane. Sections were placed in fluorescent Nissl staining solution (Neurotrace 500/525, ThermoFisher Scientific) prepared in PBS with 10 mM DTT and 0.5% RNasin Plus RNase inhibitor (Promega) and stained for 5 min on ice. After staining, sections were visualized on a fluorescence dissecting microscope (Leica) and cortical layers were individually microdissected using a needle blade micro-knife (Fine Science Tools)."

- For the cp_neurosurgical-tissue collection protocol, I would replace:
""Microdissection of cortical layers was carried out on tissue slices that were thawed and stained as described above for postmortem tissue." 
with
""Sections were placed in fluorescent Nissl staining solution (Neurotrace 500/525, ThermoFisher Scientific) prepared in PBS with 10 mM DTT and 0.5% RNasin Plus RNase inhibitor (Promega) and stained for 5 min on ice. After staining, sections were visualized on a fluorescence dissecting microscope (Leica) and cortical layers were individually microdissected using a needle blade micro-knife (Fine Science Tools).”

**Specimen from organism**

- The paper says: ""The specimens collected for this study were apparently non-pathological tissues removed during the normal course of surgery to access underlying pathological tissues.”
I would therefore change the specimen disease status from epilepsy to normal and from brain cancer to normal, and keep the donor organism disease status as it is.

**Dissociation Protocol**

- I would move the following from the Dissociation Protocol Description to a new Enrichment Protocol:
" "resulting homogenate was passed through 30µm cell strainer (Miltenyi Biotech) and centrifuged at 900xg for 10 min to pellet nuclei. Nuclei were resuspended in buffer containing 1X PBS (Ambion), 0.8% nuclease-free BSA (Omni-Pur, EMD Millipore), and 0.5% RNasin Plus.”from dissociation protocol to cell size selection protocol in the enrichment tab."

**Enrichment Protocol**

- I think there should be 2 FACs protocols corresponding to NeuN+ cells (neuronal cells) and NeuN- cells (non-neuronal cells). The neuronal cell suspensions can then be distinguished from the non-neuronal cell suspensions in the Cell Suspension tab via the enrichment protocol. The non-neuronal cell suspensions can be identified from their descriptions.

**Cell Suspension**

- The Input Specimen from organism is missing from this tab for all cell suspensions.

Hope this helps!

**Comment by ipediez** [comment]
Thanks! Applied all the corrections
