### ISSUE TITLE
Check everything worked correctly for the duplicate projects, after Release 12

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/hca-ebi-wrangler-central#564]
Somebody should go and check whether everything works as expected after this redirect request for the Browser team:

=====Below we have identified which projects will be deleted from the two which have duplicates:

1. A single-cell atlas of the healthy breast tissues reveals clinically relevant clusters of breast epithelial cells  /  Single cell atlas of the healthy breast

a) https://data.humancellatlas.org/explore/projects/a004b150-1c36-4af6-9bbd-070c06dbc17d (Lattice)
b) https://data.humancellatlas.org/explore/projects/9bab0f03-a725-4a13-9ab1-196e46cd80ed (UCSC)

We will remove b) https://data.humancellatlas.org/explore/projects/9bab0f03-a725-4a13-9ab1-196e46cd80ed (UCSC), so please arrange for its URL redirect to a) above.

2. Single-cell analysis of Crohn’s disease lesions identifies a pathogenic cellular module associated with resistance to anti-TNF therapy.

c) https://data.humancellatlas.org/explore/projects/504e0cee-1688-40fa-b936-361c4a831f87 (UCSC)
d) https://data.humancellatlas.org/explore/projects/992aad5e-7fab-46d9-a47d-df715e8cfd24 (EBI)

We will remove d) https://data.humancellatlas.org/explore/projects/992aad5e-7fab-46d9-a47d-df715e8cfd24 (EBI), so so please arrange for its URL redirect to c) above.

Please get back to me if anything is unclear.

All the best
Gabby
--

**Comment by ofanobilbao** [comment]
@gabsie if this was about checking that the redirect takes place, the deleted project links now take you to the Project that has remained. If that's all you wanted to check this ticket could be considered done.

**Comment by Wkt8** [comment]
Checked and all is good.
