### ISSUE TITLE
Remove graph validator from EC2

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/hca-ebi-wrangler-central#565]
Since the work to include the graph validator in Ingest, it is no longer needed to be ran on the EC2 instance and the version on EC2 is out of date

**Comment by ESapenaVentura** [comment]
To be coordinated with the improved graph-validation deployment

**Comment by prabh-t** [comment]
Installations found (to shutdown and remove)
- [ ]`/data/tools/ingest-graph-validator` v0.6.2 (main)
- [ ] `/home/eventura/graph_validator/ingest-graph-validator` v0.5.4
- [ ] `/home/amnon/.venv/bin/ingest-graph-validator`

No env var.
No running instances.

**Comment by ESapenaVentura** [comment]
Please don't remove my installation or @amnonkhen 's, just delete the one in `/data/tools` (Unless amnon states otherwise)

**Comment by aaclan-ebi** [comment]
Should this be moved to _Done_?
