### ISSUE TITLE
Deleting a submission from ingest

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#566]
**Description of the task:**
PRJNA694128 - Co-evolution of tumor and immune cells during progression of multiple myeloma [#492](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/492)

There is a protocol which is not linked to anything and the graph validator raised the no_orphans error. Entities cannot be deleted from ingest so I need to make a new submission and delete the current one. 

The submission has to be deleted.
**submission uuid:** c7d84c13-1b85-44b6-8e8b-9d2aca7987a9
**project uuid:**  2ad191cd-bd7a-409b-9bd1-e72b5e4cce81

**Acceptance criteria for the task:**

- [x] submission deleted

**Comment by ke4** [comment]
Submission deleted

**Comment by ke4** [comment]
Files also removed from this S3 bucket: s3://org-hca-data-archive-upload-prod/c7d84c13-1b85-44b6-8e8b-9d2aca7987a9/
