### ISSUE TITLE
Deleting submissions from ingest

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#567]
I created a set of submissions that had to be deleted due to secondary reviews or graph validator errors, so the s3 buckets have to be removed:

- [x] s3://org-hca-data-archive-upload-prod/9ee2c0ea-caac-4d2e-8ad7-c23b085bb35b/
- [x] s3://org-hca-data-archive-upload-prod/de96f68f-5fd6-4d20-8d32-9ddc6e10447f/
- [x] s3://org-hca-data-archive-upload-prod/e6e7bcf4-141a-4607-bb0e-4236dd79cc65/
- [x] s3://org-hca-data-archive-upload-prod/acf23eed-1773-4a6a-87dc-c5ac1f57b8ad/

The last one might have been already deleted, but I am not sure

**Comment by ke4** [comment]
All the above listed S3 buckets has been removed
