### ISSUE TITLE
Flow integration ingest-graph-validator documentation

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#568]
**Description of the issue**
With the new changes in the ingest-graph-validator, we need to update the documentation to make sure it stays up-to-date with the new flow of validation

**Acceptance criteria**
- [x] Determine which documents need changes
- [x] Apply those changes

**Comment by ESapenaVentura** [comment]
Documents to be updated:

- [ ] https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#experimental-graph-validation

**Comment by ESapenaVentura** [comment]
Changes applied

**Comment by jacobwindsor** [comment]
@ESapenaVentura has updated and it has been reviewed. Waiting on graph validator changes to be put into production to merge these changes

**Comment by ESapenaVentura** [comment]
Done - The screenshot has been updated and it's available [here](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#experimental-graph-validation)
