### ISSUE TITLE
GompertsAirwatCfCells Optimus dataset fastq/participant association 

### ISSUE THREAD

**Issue by nikellepetrillo** [ebi-ait/hca-ebi-wrangler-central#569]
**Description of the task:**

The pipelines team is trying to process the following two projects: 
[GompertsAirwatCfCells V3 chemistry](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22workflow%22,%22terms%22:%5B%22Unspecified%22%5D%7D,%7B%22facetName%22:%22libraryConstructionApproach%22,%22terms%22:%5B%2210x%203%27%20v3%22,%2210X%203%27%20v3%20sequencing%22,%2210x%203%27%20v3%20sequencing%22%5D%7D,%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22Transcriptional%20analysis%20of%20cystic%20fibrosis%20airways%20at%20single-cell%20resolution%20reveals%20altered%20epithelial%20cell%20states%20and%20composition%22%5D%7D,%7B%22facetName%22:%22fileFormat%22,%22terms%22:%5B%22fastq.gz%22%5D%7D%5D)

[GompertsAirwatCfCells V2 chemistry](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22workflow%22,%22terms%22:%5B%22Unspecified%22%5D%7D,%7B%22facetName%22:%22libraryConstructionApproach%22,%22terms%22:%5B%2210X%203%27%20v2%20sequencing%22%5D%7D,%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22Transcriptional%20analysis%20of%20cystic%20fibrosis%20airways%20at%20single-cell%20resolution%20reveals%20altered%20epithelial%20cell%20states%20and%20composition%22%5D%7D%5D
)

Looking at the v3 workspace, each fastq (a fastq1, fastq2, and fastqi1) are split up and are associated with 3 different participant_ids. I believe all 3 fastqs should be associated with just one participant_id. 

I believe the same issue is present in the v2 workspace as well. 

Unfortunately, we are not able to process the data in this way. Can someone take a look? Please let me know if I can provide any help or anymore information! 
Thanks!

 **Acceptance criteria for the task:**

**Comment by ofanobilbao** [comment]
This dataset was wrangled by Rachel (UCSC). I don't know how to tag her.

**Comment by rachadele** [comment]
Hi– sorry, it was my mistake. The process_id column was left blank and ingest auto-completed it with incorrect IDs. How would I go about fixing this?

**Comment by willrockout** [comment]
Pretty the submission will need to be deleted and re-submitted as the experimental graph will change.

**Comment by Wkt8** [comment]
- [ ] Ask Will to give us further details about the experiment to determine the best way forwards to fix this

**Comment by ESapenaVentura** [comment]
Changes in linking will be supported very soon - Pumping this issue to the top of the priority list to keep in mind for next sprints
