### ISSUE TITLE
Prepare answers for Ben Hutton (JSON schema in the HCA)

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#570]
**Description of the issue**
Ben Hutton, from the JSON Schema team, has reached to us about feedback on the JSON Schema.

I have had a meeting with him today (Friday 26th, 2021) to define the goals and ask questions about the questionnaire.

We have determined that I will send him my feedback before next Wednesday.

**Acceptance criteria**
- [x] A document is created with the questions
- [ ] The questions are answered
- [ ] The answers are reviewed by other members of the team
- [ ] The document is sent back to Ben Hutton

**Comment by ESapenaVentura** [comment]
I have created a document and began filling it - Need some help with some questions https://docs.google.com/document/d/1_oqR8mX6CqI6EAea6mR0K4oVi1KbEoIZRb_t7SMwmkA/edit#

**Comment by idazucchi** [comment]
Many questions are about the very beginning of the project - @gabsie will help

**Comment by ofanobilbao** [comment]
@ESapenaVentura asked Tony for feedback. He will come back in a couple of days

**Comment by aaclan-ebi** [comment]
@ESapenaVentura will send Tony a reminder today.

**Comment by prabh-t** [comment]
@ESapenaVentura to speak to Tony today.

**Comment by gabsie** [comment]
a meeting will take place, to answer the questions.

**Comment by ESapenaVentura** [comment]
This is done on our side; outcome of the meeting will be answering the questions stated in the body of the ticket
