### ISSUE TITLE
Delete submissions/projects

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#571]
**Description of the issue**
To avoid re-exporting, we need to delete the following submissions:
- [lavaertThymus](https://contribute.data.humancellatlas.org/submissions/detail?uuid=9b0585ed-267e-4217-a384-df4c9f5acedd&project=dbd836cf-bfc2-41f0-9834-41cc6c0b235a), related to #446
   - [x] Delete the submission
   - [x] Delete the upload area associated with the submission
- [Rui chen retina](https://contribute.data.humancellatlas.org/submissions/detail?uuid=7d515499-b5b6-4083-95cd-6a393344865e&project=9c20a245-f2c0-43ae-82c9-2232ec6b594f), related to #548
   - [x] Delete the submission
   - [x] Delete the upload area associated with the submission

And the following projects (With their associated submissions):
- [healthyBreastTissue](https://data.humancellatlas.org/explore/projects/9bab0f03-a725-4a13-9ab1-196e46cd80ed), related to #551
   - [x] Delete the submission
   - [x] Delete the upload area associated with the submission
   - [x] Delete the project
- [CrohnsDisease](https://data.humancellatlas.org/explore/projects/992aad5e-7fab-46d9-a47d-df715e8cfd24), related to #551
   - [x] Delete the submission
   - [x] Delete the upload area associated with the submission
   - [x] Delete the project

**Comment by idazucchi** [comment]
@aaclan-ebi and @ESapenaVentura to discuss further steps for some of the projects

**Comment by ofanobilbao** [comment]
Not urgent. This ticket is assigned to Prabhat now

**Comment by prabh-t** [comment]
Karel -> first 2 have ingest urls which is done now.
other 2 have dcp urls, which Karel confirmed that the project uuid is the same as the ingest project uuid, and we can find the submission uuid(s) and proceed with deletion the same way.
SOP to follow -> https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/Delete-project.html

**Comment by prabh-t** [comment]
- healthyBreastTissue

sub=d9403bc2-0724-4e2a-a66b-c2ab8c1a8328
project=9bab0f03-a725-4a13-9ab1-196e46cd80ed

Ingest upload area -> deleted
Terra prod staging -> deleted
Spreadsheet in pod -> deleted

**Comment by prabh-t** [comment]
- CrohnsDisease

sub=efaded80-6ccb-428f-9676-da32533e88a0
project=992aad5e-7fab-46d9-a47d-df715e8cfd24

- [x] submission upload area deleted
- [x] terra staging area deleted (needed to disconnect from vpn for gsutil cmd to work)
- [x] 

- [x] updated Delete project SOP with latest/corrected instructions.

**Comment by aaclan-ebi** [comment]
Should this be moved to _Done_?

**Comment by ESapenaVentura** [comment]
@prabh-t please move to done if finished!
