### ISSUE TITLE
Dataset stuck in validating

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#580]
**Description of the issue**
Submission [here](https://contribute.data.humancellatlas.org/submissions/detail?uuid=12896ca4-38be-4784-9e20-27241fa9c68b) is stuck in validating for several days.

**Acceptance criteria**
- [x] Submission is valid
- [x] @ESapenaVentura sends a message to rachel

**Comment by ke4** [comment]
@aaclan-ebi is going to work on this today.

**Comment by aaclan-ebi** [comment]
@ESapenaVentura I've sent a message on slack to confirm that the submission is Valid. Ticking the last checkbox for you ;)

**Comment by ESapenaVentura** [comment]
Thanks @aaclan-ebi ! I think we can consider this done :)
