### ISSUE TITLE
GSE164986 - SubventricularStimulatingProgenitor

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#581]
### Project short name:
SubventricularStimulatingProgenitor

### Primary Wrangler:
@ESapenaVentura 

### Secondary Wrangler:
@ipediez 

### Associated files

* Google Drive: https://drive.google.com/drive/u/0/folders/1kFhQF9p0Orjj2eU5WMyi_efeIVs_UJXR

### Published study links

* Paper: https://www.researchsquare.com/article/rs-151881/v1

* Accessioned data: [GSE164986](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164986)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Dataset is ready for sec.review, but it won't make it to release 13 so will not ask for sec.review until later next week

Asked for new term: https://github.com/EBISPOT/efo/issues/1426

**Comment by ESapenaVentura** [comment]
Uploaded and ready for secondary review!

**Comment by ipediez** [comment]
Overall LGTM, I would add or change a few things:

### Donors
- ARTAG (Aging-related tau astrogliopathy), CAA (Cerebral Amiloid Angiopathy), Thal phase and CERAD scores are measures related with cognitive impairment and amyloid accumulation in absence of a diagnosed Alzheimer disease. I think it would add value to the dataset to add this scores under the donor organism description, as we do not have a specific field for this. The scores are available on Supplementary Data 1.

### Specimen from organism
- Post-mortem delay (PMD): you added to all of them the mean PMD (6.35h ==22860s). Change this for the individual PMD time (available at Supplementary Data 1). This would be 4h20m for brain_tissue_1 (15600s), 8h30m for brain_tissue_2 (30600s) and 6h55m for brain_tissue_3 (24900s)

### Analysis protocol
- for the alignment_processing, the derivation process is missing. I would add alignment and quantification.

**Comment by ESapenaVentura** [comment]
Thanks for the review! I have added the suggested values and everything should be alright now :) 

Exporting!

**Comment by ESapenaVentura** [comment]
Forgot to add myself as a data curator - Needs update

**Comment by ESapenaVentura** [comment]
Looks fine!
