### ISSUE TITLE
EGAS00001004561 - Cell types of the human retina and its organoids at single-cell resolution

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#583]
### Project short name:
tbd
### Associated files

* Google Drive: https://drive.google.com/drive/folders/1Gh46cY0o7vG3382aBqv9sAo5R6a70r7n

### Published study links

* Paper: https://pubmed.ncbi.nlm.nih.gov/32946783/

* Accessioned data:  

**Ingest**: 
https://contribute.data.humancellatlas.org/projects/detail?uuid=1dddae6e-3753-48af-b20e-fa22abad125d&tab=project

### Key Events

 - [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
probably will get to secondary review today

**Comment by aaclan-ebi** [comment]
@Wkt8 will focus on this today.

**Comment by ipediez** [comment]
Ready for secondary review. Bug on ingest about project PMID, @Wkt8 is going to try to fix it manually, but might need dev action. @ESapenaVentura

**Comment by Wkt8** [comment]
PMID Issue fixed! Thanks @ESapenaVentura

**Comment by ESapenaVentura** [comment]
I have reviewed the dataset and overall it looks good, I just have a couple of things that need to be reviewed/discussed:

## Donor
- For IMR90.4, there is age available at the cellosaurus entry https://web.expasy.org/cellosaurus/CVCL_C437, if you could fill that extra info it would be great!

## Collection protocol
- For AdultRetinalschemicCollection, I don’t think organ extraction is the best ontology. Maybe change it for surgical resection?

## iPSC induction protocol
- Looking at the paper where they were stablished, it looks like for the IMR90.4 cell line, the induction protocol involved a lentivirus. Maybe we need to add another protocol with that information?


## Library preparation protocol
- The IDs can’t contain special chars (`’`)

**Comment by Wkt8** [comment]
Made changes, synced, and exported.
