### ISSUE TITLE
Comprehensive identification of fetal cis-regulatory elements in the human genome by single-cell multi-omics analysis

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#584]
**Publication:**
Comprehensive identification of fetal cis-regulatory elements in the human genome by single-cell multi-omics analysis

**Priority:**
1

**Ingest:**
I tried to register the project after filling the project info form, and I am getting an error registering it: https://contribute.data.humancellatlas.org/projects/register?doi=10.1101%2F2021.11.02.466852%20&tab=save

The date for release of the raw data is March 2023. However, given the publication with methods is available, I think if we can, it would be good to submit the metadata only for now and update with the raw data once it becomes available:
https://ngdc.cncb.ac.cn/gsa-human/s/x70211Pp

**Comment by ofanobilbao** [comment]
Managed access dataset. Nor raw data nor the matrices will be available until 2023. Wranglers will discuss if it's worth the effort to have this in the backlog right now.

**Comment by ofanobilbao** [comment]
This was discovered on the last discovery script run on 19th January 2022. It is now in Ingest as https://contribute.data.humancellatlas.org/projects/detail?uuid=0b9bbe98-369e-4b73-a44f-a5fa077f085d 

The matrix files might be available already on one of the url links given in the pre-print

**Comment by Wkt8** [comment]
This is now a HCA-Publication and we are in communication with the author. They said that they will contact us when they are closer to publication due to issues with genetic material data sharing in China.

**Comment by ofanobilbao** [comment]
The entry in Ingest should be probably "Stalled" or "In Progress" and have the wrangler associated to it. Also, the estimated cell count has not been added to the Project info in Ingest. The Catalogue is still showing a count, not sure where from

**Comment by Wkt8** [comment]
It has been changed to stalled.

**Comment by Wkt8** [comment]
Closing this until the contributor comes back to us. Have updated information in Ingest.
