### ISSUE TITLE
Single-cell transcriptome analysis reveals coordinated ectopic gene-expression patterns in medullary thymic epithelial cells

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#589]
### Project short name:
mTECMouseHuman
### Primary Wrangler:
Irene Perez-Diez
### Associated files

* Google Drive:
* Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=e09ff95d-ed7a-4188-a583-9c8a66d94489&tab=project

### Published study links

* Paper: [Single-cell transcriptome analysis reveals coordinated ectopic gene-expression patterns in medullary thymic epithelial cells](https://www.nature.com/articles/ni.3246)

* Accessioned data: [E-MTAB-3346](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-3346/)
* Accessioned data: [E-MTAB-3624](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-3624/)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ipediez** [comment]
After taking a look at this dataset, the samples that it contains are: 

- Mouse samples for scRNA-seq
- Human and Mouse samples for ATAC-seq (NOT scATAC) 

Publication text referring to Human cell processing for ATAC-seq:
Human mTEC subsets (MHCIIhi cells positive for surface TRAs and MHCIIhi cells negative for surface TRAs) were isolated and sorted by flow cytometry as described(12). ATAC-seq experiments were performed as reported(31) with the following modifications: 5 × 103 to 50 × 103 pooled cells (depending on mTEC subset frequency) were **sorted** in flow cytometry buffer (PBS containing 5% FCS) and were used for ATAC-seq experiments.

They do not specify if it's scATAC, or if they isolate the cells. When looking at the data, there are 4 ATAC-seq samples (each one with a different phenotype) for 3 human patients. It looks more as bulk data than single-cell samples. 

If there's no single-cell data available for humans, is it still eligible?

**Comment by ipediez** [comment]
Downprioritised
