### ISSUE TITLE
Low-coverage single-cell mRNA sequencing reveals cellular heterogeneity and activated signaling pathways in developing cerebral cortex

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#591]
**Publication:**
Low-coverage single-cell mRNA sequencing reveals cellular heterogeneity and activated signaling pathways in developing cerebral cortex
https://www.nature.com/articles/nbt.2967

**Google Sheet:**
https://docs.google.com/spreadsheets/d/1KPZqqsCEbqUvOJDkXe55xaBB1F9iPndyo_N-yVs7Z6k/edit#gid=362761884

**Priority:**
1

**Ingest:**
https://contribute.data.humancellatlas.org/projects/detail?uuid=d2801b3a-ef64-428c-93dc-93b8be0cd236&tab=project

**Comment by ami-day** [comment]
Almost completed the metadata but have emailed the authors about linkings between iPSCs and NPC samples. Also to ask if the iPSC ids represent different technical replicates of the same cell line.

**Comment by ami-day** [comment]
The fastq files are downloading.

**Comment by ipediez** [comment]
Assigned myself as secondary reviewer

**Comment by ipediez** [comment]
Finished secondary reviewing, in general looks good except for a couple of things to change or add

### General

- In the unspoken best practices guidelines it's stated "Use a human-readable and nice description/name when possible (This goes for all biomaterials)". I would then advise changing the names and making them more human-readable, as a suggestion.

### Donor organism

- In the unspoken best practices guidelines it's stated "Treat cell lines as donors and include them in the donor tab. Donors donate a  specimen which gets turned into a cell line". I would add the donor and link it to the cell line using the collection_protocol_hiPSCs

### Dissociation protocol

- "Dissociation method" is missing for dissociation_protocol_fetal_tissue_G21_cultured_cells and dissociation_protocol_iPSCs
- You can also add Life Technologies to the manufacturer for those two dissociation protocols

### Cell suspension

- Add human-readable cell suspension names, at least in those cell_suspension.biomaterial_core.biomaterial_name that are currently blank

### Sequence file

- file names are missing
- if the sequencing protocol is pair ended, you might have to add process IDs, unique for each pair of reads

### Analysis protocol

- Add TPM (transcripts per kilobase million) as data normalization method, as the gene expression matrix is normalized used that method.
- You can add to the description that "Quantification of gene expression levels in TPM for all genes in all samples was performed using RSEM v1.2.4"

**Comment by ami-day** [comment]
Thank you @ipediez for the review. I made the changes you suggested.

**Comment by ami-day** [comment]
Data files are syncing to ingest: https://contribute.data.humancellatlas.org/submissions/detail?uuid=00aa7a76-ccb1-4c18-a997-a241f484a003

**Comment by ami-day** [comment]
Graph is validating.

**Comment by ami-day** [comment]
Blocked by linking problem associated with ingest.

**Comment by ESapenaVentura** [comment]
Missing health status for the specimen/donor whose sample was taken for the cell line. If that is intended because there is no information about it, feel free to ignore this part of the message

Data curator is missing

**Comment by ami-day** [comment]
Updated my role as data curator: https://contribute.data.humancellatlas.org/projects/detail?uuid=45c2c853-d06f-4879-957e-f1366fb5d423&tab=upload

Status is still "exported" though.

**Comment by ami-day** [comment]
submitted updates.

**Comment by ami-day** [comment]
looks as expected in hca data portal
