### ISSUE TITLE
Multiomics single-cell analysis of human pancreatic islets reveals novel cellular states in health and type 1 diabetes

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#595]
### Project short name:
Fasolino-Human-10x3pv2
### Primary Wrangler:
@ipediez 
### Associated files

* Google Drive: 
* Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=22eed35e-0062-4c7f-90ed-388e6c29a84f

### Published study links

* Paper: https://doi.org/10.1101/2021.01.28.428598

* Accessioned data: 

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ofanobilbao** [comment]
This one looking at the entry in Ingest looks to me like UCSC are working on it. I'll check with them to be 100% sure. Cause they have not filled their names on it. But it looks very much like something they would be working on, even with the Project Label

**Comment by ofanobilbao** [comment]
Checked with UCSC. Don't move to the backlog until they come back, please.

**Comment by ofanobilbao** [comment]
Enrique confirmed that nor UCSC nor Stanford is working on this dataset, so moving it to the Queue

**Comment by idazucchi** [comment]
this is a pre-print, there is no data that can be wrangled
@ofanobilbao to comment on this

**Comment by ipediez** [comment]
As for 19/01/2022, the publication is a pre-print with no data availability. It's also missing supplementary materials or other sources, such as GitHub, where we could extract sample metadata. Downprioritised for the moment, until it gets published or the authors update the pre-print with the information needed.
