### ISSUE TITLE
Human oral mucosa cell atlas reveals a stromal-neutrophil axis regulating tissue immunity

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#596]
**Publication:**
Human oral mucosa cell atlas reveals a stromal-neutrophil axis regulating tissue immunity

**Priority:**
2

**Comment by ofanobilbao** [comment]
We have a duplication in Ingest. And UCSC has already submitted this dataset. I will at least edit that in Ingest to showcase that.
