### ISSUE TITLE
Peng He - ImmuneLung

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#597]
### Project short name: 
ImmuneLung

### Primary Wrangler:
@ESapenaVentura 

### Secondary Wrangler:
TBD

### Associated files

* Google Drive:  https://drive.google.com/drive/folders/1PGu6yblSlzVM29nz7b5caApQtIrG0kKh
* ingest: [e71a9817-3330-44ac-af81-601c900fd349](https://contribute.data.humancellatlas.org/projects/detail?uuid=e71a9817-3330-44ac-af81-601c900fd349)
### Published study links

* Paper:

* Accessioned data:

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Organoid data: https://www.biorxiv.org/content/10.1101/2021.06.30.450501v1?rss=1&utm_source=dlvr.it&utm_medium=twitter

**Comment by MightyAx** [comment]
Organiod data is due to be split out and finished by the 15th February.

**Comment by ESapenaVentura** [comment]
This will be used for the Immune Lung dataset

Current status: 
- Asked for a bit more information on the project as it's missing key bits to import to AE

**Comment by Wkt8** [comment]
Rough publication date (Peng) for late March, but he wants accessions ASAP.

**Comment by ofanobilbao** [comment]
@ESapenaVentura any news/progress on this?

**Comment by gabsie** [comment]
This dataset went live but was meant to go live late November. Enrique will try and help.

**Comment by ESapenaVentura** [comment]
Managed to retract the dataset

**Comment by Wkt8** [comment]
ArrayExpress did ad-hoc annotation on the dataset, this was wrong in one of the samples. Enrique has created a ticket in the ArrayExpress helpdesk. 

We should think about how much active support we give as opposed to pointing people at the ArrayExpress / service helpdesk.

**Comment by ofanobilbao** [comment]
Might be now public as https://www.cell.com/cell-stem-cell/fulltext/S1934-5909(22)00460-X?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS193459092200460X%3Fshowall%3Dtrue

**Comment by idazucchi** [comment]
1. check if the publication matches the project
2. update ingest and close ticket

**Comment by idazucchi** [comment]
@arschat to check with Peng if this is the same dataset and if it can be pushed to the DCP?

**Comment by arschat** [comment]
Peng verified that the [biorxiv](https://www.biorxiv.org/content/10.1101/2021.06.30.450501v1.full) manuscript is the one that is now published in [Cell Stem Cell](https://www.cell.com/cell-stem-cell/fulltext/S1934-5909(22)00460-X).

**Comment by arschat** [comment]
The action here is to wrangle E-MTAB-11435 and GSE178529. I updated [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=e71a9817-3330-44ac-af81-601c900fd349) with this information but it is down-prioritized since it is not a bionetworks dataset, HCA publication nor the contributor reached out.

Therefore ticket is closed
