### ISSUE TITLE
Project Catalogue entries without Publications

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#598]
The following 17 projects present in the Catalogue are missing their publication information
``` projects.tsv 
Unique Key	Date added	Project Title	Publications	Authors	Organs	Technologies	Cell count	ENA	Arrayexpress	GEO	EGA	dbGaP	HCA Data Portal URL
6768e2c1-38ce-4b07-87d5-552d52f01a30	30/11/2021	Single-cell RNA sequencing of urinary cells reveals distinct cellular diversity in COVID-19- associated AKI			bladder organ	10x 3' v2				GSE180595			
2b38025d-a5ea-4c0f-b22e-367824bcaf4c	21/10/2021	Mapping the temporal and spatial dynamics of the human endometrium in vivo and in vitro			uterus	10x 3' v2, 10x 3' v3	55000	ERP128125, ERP127889	E-MTAB-10287, E-MTAB-10283				https://data.humancellatlas.org/explore/projects/2b38025d-a5ea-4c0f-b22e-367824bcaf4c
fde199d2-a841-4ed1-aa65-b9e0af8969b1	20/09/2021	Cells of the human intestinal tract mapped across space and time			large intestine, small intestine, vermiform appendix	Visium Spatial Gene Expression, 10x 5' v2	428000		E-MTAB-9543, E-MTAB-9536, E-MTAB-9532, E-MTAB-9533, E-MTAB-10386				
4c886170-3f73-4661-832f-ab10409e84a9	21/06/2021	COVID-19 tissue atlases reveal SARS-CoV-2 pathology and cellular targets.			lung, kidney, liver, heart	10x 3' v3	106792			GSE171668			
a0b4a252-c768-44df-a82a-399413a75ec1	17/06/2021	Integrative analysis of cell state changes in lung fibrosis with peripheral protein biomarkers.			lung	Drop-seq	233638						
0061c7e8-7b90-4296-be53-ca1de3bd6651	16/06/2021	A single-cell and spatial atlas of autopsy tissues reveals pathology and cellular targets of SARS-CoV-2			lung, kidney, liver, spleen, trachea, lymph node, muscle tissue, nasal cavity mucosa, oral epithelium, brain	10x 3' v3, 10x 5' v2, RNAscope	220023			GSE171668, GSE163530			
e9f36305-d857-44a3-93f0-df4e6007dc97	16/06/2021	Spatial multi-omic map of human myocardial infarction			heart	Visium Spatial Gene Expression	12184						
1538d572-bcb7-426b-8d2c-84f3a7f87bb0	16/06/2021	The local and systemic response to SARS-CoV-2 infection in children and adults			blood, respiratory tract	10x immune profiling	468214			GSE168215			
60ea42e1-af49-42f5-8164-d641fdb696bc	11/06/2021	A Protocol for Revealing Oral Neutrophil Heterogeneity by Single-Cell Immune Profiling in Human Saliva			saliva	Smart-seq2	1145	SRP271375					https://data.humancellatlas.org/explore/projects/60ea42e1-af49-42f5-8164-d641fdb696bc
910fc0b2-3054-47b2-97f0-549f23e29d72	11/06/2021	Single cell analysis of emergent haematopoiesis in the human fetal bone marrow			bone marrow	Smart-seq2, CITE-seq, 10x 3' v2, 10x 3' v1		ERP123145, ERP125305	E-MTAB-9389, E-MTAB-9801				
1ce3b3dc-02f2-44a8-96da-d6d107b27a76	11/06/2021	Single-cell analysis reveals the continuum of human lympho-myeloid progenitor cells			umbilical cord	Smart-seq2	420	SRP110699		GSE100618			https://data.humancellatlas.org/explore/projects/1ce3b3dc-02f2-44a8-96da-d6d107b27a76
cc95ff89-2e68-4a08-a234-480eca21ce79	02/06/2021	Census of Immune Cells			blood, bone marrow	10x 3' v2	528092	ERP122984					https://data.humancellatlas.org/explore/projects/cc95ff89-2e68-4a08-a234-480eca21ce79
005d611a-14d5-4fbf-846e-571a1f874f70	02/06/2021	Assessing the relevance of organoids to model inter-individual variation			skin of body, stem cell, brain	10x 3' v2	19916	ERP114427					https://data.humancellatlas.org/explore/projects/005d611a-14d5-4fbf-846e-571a1f874f70
9c20a245-f2c0-43ae-82c9-2232ec6b594f	27/05/2021	Transcriptomic classification of human retinal cell types with single-nuclei RNA-seq.			eye	10x 3' v3	230800						https://data.humancellatlas.org/explore/projects/9c20a245-f2c0-43ae-82c9-2232ec6b594f
fc232d87-7b10-47f7-9197-b2c6cf210dea	27/05/2021	Human Developmental Cell Atlas Sweden			brain, lung, heart	10x 3' v3					EGAS00001004375		
b176d756-62d8-4933-83a4-8b026380262f	27/05/2021	Single-cell transcriptional landscape of human embryonic limb development			hindlimb	10x 3' v2	27426	ERP119958	E-MTAB-8813				
116965f3-f094-4769-9d28-ae675c1b569c	27/05/2021	Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts			skin of body, embryo, immune system	10x 3' v2	6263	ERP120400					https://data.humancellatlas.org/explore/projects/116965f3-f094-4769-9d28-ae675c1b569c
```

**Comment by ESapenaVentura** [comment]
**Acceptance criteria**
- [ ] The reason why the projects are displaying publication information is determined for all projects
    - 2 main reasons:
        - No DOI
        - Other (There is DOI, but publication info is not being loaded)
- [ ] Actions to solve this issue are taken

**Comment by ofanobilbao** [comment]
Probably this will need re-assessing as with the promotion to production of a fix for projects that were not correctly showing the contributor information, the Catalogue no longer displays projects that do not have a DOI in Ingest. So this ticket might as well not be longer needed

**Comment by idazucchi** [comment]
I'm going through the projects, and some have disappeared from the catalogue because they are missing the DOI
My plan is to add it and hopefully they will be displayed correctly in the catalogue

**Comment by idazucchi** [comment]
Showing up in the project catalogue:
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=6768e2c1-38ce-4b07-87d5-552d52f01a30) Single-cell RNA sequencing of urinary cells reveals distinct cellular diversity in COVID-19- associated AKI - uuid is wrong, there is a submission but no wrangler assigned --> who is working on this? the catalogue is not checked so it's never going to show up 
- [x] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=2b38025d-a5ea-4c0f-b22e-367824bcaf4c) Mapping the temporal and spatial dynamics of the human endometrium in vivo and in vitro
- [x] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=fde199d2-a841-4ed1-aa65-b9e0af8969b1) Cells of the human intestinal tract mapped across space and time - **HCA paper, set priority?**
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=4c886170-3f73-4661-832f-ab10409e84a9) COVID-19 tissue atlases reveal SARS-CoV-2 pathology and cellular targets.
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=a0b4a252-c768-44df-a82a-399413a75ec1) Integrative analysis of cell state changes in lung fibrosis with peripheral protein biomarkers.
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=0061c7e8-7b90-4296-be53-ca1de3bd6651) A single-cell and spatial atlas of autopsy tissues reveals pathology and cellular targets of SARS-CoV-2
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=e9f36305-d857-44a3-93f0-df4e6007dc97) Spatial multi-omic map of human myocardial infarction
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=1538d572-bcb7-426b-8d2c-84f3a7f87bb0) The local and systemic response to SARS-CoV-2 infection in children and adults
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=60ea42e1-af49-42f5-8164-d641fdb696bc) A Protocol for Revealing Oral Neutrophil Heterogeneity by Single-Cell Immune Profiling in Human Saliva
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=910fc0b2-3054-47b2-97f0-549f23e29d72) Single cell analysis of emergent haematopoiesis in the human fetal bone marrow
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=1ce3b3dc-02f2-44a8-96da-d6d107b27a76) Single-cell analysis reveals the continuum of human lympho-myeloid progenitor cells
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc95ff89-2e68-4a08-a234-480eca21ce79) Census of Immune Cells
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=005d611a-14d5-4fbf-846e-571a1f874f70) Assessing the relevance of organoids to model inter-individual variation
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=9c20a245-f2c0-43ae-82c9-2232ec6b594f) Transcriptomic classification of human retinal cell types with single-nuclei RNA-seq.
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=fc232d87-7b10-47f7-9197-b2c6cf210dea) Human Developmental Cell Atlas Sweden
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=b176d756-62d8-4933-83a4-8b026380262f) Single-cell transcriptional landscape of human embryonic limb development
- [ ] [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=116965f3-f094-4769-9d28-ae675c1b569c) Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts

**Comment by gabsie** [comment]
@jacobwindsor to send his list of projects and we identify why the above behaviours.

**Comment by idazucchi** [comment]
how long does it take for the projects to show up in the catalogue after the doi has been added to ingest?

**Comment by jacobwindsor** [comment]
I have fixed the issue with those not shown because of missing DOIs in [this PR](https://github.com/ebi-ait/projects-index/pull/81)

**Comment by jacobwindsor** [comment]
List of uuids without DOIs:

```
cc95ff89-2e68-4a08-a234-480eca21ce79
9c20a245-f2c0-43ae-82c9-2232ec6b594f
116965f3-f094-4769-9d28-ae675c1b569c
b176d756-62d8-4933-83a4-8b026380262f
fc232d87-7b10-47f7-9197-b2c6cf210dea
1ce3b3dc-02f2-44a8-96da-d6d107b27a76
60ea42e1-af49-42f5-8164-d641fdb696bc
fde199d2-a841-4ed1-aa65-b9e0af8969b1
2b38025d-a5ea-4c0f-b22e-367824bcaf4c
```

FYI @idazucchi @gabsie you can see this list yourself by opening the developer tools on the project catalogue.Any projects which aren't shown due to an error are shown their with the error and the UUID.

@idazucchi the script runs at 11:00PM every night so the day after you will see it in the catalogue.

**Comment by jacobwindsor** [comment]
@idazucchi The fix is now in production

**Comment by gabsie** [comment]
2 extra projects to take a look at, for @jacobwindsor cc @idazucchi
