### ISSUE TITLE
Linking large number of cell suspensions to an analysis file

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#599]
**Dataset/group this task is for:**

[conservedCellTypesHumanMouse #563
](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/563)

[Link to Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=165dea71-a95a-44e1-88cd-b2d9ad68bb1e)

[Spreadsheet (Drive)](https://docs.google.com/spreadsheets/d/11Yl8esLqqSgralm7dtjgcrIV_XTj3Mq5/edit?usp=sharing&ouid=112854478400213800085&rtpof=true&sd=true)

see related dev ticket: ebi-ait/dcp-ingest-central#590
**Description:**

This dataset is a big SMART-seq experiment with 49418 cell suspensions, with managed access data. Therefore, there are no FASTQ files available, and the authors have published a count matrix file that has to be linked to all the cell suspensions. The resulting string is not accepted by Excel at the corresponding cell, as it is too large. 

See [meeting summary](https://docs.google.com/document/d/1EzytgahoG7wAT56nirG7juR9x_IqAqVFFtUV7stF2fY/edit) by Irene and Amnon

Alternatives (arbitrarily ordered):

1. Leave “analysis file.cell suspension id” empty, load the spread sheet and update the links to sequence file using the api 
2. Add a worksheet to represent the link between an analysis file and sequence file.
3. Use “synthetic” cell suspension ids for each cell type and patient (despite the experiment having just a single cell suspension per individual cell)

a more details analysis of the solutions is in the meeting summary.

If loading the data to ingest is urgent, we'll start with 2, otherwise - we shall choose 1.

**Comment by ipediez** [comment]
Ingest yields an "out of RAM" error when trying to upload the spreadsheet. 

**Tests performed**

- Upload the spreadsheet with the correct information - Causes Ingest to break
- Upload the spreadsheet with invalid metadata (not allowed values at specimen_from_organism.preservation_storage.storage_method) - It does not break, Ingest shows the status "Metadata Invalid"

**Comment by prabh-t** [comment]
There is another issue beyond the memory issue, it seems..

**Comment by gabsie** [comment]
this will be picked up on the Stanford meeting to discuss this. the work can be revised afterwards.

**Comment by ofanobilbao** [comment]
Still pending discussion with the UCSC wranglers

**Comment by ipediez** [comment]
We agreed on aggregating the cell suspensions per donor and cell type and including as supplementary material the metadata.csv file provided by the authors, with all the information of a cell level. It has to be clear that that file is available and what information contains. As this only includes analysis files, would not affect the pipelines downstream.

This would change in this specific situation how we model an SS2 dataset, making it similar to a 10X modeling.
