### ISSUE TITLE
Bring HCA Projects that were accessioned directly in DSP into Ingest

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#60]
Ensure DSP projects that do not exist in HCA are added and accessioned:
- [x] S-SUBS5 EmbryonicHindlimb
    - [EmbryonicHindlimb](https://submission.ebi.ac.uk/api/submissions/5daa94c0-c642-401e-8fcd-c4b83543df0f)
    - [EmbryonicHindlimb_update_1](https://submission.ebi.ac.uk/api/submissions/796306f2-e411-47bc-87fd-22999e55a7ef)
- [x] S-SUBS4 [AdultHemOrgans] ~~ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=3f59ea2e-0d30-46cb-bbc0-9223a778e732)~~ <https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=af36b442-c96d-4708-99cc-b01c38dbd367>
~~- [ ] [AdultHemOrgans 291ea7ff](https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=291ea7ff-5ae3-4785-b5b2-155e388fdc79)~~
 ~~- [16e5a58f-8f57-48cb-abab-72d410981b59](https://submission.ebi.ac.uk/api/submissions/16e5a58f-8f57-48cb-abab-72d410981b59)~~
 ~~- [655fcbfd-f290-48c3-b959-2a662cd5d2ae](https://submission.ebi.ac.uk/api/submissions/655fcbfd-f290-48c3-b959-2a662cd5d2ae)~~
    - ~~`Jul 1, 2020, 10:22:23 PM	609a2401-246d-470f-a89e-6dfc38f3c7a9	Valid`~~
    - `Jul 15, 2020, 4:56:33 PM  90513d30-5f47-473e-b180-c37a974fc03b  Valid`

https://github.com/ebi-ait/ingest-archiver/wiki/DSP-Submissions-to-HCA-Projects/

**Comment by rays22** [comment]
### AdultHemOrgans

* I have updated the AdultHemOrgans HCA metadata spreadsheet to include
    * publication information for preprint PPR110213 and
    * [BioStudies and BioSamples accessions](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/72#issuecomment-653081923)

* To prevent any potential confusion, I have deleted two earlier outdated submissions and the associated project. Note, that these have never been part of DCP1: [AdultHemOrgans 291ea7ff](https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=291ea7ff-5ae3-4785-b5b2-155e388fdc79)
    1. [16e5a58f-8f57-48cb-abab-72d410981b59](https://submission.ebi.ac.uk/api/submissions/16e5a58f-8f57-48cb-abab-72d410981b59)
    2. [655fcbfd-f290-48c3-b959-2a662cd5d2ae](https://submission.ebi.ac.uk/api/submissions/655fcbfd-f290-48c3-b959-2a662cd5d2ae)

* I have re-created the project and uploaded the updated HCA metadata spreadsheet to Ingest <https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=af36b442-c96d-4708-99cc-b01c38dbd367>:

```
Jul 1, 2020, 10:22:23 PM	609a2401-246d-470f-a89e-6dfc38f3c7a9	Valid	
```

* I have uploaded the `fastq.gz` sequencing data files of the set to the Ingest upload area that is associated with the latest submission:

`s3://org-hca-data-archive-upload-prod/609a2401-246d-470f-a89e-6dfc38f3c7a9/`.


- [ ] I have not clicked `Submit`in Ingest UI for this dataset yet.
Please, note that this dataset has already been archived: it does NOT need new archive accessions. In other words, it should not be submitted to EBI archives via DSP.

**Comment by rays22** [comment]
> Ensure DSP projects that do not exist in HCA are added and accessioned:
> 
> *

@MightyAx ,
Do you mean adding archive accessions by 'accessioned' in the task description above?
I believe these datasets should not be submitted via DSP for archiving, because they have already been archived. I think we just need to send them to DCP2, because they are not part of DCP1. They came after the DCP1 freeze.
What should be done differently in Ingest UI for these two datasets? Also, before I click `Submit`, is there any issue devs need to be aware of?

**Comment by MightyAx** [comment]
To summarise our call:
### S-SUBS5 EmbryonicHindlimb
A spreadsheet exists somewhere that was used to generate the DSP submission but not added to ingest, this spreadsheet needs the DSP accessions added to it and then can be uploaded to ingest and submitted (skipping the archiving phase)

### S-SUBS4 AdultHemOrgans
Was not part of DCP 1 and the DSP submissions identified in the ticket were never submitted, so therefore there is no "lost context" from deleting the ingest project that the submissions referenced and starting again, to resolve the inaccessible upload area that ray experienced.

Each of the entities in the EBI archives  will need to be manually updated to reference the new HCA UUIDs, and to make these changes in DSP we will need a user account in the same AAP domain...  There may be an opportunity to bring this project "into the fold" when we transition away from DSP.

**Comment by lauraclarke** [comment]
@ESapenaVentura can you give a reference to the metadata/data for S-SUBS5 EmbryonicHindlimb

**Comment by ESapenaVentura** [comment]
**Metadata**: https://drive.google.com/drive/folders/1Zi6ulhmTFzmOhvLXrYJY1G61oi3llNK1 - Both spreadsheets up to date, the difference is one contains metadata for the BAM files (With my script it was the easiest way to do it)

**Data**: Refer to the s3 bucket here https://github.com/HumanCellAtlas/hca-data-wrangling/issues/388 changing the prefix from `org-humancellatlas-upload-staging` to `hca-wrangler-backup`

Please let me know if I can be of any help with it!

**Comment by rays22** [comment]
### Dataset: S-SUBS4 AdultHemOrgans

This morning I made a submission to project
<https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=af36b442-c96d-4708-99cc-b01c38dbd367>

The submission is from upload Jul 1, 2020, 10:22:23 PM and it has status `Exporting`

```
Jul 1, 2020, 10:22:23 PM    609a2401-246d-470f-a89e-6dfc38f3c7a9    Exporting.
```

I need to add the ENA accessions to the metadata. I have tried to upload an update submission:

```
Jul 6, 2020, 4:30:27 PM db5fa8f5-5069-4aa0-a5f9-edc61f9120fd    Submitted   
```

, but it does seem to have done only a partial update. I can not see any updates using Ingest UI concerning
INSDC project accession (`project.insdc_study_accessions`)
 and
ENA run accessions (`sequence_file.insdc_run_accessions`).

If necessary, I could re-start the project/submission from scratch, but I can not delete submission `609a2401-246d-470f-a89e-6dfc38f3c7a9` that has the status `Exporting`.
I have the updated metadata spreadsheet and the data files, but I am unable to update the existing submission or delete and re-create this project from scratch with the updates.

**Comment by ESapenaVentura** [comment]
**DATASET: S-SUBS5 EmbryonicHindlimb**

- Updated spreadsheet manually with accessions. It's in the google drive folder, with the suffix "_accessions"
- Uploaded spreadsheet and data to ingest: [Submission](https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?id=5f058e503d2910077dd42e09&project=b176d756-62d8-4933-83a4-8b026380262f)
- Checked that the submissions were there, submissions were successfully added to both project, biomaterials and sequence file metadata.
- Currently validating files, but it should become valid in about an hour.

**Comment by lauraclarke** [comment]
## Dataset: S-SUBS4 AdultHemOrgans

@lauraclarke to confirm what action is needed for the partial export to the DCP staging area with Rolando see https://embl-ebi-ait.slack.com/archives/C013EPUJ18W/p1594200340001200
@rays22 to remove the existing ingest submission for AdultHemOrgans and reupload spreadsheet leaving in a valid state without submitting

**Comment by ESapenaVentura** [comment]
@aaclan-ebi This is the ticket to bring S-SUBS4 and S-SUBS5 into ingest

**Comment by rays22** [comment]
Hi @aaclan-ebi ,
Please, let me know when it is OK to re-upload metadata spreadsheet for project AdultHemOrgans <https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=af36b442-c96d-4708-99cc-b01c38dbd367>.
Thanks.

**Comment by aaclan-ebi** [comment]
Hi @rays22 ! I've deleted the submissions for that project. You can reupload the spreadsheet now. But please don't submit it yet.

**Comment by rays22** [comment]
> Hi @rays22 ! I've deleted the submissions for that project. You can reupload the spreadsheet now. But please don't submit it yet.

Thanks @aaclan-ebi !

**Comment by rays22** [comment]
I have uploaded the HCA spreadsheet `FASTQ-updated-ENA_accessions.xlsx` to Ingest UI.
It is still `Validating` after 25 minutes.

**Comment by rays22** [comment]
The submission is still stuck in status `Validading` in Ingest UI.
```
Jul 15, 2020, 4:56:33 PM | 90513d30-5f47-473e-b180-c37a974fc03b | Validating
```
@aaclan-ebi ,
Could you kindly look into why it is stuck?

**Comment by aaclan-ebi** [comment]
Hi @rays22 ! 

There was a failure in marking 1 metadata as Valid. I believe this is already being retried in the code but I will double check. 

I've manually triggered the validation and that metadata is set to Valid. The submission is now in Draft because files are not uploaded yet. You may now upload the files.

Thanks!

**Comment by rays22** [comment]
Thank you @aaclan-ebi ! I will upload the file soon.

**Comment by rays22** [comment]
I have uploaded the sequence data files of S-SUBS4 AdultHemOrgans  to upload area
`    s3://org-hca-data-archive-upload-prod/90513d30-5f47-473e-b180-c37a974fc03b/`.
The submission status is now `Valid`.
