### ISSUE TITLE
Ingest server and display error

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#600]
**Dataset/group this task is for:**

proliferatingRetinoblastomaSCRNAseq

**Wrangler responsible for this dataset/lab:**
@rachadele

**Description of the task:**

I'm encountering the following error when I upload the spreadsheet for this project to ingest:

```
An error occurred importing the file.

Received an HTTP 500 from http://172.20.134.175/processes/61c0e83bf358643c2eb2de64/protocols: http://172.20.134.175/processes/61c0e83bf358643c2eb2de64/protocolsUnexpected server error
```
Additionally, the submission is not displaying the invalid metadata entities when I filter for them:
[https://contribute.data.humancellatlas.org/submissions/detail?uuid=ed214ccb-cbdf-450a-b972-7958b457afde&project=d6225aee-8f0e-4b20-a20c-682509a9ea14](https://contribute.data.humancellatlas.org/submissions/detail?uuid=ed214ccb-cbdf-450a-b972-7958b457afde&project=d6225aee-8f0e-4b20-a20c-682509a9ea14)

**Comment by aaclan-ebi** [comment]
Checking the 
```
2021-12-20 20:32:32	
{"log":"[ingest_submitter.py:77 - link_entities() ] 2021-12-20 20:32:32,270 - ingest.importer.submission.ingest_submitter - ERROR - 500 Server Error: for url: http://172.20.134.175/processes/61c0e83bf358643c2eb2de64/protocols\n","stream":"stderr","time":"2021-12-20T20:32:32.273851596Z"}
2021-12-20 20:32:32	
{"log":"[ingest_submitter.py:76 - link_entities() ] 2021-12-20 20:32:32,269 - ingest.importer.submission.ingest_submitter - ERROR - The process with id process_SRR13633760 could not be linked to protocol with id library_protocol_1.\n","stream":"stderr","time":"2021-12-20T20:32:32.270146088Z"}

```

**Comment by aaclan-ebi** [comment]
It seems that it's getting an OptimisticLockingFailureException when trying to set the protocol's validation state to Draft after the linking. I'll add a retry on that.

**Comment by aaclan-ebi** [comment]
Hi Rachel, I've pushed the fix to prod and recreated the submission. Please check: https://contribute.data.humancellatlas.org/submissions/detail?uuid=e1d3811b-f633-45fb-8eff-123dd604c75f&project=d6225aee-8f0e-4b20-a20c-682509a9ea14

**Comment by rachadele** [comment]
Thanks :- )
