### ISSUE TITLE
questions about the HCA atlas construction

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#601]
Received on 22/12/2021 on the wranglers mailbox

> Subject: [wranglers] I have a few questions about the HCA atlas construction.
> Date: 22 December 2021 at 15:08:35 GMT
> To: "wrangler-team@data.humancellatlas.org" <wrangler-team@data.humancellatlas.org>
> 
> Hello,
> I'm xxxxx from GIST, South Korea.
> 
> First of all, I appreciate developing this project to broaden our understanding of the various tissues.  
> 
> I have a few questions about the HCA atlas construction.
> 
> When HCA creates an atlas for a specific tissue or disease,
> are there detailed guidelines for sample preparation such as how many patient samples do we need, 
> how much tissue size is needed, and what protocol the hospital goes through to make the library?
> In addition, can I know what is the minimum number of cells, viability, data QC standards, etc.?
> 
> thank you
> 
> xxxxxx
> 
> School of Life Sciences
> Gwangju Institute of Science and Technology (GIST)
> Tel.: xxxxxx
> E-mail: xxxxxxx
>

**Comment by amnonkhen** [comment]
need help from @tburdett & @gabsie on how to answer

**Comment by ofanobilbao** [comment]
From what I saw this morning, Will from UCSC responded to the query before the end of the year, but forgot to copy the wrangler email. He said they would take care of the query if they get an answer from them
