### ISSUE TITLE
Create Google Drive Folder with Testing Spreadsheets

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#602]
**Description of the task:**

Create a folder in Google Drive with spreadsheets to be used for testing purposes. This folder will be accesible by everyone in the team.

**Acceptance criteria for the task:**

- [x] A Google Drive folder exists with the name "Testing Spreadsheets"
The folder contains at least:
- [x] - Any testing spreadsheets we might have scattered in different places.
- [x] - One small biologically meaningful spreadsheet with Project Information sheet
- [x] - One small biologically meaningful spreadsheet without Project Information sheet
- [x] - The folder is accessible by everyone in the team
- [x] - Relevant hca-util upload areas for the files 
@gabsie to add more potential types of testing spreadsheets

**Comment by Wkt8** [comment]
Imaging test data: https://drive.google.com/drive/folders/15MOmkLStw7AzSoK6sSEbdv_HJY0bZcZF
Ingest-graph-validator test data: https://drive.google.com/drive/folders/14cTkOwC8_DAKkRNpxvoJMTgZBBqjxpTB

**Comment by ESapenaVentura** [comment]
https://drive.google.com/drive/folders/1dKZ5bscfej7U_rjJNt0DUBi0B8r58FFo

I have created a folder with testing data within the AIT Google drive. A detailed content description can be found [here](https://docs.google.com/document/d/1iXtq0Yy2F0qW5bt9ce50N4juMQhQuCWqu6hFZi_oong/edit#heading=h.feyxk8ne04sb)

I have a couple of comments:
- Should we include this in an SOP? if so, any ideas in which?
- @Wkt8 can you input the hca-util upload area for the imaging data?
- @jacobwindsor can you check if with those spreadsheets we cover (more or less) all the use cases?

**Comment by ESapenaVentura** [comment]
Another comment:

- @ofanobilbao I skipped adding a spreadsheet without project because, currently, there is no need to. The project information can be skipped anyways, and it would just be a duplicate with 4 tabs less

**Comment by Wkt8** [comment]
Have added an additional imaging data spreadsheet and input the hca-util upload areas for both.

**Comment by jacobwindsor** [comment]
Thanks @ESapenaVentura. I have added some comments in the sheet.

I have some further thoughts though...

I think all of these sheets are better than the SS1 sheet we currently use for integration tests. We've had many discussions about refactoring/redoing our integration tests to make them less repetetive and also make them do extra bits like performance testing. I think we could:

- Use the small or medium (depending on time taken) sheets to replicate our current flow of submisson -> archiving
- Use the large dataset for performance testing and run on prod/staging once daily and ensure it takes less than a given time to export
- Can we allow the wranglers to add test cases to our integration tests with this? For example, have one folder with a few valid spreadsheets in that will alll be uploaded and ran through ingest when integration tests run. If the wranglers discover a new thing they want to test (e.g. cross submission entity linking), they add spreadsheets to that folder and they will be picked up by our integration tests

Also @ESapenaVentura can you give me some clarification on the difference in purpose between this and [this](https://github.com/HumanCellAtlas/metadata-schema/tree/staging/infrastructure_testing_files)?

**Comment by ESapenaVentura** [comment]
Hey Jacob!

There is not much difference between the 2.

The ones I created are more up to date, basically, but "in essence" (they are not the same project) they should be very similar

I will address the comments ASAP!

**Comment by ESapenaVentura** [comment]
I have tried to address all the comments

Please let me know if you're missing anything and I'll add it when I'm back

**Comment by Wkt8** [comment]
Karoly made another SS2 integration test spreadsheet for integration tests without accessions, and might be good to add it here too.

**Comment by ESapenaVentura** [comment]
I think I have addressed all the comments - Could anyone review and comment?
