### ISSUE TITLE
DCP dataset issue

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#603]
### The dataset
Sampling time-dependent artifacts in single-cell genomics studies:
https://data.humancellatlas.org/explore/projects/5b328561-4a97-40ac-b7ad-6a90fc59d374?catalog=dcp12

### Problem
It caused some problems when indexing, with approximately 400 subgraphs failing. It seems that was caused due to a three-level subgraph structure that hasn't been observed before. 

### Comments
On slack, @ESapenaVentura asked for "any entity UUID from an entity within those subgraphs", which can be obtained with `curl -s 'https://service.azul.data.humancellatlas.org/index/samples?filters=%7B%22projectId%22%3A%7B%22is%22%3A%5B%225b328561-4a97-40ac-b7ad-6a90fc59d374%22%5D%7D%7D&size=100&catalog=dcp12' | jq -r '.hits[]|.entryId'` givif 55 specimen UUIDs.

Will commented: 'I wouldn’t say the info is misleading it's just not mapped right and I believe one is causing the issue above with mapping analysis files to sequence files which I don’t believe done before and I believe can be removed.' and 'What wrong is how the experiment is mapped out it doesn’t accurately represent what the lab did.'

**Comment by ipediez** [comment]
@ipediez to check the dataset and the experimental design will be commented with @ESapenaVentura, who will include this as a discussion in the Wrangler catch-up call

**Comment by gabsie** [comment]
looks like a complex update.
let's address this for next  (not current release).
@ipediez will get a new project started for release 13.

**Comment by gabsie** [comment]
closing this (as an investigation). the wrangling update ticket will be kept for tracking.
