### ISSUE TITLE
Curation of Auto-Imports - Jan 22 Discovery

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#610]
**Projects to be curated**

- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=8beea2ed-7908-4204-b524-dad0e9c39620 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1d30a05c-aab7-47ca-972e-bf63acfc143f 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1c4cbdd4-33e3-4ded-ab43-5958de817123 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2eb96e32-b826-4de2-a97f-c6f7b01b9789 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=23005067-45da-432c-a5a7-a2065facdf92 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=772a0ab7-82e2-4c00-b091-1fe2dfc2fd0d 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=1c6a5547-e0cc-46f0-9988-1adf4fb3e9b7 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=66ab6ad5-aebb-4667-9ec6-9510fc74159f 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=94ee6877-5188-459a-a13d-a8ef1ad13274 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=e4a82fcd-d2b7-4b81-a449-acabb8818f9e 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=150dbd6a-8c30-4532-9550-13ea8ddb1af2 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=da922da8-eabe-4f99-8b58-425fd2af83df 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=91b793fb-cbad-4beb-9ffa-497953a6140b 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=67a5e888-c068-4268-a335-8badb001b2e9 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=b79b44ce-1bc2-4ffb-89db-1e260c2ba4af 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=cff1f482-e4a2-47ce-b005-a02ae627985c 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7d418c5f-79be-47ee-9f81-27366b8c5746
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=0b9bbe98-369e-4b73-a44f-a5fa077f085d 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=ef50f280-76dc-4d08-9bb3-3e28270220e9 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=25e5718f-6aac-4a4d-aa05-5f7d12f12a47 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=04bb1408-8c11-404e-b84a-e26c9284424e 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=06eeb0c9-ad5b-44bf-87db-f47e341f5e5d 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=ce207cf0-03f7-4383-a46d-d5ab9417aa24 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=423e8cbd-f03c-4177-a1ec-e112633ef930 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=bd38d12f-0fb7-42c4-8799-28ac9bd09d60 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=b0dad03e-e604-4583-a699-937a81f692d0 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=2cb10e9d-8806-42df-b565-550a15bfdf65 
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a8b9b3b2-808e-4a85-b9de-c48b5b9c772f 

**Acceptance criteria**
- [ ] All projects have been curated according to the instructions in the [SOP](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_acknowledgement_SOP.html#manual-curation-after-addition)
- [ ]  Projects show in the catalogue correctly

**Comment by prabh-t** [comment]
@wei to have a look at @ipediez comment.

**Comment by jacobwindsor** [comment]
@Wkt8 to take a look

**Comment by Wkt8** [comment]
@ipediez The closest link I found was that the last author in 'Single cell transcriptomics reveals distinct effector profiles of infiltrating T cells in lupus skin and kidney' is also an author in the SCP-279 data (Dataset 2: Lupus Nephritis (Broad Institute)). Regardless, looking at the supplementary tables from both papers shows a lot of inconsistencies. We should deprioritise this until those have been sorted out.

**Comment by yusra-haider** [comment]
@Wkt8 working on this. One more left to do

**Comment by Wkt8** [comment]
This is now complete!
