### ISSUE TITLE
[Urgent - Update] Export submission in "Complete" status

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#611]
Related to comment here https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1642638272023500

**Description of the issue**
A dataset is stuck in "Complete" status, therefore needs a developer to push it to "valid" and then needs to be exported. Import form has already been filled in.

**Acceptance criteria**
- [ ] Submission for project [iPSCderivedTenocyte](https://contribute.data.humancellatlas.org/submissions/detail?uuid=b348bae8-1c39-4221-8701-b23a755a3636&project=78d7805b-fdc8-472b-8058-d92cf886f7a4) is set back to valid
- [ ] Submission is validated again
- [ ] Submission is exported with `metadata only` flag on

**Comment by idazucchi** [comment]
@yusra-haider

**Comment by yusra-haider** [comment]
steps to perform:

- [ ] set submission to valid state by using endpoint:
https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/61e74ba47701fb51a5c31d1d/commitValidEvent

- [ ] redeploy state tracker

**Comment by aaclan-ebi** [comment]
Updates were exported for this submission.
