### ISSUE TITLE
Review mapping document for ENA archiving

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#613]
**Description of the issue**
Wranglers need to review the mapping document (https://docs.google.com/spreadsheets/d/18LvAf8wv-yGV552kk0R3SlGf5oEmAyKdKZ2OMk9QMWk/edit#gid=1421951667) to verify that we are going to archive with the proper metadata

**Acceptance criteria**
- [ ] At least one wrangler reviews and fills out the missing parts of the document
- [ ] Most (Preferably all but don't delay on capacity) wranglers agree on the mapping
- [ ] The mapping is fed back to @ke4 for future iterations on improvements

**Comment by ofanobilbao** [comment]
This is now probably obsolete. If Archiving work is prioritised this sprint, we might need something entirely different. Will ask the question and might as a consequence either put this in the To Do or Close

**Comment by ofanobilbao** [comment]
Still relevant as it might be required as part of the archiving

**Comment by ofanobilbao** [comment]
@amnonkhen could you, please, move it to the development repo? If required it will be as part of the Archiving process, not an operational need. I hope it makes sense

**Comment by idazucchi** [comment]
we have not worked on archving in the past year and a half, I'm closing this ticket since we don't need it
