### ISSUE TITLE
Delete ingest bucket

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#615]
They were associated to submissions that have been deleted:

s3://org-hca-data-archive-upload-prod/49bce4e2-2078-433e-987e-af7d11b97bb3/
s3://org-hca-data-archive-upload-prod/6d53a6ca-508a-4041-8af1-218199c71593/

**Comment by Wkt8** [comment]
The following bucket needs to be deleted:
s3://org-hca-data-archive-upload-prod/d73aad92-dc81-4616-b121-ef747bb44bf1/

**Comment by ipediez** [comment]
s3://org-hca-data-archive-upload-prod/f8536f94-cefb-4023-9b0a-9e9349d25b25/

**Comment by aaclan-ebi** [comment]
All directories were deleted.

I've made changes so that this will be automated when a submission is deleted (part of ticket: ebi-ait/dcp-ingest-central#629).

@ipediez @Wkt8 do you have this in an SOP somewhere? should we update it? Thanks!
