### ISSUE TITLE
Assign content descriptions to CGMs  

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#617]
**Context**
As a part of the effort to unify and standardise wrangling practices we are trying to agree on ontology terms for the different types of analysis files.
This ties in with the work that Irene has done #546

**Task**
In the last wrangling call we agreed to start the discussion by assigning ontology terms to the contributor generated matrices in this [spreadsheet](https://docs.google.com/spreadsheets/d/1XyDA1-4XfmJGvL4qzlkd_FZGfjNxrphVHwYwlmDWCD0/edit#gid=1423556856)
This should be done before the Wrangler Call (28/01/2022)

**Comment by MightyAx** [comment]
Is this needed?

**Comment by ofanobilbao** [comment]
@gabsie my read on this from Oversight call yesterday is that this can be considered done right?
