### ISSUE TITLE
Delete unused NCBI buckets

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#618]
**Description of the issue**
I noticed that we have over 20+ NCBI buckets, containing data. We should delete the buckets that we don't use.

Please note that we should keep the buckets that we are currently using (1 per wrangler)

**List of buckets**
- [x] s3://hca-ncbi-cloud-data-07062021
- [x] s3://hca-ncbi-cloud-data-08062021
- [x] s3://hca-ncbi-cloud-data-14042021
- [x] s3://hca-ncbi-cloud-data-140420212
- [x] s3://hca-ncbi-cloud-data-16032021
- [x] s3://hca-ncbi-cloud-data-17032021
- [x] s3://hca-ncbi-cloud-data-18032021
- [x] s3://hca-ncbi-cloud-data-ami-01032021
- [x] s3://hca-ncbi-cloud-data-ami-04082021
- [x] s3://hca-ncbi-cloud-data-ami-14052021
- [x] s3://hca-ncbi-cloud-data-ami-20092021
- [x] s3://hca-ncbi-cloud-data-ami-24052021
- [x] s3://hca-ncbi-cloud-data-ami-24052021-2
- [x] s3://hca-ncbi-cloud-data-ami-5
- [x] s3://hca-ncbi-cloud-data-ami-6
- [x] s3://hca-ncbi-cloud-data-ami-7
- [x] s3://hca-ncbi-cloud-data-ami1
- [x] s3://hca-ncbi-cloud-data-ami2
- [x] s3://hca-ncbi-cloud-data-ami3
- [x] s3://hca-ncbi-cloud-data-ami4
- [x] s3://hca-ncbi-cloud-data2

**Comment by ke4** [comment]
I deleted all of these S3 buckets as requested:

-  s3://hca-ncbi-cloud-data-07062021
-  s3://hca-ncbi-cloud-data-08062021
-  s3://hca-ncbi-cloud-data-14042021
-  s3://hca-ncbi-cloud-data-140420212
-  s3://hca-ncbi-cloud-data-16032021
-  s3://hca-ncbi-cloud-data-17032021
-  s3://hca-ncbi-cloud-data-18032021
-  s3://hca-ncbi-cloud-data-ami-01032021
-  s3://hca-ncbi-cloud-data-ami-04082021
-  s3://hca-ncbi-cloud-data-ami-14052021
-  s3://hca-ncbi-cloud-data-ami-20092021
-  s3://hca-ncbi-cloud-data-ami-24052021
-  s3://hca-ncbi-cloud-data-ami-24052021-2
-  s3://hca-ncbi-cloud-data-ami-5
-  s3://hca-ncbi-cloud-data-ami-6
-  s3://hca-ncbi-cloud-data-ami-7
-  s3://hca-ncbi-cloud-data-ami1
-  s3://hca-ncbi-cloud-data-ami2
-  s3://hca-ncbi-cloud-data-ami3
-  s3://hca-ncbi-cloud-data-ami4
-  s3://hca-ncbi-cloud-data2
