### ISSUE TITLE
Removal of fastq files from ingest prod. upload area

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#620]
Multiple fastq files require removal from the ingest prod. data upload area for this submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=13beb31c-1aa4-4355-9562-7e0fad2065b2
These files are shown as 'Draft' status.
Fastq files with 'valid' status should stay.

**Comment by ipediez** [comment]
@aaclan-ebi to share the PR and/or script

**Comment by aaclan-ebi** [comment]
PR for the script to remove files: https://github.com/ebi-ait/hca-ebi-dev-team/pull/424

**Comment by jacobwindsor** [comment]
@ami-day done!
