### ISSUE TITLE
Subsets of ILC3−ILC1-like cells generate a diversity spectrum of innate lymphoid cells in human mucosal tissues

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#624]
**Short name**
InnateLymphoidCells

**[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=f4d011ce-d1f5-48a4-ab61-ae14176e3a6e)**
**Publication**
Subsets of ILC3−ILC1-like cells generate a diversity spectrum of innate lymphoid cells in human mucosal tissues
https://www.nature.com/articles/s41590-019-0425-y

**Google Sheet**

with matrix:
https://docs.google.com/spreadsheets/d/11UWdLOj68AJ_akJLN8v3364_TqNLY91BmF8u__5Ndrc/edit#gid=177794954

no matrix:
https://docs.google.com/spreadsheets/d/1AOBAETE6XkG8XgHA5M582qPZnSHXroDQLoJxgJ4d4gU/edit#gid=177794954

**From the authors**
The chemistry was 3’ v2
single-cell fastqs were sent to us via their private upload area
They were unable to provide some donor metadata, they provided us with the disease status and development stage.
They were unable to provide a gene expression matrix and cell annotations file.

**Comment by ami-day** [comment]
Emailed the authors to ask ask about access to both raw fastq and gene expression matrix data. Also asked about the 10X technology version.

**Comment by ami-day** [comment]
Authors got back - they will send us the raw fastq and matrices, I will set up an aws transfer.

**Comment by ami-day** [comment]
Moving this to stalled. The donor metadata is not available in a public database or in the publication supplements. Need to ask the authors about this.

**Comment by ami-day** [comment]
upload area: 9269fde6-21ed-4c18-983d-e9d5b5dec37f

**Comment by ami-day** [comment]
Moving to stalled:
waiting to hear back from authors about some donor metadata.

**Comment by ofanobilbao** [comment]
@ipediez will secondary review this as soon as she finishes her current dataset

**Comment by Wkt8** [comment]
Irene will complete secondary review today

**Comment by ipediez** [comment]
I've noticed you entered some of the ontologies but not others. I've pointed out those that were not filled, just so you don't forget them

Project
- The estimated cell count is missing
- Project role ontology  is missing for you
- Maybe add in the description that the sc-RNAseq sequencing data is available upon reasonable request to the authors? That way if someone finds this dataset at HCA they can ask for the data if needed

Donor organism
- Genus species ontology is missing
- The development stage ontology is missing
- Age unit ontology is missing

Collection protocol
- Collection method ontology is missing

Specimen from organism
- Organ and organ part ontologies are missing

Cell suspension
- Genus species ontology is missing
- Selected cell types ontology is missing

Dissociation protocol
- You could add the publication DOI from where the protocol mechanical_dissociation_tonsils (10.1073/pnas.1005641107)
- Dissociation method ontology is missing

Enrichment protocol
- Check all the markers, they are badly formatted. Pay attention to the description of the field: Format as a space-delimited list of markers with +/- where + means enriched for and - means enriched against.  It should be space-delimited. For example, change NKp44+;CD196-;CD300LF-;CD103+ to NKp44+ CD196- CD300LF- CD103+

Library preparation protocol
- I would exclude the first sentence from the library_preparation_protocol_single_cell description, as it is not related with library preparation but with FACS sorting. The remaining description would be: "Single-cell RNA sequencing libraries were prepared with the 10x Genomics platform and 10X Genomics 3' v2 kit."
- Input nucleic acid molecule ontology is missing
- Nucleic acid source for library_prepration_protocol_bulk should be bulk cell
- SMARTER is a cDNA amplification library, not a library construction method. The library construction method can't be "smart-seq" for bulk rna sequencing, as it is a single cell technology. In GEO they state that RNA libraries were prepared for sequencing using standard Illumina protocols. I would use "illumina standard library construction" for the library construction method and cDNA library construction (EFO:0004187) for the ontology. 

Sequencing protocol
- The sequencing protocol for single cell is missing the sequencing protocol ID, name and description

Sequence files
- Please, remove all the files that the contributor sent to you. Keep only those files that are publicly available in a repository.

**Comment by ami-day** [comment]
Thanks @ipediez I have made these changes.
It is ready to validate in ingest now. Only potential problem is that, after removing the scRNA-seq fastq files, there is no scRNA-seq matrix, only bulk. I need to ask Natalia again if she has the single-cell matrices, and I'll also check the upload area where she sent me the data to double check.

**Comment by ami-day** [comment]
waiting to hear back from Tony about this (GDPR requirements)

**Comment by ami-day** [comment]
Going to submit this without the matrix file.

**Comment by ami-day** [comment]
Created a copy without a matrix file.

**Comment by ami-day** [comment]
requested sra objects from NCBI cloud delivery

baee61c0-c020-4ffa-adae-9df4c1f6fc75

**Comment by ami-day** [comment]
baee61c0-c020-4ffa-adae-9df4c1f6fc75

**Comment by ami-day** [comment]
Uploaded to ingest, need to sync the data files when I have them ready

**Comment by ami-day** [comment]
a00bb9e1-f062-4e55-b7c2-23e60f5d55a9

**Comment by ami-day** [comment]
synced fastq

**Comment by ami-day** [comment]
graph validating

**Comment by ami-day** [comment]
submitted.

**Comment by ami-day** [comment]
exported to DCP.

**Comment by ami-day** [comment]
I added the analysis protocol and analysis file tabs, with the relevant expression matrix, then imported the updated spreadsheet to the project in ingest. I encountered an error: https://contribute.data.humancellatlas.org/submissions/detail?uuid=522ee883-e3da-412f-a463-0112d2f2f63f&project=f4d011ce-d1f5-48a4-ab61-ae14176e3a6e

**Comment by ami-day** [comment]
We need to be able to create a new analysis file in order to upload the gene expression matrix file. I was able to add a new analysis protocol. I will create a ticket in development - new issues.

**Comment by Wkt8** [comment]
Alternatively, would this work by creating a new submission?

**Comment by Wkt8** [comment]
As this is already in metadata valid, we would not be able to create a new submission for it. Ami is willing to wait until the ticket in development to add a new file is prioritised.

**Comment by MightyAx** [comment]
I think you should be able to just add the file to the upload area:
 - provided that the upload area still exists and the submission is in a pre-exporting state (Draft, Metadata Valid).

Otherwise, a new submission to the existing project would be the "old-normal" way of handling this.

**Comment by ami-day** [comment]
@MightyAx the issue is with adding an Analysis file as a metadata entity to an existing submission, and then, like you said, we could just add the file to the upload area. I think the best approach would be to remove the changes/updates made (i.e. analysis protocol) and set the state back to exported (without exporting any changes). Then, create a new submission with the Analysis file added and submit that.

**Comment by ami-day** [comment]
Unfrotunately, I am not able to delete the Analysis protocol that was added recently: https://contribute.data.humancellatlas.org/submissions/detail?uuid=522ee883-e3da-412f-a463-0112d2f2f63f&project=f4d011ce-d1f5-48a4-ab61-ae14176e3a6e "It was not possible to delete Protocol: 5ff502a9-77c5-404a-80d9-740ccb870809. Unexpected server error"

**Comment by ofanobilbao** [comment]
Also this Project is missing you as a curator @ami-day. You need to update

**Comment by ESapenaVentura** [comment]
@ami-day to send @ESapenaVentura the spreadsheet used for update

**Comment by ofanobilbao** [comment]
Ami is showing up as part of the contributor list

**Comment by ami-day** [comment]
updated my role as data curator

**Comment by ESapenaVentura** [comment]
There are 4 entities to be added:
- An analysis file (Metadata)
- An analysis file (File)
- An analysis_protocol
- A process that links these entities (+ existing library prep protocol and sequencing protocol)

And 2 options to add them:
- Create a new submission:
   - Create a new submission with only analysis file, analysis protocol
   - Create a new process via the UI in the new submission
   - Link the old cell suspensions, old library and sequencing protocol, and new analysis file and analysis protocol manually through the UI

- In the old submission:
   - Upload the new analysis file to the hca-util upload area used previously
   - Modify the newly-created draft entity to match with the analysis file metadata (**MAY** need a dev to set up schema, not sure)
   - Add the new analysis_protocol and a new process and link everything together (library prep, sequencing prep, analysis_protocol, analysis_file)


The first option will also require a dev, as currently the status of the submission is metadata_valid
   - linking the cell suspensions

**Comment by ofanobilbao** [comment]
@ami-day this needs addressing and update pushed. No blockers

**Comment by ami-day** [comment]
Working on Option2.
Have synced the new analysis file to the s3 bucket.
Trying to modify the newly-created draft entity to match with the analysis file metadata - the UI gets stuck when I click "Edit" to edit the new Draft file. Have tried multiple times, and getting this same problem.

**Comment by ami-day** [comment]
> The UI gets stuck because the form the UI displays is based on the schema loaded via the `content.describedBy` field
> 
> The "draft" file does not have any `content` (As you can see if you inspect the metadata in the API), so it will need a dev

Will add this info to the ticket I just created in Ops. Thanks!

**Comment by ami-day** [comment]
Ticket: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/966

**Comment by ami-day** [comment]
Have submitted the updated version with analysis file.

**Comment by ami-day** [comment]
Exported. Submitted import form.

**Comment by ofanobilbao** [comment]
In Ami's absence, this looks good to me in the browser, so closing it
