### ISSUE TITLE
Ingest-Graph-Validator change for sequence file linked to cell suspension

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#626]
One of the ingest-graph-validator tests requires that a sequence file must be linked to a cell suspension. For Visium and imaging datasets, sequence files would be instead linked to an imaged_specimen. 

This is backed up by : 
- conversations with Sanger scientists who use Visium
- conversations with UCSC wranglers to use imaged_specimen 

Will be making a PR to make a change to [this ingest-graph-validator test](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/sequence_file_linkto_cell_suspesion.adoc) to include 'sequence file must be linked to a cell suspension OR imaged_specimen. 

PR here: https://github.com/ebi-ait/ingest-graph-validator/pull/64/files

**Comment by Wkt8** [comment]
![image.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/de44d6c1-e043-4095-bb64-bd11ab08f490)

**Comment by ipediez** [comment]
The PRs have been reviewed, @Wkt8 to check again

**Comment by Wkt8** [comment]
merged
