### ISSUE TITLE
Ingest project metadata update not working

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/hca-ebi-wrangler-central#627]
Trying to update the project-related metadata for this submission by spreadsheet doesn't seem to be working.
[Project: ancestryInfluencesImmuneResponse](https://contribute.data.humancellatlas.org/projects/detail?uuid=c211fd49-d980-4ba1-8c6a-c24254a3cb52)
[Submission](https://contribute.data.humancellatlas.org/submissions/detail?uuid=5086a4f1-51bf-4a52-903b-316ca3a429c2&project=c211fd49-d980-4ba1-8c6a-c24254a3cb52)

I wanted to flag it so you guys can test and see if it's only a problem with this project. I've added the spreadsheet with the changes to project tabs.
[GSE162632.xlsx](https://github.com/ebi-ait/hca-ebi-wrangler-central/files/7974971/GSE162632.xlsx)

**Comment by pnejad** [comment]
@aaclan-ebi following up on this issue

**Comment by aaclan-ebi** [comment]
@willrockout just to confirm the steps you did,
1. created the project
2.  uploaded a spreadsheet and checked the update project checkbox

Which project updates were you expecting to have been applied? Could you list them here? I've quick-scanned the info in the project in the system vs workbook, they seem identical. 🤔

**Comment by willrockout** [comment]
Sorry for the slow response, didn't get the notification. Yeah, that is the method Rachel and I tried to update the project info and it wasn't updating but it seems that it just took more time than expected. Might be good to have some kind of pop-up or label to say when a project is still updating. It wasn't like it was 30secs it was a decent amount of time with no change to the project metadata. We can close this ticket now though as the changes went through.

**Comment by aaclan-ebi** [comment]
Thanks @willrockout, that's a good point. I created a ticket in our product dev board https://github.com/ebi-ait/dcp-ingest-central/issues/672
