### ISSUE TITLE
contributor account for: LK

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#631]
Please create an account a contributor.

*Contributor details:*
* name: LK
* email: Luise.Seeker@ed.ac.uk

Request Details:
* Requested by: email

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by idazucchi** [comment]
@jacobwindsor and @amnonkhen to investigate missing permissions
