### ISSUE TITLE
contributor account for: Natalia Jaeger

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#637]
Please create an account a contributor.

*Contributor details:*
* name: Natalia Jaeger
* email: n.jaeger@wustl.edu

Request Details:
* Requested by: Ami, ami@ebi.ac.uk

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by ipediez** [comment]
@yusra-haider having problems with AWS keys, anyone to help (maybe @aaclan-ebi )

**Comment by yusra-haider** [comment]
created the account and sent contributor keys to @ami-day
