### ISSUE TITLE
2 graph validator errors blocking dataset submission

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#638]
I have uploaded a dataset with valid metadata to ingest prod. However, there are many graph validator errors:

1. There are 3 protocols linked to no entity and tagged with 'invalid graph = yes'. These protocols shouldn't be in the spreadsheet, can they please be deleted? I can't see an option to delete protocols currently. 

2. The fastq files are all uploaded and shown as valid, but something is going wrong with the linking in ingest. It is showing each cell suspension linked to only 1 sequence fastq file, whereas in the data tab it can be seen that all expected fastq files are present and valid.

**Submission:** https://contribute.data.humancellatlas.org/submissions/detail?uuid=13beb31c-1aa4-4355-9562-7e0fad2065b2

**Comment by Wkt8** [comment]
Could whichever dev who picks this up please time-track roughly how long it takes to complete (1.)? Would be really useful to know!

**Comment by aaclan-ebi** [comment]
@ami-day the linking in the spreadsheet has issues: 

<img width="1250" alt="Screenshot 2022-02-15 at 11 38 15" src="https://user-images.githubusercontent.com/31281398/154054916-f96c3035-68b0-4381-8886-975289980406.png">

You have to specify a process id if you want files to be included in the same assay process.

I'm afraid you'd have to delete this submission and reupload the files again. We dont have bulk updates of linking supported yet. :(

**Comment by ami-day** [comment]
Ohhh I see, i'll modify and re-upload and see if it fixes all the linking errors

**Comment by Wkt8** [comment]
Issue is fixed.
