### ISSUE TITLE
earlyHumanEmbryogenesisAtlas re-submission

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#641]
earlyHumanEmbryogenesisAtlas [url](https://contribute.data.humancellatlas.org/submissions/detail?uuid=386f32ec-6356-4db3-9ce0-a7e050957eee) was updated and needs to be re-submitted, but the submission is stuck in "complete". Can this same submission be re-exported?

**Comment by aaclan-ebi** [comment]
@ke4 and I will look into this first thing tomorrow!

**Comment by ke4** [comment]
@rachadele: We set the submission back to `Graph Valid`. When you would like to submit this submission again please check the `Submit only metadata to the Human Cell Atlas.` checkbox.

**Comment by idazucchi** [comment]
waiting for Rachel's feedback

**Comment by ofanobilbao** [comment]
Still waiting for Rachel's feedback

**Comment by ofanobilbao** [comment]
It's been exported
