### ISSUE TITLE
Metadata schema update - Add ontology to file_content_ontology.json

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#655]
We need an update on the metadata schema for the content_description field of files, so we can use the newly incorporated branch "information entity". 

**File to update:**
file_content_ontology.json

**Update to perform**
[Add Information Entity,  IAO:0000030 (EFO HCA subset)](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000030)

**Comment by ipediez** [comment]
"ontology": {
            "description": "An ontology term identifier in the form prefix:accession.",
            "type": "string",
            "graph_restriction":  {
                "ontologies" : ["obo:edam"**_, "obo:efo"_**],
                "classes": ["data:0006"**_, "IAO:0000030"_**],
                "relations": ["rdfs:subClassOf"],
                "direct": false,
                "include_self": false
            },
            "example": "data:3497; data:0863",
            "user_friendly": "Content description ontology ID"
        },

**Comment by Wkt8** [comment]
The relevant ticket in the metadata-schema repo is here: https://github.com/HumanCellAtlas/metadata-schema/issues/1450

**Comment by ESapenaVentura** [comment]
This ticket is not needed anymore

- [x] The term and its child terms have been added to the next HCAO release
- [x] The metadata schema update is in progress https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/695

Moving it to done :)
