### ISSUE TITLE
LineageRecordingOrganoids - Maynard

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#665]
### Project short name:
LineageRecordingCerebralOrganoids

### Primary Wrangler:
Ami

### Secondary Wrangler:
Enrique

### Associated files

* Google Drive: 
https://drive.google.com/drive/folders/1kH-8frvqedS1fIG4lZTYD7F1p886EXEQ

https://docs.google.com/spreadsheets/d/196Eggld87hqPLQ-44v1LTEbIp8BAySVj4aafs2-GAOk/edit#gid=1657302972

* Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=c4e11369-78d4-4d29-ba8e-b67907c4c65c

### Published study links

* Paper: https://www.nature.com/articles/s41592-021-01344-8
Preprint: https://doi.org/10.1101/2020.06.19.162032

* Accessioned data: E-MTAB-10971, E-MTAB-10972, E-MTAB-10973, E-MTAB-10974, PRJEB47710

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
@ebi-ait/hca-wranglers I think this dataset is not eligible? the iPSCs are CRISPR lines

**Comment by ofanobilbao** [comment]
I don't see any comment here as to if this was Eligible or not in the end. I'll move it to the bottom of the queue. It does not seem like anyone has started work on it, so we could even potentially close the ticket regardless and prioritise it when/if appropriate.

**Comment by ofanobilbao** [comment]
Also, appears as Eligible in Ingest, so if we think it is not we should reflect it in the status and the notes there.

**Comment by ESapenaVentura** [comment]
### Project - Contributors
- Gray and Barbara are missing the Principal Investigator project role

### Project - Publications
- On the PMID field, the PMC id is not accepted

### Donor
- Where did you find the donor information for the cell line? Just curious, I tried to search for it for a while and couldn’t find it

### Collection protocol
- Is there no collection protocol?

### Cell line
- I think the description of the 409b2-iCas9 cell line may be a bit big, I don’t think how it was obtained should be included. I think if you trim it down to the most notable features (iCRISPR inducible, iPSC, pluripotent, created to test scarring, etc)

### Enrichment protocol
- Markers should be separated with a space delimiter

### Imaging protocol
- I would add the manufacturer (Nikon T2i) to the microscope setup description

### Differentiation protocol
- Publication DOIs can’t be an array; I would choose the oldest one in which the protocols were defined (the original)

### Library preparation protocol
- Even though it was severely modified, I think the barcode and scar libraries should be considered 10x, according to the subsection in the methods `
- Alignment of single-cell transcriptomes and iTracer readouts`
### Sequencing protocol
- There can’t be more than one instrument per protocol so I would recommend splitting the sequencing protocols by sequencing instrument (for the 10x v2 and v3) and assigning each run the correct protocol
- Where did you get the information of the type of sequencing they did for the barcodes and scar? I could find some but I couldn’t find everything in the paper (e.g. sequencing method)

### Analysis protocol
- The first protocol is missing “normalization” in the derivation process
- For the visium protocol, I’d add a tiny bit more, for me the complete description would be: The resulting sequencing reads were aligned using Space Ranger for the regular Visium libraries (10x Genomics). S1 and S3 were automatically tissue aligned, whereas we manually annotated tissue-covering spots with Loupe Browser (10x Genomics) for S3. Spots not covering tissue were discarded manually in Loupe Browser (10x Genomics).
- Also for the visium protocol, it doesn’t look like they really processed it, so I would tag it as “raw matrix generation”?
- On the last protocol, they also did normalization, and I would add cell filtering and maybe ambient RNA correction (They did discard cells with more than 10% mitochondrial genes)

### Sequence files
The ontology for the content description is missing

### Ingest page
- Please fill out the admin area!

**Comment by ami-day** [comment]
Thanks @ESapenaVentura, done. The extra metadata I got came from Array Express and I found the cell line info. via a cell line provider online.

**Comment by ami-day** [comment]
Need to ask authors about assigned cell types

**Comment by ami-day** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=d6c14bf3-4232-4082-aa8b-cd1523360864&project=c4e11369-78d4-4d29-ba8e-b67907c4c65c

**Comment by ami-day** [comment]
syncing data files

**Comment by ami-day** [comment]
graph validating.

**Comment by ami-day** [comment]
Submitted.

**Comment by ofanobilbao** [comment]
@ami-day has the import form been completed? if so, please, move this ticket to exported, and change status in Ingest to Submitted. Thanks!

**Comment by ami-day** [comment]
I don't see this project in the HCA DCP Data Browser, to check with Ioane

**Comment by ami-day** [comment]
Looks good to me.
