### ISSUE TITLE
humanGastricCancerCells stuck in metadata validating status

### ISSUE THREAD

**Issue by ke4** [ebi-ait/hca-ebi-wrangler-central#667]

**Comment by ke4** [comment]
We re-triggered failed file validation for 11 files and waiting for their result.

**Comment by ke4** [comment]
According to the logs the validation started and never finished.
![Screenshot 2022-03-03 at 12.02.59.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/3325b749-b2d8-43f3-b2bb-3b7aeab4699c)

**Comment by ke4** [comment]
All the files are valid now and the submission status is `Metadata Valid`.

**Comment by ESapenaVentura** [comment]
@ke4 messaged @rachadele - Should be aware of this issue being resolved
