### ISSUE TITLE
ArrayExpress

### ISSUE THREAD

**Issue by LuluuuPvkp** [ebi-ait/hca-ebi-wrangler-central#674]
Hello community ! 

For our master's degree, with my team we have to prepare a R script in order to do an analysis of RNA seq.
This analysis covered a protein expression in different types of cancers.
The data we are trying to collect is here : 
[https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-9285/]
We want to use the R package "ArrayExpressHTS" in order to open RNAseq Data directly from ArrayExpress , but we found a problem with the package installation...

First we used this code to start installation : 
```
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("ArrayExpressHTS")
```
Then , this warning message appears : 
"In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘withr’ had non-zero exit status"

If I test with the package 'withr' turn in on, it seems that ArrayExpressHTS is installed
But when we try to open a dataset , by using this code : 
```
library("ArrayExpressHTS")
aehts <- ArrayExpressHTS("E-MTAB-9285")
```
this message appears : 
> library("ArrayExpressHTS")
Error in library("ArrayExpressHTS") : 
  aucun package nommé ‘ArrayExpressHTS’ n'est trouvé
> aehts <- ArrayExpressHTS("E-MTAB-9285")
Error in ArrayExpressHTS("E-MTAB-9285") : 
  could not find function "ArrayExpressHTS"

So my main question is : How to install the ArrayExpressHTS package ?
Maybe there is another package to use  in order to import data directly from ArrayExpress ?

PS : I'm sorry if this post does not belong here , it is my first post on git ..

Have a good day :)
Lucie

**Comment by ESapenaVentura** [comment]
Hi Lucy! Thanks for writing to our repo

However, even though we are based at the EBI as well, we are not part of the ArrayExpress (AE) team or its developers.

I have contacted some internal AE developers to ask them about this issue

They should come back with an answer at some point, so stay tuned!

Good luck with your issue :)

**Comment by ESapenaVentura** [comment]
Hi @LuluuuPvkp

I have been trying to contact the AE team but they are unsure of this library

If you could contact them via email to arrayexpress@ebi.ac.uk , they may be able to help you there

I'll close this ticket for now!

**Comment by LuluuuPvkp** [comment]
Hey!

Thank you a lot for these informations

Have a good day!

Le jeu. 10 mars 2022 à 11:33, ESapenaVentura ***@***.***> a
écrit :
