### ISSUE TITLE
Move documents to proper folders and re-structure repository

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#675]
**Description of the task:**
Currently, we have documents that are out of their respective folders and SOPs that are duplicated

- table.md : Deleted as it was redundant
- CITE-seq.png: Moved to `assets/images/technology_explanors/CITE-seq.png (And updated the references)
- docs/SOPs/Cgms_screenshot.png: Moved to `assets/images/matrix_screenshots/cgms_screenshot.png` (And updated references)
- docs/SOPs/hca_to_scea_tools_SOP.md: Merged with the SCEA guidelines and deleted the document. We only need 1 document about brokering to SCEA.
- 

**Acceptance criteria for the task:**
- [x] A list of the documents is redacted
- [x] A PR is created to change them

**Comment by ofanobilbao** [comment]
Wei and Amnon reviewed the PR. Leave it in Review for a while in case someone has any feedback. Moving to Don later today unless I hear otherwise
