### ISSUE TITLE
Triage "New" and no-status projects in ingest

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#684]
### Projects with no status

- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a72bed96-a4f7-401a-a67a-17b8a7357faf
   - Mystery dataset
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a815c84b-8999-433f-958e-422c0720e00d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=feb731dd-8acd-4270-b82c-f38bd5bf8e2b
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=b3938158-4e8d-4fdb-9e13-9e94270dde16
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=f71d4ab7-8115-4208-83b6-bf03dec07b74
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=8a40ff19-e614-4c50-b23b-5c9e1d546bab
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=d3446f0c-30f3-4a12-b7c3-6af877c7bb2d
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7880637a-35a1-4047-b422-b5eac2a2a358
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=71436067-ac41-4ace-be1b-2fbcc2cb02fa
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=d012d476-8f8c-4ff3-89d6-ebbe22c1b5c1
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=78b2406d-bff2-46fc-8b61-20690e602227
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=245a3a29-70df-471e-b3cf-c4a60207eda9
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=4ce06285-7aa3-4e3a-94e4-2e76b8b8f9a2
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7bcd7326-3181-40c2-b613-b93bfbcae70c
   - No publication?
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=5f7be735-1240-483f-986f-4fcc332e5e12
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=d96cc70a-a980-4cfc-af90-7b13af9bca61
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=76edd571-1d2b-4962-8967-4978089ee5e8
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=280204e6-b670-4419-bdaa-60714a6f6d5c
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7d69c575-0121-476e-a742-5a9d6db7da30
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=425f5327-25d0-4cf5-8e5b-c30a90cc2dcc
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a88f9bb8-8f6a-48f1-90ba-0483cf89c584
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=0b60d700-9a53-42a8-aa5e-fd30b4a850f3
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=f4c4d7ee-e773-41a5-ab7a-a8462a947b4c
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=06a48f80-76c9-4b9a-b308-463e9d6b089a
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=de9ba506-4a20-471c-8c51-5bc9b83a2cf7

### Status: New

- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=5c1a4406-14be-4290-a1a0-0ed5ef433101
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=957261f7-2bd6-4358-a6ed-24ee080d5cfc
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7d418c5f-79be-47ee-9f81-27366b8c5746
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7b17d499-77b8-4b48-aded-fe322beb8c43
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=5b171d7f-cd64-4181-887a-31acf2ce80ff
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=9288329e-0a0a-42f3-a7b7-61fa9cfb0600
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=72693161-e7c9-4dbd-9133-7952e675589a
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=5ceddf0e-c6f3-448a-a081-a12417593820
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7500049a-2ca5-46c6-b25f-28a9e9367a55
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=a81d7783-7659-4143-bef5-7e9a4f3865ca
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=7da6bb7b-69a1-40a5-b454-4a850c416abf

**Comment by ESapenaVentura** [comment]
The new list is a lot more manageable:

## No status
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=245a3a29-70df-471e-b3cf-c4a60207eda9
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=4ce06285-7aa3-4e3a-94e4-2e76b8b8f9a2
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=7bcd7326-3181-40c2-b613-b93bfbcae70c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=5f7be735-1240-483f-986f-4fcc332e5e12
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=d96cc70a-a980-4cfc-af90-7b13af9bca61
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=76edd571-1d2b-4962-8967-4978089ee5e8
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=280204e6-b670-4419-bdaa-60714a6f6d5c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=7d69c575-0121-476e-a742-5a9d6db7da30
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=425f5327-25d0-4cf5-8e5b-c30a90cc2dcc
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a88f9bb8-8f6a-48f1-90ba-0483cf89c584
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=0b60d700-9a53-42a8-aa5e-fd30b4a850f3
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=f4c4d7ee-e773-41a5-ab7a-a8462a947b4c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=06a48f80-76c9-4b9a-b308-463e9d6b089a
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=de9ba506-4a20-471c-8c51-5bc9b83a2cf7

**Comment by ESapenaVentura** [comment]
This should be done now.

As per March 10 2022, there should be no project in ingest with no status or status "new" _**that is not a SS2 integration test**_

**Comment by Wkt8** [comment]
@ESapenaVentura to create a separate ticket related to project catalogue status for the project in ingest.
