### ISSUE TITLE
Remove double pipe symbols from project metadata

### ISSUE THREAD

**Issue by theathorn** [ebi-ait/hca-ebi-wrangler-central#685]
**Description of the task:**

[Slack thread](https://humancellatlas.slack.com/archives/C01360XN04S/p1645840673788099).

Remove the `||` symbols from project metadata for:
  - https://data.humancellatlas.org/explore/projects/5116c081-8be7-49c5-8ce0-73b887328aa9 (updated metadata in dcp14)
  - https://data.humancellatlas.org/explore/projects/6f89a7f3-8d4a-4344-aa4f-eccfe7e91076 (new in dcp13)

For project `5116c081-8be7-49c5-8ce0-73b887328aa9` the issue is:
```
Collaborating Organizations: "Dana-Farber||Boston Children’s Cancer and Blood Disorders Center"
```

For project `6f89a7f3-8d4a-4344-aa4f-eccfe7e91076` the issue is:
```
project.contributors.laboratory: "Department of Oral Microbiology || Integrative Computational Bioscience (ICBS) Center"
```

The double-pipe symbols are causing "Manifests fail due to joiner in metadata" (https://github.com/DataBiosphere/azul/issues/3888).
This issue needs to be addressed soon as https://github.com/DataBiosphere/azul/issues/3911 will prevent these projects from being indexed.

**Acceptance criteria for the task:**
  - the double-pipe joiner is no longer present in project metadata
  - Azul is able to index and generate metadata manifests for these projects

**Comment by willrockout** [comment]
@theathorn 5116c081-8be7-49c5-8ce0-73b887328aa9 has been updated and exported. 6f89a7f3-8d4a-4344-aa4f-eccfe7e91076 I need ingest to kick to valid so I can export. @aaclan-ebi @jacobwindsor @amnonkhen can one of you do this?

**Comment by ESapenaVentura** [comment]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=f9520ef0-db4b-4b30-a372-c64f0e5e59b0&project=6f89a7f3-8d4a-4344-aa4f-eccfe7e91076 is ready @willrockout

**Comment by willrockout** [comment]
@theathorn both projects have exported. Parisa has brought up that you thought these changes could make it into this release is there anything we need to do to make that happen?

**Comment by theathorn** [comment]
OK to wait until dcp15.
