### ISSUE TITLE
Dataset stuck in exporting

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#686]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=e3569524-66b0-46e0-bbee-08e469d60fd4&project=99101928-d9b1-4aaf-b759-e97958ac7403

**Comment by aaclan-ebi** [comment]
My redeployment of ebi-ait/hca-ebi-dev-team#478 retried the exporting of these. This submission is now Exported.
