### ISSUE TITLE
contributor account for: Ayumu Tsubosaka

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/hca-ebi-wrangler-central#687]
Please create an account for a contributor.

*Contributor details:*
* Name: Ayumu Tsubosaka
* Email: tbskaym314731@gmail.com

Request Details:
* Requested by: William Sullivan

**Comment by Wkt8** [comment]
@willrockout can you please confirm here that the contributor has received and can use the account? Thanks!

**Comment by willrockout** [comment]
I've actually gotten no response from the contributor in regards to the account or spreadsheet.
