### ISSUE TITLE
Project catalogue - Detect duplicates catalogue/exported 

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#690]
**Description of the issue**
For some projects, there are duplicate project entries. One contains the information necessary for the catalogue, whereas the other contains the submission to the DCP. If the first is deleted before modifying the second, we loose information

https://contribute.data.humancellatlas.org/projects/detail?uuid=f8c3f4e9-7e12-482d-8d4b-fd5752118458&tab=project
https://contribute.data.humancellatlas.org/projects/detail?uuid=faeedcb0-e046-4be7-b1ad-80a3eeabb066&tab=project

**Comment by ESapenaVentura** [comment]
I have created a list based on title repetition; still WIP to check with other attributes (e.g. accessions)

- [ ] Pair 1:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=7bcd7326-3181-40c2-b613-b93bfbcae70c
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=8559a8ed-5d8c-4fb6-bde8-ab639cebf03c
- [ ] Pair 2:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=8559a8ed-5d8c-4fb6-bde8-ab639cebf03c
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=7bcd7326-3181-40c2-b613-b93bfbcae70c
- [ ] Pair 3:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=09c79b4c-4d18-43ac-8baf-9790378f2094
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=68df3629-d2d2-4eed-b0ab-a10e0f019b88
- [ ] Pair 4:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=68df3629-d2d2-4eed-b0ab-a10e0f019b88
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=09c79b4c-4d18-43ac-8baf-9790378f2094
- [ ] Pair 5:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=e56646ec-61fa-48ea-98d5-e0b793b0eb09
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=5bb1f67e-2ff0-4848-bbcf-17d133f0fd2d
- [ ] Pair 6:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=5bb1f67e-2ff0-4848-bbcf-17d133f0fd2d
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=e56646ec-61fa-48ea-98d5-e0b793b0eb09
- [ ] Pair 7:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=151f3c4b-42ef-44ac-9d1e-904e6835955f
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=a991ef15-4d4a-4b80-a93e-c538b4b54127
- [ ] Pair 8:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=a991ef15-4d4a-4b80-a93e-c538b4b54127
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=151f3c4b-42ef-44ac-9d1e-904e6835955f
- [ ] Pair 9:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=1e337cf3-de69-43f7-a372-e652aad67bf2
- [ ] Pair 10:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=1e337cf3-de69-43f7-a372-e652aad67bf2
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 11:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=5a54c091-79e9-4054-9e09-831b2893c5ee
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 12:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=573ccb0c-ef59-4658-8847-ffcffbfa3a00
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 13:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=6ffe87de-2251-4c18-9fb7-241feee526a2
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 14:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=13c21d3c-3af7-4685-bcaa-d4cb390c6bce
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 15:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=5ca08977-2b12-4161-9359-1b2ce7d331e9
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 16:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=566dbdff-af4e-468a-ace6-3996ed2f4b3a
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 17:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=c336c7b3-57f2-4f31-9f2d-3340425b78fa
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 18:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=69e43a37-dda7-4797-96cc-79d631ca196d
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 19:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=10734256-ad52-46c0-9af4-f4a1af79609b
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 20:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=37938c97-9c3a-4a61-8d93-021e6aee0356
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 21:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=4fb0924d-1660-43fb-a687-3bf46b2d4f48
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851
- [ ] Pair 22:
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=1bbe54e6-d127-4e65-9cec-90abb6b6ab33
	 - https://contribute.data.humancellatlas.org/projects/detail?uuid=04a72755-8ffa-4e01-9a67-63751c308851

**Comment by ofanobilbao** [comment]
I think we can move this ticket to Done as the work has been covered in a separate ticket. There might be still some scenarios that we have not checked for duplicates. But this should be enough for now I believe
