### ISSUE TITLE
Project catalogue - Submitted projects not in catalogue

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#691]
**Description of the issue**

There are 52 projects that have been submitted to the DCP have no entry in the project catalogue. We should try to add the missing details (organs, technologies, cell count, accessions) and set the flag to true.

The projects are as follow:

- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=faeedcb0-e046-4be7-b1ad-80a3eeabb066
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=3e329187-a9c4-48ec-90e3-cc45f7c2311c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=376a7f55-b876-4f60-9cf3-ed7bc83d5415
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e77fed30-959d-4fad-bc15-a0a5a85c21d2
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e526d91d-cf3a-44cb-80c5-fd7676b55a1d
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=414acced-eba0-440f-b721-befbc5642bef
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=3cfcdff5-dee1-4a7b-a591-c09c6e850b11
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8bd2e5f6-9453-4b9b-9c56-59e3a40dc87e
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=dbcd4b1d-31bd-4eb5-94e1-50e8706fa192
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=ad04c8e7-9b7d-4cce-b8e9-01e31da10b94
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=34cba5e9-ecb1-4d81-bf08-48987cd63073
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=b9484e4e-dc40-4e38-9b85-4cecf5b8c068
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8dacb243-e918-4bd2-bb9a-aac6dc424161
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=da2747fa-2921-42e0-afd4-39ef57b2b88b
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=dd7f2436-0c56-4709-bd17-e526bba4cc15
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8999b456-6fa6-438b-ab17-b62b1d8ec0c3
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=4af795f7-3e1d-4341-b867-4ac0982b9efd
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=79b13a2a-9ca1-42a4-97bd-70208a11bea6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=504e0cee-1688-40fa-b936-361c4a831f87
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=3c27d2dd-b180-4b2b-bf05-e2e418393fd1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a80a63f2-e223-4890-81b0-415855b89abc
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=602628d7-c038-48a8-aa97-ffbb2cb44c9d
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=65858543-530d-48a6-a670-f972b34dfe10
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8d566d35-d8d3-4975-a351-be5e25e9b2ea
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=783c9952-a4ae-4106-a6ce-56f20ce27f88
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=bd7104c9-a950-490e-9472-7d41c6b11c62
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=8559a8ed-5d8c-4fb6-bde8-ab639cebf03c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=f6133d2a-9f3d-4ef9-9c19-c23d6c7e6cc0
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=68df3629-d2d2-4eed-b0ab-a10e0f019b88
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=5bb1f67e-2ff0-4848-bbcf-17d133f0fd2d
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=54aaa409-dc28-48c5-be26-d368b4a5d5c6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c5ca43aa-3b2b-4216-8eb3-f57adcbc99a1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a991ef15-4d4a-4b80-a93e-c538b4b54127
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c31fa434-c9ed-4263-a9b6-d9ffb9d44005
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2084526b-a66f-4c40-bb89-6fd162f2eb38
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=38e44dd0-c3df-418e-9256-d0824748901f
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=591af954-cdcd-4839-96d3-a0d1b1e885ac
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c211fd49-d980-4ba1-8c6a-c24254a3cb52
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=65d7a168-4d62-4bc0-8324-4e742aa62de6
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=74493e98-44fc-48b0-a58f-cc7e77268b59
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=dd7ada84-3f14-4765-b7ce-9b64642bb3dc
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=4f17edf6-e9f0-42af-a54a-f02fdca76ade
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=f29b124a-8597-4862-ae98-ff3a0fd9033e
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=d6225aee-8f0e-4b20-a20c-682509a9ea14
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=065e6c13-ad6b-46a3-8075-c3137eb03068
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=78d7805b-fdc8-472b-8058-d92cf886f7a4
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=06c7dd8d-6cc6-4b79-b795-8805c47d36e1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=6f89a7f3-8d4a-4344-aa4f-eccfe7e91076
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=6663070f-fd8b-41a9-a479-2d1e07afa201
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=18e58437-76b7-4021-8ede-3f0b443fa915
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2c041c26-f75a-495f-ab36-a076f89d422a
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e255b1c6-1143-4fa6-83a8-528f15b41038
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=18d4aae2-8363-4e00-8eeb-b9e568402cf8
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2253ae59-4cc5-4bd2-b44e-ecb6d3fd7646
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=e993adcd-d4ba-4f88-9a05-d1c05bdf0c45
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=40ca2a03-ec0f-471f-a834-948199495fe7
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=a2a2f324-cf24-409e-a859-deaee871269c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=aff9c3cd-6b84-4fc2-abf2-b9c0b3038277
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=73769e0a-5fcd-41f4-9083-41ae08bfa4c1
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c7c54245-548b-4d4f-b15e-0d7e238ae6c8
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=aefb9192-43fc-46d7-a4c1-29597f7ef61b
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=77780d56-03c0-481f-aade-2038490cef9f
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=b733dc1b-1d55-45e3-8036-7eab0821742c
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=d138a114-7df5-4f7d-9ff1-f79dfd2d428f
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=c302fe54-d22d-451f-a130-e24df3d6afca
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=daa371e8-1ec3-43ef-924f-896d901eab6f
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=f4d011ce-d1f5-48a4-ab61-ae14176e3a6e
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=94e4ee09-9b4b-410a-84dc-a751ad36d0df
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=fccd3f50-cde2-47bf-8972-a293b5928aea
- [ ] https://contribute.data.humancellatlas.org/projects/detail?uuid=2eb4f5f8-42a5-4368-aa2d-337bacb96197

**Comment by ofanobilbao** [comment]
I think this has already been achieved through a different ticket so moving this to Done for now
