### ISSUE TITLE
GSE124395 - LiverCellAtlasHeterogeneity

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#694]
### Project short name:
LiverCellAtlasHeterogeneity 

### Primary Wrangler:
Ami

### Associated files

* Google Drive:
* https://docs.google.com/spreadsheets/d/1XwG0r35wRprCjAYl_TmRnDZgip9Pcro77ZEVb1hU0oU/edit#gid=2062586540

### Published study links

* Paper: https://www.nature.com/articles/s41586-019-1373-2

* Accessioned data: [GSE124395](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124395)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Need author information.

**Comment by ami-day** [comment]
Obtained info from authors (Nadim Aizarani)

**Comment by ami-day** [comment]
7706e2b2-4f83-48cf-bf4d-6814025a6787

**Comment by ipediez** [comment]
- Project:
	- Add as a supplementary link http://human-liver-cell-atlas.ie-freiburg.mpg.de/ as it includes interactive data exploration tools that might be useful for other researchers
- Protocols
	- You could add this Publication DOI doi.org/10.21203/rs.2.9620/v1 to the following protocols, as it includes detailed information for all the steps performed in this paper
		- dissociation_protocol_liver
		- all the FACS protocols
		- library_preparation_protocol
		- sequencing_protocol
- Analysis file
	- If the file GSE124395_celseq_barcodes.192.txt.gz contains cell barcodes, I would change the content description and ontologies to cell barcode (EFO:0010198). The current content description (sample ID) is defined as "Name or other identifier of an entry from a biosample database", whereas cell barcode is defined as "A short nucleotide sequence that is added during a single cell library preparation to identify reads from an individual cell."

**Comment by ami-day** [comment]
Thanks @ipediez I have made these changes.

**Comment by ami-day** [comment]
data files are syncing to ingest

**Comment by ami-day** [comment]
submitted.

**Comment by ami-day** [comment]
exported to hca dcp

**Comment by MightyAx** [comment]
R16 ReExport Successful

**Comment by ESapenaVentura** [comment]
Looks fine in the browser
