### ISSUE TITLE
dataset problem - fetalLiverAndCordBloodCiteSeq - missing links when reusing a protocol

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#699]
**Dataset this task is for:**
fetalLiverAndCordBloodCiteSeq

- project uuid - `04ad400c-58cb-40a5-bc2b-2279e13a910b`
- [link to browseHCA data portal](https://data.humancellatlas.org/explore/projects/04ad400c-58cb-40a5-bc2b-2279e13a910b)
- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=04ad400c-58cb-40a5-bc2b-2279e13a910b)

**Relevant People**
- Wrangler: Ida
- dev

**Description of the problem with the dataset**
This dataset has a first submission, already exported to the DCP. I prepared a second submission to integrate the missing data reusing the collection protocol. I referenced it using the UUID from the 1st submission, the spreadsheet is [here](https://docs.google.com/spreadsheets/d/1RU-KtREX6CDc1Skvi_Sji30JOfsM8sFB/edit?usp=drive_web&ouid=113452802627011629126&rtpof=true).
The processes that were meant to use the existing protocol turned out completely empty: no input, output or protocol.

I tried to reuse an existing protocol in staging as well and the same thing happened

**Acceptance criteria for the task:**
- [ ] the issue is investigated
- [ ] the cause of the missed linking is found

**Comment by aaclan-ebi** [comment]
It seems that the linking didn't finish but I couldn't see older logs. I'm uncertain why it didn't finish the submission. I'm trying to reupload the submission.

**Comment by amnonkhen** [comment]
@alegria to file a bug ticket on the dev board

**Comment by aaclan-ebi** [comment]
@idazucchi after graph validation there were errors about:

`* For human donors' development stage, please use terms within the HSAPDV ontology`

I think you need to do some metadata changes, first. But the linking issues should be fixed. Please let me know if you need anything else to submit this dataset.

Thanks!

**Comment by idazucchi** [comment]
@aaclan-ebi thank you!
the linking is correct and I fixed the ontology term issue
