### ISSUE TITLE
Cellxgene - Assess candidates for next dataset

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#700]
**Description of the task:**
In order to continue developing the cellxgene data flow, we need more candidates to test our tools and improve in our processes to wrangle to cellxgene

The person that works on this task will probably need to pair with @Wkt8 to make sure that the datasets selected make sense.

The dataset needs to abide to the following requirements:
- The dataset has been wrangled to the DCP
- The dataset must not already be in cellxgene
- The dataset must contain Raw count matrices that can be split by cell suspension (Not sure about this one)
- The dataset must contain cell type annotations
- The dataset must contain umap/tsne coordinates

**Acceptance criteria for the task:**
- [x] A dataset (Or a few) are selected
- [ ] The dataset ticket(s) is/are re-opened and is properly labelled

**Comment by Wkt8** [comment]
https://docs.google.com/spreadsheets/d/1ppZpCaOoyckCx2BqCuzS6Vu0itRQgyZc/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true

DCP projects with h5ad files are here. Needs checking to see if all of the required files are available. Use https://docs.google.com/document/d/1UVGIllybmEI46x22NSDpMNRywT3c8hcGrcw6opiHdbg/edit#heading=h.eykizmfvo5ve in conjunction to check!

**Comment by Wkt8** [comment]
Updated https://docs.google.com/spreadsheets/d/1ppZpCaOoyckCx2BqCuzS6Vu0itRQgyZc/edit?rtpof=true&sd=true and sent this spreadsheet to Brian (CxG) and Jason (Lattice) to cross-reference and prevent duplication of work.

**Comment by ESapenaVentura** [comment]
Avoid anything in the covid cell atlas

**Comment by Wkt8** [comment]
Prioritised list: https://docs.google.com/spreadsheets/d/183QnUgiiHJGUP1UMLKbMQ-zBV6qQAJGekkCogeGJfa0/edit#gid=0

**Comment by prabh-t** [comment]
@Wkt8 to double check list.
