### ISSUE TITLE
Retract hindlimb dataset from ENA

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#710]
WIP

**Comment by ke4** [comment]
Enrique is going to discuss it with others.

**Comment by ofanobilbao** [comment]
@ESapenaVentura has emailed ENA to retract the dataset

**Comment by prabh-t** [comment]
Enrique has a reply and will check.

**Comment by ESapenaVentura** [comment]
Dataset has been retracted until Dec 2022
