### ISSUE TITLE
LongitudinalMultiomicsCovid19

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#715]
### Project short name: 
LongitudinalMultiomicsCovid19

### Primary Wrangler:
@ami-day 
### Secondary Wrangler:
Ida

### Associated files

* Google Drive:

https://drive.google.com/drive/folders/1Ch87hzthnKx6LkWF52kZ9YTabjQvA0EI

https://docs.google.com/spreadsheets/d/1mX6Hzo5jCJ2ylZT1KW87IzS6eEadjfrUQIPGb9vRmNE/edit#gid=893924004

* Ingest: https://contribute.data.humancellatlas.org/submissions/detail?uuid=3f5bba2d-5886-4512-a831-7e873601a8e2

### Published study links

* Paper: https://doi.org/10.1016/j.immuni.2020.11.017

* Accessioned data: bulk RNA-seq (GSE161777), scRNA-seq (managed EGA, to confirm accession), preprocessed (https://beta.fastgenomics.org/p/565003)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Asked Jason if this is a Lattice dataset - For now we'll move it to the stalled list until we get a response

**Comment by prabh-t** [comment]
Enrique to check accessions in Ingest.

**Comment by Wkt8** [comment]
It is not a lattice dataset so we can wrangle it!

**Comment by ESapenaVentura** [comment]
Stalled due to priorities, will come back to it once I finish the priority datasets

**Comment by ami-day** [comment]
b38aff01-8804-40a6-b1e4-0ca06028343c

**Comment by ami-day** [comment]
data files are syncing

**Comment by ami-day** [comment]
graph validating.

**Comment by ami-day** [comment]
@idazucchi @ESapenaVentura Because the release deadline is approaching, I have submitted this project, and will update the submission in response to the secondary review once it's done.

**Comment by idazucchi** [comment]
Hi @ami-day, I'm close to done with the review and I think that we should not ask for the dataset to be imported.
I disagree with the modelling, in particular with the number of donors, specimens and cell suspension. 
If you agree with my modellling and want to update the project I don't think that those changes can be made with an update because it would require to delete donors and that's not supported

**Comment by ofanobilbao** [comment]
As a note, to add to the issues specified above, the project is stuck in Exporting as well

**Comment by ami-day** [comment]
> Hi @ami-day, I'm close to done with the review and I think that we should not ask for the dataset to be imported. I disagree with the modelling, in particular with the number of donors, specimens and cell suspension. If you agree with my modellling and want to update the project I don't think that those changes can be made with an update because it would require to delete donors and that's not supported
> 
> If you have already sent an import request we should ask for the project to be removed from the R18 manifest

OK no problem, I had decided not to send the import form, and to wait until you got back with review. I was hoping I would be able to make changes to the project in ingest if possible, but sounds like I might need to delete the submission so I can edit it and re-upload it. I'll message on slack, I'm not sure I agree that the modelling is incorrect but happy to talk about this and see, then make changes if needed.

**Comment by ami-day** [comment]
Made updates and re-uploaded a new submission. Data files are syncing.

**Comment by ami-day** [comment]
Thanks @idazucchi , i made the relevant updates and have re-submitted the submission. Data files are syncing.

**Comment by ami-day** [comment]
Complete status

**Comment by ami-day** [comment]
Looks ok in data broswer.
