### ISSUE TITLE
SARS-CoV-2 receptor networks in diabetic and COVID-19-associated kidney disease

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#717]
### Associated files

* Google Drive:

* Ingest:https://contribute.data.humancellatlas.org/projects/detail?uuid=8319c26c-6fb5-40cb-b511-f50f10bf05a7

### Published study links

* Paper:https://doi.org/10.1016/j.kint.2020.09.015

* Accessioned data: http://nephrocell.miktmc.org

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ipediez** [comment]
@ipediez to email the authors to ask about where the data (raw or pre-processed) is available for download

**Comment by idazucchi** [comment]
this could be a Lattice project, I'm checking with Jennifer

**Comment by idazucchi** [comment]
It is funded by the Seed network but Jennifer gave us the green light to wrangle it

**Comment by ami-day** [comment]
> It is funded by the Seed network but Jennifer gave us the green light to wrangle it

@idazucchi it looks like there is no raw data or expression data available, therefore I think it is inegligble for HCA DCP. Did Jennifer give any info about where to get the data?

**Comment by ofanobilbao** [comment]
@ami-day Why has this moved to stalled?

**Comment by ESapenaVentura** [comment]
This is an HCA publication, data is not available but whoever takes this dataset should try to contact the authors.

If the authors do not answer, then mark as ineligible in ingest and close the ticket

**Comment by idazucchi** [comment]
the [preprint](https://www.medrxiv.org/content/10.1101/2020.05.09.20096511v2.full) Data access section states
> LD single cell data sets are searchable at NephroCell.miktmc.org. Owing to ethical considerations, privacy protection concerns, and to avoid identifying individual study participants in vulnerable populations, the Institutional Review Board of the National Institute of Diabetes and Digestive and Kidney Diseases has stipulated that individual-level gene expression and genotype data from the American Indian DKD study cannot be made publicly available. A dynamic user-friendly interface at HumanBase (hb.flatironinstitute.org/covid-kidney) is available for researchers to explore the functional networks of gene expression signatures

This decision is not explicitly reported in the final version of the paper, but the links provided only allow visualisation of the data, no download.

Since no data is available I will close this ticket, mark the project inelegible in ingest but leave the paper in the HCA catalogue
