### ISSUE TITLE
A single-cell and single-nucleus RNA-Seq toolbox for fresh and frozen human tumors.

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#719]
### Project short name:
FreshFrozenHumanTumours

### Primary Wrangler:
Ami

### Secondary Wrangler:
Irene

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1EZONxSWvdqrdUZU4Hn4CMLPEOVBgCtX6

* Google Sheet: 
https://docs.google.com/spreadsheets/d/1mUt7-zupyi_4rk0XGnqrutQJd1LjjmUkmBVyXBJrBGc/edit#gid=1612993960

* Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=5850583c-baec-4427-8656-cd3c96c07727

### Published study links

* Paper: https://doi.org/10.1038/s41591-020-0844-1

* Accessioned data: GSE140819 and phs001983

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Requested ontology term for specimen collection process: https://github.com/HumanCellAtlas/ontology/issues/108

**Comment by ami-day** [comment]
Have sent the authors an email to get some clarifications.

**Comment by ipediez** [comment]
LGTM, good job on this project! I just have three small comments:

**Project:**

- Add the estimated cell count. They stated it in the abstract of the paper, therefore it's also available in the project description in ingest.

**Donors:**

- Why do donors MGH123 and HTAPP-443-SMP-5491 have two different development stages? According to https://tumor-toolbox.broadinstitute.org/ HTAPP-443-SMP-5491 is pediatric and I can't find the information for MGH123

**Specimen from organism:**

- Some of the organs are set as "waiting to hear from author". Did you get a response from the authors?

**Comment by ami-day** [comment]
graph validating

**Comment by ami-day** [comment]
Submitted.

**Comment by Wkt8** [comment]
Exported.

**Comment by ESapenaVentura** [comment]
Looks ok in the browser, however:

The project is duplicated in ingest. The actual project + submission is here https://contribute.data.humancellatlas.org/projects/detail?uuid=a62dae2e-cd69-4d5c-b5f8-4f7e8abdbafa and it's missing:
- technology info
- organ info
- flag to be in catalogue
- admin info


I will add them for now to move from here but please stop creating duplicate projects, use the ones existing

**Comment by ESapenaVentura** [comment]
Actually, it was missing publication PMID and doi so I would rather update it

**Comment by ESapenaVentura** [comment]
Moving to needs update: as stated in this message https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1660584420081069 the ontology_label terms for `lung` and `blood` need to be changed to lowercase

**Comment by ami-day** [comment]
Made update to lung, blood, ovary labels (upper case to lower case)

**Comment by ami-day** [comment]
Submitted.

**Comment by ami-day** [comment]
Form submitted.

**Comment by ami-day** [comment]
looks ok
