### ISSUE TITLE
Fix index and review technology explanors

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#720]
**Description of the issue**
Recently, a PR was merged to master referring to the work on ticket https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/237

However, this PR was not reviewed after the changes and it has led to a couple of issues.

The index on the left of the [git pages](https://ebi-ait.github.io/hca-ebi-wrangler-central/) displays all the new documents and some hyperlinks are broken.

This needs revision and a new PR fixing these issues.

**Acceptance criteria**
- [x] A PR has been created with the issues addressed
- [x] The PR is reviewed **successfully** by at least some other person and merged to master

**Comment by ESapenaVentura** [comment]
Add typical graphs for each type of technology

**Comment by ofanobilbao** [comment]
Some issues. But most of the fixes have been done by @Wkt8 already

**Comment by Wkt8** [comment]
Fixed. The pages have been restructured.

**Comment by Wkt8** [comment]
@ESapenaVentura to take a quick look.

**Comment by ESapenaVentura** [comment]
https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/981/files I have created a quick PR fixing some visual issues I found

Other than that, LGTM!

**Comment by Wkt8** [comment]
Merged.
