### ISSUE TITLE
Update documents with new archiving constraints

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#721]
**Description of the task**
As a data wrangler, I'd like to give clear instructions on times and expectations when archiving a dataset for a contributor. In order to keep good track and offer the best experience whilst not putting the burden on the wrangler to remember, the data will be held for a set amount of time (e.g. 2 years, TBD) and will go public after that.

**Acceptance criteria**
- [x] The documents to modify are identified
- [x] A PR is created to modify the documents
- [x] The PR is approved and merged into master
- [ ] Modify Best Practice document

**Comment by ESapenaVentura** [comment]
PR for the first document is here: https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/722

**Comment by prabh-t** [comment]
Enrique and ops to have a meeting on the 3 documentation tickets today, and will aim to make progress on at least 2.

**Comment by Wkt8** [comment]
Have added the paragraph about only holding data for 2 years (and communicating this to the contributor) to the best practices document. 

Wranglers to review if they would be interested: (https://docs.google.com/document/d/1mz5HJ9-Irr9NOHMNZYV5xt5fwsasdULO2rrllwfFyN4/edit#)

**Comment by Wkt8** [comment]
Teamwork makes the dream work @ESapenaVentura
