### ISSUE TITLE
dataset problem - HumanBCellsTonsils

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#723]
**Dataset/group this task is for:**

- project uuid - `24d0dbbc-54eb-4904-8141-934d26f1c936&`
- [link to browseHCA data portal](https://data.humancellatlas.org/explore/projects/24d0dbbc-54eb-4904-8141-934d26f1c936&)
- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=24d0dbbc-54eb-4904-8141-934d26f1c936&tab=project)

**Relevant People**
- Wrangler: Ida
- Contributor
- dev

**Description of the problem with the dataset**
This dataset has a first submission that was exported to the DCP.
I submitted a second spreadsheet reusing protocols and cell suspensions for an update. 
This caused the first submission to go back to metadata valid.

Due to some linking errors I had to delete the second submission but I am now unable to re-upload the second spreadsheet because of the first submission status.

**Acceptance criteria for the task:**
Is the exported submission moving back to metadata valid the desired behaviour?
If yes: 
- [ ] change the submission status of the first submission back to exported
If no:
- [ ] open a ticket in the dev board to tackle the issue

**Comment by prabh-t** [comment]
@idazucchi cannot upload update spreadsheet because submission state is Exported. Change state back to Valid? @aaclan-ebi @prabh-t

**Comment by Wkt8** [comment]
Waiting for the blocking ticket 'linking to previous entities doesn't work in spreadsheet import' and then Alegria will manually change state of the submission. @ESapenaVentura to have a look for preexisting feature ticket.

**Comment by MightyAx** [comment]
Alegria to look at today.

**Comment by aaclan-ebi** [comment]
The first submission is now set to Exported so @idazucchi could try reuploading the new spreadsheet for the second submission.

**Comment by MightyAx** [comment]
@idazucchi to try reuploading the new spreadsheet for the second submission.

**Comment by idazucchi** [comment]
I uploaded the spreadsheet without issues, I think this ticket can be closed since the underlying issue has already been addressed
