### ISSUE TITLE
Update documentation regarding GDPR

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#727]
**Description of the issue**
As a data wrangler, I'd like to have wrangler and user-facing detailed instructions on what data can be shared with the DCP and what are our restrictions so that I can guide users and provide with clear data deposition indications. 

**Acceptance criteria**
- [ ] The wrangler documentation has been updated with detailed bullet points describing the possible cases and how to proceed
- [ ] A user facing document is created and reviewed by all wranglers (And @gabsie )
- [ ] That document is reflected in the project catalogue
- [ ] That document is reflected in the Data Portal 'Contribute' page

**Comment by Wkt8** [comment]
Wranglers + Gabs having a meeting today.

**Comment by ipediez** [comment]
PR to review: https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/731

**Comment by ipediez** [comment]
Discussion between Tony and Gabs, we need to update our documentation. We need an expansion of information about our data policy, @ipediez to work on this and @gabsie to provide with relevant information

**Comment by gabsie** [comment]
Extra info to be supplied by Gabs on rules for data..

**Comment by ipediez** [comment]
PR reviewed and approved, adding new information based on [the ticket 753](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/753)
