### ISSUE TITLE
Make sure MS/Unaffected brain study is ready for ENA

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#73]
**Dataset/group this task is for:**
https://github.com/HumanCellAtlas/hca-data-wrangling/issues/130 - Unaffected/Multiple Sclerosis brain

**Wrangler responsible for this dataset/lab:**
@ESapenaVentura 

**Description of the task:**

The dataset indicated in the first section has their data already stored in EGA. After talking with the contributors, this dataset belongs to the public domain and the data can be publicly relased.

Nonetheless, this implies a couple of issues with EGA. Data can't be stored both in ENA and EGA, and therefore I have contacted EGA to see if they have any SOP we could follow regarding this release. The dataset is already referenced in a paper and should not lose the accession.

After a couple of emails, there is a way we can set up pointers so that anyone looking for the data referenced in the paper would be redirected to ENA. Before that, we need to set up a couple of points:

- [x] Contact Anna Williams to ask for confirmation that her team would be ok with this.
- [x] Archive data in ENA
- [x] Contact Matthieu again to begin with the re-direction process.

**Acceptance criteria for the task:**

- [x] The data is publicly shown in ENA
- [x] Searching for the data in EGA/with an EGA accession will redirect the user to the ENA submission

**Comment by ESapenaVentura** [comment]
Submisssion with latest metadata and data files uploaded:

https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=38449aea-70b5-40db-84b3-1e08f32efe34

**Comment by ESapenaVentura** [comment]
Submission has been archived but the data is still not showing in ENA:

- Study accession: ERP122827

Following actions:

- [ ] Fill in the metadata sheet with the provided accessions
- [ ] Send an email to EGA telling them about the data being archived
- [ ] Check on monday if the data is publicly available

**Comment by ESapenaVentura** [comment]
Data is publicly available.

An email has been sent to EGA to begin with the redirection process

**Comment by ESapenaVentura** [comment]
Sent a follow-up email to check how is the process going

**Comment by lauraclarke** [comment]
@ESapenaVentura is this is just waiting for the EGA to do the last update, is it okay if we move this to review QA?

**Comment by ESapenaVentura** [comment]
@lauraclarke Yes, I will move it to QA. 

So far I have not received any answer to my email

**Comment by ESapenaVentura** [comment]
Looking in the EGA-archive webpage (https://ega-archive.org/search-results.php?query=EGAS00001003412) I see that looking for this dataset actually redirects to the ENA webpage.

What is the difference between ega-archive and normal ega? (e.g. https://www.ebi.ac.uk/ega/datasets/EGAD00001004544)

In the first it is redirected, in the second it isn't
