### ISSUE TITLE
Review (and Update) Ingest Project Statuses

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#733]
**Review the Projects In Progress in Ingest and Update if needed:**

All wranglers to review their In Progress datasets in Ingest, and update if needed to Submitted or Stalled, or even back to Eligible if not working on them.

**Acceptance criteria for the task:**

All wranglers have gone through their In Progress projects in Ingest and updated their statuses when required.

- [ ] Enrique
- [ ] Ami
- [ ] Wei
- [ ] Irene
- [x] Ida

**Comment by idazucchi** [comment]
we are tracking this in the regular tasks
