### ISSUE TITLE
Single-nucleus cross-tissue molecular reference maps to decipher disease gene function.

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#738]
**Collection/dataset this task is for:**

- file name - all of them 
- link to existing collection in cellxgene"
- ticket link to DCP wrangling ticket (if available)
- link to ingest UI: https://contribute.data.humancellatlas.org/projects/detail?uuid=31887183-a72c-4308-9eac-c6140313f39c
- link to DCP: https://data.humancellatlas.org/explore/projects/31887183-a72c-4308-9eac-c6140313f39c/project-matrices

**Relevant People**
- Wrangler
- Contributor
- dev

### Associated files
* [SOP](https://docs.google.com/document/d/1UVGIllybmEI46x22NSDpMNRywT3c8hcGrcw6opiHdbg/edit#)
* [Knowledge Sharing Drive](https://drive.google.com/drive/folders/1cIgfeZZaoo2mFo2mN9iZ00_MZt94mvLv)
* [Ingest-cellxgene-submitter](https://github.com/ebi-ait/ingest-cellxgene-submitter) 
* [Cellxgene-schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md)
* [Cellxgene-schema-validate](https://github.com/chanzuckerberg/single-cell-curation)
* [Cellxgene-submit-collection](https://cellxgene.cziscience.com/?curator=true)

### Published study links

* Paper: https://www.biorxiv.org/content/10.1101/2021.07.19.452954v1.full
https://www.gtexportal.org/home/singleCellOverviewPage 
https://singlecell.broadinstitute.org/single_cell/study/SCP1479/single-nucleus-cross-tissue-molecular-reference-maps#study-download

* Accessioned data:

### Key Events

- [x] Collect necessary matrix, cell-type annotation, and embedding files
- [x] Modified var layer to meet cellxgene schema (adding feature_is_filtered)
- [x] Created/Modified raw.var to meet cellxgene schema
- [x] Modified obs layer to meet cellxgene schema 
- [x] Created uns layer to meet cellxgene schema
- [x] Ensured obsm layer is present
- [x] Created h5ad with processed component parts using AnnData
- [x] Created h5ad with raw matrix and raw var using AnnData
- [x] Filtered ENSEMBL IDs from annotated and raw matrix
- [x] Combined processed and raw h5ad to one h5ad object
- [x] Run [cellxgene-schema validate](https://github.com/chanzuckerberg/single-cell-curation)
- [ ] Secondary review (?) 
- [x] Submitted to collection in [cellxgene](https://cellxgene.cziscience.com/?curator=true)

**Comment by ipediez** [comment]
Uploaded to CellxGene, but having conversion issues when uploading on their data portal's end. Waiting on that

**Comment by prabh-t** [comment]
Wei needs to send an email to the contributor to inform them.

**Comment by Wkt8** [comment]
Modified and reuploaded. Now waiting for Jason's feedback.
