### ISSUE TITLE
Bug during dataset import: imaging probe

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#739]
I am getting an error when importing an imaging dataset in ingest. It is saying that the imaging probe related fields should be an array and that I have input string values. However, they should not be an array, also according to the schema. Could a dev please look into this?

https://contribute.data.humancellatlas.org/submissions/detail?uuid=69b17dc8-6615-4dac-9d99-ebaa746c7d6f

https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/624ee6beb06b223527d5ac46/submissionErrors

**Comment by aaclan-ebi** [comment]
Hi @ami-day , The probe property of the imaging_protocol 

(https://schema.humancellatlas.org/type/protocol/imaging/11.4.0/imaging_protocol) schema is an _array of objects_ . 
```
"probe": {
"description": "Information about each probe in the imaging experiment.",
"type": "array",
"items": {
"$ref": "https://schema.humancellatlas.org/module/protocol/1.1.1/probe"
},
"user_friendly": "Probe"
}
```

There should be a separate "module" worksheet for this. The worksheet name should be "Imaging protocol - Probe" and it should contain the imaging_protocol.protocol_core.protocol_id and imaging_protocol.probe.* columns. I'll send you the correct version of your spreadsheet for you to check.

**Comment by ami-day** [comment]
Thanks for solving this @aaclan-ebi , I think you're right. I made the changes and the metadata is in the validating state

**Comment by aaclan-ebi** [comment]
@ami-day  I've deleted all the duplicate projects with project short name `GSE171668_SingleCellAndSpatialAtlasCovid` and retained the ff project as it has wrangling notes https://contribute.data.humancellatlas.org/projects/detail?uuid=0061c7e8-7b90-4296-be53-ca1de3bd6651

I'm uploading the spreadsheet you gave me on slack. Please review the project metadata.

**Dev notes:**
It is very expensive to delete the submissions as there are so many linkings. I've decided to delete the entities associated with the submission directly in the db by doing the ff queries using the submission mongo object id:

```
db.submissionManifest.deleteMany({"submissionEnvelope" : DBRef("submissionEnvelope", ObjectId("62443828b06b223527d3594f"))})

db.biomaterial.deleteMany({"submissionEnvelope" : DBRef("submissionEnvelope", ObjectId("62443828b06b223527d3594f"))})

db.protocol.deleteMany({"submissionEnvelope" : DBRef("submissionEnvelope", ObjectId("62443828b06b223527d3594f"))})

db.file.deleteMany({"submissionEnvelope" : DBRef("submissionEnvelope", ObjectId("62443828b06b223527d3594f"))})

db.process.deleteMany({"submissionEnvelope" : DBRef("submissionEnvelope", ObjectId("62443828b06b223527d3594f"))})

db.submissionError.deleteMany({"submissionEnvelope" : DBRef("submissionEnvelope", ObjectId("62443828b06b223527d3594f"))})
```

This should be safe iff there is only 1 unsubmitted(not Exported/Archived) submission under the project.

After doing the queries, delete the submission and project via UI manually.

**Comment by aaclan-ebi** [comment]
The spreadsheet importing is in progress. Here's the link to the created submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=a2707e51-7ec2-49db-a63f-6831b8f27b94

**Comment by aaclan-ebi** [comment]
Now awaiting data file upload @ami-day
