### ISSUE TITLE
Prepare talk + poster for ISB biocuration conference

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#740]
**Description of the issue**
For the ISB UK-local Biocuration conference that is going to be held on the Genome Campus, I have been invited to give a talk:

>During the Data Standards and Ontologies (FAIR) session the organising committee would like you to give a talk with the title: The role of validation in data curation - a Human Cell Atlas Data Coordination Platform case study. Your talk with be in the Morning Thursday 5th May and you have been assigned a 12 minute slot. Please keep to time as we would like the audience to have an opportunity to ask questions at the end of your talk.

I have also been invited to present a poster if I want. 

I need to prepare the talk and have it reviewed

**Acceptance criteria**
- [X] A decision has been reached about the poster
- [x] The talk slides have been prepared
- [x] The talk slides have been reviewed
- [x] The slides are sent to Dr Rachael Huntley

**Comment by Wkt8** [comment]
Enrique is preparing the poster and talk - and will send for review on the HCA slack channel. Please review!
