### ISSUE TITLE
Dataset stuck in validating state

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#742]
My dataset has been stuck in "metadata validating" state since Friday morning. I think there is something wrong. It would be great to get this unstuck so it makes it for the April release.
https://contribute.data.humancellatlas.org/submissions/detail?uuid=8e463a3e-08f5-4afe-8267-5a637d1b5cfd&project=005d611a-14d5-4fbf-846e-571a1f874f70

**Comment by aaclan-ebi** [comment]
@ami-day There was an issue in validating one process. I wasn't sure what caused this. I triggered a draft event to revalidate it by changing the process id and undoing the changes. That set's the submission to Metadata Valid. I've proceeded to trigger the graph validation.


**Dev notes: (for future reference)**

It should be possible to see the metadata doc id in the state machine in the state tracker https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/624d876bb06b223527d4c091/documentSmReport 

Steps I did:
1. I checked the state tracker endpoint from `documentSmReport` link in the submission _links and I found the id `624d884cb06b223527d4cc84`  is still Validating in the state tracker.

2. I tried to find the entity type of the id by trial and error 

Tried accessing the document's resource in Ingest API :

https://api.ingest.archive.data.humancellatlas.org/biomaterials/624d884cb06b223527d4cc84
https://api.ingest.archive.data.humancellatlas.org/files/624d884cb06b223527d4cc84

and finally found that it's a process

https://api.ingest.archive.data.humancellatlas.org/processes/624d884cb06b223527d4cc84

I am uncertain why the valid event didn't get received/processed by the state tracker.

3. I updated it via UI, and revert the changes

4. It was revalidated and that set the overall submission state to _Metadata Valid_

**Comment by aaclan-ebi** [comment]
The submission is now in _Graph Validating_ state .

**Comment by rachadele** [comment]
I'm having the same issue with submission AtlasOfSubstantiaNigraInPD– would it be possible to do the same fix for that one?

**Comment by aaclan-ebi** [comment]
@ami-day I'm setting back the first submission of this project to _Exported_ to upload the new spreadsheet you gave me on slack. https://contribute.data.humancellatlas.org/projects/detail?uuid=005d611a-14d5-4fbf-846e-571a1f874f70

**Comment by aaclan-ebi** [comment]
The [spreadsheet](https://docs.google.com/spreadsheets/d/1iF0JnTjk89UxZ6HJAu42CdzaXvyfleKPYsLaYjSZNBA/edit#gid=75746301) is now being imported to the submission : https://contribute.data.humancellatlas.org/submissions/detail?uuid=dc0828c4-2d46-4313-b408-e69e4c7ccd33

**Comment by aaclan-ebi** [comment]
Now awaiting data file upload @ami-day
