### ISSUE TITLE
Dataset stuck in validation

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#744]
I'm having the same issue as https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/742#issuecomment-1095389637 with url https://contribute.data.humancellatlas.org/submissions/detail?uuid=d93b2db4-42f5-4127-a85a-935849f76a9e. The dataset is stuck in "metadata validating state". Would it be possible to do the same fix?

**Comment by aaclan-ebi** [comment]
@rachadele There were 6 files that were stuck in Validating. 3 of them succeeded but failed in being set to Valid. I've manually set them to valid. I couldn't find any logs for the other 3 files so I've retried the 3 files for validation and they are valid. The submission state was set to _Metadata Valid_ so I proceeded in triggering the graph validation. The submission is now in _Graph Validating_. Hopefully, when you see this message, it's already Graph Valid, or if there are errors, you can check the errors right away.
