### ISSUE TITLE
Modify documentation for new ZH columns

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#746]
**Description of the task:**
Changes to the ZH board:
- A new column "CellxGene" has been added
- The column "Finished" has been renamed to "Exported in DCP"

We need to reflect this in our [documentation](https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/docs/SOPs/dataset_wrangling_SOP.md)

**Acceptance criteria for the task:**

- [x] The documentation has been updated

**Comment by ESapenaVentura** [comment]
It's a very small change so I am considering this can be done directly on master without supervision. Let me know if anyone has any concern

**Comment by idazucchi** [comment]
this is already in master, I'm closing this ticket
