### ISSUE TITLE
Sten Linnarsson - Mouse Nervous System

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#75]
Very old description of the dataset and comments can be found here: https://github.com/HumanCellAtlas/hca-data-wrangling/issues/207

BUT the study is now published here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6086934/ (with detailed donor/sample metadata in the supplements).

Here is the latest metadata spreadsheet:
https://docs.google.com/spreadsheets/d/1RU3BHNee-8T2p-4OxVqmb1xLd14R_216/edit#gid=720818644

Status:
There was missing information in the publication methods/supplementary metadata so I emailed the authors.
This dataset is quite complex, as some samples are pooled from a mix of mouse donors, while others are not. Some missing information can be inferred from their supplements, but some can't.
The authors got back saying the mouse strain when missing is mixed.
They are also got back to say that where the adult donor ids associated with particular samples are missing, it is because they are unsure which adult mice were used for these samples.
The authors are also unsure about which 10X version (v1 or v2) was used for which samples.
The metadata sheet is complete apart from these few issues and ontologies are not yet filled.
The raw data is in bam format and getting the fastq files requires discussion with the developers.

**Comment by ami-day** [comment]
@lauraclarke Wrangling this dataset was stalled because there was missing mouse donor information for a small number of samples. We should likely still wrangle the samples where the sample metadata is complete but another reason why it was stalled was: the 10X version used varied across samples (v1 or v2) but it is not clear which 10X version maps to which sample. My understanding is that we need the 10X version info. for the data associated with each sample to be correctly processed? Does this mean we cannot continue wrangling this particular dataset for HCA? What do @ESapenaVentura, @mshadbolt and/or @rays22 think about this? If it is not suitable I will close the ticket, and if we think we can still wrangle it I will assign myself to this ticket.

**Comment by lauraclarke** [comment]
Did you try and get the sample to 10x version assignment from the lab and they said the couldn't provide it?

It would be worth asking the pipelines team how much of a blocker this is, what would the consequences of it all being treated as V2 from an analysis perspective?

**Comment by lauraclarke** [comment]
Also, should it be closed or should it be put int he blocked columm

**Comment by ami-day** [comment]
> Did you try and get the sample to 10x version assignment from the lab and they said the couldn't provide it?
> Yes, I emailed them and they were not able to provide it.
> It would be worth asking the pipelines team how much of a blocker this is, what would the consequences of it all being treated as V2 from an analysis perspective?
Ok, I'll message them on slack and see. I haven't encountered any 10X v1 datasets yet, I'm not actually sure what the different would be in terms of the UMI length and positions. I'll see what they say.

**Comment by lauraclarke** [comment]
@ami-day did these issues get resolved?

Do you think this ticket should be moved to either stalled or closed entirely?

**Comment by ami-day** [comment]
@lauraclarke I am closing this ticket. The pipelines team need to know whether the version was v1 or v2, due to different cell barcode lengths, so some of the samples cannot be processed. The dataset also consists of transgenic mouse samples so is not a high priority for us.
