### ISSUE TITLE
SOP - Inform the contributors after wrangling

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#752]
To increase community engagement, we should send an email after wrangling any dataset from a publication or repository (GEO). After verifying the wrangled dataset is live on the Data Portal, we should inform about it to the contributors. 
Add a new template email: after verifying a dataset is live on the Data Portal, we should inform the original contributors of the dataset. A good practice would be to ask them for feedback and to join the conversation on slack.

**Comment by idazucchi** [comment]
closing this because it's a copy of #753
