### ISSUE TITLE
Cellxgene Retro Actions

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#756]
**Description of the task:**

This ticket is for capturing documentation and consolidation actions from the wrangling-to-cellxgene retro on 19/04/22. 

- [ ] Use ingest-cellxgene-submitter to track jupyter and python notebooks for cellxgene work
- [x] Consolidated a general and template python notebook for creating h5ad files
- [x] Added basic comments and explanations to the python notebook
- [x] Edited Cellxgene Wrangling SOP with appropriate changes
- [ ] Edited Wrangling Workflow to include wrangling to Cellxgene and requesting for Cellxgene-rquired files
- [ ] Example files for submission to cellxgene 
- [x] Ticket made for Tools made by jacob are modules that can be imported to Jupyter 

**Acceptance criteria for the task:**

- Folders and readme established for storing jupyter and python notebooks
- Template python notebook setup for any wrangler to download, edit, and use 
- Individual use cases added in markdown, headings and subheadings added to the notebook
- Wrangling Workflow includes asking for cellxgene files
- Contributor communication includes email templates to send to contributor to inform them about cellxgene wrangling 
- Example files with a readme available in a folder in the github repo

**Comment by gabsie** [comment]
This has had progress already.
