### ISSUE TITLE
Evan Macosko - Human brain cell-type variation for GA

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#76]
Description and comments for this dataset can be found here: https://github.com/HumanCellAtlas/hca-data-wrangling/issues/115

Status: The metadata is complete and was uploaded to ingest. Postponed archiving until fixes for multiple sequencingRuns per sequencingExperiment are deployed on the archiver or we decide to do a workaround.

**Comment by ESapenaVentura** [comment]
- Data and metadata uploaded
- 7 Files pending validation
- DSP submission URL: https://submission.ebi.ac.uk/api/submissions/bfee68f6-5f3a-46d7-ac40-a0bd6c1a3640
- Ingest submission URL: https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?uuid=85196817-5785-40a3-b1d7-dd6980611bd2&project=8a67ddef-4990-4403-89e4-c650ae0964f8

**Comment by ESapenaVentura** [comment]
**Update**:

- Everything is ready to finish the submission

- I have tried to trigger the completion of the submission in ingest both to a request to the endpoint `https://archiver.ingest.archive.data.humancellatlas.org/archiveSubmissions/<dsp_submission_uuid>/complete` and following the instructions in the ingestion to archives document but it's not changing the status in DSP or the status in ingest. I could finish it manually but I'll wait until @aaclan-ebi comes back to work tomorrow.

**Comment by aaclan-ebi** [comment]
There was an error on this one because this was submitted prior the latest archiving changes. I'll take a look tomorrow!

**Comment by aaclan-ebi** [comment]
@ESapenaVentura The change to track DSP entities in Ingest is not backwards compatible atm. I think the easiest way to get accessions is to just submit it directly to DSP. And update the accessions using update submission. 

I believe we would still want to track those entities in Ingest. I will create a ticket to be able to do a migration for archive submission and its archive entities documents in the database for DSP submissions which were submitted before that  change is released.

**Comment by aaclan-ebi** [comment]
Please don't do the update submission yet. There's a current issue in the update submissions in the UI anyway.

 I see two cases that we need to handle and requires design:

1. How to export DCP datasets which have updates (new accessions) ? Some of those new accessions were already stored in Ingest.

2. New datasets which were archived prior the archiver support for storing accessions in Ingest. Those have accessions but the accessions may not have been put back to Ingest yet.

**Comment by lauraclarke** [comment]
What are the outstanding issues with this dataset?

**Comment by aaclan-ebi** [comment]
I've created this issue to be able to put back the accessions in Ingest entities.

**Comment by lauraclarke** [comment]
Thanks @aaclan-ebi 

To clarify, are there three datasets which fall into this category 
This one and the following?
https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-wrangler-central/18
https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-wrangler-central/17

**Comment by aaclan-ebi** [comment]
Yup. that is correct @lauraclarke !

**Comment by ESapenaVentura** [comment]
Part of the data is currently archived: [GSE126836](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126836)

We'll have to delete the submission (In both DSP and Ingest) and create the submissions with 2 separate spreadsheets (That I am working on) 

Summary of the current approach is:
1. Submission A: Submit data and metadata for non-archived data (Locus coeruleous and some substantia nigra). Untick "Export" in this submission.
1. Submission B: Submit data and metadata for archived data (Substantia Nigra data). Untick both "Archiving" and "Export".

I'll need a dev (@MightyAx ?) to help me delete the current submission, as it's in "Archiving" state

**Comment by ESapenaVentura** [comment]
I have divided the spreadsheets, now there are 2:
- `_archiving`: With the entities to archive
- `_exporting`: with the archived entities

**Comment by ESapenaVentura** [comment]
- New DSP submission ID: `bef5f9c6-7809-4024-a855-8fcd2a816015`

- Current status: File archiver jobs are running.
- Additional notes: Used the same directory. Deleted previous data files (I estimated the time it would take me to map older bam filenames with new bam filenames instead of running the conversion jobs was not worth it).

**Comment by ESapenaVentura** [comment]
The dataset is ready for export.

The second submission has been successfully made and the data files are in ingest now!

**Comment by ofanobilbao** [comment]
@ESapenaVentura just moved this to Finished on the wrangling board as I believe that from DCP perspective this is exported and archived, is that correct? Feel free to move it where it belongs on the DCP or archiving journey if I didn't get it right. Thanks!
