### ISSUE TITLE
Add Cell Count - Lung_Fibroblasts

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#764]
**Make sure Cell Count is both in Ingest and Staging area**

### Need to export 
Cell count is present in ingest, but no cell count is present in staging area docs
- https://contribute.data.humancellatlas.org/projects/detail?uuid=b4a7d12f-6c2f-40a3-9e35-9756997857e3

### Fixing steps
The metadata for the files has been deleted from ingest. Since this was already imported, we need to keep the UUIDs, so we need to reconstruct the metadata from the staging area. The steps I will follow are:

- [x] Download the descriptors and sequence_file metadata from the staging area
- [x] Create a script to map the fields from both entities into the metadata file entity
- [x] Post those newly created entities in ingest for the submission 
- [x] Verify everything looks correct
- [x] Re-validate and re-export

**Acceptance criteria for the task:**

- [x] Cell count is present in ingest

**Comment by ami-day** [comment]
For some reason, when I updated the project, the sequence files are all now invalid. I think this project quite a while ago, and that might be something to do with this problem: https://contribute.data.humancellatlas.org/submissions/detail?uuid=d8bcfa5a-d8a7-4dd0-8953-3c3bafdbf87e&project=b4a7d12f-6c2f-40a3-9e35-9756997857e3

**Comment by amnonkhen** [comment]
@idazucchi will look into this

**Comment by idazucchi** [comment]
I'm wondering if it's the same issue as [find ticket](url).
I've tried to edit the metadata for one file to trigger again validation. If it's the same problem than an error message will be displayed which gives us a clue to see what is wrong.
The file in draft since 13,00pm Friday 27. I'll check on Monday, I'm worried it's stuck
- i

**Comment by idazucchi** [comment]
The files are invalid because they are missing! @ami-day can you try to upload them again? This should solve the problem

**Comment by ami-day** [comment]
The problem is that the fast file names have '.' inside the name before the file .fastq.gz suffix. I have downloaded and re-imported the spreadsheet with edited file names, now I will re-download, rename and sync the relevant fast.gz files.

**Comment by ami-day** [comment]
@ESapenaVentura and @Wkt8 will have a look

**Comment by ESapenaVentura** [comment]
All metadata for the files was deleted.

The file metadata needs to be reconstructed from the staging area and programmatically added to ingest. 

I am not entirely sure how we will perform this but this is necessary as this project won't be able to be updated otherwise

**Comment by ESapenaVentura** [comment]
I will take over reconstructing the project

Once reconstructed, you can update as usual. I will keep us updated through here

As a note, unless we are specifically dropping entities, please **never delete metadata from an exported submission**. UUIDs are regenerated randomly when a new entity is created and we need to keep the UUID and other vital information (dcpVersion for example) for downstream processing

**Comment by ami-day** [comment]
Ok thanks for looking into this @ESapenaVentura, I guess the better alternative would have been to first delete the incorrectly named fastq files programatically in ingest, **and then** edit the file metadata, specifically renaming the files with "-" instead of ".", **and then** sync the newly named files?

**Comment by ESapenaVentura** [comment]
I think I managed to create a script to re-create the files - I am going to test in staging

**Comment by ESapenaVentura** [comment]
I have tried with [this](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=04dc92a5-f4fb-46e2-a5f7-f57bb38557ad) submission in ingest.

It worked as intented, it's raising a file validation error but I think that's because I point to a prod file within a staging submission.

I will proceed to add the files to ingest prod [real submission](https://contribute.data.humancellatlas.org/submissions/detail?uuid=d8bcfa5a-d8a7-4dd0-8953-3c3bafdbf87e&project=b4a7d12f-6c2f-40a3-9e35-9756997857e3)

**Comment by ESapenaVentura** [comment]
first file passed validation, the rest got stuck in validating

**Comment by ESapenaVentura** [comment]
Actions for today:
- [ ] Delete the current file metadata
- [ ] Re-upload metadata with actual filenames
- [ ] Re-upload files with actual filenames
- [ ] Check for checksums - May need to add them manually, hopefully hca-util will trigger the jobs
- [ ] re-validate graph and re-export

**Comment by ESapenaVentura** [comment]
Currently working on the first point, started renaming by calling
```
aws s3 ls s3://hca-util-upload-area/014cb6bb-0a41-4d2d-9b8e-9034f4248cda/ | awk '{if($4){t=$4; gsub(/_/, ".", t);print "aws s3 mv s3://hca-util-upload-area/014cb6bb-0a41-4d2d-9b8e-9034f4248cda/" $4 " s3://hca-util-upload-area/014cb6bb-0a41-4d2d-9b8e-9034f4248cda/" t }}' | xargs -I{} sh -c "{}"
```

**Comment by Wkt8** [comment]
Enrique - reminder to create and link to a product dev ticket for removing the ability to delete files from the UI

**Comment by ESapenaVentura** [comment]
When uploading the files after creating metadata without the `cloudUrl`, checksums are generated normally

Files are currently validating. Had an issue with 2 file metadata entities missing, may try a workaround (delete those 2, add, upload file again)

**Comment by ESapenaVentura** [comment]
File metadata looks correct - Checksums have been regenerated

I have manually added the linking based on a cell suspension - filename match

Metadata is valid now

**Comment by ESapenaVentura** [comment]
The staging area seems fine, I have checked the file descriptors/sequence file metadata, and it looks fine. The only weird thing I noticed is that the provenance is set up to the date of creation of the entity, 2022, but I really hope that is not an issue

The project metadata has been updated with the cell count as well (original purpose).

**Comment by ESapenaVentura** [comment]
Import form sent - Everything should be in order now.

**Comment by ESapenaVentura** [comment]
[Scripts](https://app.zenhub.com/files/261790554/e1f00a3d-b23a-4be8-84bf-a3768022036b/download)

[Metadata from staging area + ingest metadata generatd](https://app.zenhub.com/files/261790554/172d1518-7864-4e7c-983d-4c315b3c8c7d/download)
