### ISSUE TITLE
Add Cell Count to DCP1 Project

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#765]
**Make sure Cell Count is both in Ingest and Staging area:**

No staging area

This dataset is a DCP1 dataset, so it's not stored in the normal staging area. Need to manually check

`2043c65a-1cf8-4828-a656-9e247d4e64f1`

**Acceptance criteria for the task:**

Cell Count is added and available for the browser team to pick up when they have implemented the cell count estimate

Steps moving forward:
- [x] Ensure project schema is up to date (>=17.0.0)
- [x] Move submission back to metadata valid (using script in repo, https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/restart-submission)
- [x] Run script to add file metadata (size/content type) https://github.com/ebi-ait/dcp-ingest-central/issues/793
- [x] Ensure metadata is valid (Currently a lot of validation errors relating ontologies... seems weird)
- [x] Export
- [x] Extra steps after export (Delete metadata about files, file descriptors, links.json)
- [x] Fill out import form for release 23

**Comment by amnonkhen** [comment]
related to ebi-ait/dcp-ingest-central#793

**Comment by ESapenaVentura** [comment]
Steps moving forward:
- [ ] Ensure project schema is up to date (>17.0.0)
- [ ] Move submission back to metadata valid (using script in repo, https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/restart-submission)
- [ ] Run script to add file metadata (size/content type) https://github.com/ebi-ait/dcp-ingest-central/issues/793
- [ ] Ensure metadata is valid (Currently a lot of validation errors relating ontologies... seems weird)
- [ ] Export
- [ ] Extra steps after export (Delete metadata about files, file descriptors, links.json)
- [ ] Fill out import form for release 23

**Comment by ESapenaVentura** [comment]
The metadata is invalid, which is something I need to look into

I have started running the script to add file metadata.

It's going to take a while, since it needs to do 3466 requests. Once finished, I will post the log here

I will investigate into what type of metadata errors the submission has

**Comment by ESapenaVentura** [comment]
Validation errors:

### Biomaterials
- Provided term is not child of [http://purl.obolibrary.org/obo/UBERON_0000465] at .model_organ.ontology
- Provided term is not child of [http://purl.obolibrary.org/obo/UO_0000003,http://purl.obolibrary.org/obo/UO_0000149] at .timecourse.unit.ontology


### Files
- Validation request failed

### Thoughts
- The validation errors seem to all be related to either the model organ (embryo, in this case) and the term (day). I think this is a case in which the ontology moved around and, when re-validating, the values were not corrected. I will apply a patch while I think.

<details>
<summary>
Code used to detect errors
</summary>

```python
from hca_ingest.api.ingestapi import IngestApi
api = IngestApi('https://api.ingest.archive.data.humancellatlas.org/')
biomat = []
for bio in api.get_entities('https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/5cdb0344d96dad000858fff4', 'biomaterials', 'biomaterials'):
    biomat.append(bio)
errors = []
[errors.extend(bio['validationErrors']) for bio in biomat]
errors = [e['userFriendlyMessage'] for e in errors]

errors = list(set(errors))
for e in errors:
    print(e)
```

**Comment by ESapenaVentura** [comment]
I discovered the error in the unit ontology

This dates back to when it was first ingested, the ontology service did not work for some time and it completely flew under our radar

This dataset had a dropdown issue, so in timecourse, where it states the timecourse unit ontology, it was rolled down (000038 --> 0000039, etc etc). The correct value should be https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUO_0000033, which is the one corresponding to day. the values in between 00000033 and 0000037 are detected as valid because they are valid identifiers in the ontology, but they are not valid values to refer to day

Need to fix this.

Code for discovery:
```python
### Unit error: are all the errors the same?
unit_error = [bio for bio in errored_biomat if bio['validationErrors'][0]['userFriendlyMessage'] == 'Provided term is not child of [http://purl.obolibrary.org/obo/UO_0000003,http://purl.obolibrary.org/obo/UO_0000149] at .timecourse.unit.ontology']
values = [bio['content']['timecourse']['unit']['ontology'] for bio in unit_error]
unique_values = list(set(values))
print(len(unique_values))
713
```
713 unique values in ontology ID but same ontology_label, which is what made me think of this

**Comment by ESapenaVentura** [comment]
I've had to patch every single cell suspension, as all of them -1 (1732) had this issue

The other error is a file error; I don't know how to fix it, but since it involves the data files, I will skip it for now.

I will set the submission to graph-valid and export it

**Comment by ESapenaVentura** [comment]
The submission is exporting

**Comment by ESapenaVentura** [comment]
Export failed; apparently, there is a date missing (That is what I can make up from the following log)

```
"2022-11-07 20:34:47,388 - TerraExperimentExporter - ERROR - submission_uuid:0948a727-228f-4cfc-857e-6243c6aed08d - export_job_id:63696ad633904466861ed113 - project_uuid:2043c65a-1cf8-4828-a656-9e247d4e64f1 - strptime() argument 1 must be str, not None\n"
```

Will investigate further

**Comment by Wkt8** [comment]
Continuing to investigate the export error - and then will try to relaunch the exporter. 
There's a script that will restart the submission - do this instead of moving the submission back to the graph-valid state. @MightyAx to update with alternate method of relaunching.

**Comment by MightyAx** [comment]
There are 1,732 export error messages in the error queue. 
![Screenshot 2022-11-08 at 10.03.25.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/d473a0df-604d-43fe-b5d5-912fc329e588)

These can be retried by moving them to the main export queue.

Example Message:
![Screenshot 2022-11-08 at 10.05.40.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/2c45134e-8a08-47dc-bf62-430540daa938)
```
{
  "exportJobId": "63696ad633904466861ed113",
  "documentId": "5cdb03c6d96dad0008591b22",
  "documentUuid": "e1e8bc40-c320-4abe-aeae-ec7b076f18ff",
  "callbackLink": "/processes/5cdb03c6d96dad0008591b22",
  "documentType": "process",
  "envelopeId": "5cdb0344d96dad000858fff4",
  "envelopeUuid": "0948a727-228f-4cfc-857e-6243c6aed08d",
  "projectId": "5cdb0348d96dad000858fff6",
  "projectUuid": "2043c65a-1cf8-4828-a656-9e247d4e64f1",
  "index": 1,
  "total": 1733,
  "context": null
}
```

**Comment by MightyAx** [comment]
Error queue purged, enrique to re-export

**Comment by ESapenaVentura** [comment]
Currently exporting, so far 1 hour into the export but expected (Large amount of entities), also checking logs with this query:
`{container="ingest-exporter"} |~ "0948a727-228f-4cfc-857e-6243c6aed08d"`

shows a healthy log, with no errors.

**Comment by ESapenaVentura** [comment]
Exporting logs have finished generating (Yesterday around 16:42) 

However, the submission is still exporting, so I think it's stuck

**Comment by ESapenaVentura** [comment]
Exported (Thanks @MightyAx !)

only last 2 steps left

**Comment by ESapenaVentura** [comment]
Done
