### ISSUE TITLE
Add Cell Count - HumanHepatocyteDifferentiation

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#766]
**Make sure Cell Count is both in Ingest and Staging area**

Add cell count and export

https://contribute.data.humancellatlas.org/projects/detail?uuid=074a9f88-729a-455d-bca5-0ce80edf0cea

**Acceptance criteria for the task:**

- [x] Cell count is present in ingest

**Comment by ami-day** [comment]
The estimated cell count is present in the project metadata.

**Comment by ami-day** [comment]
graph validation requested.

**Comment by ami-day** [comment]
Submitted metadata only.

**Comment by yusra-haider** [comment]
dataset stuck in exporting, needs dev intervention

**Comment by Wkt8** [comment]
This has been exported and set to exported.
