### ISSUE TITLE
Add Cell Count - DopaminergicNeuronDifferentiation

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#767]
**Make sure Cell Count is both in Ingest and Staging area**

Add cell count and export

https://contribute.data.humancellatlas.org/projects/detail?uuid=20f37aaf-caa1-40e6-9123-be6ce8feb2d6

**Acceptance criteria for the task:**

- [x] Cell count is present in ingest

**Comment by ami-day** [comment]
This project has as estimated cell count

**Comment by ami-day** [comment]
graph validating

**Comment by ami-day** [comment]
Submitted.
