### ISSUE TITLE
Reconstruct dataset - KidneyOrganoidsBioprinting

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#775]
**Make sure Cell Count is both in Ingest and Staging area**

Add cell count and export

https://contribute.data.humancellatlas.org/projects/detail?uuid=8787c238-89ef-4636-a57d-3167e8b54a80

**Acceptance criteria for the task:**

- [x] Cell count is present in ingest

**Comment by ami-day** [comment]
I added the cell count.
The submission needs updating so that the process ids associated with the sequence files are the run accessions as opposed to the experiment accessions. I made these changes in ingest by downloading, editing then reimporting the spreadsheet, but I understand that ingest is not able to update submissions where the linkings of files to process ids has changed. Here is the project, now in graph invalid status: https://contribute.data.humancellatlas.org/submissions/detail?uuid=2552985f-707a-46dd-bf8a-3c88721d8109&project=8787c238-89ef-4636-a57d-3167e8b54a80

**Comment by gabsie** [comment]
@idazucchi please get in touch with @ami-day if you think this is possible.. and leave a note here what the outcome is.

**Comment by ami-day** [comment]
Investigating with @idazucchi now. We seem to be able to add new biomaterials or processes in ingest staging and not in ingest production, we have asked the devs if it was pushed to production. 
If we go down this route, it will take some time to add all the new process ids manually, link them to the sequence files, and delete the incorrect process ids i.e. to update the dataset manually. Ideally we could do this in bulk via spreadsheet import. As we discussed earlier, I will create a ticket in dev for bulk updates be made possible in this way.

**Comment by idazucchi** [comment]
the add process button is now displayed correctly in ingest and the linking issue can be addressed

**Comment by ke4** [comment]
@ami-day is going to look this ticket today.

**Comment by ami-day** [comment]
We need a bulk update process to do this - it is working on and off with glitches and cannot be done manually for datasets with >10 sequencing processes. Moving to stalled.

**Comment by ESapenaVentura** [comment]
This is a very complicated update.

It's not about automation but the original dataset needs to be reconstructed from scratch if we want to update this dataset.

Processes were created and deleted, and UUIDs were not preserved. There is no easy way to update this project, so I can propose:
- Create a ticket to put this dataset back in an updatable status (For the future, when capacity) and apply the changes above
- For now, just export project metadata (Which is the purpose of this ticket)

Also, I have a spreadsheet with the correct linkings, which should probably be used to update the project at some point: 
[https://app.zenhub.com/files/261790554/812db3b9-ae98-4d7d-8462-d5d7c0ad0790/download](https://app.zenhub.com/files/261790554/812db3b9-ae98-4d7d-8462-d5d7c0ad0790/download)

**Comment by ESapenaVentura** [comment]
This ticket will be used for the actual task of reconstructing the dataset, for the operational fix to fill out the cell count please refer to https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/gh/ebi-ait/hca-ebi-wrangler-central/1022

**Comment by ESapenaVentura** [comment]
https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/376 is the original ticket - It has a lot of info, so let's keep that one
