### ISSUE TITLE
The Human and Mouse Enteric Nervous System at Single-Cell Resolution

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#784]
### Project short name: 
HumanMouseEntericNervousSystem

### Primary Wrangler: 
Ami

### Secondary Wrangler:
Wei

### Associated files

* Google Drive: 
https://drive.google.com/drive/folders/1JxiNSBjWx0Vx5RwjLHL_1DbfxlJ2_mdA

* Google Sheet:
https://docs.google.com/spreadsheets/d/1mQA6lLwc1jxnd-m7OeNI1fvOJ80Gf7E21Ys4nXN8DYY/edit#gid=1072115413

### Published study links

* Paper: [The Human and Mouse Enteric Nervous System at Single-Cell Resolution](https://doi.org/10.1016/j.cell.2020.08.003)
* Accessioned data: [single cell portal](https://singlecell.broadinstitute.org/single_cell/study/SCP1038/the-human-and-mouse-enteric-nervous-system-at-single-cell-resolution#study-download)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=7be05025-9972-493a-856f-3342a8d1b183)
### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Need information from the authors. Sent them an email.

**Comment by Wkt8** [comment]
Have had a look and made some changes and comments! 
Donor Organism Tab: 
- There were multiple duplicate mice in the donor_organism tab (e.g. M1_colon_plate and M1_colon_droplet). Whilst these are separate cell suspensions, there is only 1 donor_organism (Mouse with ID M1). I removed the duplicate mice and changed the donor_organism IDs
- I also changed the strains of the mice to the strain mentioned in the publication 
- I also changed the Input Donor Organism ID column in the specimen_from_organism tab

**Comment by ami-day** [comment]
Thanks @Wkt8 !

The publication wasn't clear so I asked the authors about their donor-sample linkings. They said that the mouse donors are indeed different for the plate vs droplet and colon vs ileum samples, and linked to different donor metadata (sex and age for example). So, there are multiple M1 mice, for example. They are not duplicates.

I will have a look at the mice strains you added and add them, if it makes sense based on the mouse donors given they are not duplicated.

**Comment by ami-day** [comment]
Waiting to hear back about SCP bulk data download. The SCP team said thy would change our data quote for today so we can download all the bam files.

**Comment by Wkt8** [comment]
Issues with downloading sequence files from the SCP (they have a daily quota on downloads). They have raised Ami's download quota to facilitate downloading.

**Comment by ami-day** [comment]
bam files are converting to fastq files.

**Comment by ami-day** [comment]
> https://data.humancellatlas.org/explore/projects/7be05025-9972-493a-856f-3342a8d1b183?catalog=dcp17

Thanks for checking @Wkt8 ! I will fix the supplementary links now and keep in mind using the existing projects for next time.

I think we didn't ever have a rule that the project description should be the same as the project abstract. I prefer to provide a shorter overview for the project description, as opposed to copy and pasting the abstract.

**Comment by ami-day** [comment]
Update done (https://contribute.data.humancellatlas.org/submissions/detail?uuid=c3e29a85-51e5-4a96-89a5-37e9b9a9593b&project=7be05025-9972-493a-856f-3342a8d1b183). The project is now in Complete status, have asked the devs to push it back to metadata valid status, so it can be re-graph validated and re-exported.

**Comment by ami-day** [comment]
Yes the updates were done and it was exported.

**Comment by ESapenaVentura** [comment]
Re-opening as the updates need to be checked in the browser once they go live

**Comment by gabsie** [comment]
This is exported, needs an import form for release 20.

**Comment by ami-day** [comment]
Submitted the import form
