### ISSUE TITLE
Metadata errors not displayed correctly

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#786]
**Describe the bug**
After uploading a submission (link) some entities are metadata invalid but the error messages are missing
![Screenshot 2022-04-29 at 13.44.06.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/027fb588-c716-403d-9437-b32f02605343)

Triggering validation by editing the description of the entities produces two outcomes:
1. The error messages appear
![Screenshot 2022-04-29 at 13.46.51.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/415a94c8-1395-4e29-a714-61ac9cee7676)
2. The entity becomes metadata valid
![Screenshot 2022-04-29 at 13.48.54.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/986a5ee6-d167-4423-a7e2-047ddfdcd77f)

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the [spreadsheet](https://docs.google.com/spreadsheets/d/1Q17gBrGQLq9L-fKGaclVlgOPeEHt-wT3/edit?usp=sharing&ouid=113452802627011629126&rtpof=true&sd=true)
2. Upload the spreadsheet in [staging](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=003dd66d-5d2c-46f8-ac7c-32a06d403501)
3. See validation errors
4. Click `Biomaterials: 6 metadata errors`
5. Click `expand all`: the error messages are missing
6. Edit the entity description to trigger validation: the error message appears
7. Edit `cell_line_H1`'s description to see the validation error disappear

**Expected behaviour**
I expect the validation errors to be displayed only if the metadata is invalid: revalidation should not change the outcome
I expect the validation errror to display an error message

**Environment**
- [x] prod
- [x] staging
- [x] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [x] Firefox

**Comment by MightyAx** [comment]
@jacobwindsor 
Do we expect the fix to apply for projects that are *already* in this state of invalid without errors? Or is the fix to prevent them getting in this state in the first place?

Screenshot taken from staging this morning:
![Screenshot 2022-05-04 at 10.16.39.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/c72eb6fd-d74d-40da-a852-4dcd55839db6)

https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=39ac4216-7e5f-400f-a461-4497fd6e9582&project=003dd66d-5d2c-46f8-ac7c-32a06d403501

**Comment by MightyAx** [comment]
I spoke with Jacob, we don't expect the fix to apply for metadata items that are already in this state of invalid without errors.

@idazucchi for any metadata items on staging/production that are showing as invalid without a reason, editing these in some way should trigger revalidation to show you the reason.

Or if this is man items, you could just re-upload the project.

**Comment by MightyAx** [comment]
For reference this issue was fixed with this code change: ebi-ait/ingest-core#130

**Comment by idazucchi** [comment]
The error messages are showing up now, which is nice, but the `cell line` is still causing issues:
- if I trigger validation the error disappears
- the error message is not related to the cell line (and the field official_hca_publication does exist)
![Screenshot 2022-05-06 at 09.31.20.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/546be4eb-082c-4c59-83dc-e672ca41eefa)

**Comment by MightyAx** [comment]
I've opened ticket ebi-ait/dcp-ingest-central#768
to track this bug on the development board in future.
