### ISSUE TITLE
403 Unauthorised Uploading Spreadsheet to Existing Project

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#789]
![Screenshot 2022-05-05 at 15.35.36.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/75fa2ac7-a1db-493e-bbcc-c03f890a49bb)

**Comment by MightyAx** [comment]
@MightyAx and @ofanobilbao to investigate tomorrow after stand-up

**Comment by MightyAx** [comment]
# Reproduction steps

We have investigated and narrowed the reproduction steps to the following:
1. Create new project from DOI
1. Save a valid project by not ignoring metadata errors
1. Wait for the `project.validationState` to be "Valid" in the API
    - Without the previous two steps the error message could be genuine 
1. Data Upload Tab -> Submit to Project
1. Choose a spreadsheet
1. **Use the option: "Update the project metadata. This will overwrite the existing project metadata."**
1. Click Import Spreadsheet

You will see an error: "Operation not allowed while the project has a submission in a non-editable state."

**Comment by MightyAx** [comment]
While writing the above steps I was able to get a success using the small dataset test from the wrangler testing folder, this may be a problem with Oihane's spreadsheet.
**Investigation continues...**

**Comment by ofanobilbao** [comment]
Referenced the issue in the Development task related to this. So moving this to Done
