### ISSUE TITLE
Create slide deck for EMBL-EBI archival presentation to DCP

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#79]
## Goal

@lauraclarke and @mshadbolt are giving a presentation to the DCP about the EMBL-EBI archival resources and their goals

The topics covered by this presentation should include

- info about EMBL-EBI's core mission
- value of archiving 
- ENA
- BioSamples
- ArrayExpress
- EGA
- new archives - BioStudies and BioImaging Archive
- how this supports the HCA
- other archives which may be used by HCA in future
- Pride
- Metabolites
- Maybe something about GA4GH?
 
a slightly random selection of slides which could be useful here https://drive.google.com/drive/folders/1pxKoMPc7oJr_8gxaOaz9h1EMKQn9b9cP?usp=sharing

slide deck: https://docs.google.com/presentation/d/11jV0s9QOjZ62jwLlajdL0OFPA1P2aImHyBHh-Dc4A-8/edit#slide=id.p1

**Acceptance criteria for the task:**

- [x] draft slide deck exists - deadline 8th July
- [x] feedback from team and Tony
- [x] presentation given

**Comment by mshadbolt** [comment]
@lauraclarke should we have a date when we aim to have the draft slides ready in order to get feedback? I imagine setting up a time with Tony would be better done sooner rather than later

**Comment by lauraclarke** [comment]
Yes we should, does the 8th work, that gives us 5 working days to get feedback?

**Comment by mshadbolt** [comment]
made a google slides version here: https://docs.google.com/presentation/d/11jV0s9QOjZ62jwLlajdL0OFPA1P2aImHyBHh-Dc4A-8/edit#slide=id.g8b5fd9f066_0_0

**Comment by lauraclarke** [comment]
Slides from Thomas and Guy about ENA/EGA

EGA
https://docs.google.com/presentation/d/1XS8iIwgfMRmXu_pEizIzyaUxkUtLQLZZZ3Zhz64SWJc/edit#slide=id.g8922a18c6b_0_65
https://docs.google.com/presentation/d/1XS8iIwgfMRmXu_pEizIzyaUxkUtLQLZZZ3Zhz64SWJc/edit#slide=id.g8922a18c6b_0_65

ENA
https://drive.google.com/file/d/1DlRIZbEpx5rFkPmOLMFdwIERyCziV77c/view?usp=sharing
Slides 3-9 and 14 should be suitable

**Comment by mshadbolt** [comment]
Posted on link on slack to get feedback from the broader team
