### ISSUE TITLE
Ingest project stuck in 'Cleanup state' 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#790]
**Description of the task:**
Investigate why this project (https://contribute.data.humancellatlas.org/submissions/detail?uuid=724dff92-a752-4da9-9861-3e6392d4c59b) is stuck in the 'Cleanup state' and if it has been exported correctly

**Acceptance criteria for the task:**

- [ ] Check that this project has been exported correctly
- [ ] This project has been moved out of the 'Cleanup' state into the 'Completed' state
- [x] We know why this project is stuck in the 'Cleanup' state
- [ ] Future steps have been taken to prevent projects from being stuck in the 'Cleanup state' (a product-dev ticket for a bug + documentation?)

**Comment by MightyAx** [comment]
This project was unable to be marked Complete because of this issue: https://github.com/ebi-ait/ingest-core/commit/cdf11f4f19460c27462721b70db267e00c4e62df

**Comment by MightyAx** [comment]
I've identified that this project needs to be reexported, for the null file_id issue.
Adding to issue for tracking these: #796
