### ISSUE TITLE
Schema update priority ticket - 2022-05-09

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#793]
**What are the next schema updates?**

Expand disease ontology to include phenotype #[1460](https://github.com/HumanCellAtlas/metadata-schema/issues/1460) - Ida

**What schemas will they affect?**

 module/ontology/disease_ontology.json

**Why are these changes needed?**

Expanding the `known_disease` onotology field to include phenotype will allow contributors to report clinically signigcant phenotype observation in a way that is searchable.

**Type of change and time frame**

The update constitutes a minor change.
We are expecting to push the update before 23/05/2022

**Comment by idazucchi** [comment]
the PR is [here](https://github.com/HumanCellAtlas/metadata-schema/pull/1462)

**Comment by idazucchi** [comment]
merged the PR and fixed a bug  in src/release_prepare.py

still need to update hca spreadsheet template

**Comment by idazucchi** [comment]
I'm waiting to see if this update is connected to the issue in this ticket #811
If the two are not connected I will go ahead and update the hca spreasheet template

**Comment by Wkt8** [comment]
@ESapenaVentura came up with a workaround to use schema tabs when submitting to ingest

**Comment by Wkt8** [comment]
Should be solved with the ontology ticket update on the 18th.

**Comment by gabsie** [comment]
Now this works.
