### ISSUE TITLE
Temporary Fix to allow export of large projects

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#794]
This project is too large, it failed graph validation and took down ingest when it was exporting:

wrangling ticket: ebi-ait/hca-ebi-wrangler-central#317
ingest project: [A single-cell and spatial atlas of autopsy tissues reveals pathology and cellular targets of SARS-CoV-2](https://contribute.data.humancellatlas.org/submissions/detail?uuid=9c4eea83-8939-4232-9568-d31eea06718d&project=61515820-5bb8-45d0-8d12-f0850222ecf0)

a second very large project:
~~HPSI human cerebral organoids~~, is blocked by a separate exporter issue relating to it's original inception as a DCP1 project.
But was able to reexport file descriptors without crashing ingest

~~Project UUID: [005d611a-14d5-4fbf-846e-571a1f874f70](https://contribute.data.humancellatlas.org/projects/detail?uuid=005d611a-14d5-4fbf-846e-571a1f874f70)
Submission UUID: [dc0828c4-2d46-4313-b408-e69e4c7ccd33](https://contribute.data.humancellatlas.org/submissions/detail?uuid=dc0828c4-2d46-4313-b408-e69e4c7ccd33&project=005d611a-14d5-4fbf-846e-571a1f874f70)
API: [6256b96b0d00514fc697880b](https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/6256b96b0d00514fc697880b)~~

The only idea for how to fix this as an operations task is to run exporting with only this project and with less export threads running in parallel.

There is also a development task for a more permanent optimisation (ticket number here)

**Comment by MightyAx** [comment]
as part of ticket 796 I deleted the descriptors that were exported for this project and tried to reexport them, not realising that this project was should not be exported due to its size, and that the export that has been performed is only partially complete.

I have purged the messaged that were exporting this project from the queue. I do not know what state this means the data we have exported is in.

**Comment by MightyAx** [comment]
Another very large project:
HPSI human cerebral organoids
Project UUID: [005d611a-14d5-4fbf-846e-571a1f874f70](https://contribute.data.humancellatlas.org/projects/detail?uuid=005d611a-14d5-4fbf-846e-571a1f874f70)
Submission UUID: [dc0828c4-2d46-4313-b408-e69e4c7ccd33](https://contribute.data.humancellatlas.org/submissions/detail?uuid=dc0828c4-2d46-4313-b408-e69e4c7ccd33&project=005d611a-14d5-4fbf-846e-571a1f874f70)
API: [6256b96b0d00514fc697880b](https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/6256b96b0d00514fc697880b)

**Comment by MightyAx** [comment]
My recommendation is two things:

1. Lower the number of concurrent ingest exporter pods as not to make too many requests of core at once that blow the memory budget
    - In fact I think drastically we should set this at 1 and slowly increase over time.
1. Put errored rabbit messages in an error queue that we can requeue just the bits of a project that failed rather than having to re-export the whole project, this will be essential for big projects like these.

**Comment by MightyAx** [comment]
The plan is to lower the number of concurrent ingest exporter pods as not to make too many requests of core at once that blow the memory budget, approved at the development meeting.

**Comment by ipediez** [comment]
An issue with a DCP1 dataset: a supplementary file references some files that now are missing, @MightyAx has commented about it in the corresponding ticket (wrangling #310)

**Comment by Wkt8** [comment]
Will try to export ami's large dataset - if that works - this can be moved to done.
