### ISSUE TITLE
Human5Ovary10xChuva_v1

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#795]
**Collection/dataset this task is for:**

- file name - GSM3557964_sample145_B1_i12D_filtered_gene_bc_matrices_h5.h5
- link to existing collection in cellxgene"
- ticket link to DCP wrangling ticket (if available)
- link to ingest UI: https://contribute.data.humancellatlas.org/projects/detail?uuid=faeedcb0-e046-4be7-b1ad-80a3eeabb066
- Drive [folder](https://drive.google.com/drive/folders/1sJfQ2RjTSe760beSUIEFs4f16Iz3AflU)

**Relevant People**
- Wrangler
- Contributor
- dev

### Associated files
* [SOP](https://docs.google.com/document/d/1UVGIllybmEI46x22NSDpMNRywT3c8hcGrcw6opiHdbg/edit#)
* [Knowledge Sharing Drive](https://drive.google.com/drive/folders/1cIgfeZZaoo2mFo2mN9iZ00_MZt94mvLv)
* [Ingest-cellxgene-submitter](https://github.com/ebi-ait/ingest-cellxgene-submitter) 
* [Cellxgene-schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md)
* [Cellxgene-schema-validate](https://github.com/chanzuckerberg/single-cell-curation)
* [Cellxgene-submit-collection](https://cellxgene.cziscience.com/?curator=true)

### Published study links

* Paper:

* Accessioned data:

### Key Events

- [ ] Collect necessary matrix, cell-type annotation, and embedding files
- [ ] Modified var layer to meet cellxgene schema (adding feature_is_filtered)
- [ ] Created/Modified raw.var to meet cellxgene schema
- [ ] Modified obs layer to meet cellxgene schema 
- [ ] Created uns layer to meet cellxgene schema
- [ ] Ensured obsm layer is present
- [ ] Created h5ad with processed component parts using AnnData
- [ ] Created h5ad with raw matrix and raw var using AnnData
- [ ] Filtered ENSEMBL IDs from annotated and raw matrix
- [ ] Combined processed and raw h5ad to one h5ad object
- [ ] Run [cellxgene-schema validate](https://github.com/chanzuckerberg/single-cell-curation)
- [ ] Secondary review (?) 
- [ ] Submitted to collection in [cellxgene](https://cellxgene.cziscience.com/?curator=true)

**Comment by ipediez** [comment]
Only the raw matrices are available. We do not have an embeddings layer or cell-level information. I have emailed the authors and they will get back to me next week, presumably

**Comment by ipediez** [comment]
We have received from the contributor an h5ad file (needs to be read with Anndata 0.8) with all the needed information except for the raw matrix. I've asked them for this matrix.

**Comment by Wkt8** [comment]
Published in cellxgene.

**Comment by arschat** [comment]
Updated the [h5ad](https://drive.google.com/file/d/1f5UFFTt-Oa9pFJQHFPiZNq1-wd0OUXSc/view?usp=drive_link) with mapping based on [this](https://drive.google.com/file/d/1ARNCS6Sz3m6UoNFFSHF4yaxxca3nNPFr/view?usp=drive_link) drive file.
