### ISSUE TITLE
contributor account for Simone Webb

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#799]
Please create an account a contributor.

*Contributor details:*
* name: Simone Webb
* email: Simone.Webb@newcastle.ac.uk

Request Details:
* Requested by: Ida Zucchi

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by idazucchi** [comment]
Actually this might not be needed, @MightyAx please ignore this for now

**Comment by ofanobilbao** [comment]
@idazucchi can we close this? It's been open for 3 months in Stalled

**Comment by ofanobilbao** [comment]
I am making the call and closing. We can re-open if required at a later date or create a new ticket for it
