### ISSUE TITLE
fastq stuck in metdata validation - MegakaryocyteDevelopment

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#800]
**Dataset this task is for:**

- project uuid - `a9f5323a-ce71-471c-9caf-04cc118fd1d7`
- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=a9f5323a-ce71-471c-9caf-04cc118fd1d7)

**Relevant People**
- Wrangler: Ida
- dev

**Description of the problem with the dataset**
One fastq file has been metadata validating since Friday afternoon (~2,5 days). This stops me fron running the graph validation and exporting. 
This dataset is intended for release 17, the deadline is May 23rd so it's going to be more urgent as time passes

- [ ] check why the validation is stuck
- [x] get the file to metadata valid

**Acceptance criteria for the task:**
- [x] file is metadata valid

**Comment by MightyAx** [comment]
Stuck File:
https://api.ingest.archive.data.humancellatlas.org/files/627e3e32a9f5957dde269ff6

**Comment by MightyAx** [comment]
Completely useless instructions on how to unstick a file: https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/stuck-submissions.html

**Comment by MightyAx** [comment]
the file exists in s3
the batch job with this validation number does not exist
`validation-prod-bcab8222-8b82-4874-8974-c457a0832ece-889d5ae1-889d5ae1-ed2a-4d5c-a362-42bc78955f8e`

No errors reported for any of the id's above in the validator logs

**Comment by MightyAx** [comment]
attempting to trigger a batch job manually
