### ISSUE TITLE
Myocyte-Specific Upregulation of ACE2 in Cardiovascular Disease: Implications for SARS-CoV-2-Mediated Myocarditis

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#801]
### Associated files

* Google Drive: TBD

### Published study links

* Paper: [Myocyte-Specific Upregulation of ACE2 in Cardiovascular Disease: Implications for SARS-CoV-2-Mediated Myocarditis](https://doi.org/10.1161/circulationaha.120.047911)

* Accessioned data: https://singlecell.broadinstitute.org/single_cell/study/SCP846 could require registration

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=d84fd289-1b4b-43f0-aa84-9f0928937106)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
This ticket should actually be closed. The dataset is not eligible (no data, raw or processed).
