### ISSUE TITLE
R16 Referenced data file is missing

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#802]
https://contribute.data.humancellatlas.org/submissions/detail?uuid=db88135b-512b-41f7-874b-8566900c3635&project=18e58437-76b7-4021-8ede-3f0b443fa915

https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1651565683448179?thread_ts=1651152270.670519&cid=C014HMTV0FN

No wrangling ticket, UCSC dataset

**Comment by ESapenaVentura** [comment]
Jacob has created the metadata files

I have located and I am downloading the missing file from the ENA accession (SRP261119)

(After some issue-solving regarding clusters and python versions)

**Comment by Wkt8** [comment]
This is... done.
