### ISSUE TITLE
stuck in validation: humanHeartFailureCellularLandscape

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#803]
*Project Info*
uuid: [135f7f5c-4a85-4bcf-9f7c-4f035ff1e428](https://contribute.data.humancellatlas.org/projects/detail?uuid=135f7f5c-4a85-4bcf-9f7c-4f035ff1e428)
project short name: humanHeartFailureCellularLandscape
primary wrangler: Rachel Schwartz

Project is stuck in 'metadata validating' stae
* email: raschwar@ucsc.edu

Note:
assign to the current dev on operations.

**Comment by Wkt8** [comment]
@Wkt8 to add a bit more detail

**Comment by Wkt8** [comment]
Ingest link is here: https://contribute.data.humancellatlas.org/submissions/detail?uuid=f71d6610-9ec5-4921-b8c7-374cf157c32e&project=135f7f5c-4a85-4bcf-9f7c-4f035ff1e428
The entities stuck in 'validating' are sequence files!

**Comment by Wkt8** [comment]
![Screenshot 2022-05-20 at 10.16.02.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/08923225-1ba5-4993-b01e-56bb26e2779d)

**Comment by rachadele** [comment]
When I filter for validating entities nothing comes up:
<img width="1361" alt="Screen Shot 2022-05-20 at 8 08 18 AM" src="https://user-images.githubusercontent.com/51383714/169557748-7cdce3cb-e57c-4380-888d-99c999415aa8.png">

**Comment by rachadele** [comment]
These have been validating for a few days, which seems out of the ordinary?

**Comment by ke4** [comment]
@ke4 and @jacobwindsor investigate this later

**Comment by yusra-haider** [comment]
three fastq files are stuck in validating state.

the steps outlined in this ticket: https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/800 might help

**Comment by ke4** [comment]
We re-triggered the validation for the 1st and 2nd file and waiting for their results. If they succeed then we are going to re-trigger the 3rd one, too.

**Comment by ke4** [comment]
The 1st one has succeed. We are going to trigger the 3rd one.

**Comment by yusra-haider** [comment]
all 3 files are now in valid state, and the submission is in metadata valid state

**Comment by ofanobilbao** [comment]
Rachel has been notified. This can be moved to Done
