### ISSUE TITLE
Updating schema change SOP

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#804]
**Description of the problem**
I've followed the schema change documentation SOP to make an update and discovered that some parts are outdated.

**What needs to be updated:**
### Our SOP
SOP [here](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/schema_update_prioritisation_SOP.html#creating-a-priority-ticket)
- [x] DCP2 specs - Changing the metadata schema: should be desribed as DCP2 specs      
- [x] add lnk to [dcp2 sop](https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_operating_procedures.rst#pull-request-reviews) explains how to handle the PR request for reviews and timings
- [x] add link to [sop to determine type of update](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/evolution.md#schema-versioning)
- [x] the schema changes don't need to be presented to the dcp community before opening a PR
- [x] edit the template to present the open PR, ask for reviews and tag the reviewrs as requested in the dcp2 SOP
- [x] clarify what needs to be linked in the message (the PR I think)
- [x] point out that releasing the changes is wrangler responsability

### metadata-schema/docs
the [dcp2 SOP - how to prepare a PR](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md) should also be updated:
- [x] requirement to install pre-commit not clear, add a line to set up the git hook scripts `pre-commit install` 
  - [x] is the githook important for the PR or for the release process?
  yes, it automatically updates the json documentation
- [x] `src/schemas_are_valid_json.py ` exit code 0 is outdated and it creates confusion
- [x] add path for `update_log.csv`
- [x] create PR aginst staging branch not dev
- [x] some github components, like travis, pullapprove, are no longer working, so either:
    - [x] remove the references to avoid confusion - Travis
    - [x] remove Travis relics 
    - [x] work on making pullapprove operative again
- [x] the review process doesn't match the dcp2 ops

Metadata Schema repository - [release process](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/release_process.md): pre-release and release process for schema updates
- [x] indicate that releasing changes is also a wrangler responsability
- [x] step 1: should pull staging
- [x] step 3.i: should pull staging?
~~step 7: bug fix needed~~ I think I have already addressed this
- [x] step 8: is travis running? should say staging not develop
- [x] setp 9: always delete the PR branch?
- [x] step 10: is the done label still relevant?
- [x] step 11: is this still relevant?
- [x] can we update the PR template staging-->master ?
------------------------------------
**Acceptance criteria**
- [x] PR opened for each repository
- [x] PR merged successfully
- [x] swap travis with GitLab
- [x] fix pullapprove

to do:
- [x] address comments in the PR

**Comment by idazucchi** [comment]
I've opened a [PR](https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/817) for our SOP

**Comment by ami-day** [comment]
Ida is waiting for review of the PR

**Comment by ofanobilbao** [comment]
Wei reviewed it already. He only needs to tick it.

Then should be ready to go

**Comment by idazucchi** [comment]
Internal SOP PR merged into master

**Comment by idazucchi** [comment]
I've opened a [new PR](https://github.com/HumanCellAtlas/metadata-schema/pull/1467) in the schema repo

**Comment by idazucchi** [comment]
if the tiered review system based on the type of update has been scrapped completely then we can substantially simplify the pullapprove configuration

**Comment by idazucchi** [comment]
if the tiered review system based on the type of update has been scrapped completely then we can substantially simplify the pullapprove configuration

**Comment by Wkt8** [comment]
@MightyAx will have a look to see if GitLab can replace Travis

**Comment by MightyAx** [comment]
https://github.com/ebi-ait/dcp-ingest-central/issues/525

**Comment by idazucchi** [comment]
@Alexie replaced Travis with GitHub actions and I merged all the changes to master

The only way to test if the pullapprove configuration is correct is to open a PR so I'm waiting for the upcoming shcma PRs before closing this ticket

**Comment by idazucchi** [comment]
Pullapprove is working as expected, so I'm closing this ticekt!
