### ISSUE TITLE
missing project metadata error is not missing - AdaptiveNKCellsInMultipleMyeloma

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#805]
*Project Info*
uuid: 2eb4f5f8-42a5-4368-aa2d-337bacb96197
project short name: AdaptiveNKCellsInMultipleMyeloma
primary wrangler: Rachel Schwartz
[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=2eb4f5f8-42a5-4368-aa2d-337bacb96197)
spreadsheet [here](https://docs.google.com/spreadsheets/d/1czzNR0-jD7Da6zMsWy1wpUakFWCjcWjT/edit?usp=sharing&ouid=113452802627011629126&rtpof=true&sd=true)

*Description of the problem*
ingest throwing this error even though project shortname exists:
```
Project is Invalid. Please go back and edit the project.
* should have required property 'project_short_name' at .project_core

```
The error appears once the spreadsheet is uploaded, but this doesn't prevent running graph validation. In fact graph validation passed succesfully.
Waiting for this to be investigated before attempting to export

Note:
assign to the current dev on operations.

*Task*
- [ ] investigate why the error is reported
- [ ] investigate whether the error will affect the export
- [ ] ? create a bug ticket to solve the issue

**Comment by ofanobilbao** [comment]
@ESapenaVentura will investigate and if needed check with Yusra

**Comment by ESapenaVentura** [comment]
@rachadele the project is now valid

I checked the API and for some reason this project had metadata validation errors while in Valid state

To solve it, I just deleted the last character of the description, saved, and added it back

It should be a-ok now to export 💯
