### ISSUE TITLE
Correct typo in analysis_protocol schema

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#806]
Related to this PR https://github.com/HumanCellAtlas/metadata-schema/pull/1411

**Comment by ofanobilbao** [comment]
To be discussed to prioritise on the next Wrangle call. @ESapenaVentura to add more details

**Comment by ofanobilbao** [comment]
@ESapenaVentura did this get prioritised in the end? Status?

**Comment by idazucchi** [comment]
this is being addressed in the schema priority ticket #938
