### ISSUE TITLE
Kick projects in complete status

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/hca-ebi-wrangler-central#808]
Working on updating all projects to include project estimated cell counts. The list below are projects that need to be kicked back to valid from complete status.

1. 5bb1f67e-2ff0-4848-bbcf-17d133f0fd2d
2. 18d4aae2-8363-4e00-8eeb-b9e568402cf8
3. bd7104c9-a950-490e-9472-7d41c6b11c62
4. f6133d2a-9f3d-4ef9-9c19-c23d6c7e6cc0
5. a2a2f324-cf24-409e-a859-deaee871269c
6. aff9c3cd-6b84-4fc2-abf2-b9c0b3038277
7. 3c27d2dd-b180-4b2b-bf05-e2e418393fd1
8. f29b124a-8597-4862-ae98-ff3a0fd9033e

Ping @willrockout when completed or as they are completed.

**Comment by ipediez** [comment]
The projects need to be graph valid to be able to re-export them

**Comment by jacobwindsor** [comment]
@willrockout this is now done
