### ISSUE TITLE
cleanup of TDR staging area

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#810]
Received from KT on 23 May 2022 at 18:41:38 BST

> Hi, all.
> 
> Storage costs for HCA have been going up and so we are taking inventory.  The staging areas for import into TDR seem to be hanging on to a lot.  Nate has pulled together this list of the largest buckets:
> 
> |Bucket	|Size (TiB)	|Size	|Object Count	|Contents	|Lifecyle Rules|
> |-|-|-|-|-|-|
> [gs://broad-dsp-monster-hca-prod-ebi-storage/](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/)	|92.74|	92.74 TiB|	1.455M|	Staging area buckets for EBI and UCSC	 
> gs://broad-dsp-monster-hca-prod-ucsc-storage/|	38.95|	38.95 TiB|	3.22M|	CGMs for UCSC, unclear if this is still actively used	 
> gs://broad-dsp-monster-hca-prod-lantern/	|32.27|	32.27 TiB	|427.51K	|Staging area buckets for LANTERN	 
> gs://broad-dsp-monster-hca-prod-lattice/	|12.11	|12.11 TiB	|14.46K	|Staging area buckets for LATTICE	 
> 
> Can each group please review the what's in your bucket and either:
> * Manually clean up anything that's in there and no longer needed; and set up a process for doing so regularly in the future
> OR
> * Get in touch with Nate to set up appropriate lifecycle rules for your bucket.
> This data i costing thousands a month, so please do the first cleanup (at least) ASAP.  Thanks!
> 
> kt
> Kathleen Tibbetts (she/her)

**Comment by ofanobilbao** [comment]
@amnonkhen is this still required? From the post-demo meeting I understand that the Import team will delete the staging areas 1 week after the project makes it to the Browser. Isn't it?

**Comment by ofanobilbao** [comment]
@amnonkhen is this still required? I am trying to clean up the board and this looks like could go

**Comment by ofanobilbao** [comment]
Closing as there was not response since May I am assuming no longer required
