### ISSUE TITLE
Investigate phenotype terms error in ingest

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#811]
**Description of the problem:**
Yesterday (24/5/2022) I pushed a new schema change to expand the accepted ontology terms in the field disease, PR [here](https://github.com/HumanCellAtlas/metadata-schema/pull/1462).
When uploading a spreadsheet there is now a new error raised:
`Could not retrieve IRI for HP:0000118 at .diseases[0].ontology`
This happens with entities that have a mondo or HP term, those that have the `normal` term are not affected by the issue.

Test [project](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=7030c2fa-58a4-4c73-9f37-4c56b212fa66) in staging
[Spreadsheet](https://docs.google.com/spreadsheets/d/1Q5DLZDbbRrQz92eMQ-URC0SbCS9ggJCS/edit?usp=sharing&ouid=113452802627011629126&rtpof=true&sd=true) used for testing

**Acceptance criteria for the task:**
- [ ] investigate the cause of the error
- [ ] the error is not raised

**Comment by ipediez** [comment]
This affects submissions created between Tuesday and today. It only affects datasets with donors with diseases (not those with only normal samples), @idazucchi to check this. 

@gabsie to check if Yusra is available or choose another wangler

**Comment by idazucchi** [comment]
I uplaoded a [new submission](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=b6563324-5f7a-44ff-bc86-2d7225fc8620&tab=project) in staging and can confirm that healthy donors are not affected

**Comment by jacobwindsor** [comment]
Waiting on https://github.com/HumanCellAtlas/ontology/issues/110

**Comment by Wkt8** [comment]
Waiting for HCAO to get back to us.

**Comment by Wkt8** [comment]
This was as a result of the HPO ontology not being included in HCAO. Will be fixed with the next ontology update ticket.

**Comment by ESapenaVentura** [comment]
Hi Rachel - This was supposed to be fixed on Friday, but tl;dr:
- HP slim was not loaded
- Contacted the ontology team and investigated
- New release was created and deployed (Yesterday)
- New release is also broken 

There are a couple more details on the new release here: https://github.com/ebi-ait/hca-ebi-dev-team/issues/490

**Comment by amnonkhen** [comment]
fixed with HCAO 1.0.39, see
