### ISSUE TITLE
CRC32 checksum failing for project 00f6f940-570a-4936-9ab5-f572b7e018f5

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#815]
**Description of the task:**

3 files for project [HumanAdultUreter](https://contribute.data.humancellatlas.org/submissions/detail?uuid=a8f8dc60-4c43-470d-a3b5-05135d91e3a6&project=00f6f940-570a-4936-9ab5-f572b7e018f5) are not passing the crc32 checksum assertion when imported
Wrangler: Will Sullivan

The ~s3 area has been deleted~ ( @ESapenaVentura has since re created it ), so there is currently no way for us to check if files were corrupted over the export process

Files with this error are: 
- SRR15896955_R1.fastq.gz [see on s3](https://s3.console.aws.amazon.com/s3/object/org-hca-data-archive-upload-prod?region=us-east-1&prefix=a8f8dc60-4c43-470d-a3b5-05135d91e3a6/SRR15896955_R1.fastq.gz), see [on terra staging area](https://console.cloud.google.com/storage/browser/_details/broad-dsp-monster-hca-prod-ebi-storage/prod/00f6f940-570a-4936-9ab5-f572b7e018f5/data/SRR15896955_R1.fastq.gz;tab=live_object)
- SRR15897021_R1.fastq.gz
- SRR15897092_R2.fastq.gz

Error message (from Nate):

```
ERROR:hca.staging_area_validator:Error with file: prod/00f6f940-570a-4936-9ab5-f572b7e018f5/data/SRR15896955_R1.fastq.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py", line 141, in validate_files
    validate_file_fn(blob)
  File "/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py", line 295, in validate_data_file
    assert metadata_file['crc32c'] == base64.b64decode(blob.crc32c).hex()
AssertionError
```

Data files are available in the [original upload area](s3://hca-util-upload-area/6c52d0c1-c41f-44d2-9fc1-fe7fe0851ca0/):

**Acceptance criteria for the task:**

- [x] The descriptors or data files are updated in the staging area (Depending on which one is wrong)
- [x] The import team is notified (see on [slack](https://humancellatlas.slack.com/archives/C03KF2R03AP))
- [x] Import form updated in one of
   - [x] [original entry](https://docs.google.com/spreadsheets/d/1xApi-qay1H9ef2JQAmPNXH63Xy-0cNYBN4wBaq-YC3U/edit#gid=398656126&range=A463:D463) - this will not be updated
   - [ ] delete old entry (R18, old uuid) from import form
   - [x] a new entry for R18 with the new uuid- ~waiting for answer~ on [slack](https://humancellatlas.slack.com/archives/C03KF2R03AP/p1655283546355549). A  [new one](https://docs.google.com/spreadsheets/d/1xApi-qay1H9ef2JQAmPNXH63Xy-0cNYBN4wBaq-YC3U/edit#gid=398656126&range=D470) was created
- [x] Delete the [original submission](https://contribute.data.humancellatlas.org/submissions/detail?uuid=a8f8dc60-4c43-470d-a3b5-05135d91e3a6&project=00f6f940-570a-4936-9ab5-f572b7e018f5) **when the import form has been filled out for the replacement submission**.
- [x] clean original staging area

**Comment by ESapenaVentura** [comment]
I have asked @willrockout for the files to check

**Comment by ESapenaVentura** [comment]
the hca-util upload area is `0e69c013-2d44-4441-9a55-21ba95c27171`

**Comment by ke4** [comment]
@ESapenaVentura I reset the submission status into `Draft` for https://contribute.data.humancellatlas.org/submissions/detail?uuid=a8f8dc60-4c43-470d-a3b5-05135d91e3a6&project=00f6f940-570a-4936-9ab5-f572b7e018f5
and redeployed the state-tracker.

**Comment by ke4** [comment]
Current checksums that we have to change:
- SRR15896955_R1.fastq.gz:
"checksums": {
    "sha1": "f49dde3414a3917f2b282a463051147659212dea",
    "sha256": "72a8376bd13deb7e60ad781ce6b51832c3e1f242a364eba8063eed990ff28526",
    "crc32c": "DA1D385D",
    "s3_etag": "cadefa44a95eba296328f3865845b82c-15"
  }
- SRR15897021_R1.fastq.gz:
"checksums": {
    "sha1": "7b00671cd07d97f80dbcbd95fdcf4fdfa3b9938d",
    "sha256": "664d7ac3639fe36a4f43e50532dd0c1f82ce48f39f323055fad58be5bf790f4f",
    "crc32c": "0EF91328",
    "s3_etag": "70bffdeeb8e1f9f39f9394a1aab6f501-14"
  }
- SRR15897092_R2.fastq.gz
checksums": {
    "sha1": "bd14695c42ca7c5a38eb465326b4347e8da0c511",
    "sha256": "fdcf83ae3662a56ba8b4d356a9c7966b9334fe13816c03011c9b454ce406f916",
    "crc32c": "E2565CD9",
    "s3_etag": "f9ab0439614ed6eebdce259f00f8ae96-13"
  }

**Comment by amnonkhen** [comment]
file descriptor for SRR15896955_R1.fastq.gz

**Comment by amnonkhen** [comment]
@amnonkhen & @ke4 ran the crc calculation lambda function manually fmor the aws console.
Results for `SRR15896955_R1.fastq.gz`
```json
{
   'sha1': 'f49dde3414a3917f2b282a463051147659212dea', 
   'crc32c': 'DA1D385D', 
   'sha256': '72a8376bd13deb7e60ad781ce6b51832c3e1f242a364eba8063eed990ff28526', 
   's3_etag': 'cadefa44a95eba296328f3865845b82c-15'
}
```

**Comment by amnonkhen** [comment]
The crc comparison fails in [this file from the data import team](https://github.com/DataBiosphere/hca-import-validation/blob/main/hca/staging_area_validator.py#L286):

```python
    assert metadata_file['crc32c'] == base64.b64decode(blob.crc32c).hex()
```
The left side is taken from the file descriptor, the right side is Google's API response for the data file.
We still do not know the reason for the mismatch.

**Comment by amnonkhen** [comment]
Update from Nate:

> Okay, I do see a disconnect. The descriptor file for SRR15896955_R1.fastq.gz (f180aa2f-ce44-4cfb-bacf-fda62ee3daec_2022-05-30T18:25:44.577000Z.json) has a crc32c recorded of “da1d385d”, but when I pull the crc32c from the metadata for the actual data file and run it through this code: base64.b64decode(“on3nLw==“).hex(), it returns “a27de72f”

**Comment by amnonkhen** [comment]
next steps: download the file from s3 and staging area and compare size, contents and crc.

**Comment by ESapenaVentura** [comment]
in the ec2, in `/data/eventura/descriptors` you should be able to find `SRR15896955_R1`. The one named `SRR15896955_R1.fastq.gz` is the one from the staging area and the one named `SRR15896955_R1_s3.fastq.gz` is from the ingest bucket.

I used sha1sum and crc32 bash programs on both and got:

```
(base) eventura@ip-172-31-71-222:/data/eventura/descriptors$ crc32 SRR15896955_R1.fastq.gz 
f1321933	BAD f1321933 != 15896955
(base) eventura@ip-172-31-71-222:/data/eventura/descriptors$ sha1sum SRR15896955_R1.fastq.gz 
976b4fd88963600d9da11b88d4f30be0e9c3ee8f  SRR15896955_R1.fastq.gz
```
and
```
(base) eventura@ip-172-31-71-222:/data/eventura/descriptors$ crc32 SRR15896955_R1_s3.fastq.gz 
f1321933	BAD f1321933 != 15896955
(base) eventura@ip-172-31-71-222:/data/eventura/descriptors$ sha1sum SRR15896955_R1_s3.fastq.gz 
976b4fd88963600d9da11b88d4f30be0e9c3ee8f  SRR15896955_R1_s3.fastq.gz
```

I don't know if these are correct calculations as I am using the programs available in the EC2

**Comment by ESapenaVentura** [comment]
But also please stop working for today, we can discuss it tomorrow. There is no hurry now, this dataset has been pushed to R18

**Comment by amnonkhen** [comment]
Thanks, @ESapenaVentura, I just downloaded the files and did the same crc calculation as you.
The "BAD" messages in the output are because the crc32 tool compares the calculated checksum with the first block of 8 hexadecimal characters in the filename.

In the case of:

```
(base) eventura@ip-172-31-71-222:/data/eventura/descriptors$ crc32 SRR15896955_R1_s3.fastq.gz 
f1321933	BAD f1321933 != 15896955
```

We have:
- `f1321933` the calculated crc32 checksum
- `15896955` first hexadecimal 8 character block in the file name
They differ, so the tools classifies this as *BAD*.

**Comment by ke4** [comment]
@ESapenaVentura and @amnonkhen you are calculating CRC32 and NOT crc32c. They are not the same AFAIK.
https://stackoverflow.com/questions/26429360/crc32-vs-crc32c

**Comment by amnonkhen** [comment]
Next steps:
- [ ] backup [original SRR15896955_R1.fastq.gz file entity](https://app.zenhub.com/files/261790554/c6a951ae-2cff-4ceb-9027-c384f3c784ad/download)
- [ ] remove checksums from file entity
- [ ] rerun checksum calculation lambda
- [ ] compare results

**Comment by idazucchi** [comment]
Importing the project from scratch to see if the error appears again

**Comment by ke4** [comment]
This is the original spreadsheet for the submission: [https://app.zenhub.com/files/261790554/babeb819-49fd-4518-91b2-30c6f769c675/download](https://app.zenhub.com/files/261790554/babeb819-49fd-4518-91b2-30c6f769c675/download)

**Comment by ke4** [comment]
I created a new submission on prod to test this issue using the original spreadsheet: https://contribute.data.humancellatlas.org/submissions/detail?uuid=e2ae95d3-d547-4c38-becd-8ed5448a7f3e&project=9833669b-d694-4b93-a3d0-6b6f9dbcfc10

**Comment by ke4** [comment]
We are using the original hca util upload area to sync the files: s3://hca-util-upload-area/6c52d0c1-c41f-44d2-9fc1-fe7fe0851ca0/

**Comment by ke4** [comment]
The file upload has started

**Comment by ke4** [comment]
I check the 1st file in the ticket(SRR15896955_R1.fastq.gz) in my test submission: https://api.ingest.archive.data.humancellatlas.org/files/62a1c3b5b85bb84636c5b01d
and it looks like it calculates the correct checksum now. The one that terra has. Not the one the ingest has in the original submission.

**Comment by amnonkhen** [comment]
CRC32C value from terra:

```
amnon@cloudshell:~$ gsutil hash gs://broad-dsp-monster-hca-prod-ebi-storage/prod/00f6f940-570a-4936-9ab5-f572b7e018f5/data/SRR15897021_R1.fastq.gz

WARNING: You have requested checksumming but your crcmod installation isn't
using the module's C extension, so checksumming will run very slowly. For help
installing the extension, please see "gsutil help crcmod".

Hashes [base64] for prod/00f6f940-570a-4936-9ab5-f572b7e018f5/data/SRR15897021_R1.fastq.gz:
        Hash (md5):             H1X1bxUOVeFOskSTd/LLHg==
        Hash (crc32c):          z5QABQ==
amnon@cloudshell:~$ echo z5QABQ== | base64 -d | hexdump -v -e '/1 "%02x"'
cf940005
```

The values are identical ignoring the case.
Since the exporter will lower the case, it appear to be in order.

**Comment by ke4** [comment]
1. I removed the 3 files from the original submission (SRR15896955_R1.fastq.gz, SRR15897021_R1.fastq.gz, SRR15897092_R2.fastq.gz) : https://contribute.data.humancellatlas.org/submissions/detail?uuid=a8f8dc60-4c43-470d-a3b5-05135d91e3a6&project=00f6f940-570a-4936-9ab5-f572b7e018f5 yesterday.
2. I also created a new `hca-util-upload-area` with these 3 files: [s3://hca-util-upload-area/7b9e0381-1988-4216-af5b-d29634c3b43a/](s3://hca-util-upload-area/7b9e0381-1988-4216-af5b-d29634c3b43a)

**Comment by amnonkhen** [comment]
Plan:
- [ ] rename [original](https://contribute.data.humancellatlas.org/projects/detail?uuid=00f6f940-570a-4936-9ab5-f572b7e018f5) project, add prefix `[DON'T USE bad crc dcp-815]` to name and `DONT_USE_DCP_815_` to label
- [ ] rename [new](https://contribute.data.humancellatlas.org/projects/detail?uuid=9833669b-d694-4b93-a3d0-6b6f9dbcfc10) project as the original name and remove the dcp-815 from its name
- [ ] move new project through ingest, validate, export
- [ ] validate crc correctness
- [ ] update import form: remove original project, insert new one
- [ ] update Will on Slack

**Comment by ke4** [comment]
For the 1st file in this ticket (SRR15896955_R1.fastq.gz):
```
gsutil ls -L gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9833669b-d694-4b93-a3d0-6b6f9dbcfc10/data/SRR15896955_R1.fastq.gz | grep Hash
    Hash (crc32c):          on3nLw==
    Hash (md5): 
```

file descriptor for that file from terra:

```json
{
  "file_id": "d70fdbf5-53e3-4bc9-b98e-5c1fdbba678c",
  "file_version": "2022-06-09T09:56:05.458000Z",
  "file_name": "SRR15896955_R1.fastq.gz",
  "content_type": "binary/octet-stream; dcp-type=data",
  "size": 11810197373,
  "sha1": "976b4fd88963600d9da11b88d4f30be0e9c3ee8f",
  "sha256": "870c7727398ea92a8c9a9def3093365d6dabb4c7918cb4d96ad8aa574bf2bedf",
  "crc32c": "a27de72f",
  "s3_etag": "f8068c06406dfe549442b4f39d2a28ff-176",
  "schema_type": "file_descriptor",
  "describedBy": "https://schema.humancellatlas.org/system/2.0.0/file_descriptor",
  "schema_version": "2.0.0"
}
```

That is matching what `Nate` had previously for that file, so we should be fine with this one.

I am going to check the others later tonight as I need a brake now. 😜

**Comment by ke4** [comment]
For the 2nd file in this ticket (SRR15897021_R1.fastq.gz):
```
$gsutil ls -L gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9833669b-d694-4b93-a3d0-6b6f9dbcfc10/data/SRR15897021_R1.fastq.gz | grep Hash
    Hash (crc32c):          z5QABQ==
    Hash (md5):             H1X1bxUOVeFOskSTd/LLHg==

$echo z5QABQ== | base64 -d | hexdump -v -e '/1 "%02x"'
cf940005
```

file descriptor for that file from terra:

```json
{
  "file_id": "98fe3ef9-cd19-47f2-ab49-5954e06c567f",
  "file_version": "2022-06-09T09:56:07.810000Z",
  "file_name": "SRR15897021_R1.fastq.gz",
  "content_type": "binary/octet-stream; dcp-type=data",
  "size": 11828186317,
  "sha1": "c15a6a5dc2a7e2a30dc2451c623cd8730ea006d4",
  "sha256": "18193d944a0c31a76b01610c16ebc673f943683e85ab740c31cbfa063fb67d12",
  "crc32c": "cf940005",
  "s3_etag": "2f74fd5a84a932c03f8769e435a88b23-177",
  "schema_type": "file_descriptor",
  "describedBy": "https://schema.humancellatlas.org/system/2.0.0/file_descriptor",
  "schema_version": "2.0.0"
}
```

That is matching with the above calculation.

**Comment by ke4** [comment]
For the 3rd file in this ticket (SRR15897092_R2.fastq.gz):
```
$gsutil ls -L gs://broad-dsp-monster-hca-prod-ebi-storage/prod/9833669b-d694-4b93-a3d0-6b6f9dbcfc10/data/SRR15897092_R2.fastq.gz | grep Hash
    Hash (crc32c):          HW7lng==
    Hash (md5):             4Y+Le93QswE/j2xkbj5VLQ==

$echo HW7lng== | base64 -d | hexdump -v -e '/1 "%02x"'
1d6ee59e
```

file descriptor for that file from terra:

```json
{
  "file_id": "b68c00e4-8584-4b32-82a3-1234d72edd3f",
  "file_version": "2022-06-09T09:56:05.202000Z",
  "file_name": "SRR15897092_R2.fastq.gz",
  "content_type": "binary/octet-stream; dcp-type=data",
  "size": 14962453723,
  "sha1": "87efc09c34ca1646c5edba436e23b2a69a40d6d6",
  "sha256": "6cd65736bbfb03356d5fb1a8d00707ed0a519666a1bbf9511a9c0dba5cab27cc",
  "crc32c": "1d6ee59e",
  "s3_etag": "a35532b4c1d4911ef7c88f3c26f47128-223",
  "schema_type": "file_descriptor",
  "describedBy": "https://schema.humancellatlas.org/system/2.0.0/file_descriptor",
  "schema_version": "2.0.0"
}
```

That is matching with the above calculation.

**Comment by gabsie** [comment]
The import form still needs filling out/modifying. Check with Jeff who needs to do what.

**Comment by ke4** [comment]
We should delete the original submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=a8f8dc60-4c43-470d-a3b5-05135d91e3a6&project=00f6f940-570a-4936-9ab5-f572b7e018f5
when the import form has been filled out for the replacement submission.

**Comment by MightyAx** [comment]
The SOP for retraction is not relevant to the ticket, since we never released the data.
We can use deletion OF [THE BROKEN PROJECT ](https://contribute.data.humancellatlas.org/submissions/detail?uuid=a8f8dc60-4c43-470d-a3b5-05135d91e3a6&project=00f6f940-570a-4936-9ab5-f572b7e018f5)in Ingest UI, and from the Terra Staging Bucket.

**Comment by idazucchi** [comment]
One extra copy of the project was found and deleted

**Comment by gabsie** [comment]
@Amnon to delete the staging area --

**Comment by amnonkhen** [comment]
original staging area deleted.
