### ISSUE TITLE
Prepare slides for "Bioinformatics for PIs" course

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#816]
**Description of the task:**

@gabsie and I have been asked to help with a talk on the "Bioinformatics for PIs" course that is being held Wed-Fri

We need to prepare the slides created by claire, melanie and Henriette for last years' talk

**Acceptance criteria for the task:**

- [ ] Slides are updated
- [ ] Slides are reviewed and sent to the course

**Comment by ke4** [comment]
@ESapenaVentura and @gabsie working on this from today.
