### ISSUE TITLE
Triage new projects ingest - nxn

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#819]
**Projects to triage**

- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=b3491826-b335-4b4e-91d6-2f1d69206091
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=06d01e67-2c57-4767-96f9-33fdc6d4226a
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=d7820c50-6d86-400d-a6d6-9fec0c712a3b
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=08fe0e78-fe02-445f-97bb-98ac4842b985
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=560e3e84-fc22-448f-a3c6-9665f5e4c62f
- [x] https://contribute.data.humancellatlas.org/projects/detail?uuid=615d1d2e-7dd9-47c9-8ef9-3ab81267d50f - duplicate project Wrangled by lattice - deleted our entry
~~https://contribute.data.humancellatlas.org/projects/detail?uuid=5086a7a2-d5d8-44b0-af94-93d5e4c46f8c~~ removed
    - This project is blank
    - it seems to be an error in the nxm script.

**Acceptance criteria**
- [x] All projects have been triaged according to our SOPs

**Comment by gabsie** [comment]
Potentially for @idazucchi to pick up next week.

**Comment by idazucchi** [comment]
the last project looks very weird
![Screenshot 2022-07-01 at 18.35.47.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/ab4cb496-83e5-4329-a176-06e09fa2412b)

![Screenshot 2022-07-01 at 18.35.54.png](https://images.zenhubusercontent.com/615acd999165ed463cb3f02e/e8fc50c6-edb8-488e-8adb-68c903f18ae3)

**Comment by MightyAx** [comment]
Group discussion: the last project seems to be created in error.
@ESapenaVentura to add importer script output for the broken project.

**Comment by idazucchi** [comment]
I've added a new project [here](https://contribute.data.humancellatlas.org/projects/detail?uuid=b2e3b331-53fe-4fba-8a26-394a0bdd969c) with the paper from Enrique's comment

This was probably not added to ingest because the doi cannot be found in Europe PMC
I've opened a ticket about this issue in the Ops board
