### ISSUE TITLE
Test update submissions are exported correctly

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#82]
As a data wrangler I would like to test that the exporter currently exports updates correctly to the GCP staging area so that downstream components are able to update the data records in the TDR and analysis outputs contain the most up to date metadata.

Tests I will try:

* Make edits to the project level metadata
  - delete a contributor
  - edit the content of a field
  - add a field that was formerly empty

* Make edits to biomaterial or protocol entities
  - delete a field
  - edit a field
  - add a field that was formerly empty
  - add a new experimental subgraph i.e. donor_organism->sequence_file

* Do a full update to a project
  - do the updates outlined in ticket #81

For each update the [DCP2 MVP schema specifies](https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?ts=5ef3debd#heading=h.47publlfchdo):
* `entity_id`/`uuid` of all entities remains the same as the previous version
* `version` of each entity is updated to the current time
*  the path to any data file remains unchanged (because it reuses the previously uploaded file

**Comment by mshadbolt** [comment]
First test I will use the `HCA_only` [project](https://ui.ingest.dev.archive.data.humancellatlas.org/projects/detail?uuid=a4804fe4-6135-447a-82da-0a7e1fc55524) I created when testing the project states.

project uuid: a4804fe4-6135-447a-82da-0a7e1fc55524

I edited the project metadata directly in the UI

Changes made:
- deleted GEO accession
- changed ArrayExpress accession to E-MTAB-1234
- added the supplementary link http://celltag.org
- deleted the contributor John Doe

**Comment by mshadbolt** [comment]
First test didn't work because currently the system will not propagate updates done in the UI to either the exporter or to archiving.

The system also ignores project metadata in a spreadsheet so it doesn't seem like there is a clear path to update project level metadata in the current system.

I will move on to try updating other metadata entities.

**Comment by mshadbolt** [comment]
For fun I decided to do a spreadsheet submission to project where I altered the project information, can confirm that the changes to project metadata didn't get propagated into the UI and the submission seemed to get stuck in pending, perhaps because there was nothing to validate?

reported some weirdness in this ticket https://github.com/ebi-ait/hca-ebi-dev-team/issues/197

When I upload using the all submissions route I can submit, but information doesn't get updated in the UI.

And results in 3 new projects in my projects view

**Comment by mshadbolt** [comment]
Now I'll try to update some other entities to see whether that would work

I submitted a new project here: https://ui.ingest.dev.archive.data.humancellatlas.org/projects/detail?uuid=ed7cc937-5065-40cb-8e1c-400691715619

I downloaded the spreadsheet and made the following changes:
- added new sub-graph
  - donor 2 specimen 2 etc. -- > pbmc4k_1000_S2_L001 * 3
- deleted weight fields from donor 1
- added a selected cell type to donor 1 
- changed specimen organ part to hippocampus alveus

Uploaded via 'submit to project'

Doesn't seem to work and I get the error:
:An error occurred importing the file.

"A link from a biomaterial with id specimen_ID_2 to a protocol with id, "collection_protocol_1", is not found in the spreadsheet"

I'm going to assume this is some issue with trying to add new entities and try only doing edits rather than adding whole new entities.

I edited the spreadsheet to remove the new entities and stuck with the edits as above.

I submitted and it seems to get stuck in 'submitted' state and doesn't proceed to exporting even though I ticket box to send to HCA (I think)

**Comment by mshadbolt** [comment]
@aaclan-ebi noted that due to some of the changes made to the UI, updating or adding to a project is no longer possible through the UI

**Comment by mshadbolt** [comment]
Alegria mentioned that the addition submissions should still work so I decided to test this by making a submission of an extra specimen, cell suspension, sequence files that link to the existing donor and protocols.

Submission went Valid and proceeded to 'exporting' submission state, it seems to be stuck in this state but will check back tomorrow.

alegria created a ticket to address updates, this ticket is blocked until that work is completed https://github.com/ebi-ait/hca-ebi-dev-team/issues/201

**Comment by mshadbolt** [comment]
rolando confirmed the project was stuck in exporting and fixed a bug in the exporter and now the project is 'Complete'

**Comment by lauraclarke** [comment]
@mshadbolt Is this still blocked?

**Comment by mshadbolt** [comment]
yes it won't be unblocked until we can do update submissions

**Comment by lauraclarke** [comment]
Okay, no updates are possible at all right now then?

**Comment by mshadbolt** [comment]
see comment above https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/82#issuecomment-653074149
>due to some of the changes made to the UI, updating or adding to a project is no longer possible through the UI

**Comment by lauraclarke** [comment]
Thanks, @clairerye this sounds like we need a ticket for the fix here and to prioritize this work against other issues

@mshadbolt it is reasonable to assume that there can be no further progress made on updates till this issue is fixed. If that is the case it probably makes sense to close this issue and @clairerye can restart testing when the fix is prioritized

**Comment by mshadbolt** [comment]
yes there is already a dev ticket which I mentioned above. Will leave up to Claire whether she wants to keep this open and blocked so that the work that is blocked is visible or whether to close and remake a ticket later

**Comment by clairerye** [comment]
I think its useful having it showing that it is blocked the way Marion has marked it and links to the dev ticket that it is dependent on.
