### ISSUE TITLE
Robust temporal map of human in vitro myelopoiesis using single-cell genomics

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#824]
### Primary Wrangler:
Ami

### Associated files
INGEST: https://contribute.data.humancellatlas.org/projects/detail?uuid=ac289b77-fb12-4a6b-ad43-c0721c698e70&tab=project
* Google Drive:

https://docs.google.com/spreadsheets/d/1LlC4KDUj4lpKluklUvrpq9JIbrhs7y6J/edit#gid=2014509335

https://drive.google.com/drive/folders/1GOwQCJBB6xsWDsAGanmiKKrNhjGfpvue

### Published study links

* Paper: Robust temporal map of human in vitro myelopoiesis using single-cell genomics
https://www.nature.com/articles/s41467-022-30557-4#Sec1

* Accessioned data:
https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11616/
https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11623/
Look on the paper for more links. 

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Thanks @ESapenaVentura, I have made your suggested updates except for the following:

> * I’d use “embryo” instead if bone marrow as the organ model. I know they are only sampling the myeloid system but the “organoids” (embryoid bodies) represent the germinal layers, not just the bone marrow

I understand your point about representing iPSC cell lines with "embryo" as the organ model, but I think for the organoid cultures that "hematopoietic system" (UBERON:0002390) would be best as the model organ (because the myeloid system is part of the hematopoietic system). This is because I think the organ **model** is supposed indicate the intended organ once fully differentiated. 

I am downloading the analysis files currently (taking a long time!) and will message you on slack when they're ready.

**Comment by ESapenaVentura** [comment]
>I understand your point about representing iPSC cell lines with "embryo" as the organ model, but I think for the organoid cultures that "hematopoietic system" (UBERON:0002390) would be best as the model organ (because the myeloid system is part of the hematopoietic system). This is because I think the organ model is supposed to indicate the intended organ once fully differentiated, and they are already being cultured in differentiation media and on the path to differentiation.

Sounds good to me!

About the review,

### Analysis files
- I am missing 2 files from their portal https://www.hipimmuneatlas.org/

Other than that, looks fine to me!

**Comment by ami-day** [comment]
Ok, I have added the macrophage differentiation analysis file but not the LPS file, as discussed and the fastq files are downloading.

**Comment by ami-day** [comment]
Fastq files are downloading very slowly (slower than usual). I aim to get the fastq files upload tomorrow (so they can download overnight).

**Comment by ami-day** [comment]
Moved to Release 20

**Comment by ami-day** [comment]
graph validating

**Comment by ami-day** [comment]
Submitted.

**Comment by MightyAx** [comment]
This project is stuck in exporting because of a timeout checking the google cloud sync, the export jobs are being kept in the error queue so that they can be re-issued.

**Comment by MightyAx** [comment]
Using the [getstatus script](https://github.com/ebi-ait/hca-ebi-dev-team/blob/master/scripts/get_gcp_status/get_status.py) I can see that the GCS transfer finished after 12 hours:
```
Returned transferOperations: {
    "operations": [
        {
            "name": "transferOperations/transferJobs-62e90a452f1d496804222e7d-1659441538317039",
            "metadata": {
                "@type": "type.googleapis.com/google.storagetransfer.v1.TransferOperation",
                "name": "transferOperations/transferJobs-62e90a452f1d496804222e7d-1659441538317039",
                "projectId": "mystical-slate-284720",
                "transferSpec": {
                    "awsS3DataSource": {
                        "bucketName": "org-hca-data-archive-upload-prod",
                        "path": "f433f707-ce4c-4c24-b60f-7cda116ea598/"
                    },
                    "gcsDataSink": {
                        "bucketName": "broad-dsp-monster-hca-prod-ebi-storage",
                        "path": "prod/ac289b77-fb12-4a6b-ad43-c0721c698e70/data/"
                    },
                    "transferOptions": {}
                },
                "startTime": "2022-08-02T11:58:58.469055314Z",
                "endTime": "2022-08-02T23:23:25.009606840Z",
                "status": "SUCCESS",
                "counters": {
                    "objectsFoundFromSource": "321",
                    "bytesFoundFromSource": "3866774267708",
                    "objectsCopiedToSink": "321",
                    "bytesCopiedToSink": "3866774267708"
                },
                "transferJobName": "transferJobs/62e90a452f1d496804222e7d"
            },
            "done": true,
            "response": {
                "@type": "type.googleapis.com/google.protobuf.Empty"
            }
        }
    ]
}
job is done
```
I've patched the ingest job to show that the export is finished:
```
curl -L -X PATCH "https://api.ingest.archive.data.humancellatlas.org/exportJobs/62e90a452f1d496804222e7d" \
-H "Authorization: Bearer snip" \
-H "Content-Type: application/json" \
--data-raw "{
    \"context\": {
        \"totalAssayCount\": 103,
        \"isDataTransferComplete\": true
    }
}"
```
I've moved the errored jobs back to the job queue. This should export without problems now.

**Comment by ke4** [comment]
@ami-day to check if this is exported

**Comment by ami-day** [comment]
Submitted import form.
