### ISSUE TITLE
EGAS00001004653 - Single-Nucleus and In Situ RNA-Sequencing Reveal Cell Topographies in the Human Pancreas-

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#827]
### Associated files

* Google Drive:

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=b3938158-4e8d-4fdb-9e13-9e94270dde16 

### Published study links

* Paper: http://doi.org/10.1053/j.gastro.2020.11.010

* Accessioned data: EGAS00001004653

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
This dataset is stalled because the raw data is in EGA (managed access) and there are no raw or processed gene expression matrices available. I will email the authors to see if they have these available.

**Comment by ami-day** [comment]
I got no reply from the authors, I will mark it as ineligible and ingest and close this ticket.
