### ISSUE TITLE
SRP271375 - SARS-CoV-2 infection of the oral cavity and saliva

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#829]
### Project short name: 
SARS-CoV-2InfectionOralCavity
### Primary Wrangler:
Ami

### Secondary Wrangler:
Ida

### Associated files

* Google Drive:

https://drive.google.com/drive/folders/1ImHp0sxZEEXTWp26NufiI-LSa6G9WQHY

**N.B.** Because the Saliva data is not yet published via a publication (although it is public in their data portal), the authors have requested that we don't yet submit that data. Therefore V2 below is the main version for submission (release 21). It does not include the Saliva data.

**V1 - with Saliva data**
https://docs.google.com/spreadsheets/d/1EZUOzDGefmGqm4s_GGnwY6v2m5WoARCCuLYNx4n0dOo/edit#gid=1592345125

**V2 - without Saliva data**
https://docs.google.com/spreadsheets/d/19j9VAkPH_gGXpN0-9uCIUp_Aedv8IPQW10yeTJwAH1w/edit#gid=1139711375

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=dcbb50d1-9acf-4f70-9fda-b1f63a948c49

### Published study links

* Paper: [SARS-CoV-2 infection of the oral cavity and saliva](https://doi.org/10.1038/s41591-021-01296-8)

* Accessioned data: SRP271375

**N.B.** requested a new collection protocol ontology term: https://github.com/HumanCellAtlas/ontology/issues/117

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ofanobilbao** [comment]
Sounds to me like they are re-analysing existing data but also unpublished data. Worth a check

**Comment by ofanobilbao** [comment]
https://contribute.data.humancellatlas.org/projects/detail?uuid=69d798a1-80b3-4fc8-b124-e3a256422127 seems to me like a pre-print of this exact study. And it also seems like we were reached out directly by the contributor at some point.

**Comment by ami-day** [comment]
Requested a new ontology term: https://github.com/HumanCellAtlas/ontology/issues/117

**Comment by ami-day** [comment]
Emailed authors about obtaining gene expression matrices for the primary neutrophil data.

**Comment by ami-day** [comment]
```6e3fa1af-45a8-426b-8d8a-e5de1e257707```

**Comment by ami-day** [comment]
Stuck in "graph validation requested" state

**Comment by ami-day** [comment]
Re-triggered graph validation

**Comment by ami-day** [comment]
Graph valid

**Comment by idazucchi** [comment]
Hi Ami, I'm done secondary reviewing! It looks great I only have a few comments

### Project
- the project and study accession come from a different publication, I think that this data was re re-analysed in this paper
- the cell count should be 13,824


### Donor
- there is additional metadata like sex age ethnicity and disease in the supplementary material table 1, tabs  1 and 2, 

### Enrichment
- `enrichment_protocol_gingiva_centrifugation` is not really an enrichment step, it can be omitted


### Analysis protocol
- `analysis_protocol_cell_type_assignment_1` can be fused with `analysis_protocol_quantification_2` since they both only apply to the salivary gland data
- a protocol is needed to describe how the two datasets were combined in `byrd_warner_integrated.processed.h5ad`

### Analysis file
- `byrd20_gingiva.processed.h5ad` should not be linked to `analysis_protocol_quantification_2`

**Comment by ami-day** [comment]
Ok done, re-submitting it.

**Comment by ami-day** [comment]
Getting an error trying to delete the old submission from ingest prod. Need to upload the updated submission.

**Comment by ami-day** [comment]
Now getting an error importing the new submission.

**Comment by MightyAx** [comment]
submission deletion was successful, import should now work okay.

**Comment by ami-day** [comment]
Re-import was successful.

**Comment by ami-day** [comment]
Exported and submitted import form.

**Comment by ESapenaVentura** [comment]
@MightyAx to investigate if this has actually been exported

**Comment by MightyAx** [comment]
waiting on issue: ebi-ait/hca-ebi-wrangler-central#926

**Comment by MightyAx** [comment]
Export Successful

**Comment by ami-day** [comment]
Looks good.
