### ISSUE TITLE
Stimulated peripheral blood mononuclear cells (Ucar)

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#83]
**Primary Wrangler:**
Enrique
**Secondary Wrangler:**
Ray, Marion

**Associated files:**
`StimulatedPBMCs-issue83`
Google Drive:
<https://drive.google.com/drive/folders/1tec_2-dgyH-z8Ak2taBhnJdPsMLLpANB>
**Key Events**

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [x] Receive T&C form filled out by at least 1 representative of group/project
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data files
- [x] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata
- [x] Run graph validator
- [x] Check linking
- [x] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Get final approval of submission including metadata spreadsheet and data files
- [x] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Email UX to inform that they're ready to send survey

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by rays22** [comment]
* Received `HCA Dataset Questionnaire` response.
* Pre-filling HCA spreadsheet to be sent.

**Comment by rays22** [comment]
There are responses in questionnaire that I need to follow up before sending a reply:

```
* Were the donors/mice alive at the time of sample collection?  Response: Alive
* What type of consent do you have to release the data and metadata for your dataset?   [Donor level metadata]	Response: not sure
```

**Comment by rays22** [comment]
Sent spreadsheet and a reminder about T&C form.

**Comment by ami-day** [comment]
Sent email with data upload instructions and asked if they need upload area credentials (Ray has already created an upload area for their project)

**Comment by ami-day** [comment]
Sent them an email with upload area uuid and aws credentials
Gave them an estimate of within 2 weeks to get accessions to them

**Comment by ami-day** [comment]
Still awaiting reply from Nathan with:

- filled in metadata spreadsheet
- confirmation that they have uploaded their data to the upload area I sent them

**Comment by ESapenaVentura** [comment]
We got a spreadsheet from Nathan, sent an email with the spreadsheet back (curated) for them to review and make sure we fully captured their experiment.

Decisions with this dataset are as following:

- Archive CITE-Seq (with a little bit of manual metadata tweaking)
- Archive VCF files in EVA
   - Currently detected an error (Tried to redefine a protected keyword in VCF) in one of the files. Checking all the files to make sure it is the only error before coming back to them
- **DON'T EXPORT FOR NOW**: Before exporting, we need to figure out how to change the metadata in ingest with minimal impact.

**Comment by ESapenaVentura** [comment]
The latest vcf files are uploaded and have been validated - They are valid.

Filling the EVA metadata. Will need to wait until we have the BioSamples/ENA accessions

**Comment by ESapenaVentura** [comment]
Received latest spreadsheet on friday, saved it in the drive folder

**Comment by ESapenaVentura** [comment]
Updated the spreadsheet with a couple of corrections and additions:
- Added Ray, Marion and myself as wranglers
- Added an enrichment protocol column in cell suspension to link the enrichment properly.
- Added ontologies. There is no ontology for Illumina Novaseq S4, so I need to request the term.

@rays22 will secondary wrangle this dataset.

**Comment by rays22** [comment]
Spreadsheet version `hca_spreadsheet-2020-Lawlor_ES_no_vcf_v5_ontologies.xlsx` has failed the following graph validator tests:

```
20-09-07 14:34:51 [ingest_graph_validator.actions.test_action] - ERROR: test [no_orphans.adoc] failed: non-empty result.

20-09-07 14:34:52 [ingest_graph_validator.actions.test_action] - ERROR: test [min_experimental_design_length_5.adoc] failed: non-empty result.

20-09-07 14:34:52 [ingest_graph_validator.actions.test_action] - ERROR: test [ensure_seq_libr_prep_protocols.adoc] failed: non-empty result.
```
The problems might stem from the way the pooled cell suspensions are modelled in the metadata spreadsheet.
There are 10 distinct cell suspensions in the spreadsheet. Shouldn't there be only a single pooled cell suspension, linked to 10 distinct specimen, linked to 10 donors?

**Comment by rays22** [comment]
The metadata in the spreadsheet and the experimental design graph look correct to me for spreadsheet version `hca_spreadsheet-2020-Lawlor_no_vcf_v6_ontologies_Ray_review.xlsx`.[
![graph_issue83](https://user-images.githubusercontent.com/25171986/92467388-6dbc5100-f1c9-11ea-8f79-2f2007346153.png)
](url)

**Comment by ESapenaVentura** [comment]
- CITE-Seq data is archived under ENA (Accessions under latest spreadsheet)

- VCF data is currently being archived

**Comment by rays22** [comment]
![exp_graph-hca_spreadsheet-2020-Lawlor_no_vcf_v6_ontologies_Ray_review](https://user-images.githubusercontent.com/25171986/94053909-d4995700-fdd2-11ea-978b-02510506ddfe.png)
Full experimental design graph from `hca_spreadsheet-2020-Lawlor_no_vcf_v6_ontologies_Ray_review.xlsx`.

**Comment by rays22** [comment]
* Project label: CITEseqPBMCProject
* Dissecting the protein and transcriptional responses of human immune cells to T cell and monocyte specific activation
Submission `Sep 8, 2020, 10:32:12 AM; dfb86fe3-ef1f-42ed-b559-d74f4b3b3a11` has been archived in BioStudies and BioSamples.
* BioStudies accession: S-SUBS15
* INSDC project accession: ERP124005

@ESapenaVentura :  is there anything else left to archive (e.g. VCFs)?

**Comment by ESapenaVentura** [comment]
If I remember well, the EVA submission gets added to the normal ENA submission so we didn't get any accession from EVA

Might need to double check, though

**Comment by lauraclarke** [comment]
@ESapenaVentura is this archived already? are the next asks export (when we start that again) and send to SCEA?

**Comment by ESapenaVentura** [comment]
This is, for the moment, not suitable for SCEA

But yes, it is already archived

**Comment by ami-day** [comment]
This dataset has not been made public yet, we are waiting until they publish the manuscript.

Another problem with this dataset is the multiplexing, which might prove difficult as the pipelines currently don't support that.

**Comment by rays22** [comment]
This dataset has been exported to the Terra staging area.

**Comment by lauraclarke** [comment]
Has this one already gone to SCEA or do they not accept CITE-seq

**Comment by ESapenaVentura** [comment]
There is now a paper for this dataset https://www.frontiersin.org/articles/10.3389/fimmu.2021.636720/full that the authors would like included

**Comment by rays22** [comment]
I can confirm that the update was successfully exported.
* New metadata file with the publication update: `project_UUID/metadata/project/projectUUID_2021-05-12T14:05:50.850000Z.json`

```
    "publications": [                                                                                                   
        {                                                                                                               
            "doi": "10.3389/fimmu.2021.636720",                                                                         
            "url": "https://doi.org/10.3389/fimmu.2021.636720",                                                         
            "authors": [                                                                                                
                "Lawlor N",                                                                                             
                "Nehar-Belaid D",                                                                                       
                "Grassmann JDS",                                                                                        
                "Stoeckius M",                                                                                          
                "Smibert P",                                                                                            
                "Stitzel ML",                                                                                           
                "Pascual V",                                                                                            
                "Banchereau J",                                                                                         
                "Williams A",                                                                                           
                "Ucar D"                                                                                                
            ],                                                                                                          
            "title": "Single Cell Analysis of Blood Mononuclear Cells Stimulated Through Either LPS or Anti-CD3 and     
Anti-CD28",                                                                                                             
            "pmid": 33815388                                                                                            
        }                                                                                                               
    ],                                                                                                                  
```

- [ ]  Notified the HCA production data import team about the export.

**Comment by rays22** [comment]
There was an issue with importing the update into the [DCP.](https://data.humancellatlas.org/explore/projects/efea6426-510a-4b60-9a19-277e52bfa815)

>Hi ray, the staging area located at ` gs://broad-dsp-monster-hca-prod-ebi-storage/prod/efea6426-510a-4b60-9a19-277e52bfa81` is failing json validation on the collection_time property for several of the specimen_from_organism metadata files. For example:
gs://broad-dsp-monster-hca-prod-ebi-storage/prod/efea6426-510a-4b60-9a19-277e52bfa815/metadata/specimen_from_organism/14636efe-85cd-4c22-8ca6-e119e7600714_2020-09-08T09:32:16.090000Z.json fails the oneOf validation against the specimen_from_organism schema for the value 2018-07. I can provide more details if needed (cc: Claire Rye)
...
To clarify, the dataset is fine and will be included in the next release (7) without any changes from our side or need for re-export. Jeff (he/him) do you want us to complete another import form?
...
Jeff Korte  6 days ago
Claire Rye, yes please.  Please indicate it is for Release 7.

I have completed a new import form for release 7.
