### ISSUE TITLE
GSE159745 - ReconstituitionHumanThymus

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#834]
### Project short name: 
ReconstituitionHumanThymus
### Primary Wrangler:
Ami

### Associated files

* Google Drive:
[folder](https://drive.google.com/drive/folders/10aZNwCg4vJBotfF1ChbZ_m-4zQ3lvT_S
)
[sheet](https://docs.google.com/spreadsheets/d/1CMzo3J9gtXrByIz2A8wmfOhyKgeKEUi9/edit#gid=1611893265)

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=3e92c74d-256c-40cd-9273-16f155da8342

### Published study links

* Paper: [Reconstitution of a functional human thymus by postnatal stromal progenitor cells and natural whole-organ scaffolds](https://doi.org/10.1038/s41467-020-20082-7)

* Accessioned data: GSE159745

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Almost done curating. Requested NCBI Cloud Delivery of fastq files.

**Comment by ami-day** [comment]
Submitted new HCA ontology request for cell type ontologies: "stromal cell of thymus" and "interstitial cell of thymus"

**Comment by ami-day** [comment]
Requires some info. from authors

**Comment by Wkt8** [comment]
Assigning self for secondary-review

**Comment by Wkt8** [comment]
Project tab:
- I don't think the cell count of 51600 is right in the project level metadata. Do you have a better idea of what it might be? 

Donor_Organism: 
- You currently have 8 donor organisms for the GEO dataset, 2 donor organisms for each sample. I think these may be duplicates and there was only one donor for the GEO dataset (scRNA-seq)
- What evidence do you have that each of the GEO samples originated from a separate donor? It seems like they all come from a 6 month old healthy female and each of the different samples is a different cell subpopulation 
	- e.g. Type1 mTEC, Type 1 cTEC, Type 2 mTEC, Type 2 cTEC 
- You could also add the gender (female) and age (6 months) metadata 

Cell_Suspension
- missing the thymic interstitial cell type ontology term. I had a look at 'Interstitial cell' is available but might not be specific enough. Do you want to request a new ontology term? 
- Could also add cortical thymic epithelial cell and medullary thymic epithelial cell to the scRNA-seq cell suspensions


Sequence_File
- Could not really check these as they don't have the appropriate file names at the moment 
- Looking at the SRA run selector it looks like the fastqs are available though, which is great! 

Analysis Protocol
- Ontology term and ontology term labels missing from analysis_protocol.type

**Comment by ami-day** [comment]
> * missing the thymic interstitial cell type ontology term. I had a look at 'Interstitial cell' is available but might not be specific enough. Do you want to request a new ontology term?

Thanks @Wkt8 , working on these updates now. I had requested a new cel type ontoology term for "interstitial cell of thymus" and also "stromal cell of thymus" above it, so they will need to become available before I submit.

**Comment by ami-day** [comment]
Downloading data files

**Comment by ami-day** [comment]
bf632dd7-a33a-446c-b3e5-193f27abc05a

**Comment by ami-day** [comment]
synced files

**Comment by ami-day** [comment]
Submitted.

**Comment by ami-day** [comment]
Exported, submitted import form.

**Comment by ami-day** [comment]
Looks fine in data browser.

**Comment by idazucchi** [comment]
**Missing fastq files**
While cleaning up the hca-util areas I noticed this project had a different number of fastq files in the hca-util area from what is available in ingest. No explanation is given in here to indicate why the files are not included in the project.

3 files are missing for accession SRP287966 - run SRR12857069 is missing)

**Action**
I'm updating the accession with the missing files

**Comment by idazucchi** [comment]
tried to export project but spreadsheet generation fails due to sequence_file schema version error

```
{"log":"2023-08-03 10:56:23,020 - TerraSpreadsheetExporter - ERROR - submission_uuid:d1ce4d66-ad64-4a4d-9ac6-cd1eabc0aa20 - export_job_id:64cb879b1bfdb743144de671 - project_uuid:3e92c74d-256c-40cd-9273-16f155da8342 - The concrete entity schema version should be consistent across entities. Multiple versions of same concrete entity schema found: ['https://schema.humancellatlas.org/type/file/9.4.0/sequence_file', 'https://schema.humancellatlas.org/type/file/9.5.0/sequence_file']\n","stream":"stderr","time":"2023-08-03T10:56:23.02120782Z"}
```
   - Amnon changed status so Ida can edit the metadata and update schema to 9.5.0

**Comment by idazucchi** [comment]
I've update the schema version to 9.5.0 for all sequence_file, exported and filled out the import form

**Comment by idazucchi** [comment]
all the new files made to the browser as well as the spreadsheet
