### ISSUE TITLE
GSE132509 - Single-cell analysis of childhood leukemia reveals a link between developmental states and ribosomal protein expression as a source of intra-individual heterogeneity

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#836]
### Primary Wrangler:
Ami

### Secondary Wrangler:
Wei Kheng Teh

### Associated files

* Google Drive:

https://drive.google.com/drive/folders/1U12GudFLHcYyHMMHkyDabFLv8akr9gUn

https://docs.google.com/spreadsheets/d/1BKFLWX8xT4xfwbtj0Q_sUByh1cl7t0rj2CjpBJIo20Q/edit#gid=1714991278

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=1fa8b11f-56fa-45a6-a777-6af70e17a6b3

### Published study links

* Paper: https://doi.org/10.1101/683854

* Accessioned data: GSE132509

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Requested data from NCBI Cloud Delivery.

**Comment by ami-day** [comment]
`d00dc39a-72ae-4228-87a7-fb9f5112e336`

**Comment by ami-day** [comment]
Graph validating

**Comment by ami-day** [comment]
Stuck in "graph validation requested" state

**Comment by ami-day** [comment]
Graph valid

**Comment by Wkt8** [comment]
Assigning self for secondary review

**Comment by Wkt8** [comment]
Hey @ami-day 

Looks good! Paper is interesting and thankfully straightforward to wrangle. Thought the way you modelled it was clear and easy to understand. 

Cell_Suspension tab: 
Shouldn't be a problem but one of the links for the INSDC Experiment Accession (SRX6034690) links instead to the SRX6034691

Ingest Project Page:
- Would be good to add yourself as a curator to the ingest link
- The DOI has changed (it is now a published paper) so would be good to change that in the publications tab (https://doi.org/10.1038/s41598-020-64929-x)
- Funding tab needs to be filled in

**Comment by ami-day** [comment]
> Hey @ami-day
> 
> Looks good! Paper is interesting and thankfully straightforward to wrangle. Thought the way you modelled it was clear and easy to understand.
> 
> Cell_Suspension tab: Shouldn't be a problem but one of the links for the INSDC Experiment Accession (SRX6034690) links instead to the SRX6034691
> 
> Ingest Project Page:
> 
> * Would be good to add yourself as a curator to the ingest link
> * The DOI has changed (it is now a published paper) so would be good to change that in the publications tab (https://doi.org/10.1038/s41598-020-64929-x)
> * Funding tab needs to be filled in

Ok thanks, I have made the changes and have submitted it.

**Comment by Wkt8** [comment]
Import form needs to be filled in, then move to 'Exported'

**Comment by ami-day** [comment]
Submitted form.

**Comment by ami-day** [comment]
looks ok
