### ISSUE TITLE
kuppe's dataset stuck in exporting

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#838]
see dataset ticket: ebi-ait/hca-ebi-wrangler-central#661

The [submission](https://contribute.data.humancellatlas.org/submissions/detail?uuid=b41cb309-7f54-47de-aa07-23e853f6e879&project=e9f36305-d857-44a3-93f0-df4e6007dc97) has been updated and it's gotten stuck in exporting. 

The steps that got it stuck in exporting are:
1. Update the project metadata
2. Re-validate the submission
3. Re-validate the graph. This re-validation had to be set up manually because there is a ingest-graph-validator test that is blocking this submission. A PR was opened and is currently blocked by the integration tests failing
4. Once set up to graph-valid, asked @amnonkhen to re-deploy the state tracker
5. Hit export afterwards with the "export only metadata" flag on
6. Once a couple hours had pass, I have deleted manually from the staging area the following metadata:
   - `file_descriptors/`
   - `links/`
   - `metadata/`
      - `analysis_file/`
      - `image_file/`

An interesting fact about this submission, and the reason I had to do the last step, is that it is a R16 dataset. R16 datasets' staging areas were recently deleted by the import team and, therefore, have no data files anymore.

However, it is still stuck in exporting. 

What needs to be done is, in order of priority:
- [x] Investigate if all the needed entities have been exported
  - [x] fix problem discovered by Amnon and Ida discovered with author initials (Enrique)
  - [x] re-export
- [x] Investigate why this dataset got stuck in exporting
  - we don't know the reason, and it does not reproduce. In the future additional logging for the export process may shed light on stuck submissions.
- [x] set the project to _Exported_
- [x] make sure import form contains an entry to process this dataset on R18
- [ ] check the project in the browser after it has been imported
- [ ] Write out conclusions of the investigation and follow ups (tickets, PRs, etc)

Useful links:
- [terra staging area](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/e9f36305-d857-44a3-93f0-df4e6007dc97)
- [hca data browser](https://data.humancellatlas.org/explore/projects/e9f36305-d857-44a3-93f0-df4e6007dc97)

**Comment by ofanobilbao** [comment]
Enrique submitted the import form on Friday. If it doesn't make it we will need to give a heads-up to Jeff

**Comment by amnonkhen** [comment]
There was a problem with the author initials that Ida and Amnon discovered and Enrique fixed. I am not working on re-exporting.

**Comment by amnonkhen** [comment]
Last actions:
- [ ] @amnonkhen and @ESapenaVentura fixed the author initials 
- [ ] re-exported the project
- [ ] @amnonkhen checked [project json](https://console.cloud.google.com/storage/browser/_details/broad-dsp-monster-hca-prod-ebi-storage/prod/e9f36305-d857-44a3-93f0-df4e6007dc97/metadata/project/e9f36305-d857-44a3-93f0-df4e6007dc97_2022-06-27T14:37:26.954000Z.json;tab=live_object) to contain authors in the proper format
