### ISSUE TITLE
stuck in metadata invalid: humanHeartFailureCellularLandscape

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#839]
*Project Info*
uuid: `135f7f5c-4a85-4bcf-9f7c-4f035ff1e428`
project short name: humanHeartFailureCellularLandscape
primary wrangler: Rachel Schwartz

All files were synced to submission yesterday 06-23-2022; it appears all the files are stuck in 'validating' state except for 4 which are stuck in a missing state

Note:
assign to the current dev on operations.

- [terra staging area](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/135f7f5c-4a85-4bcf-9f7c-4f035ff1e428)
- [hca data browser](https://data.humancellatlas.org/explore/projects/135f7f5c-4a85-4bcf-9f7c-4f035ff1e428)
- [ingest ui](https://contribute.data.humancellatlas.org/projects/detail?uuid=135f7f5c-4a85-4bcf-9f7c-4f035ff1e428)
- [submission in monitoring](https://monitoring.ingest.archive.data.humancellatlas.org/goto/INCSTzR4k)
- [s3 upload area](https://s3.console.aws.amazon.com/s3/buckets/org-hca-data-archive-upload-prod?region=us-east-1&prefix=f75b08d3-4d2f-4611-98c0-86fa8a07ac49/&showversions=false)

**Comment by amnonkhen** [comment]
Tasks:

- [ ] investigate validation errors on the 4 files

```
      "errorType": "FILE_NOT_UPLOADED",
      "message": "File cloudUrl property not set.",
      "userFriendlyMessage": "File not uploaded."
```

**Comment by willrockout** [comment]
Just wanted to add that 43 files have been stuck in validating since 6-23-22.

**Comment by amnonkhen** [comment]
Looking at [SRR15835858_R2.fastq.gz](https://api.ingest.archive.data.humancellatlas.org/files/62b4a6a5b85bb84636c5e797) I notice it is missing the following attributes:

-  cloudUrl
-  checksums

-

**Comment by willrockout** [comment]
@Wkt8 for some reason your comment isn't coming up on github but I'll respond here. Thanks for catching the files had finished validating. In regards to the missing files, the bit I'm confused about is when I run an AWS ls it says the files exist in the ingest area. I can try re-syncing those 4 files if @amnonkhen is done looking over the issue?

**Comment by ESapenaVentura** [comment]
Downprioritised for now while workload is bigger than capacity - Targetting for next release

**Comment by amnonkhen** [comment]
- The [4 missing files](https://files.slack.com/files-pri/T2EQJFTMJ-F03MQBBKXH7/image.png) are now valid.
- 15 are still validating.

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to log in what changes were made

**Comment by ESapenaVentura** [comment]
The 4 missing files are now valid because I used the [upload service API](https://upload.archive.data.humancellatlas.org/), endpoint `/v1/area/{upload_area_uuid}/{filename}` to indicate the upload of the files that were missing

In the case of the re-validation of files in validating status, I just used the script we have in the [hca-ebi-dev repo](https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/retrigger_file_validation), following the instructions in the readme

**Comment by ESapenaVentura** [comment]
re-triggered validation again for 15 files as they are completely stuck

**Comment by ESapenaVentura** [comment]
Currently 8 files validating

**Comment by amnonkhen** [comment]
Graph validation passed.
Exporting the dataset.
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/82277c4a-6e70-4762-86a5-45864f201da7)

**Comment by Wkt8** [comment]
Check back at the end of the day.

**Comment by amnonkhen** [comment]
Dataset is exported. I [notified Rachel and Will on slack](https://humancellatlas.slack.com/archives/C03M539TMDL/p1657908776015439).
