### ISSUE TITLE
Haniffa - Fetal Bone Marrow

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#84]
**Primary Wrangler:**
Wei Kheng
Ida
**Secondary Wrangler:**
@ESapenaVentura

**Associated files:**

Google Drive:
https://drive.google.com/open?id=1YvdAlzQxewjADa9d9Z-zAwoWqwHF8IUu
Paper: Blood and immune development in human
fetal bone marrow and Down syndrome
https://www.nature.com/articles/s41586-021-03929-x

**Accessions**
Haniffa Lab 10X - [E-MTAB-9389](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-9389/)
Haniffa Lab 10X Down donor samples - [E-MTAB-9389](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10042/)
Haniffa Lab SS2 - [E-MTAB-9801](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-9801/)
Behjati Lab 10X - [ERP125305](https://www.ebi.ac.uk/ena/browser/view/PRJEB41514)
CITE-seq - TBA

**Key Events**

- [ ] ~~Send initial instructions about contributing, including questionnaire and T&Cs~~
- [x] Assign the Primary Wrangler
- [ ] ~~Receive T&C form filled out by at least 1 representative of group/project~~
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data files
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator
- [ ] Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission including metadata spreadsheet and data files
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Email UX to inform that they're ready to send survey

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by mshadbolt** [comment]
Was contacted by Michael Mather from the Haniffa lab needing help with an ArrayExpress submission. I convinced them to let us handle the submission to DCP and ArrayExpress so this will be a bit of a pilot on the process of getting data from our ui, exported to DCP, archived in ENA and then into MAGE-TAB and handed on to ArrayExpress.

All I know so far is that it is a fetal bone marrow project and it has a lot of SS2 data. It is part of the WSSS award.

**Comment by mshadbolt** [comment]
Spoke to Simone and Michael and explained that they would need to have individual samples for each SS2 cell. They were struggling because they were trying to add 100s/1000s of files to a single sample, thinking of a sample as a specimen rather than a cell.

We decided it would be easiest if they finish their submission for the 10x part of their experiment in ArrayExpress and then pass on the metadata from this for us to convert to HCA format after they have their manuscript submitted. At that time we can work together to sort out the SS2 submission as it is necessarily a bit more complicated.

**Comment by mshadbolt** [comment]
Simone got back to me and has provided me reviewer login for their 10X submission and a spreadsheet with their SS2 metadata.

I will be converting the 10X submission to HCA format and helping them convert the SS2 to both HCA and ArrayExpress format. They are hoping to have the SS2 submission complete by the time the manuscript has gone through first round reviews (Octoberish)

**Comment by mshadbolt** [comment]
This project is quite a large collaboration and includes data from another ENA submission -  ERP125305, as well as further CITE-SEQ data that is yet to be archived. I have updated the main body with the known accessions to date, the AE accessions are not yet public

**Comment by mshadbolt** [comment]
apparently the manuscript is in review with nature, so we should get some more details in the next few weeks hopefully.

**Comment by Wkt8** [comment]
This is now a hca-publication (https://www.biorxiv.org/content/10.1101/2021.06.25.449771v1.full), Muzz has stated that they expect the ArrayExpress accessions (still not public) to be public in a month or so and will check back with them then.

**Comment by Wkt8** [comment]
Accessions are now public

**Comment by Wkt8** [comment]
There's really three accessions to the paper: 
10x (E-MTAB-9389)
SS2 (E-MTAB-9801)
10x (E-MTAB-10042)

**Comment by ofanobilbao** [comment]
It now has a peer reviewed publication: https://www.nature.com/articles/s41586-021-03929-x

**Comment by ofanobilbao** [comment]
https://doi.org/10.1038/s41586-021-03929-x

**Comment by ami-day** [comment]
Hi @Wkt8 did you ever hear back from the authors? shall I take this dataset on or not?

**Comment by Wkt8** [comment]
See recent emails from Simone and Muzz, this is now an update ticket as UCSC actually wrangled this project. Simone has come back to us with a list of things to update (for the catalogue and for the data portal). See below.

----------
Thank you also for adding our project to the data catalogue. A few edits if that's okay with you?

- [ ] organ = bone marrow, cord blood, liver (all from human)
- [ ] technology = 10x 3' v2, 10x 5' v2, 10x VDJ-TCR, 10x VDJ-BCR, Smart-seq2, CITE-seq
- [ ] cell count = total post-QC is 164,709 (adding the breakdown below into text will help users, please include if possible)
- [ ] 119,971 for 10x scRNA-seq (103,228 from fetal bone marrow; 16,743 from Down syndrome fetal bone marrow) 
- [ ] 486 for Smart-seq2 scRNA-seq (from fetal bone marrow)
- [ ] 44,252 for CITE-seq (35,273 from CD34+ fetal bone marrow, fetal liver, and cord blood; 8,978 from non-FACs sorted fetal bone marrow)
- [ ] data location - the data can also be downloaded more readily as transformed counts within an object at our data portal - https://fbm.cellatlas.io/. also, do you mind please putting the ArrayExpress accesion first? These contain overall study design and explanations of data on other platforms, whereas the ENA data is jusr from one biological replicate and doesn't contain this information, so isnt the most usefl to put first. Also, the hyperlink for the AE accessions is not working.

With regards to the data portal:
- [ ] Much of the description text (from "overall design" onward), are taken from the GEO accession for the CITE-seq data, and do not incorporate much of the overall study design. Could you please replace this text with the data accesiblity statement from the manuscript (as well as the breakdown of cell numbers given above?).
- [ ] https://fbm.cellatlas.io/ can be added under analysis portals
- [ ] there are two matrices that can be added from ": E-MTAB-9389" and one matrix that can be added from "E-MTAB-9801". These are in the csv format named "....processed.zip" and are raw count matrices. If you can add descriptions for each file, please let me know and i will provide
- [ ] could organ and anatomical part please reflect: human fetal bone marrow, fetal cord blood, liver 
- [ ] selected cell types: heterogenous
- [ ] disease status: typical and trisomy 21
- [ ] developmental stage - first and second trimester
- [ ] library construction - as above: 10x 3' v2, 10x 5' v2, 10x VDJ-TCR, 10x VDJ-BCR, Smart-seq2, CITE-seq
- [ ] count estimate as above
- [ ] you can also put muzz as contributor and Newcastle Uni for collaborating organisations
- [ ] I have also noticed that our accession "Decoding the development of the blood and immune systems during human fetal liver haematopoiesis" on the project catalogue should take the name of its peer-reviewed article: "Decoding human fetal liver haematopoiesis"
- [ ]

**Comment by idazucchi** [comment]
I'm wrangling E-MTAB-9389, I've emailed Simone to ask for some clarifications

**Comment by idazucchi** [comment]
**Mail exchange [here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/eip3n7tEjws/m/FjacvoAeAgAJ)**

#### An update:
There are 5 accessions:
- 1 from GEO - wrangled by UCSC team and already exported
- 3 from ArrayExapress - done wrangling them
- 1 from ENA - currently wrangling
There are more files that I would expect and I'm trying to understand if they are technical replicates

**Comment by idazucchi** [comment]
About the ENA dataset: the authors confirmed that there is just one donor, but 8 distinct samples were taken. Each library has sequencing technical replicates

**Comment by idazucchi** [comment]
I've put this in secondary review while the issue with the missing links to the reused collection protocol is being investigated ([Ops ticket](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/699))

The up-to-date spreadsheet is [here](https://docs.google.com/spreadsheets/d/1RU-KtREX6CDc1Skvi_Sji30JOfsM8sFB/edit?usp=sharing&ouid=113452802627011629126&rtpof=true&sd=true)

**Comment by amnonkhen** [comment]
@ESapenaVentura to secondary review

**Comment by idazucchi** [comment]
the linking issue was resolved and the submission is graph valid

**Comment by ESapenaVentura** [comment]
Hi @idazucchi ! My goodness this is a big dataset, congratulations on wrangling this! I have a couple of notes:

## Project
- Description seems a bit weirdly formatted in the UI for me, but maybe it’s just how it looks like
- Missing accession PRJNA702168 (==SRP306736). Interestingly, only ENA gives a distinctive PRJ accession, when looking into the PRJEB to find the American equivalent I found that they don’t change the accession (https://www.ncbi.nlm.nih.gov/sra/ERX5814824[accn])

-Supplementary link(s): Please use just the link! 

## Project - Publications:
-Very small thing but please take out the #Abs1 at the end (Usually the hashes point to specific parts of the paper, but we should try to point at the paper)

## Protocols
-Are the dissociation protocols any different? I noticed that you added a new dissociation protocol in your spreadsheet (FBM_mechanical) and the description is very similar to https://api.ingest.archive.data.humancellatlas.org/protocols/61a69a71c7b79307bb4852d1 , which is one of the dissociation protocols of the UCSC submission


Other than that, LGTM! I am sure this took a lot of work, especially with all the different enrichment protocols, cell suspensions and crossed protocols/donors in one paper

About your questions:
- Unfortunately so far we can only input certain data portals. I think your idea to wrangle to cellxgene is great though!
- I don't understand the question, I couldn't find any "heterogeneous" inferred cell type?
- I think it's fine to leave it to a more broad term like the one you chose
- This one is a bit tricky. it's only going to display the number of cells according to the cell suspension count; this will be solved when the browser implements the project estimated cell count, but for now it's only going to display the sum of SS2 cell counts

**Comment by idazucchi** [comment]
I've applied the changes and filled out the import form

**Comment by ESapenaVentura** [comment]
An ontology ID is not displaying properly (added as a label). @idazucchi is going to fix it and let the UCSC team know

**Comment by ESapenaVentura** [comment]
@idazucchi when submissions are in complete status, unfortunately they can't be easily reverted to metadata valid (as they no longer have the data files, they will fail to validate if they jump back to that state)

What we've usually done is make the changes and then get them in metadata valid status, but you need a dev for that!

**Comment by idazucchi** [comment]
I didn't know that! The submission was put into metadata valid by Jacob so I can move forward with graph validation and submission of the updated metadata
