### ISSUE TITLE
error triggering graph validation

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#841]
Reported by @ami-day 

> When i try to trigger graph validation I get a 401 error: https://contribute.data.humancellatlas.org/submissions/detail?uuid=fce1dc75-017f-40e7-bc17-b57af4957d46&project=ec6476ee-2949-41f3-947b-8eef41d6d3ac "an error occurred while triggering validation -  Http failure response for https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/62b9d234b85bb84636c610da/graphValidationRequestedEvent: 401 OK "

**Comment by ESapenaVentura** [comment]
There are no submissions for this dataset

**Comment by ofanobilbao** [comment]
@ami-day see comment above. Can we close this ticket? If not, provide more detail, please

**Comment by amnonkhen** [comment]
no response - closing.
