### ISSUE TITLE
re-exporting dcp1 projects

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#843]
See [summary of discussion](https://miro.com/app/board/uXjVOoChXfE=/) between @ESapenaVentura 7 @amnonkhen 

dcp1 projects has several issues preventing them from being re-exported:

1. missing file attributes, e.g. size, type
2. missing data files (not relevant for metadata updates)
3. missing dcpVersion attribute - already fixed (#481), here for completeness

Currently there are no dcp1 projects that need updates but:
- ebi-ait/dcp-ingest-central#793
- #765

**Comment by amnonkhen** [comment]
Per 28/9 Ops Review session, this would not be needed for another 2 months. Revisit early Dec.

**Comment by ofanobilbao** [comment]
Closing this ticket as we seem to keep going in circles with this. We've discussed in Ops Review Meeting recently and Gabs was assigned with creating a ticket in Dev board instead to address the need
