### ISSUE TITLE
Change metadata-schema pullapprove config to not check for schema linter

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#845]
**Description of the issue**
Since the schema linter is triggered by the github actions and displayed on the PR, we should make it so that pullapprove does not check for it to request the reviews.

**Comment by idazucchi** [comment]
I've made the change in staging and merged into Master with a hotfix
[this](https://github.com/HumanCellAtlas/metadata-schema/pull/1476) is the PR
