### ISSUE TITLE
Fix the script to generate markdown human-readable schema docs

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#846]
**Description of the task:**

Currently, the script that is used to generate the human-readable metadata schema documentation is generating the hyperlinks wrong, using underscores instead of hyphens when linking within a document.

As a data wrangler, I want the script to generate human-readable metadata schema docs (In [here](https://github.com/HumanCellAtlas/metadata-schema/blob/master/src/human_readable_json.py) to generate readable markdowns that point to the proper locations within the document.

**Acceptance criteria for the task:**

- [x] The script is fixed and a PR is opened.
- [x] The PR is reviewed by @amnonkhen 
- [x] The PR is merged to staging and released to master

**Comment by idazucchi** [comment]
@ESapenaVentura to link the PR
@amnonkhen to review the PR

**Comment by ESapenaVentura** [comment]
@ESapenaVentura has reviewed, @amnonkhen to answer to messages

**Comment by idazucchi** [comment]
@MightyAx to take a look

**Comment by MightyAx** [comment]
Added the python tests to GitHub actions.
@ESapenaVentura to re-review

**Comment by ESapenaVentura** [comment]
I have re-reviewed and merged the PR!
