### ISSUE TITLE
HumanHematopoieticProfiling - CellxGene

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#848]
**Collection/dataset this task is for:**

- file name - human_cd34_bm_rep1.h5ad, human_cd34_bm_rep2.h5ad, human_cd34_bm_rep3.h5ad
- link to existing collection in cellxgene - WIP
~~- ticket link to DCP wrangling ticket~~ USCS team
- link to [ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=091cf39b-01bc-42e5-9437-f419a66c8a45)

**Relevant People**
- DCP Wrangler:  Parisa
- Contributor: Manu Setty

### Primary Wrangler:
Ida

### Associated files
* [SOP](https://docs.google.com/document/d/1UVGIllybmEI46x22NSDpMNRywT3c8hcGrcw6opiHdbg/edit#)
* [Knowledge Sharing Drive](https://drive.google.com/drive/folders/1cIgfeZZaoo2mFo2mN9iZ00_MZt94mvLv)
* [Ingest-cellxgene-submitter](https://github.com/ebi-ait/ingest-cellxgene-submitter) 
* [Cellxgene-schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md)
* [Cellxgene-schema-validate](https://github.com/chanzuckerberg/single-cell-curation)
* [Cellxgene-submit-collection](https://cellxgene.cziscience.com/?curator=true)

### Published study links

* Paper: [Characterization of cell fate probabilities in single-cell data with Palantir](https://www.nature.com/articles/s41587-019-0068-4)

* Accessioned data: [DCP project](https://data.humancellatlas.org/explore/projects/091cf39b-01bc-42e5-9437-f419a66c8a45)

### Key Events

- [ ] Collect necessary matrix, cell-type annotation, and embedding files
- [ ] Modified var layer to meet cellxgene schema (adding feature_is_filtered)
- [ ] Created/Modified raw.var to meet cellxgene schema
- [ ] Modified obs layer to meet cellxgene schema 
- [ ] Created uns layer to meet cellxgene schema
- [ ] Ensured obsm layer is present
- [ ] Created h5ad with processed component parts using AnnData
- [ ] Created h5ad with raw matrix and raw var using AnnData
- [ ] Filtered ENSEMBL IDs from annotated and raw matrix
- [ ] Combined processed and raw h5ad to one h5ad object
- [ ] Run [cellxgene-schema validate](https://github.com/chanzuckerberg/single-cell-curation)
- [ ] Secondary review (?) 
- [ ] Submitted to collection in [cellxgene](https://cellxgene.cziscience.com/?curator=true)

**Comment by idazucchi** [comment]
the h5ad files have all the required metadata, except for:
- the cell type info --> stored in a separate file `HaematopoieticProfiling-10x_cell_type_2020-03-12.csv` 
- gene ENSEMBL ids --> [email thread](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/yhshD7s3F7U/m/kppdGbfIBAAJ) to request this information

**Comment by ESapenaVentura** [comment]
@idazucchi to send an email to get the gene ENSEMBL ids!

**Comment by idazucchi** [comment]
I also need to send an email to get help with the cell type:
the obs layer doesn't have barcodes so I can't match up the info between the cell type file and the h5ad

**Comment by Wkt8** [comment]
Taking over this!

**Comment by MightyAx** [comment]
review from Jason received, changes to be made

**Comment by Wkt8** [comment]
Need Jason to comment about whether or not this is still suitable for cellxgene as they do not have many genes available

**Comment by Wkt8** [comment]
Not enough genes. Closing.
