### ISSUE TITLE
Identify which projects from the skin atlas we have already in the system

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#850]
**Description of the task:**

As a data wrangler, I want to keep track of the projects from the skin BioNetwork in order to make prioritisation decisions for the next sets of datasets that we are going to work on

We have a list of the projects here:  https://drive.google.com/drive/folders/132SSAa4pp54sy1vYXLUsH_Qf2GUacMCl

**Acceptance criteria for the task:**
- [x] All projects are, at least, in the project catalogue
- [x] All projects have put into 2 categories: in ingest/in the dcp

**Comment by ESapenaVentura** [comment]
DOIs:

10.1016/j.jid.2019.07.726
10.1038/s41556-021-00740-8
10.1038/s42003-020-0922-4
10.1016/j.celrep.2018.09.006
10.1038/s41467-020-18075-7
10.1182/blood.2019004725
10.1126/science.aba6500
10.1016/j.cell.2020.05.039
10.1016/j.devcel.2020.11.002
10.1016/j.jid.2017.09.045
10.1016/j.jaci.2020.01.042

**Comment by ESapenaVentura** [comment]
Just for the sake of numbers:

- Projects we already had in catalogue: 4/11
- Projects we already had in the DCP: 2/11
- Projects we didn't acknowledge: 5/11

**Comment by gabsie** [comment]
This is ready to close, I populated the spreadsheet which we can keep for tracking with Maria Kasper. 
https://docs.google.com/spreadsheets/d/1oojWX8HvfPyxohIGwnoreiPSXn3QJRcPt3BjjbIHm94/edit?usp=sharing  

@idazucchi @ESapenaVentura
