### ISSUE TITLE
GSE129611 - TranscriptionalFeaturesHairFollicles

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#852]
### Project short name:
TranscriptionalFeaturesHairFollicles
### Primary Wrangler:
Ida
### Secondary Wrangler:
Wei

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1RqVpkGLFHw6UMbSExJE5pBUOkQChfkQX)

### Published study links

* Paper: [Defining Transcriptional Signatures of Human Hair Follicle Cell States](https://doi.org/10.1016/j.jid.2019.07.726)

* Accessioned data: [GSE129611](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129611)

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=8b9cb6ae-6a43-4e47-b9fb-3df7aeec941f&tab=project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
There is almost no donor metadata available and very little info on library preparation/
The 10x version is missing but the paper was published in 2019 I have no idea if I'll ever get a reply back
the files look odd:
4 runs for one sample, 1 fastq each and reads are all 59pb --> not sure how to grup them/ classify them

**Comment by idazucchi** [comment]
I'm syncing the files, then it's time for graph validation and SR

**Comment by Wkt8** [comment]
I mistakenly already secondary reviewed this so I'm just going to add comments here! 

Donor_organism: Have to use a different development_stage_ontology_id because this is not allowed by graph validation. Try HsapDv:0000001

Cell suspension has 5 cell suspensions but from the paper it says "Libraries were generated and sequenced using the Drop-seq (n = 2) and
commercial 10X Genomics (n = 2) platforms" - but in GEO it clearly marks 5 separate cell suspensions. Any thoughts? 

The contributor replied stating that it is 10x 3' v2, that was used, so this does not need to be changed.

**Comment by idazucchi** [comment]
I've sent an email to check if the sample in GEO are correct

About the developmental stage - the test still needs to be deleted anyway #878 - not sure if `post-embryonic stage` is the best developmental stage to use here, but there is no information on the age of the donors

**Comment by idazucchi** [comment]
The sample in GEO are correct, the IGV test has been deleted and I've kept the develpmental stage `post-embryonic stage` 

The project passed graph validation 

I'm exporting now

**Comment by idazucchi** [comment]
Verified in the data browser!
