### ISSUE TITLE
Transcriptional Programming of Normal and Inflamed Human Epidermis at Single-Cell Resolution

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#854]
### Project short name:
tbd
### Associated files

* Google Drive: tbd

### Published study links

* Paper: [Transcriptional Programming of Normal and Inflamed Human Epidermis at Single-Cell Resolution](https://doi.org/10.1016/j.celrep.2018.09.006)

* Accessioned data: need to check (with Maria ?) if there is a cell count matrix available

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=8fd1609b-cd2d-4b4d-bb96-49ae6b8ade2f&tab=project)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
@gabsie if this has no count matrix available it's inelegible by our criteria - do we want to curate the metadata anyway for the skin network?

**Comment by ami-day** [comment]
Note from @gabsie : Maria is going to get in touch with relevant network contributors about making gene expression matrices files available. For now, let's not curate this dataset until the matrices become available.

**Comment by ofanobilbao** [comment]
Added link to ticket in Ingest and made relevant notes there. Closing this for now

**Comment by arschat** [comment]
graph valid and ready for sec review!

**Comment by arschat** [comment]
CELLxGENE is not mentioned but it's fine[.](https://explore.data.humancellatlas.org/projects/8fd1609b-cd2d-4b4d-bb96-49ae6b8ade2f?catalog=dcp52) verified in browser
