### ISSUE TITLE
GSE147482 - HumanNeonatalForeskin

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#855]
### Project short name:
HumanNeonatalForeskin
### Primary Wrangler:
Ami

### Associated files

* Google Drive:
https://drive.google.com/drive/folders/1w4EZ-D1ijoDci8R4SXSWZqJBfbld1OCw

* GoogleSheet:
https://docs.google.com/spreadsheets/d/1NZPjGwrXOCLTrHYG_lOy-Ul1Yb-VUxy-/edit#gid=932941242

### Published study links

* Paper: [Single cell transcriptomics of human epidermis identifies basal stem cell transition states](https://doi.org/10.1038/s41467-020-18075-7)

* Accessioned data:  [GSE147482](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE147482)

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=66d7d92a-d6c5-492c-815b-f81c7c93c984&tab=project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Requested SRA files from NCBI.

**Comment by ami-day** [comment]
SRA files won't convert to fastq. Downloading bam files.

**Comment by ami-day** [comment]
Bam files still converting to fastq.

**Comment by ami-day** [comment]
Uploading files to: 642ad7d5-bbc0-4615-8f22-d215b9c8a120

**Comment by ami-day** [comment]
The index file for Donor 1 has reads of length 0 which causes an error in ingest when validating. Since the index files are not needed for 10X data, I am deleting the file metadata and will upload only R1 and R2 for that run.

**Comment by ami-day** [comment]
syncing data files

**Comment by ami-day** [comment]
Graph validating

**Comment by Wkt8** [comment]
Looks good to me! Two things: 

Interesting that the dissociation protocol from the GEO submission and the paper are different - e.g. 'several hours in dispase' vs. 'up to 2 hours in dispase' and 'trypsinized for 30min' vs. 'trypsinized for 15 min' 

I'd also ideally want to hear Enrique and Ida's opinion on dropping the index file. Do you have any idea why it output with reads of length 0?

**Comment by ami-day** [comment]
> Looks good to me! Two things:

> I'd ideally want to hear Enrique and Ida's opinion on dropping the index file. Do you have any idea why it output with reads of length 0?

Yea, that makes sense. It said "read with length 0" which I think is not necesserily all reads. Because the index reads are short, its quite possible it got truncated somehow. The index reads are not needed for processing and analysis if the technology is 10X, based on my understanding, as we link the runs and experiments to the fastq files in the metadata. So, I didn't see any harm in removing it. But yes let's see what @ESapenaVentura and @idazucchi think

**Comment by ami-day** [comment]
Submitted.

**Comment by ami-day** [comment]
Exported, submitted import form.
