### ISSUE TITLE
GSE147944 - cutaneousTcellLymphoma

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#856]
### Project short name:
CutaneousTcellLymphomaSTAT6

### Primary Wrangler:
Ami

### Secondary Wrangler:
Ida

### Associated files

* Google Drive:

https://docs.google.com/spreadsheets/d/1SN-9T3V0FFfOZ9VGvTEQ8JEHDokPJoFzgIdgGprY8iE/edit#gid=1868030719

### Published study links

* Paper: [Genome-wide transcriptome analysis of the STAT6-regulated genes in advanced-stage cutaneous T-cell lymphoma](https://doi.org/10.1182/blood.2019004725)

* Accessioned data:

Series: [GSE147947](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE147947)

scRNA-Seq data: [GSE147944](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE147944) - count cell matrices only

Bulk data: [GSE147911](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE147911)

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=a1375150-dda4-4081-8318-c1593622da55&tab=project) 

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Need to add a treatment protocol: Cells were activated by the Dynabeads CD3/CD28 T cell Expander (ThermoFisher, bead-to-cell ratio: 1:1).

**Comment by ami-day** [comment]
Downloading bulk RNA sequencing data.

**Comment by ami-day** [comment]
`76b72ab5-702e-4057-b0a5-c1ebdea8c03c`

**Comment by gabsie** [comment]
Data is being uploaded.

**Comment by idazucchi** [comment]
Hi ami, I'm done with the review! It looks good, I have just a few comments

### Project
- you should add yourself as curator!

### Collection
- remove healthy/ disease from description since the protocols are used for both disease and healthy 

### Enrichment
- you can add CD4+ to the markers

### Cell suspension
- you can add the INSDC sample accession for the bulk RNAseq
- I think that the treatment protocol should be applied to all bulk RNAseq cell suspension, the controls go through the same treatment as the STAT6 ones but without any drug
> samples were cultured for 48 hours with or without the STAT6 inhibitor and then analyzed with RNAseq

You can also apply the timecourse to the controls as well, something like 48h RNA collected after 48h in culture, to show that the controls were under the same conditions as the treated samples

### Analysis protocol
- remove the `|` from the computational methods, it't a reserved character

### Analysis file
- I'd use `count matrix` for the scRNAseq because the ontology definition is more accurate that that for gene expression matrix

**Comment by ami-day** [comment]
> Hi ami, I'm done with the review! It looks good, I have just a few comments
> 
> ### Project
> * you should add yourself as curator!
> 
> ### Collection
> * remove healthy/ disease from description since the protocols are used for both disease and healthy
> 
> ### Enrichment
> * you can add CD4+ to the markers
> 
> ### Cell suspension
> * you can add the INSDC sample accession for the bulk RNAseq
> * I think that the treatment protocol should be applied to all bulk RNAseq cell suspension, the controls go through the same treatment as the STAT6 ones but without any drug
> 
> > samples were cultured for 48 hours with or without the STAT6 inhibitor and then analyzed with RNAseq
> 
> You can also apply the timecourse to the controls as well, something like 48h RNA collected after 48h in culture, to show that the controls were under the same conditions as the treated samples
> 
> ### Analysis protocol
> * remove the `|` from the computational methods, it't a reserved character
> 
> ### Analysis file
> * I'd use `count matrix` for the scRNAseq because the ontology definition is more accurate that that for gene expression matrix

Thank you, I have made most of the suggested changes and re-submitting it now.

**Comment by ami-day** [comment]
submitted

**Comment by ami-day** [comment]
Exported and import form submitted.

**Comment by ami-day** [comment]
Looks good

**Comment by idazucchi** [comment]
the import team had issues with this project due to the new treatment protocol - the project was removed from R22
this was not handed off when Ami left so no one ever followed up on it

next steps:
- [ ] check if other projects with the treatment protocol were ever exported
- [ ] check with import team if they are ready for this
- [ ] fill out import form

**Comment by idazucchi** [comment]
import failed - [slack](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1697518396836619) + [ticket](https://github.com/DataBiosphere/azul/issues/5619)

**Comment by idazucchi** [comment]
this was part of the initial skin list but is not on Dave's tracker 
do we want to:
- [ ] raise again the issue of the treatment protocol
- [ ] close this ticket, drop this project
