### ISSUE TITLE
GSE144240 - MultimodalSquamousCarcinoma

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#857]
### Project short name:
MultimodalSquamousCarcinoma
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1fm0TgR0rQ5HL2vPK2jaghXFfgWIarCNM)

### Published study links

* Paper: [Multimodal Analysis of Composition and Spatial Architecture in Human Squamous Cell Carcinoma](https://doi.org/10.1016/j.cell.2020.05.039)

* Accessioned data: [GSE144240](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144240)
   - [GSE144236](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144236) 	single-cell RNA-seq - elegible
   - ~~[GSE144237](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144237)~~ 	WES - non elegible
   - ~~[GSE144238](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144238)~~	CRISPR screen - non elegible
   - [GSE144239](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144239) 	Spatial Transcriptomics - elegible

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=bb19eac6-db1a-4334-befa-d6f200d467fc&tab=project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by gabsie** [comment]
@ESapenaVentura getting the files

**Comment by idazucchi** [comment]
I've prepared all the files in the hca-util and I am fill in in the detailes of the last few analysis files.

The only thing missing is an ontology term for the spatial transcriptomics library preparation - I've opened a [ticket](https://github.com/HumanCellAtlas/ontology/issues/118) about it in the HCAO
For now I'm doing validation of the oroject using the wrong ontology term and I will not push this until the term is available

**Comment by idazucchi** [comment]
I need to reconvert again a bam file because the index files didn't pass validation

**Comment by idazucchi** [comment]
I deleted 3 index files because they were empty

Graph validation failed - I am missing info on which cell suspensions were sorted - I am pinging the authors again

**Comment by idazucchi** [comment]
no reply from the authors. I think we can either 
1. close the ticket
1. reach out to the skin bionetwork and see if they can get in touch with the authors

**Comment by idazucchi** [comment]
I'm closing the ticket and deleting the hca-util area
