### ISSUE TITLE
AgingSkinAtlas - A Single-Cell Transcriptomic Atlas of Human Skin Aging

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#858]
### Project short name:
AgingSkinAtlas
### Primary Wrangler:
Ami

### Associated files

* Google Drive: 

https://drive.google.com/drive/folders/1huwmsNCyeYSE5TzBwRPMkQw_tJVq7f17

https://docs.google.com/spreadsheets/d/12vuk9-SUKbPi4flwqi_kXmn2mBpQCSY0_SxI0AZpeEs/edit#gid=1539471600

### Published study links

* Paper: [A Single-Cell Transcriptomic Atlas of Human Skin Aging](https://doi.org/10.1016/j.devcel.2020.11.002)

* Accessioned data: [HRA000395](https://ngdc.cncb.ac.cn/gsa-human/browse/HRA000395) in GSA 
Aging Atlas (https://bigd.big.ac.cn/aging/landscape?project=Human_Skin)

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=923d3231-7295-4184-b3f6-c3082766a8c7&tab=project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Downloading fastq files from https://ngdc.cncb.ac.cn/aging/landscape?project=Human_Skin

**Comment by ami-day** [comment]
Note: emailed the authors about obtaining gene expression matrices files and cell type annotation files.

**Comment by ami-day** [comment]
uploading to d0ada739-b5ca-4112-8375-c0cd24b0441b

**Comment by ami-day** [comment]
No response from authors about matrix and cell annotations files.

**Comment by ami-day** [comment]
Uploading files to hca-util bucket

**Comment by ami-day** [comment]
Graph validating.

**Comment by Wkt8** [comment]
Secondary Review: 
This looks great! Only two small things I wanted to check :) 

Donor_Organism
I couldn't find where you were getting this specific metadata for the donor_organisms - regarding the Han Chinese ethnicity, alcohol history, and smoking history? 

Sequence_File
Are you 100% sure that these are read1 and read2 files? Just asking as they seem to have an unusual suffix of '_f1'

**Comment by ami-day** [comment]
> Secondary Review: This looks great! Only two small things I wanted to check :)
> 
> Donor_Organism I couldn't find where you were getting this specific metadata for the donor_organisms - regarding the Han Chinese ethnicity, alcohol history, and smoking history?
> I found these via supplementary links via the paper and portal!
> Sequence_File Are you 100% sure that these are read1 and read2 files? Just asking as they seem to have an unusual suffix of '_f1'
yep, Im pretty sure 'f1' means 'forward read 1' and then r1 means 'reverse read 1'.

**Comment by ami-day** [comment]
I will go ahead and submit it :)

**Comment by ami-day** [comment]
submitted import form, exported.
