### ISSUE TITLE
GSE138669 - SkinSystemicSclerosis

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#859]
### Project short name:
SkinSystemicSclerosis
 
### Primary Wrangler:
Ida

### Secondary Wrangler:
Ami

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1tkFLKuPQglQU-YXYaTrLmzw22YyKVBlV)
  [project](https://docs.google.com/spreadsheets/d/1Gl5YO9xj4jwPdQJkgSZLzYLufE4HOTJV/edit?usp=sharing&ouid=113452802627011629126&rtpof=true&sd=true)

### Published study links

* Initial Paper: [SFRP2/DPP4 and FMO1/LSP1 Define Major Fibroblast Populations in Human Skin](https://doi.org/10.1016/j.jid.2017.09.045)
* Paper with accessioned data: [Expansion of Fcγ Receptor IIIa–Positive Macrophages, Ficolin 1–Positive Monocyte-Derived Dendritic Cells, and Plasmacytoid Dendritic Cells Associated With Severe Skin Disease in Systemic Sclerosis](https://doi.org/10.1002/art.41813)

* Accessioned data: [GSE138669](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138669)

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=7f351a4c-d24c-4fcd-9040-f79071b097d0&tab=project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
- [ ] check paper for accessions
- [ ] write to authors to see if datas has been published

**Comment by idazucchi** [comment]
**Bam-to-fastq**
The files are in bam format so I've converted them using the bamtofastq tool in the ec2.
Some things don't look right:
- 10x v1 files are split as follows:
   - R3 is 10bp --> UMI
   - R2 is 14bp  --> cell barcode 
   - R1 is 98pb -->  cDNA
   - I1 is 8bp 
- 10x v2 - three I1 files have no reads
```
@E00440:237:HM3CLCCXY:7:2116:30858:65177 2:N:0:0

+

@E00440:237:HM3CLCCXY:7:1112:6258:17008 2:N:0:0

+

@E00440:237:HM3CLCCXY:7:1208:1763:16147 2:N:0:0

```

I'm not sure the issues with the fastq files can be solved in time for the release

**Comment by MightyAx** [comment]
@ami-day has some prior experience with this problem.

**Comment by idazucchi** [comment]
There is on h5 file per donor but the contents of those 22 h5 files are identical, so I think it might be one integrated analysis file for all donors.
There is not enough time to confirm this with the authors and if I submit the files now it could prove difficult to delete the wrong files from the DCP.

I'll contact the authors again and hopefully get h5ad files with more metadata as well

**Comment by idazucchi** [comment]
Graph valid!

I've omitted the 3 empty I1 files and the analysis files/protocol

**Comment by idazucchi** [comment]
Graph valid!

I've omitted the 3 empty I1 files and the analysis files/protocol

**Comment by ami-day** [comment]
This looks really good to me, nice work!

I can't see any issues other than, I am not sure why the Analysis Protocol and File tabs were not included, given they are available in GEO (e.g. project level: GSE138669_RAW.tar and sample level: GSM4115868_SC1raw_feature_bc_matrix.h5).







<br class="Apple-interchange-newline">[GSM4115868](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4115868)

**Comment by idazucchi** [comment]
I'm exporting the dataset

This will need to be updated to add analysis protocol and files - I'll do it as soon as I can confirm that the h5 files are different for each donor
Both the size (737’280 cells and 33’538 genes) and the fact that all files have the same dimensions is suspicious
The total number of cells reported in the paper is 65'199 - even taking into account quality checks it still looks like too many cells

**Comment by idazucchi** [comment]
Verified in the data browser!

**Comment by gabsie** [comment]
There's a problem here with spreadsheet generation for this dataset (stuck for indefinite time). @idazucchi will also create a bug ticket for Dev

**Comment by idazucchi** [comment]
I've added a new submission (spreadsheet here) with the analysis files. The linking to the existing entities was done using the uuids and checked manually because the spreadsheet cannot be generated.

I'm now exporting

**Comment by arschat** [comment]
There are 3 publications referencing the same data.
1. https://doi.org/10.1016/j.jid.2017.09.045
2. https://doi.org/10.1002/art.41813
3. https://doi.org/10.1038/s41467-021-24607-6

We started from 1, then authors pointed us to 2, and now bionetwork references 3 in their list (through the data portal tracker).

Publications 2 and 3 reference the same GEO accession [GSE138669](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138669) and the same donor_ids in the figures. It's a different analysis of the same data.

For consistency among other components, the project title in the tracker is `Myofibroblast transcriptome indicates SFRP2hi fibroblast progenitors in systemic sclerosis skin`
We need to decide if we will include all 3 publications, and which will be the project title.

**Comment by idazucchi** [comment]
@arschat did you also export the changes?

**Comment by arschat** [comment]
No, I've not exported the changes. I asked Dave about this but did not get a reply on that question specifically.
> 10.1038/s41467-021-24607-6    7f351a4c-d24c-4fcd-9040-f79071b097d0
    both publications point to the same GEO accession (GSE138669) and reference the same donor IDs. GEO also, points back to the second publication (10.1002/art.41813), and that's why we decided to mention this publication in the project. The difference between the two studies is the analysis that was done along with non-sequencing experiments, but authors did not share any integrated objects that might be different between the two analysis (only fastq & raw count matrices). We could add the first publication (10.1038/s41467-021-24607-6) as well, but let me know if you would like us to change the title as well.

**Comment by arschat** [comment]
* changed the project title to `Myofibroblast transcriptome indicates SFRP2hi fibroblast progenitors in systemic sclerosis skin`
* Added the skin bionetwork in the hca_bionetworks field

**Comment by idazucchi** [comment]
project metadata exported!

from the gpc bucket
```
4500  2023-07-27T05:56:35Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/7f351a4c-d24c-4fcd-9040-f79071b097d0/metadata/project/7f351a4c-d24c-4fcd-9040-f79071b097d0_2022-08-25T14:22:53.860000Z.json
4589  2024-09-27T16:04:11Z  gs://broad-dsp-monster-hca-prod-ebi-storage/prod/7f351a4c-d24c-4fcd-9040-f79071b097d0/metadata/project/7f351a4c-d24c-4fcd-9040-f79071b097d0_2024-09-26T14:30:26.573000Z.json
```

import form filled out

**Comment by arschat** [comment]
Verified in [browser](https://explore.data.humancellatlas.org/projects/7f351a4c-d24c-4fcd-9040-f79071b097d0?catalog=dcp43)!
