### ISSUE TITLE
GSE118555 MouseLungMyofibroblasts

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#86]
**Primary Wrangler:**
Ray
**Secondary Wrangler:**
Marion

**Associated files:**

Google Drive: [Folder](https://drive.google.com/drive/folders/1mcQXbNEB92RZRV8fZdjoBoecPg1ZsGIy)

s3 bucket: TBC

**Key Events**

- [x] Assign the Primary Wrangler
- [x] Fill spreadsheet (to a sufficient standard to submit dataset)
- [ ] Get CellType annotation (To a sufficient standard to submit to SCEA)
- [ ] Upload data (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata (most likely in staging)
- [ ] Check linking
- [ ] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from SCEA
- [ ] Submit dataset to Production?

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by lauraclarke** [comment]
This seems blocked by lack of response from contributors

2020-04-09: sent second query to lead author Xin Sun xinsun@ucsd.edu
about critical 10x experimental details.
No reply yet.

This was copied from https://github.com/HumanCellAtlas/hca-data-wrangling/issues/446

**Comment by rays22** [comment]
This is a published mouse dataset.
I am closing this ticket, because there is no response from authors to clarify critical 10x experimental details.
