### ISSUE TITLE
GSE147424  - Single-cell transcriptome analysis of human skin identifies novel fibroblast subpopulation and enrichment of immune subsets in atopic dermatitis

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#860]
### Project short name:
tbd
### Primary Wrangler:
Ami

### Associated files

* Google Drive: 
https://drive.google.com/drive/folders/15VQLG6qWq9kOUENSQ0hUW0YUGIxuYsS6

https://docs.google.com/spreadsheets/d/1qDj7_LnCQ6UrkrOAbajalxVsLdTuZhPf/edit#gid=148213679

### Published study links

* Paper: [Single-cell transcriptome analysis of human skin identifies novel fibroblast subpopulation and enrichment of immune subsets in atopic dermatitis](https://doi.org/10.1016/j.jaci.2020.01.042)

* Accessioned data: [GSE147424](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE147424)

* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=bb121a66-6803-435e-bb10-94ac2b53dd92&tab=project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Need to email authors about donors: not clear which samples came from which donors.

**Comment by ami-day** [comment]
Authors cannot provide linking between donors and samples. Need to discuss eligibility with other wranglers.

**Comment by ami-day** [comment]
Discussed with Ida and Enrique. We decided we should ask Maria about the linking - should we link each sample to a separate donor? we can't get info on the linking from the contributing author.

**Comment by ami-day** [comment]
Hi @gabsie did you get a chance to ask Maria about the authors getting back with donor-sample linking info? I think if we cannot get this info, we will need to mark it as ineligible and it won't be submitted, as the linking is crucial for interpretation of the dataset.

**Comment by ami-day** [comment]
@gabsie will look into this

**Comment by gabsie** [comment]
OK, so - all I wish to ask here is that after New year somebody else just checks whether this could be interpreted from the paper at all. 
I am afraid I cannot at this point ask Maria - the lead for the Skin network. 
Thanks, 
Gabs

**Comment by idazucchi** [comment]
not part of the official list for wave 2
