### ISSUE TITLE
Files stuck in validating

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#862]
**Description of the project**

4 Files have been stuck in validation for this submission for more than 24 hours:
- Submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=0a275b09-57cd-42e1-8943-119a4dbd8a17

**Acceptance criteria**
- [x] File validation has been re-triggered
- [x] Files validate normally

**Comment by Wkt8** [comment]
Project is in the 'complete' status now.
