### ISSUE TITLE
Investigate R19 import errors

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#864]
**Description of the issue**
As stated in the email below, there have been several R19 errors reported by Nathan Calvanese.

> Hi Enrique, 
> 
> I wanted to pass along some

>  of our findings from the DCP19 import so that we can look into getting these resolved.

> 
> # Staging Area Validation Failures:
> ## `f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc`
> -- Seeing cases where provenance had additional, unexpected properties ("schema_major_version" and "`schema_minor_version`" as opposed to just "`schema_version`" in major.minor.patch format, as specified in https://schema.humancellatlas.org/system/1.0.3/provenance). Example file: `f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc/metadata/cell_suspension/02341f59-b12e-4039-83c6-b563919f7845_2021-06-01T15:37:17.915000Z.json`
> ## `c16a754f-5da3-46ed-8c1e-6426af2ef625` 
> -- Multiple errors where import "Did not find data file" (for example, "Exception: ('Did not find data file', {'name': {'prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/metadata/analysis_file/e6deb67f-febb-435c-ac31-a70f14f4eb9a_2022-04-14T10:54:28.706000Z.json'}, 'entity_id': 'e6deb67f-febb-435c-ac31-a70f14f4eb9a', 'entity_type': 'analysis_file', 'metadata_versions': {'2022-04-14T10:54:28.706000Z'}, 'descriptor_versions': {'2022-04-14T10:54:28.706000Z'}, 'project': {'c16a754f-5da3-46ed-8c1e-6426af2ef625'}, 'category': {'output'}, 'found_metadata': True, 'data_file_name': 'GSM4058926_137C.dgecounts.rds.gz', 'found_data_file': False, 'crc32c': '8b7af94c'})"). Suspect this may be a partial/updated staging area potentially, as the importer still does not support that functionality.
> ## `e9f36305-d857-44a3-93f0-df4e6007dc97 `
> -- Same as above. Multiple errors where import "Did not find data file" (for example, "Exception: ('Did not find data file', {'name': {'prod/e9f36305-d857-44a3-93f0-df4e6007dc97/metadata/analysis_file/ea150ba4-6430-4c60-ac23-0b874c99318f_2022-05-19T11:18:21.037000Z.json'}, 'entity_id': 'ea150ba4-6430-4c60-ac23-0b874c99318f', 'entity_type': 'analysis_file', 'metadata_versions': {'2022-05-19T11:18:21.037000Z'}, 'descriptor_versions': {'2022-05-19T11:18:21.037000Z'}, 'project': {'e9f36305-d857-44a3-93f0-df4e6007dc97'}, 'category': {'output'}, 'found_metadata': True, 'data_file_name': 'snRNA_CK158_filtered_feature_bc_matrix.h5', 'found_data_file': False, 'crc32c': 'ad0fc3b5'})"). Suspect this may be a partial/updated staging area potentially, as the importer still does not support that functionality.
> 
> # Staging Area Still Running/Rerunning:
> ## `957261f7-2bd6-4358-a6ed-24ee080d5cfc`
> -- Ran into some connectivity issues, so kicked off the job again. Will follow up here if any validation failures are identified.
> ## **e57dc176-ab98-446b-90c2-89e0842152fd**
> -- This one was missing the staging_area.json file. I added it in and kicked off the job again to keep things moving along. Will follow up here if any validation failures are identified.
> ## `e0009214-c0a0-4a7b-96e2-d6a83e966ce0`
> -- This one is still running. I was under the impression that this was a Lantern-owned project now, but the institution was marked as EBI on the import form. Is this correct? If so, I'll let it continue to run and follow up here if any validation failures are identified. 

**Acceptance criteria**
- [x] All errors have been identified (Why/how did it happen)
- [ ] Solutions are lined up
- [ ] Received confirmation from Nathan that the import was successful

**Comment by ESapenaVentura** [comment]
[COMMENT IN PROGRESS]
**Validation failures**:
- f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc: This error is due to the data being pre
- `c16a754f-5da3-46ed-8c1e-6426af2ef625`
   - **Problem**:This is one of the datasets exported as part of the idiopathic lung fibrosis ontology update. This project was exported with the `only metadata` flag on and it's part of release 16, so descriptors were created but the files were deleted when the R16 staging area was cleaned up.
   - **Solution**: `gsutil -m rm -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/descriptors/`
   - **Solved?**: [ ]

**Comment by ESapenaVentura** [comment]
Still solving errors, the three above are fine.

Tabula muris is currently being validated, Nathan to come back to me once it finishes validating

So far, 2 new errors have been detected:
- 005d611a-14d5-4fbf-846e-571a1f874f70: DCP1 dataset, will investigate into this
- 9f111577-db48-43ab-a487-6a405ecb686a: New dataset for R19, will investigate the error as well

**Comment by ESapenaVentura** [comment]
### `005d611a-14d5-4fbf-846e-571a1f874f70`
**[Assessing the relevance of organoids to model inter-individual variation](https://contribute.data.humancellatlas.org/submissions/detail?uuid=dc0828c4-2d46-4313-b408-e69e4c7ccd33&project=005d611a-14d5-4fbf-846e-571a1f874f70)**
- **Problem**: This project has a mix of submissions (DCP1/DCP2), with the first one having supplementary files. For some reason, in one of the exports, a supplementary file metadata was exported. There is no data file in the staging area, so that is what is likely causing issues. There is also no descriptor.
- **Solution**: `gsutil rm gs://broad-dsp-monster-hca-prod-ebi-storage/prod/005d611a-14d5-4fbf-846e-571a1f874f70/metadata/supplementary_file/35219225-8e86-42aa-b791-22f1416fc916_2019-05-15T09:36:02.451000Z.json`
- **Solved?**: :white_check_mark:

**Comment by ESapenaVentura** [comment]
### `9f111577-db48-43ab-a487-6a405ecb686a`
[Single cell transcriptomics of human brain epileptic lesions identifies pro-inflammatory immune mechanisms based on interlacing cellular immune networks](https://contribute.data.humancellatlas.org/submissions/detail?uuid=6970a239-9ae9-4166-a82d-4733a0ad9717&project=9f111577-db48-43ab-a487-6a405ecb686a)
- So far, I can't find a single issue with this dataset. I have checked that all the files have been exported (2 analysis files), in the proper folders, with descriptors, and metadata pointing to them. Metadata seems to also be fine, and only 2 `links` (2 subgraphs), as expected. I will wait on Nathan to come back to this

**Comment by gabsie** [comment]
@ESapenaVentura will speak to Nate to say there's nothing wrong with the email.
The error reported is based on format, but we cannot identify what is the problem.

@ESapenaVentura wishes to propose once again exporting only metadata, if there are no changes in files at all.

**Comment by MightyAx** [comment]
The last project was an email validation issue, which will leave the project out of the release 19 and will be included in the release 20
