### ISSUE TITLE
Dataset stuck in exporting

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#869]
**Description of the task:**

[dataset a815c84b-8999-433f-958e-422c0720e00d](https://contribute.data.humancellatlas.org/submissions/detail?uuid=2ad60ae7-9274-4eaa-b22a-2b345d5201b0&project=a815c84b-8999-433f-958e-422c0720e00d) is stuck in exporting

Checking grafana, no export messages for this dataset have been exported due to `list index out of range` errors.

Wrangling ticket #61

**Acceptance criteria for the task:**
- [x] dataset process entities are fixed
- [x] Pull export jobs out of the error queue
- [x] The dataset is exported successfully

I (Alexie) don't think the following are required:
- [ ] bug ebi-ait/dcp-ingest-central#813 discovered during the investigation is resolved
    - Not required if we are making the operation change manually
- [ ] The dataset is set back to graph valid
    - Not required if we simply require the errored jobs
- [ ] @ESapenaVentura is notified to add a small change before exporting
    - Do not know why this would be needed

**Comment by MightyAx** [comment]
using `pip install -i https://test.pypi.org/simple/ hca-ingest==2.0.1`

```

>>> from hca_ingest.api.ingestapi import IngestApi
>>> api = IngestApi('https://api.ingest.archive.data.humancellatlas.org')
>>> api.set_token('Bearer '}
>>> sub_id = '62dfd2e25cc3b03957ee8cd4'
>>> sub = api.get('https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/' + sub_id).json()
<Response [200]>
>>> processes = api.get_related_entities('processes', sub, 'processes')
>>> project = api.get_related_project(sub_id)
>>> for process in processes:
...     api.link_entity(process, project, 'projects')
... 
<Response [204]> x 40 times
```

**Comment by MightyAx** [comment]
### Pull export jobs out of the error queue

I created this script, I'll upload it to the scripts repo soon.
The jobs have been moved back to the main queue, but are waiting behind jobs that are waiting for the timeout.

``` requeue.py
import json
import pika
import sys

target_export_job_ids = sys.argv[1:]
if not target_export_job_ids:
    sys.stderr.write("Usage: %s [target_export_job_ids]...\n" % sys.argv[0])
    sys.exit(1)

print(f' [*] Looking for export jobs: {target_export_job_ids}')
print('Remember to run: kubectl port-forward rabbit-0 5672:5672')

connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()

exchange = 'ingest.exporter.exchange'
source_queue = 'ingest.exporter.errored.queue'
destination_queue = 'ingest.exporter.experiment.submitted'
queue = channel.queue_declare(
    source_queue,
    durable=True,
    auto_delete=False
)

def callback(ch, method, properties, body):
    experiment = json.loads(body)
    export_job_id = experiment.get("exportJobId")
    if export_job_id in target_export_job_ids:
        print(f'{method.delivery_tag} Found {export_job_id}: {experiment}')
        channel.basic_publish(
            exchange=exchange,
            routing_key=destination_queue,
            body=body
        )
        channel.basic_ack(method.delivery_tag)
        print(f'{method.delivery_tag} Moved to {destination_queue}')

print(' [*] Waiting for jobs. To exit press CTRL+C')

channel.basic_consume(
    queue=source_queue,
    on_message_callback=callback,
    auto_ack=False
)

channel.start_consuming()
```

**Comment by MightyAx** [comment]
I've scaled the exporter to 0,
this released the in-progress waiting jobs into the queue

I've then moved the jobs for this submission back to the export queue
and scaled the exporter back to 10
