### ISSUE TITLE
GSE135893 - Single-cell RNA-sequencing reveals profibrotic roles of distinct epithelial and mesenchymal lineages in pulmonary fibrosis

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#87]
*

**Primary Wrangler:**
Enrique
**Secondary Wrangler:**
Marion

**Associated files:**

Google Drive: [Folder](https://drive.google.com/drive/folders/1IE9r3n9Hmy-e2APgZrCT6N0pyTk3KsOK)

**Key Events**

- [x] Assign the Primary Wrangler
- [x] Fill spreadsheet (to a sufficient standard to submit dataset)
- [ ] Get CellType annotation (To a sufficient standard to submit to SCEA)
- [x] Upload data (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata (most likely in staging)
- [x] Check linking
- [x] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from SCEA
- [x] Submit dataset to Production?

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

Copy of issue https://github.com/HumanCellAtlas/hca-data-wrangling/issues/443 Not clear on current state

**INGEST SUBMISSION**: https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?uuid=039ef2b5-6e6e-4f4b-9567-40762fb2a20f

**Comment by clairerye** [comment]
Just checking, @lauraclarke is the s3 bucket location something that should not be put in here now it is a public repo.

**Comment by lauraclarke** [comment]
I think that was a decision so that was my oversight. I have deleted it from the ticket but I know git keeps some sort of history so I don't know what the consequences of that are

**Comment by ESapenaVentura** [comment]
We had a response from the contributor:
>Some of the samples have multiple 10X preps. If there are multiple identifiers it means there were multiple preps - e.g. for THD0005 we prepared three independent 10X genomics runs.

With this information I will review the metadata today and upload it to ingest for validation.

**Comment by ESapenaVentura** [comment]
https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?uuid=039ef2b5-6e6e-4f4b-9567-40762fb2a20f

- Metadata has been revised. I think it's ok now, but @mshadbolt please feel free to review again. I have used the fastq filenames to divide in library preps (If you look at filenames and divide the string by "_", I have considered number 2 substring as cell_suspension_id and number 8 substring as library_prep_id). This way I get the 3 library preps mentioned for THD0005 above.
- Ran on `ingest-graph-validator`, looks ok!
- The s3 files were not uploaded in the bucket. Uploading with script `move_data_from_insdc`!

Steps after that:
- [ ] Wait for secondary wrangling
- [ ] Upload files to ingest upload area
- [ ] Make sure checkboxes are unticked before hitting the "submit" button
- [ ] Finish submission in ingest

**Comment by ESapenaVentura** [comment]
Data has been uploaded to the submission above (Currently validating)

**Comment by mshadbolt** [comment]
We had a quick discussion and the updated library prep and cell suspension looks good to me!

**Comment by ESapenaVentura** [comment]
Thanks @mshadbolt !

Then the submission is ready for DCP2!

Due to the current status of the exporter, I won't hit the "Submit" button to avoid unexpected exports to DCP2.

@lauraclarke should we close the ticket?

**Comment by lauraclarke** [comment]
I think closing the ticket is a good idea. We should figure out how to track export from Ingest to DCP2 after Thursday's meetings

**Comment by ESapenaVentura** [comment]
Re-opening so the SCEA brokering can be tracked

**Comment by mshadbolt** [comment]
while curating I noticed that the bioarxiv preprint can now be replaced by the journal article here: https://advances.sciencemag.org/content/6/28/eaba1972

**Comment by ami-day** [comment]
This dataset is already in SCEA and can be seen in their browser.

**Comment by arschat** [comment]
Project published in browser.
[https://explore.data.humancellatlas.org/projects/c1a9a93d-d9de-4e65-9619-a9cec1052eaa](https://explore.data.humancellatlas.org/projects/c1a9a93d-d9de-4e65-9619-a9cec1052eaa)
