### ISSUE TITLE
dataset problem - GEO file should not be displayed in data browser

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#870]
##### [MultipleSclerosisLineageDiversity](https://contribute.data.humancellatlas.org/submissions/detail?uuid=a91a7a21-4443-481d-8466-9282a401c5cf&project=ce7b12ba-664f-4f79-8fc7-3de6b1892183)
[Data Browser Project Matrices Link](https://data.humancellatlas.org/explore/projects/ce7b12ba-664f-4f79-8fc7-3de6b1892183/project-matrices)
- [x] Create new analysis file metadata and fill information (API, @ESapenaVentura )
- [x] Create new analysis_protocol and fill information
- [x] Create new process and link together (UI):
   - Analysis file
   - Analysis protocol
   - Input biomaterials
- [x] Upload a new analysis file for `EMS83370-supplement-2.xlsx`
    ~- Using the latest `analysis_file`/`analysis_protocol` schema should allow access the the relevant matrix fields detailed above.~
    - Once the submission is exported Azul will then remove the extra `GSE134809_RAW.tar` file

**Comment by ESapenaVentura** [comment]
Continuation from the dataset missing an update from [this ticket](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/354)

**Comment by ofanobilbao** [comment]
@ami-day to communicate to Trevor and Hannes that this is on Browser team

**Comment by ami-day** [comment]
Messaged the data browser team on dcp-ops channel

**Comment by ofanobilbao** [comment]
See conversation/thread here: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1662547791187619 

@ami-day has to start the process to sort it out

**Comment by MightyAx** [comment]
Old Ticket Description:

> 
> In the data portal, there is a contributor-generated matrix (GEO file) named "GSE134809_RAW.tar" associated with the following project:
> 
> https://data.humancellatlas.org/explore/projects/ce7b12ba-664f-4f79-8fc7-3de6b1892183
> https://data.humancellatlas.org/explore/projects/ce7b12ba-664f-4f79-8fc7-3de6b1892183/project-matrices
> 
> There is however no GEO matrix file associated with this project in the GEO database, and the accession and file name (GSE134809_RAW.tar) is associated with a different project/publication.
> 
> The GEO gene expression matrix file was not submitted to ingest, nor was any other analysis file for this project. It is likely there was a mistake made previously when we filled out the gene expression analysis files for import in a shared spreadsheet. It must have been entered linked to the wrong project.
> 
> I believe the matrix would need to be deleted by the Data Browser team, as it does not appear to be in ingest.
> 
> Ingest Project:
> https://contribute.data.humancellatlas.org/projects/detail?uuid=ce7b12ba-664f-4f79-8fc7-3de6b1892183
> 
> The project which SHOULD link to the above GEO file is this one:
> https://data.humancellatlas.org/explore/projects/504e0cee-1688-40fa-b936-361c4a831f87/project-matrices
> The file needs to be added to this project as an analysis file.

**Comment by MightyAx** [comment]
From Ami:
The project which SHOULD link to the above GEO file is this one:
https://data.humancellatlas.org/explore/projects/504e0cee-1688-40fa-b936-361c4a831f87/project-matrices
The file needs to be added to this project as an analysis file.

Weirdly, there are analysis files linked to this project in ingest: https://contribute.data.humancellatlas.org/submissions/detail?uuid=cddf06c7-5d43-4013-a0b0-271fb611e396&project=504e0cee-1688-40fa-b936-361c4a831f87

**Comment by MightyAx** [comment]
I believe the method that hannes linked to outlines the following steps we need to take in ingest:
We need to use [this method](https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_system_design.rst#512describing-cgms-as-analysis-files) to upload the CGMs as analysis files:
1. Use the right Schema:
    - [ ] Change the schema version of the analysis protocols to be at least [9.2.0](https://schema.humancellatlas.org/type/protocol/analysis/9.2.0/analysis_protocol)
    - [ ] Change (or add) files with the schema type `analysis_file` and with version at least [6.3.0](https://schema.humancellatlas.org/type/file/6.3.0/analysis_file)
        - Which references `file_core` at least [6.2.0](https://schema.humancellatlas.org/core/file/6.2.0/file_core)
1. Include the relevant info:
    - [ ] populate `analysis_file.matrix_cell_count`
    - [ ] populate `analysis_file.file_core.file_source` = Contributor
    - [ ] populate the `analysis_protocol` with the `data_normalization_methods` and `derivation_process`

**Comment by ofanobilbao** [comment]
@ami-day please, address this.

**Comment by ofanobilbao** [comment]
@ESapenaVentura and @ami-day had a chat yesterday to discuss this. Enrique has amended the body of the ticket. This should be ready to go. Enrique has an action on this, and then Ami will have whatever actions remain to do

**Comment by ami-day** [comment]
I'm going to split this ticket into separate tickets. The [HumanIleumCronsNormalHaberman](https://contribute.data.humancellatlas.org/submissions/detail?uuid=cddf06c7-5d43-4013-a0b0-271fb611e396&project=504e0cee-1688-40fa-b936-361c4a831f87) project needs a GEO analysis file submitted as an analysis file, but we cannot yet link a file to many cell suspensions in ingest programatically/automatically in ingest. It is a manual process. We already have a user story ticket for this feature.

**Comment by ami-day** [comment]
I have moved the [HumanIleumCronsNormalHaberman](https://contribute.data.humancellatlas.org/submissions/detail?uuid=cddf06c7-5d43-4013-a0b0-271fb611e396&project=504e0cee-1688-40fa-b936-361c4a831f87) project information to this ticket:
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/957

**Comment by ami-day** [comment]
Waiting on first step "Create new analysis file metadata and fill information" - @ESapenaVentura will do this using the API

**Comment by ESapenaVentura** [comment]
Done, created the analysis file metadata (the metadata itself needs to be updated in the UI!)

**Comment by ami-day** [comment]
Completed next steps, now graph validating

**Comment by ami-day** [comment]
Submitted

**Comment by ami-day** [comment]
Exported and form submitted.
