### ISSUE TITLE
stuck in export: breastTranscriptomeAtlas

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#872]
*Project Info*
uuid: 9b876d31-0739-4e96-9846-f76e6a427279
project short name: breastTranscriptomeAtlas
primary wrangler: Rachel Schwartz
[Ingest link](https://contribute.data.humancellatlas.org/projects/detail?uuid=9b876d31-0739-4e96-9846-f76e6a427279)

*background*
* slack link: 
* email: 

Note:
assign to the current dev on operations.

**Comment by MightyAx** [comment]
The issue of this submission being stuck in exporting has been resolved

**Comment by MightyAx** [comment]
@rachadele Can you confirm you are happy that [your project](https://contribute.data.humancellatlas.org/projects/detail?uuid=9b876d31-0739-4e96-9846-f76e6a427279) exported okay?
If so we can close the ticket.

**Comment by rachadele** [comment]
yes!
