### ISSUE TITLE
GSE167597 - Single nucleus RNA-sequencing defines unexpected diversity of cholinergic neuron types in the adult mouse spinal cord.

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/hca-ebi-wrangler-central#874]
Doing this project as a comparison to what was supplied by Paulo from the Dev Atlas. Please let's have a wrangler volunteer to do this.

### Project short name:
Alkaslasi2021

### Primary Wrangler:
Ami

### Google Drive:

https://drive.google.com/drive/folders/1Q3vqwf6yD6VBY8qHjHhqLsPzW5FCkO0Y

https://docs.google.com/spreadsheets/d/1d7UgIPgw__aFD6H88Zi7ZzmsB6IFyUMf/edit#gid=1564308230

### Published study links

- Paper:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8087807/
- Accessioned data: GSE167597
- Ingest: project

https://contribute.data.humancellatlas.org/projects/detail?uuid=a7c66eb1-4a4e-4f6c-9e30-ad2a485f8301&tab=project

### Key Events

- [x]  Convert published metadata to HCA spreadsheet
- [x]  Manually curate dataset to meet HCA metadata standard
- [x]  Collect any matrix and cell-type annotation files
- [x]  Upload sheet to validate metadata
- [x]  Check linking using ingest graph validator
- [x]  Transfer raw files to ingest to validate data files
- [x]  Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x]  Submit dataset to Production
- [x]  Complete the Export SOP
- [ ]  Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Downloading bam files

**Comment by ami-day** [comment]
Need to ask for cell type annotations file.

**Comment by ami-day** [comment]
Converting bam files.

**Comment by ami-day** [comment]
Uploading fastq here: b5541df6-de81-411f-b4bd-9975465f596c

**Comment by ami-day** [comment]
Need to ask authors about the cell count. All the individual sample matrix files have 6,794,879 cell barcodes, which doesn't seem right. The normalized matrix with all samples has 16,042 barcodes in total.

**Comment by ami-day** [comment]
Reply from authors:

-  ~24,000, 15,000, and 34,000, GFP+ nuclei - the approximate outputs from FACS sorting of GFP+ nuclei

-   34,231 – the total number of nuclei sequenced across experiments after filtering, of which many were not cholinergic (we speculate due to developmental expression of Chat-Cre)

- 16,042 – the total number of cholinergic nuclei actually analyzed in the study

- The individual matrix files – every single cell sequenced, regardless of quality, for each sample

Attached are the barcodes for the 16,042 cholinergic nuclei analyzed in the study with the associated annotations. Is that all you need? I can also provide the same for the 34,231 nuclei after filtering (including annotations for the excitatory and inhibitory neurons, but not beyond that) if that’s helpful.

**Comment by ami-day** [comment]
Syncing data files

**Comment by gabsie** [comment]
hey @ami-day - here are the extra matrices in H5 format: https://export.uppmax.uu.se/snic2022-23-113/datasets/Alkaslasi2021/

Please make sure they are also part of the dataset ;)
Gabs

**Comment by ami-day** [comment]
> Secondary Review: Alkaslasi
> 
> Donor_Organism
> 
> * There are 4 mice here in the spreadsheet, 2 which are male and 2 which are female
> * However, there are n = 12 mice mentioned in the paper
>   
>   * ("FACS sorted GFP+ nuclei from n = 12 mice (6 females and 6 males, 8 weeks old) were pooled from each region to obtain the nuclei analyzed in this study.")
>   * We collected ~24,000, 15,000, and 34,000, GFP+ nuclei from the cervical, thoracic, and lumbar/sacral spinal cord samples, respectively (these nuclei were pooled from n = 4 mice in 3 replicates, n = 12 total).
> * So I think there should actually be n = 12 mice here in the donor_organism tab, 6 male, 6 female?
> * 8 weeks old may be too young to be classified as 'adult' for the donor_organism.development_stage  - consider using "EFO:0001302"
> 
> Specimen from organism:
> 
> * If the above regarding donor_organism is correct, should there then be a separate specimen from each donor_organism?
> 
> Analysis_File
> 
> * Add the h5 file if it's present!

Ok done, thanks.

**Comment by ami-day** [comment]
Graph is valid. Ready for @gabsie to contact Paulo.

**Comment by ami-day** [comment]
Submitted
