### ISSUE TITLE
Improve documentation on schema update process

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#875]
**Description of the issue**

As a data wrangler that wants to update the metadata schema, I would like:
- All the documentation collected in a ticket
- All the steps, including the semi-optional ones (Like generating the test data), well documented and kept up-to-date

**Acceptance criteria**

- [ ] The documentation to be updated is collected in the ticket
- [ ] Next steps are delineated in this ticket (E.g. Merge all the documentation in a single document)
- [ ] Tickets for the next step are created/A PR is created to address this issue

**Comment by ofanobilbao** [comment]
@ami-day please, comment

**Comment by ofanobilbao** [comment]
@ESapenaVentura as per discussion on Ops Review meeting last week, @ami-day was happy with the content and did not want to add anything else. You're good to go with the content

**Comment by ofanobilbao** [comment]
I wonder, do we even need this ticket if everyone is happy with the current documentation?

**Comment by ESapenaVentura** [comment]
closing ticket!
