### ISSUE TITLE
Graph validation test deletion

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#878]
**Description of the task:**
The test `HSAPDV ontology is used for human donors` was removed from the set of ingest graph validation tests with [this](https://github.com/ebi-ait/ingest-graph-validator/commit/fed5f5ad38efed0237cba84b5c47cb25367aa4a9#diff-eae271295dcffacd51fa038b5276b9e5805c95d51b26e2a3c0888ef181a1f2e9) commit
However this change has not been deployed to production because of some integration tests failing and blocking the process.

This failed test is now bloking another dataset #852 so I would like a dev to look into what happened and to make sure the test is deleted on prod

**Priority**
Not particularly urgent, as far as I know only #852 is blocked by this test, but it would be nice to do this with some advance on the release deadline so that there is enough time to then export the dataset

**Acceptance criteria for the task:**
- [ ] the test is deleted from prod
- [ ] the [dataset](https://contribute.data.humancellatlas.org/projects/detail?uuid=8b9cb6ae-6a43-4e47-b9fb-3df7aeec941f&tab=project) from ticket #852 is passing graph validation

**Comment by Wkt8** [comment]
Either give wkt8 access or get someone with access to redeploy. 
@MightyAx to redeploy the ingest-graph-validator repo.
