### ISSUE TITLE
dataset problem - breastTranscriptomeAtlas

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#879]
**Dataset/group this task is for:**

- project uuid - 9b876d31-0739-4e96-9846-f76e6a427279

- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=9b876d31-0739-4e96-9846-f76e6a427279&tab=upload)

**Relevant People**
- Wrangler: Rachel Schwartz
- Contributor
- dev

**Description of the problem with the dataset**

I am attempting to update some biomaterial fields by downloading the spreadsheet from ingest (with uuids) and re-uploading. However I'm seeing this error and I'm unsure what's causing it:

`There was an error retrieving the schema information to process the spreadsheet. list index out of range`

**Comment by willrockout** [comment]
Here is the spreadsheet if you guys want to test
[breastTranscriptomeAtlas_from_ingest.xlsx](https://github.com/ebi-ait/hca-ebi-wrangler-central/files/9283169/breastTranscriptomeAtlas_from_ingest.xlsx)

The things we changed are listed below:
- Added donor_organism.medical_history.treatment field
- Filled in missing donor_organism.human_specific.ethnicity.ontology_label fields
- Filled in missing donor_organism.diseases.text, donor_organism.diseases.ontology, and donor_organism.diseases.ontology_label fields
- Filled in missing specimen_from_organism.diseases.text, specimen_from_organism.diseases.ontology, and specimen_from_organism.diseases.ontology_label fields
- Filled missing specimen_from_organism.biomaterial_core.biomaterial_name field
- Filled in missing cell_suspension.biomaterial_core.biomaterial_description

**Comment by ESapenaVentura** [comment]
I can see there are 2 submissions, so I am going to assume you tried to update the submission by submitting to project, effectively creating a new one instead of updating the original submission

I am going to try to update the submission with the spreadsheet provided

**Comment by ESapenaVentura** [comment]
Got error
```
There was an error retrieving the schema information to process the spreadsheet. Was unable to read metadata schema JSON at None
```
Trying to investigate what's going on. For now, I am going to try and re-introduce the "schemas" tab

**Comment by willrockout** [comment]
@ESapenaVentura That is weird because both @rachadele and I tried to update the submission from the submission page not by submitting to the project.....Also, we tried deleting the schemas tab and it raise 11 more errors to the tune of list index out of range as well as others....

**Comment by rachadele** [comment]
Acutally @willrockout @ESapenaVentura I believe did mistakenly submit to the project as Enrique mentioned. Sorry y'all!

**Comment by ESapenaVentura** [comment]
@rachadele @willrockout this is done now! :) it should be completely fine
