### ISSUE TITLE
Validation error: metadata schema update test data

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#882]
We recently submitted a pull request for metadata schema update. The update includes a new protocol type (treatment protocol) and associated ontology labels. 

I created test data for the schema change and uploaded it to ingest staging. I expected it to validate ok, however, there seems to be a validation error associated with checking the correct ontology labels are used. Specifically, the error reads: 

```
Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070] at .target_pathway[0].ontology
```
However, the provided term (positive regulation of T cell activation (_GO:0050870_) IS an acceptable ontology label for the "target pathway ontology" field. The expected schema json file with ontology requirements is this one: json_schema/module/ontology/target_pathway_ontology.json
in the [pull request 1481](https://github.com/HumanCellAtlas/metadata-schema/pull/1481)

Submission: [The cellular immune response to COVID-19 deciphered by single cell multi-omics across three UK centres](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=27c552fc-bb6e-48f2-8223-dcd6eb57f2fa)

It would be great if a dev could investigate the cause of this error message, feel free to message me on slack about this.

**Comment by gabsie** [comment]
@ami-day - please just put a link to the project with this error.

**Comment by MightyAx** [comment]
![Screenshot 2022-08-23 at 09.53.51.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/1138aa62-3230-4354-9b51-a4b227945f31)

**Comment by ESapenaVentura** [comment]
treatment protocol validates correctly in dev: https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=d1bd44e9-e930-4aa9-b92e-b654ff384821
https://api.ingest.dev.archive.data.humancellatlas.org/protocols/6304d88b90cbf9786e4ef4e0

this is pretty fishy!

**Comment by idazucchi** [comment]
@ami-day to test the same spreadsheet in dev to see if it validates

**Comment by ami-day** [comment]
It validates ok in dev: https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=3a5d3ab6-f2b4-4197-8595-5f738498cc0e&project=24fd5dbc-6c2d-48a0-9001-0b0ab0341351

**Comment by MightyAx** [comment]
The schema is available at
https://schema.staging.data.humancellatlas.org/module/ontology/1.0.0/target_pathway_ontology
```
    "ontology": {
      "description": "An ontology term identifier in the form prefix:accession.",
      "type": "string",
      "graph_restriction": {
        "ontologies": [
          "obo:hcao"
        ],
        "classes": [
          "GO:0050789"
        ],
        "relations": [
          "rdfs:subClassOf"
        ],
        "direct": false,
        "include_self": false
      },
      "user_friendly": "Target pathway ontology ID",
      "example": "GO:0043382"
```

But the ontology error being given is still 
```
Provided term is not child of [http://purl.obolibrary.org/obo/OBI_0000070] 
```

So some schema change isn't being picked up.
Did the schema change without having the version numbers changed? This might affect a schema cache that I believe exists somewhere.

**Comment by ESapenaVentura** [comment]
@MightyAx yes, it was changed, but this specific field was not changed amongst the different documents

Do you think that could be the cause anyways?

**Comment by MightyAx** [comment]
It seems that the staging ingest UI is using the prod schema service with the staging ontology service :S

**Comment by MightyAx** [comment]
I've tried restarting the ingest-validator

**Comment by ESapenaVentura** [comment]
When we post schema updates, we should probably re-start the validator (or have it re-start as a cron job?)

@ami-day to check fix

**Comment by ofanobilbao** [comment]
It is sorted

**Comment by ami-day** [comment]
It is currently exporting.
