### ISSUE TITLE
Prepare Poster for WSSS Meeting

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#884]
We are delighted to announce that our final WSSS scientific meeting, will take place in-person on Wednesday 14 September in the auditorium, Genome Campus, Hinxton.  This meeting will be a hybrid meeting, however, we very much hope that you will be able to attend in person.

- [ ] Poster is prepared with WSSS information
- [ ] Members of the team have viewed and given feedback on the poster
- [ ] Poster is printed 

https://docs.google.com/presentation/d/1P_8Xg2JkfjA0SrSM1m14-FboQoCSWY-ZltmYfJhcYQ4/edit#slide=id.p

**Comment by ofanobilbao** [comment]
It's sent for printing already
