### ISSUE TITLE
Human Cell Landscape - liver - Lei Zhang

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#89]
**Primary Wrangler:**
Ray
**Secondary Wrangler:**

**Associated files:**
`HCL-liver-issue89`
Google Drive: [HCL-liver-issue89](https://drive.google.com/drive/folders/1HhtxDwlarVP3-AqKQGYiqKsK4ROa2wH2)

**Key Events**

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [x] Receive T&C form filled out by at least 1 representative of group/project
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data files
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator
- [ ] Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission including metadata spreadsheet and data files
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Email UX to inform that they're ready to send survey

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by rays22** [comment]
The contributors disagree with one of the terms in the terms and conditions questionnaire:

    I disagree --> 2. All the data collaborators’ names and email addresses provided with the data will be available for unrestricted public view, redistribution, and reuse.

**Comment by rays22** [comment]
Sent metadata spreadsheet.

**Comment by rays22** [comment]
Sent HCA upload credentials and instructions in a separate email.

**Comment by rays22** [comment]
After finding out that the upload area had been deleted for some reason, I have set up a new upload area for this project.
I have sent my apologies and a new upload area UUID to contributor Lei Zhang.

**Comment by rays22** [comment]
Sent query to contributor about the status of the submission and offered help if needed.

**Comment by rays22** [comment]
Progress on this dataset has stalled, because I have not heard from the contributors for awhile.

**Comment by ami-day** [comment]
We decided this is not suitable due to inability to get data and so we are closing it. There is no data available even in matrix format and Ray has not been able to get more information from the contributors as they are not responding.
