### ISSUE TITLE
GSE134174 - smokingAirwayEpithelium

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#892]
### Project short name: 
smokingAirwayEpithelium

### Primary Wrangler:
Ida
### Secondary Wrangler:
Ami

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1glL0s_LoL0tADrqyX7-v8ItoZUtJTiv9)

### Link to Ingest:
https://contribute.data.humancellatlas.org/projects/detail?uuid=34c9a62c-a610-4e31-b343-8fb7be676f8c 

### Published study links

* Paper: [Dissecting the cellular specificity of smoking effects and reconstructing lineages in the human airway epithelium](https://www.nature.com/articles/s41467-020-16239-z)

* Accessioned data: [GSE134174](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE134174) 

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
There are two parts to this dataset:

#### Tissue ex vivo 
15 samples analysed with 10x. According to GEO it's 3' v3 for all of them but:
 - the lung atlas reports the dataset as 3' v3 and 3' v2
- some file lengths match 3' v3, some 3' v2, while some look like full length sequencing (both reads 151bp)
</br>

#### Cultured tissue
20 time point per donor, 3 donors. I've modelled it as timecourse but I'm not sure it's done correctly. 
The samples are grouped together by chip --> legend available from geo `GSE134174_TXX_invitro_metadata.txt.gz`
According to GEO these were analysed with:
> ICELL8 single-cell poly-(A)+ transcriptome amplification hands-on workflow (with Triton X-100 for cell lysis), protocol D07-000040-003 rev4

This should be a full length technique but the read lenght are compatible with 10x v2 (R1=26pb, R2=101pb) --> is the techinque the wrong one or is it actually tag-based?

**Comment by idazucchi** [comment]
I'm sending an email to the authors to confirm the 10x kit used for some runs and barcode/UMI length for ICELL8 library preparation

In the mean time I'm validating the spreadsheet, file and graph 

I should be able to make most changes with a bulk update if needed

**Comment by idazucchi** [comment]
I got a reply today!
- [ ] assumptions on the 10x version correct
- [ ] ICELL8 umi and cell barcode lengths

**Comment by ami-day** [comment]
This all looks very good to me! Some minor comments:

**Project**

- Some of the technologies are missing
- The organ is Lung but it is Trachea in the metadata sheet

**Cell suspension**

- ROCK1 inhibitor is included in drug treatment field, but it is a standard inhibitor used for maintenance of appropriate cell culture conditions. It is not e.g. a therapeutic drug or other small molecule used to induce a specific drug response.

**Library preparation protocol**

- I don't see any link to library_protocol_10x_v2 - should it be deleted? (this is relevant to comment above about the listed project technology types)

**Analysis file**

- The cell count estimates again seem much higher than the estimated cell count recorded in the Project metadata. It might be worth checking, if you haven't already, where the Project estimate came from. If it is quoted in the publication, it can be assumed that this was the estimate post-filtering/processing.

**Comment by idazucchi** [comment]
I fixed the missing information in the project and moved ROCK1 to the growth medium instead.
I checked that library_protocol_10x_v2 is linked correctly and the cell count discrepancy is down to quality control

**Comment by idazucchi** [comment]
checked in the browser
