### ISSUE TITLE
Check for duplicate Projects in Ingest

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#896]
**Check for duplicate Projects in Ingest:**

EBI Wranglers need to check that the Projects they've wrangled or are in the process of wrangling don't have any duplicates in Ingest.

They will:

- [x] Check Projects that they have submitted to DCP / Check Projects that they have in Progress / Check Projects were they are the assigned wrangler
- [x] Identify Duplicates
- [x] Copy over any missing Project Information from duplicates to Project copy that contains submission (including Catalogue tick)
- [x] Delete any redundant copies of the projects

**Acceptance criteria for the task:**

- [x] Projects checked
- [x] Copied over missing information.
- [x] All Projects are marked for the Catalogue
- [x] All required duplicates have been deleted

**Comment by MightyAx** [comment]
We can solve this with code:
**Without taking action**, highlight duplicates and recommend what is real/imposter by:

1. Get all projects from ingest
2. for all projects in ingest search doi / and title to see if an imposter project exists
3. Highlight which projects are "real" and which are imposters by:
    - checking the UUID in AZUL
    - Which projects have submissions that have been exported (submissionEnvelope/{id}/exportJobs/
    - projects without submissions are probable imposters

**Comment by ESapenaVentura** [comment]
Azul's endpoint: `https://service.azul.data.humancellatlas.org/index/projects/{project_uuid}`

**Comment by MightyAx** [comment]
@gabsie @ofanobilbao to review

**Comment by MightyAx** [comment]
Given the above I would recommend the following
1. Delete any project from the list above that does not have a submission, which leaves:
```

UUID: a29952d9-925e-40f4-8a1c-274f118f1f51 Key: 10.1038/s41591-018-0269-2 External: Found In Azul, Submissions: 1 Exported: 2
UUID: 4a95101c-9ffc-4f30-a809-f04518a23803 Key: 10.1038/s41591-018-0269-2 External: Found In Azul, Submissions: 1 Exported: 2
UUID: 54661b25-f2a9-4474-85fe-c482380db2a4 Key: 10.1038/s41586-019-1373-2 External: Not in Azul, Submissions: 1 Exported: 0
UUID: 94e4ee09-9b4b-410a-84dc-a751ad36d0df Key: 10.1038/s41586-019-1373-2 External: Found In Azul, Submissions: 1 Exported: 4
UUID: 56e73ccb-7ae9-4fae-a738-acfb69936d7a Key: 10.1038/s41556-020-00607-4 External: Found In Azul, Submissions: 1 Exported: 3
UUID: 8dacb243-e918-4bd2-bb9a-aac6dc424161 Key: 10.1038/s41556-020-00607-4 External: Found In Azul, Submissions: 1 Exported: 3
UUID: e56646ec-61fa-48ea-98d5-e0b793b0eb09 Key: doi.org/10.7554/eLife.32303.001 External: Not in Azul, Submissions: 1 Exported: 0
UUID: 5bb1f67e-2ff0-4848-bbcf-17d133f0fd2d Key: doi.org/10.7554/eLife.32303.001 External: Found In Azul, Submissions: 1 Exported: 2
UUID: 5391ccd6-7d90-405c-ba55-4b726ee74421 Key: 10.1038/s41586-021-03570-8 External: Not in Azul, Submissions: 1 Exported: 0
UUID: 61515820-5bb8-45d0-8d12-f0850222ecf0 Key: 10.1038/s41586-021-03570-8 External: Not in Azul, Submissions: 1 Exported: 2
UUID: 75d53067-5fc1-40d1-8964-86b5ab2f71bf Key: 10.1016/j.cell.2016.07.054 External: Not in Azul, Submissions: 1 Exported: 0
UUID: 48147975-d3f0-4d96-92fe-ad0bc5fe2183 Key: 10.1016/j.cell.2016.07.054 External: Not in Azul, Submissions: 1 Exported: 0
```

2. Delete the following because they are not exported, and an exported submission for another doi exists:

- UUID: `5391ccd6-7d90-405c-ba55-4b726ee74421` Key: `10.1038/s41586-021-03570-8`
- UUID: `e56646ec-61fa-48ea-98d5-e0b793b0eb09` Key: `doi.org/10.7554/eLife.32303.001`
- UUID: `54661b25-f2a9-4474-85fe-c482380db2a4` Key: `10.1038/s41586-019-1373-2`

This would leave the following duplicates for manual investigation:
```
UUID: a29952d9-925e-40f4-8a1c-274f118f1f51 Key: 10.1038/s41591-018-0269-2 External: Found In Azul, Submissions: 1 Exported: 2
UUID: 4a95101c-9ffc-4f30-a809-f04518a23803 Key: 10.1038/s41591-018-0269-2 External: Found In Azul, Submissions: 1 Exported: 2
UUID: 56e73ccb-7ae9-4fae-a738-acfb69936d7a Key: 10.1038/s41556-020-00607-4 External: Found In Azul, Submissions: 1 Exported: 3
UUID: 8dacb243-e918-4bd2-bb9a-aac6dc424161 Key: 10.1038/s41556-020-00607-4 External: Found In Azul, Submissions: 1 Exported: 3
UUID: 75d53067-5fc1-40d1-8964-86b5ab2f71bf Key: 10.1016/j.cell.2016.07.054 External: Not in Azul, Submissions: 1 Exported: 0
UUID: 48147975-d3f0-4d96-92fe-ad0bc5fe2183 Key: 10.1016/j.cell.2016.07.054 External: Not in Azul, Submissions: 1 Exported: 0
```

**Comment by ofanobilbao** [comment]
Thanks @MightyAx. I will review with Gabs and let you know. I went through the first few duplicates on Friday, and it might not be as easy as purely delete the copies without submission. We need to first copy a few fields from the Project Information into the copy with submission. But also, I found at least a few odd cases where the publication etc seemed to be incorrect. So some investigations might be required before deleting anything.

**Comment by ESapenaVentura** [comment]
@ofanobilbao to tag @MightyAx  when we have the list of projects to delete

**Comment by ofanobilbao** [comment]
I am nearly done working through the list. I will post update tomorrow in the ticket

**Comment by ami-day** [comment]
Thanks @MightyAx for this awesome works, saves so much time when mostly automated!

**Comment by ofanobilbao** [comment]
OK, so I've gone and amended almost all required duplicates. Most are fine now. Hopefully with the recently launched improvements, no more duplicates will be created.

I will create separate tickets for all the Project entries or Datasets that require some action and tag the appropriate people. I will move this ticket to Done. As the scope of the ticket has been more than fulfilled now. I will link the Action tickets into the epic to track them together
