### ISSUE TITLE
multiple datasets stuck in "graph validation requested" status

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#897]
I made updates to 2 datasets on Friday (or maybe Monday) and then re-validated them. I clicked "graph validate" and they have both been in "graph validation requested" status ever since. I think they are likely stuck, as they should be graph validating by now? Here are the submissions:

https://contribute.data.humancellatlas.org/submissions/detail?uuid=bdd1b6ca-7431-413e-97ec-71e36bf6073d&project=b7259878-436c-4274-bfff-ca76f4cb7892

https://contribute.data.humancellatlas.org/projects/detail?uuid=e0c74c7a-20a4-4505-9cf1-38dcdd23011b&tab=upload

https://contribute.data.humancellatlas.org/projects/detail?uuid=a62dae2e-cd69-4d5c-b5f8-4f7e8abdbafa&tab=upload

Also newly created submissions:

https://contribute.data.humancellatlas.org/projects/detail?uuid=dcbb50d1-9acf-4f70-9fda-b1f63a948c49&tab=upload

https://contribute.data.humancellatlas.org/projects/detail?uuid=1fa8b11f-56fa-45a6-a777-6af70e17a6b3&tab=upload

https://contribute.data.humancellatlas.org/projects/detail?uuid=c8e6c5d9-fcde-4845-bead-ff96999e3051&tab=upload

**Comment by MightyAx** [comment]
The graph validator has "silently crashed" Restarting it has reprocessed all the items waiting for graph validation.
```
kubectl rollout restart deployment ingest-graph-validator
```
