### ISSUE TITLE
Assessment of how many suitable AE datasets are available for DCP2

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#9]
**Description of the task:**

The goal is to incorporate suitable AE datasets into HCA DCP2 to help build the Human Cell Atlas.

These are the remaining tasks of [Prototype process to FAIRify datasets in ArrayExpress and GEO #1242](https://github.com/HumanCellAtlas/metadata-schema/issues/1242) related to the documentation of AE -> HCA data flow.

This issue is a copy of [#1272](https://github.com/HumanCellAtlas/metadata-schema/issues/1272) in the new public repo.

**Acceptance criteria for the task:**

~- [ ] Document the AE -> HCA data/metadata flow.
    - [ ] 1. Process definition for the conversion of AE metadata to HCA standards.
    - [ ] 2. Process definition for uploading converted metadata and data to HCA.~ The documentation component of this issue has been transferred to <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/23> 
- [x] Assessment of how many datasets suitable for DCP2 are in AE

**Comment by lauraclarke** [comment]
Part of this task is liked to the new task defined in https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/6 @rays22 do you think it is worth editing this task to reflect that?

**Comment by rays22** [comment]
> Part of this task is linked to the new task defined in #6 @rays22 do you think it is worth editing this task to reflect that?

@lauraclarke ,
Yes, I agree. I am going to edit this task to align its goals with that of [#6](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/6).

**Comment by rays22** [comment]
My plans for this task are:
- make a list of datasets that have been
    - assessed and added to the HCA spreadsheet, in particular those, that have been
        - converted to HCA format
            - find the location of converted metadata
            - find the location of raw data to be uploaded to HCA
- do a trawl in ArrayExpress (AE) for datasets that would be suitable for HCA, but are yet to be converted to HCA format
    - use the HCA publication list as a starting point, but
    - look for other potential datasets too

I am making a new ticket to separate the documentation component of this issue and thereby

> Document the AE -> HCA data/metadata flow.
> 1. Process definition for the conversion of AE metadata to HCA standards.
> 2. Process definition for uploading converted metadata and data to HCA.

to make this task more focussed and aligned with the current sprint goal
[Key result 1: A list of new data which can be submitted to DCP2 from contributors and AE/GEO](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/6)

**Comment by rays22** [comment]
* 3 publications out of 41 on the HCA publication list have associated data and metadata in ArrayExpress. See sheet [HCA publication list with status](https://docs.google.com/spreadsheets/d/1lYRD42Yo05w0HXNaRNpQCxKrXpRs-BNS/)
 * Wrangling status from the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0) :

```
HCA Project Short Name  Archival Accession ID   HCA status  HCA status Comment
Fetal/Maternal Interface    E-MTAB-6701;E-MTAB-6678 Complete - in DCP   
WongAdultRetina E-MTAB-7316 Complete - in DCP   archival ids need to be added to metadata
haniffa-fetal-liver E-MTAB-7407 Complete - in EBI archive   Partially in ArrayExpress, SS2 and VDJ not, all needs to be submitted to DCP

```

**Comment by rays22** [comment]
There are 53 datasets with data in ArrayExpress. Some of the 53 overlap with GEO datasets.
* 5 datasets are already in DCP
* 2 datasets have validated HCA spreadsheets
* 4 datasets are in progress at various stages of curation/conversion
* 1 uncurated dataset is on the humancellatlas.org publication list
* 11 datasets (to be curated) flagged as medium priority
* 11 datasets (to be curated) flagged as low low priority
* 1 dataset unsutiable (only 1 fastq)
* the rest of the datasets blocked, because data embargo or unavailability

**Comment by rays22** [comment]
I have not been able to identify any new ArrayExpress datasets in Europe PMC  or ArrayExpress itself that are not already targeted in our [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0).
I have found one candidate in ArrayExpress (which happens to be a GEO submission):

* Single-cell RNA-Seq profiling of human preimplantation embryos and embryonic stem cells.
Nature Structural & Molecular Biology, 11 Aug 2013, 20(9):1131-1139
DOI: 10.1038/nsmb.2660 PMID: 23934149
Functional Genomics Experiments in ArrayExpress
    * Tracing pluripotency of human early embryos and embryonic stem cells by single cell RNA-seq
    (ArrayExpress - E-GEOD-36552) 
E-GEOD-36552 - Tracing pluripotency of human early embryos and embryonic stem cells by single cell RNA-seq

**Comment by lauraclarke** [comment]
Thanks for this assessment @rays22 it looks great, is everything now in the data tracking sheet?

On a related note, Have you looked at how the 74 human datasets in SCEA overlap with this list? https://www.ebi.ac.uk/gxa/sc/experiments?species=homo%20sapiens

For the GEO dataset, I think they try and keep the number the same between GSE and E-GEOD if you wanted to check if we already have the GEO dataset tracked anywhere

**Comment by rays22** [comment]
> Thanks for this assessment @rays22 it looks great, is everything now in the data tracking sheet?

I need to double check which datasets to add to the spreadsheet [Datasets for DCP2.0 MVP](https://docs.google.com/spreadsheets/d/1lJFPR-loZuBhKdijOcSOn7wqe_-N4MYWKJkLFfRqefU/edit#gid=165291923)
<https://docs.google.com/spreadsheets/d/1lJFPR-loZuBhKdijOcSOn7wqe_-N4MYWKJkLFfRqefU/edit#gid=165291923>
, but the AE datasets are already in the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0)
<https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0>
.


> On a related note, Have you looked at how the 74 human datasets in SCEA overlap with this list? https://www.ebi.ac.uk/gxa/sc/experiments?species=homo%20sapiens

@lauraclarke 
No, I am afraid not yet. I will compare the datasets on that list with my list.

**Comment by rays22** [comment]
- I have not been able to do a comprehensive comparison of the SCEA list of 74 human datasets with the list of datasets in our dataset tracking sheet. The reasons are as follows:
The comparison of the 74-long SCEA list with the 504-long dataset tracking list would require considerable manual effort.
    * The `Title` is the only dataset identifier on the SCEA list. However, it is not consistently the title of any related publication. I would need to click on each title on the SCEA list and manually copy the relevant publication information. I have not been able to find a way to download the relevant publications in bulk.
    * Our dataset tracking sheet contains publication titles. I should note that there are many duplicate rows that share the same publication title(s). However, inconsistent punctuation and special characters make programmatic comparison of the 504 unique titles with the 74 titles on the SCEA list very difficult.

I am opening a new ticket to address the question about the overlap of the [SCEA list](https://www.ebi.ac.uk/gxa/sc/experiments?species=homo%20sapiens) and the [Dataset Tracking Sheet](https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/):
<https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/37>.
