### ISSUE TITLE
Add project labels for all HCA samples

### ISSUE THREAD

**Issue by FuqiX** [ebi-ait/hca-ebi-wrangler-central#90]
**Description of the task:**

As a data consumer, I am looking for a single query to retrieve all HCA samples. One solution is to use a consistent project label for all HCA samples. 

For example, many HCA samples have the"project: Human cell Atlas" label. These samples can be retrieved using https://www.ebi.ac.uk/biosamples/samples?filter=attr:project:Human%20Cell%20Atlas 

As discussed with Enrique, here are some __potential tasks:__
- [x] Decide which project label to use, i.e. `project: Human Cell Atlas`?
- [x] Find all existing HCA samples in BioSD
- [x] Update existing samples and make sure every sample has the correct project label.
- [x] Add the project label to all future samples.

__Related materials:__
1. What is a project label
```project label example
{
	"characteristics": {
		"project": {
			"text": "Human Cell Atlas"
		}}}
```
2. related sample accessions:
[all samples in subs-team-2](https://www.ebi.ac.uk/biosamples/accessions?filter=domain:subs.team-2&size=1000)
[all samples in subs-team-20](https://www.ebi.ac.uk/biosamples/accessions?filter=domain:subs.team-20&size=1000)
[Samples with the HCA project lable](https://www.ebi.ac.uk/biosamples/samples?filter=attr:project:Human+Cell+Atlas)

cc @cinciaT

**Comment by ESapenaVentura** [comment]
@lauraclarke @clairerye Fuqi and I talked about this.

This request does not require any change in the archiver, as it's already generating a `"{"project": "Human Cell Atlas"}` label.

The only work that has to stem from this is to update the samples for the 2 submissions that were archived outside of the archiver:

- https://www.ebi.ac.uk/biostudies/studies/S-SUBS5
- https://www.ebi.ac.uk/biostudies/studies/S-SUBS4

I think this is feasible in a short amount of time and it's a really great feature. Also @FuqiX you commented that we could maybe show "HCA samples" in the main webpage so they could retrieve them just by clicking there, right?

**Comment by FuqiX** [comment]
>  @FuqiX you commented that we could maybe show "HCA samples" in the main webpage so they could retrieve them just by clicking there, right?

Yep. The idea is to display it on [BioSD homepage](https://www.ebi.ac.uk/biosamples/), along with FAANG, HipSci. The layout might be slightly different.  cc @mcourtot

**Comment by ESapenaVentura** [comment]
I have been working on this and I've found a problem when updating the samples.

It seems that for all BioSamples that are "lower" than donor (Specimen, cell suspension), it throws the error `Failed to change release date for "<accession>". Invalid accession. Only study, project or sample release dates may be changed.`

I have sent a ticket to DSP and waiting for the response. For now we can't proceed with this the intended way.

**Comment by ESapenaVentura** [comment]
All samples from S-SUBS5 have been labelled with the project: Human Cell Atlas label!

DSP submission [here](https://submission.ebi.ac.uk/api/submissions/75356816-cc41-45f8-9980-15b733f505c1)

**Comment by ESapenaVentura** [comment]
All samples from S-SUBS4 have been labelled with the attribute `project: Human Cell Atlas"` 

DSP Submission [here](https://submission.ebi.ac.uk/api/submissions/86ad8b71-19f1-4385-9c23-6e8fb5250f74)

**Comment by ESapenaVentura** [comment]
The data is not yet indexed but looking at requests to the hinxton server, all samples have been successfully updated.

All the future samples will be labelled with `project: Human Cell Atlas`.

Is there any further action we need to take @FuqiX @CinciaT?

**Comment by FuqiX** [comment]
it looks good to me. Ticket closed. Thanks!
