### ISSUE TITLE
Migrating CxG Datasets to 3.0.0

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#904]
Hi Wei (whenever you are back),
We are surveying Private CxG Datasets for migration to 3.0.0
Would you be able to update the Datasets in these Collections to ensure that obs.donor_id is filled in?
https://cellxgene.cziscience.com/collections/a8b45dbb-5e0b-48a5-ac57-1b9b70b42744
https://cellxgene.cziscience.com/collections/762afb8d-874b-4922-890b-a9e348fc6b91
https://cellxgene.cziscience.com/collections/e33ffcd3-7cbf-4b8c-b0f4-85587ad5019a
https://cellxgene.cziscience.com/collections/41b49bd7-b1d6-4c72-8eea-5e0f601dd824

Hoping to have donor_id in place for everything by Sept 30th - let me know if you think that's doable

**Acceptance criteria for the task:**
Following datasets have donor_id in the obs layer 
- [x] https://cellxgene.cziscience.com/collections/a8b45dbb-5e0b-48a5-ac57-1b9b70b42744
- [x] https://cellxgene.cziscience.com/collections/762afb8d-874b-4922-890b-a9e348fc6b91
- [x] https://cellxgene.cziscience.com/collections/e33ffcd3-7cbf-4b8c-b0f4-85587ad5019a
- [ ] https://cellxgene.cziscience.com/collections/41b49bd7-b1d6-4c72-8eea-5e0f601dd824

**Comment by Wkt8** [comment]
One more left!

**Comment by ofanobilbao** [comment]
We are over the deadline in the ticket. Is this ticket still required @Wkt8 ?

**Comment by ofanobilbao** [comment]
@Wkt8 is this still required? Should it stay in the backlog or be closed?
