### ISSUE TITLE
Investigate linking thousands of cell suspensions in ingest

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#905]
**Background**

An example dataset:
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/889

For some datasets, there are thousands of cell ids linked to 1 analysis file, and they will not all fit in 1 cell in Excel or Google Sheets. We need to be able to link all the cell suspensions to 1 Analysis file, or, alternatively, to 1 additional cell suspension (like an experiment accession). In the above dataset, I cannot do both of these things, because the number of cell ids is so large.

**Aim**

- [ ] Discuss approach with other wranglers
- [ ] Most likely outcome: find a way to implement the linkings in ingest, bypassing the limit imposed in Excel and Google Sheets

**Comment by ofanobilbao** [comment]
@ami-day might have found a workaround. Will work on this today and update the ticket later

**Comment by ami-day** [comment]
I found a workaround, therefore I am closing this ticket.
