### ISSUE TITLE
Add Project to Catalogue - 34ec845b-cd7a-4c43-99e4-d2932d5d85bb

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#908]
Project [34ec845b-cd7a-4c43-99e4-d2932d5d85bb](https://contribute.data.humancellatlas.org/projects/detail?uuid=34ec845b-cd7a-4c43-99e4-d2932d5d85bb&tab=project) contains a submission in Metadata Validating status.

That makes the project non editable.

Acceptance criteria:
- [x] Sort submission status issues - set to Valid
- [x] Catalogue box is ticked

**Comment by amnonkhen** [comment]
project set to Valid

**Comment by amnonkhen** [comment]
Project visible in Catalogue
