### ISSUE TITLE
Add Project to Catalogue and sort Submission Status

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#910]
Project [8559a8ed-5d8c-4fb6-bde8-ab639cebf03c](url) has a submission in "Exporting" status. From the query that Alexie run, I know that this project is in DCP.

The DCP shows an update on January 2022. I believe that's when the analysis from pipelines was added. There has been no further updates. Maybe is related to the schema version bump that took place recently.

I also can't add the tick to add to the Catalogue as the Project in non editable due to the submission.

Acceptance criteria:

- [x] Check if the submission has exported successfully.
- [x] Submission is not stuck in an In Progress status, but in either exported, etc
- [x] The project information tab is edited to tick the Catalogue box.
- [x] The project is available in the Catalogue with a link to DCP

**Comment by ESapenaVentura** [comment]
The submission is in DCP, and only contains 1 import request from a year ago so I will assume everything went smoothly

[Submission](https://contribute.data.humancellatlas.org/submissions/detail?uuid=8c5d513d-e3e9-4661-862a-ba7e23928706&project=8559a8ed-5d8c-4fb6-bde8-ab639cebf03c) should be in "Exported" status

I will work on it and update the metadata

**Comment by ESapenaVentura** [comment]
Submission set to `Exported` using the script in https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/restart-submission

Parameters:
```
sh restart-submission.sh -s 6171cc1e30cc2b2282b18764 -t <ingest_token> -n "Exported" 

```

**Comment by ESapenaVentura** [comment]
It's in the catalogue now with a link to the DCP https://www.ebi.ac.uk/humancellatlas/project-catalogue/
