### ISSUE TITLE
Sort out projects with matching DOI in Ingest & DCP

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#911]
**Sort out projects with matching DOI in Ingest & DCP**

There are two Projects in Ingest, that are also published in DCP that share the same DOI. If you look at the projects, there are inconsistencies. They do not look right.

The projects are:

- [A single-cell reference map of transcriptional states for human blood and tissue T cell activation](https://contribute.data.humancellatlas.org/projects/detail?uuid=4a95101c-9ffc-4f30-a809-f04518a23803)

- [Bone marrow plasma cells from hip replacement surgeries](https://contribute.data.humancellatlas.org/projects/detail?uuid=a29952d9-925e-40f4-8a1c-274f118f1f51)

**Acceptance criteria for the task:**

- [x] Wranglers have checked both projects
- [x] Wranglers have discussed issues (if any) and come up with actions (if any)
- [x] Wranglers have sorted out the projects (if need be)

**Comment by ofanobilbao** [comment]
For Project [n1](https://contribute.data.humancellatlas.org/projects/detail?uuid=4a95101c-9ffc-4f30-a809-f04518a23803) : 

- The accession and the linked publication match (Published Dec 2018), but the contributors and contacts, and title and other Project details don't really match with the paper

**Comment by ofanobilbao** [comment]
Likewise, for [Project n2](https://contribute.data.humancellatlas.org/projects/detail?uuid=a29952d9-925e-40f4-8a1c-274f118f1f51):

- The accession and the linked publication match but the contributors and contacts, and title etc don't seem to match.

1st published in DCP in May 2019. Updated in November 2021

**Comment by ofanobilbao** [comment]
Question for the wranglers: Maybe for Enrique for historical background or UCSC wranglers (Paris or Will).

Are these ok?

Or are these two parts of the same publication? Odd thing is that the authors don't match either

**Comment by ESapenaVentura** [comment]
P1 is not correct

Project N1 corresponds to this paper https://www.nature.com/articles/s41467-019-12464-3#data-availability

If we take a look at the GSE accession, https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126030

We see that there are several PP... samples, with the exact same IDs as in the metadata https://contribute.data.humancellatlas.org/projects/detail?uuid=4a95101c-9ffc-4f30-a809-f04518a23803&tab=metadata

**Comment by ESapenaVentura** [comment]
The dataset was wrangled by Chris, so I am going to ask the UCSC wranglers what the deal is with this dataset, exposing that the accession seems to match with this other accession

**Comment by ESapenaVentura** [comment]
Project is exporting and import request has been sent

Waiting on the export to finish to apply staging area fixes (Needed as DCP1 dataset)

**Comment by ESapenaVentura** [comment]
The export is going to fail due to file sizes not being present in the metadata of the files

**Comment by ESapenaVentura** [comment]
The submission is in a permanent Draft status, I have tried to change it but it's not working

**Comment by ESapenaVentura** [comment]
Project has been exported

To re-start the submission, I have followed the instructions on this script https://github.com/ebi-ait/hca-ebi-dev-team/blob/master/scripts/restart-submission/restart-submission.sh

The PR will follow once I add these last steps!
