### ISSUE TITLE
Submission stuck in Exporting - GSE132065_BloodTimeHuman

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#912]
**Project Published in DCP has a submission that is now stuck in Exporting status**

Project [GSE132065_BloodTimeHuman](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b328561-4a97-40ac-b7ad-6a90fc59d374&tab=project) was Published in DCP a while ago.

Now the submission is stuck in "Exporting".

We probably want to sort it out in case we want to do any updates in the future. And also so that the status matches what's been done to that project.

Acceptance Criteria:
- [x] Discover why is stuck
- [x] The submission is not on an In Progress Status but on a definitive one (Exported for example)

**Comment by MightyAx** [comment]
Last attempt to export (just metadata): 22nd July
Our logs don't go that far back.

I'll reset back to graph valid and attempt to re-export (just metadata) now.

**Comment by MightyAx** [comment]
Export in progress, will monitor

**Comment by MightyAx** [comment]
In progress: 288/408 done
No errors so far.

**Comment by idazucchi** [comment]
if the export fails we can force the state to exported so in the future we can change the project info and make other updates.
The downstream components are not ready to import the updates done in June 2022 yet so there is no need for an import form

**Comment by MightyAx** [comment]
Exported!
