### ISSUE TITLE
stuck in validating: chronicWoundDiabetes

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#913]
*Project Info*
uuid: 34ec845b-cd7a-4c43-99e4-d2932d5d85bb
project short name: chronicWoundDiabetes
primary wrangler: Rachel Schwartz

*background* Several sequence files have been validating for 2 days.
* slack link: 
* email: 

Note:
assign to the current dev on operations.

**Comment by ESapenaVentura** [comment]
Duplicate of https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/908, but thanks for creating the ticket!
