### ISSUE TITLE
dataset problem -  Project stuck in graph validating state

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#914]
**Dataset/group this task is for:**

 Project stuck in graph validating state
In addition, this is a submission which I would like to delete. Hence, if possible, unsticking it and then deleting the submission (**not** the project) would be great.

https://contribute.data.humancellatlas.org/projects/detail?uuid=a4f154f8-5cc9-40b5-b8d7-af90afce8a8f&tab=project
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/853

**Comment by Wkt8** [comment]
@ami-day to close or to double-check

**Comment by amnonkhen** [comment]
The submission status is *Metadata Invalid*
@ami-day to check

**Comment by gabsie** [comment]
This is sorted.
