### ISSUE TITLE
GSE128531 - Single-Cell Lymphocyte Heterogeneity in Advanced Cutaneous T-cell Lymphoma Skin Tumors

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#915]
### Project short name:
TCellLymphomaHeterogeneity ?
### Primary Wrangler:
Ami

### Secondary Wrangler:
Ida

### Associated files

* Google Drive:

https://docs.google.com/spreadsheets/d/1P4KTCaJg-YtF7GY-rRaPqKR658AnTerW7a1yAuF0xmk/edit#gid=1636914881

### Published study links

* Paper: [Single-Cell Lymphocyte Heterogeneity in Advanced Cutaneous T-cell Lymphoma Skin Tumors](https://doi.org/10.1158/1078-0432.ccr-19-0148)

* Accessioned data: [GSE128531](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE128531)

* ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=990d251f-6dab-4a98-a2b6-6cfe7e4708b9)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Hi ami, I'm done with the review! It looks great I only have a few comments.

### Project
- the project label is missing
- you should add yourself as a curator!

### Library
- you can add PCR in the cDNA amplification


### Analysis protocol
- please remove the `|` from computational methods, it's not allowed

### Analysis file
- add file source
- the content description should be count matrix

**Comment by ami-day** [comment]
Submitted import form as it successfully exported.

**Comment by ami-day** [comment]
Looks good.
