### ISSUE TITLE
dataset problem - Error deleting submission

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#916]
Project: HumanMelanocyteDevelopment ebi-ait/hca-ebi-wrangler-central#853
I would like to delete a submission from a project in ingest (prod), however I am getting an unusual error trying to do. Would it be possible for a dev to delete the submission (and keep the project)?

- uuid: `a4f154f8-5cc9-40b5-b8d7-af90afce8a8f`
- [ingest ui](https://contribute.data.humancellatlas.org/projects/detail?uuid=a4f154f8-5cc9-40b5-b8d7-af90afce8a8f&tab=upload)
- dataset ticket: ebi-ait/hca-ebi-wrangler-central#853

This has also happened for an additional project when I tried to delete a submission:
[SARS-CoV-2InfectionOralCavity](https://contribute.data.humancellatlas.org/projects/detail?uuid=dcbb50d1-9acf-4f70-9fda-b1f63a948c49) - uuid `dcbb50d1-9acf-4f70-9fda-b1f63a948c49`
 
```
An error has occurred while deleting the submission w/UUID bb8ee0dc-97f9-4340-9c28-831162336a54 (SARS-CoV-2 infection of the oral cavity and saliva.)
```

```
Http failure response for https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/6315e2c7f720a669b7be9ea0: 0 Unknown Error"
```

**Comment by amnonkhen** [comment]
Still investigating.

**Comment by amnonkhen** [comment]
There is a NullPointerException in the logs:

```
{"log":"\u0009at org.humancellatlas.ingest.submission.web.SubmissionController.forceDeleteSubmission(SubmissionController.java:372) ~[classes!/:na]\n","stream":"stdout","time":"2022-09-23T18:00:18.262577079Z"}
2022-09-23 19:00:18	
{"log":"\u0009at org.humancellatlas.ingest.submission.SubmissionEnvelopeService.deleteSubmission(SubmissionEnvelopeService.java:240) ~[classes!/:na]\n","stream":"stdout","time":"2022-09-23T18:00:18.262571109Z"}
2022-09-23 19:00:18	
{"log":"java.lang.NullPointerException: null\n","stream":"stdout","time":"2022-09-23T18:00:18.262566469Z"
```

**Comment by MightyAx** [comment]
```
DELETE https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/6329972dd95e613712f0fe2a
```
504 GATEWAY TIMEOUT
The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.

**Comment by ESapenaVentura** [comment]
Ami was able to delete/ import a new submission without problems

**Comment by Wkt8** [comment]
I also got this error, but after a few minutes and a refresh it resolved and the submission was deleted

**Comment by amnonkhen** [comment]
@amnonkhen to check whether still relevant

**Comment by amnonkhen** [comment]
no longer relevant - closing
