### ISSUE TITLE
stuck in validating: scAnalysisOfEndometriosis

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#919]
*Project Info*
uuid: `445d3182-ab53-4ede-80bc-a6a4d43acfe0`
project short name: scAnalysisOfEndometriosis
primary wrangler: Rachel Schwartz

project has been metadata validating for >24 hours, 2 files still validating

Note:
assign to the current dev on operations.

**Comment by ESapenaVentura** [comment]
Submission is not validating anymore, is there anything else that we need to do here?

**Comment by rachadele** [comment]
yes, there was a graph error and I had to create a new project: 2b81ecc4-6ee0-438f-8c5b-c10b2464069e
still stuck in validating

**Comment by MightyAx** [comment]
I found the issue, these two files been unable to validate.
Using the [Retrigger FIle Validation Script](https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/retrigger_file_validation)
