### ISSUE TITLE
Archive "Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts"

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#92]
This dataset has metadata archived at BioStudies and BioSamples but is yet to be archived in ENA

The latest spreadsheet is here:

https://drive.google.com/drive/folders/16EgE-SBBwXWQe8G_edWXNkNj3XSMl36-

It has a related AUDR ticket here:

HumanCellAtlas/hca-data-wrangling#366

AUDR issues are fixed in the latest spreadsheet but this dataset will still require an update in the archives

The data is in DCP1 DSS

Original tracker ticket: https://github.com/HumanCellAtlas/hca-data-wrangling/issues/284

**Comment by ESapenaVentura** [comment]
@aaclan-ebi issued a fix for the pooled samples issue.

I suggest we try archiving this dataset this sprint as a test.

**Comment by ami-day** [comment]
Hi @jacobwindsor what was the problem with archiving this dataset?

**Comment by ofanobilbao** [comment]
@ESapenaVentura what is it that is missing to be done for this dataset? It is not completely clear from the ticket. This dataset is in the DCP portal.

**Comment by ESapenaVentura** [comment]
This dataset is missing archiving!
