### ISSUE TITLE
stuck in Submitted: biliaryTractCancerImmuneAtlas

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#935]
*Project Info*
uuid: `28371655-60ba-449e-a303-5859b29ead65`
project short name: biliaryTractCancerImmuneAtlas
primary wrangler: Rachel Schwartz

Project has been stuck in 'submitted' status for ~5 days
* slack link: 
* email: 

Note:
assign to the current dev on operations.

**Comment by Wkt8** [comment]
Rachel, we believe the project is now in the 'Complete' status. Please close if no further action is needed.
