### ISSUE TITLE
stuck in submitted: scAnalysisOfEndometriosis

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#936]
*Project Info*
uuid: `2b81ecc4-6ee0-438f-8c5b-c10b2464069e`
project short name: scAnalysisOfEndometriosis
primary wrangler: Rachel Schwartz

Project has been stuck in 'submitted' status for ~5 days.

Note:
assign to the current dev on operations.

**Comment by Wkt8** [comment]
Rachel, we believe the project is now in the 'Complete' status. Please close if no further action is needed.
