### ISSUE TITLE
Fetal Spine Atlas 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#939]
See email here: https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/azc03FGtBWY 

### Associated files:

* Google Drive:

### Key Events

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [ ] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by idazucchi** [comment]
[dataset questionnaire](https://docs.google.com/spreadsheets/d/1QKMGYieudjwFtHzwUDEDabspRSe5Heqfvd95WTKucQM/edit#gid=1332239357) row 81 --> mice --> it can potentially go to ENA as well

**Comment by Wkt8** [comment]
Enrique to reply and suggest meeting times as they don't understand the questionnaire.

**Comment by Wkt8** [comment]
@gabsie to reply to doodle poll for options on meetings for Thursday and Friday (27th/28th October)

**Comment by gabsie** [comment]
Contributor is to send metadata sheets next, @ESapenaVentura  will remind tomorrow

**Comment by ofanobilbao** [comment]
This ticket now superseded by https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/971. Closing this one
