### ISSUE TITLE
Majlinda Lako: deconstructing retinal organoids

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#94]
**Primary Wrangler:**
@ESapenaVentura 
**Secondary Wrangler:**
TBD

**Associated files:**

Google Drive: TBD

s3 bucket: TBD

**Key Events**

- [x] Assign the Primary Wrangler
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata (most likely in staging)
- [ ] Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission including metadata spreadsheet and data files
- [ ] Submit dataset to Production and hand off tracking to data dashboard

This public dataset belongs to `Majlinda Lako's` team, with whom we want to have a good relationship as we are expecting other data from them related to the MRC Developmental Cell Atlas grant.

**Comment by lauraclarke** [comment]
@ESapenaVentura is this for the current work with Majlinda, 

If it is, can you update the ticket with what is happening now

If not, can you close the issue and create a ticket for the current work

**Comment by ESapenaVentura** [comment]
@lauraclarke No, this is for a geo dataset that I wanted to wrangle but got de-prioritised. I will create the ticket for the dataset Linda is preparing

**Comment by lauraclarke** [comment]
Is the GEO dataset in the data tracker?

**Comment by lauraclarke** [comment]
I have added it to the data tracker

**Comment by ESapenaVentura** [comment]
My apologies, didn't see the comment!

Thanks!
