### ISSUE TITLE
Contributor dataset: Paul - SalivaryGlandSjogrenSyndrome

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#940]
See Email here: https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/xHeVZnbFZ08/m/pkNxOWnCAwAJ 

### Project short name:
SalivaryGlandSjogrenSyndrome
### Associated resources:

* Google Drive: [folder](https://drive.google.com/drive/folders/1NjUPosOoAYOIdj_hudWJYL8Gv8GvZfXc)
* Publication: Single cell profiling of transcriptional states of enriched immune cells in salivary glands from patients with Primary Sjogren’s Syndrome and healthy controls

- cell count ~32000 cells 
- donors 13 

### Key Events

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [ ] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by idazucchi** [comment]
[dataset questionnaire](https://docs.google.com/spreadsheets/d/1QKMGYieudjwFtHzwUDEDabspRSe5Heqfvd95WTKucQM/edit#gid=1332239357) row 82 --> living donors - can we work on this?

**Comment by ESapenaVentura** [comment]
Meeting to discuss w/ Wranglers + @gabsie tomorrow (Fri 21st Oct)

**Comment by Wkt8** [comment]
Enrique to reply and suggest meeting times as they don't understand the questionnaire.

**Comment by idazucchi** [comment]
Potentially using the same approach as Kuppe's dataset

**Comment by idazucchi** [comment]
We've had a meeting on 8-11-22, the highlights are:
- they are ok with going with the Kuppe route
- they have no manuscript yet but have a methods section they can send us
- they would like the dataset to go live only after they have submitted the manuscript, potentially January

Actions:
- [ ] get the t&c signed
- [ ] ask for the metadata
- [ ] send credentials/ instructions on hca-util upload

**Comment by idazucchi** [comment]
waiting for #977 - contributor credentials for hca-util
I will send an email with instructions after that

**Comment by idazucchi** [comment]
Sent an email with instructions for meta/data last week, waiting for a reply

**Comment by ofanobilbao** [comment]
Closing for lack of responsiveness from contributors
