### ISSUE TITLE
TabulaMurisSenis

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#948]
### Project short name:
TabulaMurisSenis

### Primary Wrangler:
Ami

### Associated files

* Google Drive:

### Published study links

* Paper:
https://www.nature.com/articles/s41586-020-2496-1#Sec2

* Accessioned data:
GSE149590

**Ingest**
https://contribute.data.humancellatlas.org/projects/detail?uuid=73c22527-e1d3-4e94-b081-2bd80a0ca230&tab=project

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ofanobilbao** [comment]
@ami-day and @ofanobilbao to discuss priority of this dataset

**Comment by ofanobilbao** [comment]
Closing the ticket as this is not immediate priority. The project is in Ingest and I have done the remaining triage parts so that it has all the required information to assess if to curate later
