### ISSUE TITLE
GSE136719 - Single-cell analysis reveals dynamic changes of neural cells in developing human spinal cord

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#951]
### Project short name:
Zhang2021HumanSpinal

### Primary Wrangler:
Ami

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=9288329e-0a0a-42f3-a7b7-61fa9cfb0600&tab=project

### Associated files

* Google Drive:
https://drive.google.com/drive/folders/1GhRU_iWUwZfZPIZM0Cavw9OM1mP90cKe

Google Sheet: https://docs.google.com/spreadsheets/d/13qdnvVHPu1vCjKtpbsmxuoRsfKwVO9N8etOQkCJFNQI/edit#gid=1889564120

Zhang2021HumanSpinal

### Published study links

* Paper: 
https://doi.org/10.15252/embr.202152728

* Accessioned data: GSE136719

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ofanobilbao** [comment]
Paper needs to be requested to the library services

**Comment by ami-day** [comment]
Emailed the authors to ask about getting the linkings between the sample IDs and the unique donors. This info is not available via the publication or GEO accession.

**Comment by ofanobilbao** [comment]
Closing for lack of response form contributor and no linking available
