### ISSUE TITLE
GSE196830 - Single-cell eQTL mapping identifies cell type-specific genetic control of autoimmune disease

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#954]
### Project short name:
-Human-10x3pv2--4

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=f2078d5f-2e7d-4844-8552-f7c41a231e52

### Associated files

* Google Drive:

### Published study links

* Paper: https://doi.org/10.1126/science.abf3041

* Accessioned data: [GSE196830](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE196830)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ofanobilbao** [comment]
Agreed with wranglers on Friday that if we are focusing on something else, immune atlas datasets should drop from the Queue. Therefore closing the ticket as nothing was done

**Comment by arschat** [comment]
Dataset had been wrangled by UCSC team. Immune integration team asked us for mapping of donor_id to CxG donor_id and asked for flat metadata for this project.

[cxg_dcp_mapping.csv](https://github.com/ebi-ait/hca-ebi-wrangler-central/files/15264917/cxg_dcp_mapping.csv)

[flat_metadata.csv](https://github.com/ebi-ait/hca-ebi-wrangler-central/files/15264918/flat_metadata.csv)

During this investigation, we found some mismatches in the DCP spreadsheet between the mapping of specimen_from_organism and pooled cell_suspensions.
I updated the DCP project with the correct mapping and added the CxG donor_id to the donor description.
[eQTLAutoimmune_pool_fix.xlsx](https://github.com/ebi-ait/hca-ebi-wrangler-central/files/15264929/eQTLAutoimmune_pool_fix.xlsx)

Project is not exported for the next release R39, and import form has been sent.
Pending verification in browser.

**Comment by arschat** [comment]
Update verified in [browser](https://explore.data.humancellatlas.org/projects/f2078d5f-2e7d-4844-8552-f7c41a231e52?catalog=dcp39).
