### ISSUE TITLE
contributor account for: B. L.

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#959]
Please create an account a contributor.

*Contributor details:*
* name: B.L.
* email: libo@broadinstitute.org

Request Details:
* Requested by: email

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by amnonkhen** [comment]
done

**Comment by idazucchi** [comment]
some changes needed to the contributor communication SOP

**Comment by Wkt8** [comment]
@ESapenaVentura to create a separate ticket for modifying the contributor communication SOP
