### ISSUE TITLE
Revert project status in ingest

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#960]
Could a developer please change the status of this project from "Complete" so that I can re-export it? https://contribute.data.humancellatlas.org/submissions/detail?uuid=cddf06c7-5d43-4013-a0b0-271fb611e396&project=504e0cee-1688-40fa-b936-361c4a831f87 

It seems the analysis files are present but they didn't get displayed in the HCA Data Browser. My solution atm is to re-export it and re-submit the import form to see if that resolves the issue, as I think the initial mix-up happened when we were listing the analysis files for projects manually a while back.

**Example file**
[GSM4761144_194_matrix.mtx.gz](https://api.ingest.archive.data.humancellatlas.org/files/614a3e5e97ebaa5cf3529e5f)

**Comment by idazucchi** [comment]
this is the same dataset as #957

**Comment by Wkt8** [comment]
Meeting needed between Ami and a dev to determine what analysis files should be: 
- displayed on the browser and are not there
- displayed on the browser and are there
- not displayed on the browser and are there

@amnonkhen to post a link to documentation related to looking at the terra staging area to investigate what analysis files are present in the staging area.

**Comment by amnonkhen** [comment]
@ami-day Please check whether the files are on terra, so we know whether the problwm is on the export from ingest side or on the data import side. 
For your convenience here are the [terra access docs](https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html)

**Comment by amnonkhen** [comment]
The mentioned file, `GSM4761144_194_matrix.mtx.gz`, is [in terra](https://console.cloud.google.com/storage/browser/_details/broad-dsp-monster-hca-prod-ebi-storage/prod/504e0cee-1688-40fa-b936-361c4a831f87/data/GSM4761144_194_matrix.mtx.gz;tab=live_object).
The next step, therefore, is to see why it was not imported.

**Comment by amnonkhen** [comment]
The [file](https://api.ingest.archive.data.humancellatlas.org/files/614a3e5e97ebaa5cf3529e5f)'s cloud url is `s3://org-hca-data-archive-upload-prod/cddf06c7-5d43-4013-a0b0-271fb611e396/GSM4761144_194_matrix.mtx.gz`
This location does not exist in [the prod bucket on s3](https://s3.console.aws.amazon.com/s3/buckets/org-hca-data-archive-upload-prod?region=us-east-1&tab=objects).
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/d25905b3-e745-403b-8c2c-84e4fb0778e1)

**Comment by amnonkhen** [comment]
The mentioned file is downloadable from the browser in the project's [Download Project Data](https://data.humancellatlas.org/explore/projects/504e0cee-1688-40fa-b936-361c4a831f87/get-curl-command)

**Comment by ami-day** [comment]
> The mentioned file is downloadable from the browser in the project's [Download Project Data](https://data.humancellatlas.org/explore/projects/504e0cee-1688-40fa-b936-361c4a831f87/get-curl-command)

Thanks Amnon, although it is not downloadable from the CGM page, which it should be. so we need to re-export this project.
