### ISSUE TITLE
Revert project status in ingest

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#964]
**Description of the task:**

Could someone please revert chronicWoundDiabetes (34ec845b-cd7a-4c43-99e4-d2932d5d85bb) from complete -> exported so it can be resubmitted? I need to update publication info.

Thanks!

**Comment by ESapenaVentura** [comment]
Done :) Remember to export with "Metadata only" tickbox!

**Comment by rachadele** [comment]
Thanks Enrique!
