### ISSUE TITLE
Project stuck in metadata validating state

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#965]
I have a project submission which is stuck in "metadata validating" state:
https://contribute.data.humancellatlas.org/projects/detail?uuid=48b198ef-3d59-4e57-900f-df54c2435669&tab=upload
Specifically, there are multiple fastq files stuck in validating status. E.g. file with name: SAG657A5_S4_L004_R1_001.fastq.gz and uuid: `7200c422-34fc-436b-bc44-a628f98e4e32`

**Comment by ESapenaVentura** [comment]
I have run the script to re-validate files, currently re-validating

**Comment by ami-day** [comment]
I think it got stuck "metadata validating" again: https://contribute.data.humancellatlas.org/projects/detail?uuid=48b198ef-3d59-4e57-900f-df54c2435669&tab=upload
Specifically, some of the fastq files are stuck in the validating state.

**Comment by ESapenaVentura** [comment]
Files have been re-validated again! 

The only problem now is the draft file

**Comment by ami-day** [comment]
> Files have been re-validated again!
> 
> The only problem now is the draft file

Perfect! thanks @ESapenaVentura I'll delete that draft file. Do you know what the problem was? or did the files re-validate successfully without intervention?

**Comment by ofanobilbao** [comment]
Issue was solved so moving it to Done
