### ISSUE TITLE
Project stuck in "Edit file" mode

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#966]
**Background**

I have synced a new file to a submission in ingest using the hca-util sync command. The file successfully synced and is in "Draft" status as expected (since the file metadata was not in the original submission). However, when I click "Edit" to edit the file (to add the file metadata), the browser gets stuck with the loading symbol. I have repeated this multiple times, and get the same issue. 

Happy to discuss in a video call with a screenshare.

Enrique's comments:
The UI gets stuck because the form the UI displays is based on the schema loaded via the content.describedBy field. The "draft" file does not have any content (As you can see if you inspect the metadata in the API), so it will need a dev. The "draft" file does not have any content because it was created as a new file for which we want to add metadata content in the UI, it was not in the original submission.

Link to submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=522ee883-e3da-412f-a463-0112d2f2f63f&project=f4d011ce-d1f5-48a4-ab61-ae14176e3a6e

Submission uuid: 522ee883-e3da-412f-a463-0112d2f2f63f
Project uuid: f4d011ce-d1f5-48a4-ab61-ae14176e3a6e

**Comment by MightyAx** [comment]
File doesn't have a schema.
Short term we can post the schema to the file.

This will effect all filers that are added to the upload area without existing in the submission so a long term fix would be needed (for example: the UI could ask the user which schema to use)

**Comment by ESapenaVentura** [comment]
Done

Pointed to analysis file schema 6.5 https://schema.humancellatlas.org/type/file/6.5.0/analysis_file

**Comment by ESapenaVentura** [comment]
I would double check, there are other weird errors - Why is it saying something about the analysis protocol?

**Comment by ami-day** [comment]
> I would double check, there are other weird errors - Why is it saying something about the analysis protocol?

Yes, I am now unable to access the submission. The analysis protocol error occurred when I submitted an updated spreadsheet with an analysis protocol  (as opposed to adding a new protocol at the UI). Let's have a huddle on slack

**Comment by ami-day** [comment]
Sorted.
