### ISSUE TITLE
treatment protocol not found for "cutaneousTcellLymphoma"

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#968]
**Description of the issue** 

Snapshot `hca_prod_a1375150dda440818318c1593622da55__20221101_dcp2_20221101_dcp22` is missing the treatment_protocol table.

The project is [cutaneousTcellLymphoma](https://contribute.data.humancellatlas.org/submissions/detail?uuid=c6f49bb6-5750-44e8-94c2-51b0a7a753d2&project=a1375150-dda4-4081-8318-c1593622da55), which was wrangled by @ami-day .

Currently investigating the reasons, the protocol is there and ingest does not classify it as "unlinked", so I will be checking:

- [x] Spreadsheet (Easier to investigate than the API; protocols do not link to their processes)
- [x] Staging area

**Comment by ESapenaVentura** [comment]
The treatment protocol is in ingest, with at least 1 subgraph that goes all the way to the files

**Comment by ESapenaVentura** [comment]
The treatment protocol is in the staging area, adhering to the staging area exchange format

**Comment by ESapenaVentura** [comment]
I suspect this is an issue on the importer's side, and a good reminder of why I suggested that everybody needed to use the test data :)

**Comment by ofanobilbao** [comment]
@ESapenaVentura has already communicated this to the Import team
