### ISSUE TITLE
Part of Atlas publication wrangled by Lattice

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#969]
** There is a publication part of the Kidney Atlas effort that I can't find in ingest, but one of the accessions matches a submission made by Lattice. We need to assess if it is the same project or not**

- Publication: https://www.biorxiv.org/content/10.1101/2021.07.28.454201v1.full
- Link to Lattice's project in Ingest: https://contribute.data.humancellatlas.org/projects/detail?uuid=f4019385-a929-4b82-b643-74cc728d37d1 
- Link to Lattice's project in DCP: https://data.humancellatlas.org/explore/projects/94023a08-611d-4f22-a8c9-90956e091b2e

**Acceptance criteria for the task:**

- [x] Checked if project is the same or not
- [ ] If the same, come up with potential actions for Lattice (if any)
- [ ] If not the same, add project to Ingest as part of the Kidney Atlas

**Comment by ofanobilbao** [comment]
Kidney dataset that it's part of the shortlist for the Atlas provided by Peng. Any volunteers to check if we have it in the DCP already or not? 
https://data.humancellatlas.org/explore/projects/94023a08-611d-4f22-a8c9-90956e091b2e is a Lattice project. It's missing stuff. And it might be that it only contains part of the data. TBD. 1st accession matches another publication pushed to DCP by Lattice.

All accessions: GSE169285, GSE171406, GSE104954

@idazucchi @ESapenaVentura @Wkt8 who wants to volunteer to look into this after the Release cut off?

**Comment by ESapenaVentura** [comment]
It seems that the dataset we have registered (Kidney atlas) is a compilation of data from several sources. In the data availability section:

> Raw sequencing and imaging data (snCv3, scCv3, 3D imaging) generated as part of the Kidney Precision Medicine Project (KPMP) has been deposited at atlas.kpmp.org. Raw sequencing data (snCv3, SNARE2, Slide-seq) generated as part of the Human Biomolecular Atlas Project (HuBMAP) has been deposited at portal.hubmapconsortium.org/. Raw sequencing data (scCv3) on living donor biopsies as part of the Chan Zuckerberg Initiative (CZI) and Human Cell Atlas (HCA) will be available in the Gene Expression Omnibus (GEO) as GSE169285. Visium spatial transcriptomic data is available in GEO as GSE171406. Neptune sequencing and clinical data is available upon request to NEPTUNE-STUDY@umich.edu. ERCB data was obtained from GEO as GSE104954. KPMP snCv3 and scCv3 cell types and expression profiles can be interrogated using the KPMP Data Atlas Explorer: https://atlas.kpmp.org/explorer. snCv3 healthy reference data is available for reference-based single cell mapping by the Azimuth tool: azimuth.hubmapconsortium.org/.

I think they just used the data for 2 different projects,

- The Kidney atlas described in the preprint
- A more specific paper with specific findings related to this set of data https://www.sciencedirect.com/science/article/abs/pii/S0085253821011625 (Lattice project)

The contributors for the specific paper is a subset of the contributors for the atlas preprint, further indicating that it just may be a "sub-research" kind of paper

When we wrangle this, we should probably reference to this data (The first accession) rather than duplicating it. Not sure exactly how it would be the best way to point it though

**Comment by amnonkhen** [comment]
@ESapenaVentura to discuss with the wranglers before going on AL.

**Comment by amnonkhen** [comment]
@ESapenaVentura to discuss with the wranglers before going on AL.

**Comment by amnonkhen** [comment]
@ESapenaVentura to discuss with the wranglers before going on AL.

**Comment by Wkt8** [comment]
Had a meeting with Enrique. Actions are. 

Short-Term actions:
- Wrangle all other kidney bionetwork datasets apart from this one
- Create the kidney bionetwork project (which uses primary data from the lattice proejct) in the DCP, setting it to not eligible, and adding information in the note (link to this ticket) 

Long-term actions:
- create a ticket discussing the required design of this use case (we should do this with DCP Demos) 
- The use case being: A dataset has been wrangled to the DCP, another dataset uses some of that data which is already in the DCP. How do we avoid re-wrangling primary data and duplicating data in the DCP?

**Comment by gabsie** [comment]
To be put in ingest with low priority and transfer the comments.

**Comment by Wkt8** [comment]
Ticket created: https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/gh/ebi-ait/dcp-ingest-central/913

**Comment by idazucchi** [comment]
It looks

**Comment by idazucchi** [comment]
the Lattice dataset [(HealthyhumankidneycelltypesinglecellRNA-seqdata)](https://data.humancellatlas.org/explore/projects/94023a08-611d-4f22-a8c9-90956e091b2e) only has data from the healthy donors of [GSE169285](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE169285)

GEO only has cell count data, but on the DCP we have no matrices and have fastqs instead. 
Discuss next steps

**Comment by idazucchi** [comment]
I've emailed Peng to check what part of the accession is needed for the atlas, depending on his reply we can decide on next steps

**Comment by idazucchi** [comment]
Peng is interested in the cell count files for both the healthy and disease donors. I emailed Jason to see if they have capacity to update the project, but the lattice team is no equipped to submit analysis files to the DCP.

The lattice team however worked with the authors to depoosit the data in cellxgene --> https://cellxgene.cziscience.com/collections/bcb61471-2a44-4d00-a0af-ff085512674c
I'll update Peng about this

**Comment by idazucchi** [comment]
I've communicated with Peng, there is no further action we can take for this specific dataset so I'm closing the ticket
