### ISSUE TITLE
contributor account for: Aleksandra Ivovic

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#977]
Please create an account a contributor.

*Contributor details:*
* name: Aleksandra Ivovic
* email: ai5@sanger.ac.uk

Request Details:
* Requested by: @idazucchi 
* request email details: see [email thread](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/xHeVZnbFZ08/m/p-nh4idyBgAJ)
The person doing the upload is not the contributor but the bioinformatician 

[SOP link](https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_wrangling_SOP.html#aws-user-for-contributors)

**Comment by Wkt8** [comment]
This is done.
