### ISSUE TITLE
E-MTAB-12524 - dandelionPBMC

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#979]
### Project short name:
dandelionPBMC
### Primary Wrangler:
Ida

### Associated files:

* Google Drive: [folder](https://drive.google.com/drive/folders/1faj45P1HGl-4RGugMYmHo8VVkeMzC2hX?usp=sharing)
* [Single cell antigen receptor analysis reveals lymphocyte developmental origins](https://doi.org/10.1038/s41587-023-01734-7)
* [E-MTAB-12524](http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-12524/)
[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=a83b7f45-bfb1-4c6a-97e9-8e3370065cc1)
### Key Events

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire
- [ ] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by ESapenaVentura** [comment]
In contact with Chenqu/Krzysztof.

Has a preprint so we should pre-fill spreadsheet before sending

**Comment by ESapenaVentura** [comment]
This data will be archived in AE, so there is no paper-related urgent deadlines

**Comment by ofanobilbao** [comment]
@ESapenaVentura is this stalled or down prioritised?

**Comment by ofanobilbao** [comment]
@ESapenaVentura is this stalled or down prioritised?

**Comment by idazucchi** [comment]
The data was archived by the authors, it's now public and can be wrangled like any other publication

**Comment by idazucchi** [comment]
#### Libraries
I've used just 2 cell suspensions and I've recorded the library ids in the sequence file tab. Since the library prep technique is multiomic it produces 3 libraries from the same cells and it would be misleading to represent each of those 3 libraries as different cell suspensions

The dataset is ready for secondary review

**Comment by arschat** [comment]
Excellent minimal dataset, Ida!

The only comment I would make is to update the project title to match the peer-reviewed publication's title `Dandelion uses the single-cell adaptive immune receptor repertoire to explore lymphocyte developmental origins` and the project description to match the abstract.
No other comments on my sec review! Well done!

**Comment by idazucchi** [comment]
thanks for catching the mismatch between the project and paper title!
I fixed it and I'm exporting it now

**Comment by idazucchi** [comment]
exported and filled in import form

**Comment by idazucchi** [comment]
reviewed in browser
