### ISSUE TITLE
Contact contributors to register with project registration

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#98]
We want to get some real projects in the system, we need to determine who to ask and then email them. 
 - [x] chat to @lauraclarke , @mshadbolt and @ESapenaVentura about who is friendly and might be best as early testers. 
 - [x] List 6 contributors 
 - [x] Draft email to send
https://docs.google.com/document/d/13dXETBh7VUOWPxwwxesJNI_KlMZSMyJrtWa14jeSgJM/edit
 - [x] feedback/sense check before sending - for timing, can you let @clairerye know when we are ready to go please.
 
@ESapenaVentura send emails to
- [x] Majlina Lako
- [x] Christopher Buckley

@lauraclarke send emails to 
- [x] contact in HCA:Organoid
- [x] contact in ESPACE

@mshadbolt send email to
- [ ] Paul Gibson

**Comment by ESapenaVentura** [comment]
I suppose we'll discuss this at some point in a call but I can list you at least 3 that come off the top of my head right now:

- Majlinda lako (Although now her team is pretty busy submitting 3 manuscripts) 
- Muzz Haniffa (Although she's super busy usually, we've had good interactions with her team in the past)
- Christopher buckley: We haven't talked with him for a while but the interactions we've had with him and his team have been really positive

**Comment by ami-day** [comment]
@clairerye does this mean identifying contributors who will have a new project ready to register? or should we ask contributors who have already registered a project to test our system with an already registered project, as a test project?

**Comment by clairerye** [comment]
I think we want super friendly contributors who are willing to help us improve our system/identify any aspects we have overlooked but to register with projects that they will eventually want to submit to the DCP - they don't need to be ready now, or even soon but we want them to be real projects they are working on if at all possible.

**Comment by lauraclarke** [comment]
I can identify 2 or 3 of the folks from the H2020 awards who are engaged and likely to be willing to help

**Comment by ami-day** [comment]
That would be good @lauraclarke thanks. @mshadbolt and @ESapenaVentura do you have any particularly friendly contributors in mind? 
I have only worked with Elisa Laurenti, but I would include her in the list.
I guess we should exclude any contributor who does not work with us as a first choice and instead uses SRA or other.

**Comment by ami-day** [comment]
I have found Peter Linnarrsosn to be quite friendly, although it seems he works on Mouse.

**Comment by lauraclarke** [comment]
I think excluding uses who don't come to us first is a mistake, there are friendly collaborators who still go to SRA or ArrayExpress before us and getting their feedback on this system is almost more important

**Comment by lauraclarke** [comment]
@ami-day do you mean Sten Linnarsson and Peter Lönnerberg
They do work in human but as they specialise in the brain many of the experiments they do have to start in mouse

**Comment by ami-day** [comment]
> @ami-day do you mean Sten Linnarsson and Peter Lönnerberg
> They do work in human but as they specialise in the brain many of the experiments they do have to start in mouse

Yes, I meant Sten Linnarsson. I'm not sure whether Peter Lönnerberg was involved in more than uploading the raw data files.

So the list is:

- Majlinda lako (Although now her team is pretty busy submitting 3 manuscripts)

- Muzz Haniffa (Although she's super busy usually, we've had good interactions with her team in the past)

- Christopher buckley: We haven't talked with him for a while but the interactions we've had with him and his team have been really positive

- 3 from Laura OR 2 from Laura

- optional: Sten Linnarsson

Please can someone confirm the options in this list and I'll start drafting the email

**Comment by lauraclarke** [comment]
@ami-day  Peter Lonnerberg is Sten's bioinformatician

On the emails, who is planning to send them? I am very happy to send them to folks from H2020, I would need to do digging to find good candidates but I suspect they would be better coming from me as they know who I am whereas anyone from the wrangling team might be more likely to be missed as they aren't from someone who they recognise

**Comment by ami-day** [comment]
> @ami-day Peter Lonnerberg is Sten's bioinformatician
> 
> On the emails, who is planning to send them? I am very happy to send them to folks from H2020, I would need to do digging to find good candidates but I suspect they would be better coming from me as they know who I am whereas anyone from the wrangling team might be more likely to be missed as they aren't from someone who they recognise

Yea that sounds good. I thought I'd get started as Claire asked me to coordinate this ticket, but I think you would have a better idea of what to draft in the email, especially as I have only worked with 1 contributor directly. Happy to help out where I can though.

**Comment by lauraclarke** [comment]
You writing a draft is a great plan. I was more thinking about who sends the email rather than what the email contained

**Comment by ami-day** [comment]
Ok then, I'll draft it and post it here

**Comment by ami-day** [comment]
@lauraclarke @clairerye here is a draft email for review: https://docs.google.com/document/d/13dXETBh7VUOWPxwwxesJNI_KlMZSMyJrtWa14jeSgJM/edit

**Comment by lauraclarke** [comment]
I and @mshadbolt discussed that Paul Gibson might be a better first test than Muzz Hannifa from a WSSS perspective

**Comment by lauraclarke** [comment]
Final text is here https://docs.google.com/document/d/13dXETBh7VUOWPxwwxesJNI_KlMZSMyJrtWa14jeSgJM/edit

**Comment by ami-day** [comment]
@lauraclarke I think this ticket can be closed now?

**Comment by lauraclarke** [comment]
If you identify tickets that you think can be closed, please feel free to close them. Everyone who was associated with that ticket should get an email about it so if they think it is still needed they can reopen it
