### ISSUE TITLE
Error importing Spreadsheet

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#986]
Error importing integration test spreadsheet
https://contribute.data.humancellatlas.org/submissions/detail?uuid=0d390034-5889-4ea9-b514-72d7dcbaf450

![Screenshot 2022-12-02 at 09.28.32.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/f755a384-b966-4e8a-a0c6-31878a3dc071)

**Comment by idazucchi** [comment]
needs investigation, might be related to the cache

**Comment by ESapenaVentura** [comment]
Hopefully fixed with new changes (already in dev)

**Comment by Mil-m** [comment]
It's Ok that I have this error after the attempt to log in for this link?

Authentication Error

An error occured during authentication. Please retry logging in. If the error is persistent, please email hca-ingest-dev@ebi.ac.uk

**Comment by Mil-m** [comment]
The same problem for staging...

**Comment by MightyAx** [comment]
this was because of an underlying problem with the previously released broker that I fixed with broker PR [#49](https://github.com/ebi-ait/dcp-ingest-central/issues/49)
As discussed in my comments on ebi-ait/dcp-ingest-central#858, The no such table: responses issues seems to hide other errors so may reappear.
