### ISSUE TITLE
kick Single-cell Transcriptome Atlas of Testis Aging from complete -> exported

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#987]
project: Single-cell Transcriptome Atlas of Testis Aging
uuid: `e88714c2-2e78-49da-8146-5a60b50628b4`

need to update project level cell count

**Comment by ESapenaVentura** [comment]
Hi @rachadele - This submission got a load of other errors while exporting, while we investigate what is happening I am not able to kick it back to exported/Metadata valid

Apologies about this!

**Comment by rachadele** [comment]
it looks like it's complete now! would you be able to kick it back?

**Comment by rachadele** [comment]
thanks enrique :- )
