### ISSUE TITLE
Import issues for 3 datasets

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#988]
**Description of the issue**

For release 23, there have been a couple of issues regarding datasets:

### 1. schema_major_version and schema_minor_version  in documents (schema version problem)
- [Single-cell RNA-seq analysis throughout a 125-day differentiation protocol that converted H1 human embryonic stem cells to a variety of ventrally-derived cell types.](https://contribute.data.humancellatlas.org/projects/detail?uuid=2043c65a-1cf8-4828-a656-9e247d4e64f1&tab=project)
- [A single cell immune cell atlas of human hematopoietic system](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc95ff89-2e68-4a08-a234-480eca21ce79)

### 2. crc32 assertion error with generated spreadsheet file (GSE117211_KidneyMicroOrganoids_metadata_02-09-2022.xlsx)

> Project [GSE117211_KidneyMicroOrganoids](https://contribute.data.humancellatlas.org/projects/detail?uuid=e0c74c7a-20a4-4505-9cf1-38dcdd23011b) has an assertion error where the recorded crc32c doesn’t match the calculated one for file prod/e0c74c7a-20a4-4505-9cf1-38dcdd23011b/data/GSE117211_KidneyMicroOrganoids_metadata_02-09-2022.xlsx. I believe we’ve run into this one in the past as well.

### 3. Duplicated file descriptors for spreadsheet

>Okay, I think I see what’s going on with the last project that is having issues [gliaDiversityAtlasAcrossAdLifespan](https://contribute.data.humancellatlas.org/projects/detail?uuid=258c5e15-d125-4f2d-8b4c-e3122548ec9b). There is an xlsx file (gliaDiversityAtlasAcrossAdLifespan_metadata_02-12-2022.xlsx) in the data tab that has six different version of the descriptor file with 6 different crc32c values. The importer is trying to load all versions of those descriptor files as records (which would then be reconciled downstream) but is running into mismatches between the crc32c value on the imported data file and the crc32c recorded on the supplementary_file descriptor files

**Comment by MightyAx** [comment]
Project [GSE117211_KidneyMicroOrganoids](https://contribute.data.humancellatlas.org/projects/detail?uuid=e0c74c7a-20a4-4505-9cf1-38dcdd23011b):
    - We sent this file 52 times (because of the now resolved issue #886)
    - The latest version of the file `2022-11-29T12:07:29.566000Z` is consistent though, downloading the data file and running a crc check reveals the correct crc:
        - [metadata](https://console.cloud.google.com/storage/browser/_details/broad-dsp-monster-hca-prod-ebi-storage/prod/e0c74c7a-20a4-4505-9cf1-38dcdd23011b/metadata/supplementary_file/e0889100-ad52-5ac4-b928-a47b3e82952f_2022-11-29T12%3A07%3A29.566000Z.json)
        - [descriptors](https://console.cloud.google.com/storage/browser/_details/broad-dsp-monster-hca-prod-ebi-storage/prod/e0c74c7a-20a4-4505-9cf1-38dcdd23011b/descriptors/supplementary_file/e0889100-ad52-5ac4-b928-a47b3e82952f_2022-11-29T12%3A07%3A29.566000Z.json)
        - [links](https://storage.cloud.google.com/broad-dsp-monster-hca-prod-ebi-storage/prod/e0c74c7a-20a4-4505-9cf1-38dcdd23011b/links/e0889100-ad52-5ac4-b928-a47b3e82952f_2022-11-29T12%3A07%3A29.566000Z_e0c74c7a-20a4-4505-9cf1-38dcdd23011b.json)
        - [data](https://console.cloud.google.com/storage/browser/_details/broad-dsp-monster-hca-prod-ebi-storage/prod/e0c74c7a-20a4-4505-9cf1-38dcdd23011b/data/GSE117211_KidneyMicroOrganoids_metadata_29-11-2022.xlsx)
    - I think this should work in terra but we can delete the duplicates as a courtesy.

**Comment by MightyAx** [comment]
deletion:

```bash

gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/descriptors/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T16:29:04.424000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/descriptors/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:10:44.501000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/descriptors/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:10:55.242000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/descriptors/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:11:09.153000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/descriptors/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:11:20.653000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/metadata/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T16:29:04.424000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/metadata/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:10:44.501000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/metadata/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:10:55.242000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/metadata/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:11:09.153000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/metadata/supplementary_file/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:11:20.653000Z.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/links/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T16:29:04.424000Z_258c5e15-d125-4f2d-8b4c-e3122548ec9b.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/links/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:10:44.501000Z_258c5e15-d125-4f2d-8b4c-e3122548ec9b.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/links/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:10:55.242000Z_258c5e15-d125-4f2d-8b4c-e3122548ec9b.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/links/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:11:09.153000Z_258c5e15-d125-4f2d-8b4c-e3122548ec9b.json"
gsutil -m rm "gs://broad-dsp-monster-hca-prod-ebi-storage/prod/258c5e15-d125-4f2d-8b4c-e3122548ec9b/links/d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4_2022-12-02T17:11:20.653000Z_258c5e15-d125-4f2d-8b4c-e3122548ec9b.json"
```

**Comment by MightyAx** [comment]
### Regarding Issue 2 and 3:
As far as I can tell both were actually just symptoms of the now resolved #886 issue about duplicate exports.
 
- When I downloaded the latest spreadsheet for both projects and ran a CRC check, it matched the CRC of the latest file descriptors in terra. :tada: 
- When I created a “new” spreadsheet from scratch, the new file had the same CRC, meaning the new file was identical. :tada: 
- There was a version of the descriptor for each export each with a different CRC (as well as metadata and link files), we no longer have the old spreadsheet files to match against. I have to assume that each of the spreadsheets matched the stated CRC. :man-shrugging: 

So I think the only problem is that when multiple versions of a file exist in the terra staging bucket, terra is processing the OLDEST versions first. When errors are discovered, I assume the import is stopping, even when a later version exists that may not include the error.

Thankfully I don’t think we will encounter this issue in “normal” usage and has only been brought to light by an issue in the ingest system, which we have already fixed.

**Comment by ESapenaVentura** [comment]
Update on Issue 1:
There are several entities in those 2 submissions that have outdated schemas, resulting in loading provenance 1.0.3. Our exporter tries to generate values for `schema_major_version` and `schema_minor_version`, which do not exist in that schema, ending up with schema errors.

Steps:
- [ ] Identify which entities have outdated schemas
- [ ] Update them to the latest (Or first schema that used provenance 1.1.0)
- [ ] Re-export only metadata
- [ ] Notify Nathan

**Comment by ESapenaVentura** [comment]
Project `2043c65a-1cf8-4828-a656-9e247d4e64f1`:
- Ran `gsutil -m cp -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2043c65a-1cf8-4828-a656-9e247d4e64f1/metadata/ .` to investigate the metadata
- Ran `find . | xargs -I{} sh -c "cat {} | grep -q 'schema_minor_version\": null' && echo {}" | wc -l`
Found 5218 entities. From these entities:
- All the metadata types are affected (`find . | grep json | xargs -I{} sh -c "cat {} | grep -q 'schema_minor_version\": null' && echo {}" | awk -F "/" '!_[$2]++')
- After discovering this, I did a quick comparison, and discovered that everything except the project metadata has old entities

I don't know if I will be able to correct this dataset, so I am going to focus on the other one ([A single cell immune cell atlas of human hematopoietic system](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc95ff89-2e68-4a08-a234-480eca21ce79)), which at the moment is a higher priority

**Comment by ESapenaVentura** [comment]
Project A single cell immune cell atlas of human hematopoietic system:

- Only processes are affected (Ran similar command as above, just changing the cp command to match the project uuid)

### List of affected processes
<details><summary> List of affected processes</summary>

```
b6921264-a115-4874-8f58-7e9a1a8ee032_2022-11-23T14:36:57.633000Z.json
caf67529-13b5-47e0-ab87-46597019f59c_2022-11-23T14:36:57.633000Z.json
daa9f932-0b1d-49b2-8927-334e26bb42ac_2022-11-23T14:36:57.633000Z.json
bed3c3b1-01fd-426c-8a65-1f07580cc566_2022-11-23T14:36:57.633000Z.json
4a8360b1-8c20-4022-bebc-fa50a92e7b1d_2022-11-23T14:36:57.633000Z.json
7f3a803e-8254-42fd-b7cc-b18f0011eaeb_2022-11-23T14:36:57.633000Z.json
94d9bb81-8c29-4678-861a-df72f5d5c2b9_2022-11-23T14:36:57.633000Z.json
94579770-0d24-41b9-b6b1-d7f565aba9fe_2022-11-23T14:36:57.633000Z.json
4f749210-1da4-4371-84c0-d199854e8dd2_2022-11-23T14:36:57.633000Z.json
76f00716-3c4f-4152-bcce-8b8a8ff541a9_2022-11-23T14:36:57.633000Z.json
6a801a9c-4c07-43df-a55b-63073f86e8ce_2022-11-23T14:36:57.633000Z.json
712c8ca2-0051-4d9a-bf0a-7a96dfbfaaf6_2022-11-23T14:36:57.633000Z.json
5fecee5b-9e85-48a0-bb0b-5ef7ba7e6c9e_2022-11-23T14:36:57.633000Z.json
041636ee-87fe-4665-aa62-9a7c1cf63347_2022-11-23T14:36:57.633000Z.json
b8b03f03-37ca-495a-ac4f-b51fdd5ec23b_2022-11-23T14:36:57.633000Z.json
efbbd4f1-dda9-4fbc-a98b-1bc75cee0883_2022-11-23T14:36:57.633000Z.json
33da5264-b13e-4bb9-90a4-e0447779112f_2022-11-23T14:36:57.633000Z.json
f6aa62da-ebde-4996-8795-a0beff5cd280_2022-11-23T14:36:57.633000Z.json
f330ee5b-63a3-45d4-80ea-e1a84d39d909_2022-11-23T14:36:57.633000Z.json
7c57194b-88dc-4b6e-86c1-7a33989b2446_2022-11-23T14:36:57.633000Z.json
4503151b-7dcf-432c-92b1-a1c7bdcd502c_2022-11-23T14:36:57.633000Z.json
c4d7d0ee-6eea-4066-b61b-1080ace3c61b_2022-11-23T14:36:57.633000Z.json
200996e5-16a0-49d5-913c-ecf25a122438_2022-11-23T14:36:57.633000Z.json
18d80ddd-4d6b-4a43-a863-c0f889b7cc80_2022-11-23T14:36:57.633000Z.json
5ab1ee14-88ee-4159-9b01-ef33273b9456_2022-11-23T14:36:57.633000Z.json
d1daf83b-d573-4e06-a147-5e3c57b9b011_2022-11-23T14:36:57.633000Z.json
f0c19344-fb8c-4d45-ae3f-5ccb581ee71d_2022-11-23T14:36:57.633000Z.json
4dcb8535-211a-4d93-9e82-3bed8975f952_2022-11-23T14:36:57.633000Z.json
6e2f7a1a-e113-4470-9193-73b17fef6507_2022-11-23T14:36:57.633000Z.json
e81f7eed-32ac-459c-b075-46ebf0066433_2022-11-23T14:36:57.633000Z.json
f2a86808-9e74-442e-bd62-866903b8d86e_2022-11-23T14:36:57.633000Z.json
09e1dcb4-6db6-4ded-9993-c991c3e615f7_2022-11-23T14:36:57.633000Z.json
89fb73aa-3a68-4e06-ba2a-7d17b066ba7d_2022-11-23T14:36:57.633000Z.json
ea5ffc6f-c50f-44ad-8f8d-c8d5548d46cc_2022-11-23T14:36:57.633000Z.json
934a42dd-d909-4c31-b056-0e36bd004f36_2022-11-23T14:36:57.633000Z.json
11820a89-991e-45e0-9a76-512e34fde4dc_2022-11-23T14:36:57.633000Z.json
38160445-af72-4faf-be93-212ec9ced62e_2022-11-23T14:36:57.633000Z.json
ec752b0f-b708-4cc7-8557-f36236f93384_2022-11-23T14:36:57.633000Z.json
5b23d609-58eb-41fa-a5ed-703008a46aee_2022-11-23T14:36:57.633000Z.json
6a4e0c27-291f-4caf-ac3f-12a085fae7e2_2022-11-23T14:36:57.633000Z.json
08b7f415-c188-4b64-8fbc-e193a142ac2f_2022-11-23T14:36:57.633000Z.json
5cd0c850-ee65-4137-94c7-b73056edda20_2022-11-23T14:36:57.633000Z.json
b5e3f240-308e-41bd-a65e-c0f8cb0c5177_2022-11-23T14:36:57.633000Z.json
f72fa9a0-b9ab-49e8-9378-9d9a97dd4018_2022-11-23T14:36:57.633000Z.json
53ec4980-692a-4a99-91ca-dd25fc56ab11_2022-11-23T14:36:57.633000Z.json
96a2c9a2-ecdd-453a-8fb9-28b3f8f30e1c_2022-11-23T14:36:57.633000Z.json
1577156c-87dd-4293-9830-9addf07414ae_2022-11-23T14:36:57.633000Z.json
5815d3d6-738a-41b9-9887-4ec2fe983736_2022-11-23T14:36:57.633000Z.json
7ce990fb-219d-4ed3-984d-ca8be96d6242_2022-11-23T14:36:57.633000Z.json
5430f6da-db54-4310-b94d-2f65802a28d5_2022-11-23T14:36:57.633000Z.json
aa86d5f0-2d25-4e26-9bef-fd5d52a2f50a_2022-11-23T14:36:57.633000Z.json
9d7be81a-e5de-47a8-af79-59a4ca514f61_2022-11-23T14:36:57.633000Z.json
57f38507-e7ed-47de-b8a3-1988c6547144_2022-11-23T14:36:57.633000Z.json
a0683db5-e203-48f4-b36a-ee8ac27c5620_2022-11-23T14:36:57.633000Z.json
1fe593af-3bd7-45dc-bc53-89bbcfa14d0a_2022-11-23T14:36:57.633000Z.json
5da25649-8d6b-4740-9165-2374c0744876_2022-11-23T14:36:57.633000Z.json
f9204513-2736-4457-b2d6-b81f6baf9e87_2022-11-23T14:36:57.633000Z.json
277144ba-638f-4d99-838c-e208458f41f7_2022-11-23T14:36:57.633000Z.json
2c352d95-96d0-4c71-bbe7-5520b8308803_2022-11-23T14:36:57.633000Z.json
ce4c0953-c697-47c5-9471-ed11d1f907ba_2022-11-23T14:36:57.633000Z.json
5acf8ed3-be2d-47bf-90c1-dca6bc89c92f_2022-11-23T14:36:57.633000Z.json
e4408f8a-40d5-4ae6-b24f-002c2b2d3eb2_2022-11-23T14:36:57.633000Z.json
862221fe-8c4a-4333-a82f-27ad2da26e03_2022-11-23T14:36:57.633000Z.json
e05bf632-9d70-400c-890b-3194f2f92623_2022-11-23T14:36:57.633000Z.json
6609c4c8-a166-45fc-83b8-f552000ea180_2022-11-23T14:36:57.633000Z.json
f26c691f-8259-48d7-a918-a60a87fc840f_2022-11-23T14:36:57.633000Z.json
da5d3e97-55a8-470f-9d8c-a4d2ab8e3022_2022-11-23T14:36:57.633000Z.json
1d1ab78a-8dd7-47ce-be8f-f4290b713a4d_2022-11-23T14:36:57.633000Z.json
051d2f41-0f7f-448e-bb53-df3d6ca4647d_2022-11-23T14:36:57.633000Z.json
de6f7151-44ad-4ab7-b969-eb0f795a3e2c_2022-11-23T14:36:57.633000Z.json
a160bdee-cc7c-4e1b-a2be-5227d0c4ddba_2022-11-23T14:36:57.633000Z.json
8dd950d7-1e2e-4f40-969e-469631d734ea_2022-11-23T14:36:57.633000Z.json
c65ca2ec-02b1-491b-a797-e7d072fc4c93_2022-11-23T14:36:57.633000Z.json
e4b00508-c601-4368-bee4-a67489df1240_2022-11-23T14:36:57.633000Z.json
f8578823-e58d-4c78-a4b4-1625adc3a7eb_2022-11-23T14:36:57.633000Z.json
b90a0941-6aea-48fc-8cf2-36d6b5cf51ed_2022-11-23T14:36:57.633000Z.json
1c6e8f00-1196-4935-8e8a-0524a65bb231_2022-11-23T14:36:57.633000Z.json
cc255af8-cbe4-4e93-a09c-8551eebc7e01_2022-11-23T14:36:57.633000Z.json
c925e726-8819-4bbb-90f0-a0b435d74867_2022-11-23T14:36:57.633000Z.json
6ff14ad3-efe0-4c03-982c-849cc9e42207_2022-11-23T14:36:57.633000Z.json
3d91d618-6c74-4c24-a2f9-88cd882fa8bc_2022-11-23T14:36:57.633000Z.json
615099a9-8769-48a2-be7a-2ea2fa7e659f_2022-11-23T14:36:57.633000Z.json
9bcf26d6-5518-4fd0-940d-d0578c1ea261_2022-11-23T14:36:57.633000Z.json
afe14ae8-096d-458a-81a5-7a3ac43ba5d9_2022-11-23T14:36:57.633000Z.json
4f517288-3574-4586-836e-db6eaab13674_2022-11-23T14:36:57.633000Z.json
22b1cebb-5eab-48cb-a017-e60284bd3ff5_2022-11-23T14:36:57.633000Z.json
ce9a6ed9-ca53-422b-a208-91d447dbf4a5_2022-11-23T14:36:57.633000Z.json
9adb3dee-717f-45dc-892a-578617ebc55b_2022-11-23T14:36:57.633000Z.json
e9ffb21d-38cc-4c40-bbb1-8ab944b9836a_2022-11-23T14:36:57.633000Z.json
b0a97386-49d6-4c17-9a96-4dd0a4676cbd_2022-11-23T14:36:57.633000Z.json
3e899b6f-959e-4b3c-9baa-6b247b06c350_2022-11-23T14:36:57.633000Z.json
e7ede29d-d867-44b7-badd-16ff716210ea_2022-11-23T14:36:57.633000Z.json
f86d81b6-542c-42d2-b2f8-e8521a256818_2022-11-23T14:36:57.633000Z.json
71369214-57de-4e8e-b8a2-2a3719684bb1_2022-11-23T14:36:57.633000Z.json
d02b7fb3-4760-47f3-ae90-4b1af4723752_2022-11-23T14:36:57.633000Z.json
b9027d1a-a4d4-4719-ae3d-288e09f849c8_2022-11-23T14:36:57.633000Z.json
989148b3-7e6d-4d93-914b-c9f185ceff95_2022-11-23T14:36:57.633000Z.json
e50920a4-0900-4520-92d3-959ec30fd992_2022-11-23T14:36:57.633000Z.json
1d81d490-6526-4f54-b25a-9f32ed668798_2022-11-23T14:36:57.633000Z.json
b6f5cb87-5744-4bf5-8d53-ffe6920bab2c_2022-11-23T14:36:57.633000Z.json
2e42de1b-4f53-44a9-a87e-d657201c0aa9_2022-11-23T14:36:57.633000Z.json
8c980607-de68-45ac-ba49-3435ba0a2a2a_2022-11-23T14:36:57.633000Z.json
dc9f5acf-b7eb-4577-a1c6-50154c5e4c9f_2022-11-23T14:36:57.633000Z.json
062ea5b8-ad82-469b-aab5-7073545f888c_2022-11-23T14:36:57.633000Z.json
9ad2cada-4c3c-4cc4-9b7c-d4d2b0b04613_2022-11-23T14:36:57.633000Z.json
b0d7d9ae-592b-4f61-bad9-0210c4ec0183_2022-11-23T14:36:57.633000Z.json
33d2b45e-5d35-4e92-8bfc-3fec37d7358e_2022-11-23T14:36:57.633000Z.json
487018ec-3f8c-4c30-b02b-abdcb051c5eb_2022-11-23T14:36:57.633000Z.json
7d866229-6766-4bf1-baef-20899d1dee52_2022-11-23T14:36:57.633000Z.json
d42018ce-e28c-4e5b-858d-60fc3ccb4fc7_2022-11-23T14:36:57.633000Z.json
7d4b2368-33e0-47a7-9735-ce58b184af56_2022-11-23T14:36:57.633000Z.json
82d461ac-9605-4f65-88a6-9897e4e16b4d_2022-11-23T14:36:57.633000Z.json
95042ff3-e27d-4311-87f4-93d82a3d83d8_2022-11-23T14:36:57.633000Z.json
e1afc0b4-9664-44c5-b5c2-5e76ebbb5e01_2022-11-23T14:36:57.633000Z.json
1f3bc911-180e-4d92-8b05-6a0bb77ce3ee_2022-11-23T14:36:57.633000Z.json
2965c3c4-f874-4c86-9ff0-ae9e5e3ca29d_2022-11-23T14:36:57.633000Z.json
e4da8e48-3790-403b-bdbf-7def687fc230_2022-11-23T14:36:57.633000Z.json
2169c7f2-0add-40c5-949b-a5b37c19f802_2022-11-23T14:36:57.633000Z.json
ebd59fe4-4009-452d-a8e2-91c5437677c5_2022-11-23T14:36:57.633000Z.json
f396a9fd-5907-4ae9-a0fa-7a6ee2d4550d_2022-11-23T14:36:57.633000Z.json
6109861a-d672-47f7-9a65-c2f424ab27d5_2022-11-23T14:36:57.633000Z.json
2f8707d5-4f27-4d02-affa-724d55753b47_2022-11-23T14:36:57.633000Z.json
5c29767c-8d6e-481c-95ab-dff08d72fd10_2022-11-23T14:36:57.633000Z.json
19b6a831-6525-4aaa-be52-368c7e744c46_2022-11-23T14:36:57.633000Z.json
0888d86d-9c92-49e1-9663-65523128f443_2022-11-23T14:36:57.633000Z.json
359276eb-dfe7-4444-b5c2-7f5eeb5ba43d_2022-11-23T14:36:57.633000Z.json
5d25e058-6812-4002-b835-ec7debc55425_2022-11-23T14:36:57.633000Z.json
```
</details>

So, the course of actions is:
- [ ] Find out which version they are on
- [ ] Find out which version will be acceptable
- [ ] Find out if it's an easy update
- [ ] If it is, update and re-export (Only metadata) deleting the entities that have been updated from the staging area

**Comment by ESapenaVentura** [comment]
The fixes to the last dataset will be documented in a separate ticket, https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/992

Moving this ticket to done
