### ISSUE TITLE
fix export of "125 days differentiation of embryonic stem cells" dataset - GSE93593

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#992]
**Description of the issue**

The dataset [Single-cell RNA-seq analysis throughout a 125-day differentiation protocol that converted H1 human embryonic stem cells to a variety of ventrally-derived cell types.](https://contribute.data.humancellatlas.org/projects/detail?uuid=2043c65a-1cf8-4828-a656-9e247d4e64f1&tab=project) was exported for Release 23 but had a couple of issues related to the import.

The issues were all related to schemas used in the entities being outdated. After a quick scan of the staging area, everything but the project entity had an outdated schema, that is incompatible with the exporter.

**Acceptance criteria**

- [x] All schema upgrades have been identified (e.g. cell_suspension 5.0.0 --> 12.0.0)
- [x] Upgrades are categorised based on the ability to do them automatically or not
- [x] All entities are updated to the latest schemas
- [x] Metadata is deleted from the staging area
- [x] Project is re-exported

**Comment by ESapenaVentura** [comment]
Schemas in the submission:
- https://schema.humancellatlas.org/type/biomaterial/13.1.0/cell_suspension
- https://schema.humancellatlas.org/type/biomaterial/15.3.0/donor_organism
- https://schema.humancellatlas.org/type/biomaterial/14.3.0/cell_line
- https://schema.humancellatlas.org/type/biomaterial/10.2.0/specimen_from_organism
- https://schema.dev.data.humancellatlas.org/type/biomaterial/13.1.0/cell_suspension
- https://schema.humancellatlas.org/type/process/9.0.0/process
- https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.1.0/differentiation_protocol
- https://schema.humancellatlas.org/type/protocol/biomaterial_collection/6.1.0/dissociation_protocol
- https://schema.dev.data.humancellatlas.org/type/protocol/biomaterial_collection/3.0.0/enrichment_protocol
- https://schema.dev.data.humancellatlas.org/type/protocol/sequencing/6.1.0/library_preparation_protocol
- https://schema.dev.data.humancellatlas.org/type/protocol/sequencing/10.0.0/sequencing_protocol

**Comment by ESapenaVentura** [comment]
I have divided the types of changes into 2: 
- Minor changes: Can be automatically updated. Do not need to be looked into (Minor changes do not break backwards compatibility)
- Major changes: Will need to be manually looked.

The list goes as follows:

## Minor changes
- https://schema.humancellatlas.org/type/biomaterial/13.1.0/cell_suspension: https://schema.humancellatlas.org/type/biomaterial/13.3.0/cell_suspension
- https://schema.humancellatlas.org/type/biomaterial/15.3.0/donor_organism: https://schema.humancellatlas.org/type/biomaterial/15.6.1/donor_organism
- https://schema.humancellatlas.org/type/biomaterial/10.2.0/specimen_from_organism: https://schema.humancellatlas.org/type/biomaterial/10.5.0/specimen_from_organism
- https://schema.dev.data.humancellatlas.org/type/biomaterial/13.1.0/cell_suspension: https://schema.humancellatlas.org/type/biomaterial/13.3.0/cell_suspension
- https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.1.0/differentiation_protocol: https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.2.0/differentiation_protocol
- https://schema.humancellatlas.org/type/protocol/biomaterial_collection/6.1.0/dissociation_protocol: https://schema.humancellatlas.org/type/protocol/biomaterial_collection/6.2.0/dissociation_protocol
- https://schema.dev.data.humancellatlas.org/type/protocol/biomaterial_collection/3.0.0/enrichment_protocol: https://schema.humancellatlas.org/type/protocol/biomaterial_collection/3.1.0/enrichment_protocol
- https://schema.dev.data.humancellatlas.org/type/protocol/sequencing/6.1.0/library_preparation_protocol: https://schema.humancellatlas.org/type/protocol/sequencing/6.3.1/library_preparation_protocol
- https://schema.dev.data.humancellatlas.org/type/protocol/sequencing/10.0.0/sequencing_protocol: https://schema.humancellatlas.org/type/protocol/sequencing/10.1.0/sequencing_protocol
- https://schema.humancellatlas.org/type/process/9.0.0/process: https://schema.humancellatlas.org/type/process/9.2.0/process

## Major changes:
- https://schema.humancellatlas.org/type/biomaterial/14.3.0/cell_line: https://schema.humancellatlas.org/type/biomaterial/15.1.0/cell_line

**Comment by ESapenaVentura** [comment]
AI:

- [ ] Retrieve all the entities related to the submission
- [ ] With the map of updates, automatically update the entities with their correct schema
- [ ] Export the project

**Comment by ESapenaVentura** [comment]
### Retrieve all the entities related to the submission

Files were skipped, since we can't import them anyways (Also, skipping set-up of the IngestApi object)

```python
submission = api.get_submission('https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/5cdb0344d96dad000858fff4')
biomaterials = api.get_related_entities('biomaterials', submission, 'biomaterials')
biomaterials = list(api.get_related_entities('biomaterials', submission, 'biomaterials'))
protocols = list(api.get_related_entities('protocols', submission, 'protocols'))
processes = list(api.get_related_entities('processes', submission, 'processes'))
```

Map:
```
{'https://schema.dev.data.humancellatlas.org/type/biomaterial/13.1.0/cell_suspension': 'https://schema.humancellatlas.org/type/biomaterial/13.3.0/cell_suspension',
 'https://schema.dev.data.humancellatlas.org/type/protocol/biomaterial_collection/3.0.0/enrichment_protocol': 'https://schema.humancellatlas.org/type/protocol/biomaterial_collection/3.1.0/enrichment_protocol',
 'https://schema.dev.data.humancellatlas.org/type/protocol/sequencing/10.0.0/sequencing_protocol': 'https://schema.humancellatlas.org/type/protocol/sequencing/10.1.0/sequencing_protocol',
 'https://schema.dev.data.humancellatlas.org/type/protocol/sequencing/6.1.0/library_preparation_protocol': 'https://schema.humancellatlas.org/type/protocol/sequencing/6.3.1/library_preparation_protocol',
 'https://schema.humancellatlas.org/type/biomaterial/10.2.0/specimen_from_organism': 'https://schema.humancellatlas.org/type/biomaterial/10.5.0/specimen_from_organism',
 'https://schema.humancellatlas.org/type/biomaterial/13.1.0/cell_suspension': 'https://schema.humancellatlas.org/type/biomaterial/13.3.0/cell_suspension',
 'https://schema.humancellatlas.org/type/biomaterial/14.3.0/cell_line': 'https://schema.humancellatlas.org/type/biomaterial/15.1.0/cell_line',
 'https://schema.humancellatlas.org/type/biomaterial/15.3.0/donor_organism': 'https://schema.humancellatlas.org/type/biomaterial/15.6.1/donor_organism',
 'https://schema.humancellatlas.org/type/process/9.0.0/process': 'https://schema.humancellatlas.org/type/process/9.2.0/process',
 'https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.1.0/differentiation_protocol': 'https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.2.0/differentiation_protocol',
 'https://schema.humancellatlas.org/type/protocol/biomaterial_collection/6.1.0/dissociation_protocol': 'https://schema.humancellatlas.org/type/protocol/biomaterial_collection/6.2.0/dissociation_protocol'}

```

**Comment by ESapenaVentura** [comment]
## With the map of updates, update the entities

Biomaterials: 
```python
for b in biomaterials:
    b['content']['describedBy'] = mapped_schemas[b['content']['describedBy']]
    r = api.patch(b['_links']['self']['href'], json={'content': b['content']})
```

**Comment by ESapenaVentura** [comment]
cell_lines need to be updated with `publications.hca_publication = false`

**Comment by ESapenaVentura** [comment]
### Export the dataset

The dataset needs to be put manually into graph valid state. It has 2 files errors (No idea why, there is no message, but we are not exporting files).

The dataset has been graph-validated before so I am going to use the restart-submission script in the hca-ebi-dev repo to restart the submission

**Comment by ESapenaVentura** [comment]
The export is working - That means, system-wise, this is effectively a DCP2 dataset with the upload area cleaned.

**Comment by amnonkhen** [comment]
tasks:
- [ ] rename terra staging area
- [ ] re-export
- [ ] update DCP25 import form

**Comment by ESapenaVentura** [comment]
Re-export did not work.

Stuck in metadata export and there are several messages acknowledging data transfer error.

```
{"log":"2023-02-20 15:57:20,665 - TerraSubmissionExporter - ERROR - submission_uuid:0948a727-228f-4cfc-857e-6243c6aed08d - export_job_id:63f3985969335b24a7094647 - project_uuid:2043c65a-1cf8-4828-a656-9e247d4e64f1 - Rejecting message: {\"exportJobId\":\"63f3985969335b24a7094647\",\"submissionUuid\":\"0948a727-228f-4cfc-857e-6243c6aed08d\",\"projectUuid\":\"2043c65a-1cf8-4828-a656-9e247d4e64f1\",\"callbackLink\":\"/exportJobs/63f3985969335b24a7094647\",\"context\":{}} due to error: FileTransferCouldNotStart\n","stream":"stderr","time":"2023-02-20T15:57:20.666247229Z"}
```

**Comment by ESapenaVentura** [comment]
I have deleted the staging area and forced a re-export

**Comment by ESapenaVentura** [comment]
Log shows exported, but project shows up as exporting:
```
"2023-02-24 11:21:24.455  INFO 6 --- [pool-5-thread-1] o.h.i.s.monitor.SubmissionStateListener  : \tEnvelope '0948a727-228f-4cfc-857e-6243c6aed08d' -> State EXPORTED\n"
```

Will wait for a bit

**Comment by ofanobilbao** [comment]
On hold until after the HCA GM in July. Just needs time from Enrique to complete the update together probably with the Immune Cell Atlas

**Comment by ESapenaVentura** [comment]
it's actually been solved from what I can see in ingest/import forms/etc. 

Will close it
