### ISSUE TITLE
Triage new datasets - 56 new additions

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#993]
### To triage

- [x] [The Short Chain Fatty Acid Butyrate Imprints an Antimicrobial Program in Macrophages.](https://contribute.data.humancellatlas.org/projects/detail?uuid=4aee283b-ce74-4da6-ade5-d3dde75e7244)
- [x] [Single-cell transcriptomic analysis of tissue-resident memory T cells in human lung cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=e3a0bbc1-daaa-47e3-9661-a711ec7d205f)
- [x] [Single-Cell Transcriptomic Map of the Human and Mouse Bladders.](https://contribute.data.humancellatlas.org/projects/detail?uuid=6a1b7028-7e9f-43c3-95ee-7da67154a10a)
- [x] [Single-cell reconstruction of the adult human heart during heart failure and recovery reveals the cellular landscape underlying cardiac function.](https://contribute.data.humancellatlas.org/projects/detail?uuid=41aee104-4013-4f51-be3b-0d8fccaa3869)
- [x] [Sampling artifacts in single-cell genomics cohort studies](https://contribute.data.humancellatlas.org/projects/detail?uuid=81e5fdc9-7caf-4607-9908-04914bd8a9c9)
- [x] [Peripheral T cell expansion predicts tumour infiltration and clinical response.](https://contribute.data.humancellatlas.org/projects/detail?uuid=3b2ce506-276a-4bbc-a72d-325ef5725073)
- [x] [Layilin augments integrin activation to promote antitumor immunity. ](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc1558e6-e294-4fa8-b3df-5821fc89de26)
- [x] [Multidimensional study of the heterogeneity of leukemia cells in t(8;21) acute myelogenous leukemia identifies the subtype with poor outcome.](https://contribute.data.humancellatlas.org/projects/detail?uuid=260f11d4-5f2b-4ec1-a1b6-ad17ae40666a)
- [x] [Robust gene expression programs underlie recurrent cell states and phenotype switching in melanoma.](https://contribute.data.humancellatlas.org/projects/detail?uuid=49c54760-e21b-4eea-a513-0338230dacfb)
- [x] [Single-Cell Transcriptome Analysis of Colon Cancer Cell Response to 5-Fluorouracil-Induced DNA Damage.](https://contribute.data.humancellatlas.org/projects/detail?uuid=b222f2d6-14ff-4809-bec7-1991ed53210f) 
- [x] [Onco-fetal Reprogramming of Endothelial Cells Drives Immunosuppressive Macrophages in Hepatocellular Carcinoma.](https://contribute.data.humancellatlas.org/projects/detail?uuid=55a871d9-e4e8-480d-9896-bb8a4a3255e2)
- [x] [Single-nucleus transcriptome analysis reveals dysregulation of angiogenic endothelial cells and neuroprotective glia in Alzheimer's disease.](https://contribute.data.humancellatlas.org/projects/detail?uuid=459f014d-8918-427c-900f-155b7a5b307d) 
- [x] [Optimized design of single-cell RNA sequencing experiments for cell-type-specific eQTL analysis.](https://contribute.data.humancellatlas.org/projects/detail?uuid=524a3e78-16f0-47c1-b7ae-87d6d197da36) 
- [x] [Immune suppressive landscape in the human esophageal squamous cell carcinoma microenvironment.](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc658ea5-d8b1-4ea6-b487-14f4274f2a7c)
- [x] [Heterogeneous bone-marrow stromal progenitors drive myelofibrosis via a druggable alarmin axis.](https://contribute.data.humancellatlas.org/projects/detail?uuid=7955068e-4bf4-4338-b650-a65efd063b24)
- [x] [Single-cell analysis supports a luminal-neuroendocrine transdifferentiation in human prostate cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=a2d86d35-6ca9-4ab4-ad1e-1b778375a247)
- [x] [Neurological Manifestations of COVID-19 Feature T Cell Exhaustion and Dedifferentiated Monocytes in Cerebrospinal Fluid.](https://contribute.data.humancellatlas.org/projects/detail?uuid=c3854236-a53b-4e71-bafd-2a96d14e3a9c)
- [x] [Tissue-specific transcriptional imprinting and heterogeneity in human innate lymphoid cells revealed by full-length single-cell RNA-sequencing.](https://contribute.data.humancellatlas.org/projects/detail?uuid=9d140a8f-67cd-44dc-8ff4-3c9e9d917471)
- [x] [Single-cell analysis reveals transcriptomic remodellings in distinct cell types that contribute to human prostate cancer progression.](https://contribute.data.humancellatlas.org/projects/detail?uuid=2bec6068-fb1c-479a-9ce3-9b694f47c19d)
- [x] [Tumour heterogeneity and intercellular networks of nasopharyngeal carcinoma at single cell resolution.](https://contribute.data.humancellatlas.org/projects/detail?uuid=48676a12-aa47-4dea-be45-5b0111918bdb)
- [x] [Colorectal Cancer Stem Cell States Uncovered by Simultaneous Single-Cell Analysis of Transcriptome and Telomeres.](https://contribute.data.humancellatlas.org/projects/detail?uuid=247e0c3a-951f-4ef3-8ab3-2a4f6404b54f)
- [x] [Inhibitory CD161 receptor identified in glioma-infiltrating T cells by single-cell analysis.](https://contribute.data.humancellatlas.org/projects/detail?uuid=636cf470-688d-4456-b50f-2026fb41a56d)
- [x] [Divergent and self-reactive immune responses in the CNS of COVID-19 patients with neurological symptoms.](https://contribute.data.humancellatlas.org/projects/detail?uuid=20810c9b-c69f-4d71-ab54-ebd091729c1f)
- [x] [Single-Cell Characterization of the Immune Microenvironment of Melanoma Brain and Leptomeningeal Metastases.](https://contribute.data.humancellatlas.org/projects/detail?uuid=28c105fc-9992-4f1d-8f95-191f6853b1f5)
- [x] [Serial single-cell genomics reveals convergent subclonal evolution of resistance as early-stage breast cancer patients progress on endocrine plus CDK4/6 therapy.](https://contribute.data.humancellatlas.org/projects/detail?uuid=624e704d-f019-423c-a77d-d509efc0a9b6)
- [x] [Single-cell RNA-seq reveals fibroblast heterogeneity and increased mesenchymal fibroblasts in human fibrotic skin diseases.](https://contribute.data.humancellatlas.org/projects/detail?uuid=52e575e4-27ad-4773-9883-03bfa2055ebc)
- [x] [Dissecting the single-cell transcriptome network underlying esophagus non-malignant tissues and esophageal squamous cell carcinoma.](https://contribute.data.humancellatlas.org/projects/detail?uuid=b93f28df-d21b-46c7-b9c0-e401ad6a219c) - data available only upon request --> eligible priority 3
- [x] [Dissecting spatial heterogeneity and the immune-evasion mechanism of CTCs by single-cell RNA-seq in hepatocellular carcinoma.](https://contribute.data.humancellatlas.org/projects/detail?uuid=1e755972-d513-496e-9095-0e95ed361ae8) - manged access, fastq available from CNGB but no analysis files available --> eligible priority 3
- [x] [Single-nucleus chromatin accessibility and transcriptomic characterization of Alzheimer's disease.](https://contribute.data.humancellatlas.org/projects/detail?uuid=9099ffe6-8178-4762-8c82-2760c2fe4e59)
- [x] [Single-cell transcriptomic landscape reveals tumor specific innate lymphoid cells associated with colorectal cancer progression.](https://contribute.data.humancellatlas.org/projects/detail?uuid=acf55ae3-ecff-4e99-9b19-f5a01b73d5d9)
- [x] [Spatially organized multicellular immune hubs in human colorectal cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=6f03e4ad-9305-4bfa-a5b6-929ffb1d94bd)
- [X] [Single-cell RNA sequencing reveals the epithelial cell heterogeneity and invasive subpopulation in human bladder cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=6b8a711b-b6aa-4519-8a76-13c79e9902cb) 
- [x] [A single-cell and spatially resolved atlas of human breast cancers.](https://contribute.data.humancellatlas.org/projects/detail?uuid=6ee633a3-db85-4e05-8829-bd78558f43e2)
- [x] [Single-nucleus transcriptome analysis reveals cell-type-specific molecular signatures across reward circuitry in the human brain.](https://contribute.data.humancellatlas.org/projects/detail?uuid=562e0c9b-ea4e-4bdc-b3e2-f76331d6f36d)
- [x] [The landscape of tumor cell states and ecosystems in diffuse large B cell lymphoma.](https://contribute.data.humancellatlas.org/projects/detail?uuid=04fa5926-387e-4ab4-8969-7a1f4f9b1de4)
- [x] [Single-cell epigenomics reveals mechanisms of human cortical development.](https://contribute.data.humancellatlas.org/projects/detail?uuid=f06c9723-d963-466a-9777-962b3cfb6d5e)
- [x] [The serine proteases dipeptidyl-peptidase 4 and urokinase are key molecules in human and mouse scar formation.](https://contribute.data.humancellatlas.org/projects/detail?uuid=222a92d5-277b-489c-aad8-a680d1fd2b12)
- [x] [Defining the architecture of cerebrospinal fluid cellular communities in neuroinflammatory diseases](https://contribute.data.humancellatlas.org/projects/detail?uuid=4aaf736f-db79-464d-8bf1-d7f6bd8d83a0) - data/methods not available yet in preprint
- [x] [Resolving the difference between left-sided and right-sided colorectal cancer by single-cell sequencing. ](https://contribute.data.humancellatlas.org/projects/detail?uuid=e58e3c1f-bade-464e-a637-a64475236e9f)
- [x] [Altered cell and RNA isoform diversity in aging Down syndrome brains.](https://contribute.data.humancellatlas.org/projects/detail?uuid=45ff8e45-cd2a-47e8-ae7f-c537b65f3ead)
- [x] [Resolving the immune landscape of human prostate at a single-cell level in health and cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=3b45ae25-15b3-49cf-b8ce-854d6d845439)
- [x] [Temporal single-cell tracing reveals clonal revival and expansion of precursor exhausted T cells during anti-PD-1 therapy in lung cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=e0035b31-7c6d-431c-90ce-e02b43894ca3)
- [x] [Liver stromal cells restrict macrophage maturation and stromal IL-6 limits the differentiation of cirrhosis-linked macrophages.](https://contribute.data.humancellatlas.org/projects/detail?uuid=5c7ab401-4d87-43ea-a88f-416ad4d8ba3a)
- [x] [Mapping transcriptomic vector fields of single cells.](https://contribute.data.humancellatlas.org/projects/detail?uuid=ab897789-b2b0-4750-b5e0-6ec3885d2936)
- [x] [Single-cell transcriptomics analysis reveals intratumoral heterogeneity and identifies a gene signature associated with prognosis of hepatocellular carcinoma. ](https://contribute.data.humancellatlas.org/projects/detail?uuid=05a307a7-87a1-4652-9c47-b3ca2ff71796) - data available only upon request  --> eligible priority 3
- [x] [Clonally heritable gene expression imparts a layer of diversity within cell types](https://contribute.data.humancellatlas.org/projects/detail?uuid=57e84dbd-7d27-489b-bea3-d58c3ebe3960)
- [x] [Schwann cells contribute to keloid formation.](https://contribute.data.humancellatlas.org/projects/detail?uuid=32f45af8-f71b-454c-afac-64a4c44c2c2f). @anu-shiva 
- [x] [Single-Cell RNA-seq Reveals a Developmental Hierarchy Super-Imposed Over Subclonal Evolution in the Cellular Ecosystem of Prostate Cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=e5f2a945-9ee3-44fb-8839-671a84f1bbf3) - [data](https://ngdc.cncb.ac.cn/gsa-human/browse/HRA000823) cell count matrices available only upon request --> eligible priority 3
- [x] [Cross-tissue immune cell analysis reveals tissue-specific features in humans.](https://contribute.data.humancellatlas.org/projects/detail?uuid=3e3c6938-50fd-465f-b092-5bba10eb42ca)
- [x] [Immune disease risk variants regulate gene expression dynamics during CD4<sup>+</sup> T cell activation.](https://contribute.data.humancellatlas.org/projects/detail?uuid=c0e529da-1a1c-42ec-ad6f-db2797c293e8)
- [x] [Single-cell RNA-sequencing of peripheral blood mononuclear cells reveals widespread, context-specific gene expression regulation upon pathogenic exposure.](https://contribute.data.humancellatlas.org/projects/detail?uuid=5ff9d455-5b27-4d01-a10a-26a719a86f4f)
- [x] [Single-cell transcriptional regulation and genetic evolution of neuroendocrine prostate cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=760e943f-2a70-4178-8431-4ba79cdbd7ec)
- [x] [Single-cell analyses define a continuum of cell state and composition changes in the malignant transformation of polyps to colorectal cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=eaa83612-4307-45f4-8d61-ca1605e63eef)
- [x] [Single-cell and bulk transcriptome sequencing identifies two epithelial tumor cell states and refines the consensus molecular classification of colorectal cancer.](https://contribute.data.humancellatlas.org/projects/detail?uuid=6471ce64-3e50-4f91-9602-bd85addbeac2)
- [x] [Single-Nuclei RNA Sequencing of 5 Regions of the Human Prenatal Brain Implicates Developing Neuron Populations in Genetic Risk for Schizophrenia.](https://contribute.data.humancellatlas.org/projects/detail?uuid=f42cf755-6e85-451a-b035-890e4d898347)
- [x] [A single-cell atlas of the multicellular ecosystem of primary and metastatic hepatocellular carcinoma.](https://contribute.data.humancellatlas.org/projects/detail?uuid=b5a04da1-7c8c-4032-a64a-b4bc1dd0bc73)

**Comment by ofanobilbao** [comment]
5th on the list: https://contribute.data.humancellatlas.org/projects/detail?uuid=81e5fdc9-7caf-4607-9908-04914bd8a9c9. I believe this is the pre-print for a paper that we already pushed to DCP: https://contribute.data.humancellatlas.org/projects/detail?uuid=5b328561-4a97-40ac-b7ad-6a90fc59d374&tab=project. Probably a wrangler will need to look into it. But this might keep happening. How do we want to deal with it? Do we include both DOI in the publication tab and only keep one project entry? We probably should right? Would the discovery script deal well with it?

**Comment by ofanobilbao** [comment]
7th on the list: https://contribute.data.humancellatlas.org/projects/detail?uuid=cc1558e6-e294-4fa8-b3df-5821fc89de26&tab=project. I've not marked for Catalogue yet. Want to confirm eligibility with the wranglers and Gabs. It all seems like Disease data

**Comment by ofanobilbao** [comment]
8th on the list: https://contribute.data.humancellatlas.org/projects/detail?uuid=260f11d4-5f2b-4ec1-a1b6-ad17ae40666a&tab=project. I've not marked for Catalogue yet. Want to confirm eligibility with the wranglers and Gabs. It all seems like Disease data

**Comment by idazucchi** [comment]
8th on the list: https://contribute.data.humancellatlas.org/projects/detail?uuid=260f11d4-5f2b-4ec1-a1b6-ad17ae40666a&tab=project. I've not marked for Catalogue yet. Want to confirm eligibility with the wranglers and Gabs. It all seems like Disease data, it's managed access and it's just one donor
