### ISSUE TITLE
Single-cell protein activity analysis identifies recurrence-associated renal tumor macrophages

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#994]
Single-cell protein activity analysis identifies recurrence-associated renal tumor macrophages

### Project short name:
Califano-Human-10x3pv2

### Link to Ingest

* https://contribute.data.humancellatlas.org/projects/detail?uuid=95d058bc-9cec-4c88-8d2c-05b4a45bf24f&tab=project

### Associated files

* Google Drive: https://drive.google.com/drive/folders/15aZrDjJyyf0cI7Rdv77QJBRwq-xaA_4U

### Published study links

* Paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8479759/

* Accessioned data:

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
No link between donors in supplementary table 1 and raw and analysis files available in their github. Sent an email.

------

> Dear Dr. Charles G. Drake and Dr. Andrea Califano, 

I am writing on behalf of the Human Cell Atlas Data Coordination Platform and Human Cell Atlas Kidney Biological Network. I am currently wrangling your paper “Single-cell protein activity analysis identifies recurrence-associated renal tumor macrophages” (https://doi.org/10.1016/j.cell.2021.04.038) for submission into the HCA DCP and had a couple questions about the paper. 

I am attempting to match up individual donors from Supplemental Table 1 (https://ars.els-cdn.com/content/image/1-s2.0-S0092867421005730-mmc1.pdf) to the separate gene expression files in the singlecell_rawdata GitHub folder (https://github.com/Aleksobrad/single-cell-rcc-pipeline/tree/master/singlecell_rawdata). Would you be able to help with this linking? 

Warm regards,
Wei Kheng
On Behalf of the HCA DCP Ingestion Service

**Comment by Wkt8** [comment]
They sent back an email and I've curated the data! Needs a secondary review.

**Comment by idazucchi** [comment]
Hello! I'm done with the secondary review :)

- donor alive at collection should be yes 
> Tissue were obtained from 11 adult patients with clear cell renal carcinoma undergoing nephrectomy to treat primary, non-metastatic disease

- specimen, dissociation, cell suspension, library prep, sequencing, analysis protocol names all have underscores, maybe you can swap them with spaces?

- dissociation protocol: you can add the dissociation kit 

- enrichment: the protocol name is missing

- cell suspension: the selected cell type for CD45+ cells should be `hematopoietic compartment`

- library prep: primer should be poly-dT

- analysis protocol : you can fill out the derivation process for `processed_matrix_generation`

- analysis files: I think `singlecell_gex_viper_analysis.R` is actually an R script, you can include `cd45neg_merged_seurat_viper.rds` and `cd45pos_merged_seurat_viper.rds` instead

- project:
   - add the link to the git hub page?
   - add yourself as a data curator

**Comment by Wkt8** [comment]
Exported, and product import form filled!

**Comment by ofanobilbao** [comment]
@gabsie again why is this in stalled?

**Comment by ofanobilbao** [comment]
Closing as per conversation in Operations Review Meeting today. There does not seem to be anything wrong with this dataset
