### ISSUE TITLE
PRJNA705464 - ImmuneLandscapeccRCC

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#996]
### Project short name:
ImmuneLandscapeccRCC

### Primary Wrangler:
Ida
### Link to Ingest

* https://contribute.data.humancellatlas.org/projects/detail?uuid=12f32054-8f18-4dae-8959-bfce7e3108e7&tab=project

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/17xEO4jStfc_k80UukrNC3XLA7d41t94o)

### Published study links

* Paper: [Single-cell sequencing links multiregional immune landscapes and tissue-resident T cells in ccRCC to tumor topology and therapy efficacy](https://www.sciencedirect.com/science/article/pii/S1535610821001653?via%3Dihub)

* Accessioned data: [PRJNA705464](https://www.ncbi.nlm.nih.gov/Traces/study/?WebEnv=MCID_63d1009838f314290a7718c2&query_key=1&GALAXY_URL=https%3A%2F%2Fusegalaxy.org%2Ftool_runner%3Ftool_id%3Dsra_source), [SRZ190804](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?analysis=SRZ190804)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
Review:

Donor:
- Medications should be separated with commas

Sequence files:
- Processes should be grouped by SRR accession, and lane indexes (which are indicated) are there to distinguish between replicates

Other than that, LGTM!!

**Comment by idazucchi** [comment]
I applied the comments and I will write to the authors to check the sequencing machine. Also asking about cellxgene

**Comment by ESapenaVentura** [comment]
@arschat to chat with @idazucchi to start wrangling this dataset for cellxgene

**Comment by arschat** [comment]
Accessed files needed from 20+gb rds object, through codon-cluster.

Attaching a small markdown with guidance on how to do this, for future reference.

Proceeding with load all into an h5ad for the jupyter notebook.
[https://app.zenhub.com/files/261790554/b0bc0844-b9f8-4ed1-9e2e-7c83b999f7b6/download](https://app.zenhub.com/files/261790554/b0bc0844-b9f8-4ed1-9e2e-7c83b999f7b6/download)

**Comment by arschat** [comment]
Converted both matrices to csr and size reduced to 5.6gb. Uploading h5ad file in [drive folder](https://drive.google.com/drive/folders/17xEO4jStfc_k80UukrNC3XLA7d41t94o?usp=sharing).

**Comment by arschat** [comment]
collection has been published on CxG
https://cellxgene.cziscience.com/collections/3f50314f-bdc9-40c6-8e4a-b0901ebfbe4c
