### ISSUE TITLE
GSE145927 - ChimerismKidneyTransplantReject

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#997]
### Project short name:
ChimerismKidneyTransplantReject

### Primary Wrangler:
Ida

### Secondary Wrangler:
@arschat 

### Link to Ingest

* https://contribute.data.humancellatlas.org/projects/detail?uuid=4ef86852-aca0-4a91-8522-9968e0e54dbe&tab=project

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1n6RRpTw-403MvUCxybcjIBzBTeCEIc9d)

### Published study links

* Paper: [Harnessing Expressed Single Nucleotide Variation and Single Cell RNA Sequencing To Define Immune Cell Chimerism in the Rejecting Kidney Transplant](https://jasn.asnjournals.org/content/jnephrol/31/9/1977.full.pdf?with-ds=yes)

* Accessioned data: [GSE145927](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE145927)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
missing metadata on the donor pre/post transplant

**Comment by idazucchi** [comment]
one donor donated a sample both pre and post kidney transplant --> I'm not sure of how I want to represent this

**Comment by idazucchi** [comment]
I've sent an email to the authors to get the missing information - in the meanwhile I validated the dataset and it's ready for secondary review

I will update with the correct information as soon as the authors reply

**Comment by idazucchi** [comment]
from Arsenios:
## secondary review comments

project: middle names are not between commas
		 same grand ids are not identical. possible typos?

filenames: matching filenames in spreadsheet & aws ls s3://org-hca-data-archive-upload-prod/cceb5d52-c201-41d5-9554-349ff90659cc/ √

speciment: donor numbering in description is misguiding
		   inconsistency between GEO timepoint and paper (GEO: 2 years and 8 months/ 2 years and 9 months, paper: 2 years and 7 months ~ 945 days / one month after ~ 974 days)

discociation protocol: mechanical_dissociation is not mentioned in cell suspension or anywhere

sequence files: library protocol is the other way round (biopsy1-5 have 10x_3' should have 10x_5'/ biopsy6-7 have 10x_5' should have 10x_3')

**Comment by idazucchi** [comment]
I've applied the suggestions and graph validated, but I still need some information from the authors. I will ping them again today

**Comment by idazucchi** [comment]
I will ping the authors again but if they don't reply can we publish the project without the genome version?

**Comment by idazucchi** [comment]
Project exported correctly, I checked the google bucket
- [ ] fill import form

**Comment by idazucchi** [comment]
do we want a new term for transplant rejection?

**Comment by ofanobilbao** [comment]
Only to do the update if capacity allows

**Comment by idazucchi** [comment]
verified in the browser

**Comment by idazucchi** [comment]
- the cell barcode lenght is wrong for 10x v2

**Comment by idazucchi** [comment]
verified in the browser
