### ISSUE TITLE
GSE145173 - Decoding myofibroblast origins in human kidney fibrosis

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#998]
GSE145173 - Decoding myofibroblast origins in human kidney fibrosis

### Project short name:
Kramann-Human-Smartseq2

### Primary Wrangler:
Arsenios Chatzigeorgiou @arschat 

### Link to Ingest

* https://contribute.data.humancellatlas.org/projects/detail?uuid=128952c1-1906-4746-b4dd-6a10d1ff52d0&tab=project

### Associated files

* Google Drive:
https://drive.google.com/drive/folders/1aZdaFpbHb8R7LKEIPZ9WnLdVNIODIjv_?usp=sharing

### Published study links

* Paper: https://www.nature.com/articles/s41586-020-2941-1 

* Accessioned data: [GSE145173](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE145173), [GSE144528](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144528)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Number of mice samples not clear, neither for 10x data nor for Smart-Seq2. Contacted corresponding author to clarify.

**Comment by arschat** [comment]
Deleted ncbi-cloud mouse data.

> locate the sra_metadata_UUID.csv file that was created on cloud syncing.
> download file locally
`aws s3 cp s3://hca-ncbi-cloud-data/sra_metadata_b2338de6-2faa-4d5b-b731-4a8ba54a3212.csv .`
> validate that the submission column has the correct SRA number(s)
`awk -F',' '{ print $43}' sra_metadata_b2338de6-2faa-4d5b-b731-4a8ba54a3212.csv | uniq`
> save sra run IDs
`awk -F',' '{ print $1}' sra_metadata_b2338de6-2faa-4d5b-b731-4a8ba54a3212.csv > rm_ncbi_cloud_s3.csv`
> read file with sra run IDs and delete corresponding directories in ncbi-cloud storage
`while read p; do aws s3 rm s3://hca-ncbi-cloud-data/$p --recursive; done < rm_ncbi_cloud_s3.csv`
> delete sra_metadata_UUID.csv
`aws s3 rm s3://hca-ncbi-cloud-data/sra_metadata_b2338de6-2faa-4d5b-b731-4a8ba54a3212.csv`

**Comment by anu-shiva** [comment]
@arschat to contact contributors for donor/specimen info

**Comment by arschat** [comment]
Three follow-up emails has been sent from February, without an answer.
See [here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/t6M_26xNNsA/m/c3rn33OYBQAJ) and [here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/Q5tSOPyNNfk/m/qOp5-eSvAAAJ)
