### ISSUE TITLE
GSE151671 - SuryawanshiKidneyAllografts

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#999]
### Project short name:
SuryawanshiKidneyAllografts

### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Link to Ingest

* https://contribute.data.humancellatlas.org/projects/detail?uuid=6e522b93-9b70-4f0c-9990-b9cff721251b&tab=project

### Associated files

* Google Drive: [foldr](https://drive.google.com/drive/folders/1vwlQS3dNAvlWggN5-uO66KYdl6Ne0Rl3)

### Published study links

* Paper: [Detection of infiltrating fibroblasts by single-cell transcriptomics in human kidney allografts](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0267704)

* Accessioned data:  [GSE151671](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE151671)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
preparing the fastq files `16c73b63-f679-4f67-9d54-117f588171da`

**Comment by idazucchi** [comment]
**Donor/Specimens**
there are two kidney transplant receivers that donated part of their transplant kidney (biopsies)
I'm not sure if I captured the disease status correctly for the specimen, I tried to capture the health status at the time of the biopsy. (see the result section of the paper)

**Comment by arschat** [comment]
## Analysis Protocol
Protocol ID `matrix generation` has spaces

## Analysis File
`Matrix cell count` has 6001 cells, but matrix contains 6000 cells (first column is gene names)

**Comment by ofanobilbao** [comment]
@gabsie why is this in the stalled column? It is public in DCP already

**Comment by gabsie** [comment]
something has happened here which I have no explanation for :), I wouldn't reopen just like that - no comment as well.

**Comment by ofanobilbao** [comment]
As per Operations Review meeting today, closing as it does not seem as there was anything wrong with this dataset
